### ISSUE TITLE
Allow to import Typescript files from other packages

### ISSUE THREAD

**Issue by lcswillems** [zeit/next.js#9303] opened 2019-11-04 08:25 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

When I include a Typescript file from another package, I get this error:

`You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders`

## Describe the solution you'd like

I would like to be able to import Typescript files from other packages.

**Comment by timneutkens** [comment] 2019-11-04 09:36
Duplicate of #706

**Closed by timneutkens** 2019-11-04 09:36 UTC

**Comment by balazsorban44** [comment] 2022-01-31 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
