### ISSUE TITLE
Large css/scss imports don't work with new granularChunks option

### ISSUE THREAD

**Issue by marbemac** [zeit/next.js#8314] opened 2019-08-10 05:06 UTC
# Bug report

## Describe the bug

The recently introduced `experimental.granularChunks` option (#7696) is incredible, however it's not handling large css / scss files well. I'm not terribly familiar with the next internals, so this could be a symptom of a larger problem, but so far everything except our large scss imports are working great.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone https://github.com/marbemac/nextjs-granular-modules-bug
2. `yarn` and `yarn dev`
3. open `http://localhost:3000`
4. see error in developer tools

## Expected behavior

Should be able to import large css/scss files while using the `granularChunks` option.

## Screenshots

<img width="1673" alt="Screen Shot 2019-08-10 at 12 02 15 AM" src="https://user-images.githubusercontent.com/847542/62817833-8c51a380-bb02-11e9-86a6-b9f60023fe31.png">

## System information

- OS: macOS
- Version of Next.js: 9.0.4-canary.2

## Additional context

Able to work around it for now by modifying the lib cacheGroup in the webpack config to ignore files loaded via `css-loader`.

```ts
webpack: (c) => {
  if (c.optimization.splitChunks.cacheGroups) {
    c.optimization.splitChunks.cacheGroups.lib.test = module => {
      const identifier = module.identifier();
      return (
        module.size() > 160000 && /node_modules[/\\]/.test(identifier) && !/^.+css-loader\//.test(identifier)
      );
    };
  }

  return c;
},
```

**Comment by slorber** [comment] 2019-08-15 17:44
Hey, don't know at all if this is related, but Gatsby had to disable CSS code splitting due to problems related to css loading order. Maybe Next is doing to have the same issues with the new granular option. cc @atcastle you may find it useful to see how Gatsby configure splitChunks: https://github.com/gatsbyjs/gatsby/issues/16661

**Comment by Timer** [comment] 2019-08-15 18:18
Thanks for the report! We'll keep this in mind before we make the new behavior the default.

Do note, we have full intentions to split CSS and not use a single bundle! We'll be sure to solve any sort of ordering issue(s).

**Comment by Timer** [comment] 2019-12-13 13:58
This should be fixed in the latest canary.

**Closed by Timer** 2019-12-13 13:58 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-30 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
