### ISSUE TITLE
router.query becomes empty after page refresh

### ISSUE THREAD

**Issue by ivanhoe-dev** [zeit/next.js#10534] opened 2020-02-14 13:46 UTC
When I redirect from page A to page B by `next/link`, the router.query (from `next/router`) contains the data I want. However, when I refresh page B on browser, the router.query becomes empty. Is this a bug? It works fine in react-router...

**Comment by kachkaev** [comment] 2020-02-14 13:50
👋 @ivanhoe-dev could you please provide an example with reproduction? Next.js maintainers won't be able to help if the issue does not follow one of the [provided templates](https://github.com/zeit/next.js/tree/canary/.github/ISSUE_TEMPLATE).

**Comment by timneutkens** [comment] 2020-02-14 13:54
Sounds similar to https://github.com/zeit/next.js/issues/10521

Closing this as it doesn't follow the issue template.

**Closed by timneutkens** 2020-02-14 13:54 UTC

**Comment by balazsorban44** [comment] 2022-01-30 13:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
