### ISSUE TITLE
SSR and SSG pages when browsed with a trailing slash results in 404

### ISSUE THREAD

**Issue by gauravkrp** [zeit/next.js#13168] opened 2020-05-20 22:43 UTC
# Bug report
I'm using Next 9.4 for my website - https://accessgatelabs.com
All pages are SSR and SSG at build and when they are browsed with a trailing slash are resulting in 404

## Describe the bug
On home page - https://accessgatelabs.com , when you click about page link your are redirected immediately (thanks to <Link> preloading) to https://accessgatelabs.com/about
But when you try to access https://accessgatelabs.com/about/ - it results in 404.
It is a **very basic feature** and should be present by default as everywhere you share your site url or if the site is crawled by web crawlers, they usually add a trailing slash at the end of page url. 
Thus in all such typical scenario, the page will result in a 404, which is **worst experience**. 

## To Reproduce
SSR and SSG any page in Next.js
Then navigate to your pages with a trailing slash at the end of url.

## Expected behavior
Page url when browsed with a trailing slash at the end should point/redirect to the page instead of a 404. For e.g. https://accessgatelabs.com/about/ should open the page at https://accessgatelabs.com/about

Please @Timer  resolve the issue at the earliest. This should be a must-have feature for ssr applications.

**Comment by timneutkens** [comment] 2020-05-21 12:05
Duplicate of #5214

> Please @Timer resolve the issue at the earliest. This should be a must-have feature for ssr applications.

If you want us to prioritize features for you feel free to reach out to enterprise@vercel.com to see if we can help you with dedicated support.

**Closed by timneutkens** 2020-05-21 12:05 UTC

**Comment by balazsorban44** [comment] 2022-01-30 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
