### ISSUE TITLE
Page open from Link not use assetPrefix to load chunked js when using granularChunks

### ISSUE THREAD

**Issue by superkoh** [zeit/next.js#9222] opened 2019-10-28 07:35 UTC
# Bug report

## Describe the bug

Page open from Link not use assetPrefix to load chunked js when using granularChunks

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Let's say we have a site with www.example.com

1. add granularChunks in next.config.js
2. set an assetPrefix in next.config.js, like static.example.com
3. build and run in production mode
4. click link implemented by <Link/> (e.g. `<Link href={{pathname: '/index'}} as="/">link</Link>`)
5. index.js will load from static.example.com and other js will load from www.example.com

## Expected behavior

All js should be loaded from static.example.com

## System information

- OS: [Linux]
- Browser (if applies) [chrome]
- Version of Next.js: [9.1.1]

**Comment by Timer** [comment] 2019-10-28 13:57
Duplicate of https://github.com/zeit/next.js/issues/8989

**Closed by Timer** 2019-10-28 13:57 UTC

**Comment by balazsorban44** [comment] 2022-01-31 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
