### ISSUE TITLE
the index page keep generate static html on each request

### ISSUE THREAD

**Issue by yjisme** [zeit/next.js#10963] opened 2020-03-11 09:55 UTC
add `page/index.js` to empty project, and includes these code:

```
export default ({ number }) => {
  console.log("index render");
  return (
    <div>
      <h1>Index : {number}</h1>
    </div>
  );
};

export async function getStaticProps() {
  console.log("index getStaticProps");
  return {
    props: {
      number: 1
    }
  };
}
```

then I use `next build` command, it's print correctly in console.

but when I request `http://localhost:3000/` in browser, the console log repeat every request except the first request.

i check `.next` dir, the `index.html` generated correctly, but why the request trigger it generate again?

but when I copy the code to any other page, there is no problem, no console words out

did i miss something?

**Comment by fancierpj0** [comment] 2020-03-12 12:20
i have the same problem with u~~~~

**Comment by timneutkens** [comment] 2020-03-12 12:24
This was fixed on next@canary.

**Closed by timneutkens** 2020-03-12 12:24 UTC

**Comment by balazsorban44** [comment] 2022-01-30 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
