### ISSUE TITLE
validate Router.push params

### ISSUE THREAD

**Issue by hanford** [zeit/next.js#4141] opened 2018-04-11 19:54 UTC
When using `Router.push(url, as, { shallow })` the `Router` should validate that `as` is a String and warn the consumer. 

As a consumer, I would expect `Router.push` to gracefully handle / fallback to setting `as = url` so I can simply invoke `Router.push(url, {shallow: true})` but 🤷‍♀️

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1. invoke `Router.push` like `Router.push(url, { shallow: true })`

## Context
If doing ^ it can stop the URL of your next app from updating even when navigating deep into different routes. 

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    5.1    |

**Comment by timneutkens** [comment] 2018-04-11 19:57
`url` and `as` actually accept a string or object. But `require('url').format({shallow: true})` would hold `''`, so we need to check for an empty string and warn/fail (@arunoda can you give your option on warn/fail?) to make it clear to the user.

I don't want to change the Router API at this point, but providing a clear message would go a long way in preventing issues like the one Eaze was experiencing 🙏

**Comment by arunoda** [comment] 2018-04-11 23:30
The idea we had when designing this is to create an explicit API without any parameter overloading. And `as` could be an object with a parsed URL object.

I agree with @timneutkens on not to change the routing API. But, it's nice to warn user in this case.

**Comment by sebas5384** [comment] 2018-06-06 23:06
I just wanted to let you know that I had the same expectation as @hanford

**Comment by timneutkens** [comment] 2019-08-09 15:31
Afaik this was landed in Next.js 9.

**Closed by timneutkens** 2019-08-09 15:31 UTC
Labels: Type: Enhancement, priority: high

**Comment by balazsorban44** [comment] 2022-01-31 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
