### ISSUE TITLE
Page is reloading for dynamic route even though shallow=true

### ISSUE THREAD

**Issue by rahul3103** [zeit/next.js#10736] opened 2020-02-28 09:58 UTC
# Page is reloading for dynamic route even though shallow=true

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

https://codesandbox.io/s/ecstatic-buck-2t2tr

On the `/` when you click the button the url is changing and the page is not reloading and on closing the url gets back to `/`. But when I am trying the same with dynamic route :

I have created dynamic route `/class/[slug]/[uid]` and `/lesson/[slug]/[uid]`

Now I want the same behavior here but the page is reloading

Open url `/class/test/test1` and click on button the modal opens but page reload

`Router.push("/class/test/test1", "/lesson/test/test1", { shallow: true });` the page gets reloaded after render

## Expected behavior

Page should not reload

**Comment by ijjk** [comment] 2020-02-28 16:32
Hi, it looks like this is due to an invalid `href` being passed to `next/router` specifically this bit `Router.push("/class/test/test1", "/lesson/test/test1", { shallow: true });` `href` needs to be the page from your pages folder e.g. `Router.push("/lesson/[slug]/[uid]", "/lesson/test/test1", { shallow: true });`

See more info in our [docs](https://nextjs.org/docs/api-reference/next/link#dynamic-routes).

I'm gonna close this since it doesn't appear to be an issue with Next.js. If you are still having trouble with this feel free to reply with additional details

**Closed by ijjk** 2020-02-28 16:32 UTC

**Comment by rahul3103** [comment] 2020-03-02 04:05
@ijjk How it's working at `Router.push("/", "/about", { shallow: true });` . Similarly, I want to display some other URL when that button is clicked but not reload the page. How can I do that. I want my pop up to come and URL should change and when I close it should go back.

```
url - The URL to navigate to. This is usually the name of a page
as - Optional decorator for the URL that will be shown in the browser. Defaults to url
options - Optional object with the following configuration options:
shallow: Update the path of the current page without rerunning getInitialProps. Defaults to false
```

I thought in the docs its written just to show in the browser.

**Comment by ijjk** [comment] 2020-03-02 14:51
The page reloading when using `Router.push` or `next/link` is caused by an invalid page being provided and it failing to load so it falls back to a server-side transition. You are able to achieve what you are wanting as long as you provide a valid page (existing in your `pages` folder) for the `href` value

**Comment by rahul3103** [comment] 2020-03-03 06:53
@ijjk Sorry, for bugging you again. But, I am providing the same `href` which is `/class/test/test1` and I am on that same route but I am providing the `as` different just like above. This `href` is correct `/class/test/test1`.

**Comment by ijjk** [comment] 2020-03-03 15:42
The `/class/test/test1` `href` is invalid, you need to specify the page from your pages folder which should be `/class/[slug]/[uid]` or `/lesson/[slug]/[uid]` depending on which `as` value you are providing since the dynamic route needs to match the provided `as` value. Please take a look at our documentation for this here: https://nextjs.org/docs/api-reference/next/link#dynamic-routes

**Comment by balazsorban44** [comment] 2022-01-30 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
