### ISSUE TITLE
on-demand-entries-pings change cookie so l can't use cookie to keep login

### ISSUE THREAD

**Issue by Ai01** [zeit/next.js#3879] opened 2018-02-24 07:31 UTC
![image](https://user-images.githubusercontent.com/18245929/36627008-82c2a5a4-1977-11e8-8d80-3b96f25601d7.png)

![image](https://user-images.githubusercontent.com/18245929/36627017-8ebd52aa-1977-11e8-883b-982a183ea9ae.png)

you can see. the post request success. so l get the session from back-end. but after that, the on-demand-entries-ping change the cookies. so l lost the login session message.
anybody meet the same questions ? please give me some help.  thank you very much.

**Comment by liweinan0423** [comment] 2018-02-24 07:51
it should be caused by 
https://github.com/zeit/next.js/blob/85f341c9d834114be1127cf73a04bc3517cc2f67/client/on-demand-entries-client.js#L19-L22

**Comment by Ai01** [comment] 2018-02-24 08:13
@liweinan0423 how can l fix this problem? l didn't find the way to change the header in on-demand-entries-client.js

**Comment by liweinan0423** [comment] 2018-02-24 08:19
https://github.com/zeit/next.js/commit/85f341c9d834114be1127cf73a04bc3517cc2f67#diff-9a3b2205470e098182c19414ab4d27f2R21

@timneutkens why did you change 'same-origin' to 'omit'?

**Comment by Ai01** [comment] 2018-02-24 09:47
@liweinan0423 after adding `withCredentials: true` and the cors header's in my backend. l found this problem go away


 maybe this is the key and this is not nextJs's fault. l'll try to find where the cookie come from

**Comment by timneutkens** [comment] 2018-02-24 10:55
@liweinan0423 it was actually @arunoda that changed it 🕵️

**Comment by brycejacobs** [comment] 2018-03-06 06:34
Are there any updates on this? Losing cookies whenever the request fires off.

**Comment by arunoda** [comment] 2018-03-06 12:12
@Ai01 @brycejacobs We removed this to support our multi-zones feature. Anyway, we only omit sending cookies for `on-demand-entries` request only. (Which is dev only and user should not handle it)

I just checked and this doesn't clear cookies but simply don't send cookies with on-demand-entries. For any other request after that, it'll send cookies.

I am closing this due to ^^ reason. But if you feel otherwise, create a sample repo with the case and re-open this issue.

**Closed by arunoda** 2018-03-06 12:12 UTC
