### ISSUE TITLE
Dynamic import is loading all dependency even it's lazy loaded. Next 7.0.0

### ISSUE THREAD

**Issue by ptdede** [zeit/next.js#5221] opened 2018-09-20 06:44 UTC
# Bug report

## Describe the bug

on "next": "^7.0.0", dynamic import is importing ALL of the module that is supposed to lazy loaded. unlike "next": "^6.1.2", the module is correctly loaded on demand.

## To Reproduce

```
import dynamic from "next/dynamic";
const TextSideSlider: any = dynamic(
    import(/* webpackChunkName: 'TextSideSlider' */"./TextSideSlider") as any,
);
```

this component is used only on route /b. But, on route /a it's already loaded.

## Expected behavior
Dynamic imported module loaded when it's needed. like on next 6.1.2.

## Screenshots
"next": "^6.1.2"
on route /a
TextSideSlider component is not loaded.
<img width="580" alt="screen shot 2018-09-20 at 14 25 08" src="https://user-images.githubusercontent.com/3388701/45800105-694bb480-bce2-11e8-95ed-a8da6c070b83.png">

on route /b
TextSideSlider component is loaded correctly on demand.
<img width="582" alt="screen shot 2018-09-20 at 14 25 41" src="https://user-images.githubusercontent.com/3388701/45800213-c21b4d00-bce2-11e8-8c9e-7f07159d6f79.png">

"next": "^7.0.0",
on route /a
TextSideSlider component is already loaded
<img width="582" alt="screen shot 2018-09-20 at 14 28 30" src="https://user-images.githubusercontent.com/3388701/45800278-00b10780-bce3-11e8-96c8-cd6baa2f3708.png">

on route /b
nothing changed
<img width="582" alt="screen shot 2018-09-20 at 14 28 42" src="https://user-images.githubusercontent.com/3388701/45800291-0a3a6f80-bce3-11e8-8a10-47d7ed1e707f.png">

## System information
 - OS: macOS
 - Browser chrome
 - Version of Next.js: 6.1.2 & 7.0.0

**Comment by tusbar** [comment] 2018-09-20 08:18
Probably dupe of #5213

**Comment by ptdede** [comment] 2018-09-20 08:42
@tusbar Yes.. Maybe it's related? 
I tried to `rm -rf node_modules/.cache`, `rm -rf .next`, then `npm run build`. but the all dynamic module is still loaded initially in my project. 

using your repo it's correctly loaded the dynamic component on demand when i do `rm -rf node_modules/.cache`. and remove <Message> component inside page/index.js
the message component chunk only loaded on /about page.

**Comment by dnakov** [comment] 2018-09-20 14:54
This worked for me:
```
import dynamic from "next/dynamic";
const TextSideSlider: any = dynamic(
    () => import(/* webpackChunkName: 'TextSideSlider' */"./TextSideSlider") as any,
);
```

**Comment by ptdede** [comment] 2018-09-20 15:14
@dnakov well i just try with @tusbar repo. I confirm it works. hahaha. But not in my case. I still try to figure it out whats wrong with my code. comeback later after found out what's wrong.

**Comment by ptdede** [comment] 2018-09-20 15:49
@dnakov Oh wait. i didn't pay attention to your code. you're trying to return anonymous function within dynamic function? my typescript compiler is complaining about that 
```
Argument of type '() => any' is not assignable to parameter of type 'Promise<ComponentType<{}>>'. 
Property 'then' is missing in type '() => any'.
```

**Comment by dnakov** [comment] 2018-09-20 16:15
yeah, sorry, this wasnt typescript-correct. just meant that i put the import in a function so it doesn’t get loaded immediately

**Comment by ptdede** [comment] 2018-09-24 04:45
@dnakov no problem, i get your idea. Thanks. 👍

**Comment by timneutkens** [comment] 2018-09-24 06:51
#5249 fixes this issue.

**Comment by ptdede** [comment] 2018-09-24 15:19
Thanks @timneutkens ! Will try after release

**Closed** 2018-09-25 13:27 UTC

**Comment by ptdede** [comment] 2018-09-27 19:17
This works using next 7.0.1-canary.2:
thanks for the fix @timneutkens 👍 

```
const TextSideSlider: any = dynamic({
    loader: () => import(/* webpackChunkName: 'TextSideSlider' */"./TextSideSlider"),
} as any);
```
