### ISSUE TITLE
[Next 9] Importing react-dom would bloat the bundle size

### ISSUE THREAD

**Issue by zenozen** [zeit/next.js#7949] opened 2019-07-14 00:59 UTC
# Bug report

## Describe the bug

Importing react-dom in a page or in one of its dependent component will cause react-dom.production.min.js to be included in the page bundle, adding about 32K gzipped size to a page.

This is pretty common, examples:
- ReactDOM.createPortal
- `react-transition-group` also imports `react-dom`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'pages/any-page.js'
2. Add `import ReactDOM from 'react-dom';`
3. In the render function, do `console.log(ReactDOM)`. Just to use that dependency.
4. Production build the project and inspect the bundle size

## Expected behavior

react-dom should just be in the common bundle, not included again here.
This does not happen with Next 8.

## System information

- OS: macOS
- Version of Next.js: 9.0.1

**Comment by timneutkens** [comment] 2019-08-10 13:53
@atcastle is this fixed by the new chunking logic?

**Comment by atcastle** [comment] 2019-08-12 17:36
This definitely shouldn't happen with granular chunks--but then, it shouldn't happen without it, either. The old SplitChunksConfig has 
`test: /[\\/]node_modules[\\/](react|react-dom|scheduler)[\\/]/,` which should always split react-dom out of the endpoint bundles and into commons.

I just tried to repro this by following the directions in the bug report on one of the integration test apps and I didn't see the behavior (even without granular chunks). Do we have an example repo that exhibits this behavior?

**Comment by timneutkens** [comment] 2019-08-12 18:28
Yeah it definitely shouldn't happen / duplicate

**Comment by wyattanderson** [comment] 2019-08-12 19:32
I'm definitely seeing this in an app of mine; I'll see about putting together a reproducer.

**Comment by zenozen** [comment] 2019-08-12 19:57
Indeed it cannot be reproduced with a simple example.

Did some experiment. It seems that it only appears after your project reaches a certain level of complexity. I pinned down to something like

```
pageA (which imports react-dom) -> componentA -> componentA2`
pageB (does not import react-dom) -> componentB
index (does not import react-dom) -> componentX
```

And it's like, removing any of these dependency would make pageA shrinks to normal. Even in componentA2 there's an `export function foo()`, removing that would makes pageA shrink. So my guess is definitely related to complexity of the dependency graph.

@wyattanderson What do you see in your case? react-dom as well? It would be great if we can have a repro.

**Comment by wyattanderson** [comment] 2019-08-12 21:00
Yeah, I'm away from the machine that has this project on it at the moment, but it's for `react-dom` and by using `webpack-bundle-analyzer`, I can see that:
- the `commons` chunk has `react-dom`
- any page or component chunk that imports [`react-modal`](https://github.com/reactjs/react-modal) (a third-party NPM module which itself imports `react-dom`, as a peer dependency) _also_ has a separate copy of `react-dom`; these pages don't import `react-dom` directly.
Removing the `react-modal` import removes `react-dom` from the page/component chunk.

**Comment by timneutkens** [comment] 2019-08-26 16:29
@zenozen it's fixed in the new chunking behavior:

```
module.exports = {
  experimental: {
    granularChunks: true
  }
}
```

**Comment by timneutkens** [comment] 2019-08-26 17:34
It's going to be out of experimental soon once we have more metrics 👍

**Closed** 2019-09-03 14:55 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 06:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
