### ISSUE TITLE
Breakpoints do not work in Visual Studio Code

### ISSUE THREAD

**Issue by chadalen** [zeit/next.js#9659] opened 2019-12-07 09:08 UTC
# Bug report
Next.js does not work with Visual Studio Code's Debugger. e.g breakpoints do not work. This makes Next.js (at least for me) very frustrating to use. Microsoft has not been maintaining the repo found here (https://github.com/microsoft/vscode-recipes/tree/master/Next-js). This used to work in previous versions of Next.js.

Can the Next.js team please look into this? Visual Studio Code is one of the most popular code editors for web development so it should be heavily supported. I'm sure this is frustrating for other people as well.

## Describe the bug
Visual Studio Code's breakpoints do not work with Next.js

## To Reproduce

1. Use the latest version of Visual Studio Code
2. Use the latest version of Next.js
3. Try to get debugging working properly

## Expected behavior
Visual Studio Code's debugging feature should work with Next.js

## Screenshots
N/A

## System information

- OS: MacOS
- Browser: Chrome
- Version of Next.js: 9

**Comment by timneutkens** [comment] 2019-12-07 14:22
Duplicate of #4571

**Closed by timneutkens** 2019-12-07 14:22 UTC

**Comment by balazsorban44** [comment] 2022-01-30 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
