### ISSUE TITLE
Internal Server Error Firebase hosting

### ISSUE THREAD

**Issue by pvhieuit** [zeit/next.js#5132] opened 2018-09-09 15:38 UTC
# [With Firebase Hosting Example](https://github.com/zeit/next.js/tree/canary/examples/with-firebase-hosting)

Hi guys, when i deploy with-firebase-hosting example to firebase hosting, it has error **"Internal Server Error"**

Error Log:
![image](https://user-images.githubusercontent.com/18276928/45266082-b7a9b980-b47f-11e8-9007-13e00d6459c3.png)

Can anyone help me?
Thanks in advance!

**Comment by jthegedus** [comment] 2018-09-12 07:12
Try this https://github.com/zeit/next.js/tree/canary/examples/with-firebase-hosting#_appjs

If you could provide a minimal reproduction repo that would be good.

**Comment by timneutkens** [comment] 2018-09-12 07:55
The issue is building on Windows and deploying on Linux, i’ve Talked about this before in another issue and i guess node on Windows would support forward slash requires. Will have to try that out.

**Comment by pvhieuit** [comment] 2018-09-12 09:59
> Try this https://github.com/zeit/next.js/tree/canary/examples/with-firebase-hosting#_appjs
> 
> If you could provide a minimal reproduction repo that would be good.

I tried to install `@babel/runtime` but it still does not work.

package.json
```javascript
"scripts": {
    "dev": "next \"src/app/\"",
    "preserve": "npm run build-public && npm run build-funcs && npm run build-app && npm run copy-deps && npm run install-deps",
    "serve": "SET NODE_ENV=production firebase serve",
    "predeploy": "npm run build-public && npm run build-funcs && npm run build-app && npm run copy-deps",
    "deploy": "firebase deploy",
    "clean": "rimraf \"dist/functions/**\" && rimraf \"dist/public\"",
    "build-public": "cpx \"src/public/**/*.*\" \"dist/public\" -C",
    "build-funcs": "babel \"src/functions\" --out-dir \"dist/functions\"",
    "build-app": "next build \"src/app/\"",
    "copy-deps": "cpx \"*{package.json,package-lock.json,yarn.lock}\" \"dist/functions\" -C",
    "install-deps": "cd \"dist/functions\" && npm i"
  },
  "dependencies": {
    "firebase-admin": "^6.0.0",
    "firebase-functions": "^2.0.5",
    "next": "^6.0.3",
    "react": "^16.3.2",
    "react-dom": "^16.3.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.0.0",
    "@babel/core": "^7.0.0",
    "@babel/runtime": "^7.0.0",
    "cpx": "^1.5.0",
    "firebase-tools": "^4.2.1",
    "prettier": "^1.14.2",
    "rimraf": "^2.6.2"
  }
````

**Comment by pvhieuit** [comment] 2018-09-12 10:07
> The issue is building on Windows and deploying on Linux, i’ve Talked about this before in another issue and i guess node on Windows would support forward slash requires. Will have to try that out.

Hi @timneutkens,
Can you guide me specifically?

**Comment by timneutkens** [comment] 2018-09-12 10:09
It's something we have to fix in Next.js.

**Comment by pvhieuit** [comment] 2018-09-12 10:15
I hope it will be fixed soon

**Comment by do-n-khanh** [comment] 2018-09-13 02:49
i got the same error when deploying a build ( on Windows 10) to google app engine. Hope you can fix it asap. Thanks

**Comment by jthegedus** [comment] 2018-09-14 01:12
Ah, I see, this is the cause:

![nextjs-windows-build-error](https://user-images.githubusercontent.com/20798510/45523867-dbb62380-b80e-11e8-8c7f-72e4784805c2.png)

`\pages\_error.js` should be `/pages/_error.js`.

Thanks @timneutkens

**Comment by sdelvalle57** [comment] 2018-09-14 09:49
Is yet there a solution for this issue?
Having the same problem...

**Comment by pvhieuit** [comment] 2018-09-16 04:51
@do-n-khanh if you are in a hurry, you should be using **Mac** or **Linux** to deploy your app to Google App Engine.

**Comment by do-n-khanh** [comment] 2018-09-16 05:29
@pvhieuit Thanks. Yeah, I actually had to use Windows Subsystem for Linux to deploy my app to gae.

**Comment by timneutkens** [comment] 2018-10-17 12:40
Duplicate of https://github.com/zeit/next.js/issues/5132

**Closed by timneutkens** 2018-10-17 12:40 UTC

**Comment by maximilian183** [comment] 2018-10-17 16:32
#5132 is a duplicate of #5132?
