### ISSUE TITLE
with-google-analytics example cannot be applied to AMP pages.

### ISSUE THREAD

**Issue by bulentala** [zeit/next.js#9290] opened 2019-11-02 18:10 UTC
The code structure used in the with-google-analytics example is not supported by AMP. This code does not work when I want to use the NextJs project as amp. 
NextJS can be updated with the code used on the original site

https://github.com/zeit/next-site/blob/master/pages/_document.js

**Comment by jamesmosier** [comment] 2019-12-12 14:18
Do you think it is best to add the AMP Google Analytics implementation to the existing `with-google-analytics` example or create a new `with-google-analytics-amp` example? @Timer

**Comment by timneutkens** [comment] 2020-04-28 08:09
This was fixed by #9723

**Closed by timneutkens** 2020-04-28 08:09 UTC
Labels: Type: Example, good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-30 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
