### ISSUE TITLE
Npm run build hanging on "Automatically optimizing pages"

### ISSUE THREAD

**Issue by jlbroughton88** [zeit/next.js#9360] opened 2019-11-09 22:09 UTC
# Bug report
Build hangs on "Automatically optimizing pages".

## Describe the bug
When I run npm run build, it compiles successfully and then hangs on "Automatically optimizing pages".

## To Reproduce

I don't know, but heres my repo... _https://github.com/jlbroughton88/Social-Media-App_

Here are my scripts if they matter...
`  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "next build",
    "dev": "NODE_ENV=production nodemon server",
    "find": "pgrep node",
    "kill": "pkill node"
  }`

## Expected behavior

I expect the build to finish without any interruption.

## Screenshots

**Console**
<img width="157" alt="Screen Shot 2019-11-09 at 5 08 25 PM" src="https://user-images.githubusercontent.com/42415136/68535648-9064ab80-0313-11ea-9f22-6da340d8b394.png">

**Here is my _next folder, which i've recently included in my .gitignore**
<img width="618" alt="Screen Shot 2019-11-09 at 5 07 12 PM" src="https://user-images.githubusercontent.com/42415136/68535646-72974680-0313-11ea-95b1-746a0ec94203.png">

## System information

- OS: [MacOS]
- Browser (if applies): [Chrome]
- Version of Next.js: [9.1.3]

**Comment by jamesmosier** [comment] 2019-11-10 22:36
I cloned your project and was able to successfully run `npm run build`.

I would try to delete your `node_modules` and then re-run `npm install` and then `npm run build`.

If that doesn't work, try deleting your `_next` folder as well and re-run `npm run build`.

Hope that helps!

<img width="861" alt="Screen Shot 2019-11-10 at 5 34 38 PM" src="https://user-images.githubusercontent.com/2854919/68552019-69c07680-03e0-11ea-80b2-583d7bd13d70.png">

**Comment by ijjk** [comment] 2019-11-13 02:45
Closing as we can't reproduce this. Please reply with additional details if you are still running into this

**Closed by ijjk** 2019-11-13 02:45 UTC
Labels: Can't Reproduce

**Comment by stijnvanderlaan** [comment] 2020-02-25 15:19
I have the same problem, also when this happens the node instance in the background will grow in memory (I had multiple instances using +12GB) even when you ctrl+c the build process.

**Comment by balazsorban44** [comment] 2022-01-30 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
