### ISSUE TITLE
500 internal server error when refreshing page - with custom server as in the example

### ISSUE THREAD

**Issue by mv5** [zeit/next.js#5556] opened 2018-10-30 19:29 UTC
I copied the custom server with express example so that every page (not just the homepage)
 could be server rendered.
I am still getting a 500 error when refreshing.
I'm deploying with now.

I have a server.js file in root folder that looks like this:
const express = require('express')
const next = require('next')

const port = parseInt(process.env.PORT, 10) || 3000
const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const handle = app.getRequestHandler()

app.prepare()
  .then(() => {
    const server = express()
    server.get('*', (req, res) => {
      return handle(req, res)
    })

    server.listen(port, (err) => {
      if (err) throw err
      console.log(`> Ready on http://localhost:${port}`)
    })
  })

package.json looks like this:
{
  "name": "create-next-example-app",
  "scripts": {
    "dev": "node server.js",
    "build": "next build",
    "start": "NODE_ENV=production node server.js"
  },
  "dependencies": {
    "express": "^4.16.4",
    "isomorphic-unfetch": "^3.0.0",
    "next": "7.0.2",
    "react": "16.6.0",
    "react-dom": "16.6.0"
  }
}

thanks for the help

**Comment by timneutkens** [comment] 2018-10-31 15:44
I'm adding labels, but this is not following the issue template, so next time I'll close it.

**Comment by mv5** [comment] 2018-11-01 12:07
ok, sorry about that...
I noticed that when navigating client side to the about page for example,
the requested url looks like this:
`_next/static/bFto_PzEAaO29KRX3~Ldj/pages/about.js`
but when refreshing its just `/about`
so maybe it has to do with the deployment process and not next?

**Comment by mv5** [comment] 2018-11-01 19:09
refreshing now works, don't know what was the problem before...

**Closed** 2018-11-01 19:08 UTC
Labels: good first issue, help wanted

**Comment by jeffryang24** [comment] 2019-02-12 04:45
@mv5 Could you share the way you fix your problem? Currently, I also faces the same problem. The 500 page showed when I opened the page through browser bar (server side) and the page was rendered successfully when navigating from the client side.

**Comment by jeffryang24** [comment] 2019-02-12 06:35
> @mv5 Could you share the way you fix your problem? Currently, I'm also facing the same problem. The 500 page showed when I opened the page through browser bar (server side) and the page was rendered successfully when navigating from the client side.

Already found the problem, non NextJS related issue. I use `Object.values` inside my source code within NodeJS v6.9.1, which was not supported yet on that time. Current solution is using polyfill to fix that issue. :bowing_man:

**Comment by hutber** [comment] 2019-11-06 15:35
I am curious as to why it doesn't happen on initial page load though.

**Comment by abhi12299** [comment] 2020-01-26 14:11
Similar problem here. Doesn't happen in development environment. Any solutions?

**Comment by audreybozorgi** [comment] 2022-01-01 14:07
I have same solution in production. Doesn't happen in development environment too. sicking for solution as it blocks my build for a month :(

**Comment by balazsorban44** [comment] 2022-01-31 15:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
