### ISSUE TITLE
styled-jsx breaks in SSR with material-ui

### ISSUE THREAD

**Issue by lifeiscontent** [zeit/next.js#7583] opened 2019-06-15 00:23 UTC
# Examples bug report

## Example name

with-material-ui

## Describe the bug

styled-jsx ssr breaks

styles only load client side

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://codesandbox.io/s/nextjs-inufq
2. Click on look at the preview

## Expected behavior

SSR includes styled-jsx style

## System information

- OS: macOS
- Browser (if applies) chrome
- Version of Next.js: latest stable

**Comment by ijjk** [comment] 2019-07-02 17:54
Hi, it looks like https://codesandbox.io/s/nextjs-inufq is no longer available. This might have been fixed in #7697. You can test with that fix using the latest canary of Next.js `v8.1.1-canary.64`. 

If you are still encountering this problem please reply with additional details.

**Closed by ijjk** 2019-07-02 17:54 UTC

**Comment by balazsorban44** [comment] 2022-01-31 13:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
