### ISSUE TITLE
Externally imported contents in CSS files have strings escaped (content:'\xxx' dont render right)

### ISSUE THREAD

**Issue by ruhaim** [zeit/next.js#10302] opened 2020-01-28 08:40 UTC
# Bug report
css content strings added for icons appear as stings not as icons

## Describe the bug
a css class defined as 
`.a::before {
  content: '\f054';
}`
dont render the icon, instead some text is displayed

## To Reproduce
USe this code sandbox to view the issue and a probable workaround with scss
https://codesandbox.io/s/async-wind-uj7z6
Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a css class with 'content' eg: a.css
`a::before {
  content: '\f054';
}`
2. import the css class into the react component 
`import css from "../style/a.css";` 
3. `<style jsx>{css}</style>` in the component to render the styles
4. in the render function add html in a way that the class will get selected
eg: 
`<a>Hi</a>`
## Expected behavior

The icon should render instead of the text
## Screenshots
![image](https://user-images.githubusercontent.com/3959554/73247859-d2e1aa00-41d7-11ea-84af-63f10f4f5b44.png)

## System information
-package.json dev deps
`
  "devDependencies": {
    "cross-env": "^5.2.0",
    "node-sass": "^4.7.2",
    "sass-loader": "7.1.0"
  },
`
-next.config.js
 `
module.exports = {
    webpack: (config, { defaultLoaders }) => {
      config.module.rules.push({
        test: /\.scss|css$/,
        use: [
          defaultLoaders.babel,
          {
            loader: require('styled-jsx/webpack').loader,
            options: {
              type: 'scoped'
            }
          },
          'sass-loader'
        ]
      })
  
      return config
    }
  }
  `
- Browser Chrome
- Version of Next.js: seems to be broken in v9, v9.1 and v9.2, works fine in v7 and v8 though 

## Additional context
Seems like a issue related to the style-jsx version that is bundled
https://github.com/zeit/styled-jsx/issues/589, i have commented my findings  and workaround in that issue as well

**Comment by ruhaim** [comment] 2020-01-28 08:44
As a workaround you can define the content in SCSS using the unquote function as below
`.c::before {
  content: unquote('"\f054"');
}
.d::before {
  content: unquote("'\f054'");
}`

**Comment by Timer** [comment] 2020-01-28 16:04
Duplicate of https://github.com/zeit/styled-jsx/issues/589

**Closed by Timer** 2020-01-28 16:04 UTC

**Comment by balazsorban44** [comment] 2022-01-30 14:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
