### ISSUE TITLE
autoPrerender not working

### ISSUE THREAD

**Issue by oxilor** [zeit/next.js#8977] opened 2019-10-07 03:08 UTC
# autoPrerender not working

## Describe the bug

```
devIndicators: {
   autoPrerender: false,
},
```
not working

## To Reproduce

1. Create a project by "npx create-next-app"
2. Add the "pages/_app.jsx" file
```javascript
import App from 'next/app'
import React from 'react'

class MyApp extends App {
    static async getInitialProps (appContext) {
        const appProps = await App.getInitialProps(appContext)
        return { ...appProps }
    }

    render () {
        const { Component, pageProps } = this.props
        return (<Component { ...pageProps } />)
    }
}

export default MyApp
```
3. Replace the "next.config.js" file to
```
module.exports = {
  devIndicators: {
    autoPrerender: false,
  },
}
```
4. Run "yarn build"
5. See the error "Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`"

## Expected behavior

No "You have opted-out of Automatic Static Optimization" warning.

## Screenshots

<img width="660" alt="console" src="https://user-images.githubusercontent.com/35278731/66282103-c4891e80-e8c6-11e9-9619-f57df1a00a80.png">

## System information

- OS: macOS
- The version of Next.js: 9.0.8

**Comment by Timer** [comment] 2019-10-07 05:11
This option only toggles the in-browser build indicator. 
You cannot dismiss the message emitted during the build.

I'll close this as no action required, as we're not planning on allowing this message be disabled.

**Closed by Timer** 2019-10-07 05:11 UTC

**Comment by balazsorban44** [comment] 2022-01-31 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
