### ISSUE TITLE
High `next dev` memory usage on elementary OS

### ISSUE THREAD

**Issue by whthT** [zeit/next.js#8808] opened 2019-09-20 14:09 UTC
# Bug report
Hi, I'm developing a project for the `next@9.0.5` and I've encountered a problem as I mentioned in the title. I've shared detailed information below

## Describe the bug
If there is a browser with the local address where your application is published, nodejs starts to use your machine's memory in seconds.
I've removed all plug-ins, components, and pages from within the project to solve the problem, but none has been resolved.
What I noticed is that if the website is not open on any browser, it uses memory properly (around 300MB), but this problem arises when you turn off the giant server and turn it on again.
I didn't come across this problem when NextJS was first installed.

## Screenshots

![stuck](https://user-images.githubusercontent.com/5617385/65333232-c4033f00-dbc8-11e9-932d-8384ba785ce3.png)

## System information

- OS: elementary OS 5.0 Juno (Ubuntu 18.04.2 LTS)
- Browser: Chrome Version 77.0.3865.90 (Official Build) (64-bit)
- Version of Next.js: 9.0.5

## Additional context
It seems that there is no problem with the Windows Operating System.

**Comment by timneutkens** [comment] 2019-09-21 09:49
I'm not sure how we can investigate this. It sounds super unlikely that this is directly related to Next.js as we haven't had this kind of report for other operating systems 🤔

**Comment by jeremy-coleman** [comment] 2019-09-22 16:56
its webpack

**Comment by timneutkens** [comment] 2019-09-23 08:02
@jeremy-coleman I'm not sure how your comment here is relevant. You didn't investigate the issue outlined here: https://github.com/zeit/next.js/issues/8808#issue-496374488.

**Comment by jeremy-coleman** [comment] 2019-09-23 16:51
try running with --max-old-space 8096, it will leak to 8.1mb. its webpack. It happens on windows too, use the windows process explorer to inspect mem use

**Comment by whthT** [comment] 2019-10-04 14:41
@jeremy-coleman Hi, when i try to run with `--max-old-space` nothing change.

**Comment by timneutkens** [comment] 2020-01-02 22:54
Closing this as it's impossible to investigate. Maybe same as #7929

**Closed by timneutkens** 2020-01-02 22:54 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-30 17:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
