### ISSUE TITLE
not working if library js requires css

### ISSUE THREAD

**Issue by disjukr** [zeit/next.js#5475] opened 2018-10-18 11:01 UTC
# Bug report

## Describe the bug

my library is ui component library that depends [css modules](https://github.com/css-modules/css-modules)

## Expected behavior
works css loader to my library code as well

## Screenshots
<img width="900" alt="2018-10-18 6 45 34" src="https://user-images.githubusercontent.com/690661/47146394-e466b180-d306-11e8-9ec2-abebd9a8452f.png">

### `my-library/MyComponent/index.js`
![2018-10-18 6 52 35](https://user-images.githubusercontent.com/690661/47146447-0102e980-d307-11e8-8c09-11a254d06c7d.png)

## System information
 - OS: macOS
 - Version of Next.js: 7.0.1
```json
"dependencies": {
  "next": "^7.0.1",
  "@zeit/next-css": "^1.0.1"
}
```
## Additional context

similar issues
- https://github.com/zeit/next-plugins/issues/70
- https://github.com/zeit/next.js/issues/105
- https://github.com/zeit/next-plugins/issues/273
- https://github.com/zeit/next.js/issues/706
- https://github.com/zeit/next.js/issues/4114
- https://github.com/zeit/next.js/issues/4617
- https://github.com/zeit/next.js/issues/4637
- https://github.com/zeit/next.js/issues/5278

**Comment by timneutkens** [comment] 2018-10-18 11:53
Closing this as duplicate of zeit/next-plugins#273

**Closed by timneutkens** 2018-10-18 11:53 UTC
