### ISSUE TITLE
/Page works just fine but /page throws an error? Need lowercase urls to work

### ISSUE THREAD

**Issue by brooksrelyt** [zeit/next.js#11609] opened 2020-04-02 19:04 UTC
# Bug report

Only title case links are working for pages.

## Describe the bug

I am confused about an issue related to the case of the links I am using.

For example:

https://example.com/page (does not work - 404 error)

but

https://example.com/Page (does work)

## Expected behavior

I expected /page to work without a 404.

## Screenshots

I changed all file names to be lowercase just to test if that would work:
<img width="248" alt="Screen Shot 2020-04-02 at 3 03 46 PM" src="https://user-images.githubusercontent.com/5075282/78291333-31d2e080-74f3-11ea-8a70-10b01af13df4.png">

**Comment by timneutkens** [comment] 2020-04-03 07:49
Duplicate of https://github.com/zeit/next.js/issues/8825

**Closed by timneutkens** 2020-04-03 07:49 UTC

**Comment by balazsorban44** [comment] 2022-01-30 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
