### ISSUE TITLE
Module not Found error when writing components.

### ISSUE THREAD

**Issue by pavittarx** [zeit/next.js#12605] opened 2020-05-07 14:59 UTC
# Bug report
I have a component that reads a file & returns its content. Something similar to (https://nextjs.org/learn/basics/data-fetching/implement-getstaticprops) in the docs. 

But, it produces an error 
[ error ] ./lib/test.js
Module not found: Can't resolve 'fs' in 'C:\Users\pavit\Desktop\fs-error\lib'

## Describe the bug
Some data is stored in a file, I want to read from the file & expose parts of it to build a component.
The file is stored in /data directory. 
The component is stored in /components directory. 
The library file is stored in /lib directory. 

`/pages/index.js` imports `/components/container.js` which uses `/lib/test.js`. However,
`import fs from 'fs';` in /lib/test.js produces the error. 

It works when container.js is inside /pages directory, but I do not want that, since I want to expose `container.js` as a component.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
 View: https://gitlab.com/pavittarx/nextjs-fs-error

`npm run dev` would produce the error. 

*  adding `import fs from 'fs';` in /components/container.js starts producing the same error in container.js. 

## Expected behavior
The module should not produce such error, since I am exporting the component to be used with `getStaticProps`, not to be bundled with the browser. Also, since the module can imported only at the top level, there is no scope of importing it inside `getStaticProps`.

## System information

- OS: [e.g. macOS, Windows] Windows 10
- Browser (if applies) [e.g. chrome, safari] Opera, Edge
- Version of Next.js: [e.g. 6.0.2] Latest
- Version of Node.js: [e.g. 10.10.0] 10.16.3

**Comment by lfades** [comment] 2020-05-07 18:06
@pavittarx `getStaticProps` can only be used inside page files, not in external components, and Node.js only modules like `fs` have to be used inside it, otherwise the client side bundle will include them and that's why you get that error.

**Comment by pavittarx** [comment] 2020-05-08 02:20
@lfades 
Thanks for your time & response, but I didn't find this information in the docs. Also, is there some other way I can go on to achieve it?

I wanted the component to be self-sufficient. Say, 
<Component name="alpha"/> 
<Component name="beta" />
produce different results. And, they are dynamically generated based on the data in sample File. 

Well, one approach I could think of is, fetch. manipulate & pass data as props in `/pages/index,js`. But, that would require me to write same piece of code over & over for different pages, which I certainly do not want to do.

**Comment by lfades** [comment] 2020-05-08 15:47
It's in docs: https://nextjs.org/docs/basic-features/data-fetching#only-allowed-in-a-page-1

Data fetching methods can only be used inside a page file, that's intended to keep the data fetching required for a page inside the page.

I'm closing the issue as there's nothing else to solve from Next.js side. I would recommend that you fetch the data in the page and pass it as props to the component. In the future we may come with a better solution as React continues improving.

**Closed by lfades** 2020-05-08 15:47 UTC

**Comment by kovart** [comment] 2020-09-20 08:56
So, as I understand it, I can't use my high-level modules that wrap 'fs' module, right? 
I'm getting an error "Module not found: Error: Can't resolve 'fs' in 'D:\Workspace\PROJECT_NAME\src\emulator'", but I use this database emulator only in getStaticProps().

**Comment by balazsorban44** [comment] 2022-01-29 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
