### ISSUE TITLE
[9.3.0] 404 page getInitialProps not working

### ISSUE THREAD

**Issue by tankpower1** [zeit/next.js#10999] opened 2020-03-12 12:25 UTC
^ Topic

**Comment by timneutkens** [comment] 2020-03-12 12:27
Closing as the issue template is not followed.

**Closed by timneutkens** 2020-03-12 12:27 UTC

**Comment by balazsorban44** [comment] 2022-01-30 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
