### ISSUE TITLE
App stuck at [wait] compiling ... 

### ISSUE THREAD

**Issue by ZhouYuTao2017** [zeit/next.js#9828] opened 2019-12-25 08:32 UTC
# Bug report

## Describe the bug
 stuck at [wait] compiling

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. next

## System information

- OS: macOS
- Browser (if applies) [e.g. chrome, safari]:chrome
- Version of Next.js:9

**Comment by ZhouYuTao2017** [comment] 2019-12-25 08:34
![image](https://user-images.githubusercontent.com/30223113/71439389-64bb4a80-2734-11ea-8a2f-d6761d212e3d.png)

**Comment by timneutkens** [comment] 2019-12-25 10:59
A full reproduction is needed as per the issue template. Otherwise it’s impossible to help.

**Comment by ZhouYuTao2017** [comment] 2019-12-26 10:45
> A full reproduction is needed as per the issue template. Otherwise it’s impossible to help.
Thanks, I have found the problem, the wrong background-images path will trigger this problem

**Comment by timneutkens** [comment] 2019-12-26 12:04
Still please provide a full reproduction so that we can handle it.

**Comment by ZhouYuTao2017** [comment] 2019-12-27 02:46
> Still please provide a full reproduction so that we can handle it.
Reference errors will always compile
![image](https://user-images.githubusercontent.com/30223113/71498080-de1e7e80-2895-11ea-96a8-fb33d725cab2.png)

This will be normal
![image](https://user-images.githubusercontent.com/30223113/71498133-1625c180-2896-11ea-8fdf-afe006a8090b.png)

**Comment by timneutkens** [comment] 2019-12-27 14:28
This is still not enough to look into it unfortunately, as we don’t know how you implemented css support.

**Comment by Timer** [comment] 2019-12-27 16:48
I've tested that the following CSS successfully compiles / recovers after fixed with the new experimental CSS support:
```css
body {
  color: blue;
  background-image: url(../not-real.jpg);
}
```

I'm closing this as no reproduction has been provided. Happy to re-open if you can provide a demo!

**Closed by Timer** 2019-12-27 16:48 UTC
Labels: Can't Reproduce

**Comment by balazsorban44** [comment] 2022-01-30 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
