### ISSUE TITLE
Improve Router Typings

### ISSUE THREAD

**Issue by tills13** [zeit/next.js#7799] opened 2019-07-08 21:17 UTC
# Feature request

Improve typings for the router.

## Describe the solution you'd like

A couple examples:

* `useRouter` seems to have an `any` return type (because of [this line](https://github.com/zeit/next.js/blob/master/packages/next-server/lib/router-context.ts#L3)) 

```
import * as React from 'react'
import { BaseRouter } from './router/router'

export const RouterContext = React.createContext<BaseRouter | null>(null)
```

* `useRouter` should be generic, as well. This involves propagating generics down through to `BaseRouter<P>` (and finally update `query` to `query: ParsedUrlQuery & P`). This is to allow you to specific custom query (URL params, etc).
* Regression: lost `WithRouterProps` type export from `next/router`
* Improved [`WithRouterProps`](https://github.com/zeit/next.js/blob/master/packages/next/client/with-router.tsx#L6) typings via generics. See [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/next-server/router.d.ts#L81). 
* (still finding more)

## Describe alternatives you've considered

The only "alternatives" are rolling your own types and asserting e.g. `router.query as MyQueryType` etc.

**Comment by tills13** [comment] 2019-07-08 21:17
Should I be adding an issue per area I'd like to see types improved? Or would one issue suffice?

**Comment by felixmosh** [comment] 2019-07-08 21:47
My [PR](https://github.com/zeit/next.js/pull/7797) solves the WithRouterProps with query types

**Comment by tills13** [comment] 2019-07-08 22:02
Possible duplicate of #7764

**Comment by huv1k** [comment] 2019-07-08 22:04
It's duplicate of it and we have already pending PR for it #7768, it's not yet done. It requires more changes in the codebase.

**Comment by tills13** [comment] 2019-07-08 22:16
Between #7768 and #7797 this can be closed. (not sure if I should do that or leave it to contributors)

**Comment by Timer** [comment] 2019-07-09 01:31
Closing since it's handled by #7768

**Closed by Timer** 2019-07-09 01:31 UTC
Labels: Type: Bug, Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
