### ISSUE TITLE
Feature: Multiple path segments in page filenames

### ISSUE THREAD

**Issue by overlookmotel** [zeit/next.js#12113] opened 2020-04-22 16:45 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I am a big fan of Next's file system router. However, with dynamic routes, it can lead to deeper folder structures than I would like.

For example, if I have CRUD routes for "bands" and "albums", where each "album" belongs to a "band", I end up with the following folder structure in `pages`:

```sh
# 1 folder deep
bands/index.js
bands/new.js
# 2 folders deep
bands/[bandId]/index.js
bands/[bandId]/edit.js
bands/[bandId]/delete.js
# 3 folders deep
bands/[bandId]/albums/index.js
bands/[bandId]/albums/new.js
# 4 folders deep
bands/[bandId]/albums/[albumId]/index.js
bands/[bandId]/albums/[albumId]/edit.js
bands/[bandId]/albums/[albumId]/delete.js
```

Personally, I find:

1. the deep folder structure gets unmanageable (especially when the hierarchy is deeper).
2. it's unnatural to have pages related to "bands" split between two folders `bands` and `bands/[bandId]`.

#### Possible solution 1

It would be easier to get a flat folder structure if multiple path segments could be included in a single filename. i.e. filenames like `[xxx]yyy.js` or `[xxx][yyy].js`.

The above example could become:

```sh
# 1 folder deep
bands/index.js
bands/new.js
bands/[bandId].js
bands/[bandId]edit.js
bands/[bandId]delete.js
# 2 folders deep
bands/[bandId]albums/index.js
bands/[bandId]albums/new.js
bands/[bandId]albums/[albumId].js
bands/[bandId]albums/[albumId]edit.js
bands/[bandId]albums/[albumId]delete.js
```

This has nested folders only 2-deep rather than 4, and the `[bandId]albums` folder contains all 5 files related to "albums" in one place.

I imagine this could be achieved as simply as using a regex on file paths before they are converted to routes `path.replace(/\](?!\.)/g, ']/')`.

#### Possible solution 2

Make some "special" character in filenames be treated as a slash. e.g. `~`.

```sh
# 1 folder deep
bands/index.js
bands/new.js
bands/[bandId].js
bands/[bandId]~edit.js
bands/[bandId]~delete.js
# 2 folders deep
bands/[bandId]~albums/index.js
bands/[bandId]~albums/new.js
bands/[bandId]~albums/[albumId].js
bands/[bandId]~albums/[albumId]~edit.js
bands/[bandId]~albums/[albumId]~delete.js
```

This doesn't produce any better result for my use case, but it's more flexible. Someone else might want to flatten a structure with routes which don't use dynamic paths e.g. `pages/some/deep/structure.js` -> `some~deep~structure.js`.

#### Possible solution 3

Either of the above would be (strictly speaking) be a breaking change. Someone somewhere might have a page called `[foo]bar.js` and want its url to be static at `http://mysite.com/[foo]bar` - which is what they'd get at present.

A way to introduce this functionality in a non-breaking way would be to add an option to `next.config.js` allowing the user to provide a custom file path -> URL path mapping function.

```js
// next.config.js
module.exports = {
  transformFilePath(path) {
    return path.replace(/~/g, '/');
  }
};
```

This would also allow the user flexibility to do other kinds of path transformation/mapping.

I have a convention, for example, that params are always the same as the singular of the enclosing folder's name + `Id`. e.g. `bands/[bandId].js`, `albums/[albumId].js`. With a custom transform function, I could have terser file names e.g. `bands/[].js` and use the transform function to automatically flesh them out to `bands/[bandId].js`.

I imagine this would not be too difficult to implement for server and dev environments, but I'm not sure if it'd hugely complicate serverless deployment.

## Describe alternatives you've considered

Perhaps using a custom server would allow this, but that would rule out SSG.

Maybe it's somehow possible through custom webpack config, but I'm not sure. If anyone thinks that is a viable solution I'd hugely appreciate any pointers.

I don't *think* this is covered by #9081.

## Additional context

If you'd be willing to accept one of the above solutions (or something else which fulfils my use case), I'd be happy to implement and submit a PR.

**Comment by overlookmotel** [comment] 2020-04-22 16:46
Oh damn it! I've just seen #11647 which asks for the same feature, but for different reasons. I'll post my use case on a comment on that issue instead.

**Comment by overlookmotel** [comment] 2020-04-22 16:54
I just saw #11647 which is asking for a similar but not identical feature.

In #11647, `[package]@[version].js` would be treated as a single URL path segment, whereas in my use case, it would be treated as if it was `[package]/@/[version].js`.

This suggests that my Solution 1 above is not viable, as the behavior wouldn't be what everyone expects. But perhaps the other solutions are workable.

**Comment by timneutkens** [comment] 2020-05-25 14:08
Closing this as it doesn't seem to have traction (no 👍 from other people). We're currently not planning to change the directory structure (as it would be a breaking change).

**Closed by timneutkens** 2020-05-25 14:08 UTC

**Comment by balazsorban44** [comment] 2022-01-30 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
