### ISSUE TITLE
amp example do not have bundle file "app.js"

### ISSUE THREAD

**Issue by Wolke** [zeit/next.js#1728] opened 2017-04-15 07:58 UTC
so every thing is not work fine?
when I call next build;

how to get the app.js right path;
the I can add to _document.js

**Comment by Wolke** [comment] 2017-04-21 05:24
no one have answer?

**Comment by timneutkens** [comment] 2017-04-21 08:19
@impronunciable could you check this out? Thanks ❤️

**Comment by impronunciable** [comment] 2017-04-21 14:18
sure @timneutkens

**Comment by impronunciable** [comment] 2017-04-23 14:08
@Wolke If I want to include `app.js` I would add

```
<NextScript />
<Main />
```

into `pages/_document.js`. The issue is amp only allows a very small strict subset of javascript to run in your amp pages. I think for the moment the best approach is to add the desired js as a separate script and include it using the `<Head>` tag inside the page where you want to execute it

**Comment by Wolke** [comment] 2017-04-27 17:14
I just combine the two example "with-amp" , "with-react-md".
and I dont know where to add
`<NextScript />
<Main />`
so because the project do not know the correct bundle file "app.js" path , so I can not work well for drawer.
[https://github.com/Wolke/with-react-md-amp](https://github.com/Wolke/with-react-md-amp)

**Comment by impronunciable** [comment] 2017-04-28 13:50
@Wolke I think you forgot to add the code you want to mention

**Comment by impronunciable** [comment] 2017-05-10 01:06
Closing since this was already answered. Feel free to reopen

**Closed by impronunciable** 2017-05-10 01:06 UTC
