### ISSUE TITLE
support for _layout.js file

### ISSUE THREAD

**Issue by luisrudge** [zeit/next.js#104] opened 2016-10-27 01:01 UTC
Exactly like you support the _error.js file.
This would solve a common question people are asking (https://github.com/zeit/next.js/issues/71, https://twitter.com/luisrudge/status/790946965123112960).

The idea is look for a _layout.js file. If it exists, render it passing the current route's content as children.

**Comment by dlindenkreuz** [comment] 2016-10-27 17:03
Is this a duplicate of #88?

**Comment by luisrudge** [comment] 2016-10-27 17:06
It wasn't until you renamed the issue 😝

**Comment by dlindenkreuz** [comment] 2016-10-27 17:10
Hehe, kinda. The issue was originally about allowing animated route transitions which would need an editable top-level app component.

I guessed the root of the issue is not route transitions but rather having an editable top-level app component which would also solve many other issues like the current force re-mounting of all components (see #50). To better describe its core, I decided to rename the issue.

**Closed** 2016-10-27 17:24 UTC
