### ISSUE TITLE
Failed to build with new approach of handling CSS: can't read property pop of undefined

### ISSUE THREAD

**Issue by ivadimko** [zeit/next.js#10171] opened 2020-01-20 15:16 UTC
# Bug report

## Describe the bug

Building nextjs app throws an error:
```
Failed to compile.

chunk c8f7fe3b0e41be846d5687592cf2018ff6e22687
static/css/030f3c81fcf6deab04e9.css
Cannot read property 'pop' of undefined
```

## To Reproduce

add some [name].module.css and build the app

## Expected behavior

App builds without errors

## System information

- OS: Tried on MacOS (nodejs v10 and nodejs v12) and Linux (Docker container node:12)
- Version of Next.js: 9.0.2

## Additional context

adding next snippet in my next.config.js solves the issue but I don't think it is the best way
```
    if (config.optimization.splitChunks) {
      config.optimization.splitChunks.cacheGroups.shared.enforce = true;
    }
```

**Comment by Timer** [comment] 2020-01-20 15:59
Please provide a reproducible demo.

**Comment by zhangchao828** [comment] 2020-01-21 01:40
me too

**Comment by Timer** [comment] 2020-01-21 21:58
Duplicate of #10161

**Closed by Timer** 2020-01-21 21:58 UTC
Labels: Can't Reproduce

**Comment by balazsorban44** [comment] 2022-01-30 15:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
