### ISSUE TITLE
Background image url in css files addon assets prefix.

### ISSUE THREAD

**Issue by KennyWho** [zeit/next.js#9781] opened 2019-12-18 18:56 UTC
I can put images files in the 'public/static' path. when the project built, the URL should be instead by CDN, I need to find '/static/' in all CSS files and replace it. Is there a better way?
Another question is I want to give the background image file a hashtag, I try to use `file-loader`, but it can't work as well in next.js. I find some solution is only for in js files, but not in the CSS file. Does anyone have an idea?

**Comment by timneutkens** [comment] 2019-12-18 19:21
Closing as this doesn't follow the issue template.

**Closed by timneutkens** 2019-12-18 19:21 UTC

**Comment by Angelki** [comment] 2019-12-26 04:06
> I can put images files in the 'public/static' path. when the project built, the URL should be instead by CDN, I need to find '/static/' in all CSS files and replace it. Is there a better way?
> Another question is I want to give the background image file a hashtag, I try to use `file-loader`, but it can't work as well in next.js. I find some solution is only for in js files, but not in the CSS file. Does anyone have an idea?

Do you have any solutions?

**Comment by KennyWho** [comment] 2019-12-26 10:13
@Angelki yeah, but it's not the best way. I traverse all the images in 'public/static' directory and create a map to store the file md5 and the file path. and then I push the md5 file to CDN, and replace the static file reference to the md5 file path.

**Comment by balazsorban44** [comment] 2022-01-30 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
