### ISSUE TITLE
<Link> doesn't work with custom components?

### ISSUE THREAD

**Issue by ianstormtaylor** [zeit/next.js#9341] opened 2019-11-07 19:30 UTC
# Bug report

## Describe the bug

The `<Link>` component doesn't appear to pass on the `href` prop when wrapping a custom component instead of the native `<a>`.

## To Reproduce

Here's a CodeSandbox: https://codesandbox.io/s/nextjs-qtynp

I made sure to use `React.forwardRef`.

## Expected behavior

Both of the links should have their `href` props populated.

## System information

- OS: macOS
- Version of Next.js: 9.1.2
- Version of React: 16.11.0

## Additional context

It sounds unlikely that this is broken, since I assume this is one of the most commonly used codepaths. But I keep trying everything and nothing seems to work, so I figured I'd open this.

**Comment by prichodko** [comment] 2019-11-07 23:16
Pass `passHref` prop to <Link /> component. More info [here](https://nextjs.org/docs#forcing-the-link-to-expose-href-to-its-child).

**Comment by ianstormtaylor** [comment] 2019-11-07 23:26
Ahhhh, wow thank you @prichodko!

For the maintainers, I would seriously consider changing how `<Link>` works. The current `href/onClick` passing is *really magic-y* and hard to wrap your head around if you are doing anything other than a simple `<a>` element. It's kind of crazy right now that there's a failure case where everything appears to work while clicking around, and you only notice it if you happen to inspect the DOM and see that `href=` is missing, or notice that `cursor: pointer` isn't active.

I think it would be much easier to understand if it used a render-prop-based API where you did the passing yourself.

**Comment by Timer** [comment] 2020-04-15 04:58
Feature request is duplicate of #8207 after OP issue was fixed.

**Closed by Timer** 2020-04-15 04:58 UTC

**Comment by ianstormtaylor** [comment] 2020-07-11 02:37
Just got stumped by this again when needing to work with Next.js again after some time away from it. I'd recommend adding something to main routing the docs about `passHref`, because using custom components seems like the 90% use case for React apps IMO. Very unintuitive and easy to miss that it's broken.

**Comment by aboveyunhai** [comment] 2021-05-22 06:58
> Just got stumped by this again when needing to work with Next.js again after some time away from it. I'd recommend adding something to main routing the docs about `passHref`, because using custom components seems like the 90% use case for React apps IMO. Very unintuitive and easy to miss that it's broken. I imagine a lot of people must either (a) have broken links in their apps without realizing it, or (b) had to spend lots of time figuring out why the magic was failing.

my magic take for this one is to create a custom `<a />` tag and `unstyle` everything of the tag to make it empty, then wrap everything inside like `<NextLink><a  /*unset all styles to make it pure href only, no need to pass anything */> whatever inside </a></NextLink>`. It seems like the most stable way.

**Comment by balazsorban44** [comment] 2022-01-28 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
