### ISSUE TITLE
next.js9, css modules open  antd  style lapse

### ISSUE THREAD

**Issue by ZhouYuTao2017** [zeit/next.js#9774] opened 2019-12-18 07:05 UTC
# Bug report

## Describe the bug

open css modules ,antd style is lapse

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1.open css modules

## Expected behavior
antd style is normal

## Screenshots
antd tsx
![image](https://user-images.githubusercontent.com/30223113/71063049-e0525000-21a6-11ea-81a4-997f50c42bb7.png)

next.config.js
![image](https://user-images.githubusercontent.com/30223113/71063093-feb84b80-21a6-11ea-815f-75d9b3351fbc.png)
![image](https://user-images.githubusercontent.com/30223113/71063186-30311700-21a7-11ea-96a7-0669e88b6e13.png)

reality
![image](https://user-images.githubusercontent.com/30223113/71063150-1d1e4700-21a7-11ea-9d28-883e6b39372b.png)

## System information

- OS: macOS
- Browser:chrome
- Version of Next.js: 9.1

**Comment by ZhouYuTao2017** [comment] 2019-12-18 07:18
cssModules:true,but antd component class are not converted

**Comment by timneutkens** [comment] 2019-12-18 09:59
Providing a bunch of code screenshots is not a clear and concise reproduction.

Closing this as it's probably covered by https://github.com/zeit/next.js/issues/8626

**Closed by timneutkens** 2019-12-18 09:59 UTC
Labels: Can't Reproduce

**Comment by balazsorban44** [comment] 2022-01-30 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
