### ISSUE TITLE
react-hot-loader disable-warnings

### ISSUE THREAD

**Issue by steida** [zeit/next.js#3102] opened 2017-10-15 22:25 UTC
As I checked the code, there is no possibility to disable react-hot-loader warnings. 
What Next.js team does? Ignore them? Thank you.

https://github.com/gaearon/react-hot-loader#disable-warnings

**Comment by oliviertassinari** [comment] 2017-10-17 21:09
Duplicate of #3109

**Closed** 2017-10-17 21:27 UTC
