### ISSUE TITLE
[TypeError: Cannot read property 'toLowerCase' of undefined] when running in Docker

### ISSUE THREAD

**Issue by matt1as** [zeit/next.js#344] opened 2016-12-05 11:13 UTC
When running my application inside a docker container I get the following stack

    [TypeError: Cannot read property 'toLowerCase' of undefined]

    npm info lifecycle Bryderi@~dev: Failed to exec dev script
    npm ERR! Linux 4.4.27-moby
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
    npm ERR! node v5.2.0
    npm ERR! npm  v3.3.12
    npm ERR! code ELIFECYCLE
    npm ERR! Bryderi@ dev: `next`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the Bryderi@ dev script 'next'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the Bryderi package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     next
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls Bryderi
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /usr/src/npm-debug.log

However if I run the same application outside the docker container it all works as expected. I'm running the same version of node and NPM on both
`~/D/P/b/client> node --version
v5.2.0
~/D/P/b/client> npm --version
3.3.12`

My dockerfile looks like
    FROM node:5.2

    EXPOSE 3000 3030

    WORKDIR /usr/src

    COPY package.json /usr/src
    RUN npm install

And my docker-compose file like
    version: '2'
    services:
      web:
        build: ./client
        ports:
          - "3000:3000"
          - "3030:3030"
       volumes:
          - ./client:/usr/src/:rw
          - /usr/src/node_modules
        command:
            npm run dev
        working_dir:
            /usr/src

**Comment by dschenkelman** [comment] 2016-12-13 00:48
Hey :Wave:,

Using this with docker and ❤️  it. Can I help with anything to get this published to npm?

Thanks,

**Comment by uipoet** [comment] 2016-12-19 17:19
Would it be possible for @rauchg or another maintainer to use milestones for communicating when pull requests like this one are planned to land in the npm releases? Yes, the issue is "resolved" here in the repo, but I've been forced to lock my version to 1.1.2 and manually recheck if a release has happened for two weeks and counting...

**Comment by timneutkens** [comment] 2017-01-17 20:42
Landed in v2.0.0. Closing issue. @uipoet great suggestion, I'll create a new ticket for it.

**Closed by timneutkens** 2017-01-17 20:42 UTC
