### ISSUE TITLE
Next.js is stuck compiling

### ISSUE THREAD

**Issue by vernak2539** [zeit/next.js#10998] opened 2020-03-12 12:24 UTC
# Bug report

## Describe the bug

When I start my express server, which implements next, I navigate to a page and it starts compiling it as usual. It then proceeds stay there and never completes compiling.

This happens when in dev mode.

## To Reproduce

Repo: https://github.com/vernak2539/nextjs-build-error-repo

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `npm i`
2. `npm run dev`
3.  load URL output at bottom `http://localhost:6942`
4. See build stuck

## Expected behavior

Expect the compile to finish and the page to be built

## System information

- OS: macOS
- Browser: chrome, FF
- Version of Next.js: next@9.1.5

## Additional context

Here is the output when using the webpackbar plugin

```
[alexvernacchia:~/deliveroo/agent-support-app]$ node -r dotenv/config app/server.js --verbose
Defining routes from exportPathMap

✔ Webpack
  Compiled successfully in 1.87s

> Using external babel configuration
> Location: "/Users/alexvernacchia/deliveroo/asa/.babelrc"

✖ Webpack
  Compiled with some errors in 2.19s

[ ready ] compiled successfully
> Ready on https://agent.test
[ event ] build page: /interactions-home
[ wait ]  compiling ...

● Webpack █████████████████████████ after chunk asset optimization (93%) SourceMapDevToolPlugin static/runtime/webpack.js
 generate SourceMap

```

I've just noticed it says it compiled with some errors, but it's not showing what they are. This only changes from "successful" to "errors" after the initial `interactions-home` page starts to build

**Comment by timneutkens** [comment] 2020-03-12 12:27
Please provide a complete reproduction, this issue is not actionable otherwise.

**Comment by vernak2539** [comment] 2020-03-12 13:50
I've been trying to do this for a while now, but having a hard time getting a minimal solution that can be shared outside my company. I keep on removing things and then it just works, but the original doesn't. Have any suggestions?

**Comment by vernak2539** [comment] 2020-03-12 14:41
@timneutkens I've added a repo with it being reproducible

**Comment by vernak2539** [comment] 2020-03-12 16:29
I think there's something going on with npm... installing dependencies with yarn allowed the compile to complete. I'm unsure as to what it would be though

**Comment by Timer** [comment] 2020-04-15 05:49
This behavior might be fixed in 9.3.5 or newer. Closing as not easily reproduced with the demo.

**Closed by Timer** 2020-04-15 05:49 UTC
Labels: Please add a complete reproduction

**Comment by barbogast** [comment] 2020-04-26 05:46
I just had infinite compiling because I did 
```js
import { Context } from 'next'
```

instead of 

```js
import type { Context } from 'next'
```

Of course the code was wrong in this case. But maybe next shouldn't compile forever? Not sure though...

Happy to provide more details if interesting.

**Comment by barbogast** [comment] 2020-04-26 06:54
I forgot to mention: going from 9.3.4 to 9.3.5 did indeed resolve the infinite compiling. I got the following error then (which wasn't very helpful):
![image](https://user-images.githubusercontent.com/941889/80300269-79b7f100-879b-11ea-837f-6dcca1bb188b.png)

**Comment by timneutkens** [comment] 2020-04-26 15:08
@barbogast can you try upgrading to next@canary? We made the compilation throw an error when you try to import from `'next'` directly 👍

**Comment by barbogast** [comment] 2020-04-26 18:47
For canary I get the same error message (see screenshot).

**Comment by vernak2539** [comment] 2020-04-27 15:30
A coworker of mine had the same issue as this, working on the same code as me when I originally had this problem. 

To fix it, we had to use yarn to install the deps (even though the project hadn't used it before). Then it worked. We were then able to delete the `node_modules` folder and use npm to install deps. After this, it worked again. 

I have a feeling it was some funky thing going on with our dependencies, but can't be sure. Upgrading next to the latest version didn't help them solve the issue.

**Comment by warcraft14115** [comment] 2020-07-03 17:40
@vernak2539 Do you have error like me? [#14817](https://github.com/vercel/next.js/issues/14817)

**Comment by amanKumar689** [comment] 2021-05-31 11:44
Next js provides wrong error information

**Comment by amanKumar689** [comment] 2021-05-31 11:44
it shows file (fs) module not found but problem was syntax error i used a variable that is undefined

**Comment by amanKumar689** [comment] 2021-05-31 11:45
plzz tell NEXT js team solve  bugs

**Comment by timneutkens** [comment] 2021-05-31 13:35
Please open a new issue following the issue template which includes providing a reproduction.

**Comment by balazsorban44** [comment] 2022-01-28 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
