### ISSUE TITLE
Request: Example for debugging next.js application in vscode

### ISSUE THREAD

**Issue by iliran11** [zeit/next.js#10516] opened 2020-02-13 08:18 UTC
# Feature request

## Describe the solution you'd like
A detailed example how to properly debug typescript next.js in vscode - both in client side and in server side.

## Additional context

Was googling and reading spectrum chat. Saw only partial,outdated  and semi-working examples for debugging next.js with vscode.

**Comment by timneutkens** [comment] 2020-02-13 12:23
Duplicate of #4571

**Closed by timneutkens** 2020-02-13 12:23 UTC

**Comment by vvo** [comment] 2020-03-03 14:30
Hey there, I just got it working in latest Next.js versions too, I created a documentation page for Next.js website, let me know what you think: https://github.com/zeit/next.js/pull/10807

**Comment by balazsorban44** [comment] 2022-01-30 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
