### ISSUE TITLE
BaseURL for the Link

### ISSUE THREAD

**Issue by teddylau168** [zeit/next.js#8489] opened 2019-08-23 10:49 UTC
I'm doing a demo with Nex.js, I got a problem with the path.
First of all, I know there are "assetsPrefix", and i have no problem with static content, images, CSS or js. The problem is about the Link

```
import Link from 'next/link'
<Link href="/about"}>.....</Link>
```

Everything is fine when i run the site in development mode via `npm run dev`, but the Link is go wrong when I export via `npm run export`.

For example, I have set the assetsPrefix  in the next.config.js like the following
```
const isProd = process.env.NODE_ENV === 'production'
{ 
assetPrefix: isProd ? 'http://localhost:8888/nextjs/demo' : null
}
```
In development mode, the link becomes `http://localhost:3000/about` that fine.

In Exported static HTML, the link becomes `/about/`, after i click the link, the page url is changed to `http://localhost:8888/about`, actually I prefer `http://localhost:8888/next/demo/about`.

That means the Link base URL is not controlled by "assetPrefix", doesn't it?

**Comment by teddylau168** [comment] 2019-08-23 10:58
So far, I made a custom baseURL function ...
```
<Link href={path} as={baseURL(path)}>
```

It would be great if there's a better solution.

**Comment by Timer** [comment] 2019-08-23 13:42
This is a duplicate of https://github.com/zeit/next.js/issues/4998. Please follow it for updates.

**Closed by Timer** 2019-08-23 13:42 UTC

**Comment by balazsorban44** [comment] 2022-01-31 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
