### ISSUE TITLE
Using Inferno Example - TypeError

### ISSUE THREAD

**Issue by justsee** [zeit/next.js#703] opened 2017-01-09 00:06 UTC
Using [latest Inferno example](https://github.com/zeit/next.js/tree/9163da459e2cb078c5d4792696513b48d1b3c75d/examples/using-inferno) renders and appears to work, but a TypeError is thrown in the console with each page request:

```
next.js?e673db6:37 TypeError: instance.componentWillMount is not a function
    at createClassComponentInstance (inferno.node.js?19343be:2039)
    at hydrateComponent (inferno.node.js?19343be:2218)
    at hydrate (inferno.node.js?19343be:2348)
    at hydrateComponent (inferno.node.js?19343be:2227)
    at hydrate (inferno.node.js?19343be:2348)
    at hydrateComponent (inferno.node.js?19343be:2227)
    at hydrate (inferno.node.js?19343be:2348)
    at hydrateRoot (inferno.node.js?19343be:2369)
    at Object.render (inferno.node.js?19343be:2441)
    at doRender (next.js?e673db6:119)
```

I could only see [1 closed issue in Inferno](https://github.com/infernojs/inferno/issues?utf8=%E2%9C%93&q=is%3Aissue%20%22componentWillMount%20is%20not%20a%20function%22%20is%3Aclosed%20) mentioning that error string, and it wasn't clear if it was relevant.

**Comment by timneutkens** [comment] 2017-01-09 21:48
Upstream issue in inferno-compat. From what I could find it's because of this line https://github.com/infernojs/inferno/blob/5e4dc8499cca7617f8350569cccbfb90849baca3/src/server/renderToString.ts#L69. It's already fixed but not included in the bundle.

**Comment by timneutkens** [comment] 2017-01-09 22:09
Found it. https://github.com/infernojs/inferno/blob/5e4dc8499cca7617f8350569cccbfb90849baca3/src/DOM/utils.ts#L39 Creating a PR now.

**Comment by rauchg** [comment] 2017-01-09 22:16
Woah, excellent find @timneutkens

**Comment by timneutkens** [comment] 2017-01-10 11:22
@rauchg Fix was merged. Not sure if we should close this issue. They release really fast, so I think we could close this.

**Comment by pungggi** [comment] 2017-01-11 20:29
hi @timneutkens 
journey is not over yet, using infoerno 1.1.2:
TypeError: **instance.getChildContext** is not a function
    at createClassComponentInstance (inferno.node.js?28ef546:2088)
    at hydrateComponent (inferno.node.js?28ef546:2266)
    at hydrate (inferno.node.js?28ef546:2396)
    at hydrateComponent (inferno.node.js?28ef546:2275)
    at hydrate (inferno.node.js?28ef546:2396)
    at hydrateComponent (inferno.node.js?28ef546:2275)
    at hydrate (inferno.node.js?28ef546:2396)
    at hydrateRoot (inferno.node.js?28ef546:2417)
    at Object.render (inferno.node.js?28ef546:2489)
    at doRender (next.js?0ca01b5:119)

**Comment by timneutkens** [comment] 2017-01-12 07:03
@pungggi hmm, I'll have a look into this 👍

**Comment by pungggi** [comment] 2017-02-02 19:46
when checking null on "childContex" it will throw a new errror
![image](https://cloud.githubusercontent.com/assets/5635709/22565508/ac338a22-e988-11e6-857a-dd9f9ac6c048.png)

**Comment by timneutkens** [comment] 2017-02-02 19:51
@pungggi you actually have to check `isNullOrUndef(instance.getChildContext)`. I've already looked into this. Just have to test it a bit more.

**Comment by pungggi** [comment] 2017-02-02 20:18
doh! you are right, thank you

**Comment by timneutkens** [comment] 2017-02-02 20:25
@pungggi I'll create a PR for it. Already had written the code at the right place. Just hadn't had the time to test it thoroughly 😄

**Comment by jazzido** [comment] 2017-02-06 18:16
I'm still seeing this issue on `inferno^1.2.2`.

![image](https://cloud.githubusercontent.com/assets/27584/22660132/67cc21e4-ec6e-11e6-8974-c9157f316a5c.png)

**Comment by timneutkens** [comment] 2017-02-06 19:02
@jazzido the issue turned out to be a bit bigger than I initially thought. @lukeed is going to take a look at it sometime.

**Comment by lukeed** [comment] 2017-02-08 02:12
Sorry, I was traveling. Now back to my normal work schedule 👍

**Comment by abstracthat** [comment] 2017-03-01 17:20
Are you able to take a look @lukeed? Would love to use Inferno with Next!

**Comment by lukeed** [comment] 2017-03-01 17:46
Thanks @abstracthat, looking at it now. The ball is now in Next.js's court as it looks like the `inferno-compat` issue was fixed.

@timneutkens @rauchg @arunoda: While building from the `examples` folder, the `dev` and `build` tasks traverse upwards & pull `React` and `ReactDOM` from the root's node_modules directory. This allows Next.js to be built. However, once in the browser, the `prefetch.js` file throws in the browser because _it_ is expecting React to be present, when it is not. It does not get the memo that `React` and `ReactDOM` have been aliased.

If I reproduce/move the `examples/using-inferno` directory outside of the `next.js` root, the `dev` and `build` tasks fail to run _because internal Next.js files aren't respecting aliases_. This is the same problem as above---this is just a more abrupt & concrete illustration of what's happening.

```js
// next.config.js
module.exports = {
  webpack: function (config) {
    config.resolve.alias = {
      'react': 'inferno-compat',
      'react-dom': 'inferno-compat'
    }
    return config
  }
}
```

**Closed** 2017-06-11 22:00 UTC
Labels: Is Upstream
