### ISSUE TITLE
options has an unknown property 'localIdentName'

### ISSUE THREAD

**Issue by dijer119** [zeit/next.js#8961] opened 2019-10-04 07:08 UTC
# Bug report

## Describe the bug
next.config.js
```
module.exports = withCSS(withSass({
  cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: "[local]___[hash:base64:5]",
  },
  webpack(config) {
    HACK_removeMinimizeOptionFromCssLoaders(config);
    config.module.rules.push({
      test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
      use: {
        loader: 'url-loader',
        options: {
          limit: 100000
        }
      }
    })
    // config.module.rules.push({
    //   test: /\.scss$/,
    //   use: [
    //   ]
    // })
    return config
  },
  sassLoaderOptions: {
    sourceMap: true
  }
}));
```

<img width="1055" alt="스크린샷 2019-10-04 오후 4 06 05" src="https://user-images.githubusercontent.com/3210053/66187934-f0d34e00-e6c0-11e9-82ea-f3d4d8f6900c.png">

if cssModule/cssLoaderOptions is removed, not problem..
why error plz?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: macOS
- Browser : chrome
- Version of Next.js: 9.0.7

**Comment by royalbhati** [comment] 2019-10-04 07:17
This is fixed in next@9.0.8-canary.3 
Try updating next tothe  latest canary build

**Comment by dijer119** [comment] 2019-10-04 08:05
i tried to install next@9.0.8-canary.3, but the same error occurred

**Comment by royalbhati** [comment] 2019-10-04 08:23
> i tried to install next@9.0.8-canary.3, but the same error occurred

npm install --save next@canary

**Comment by royalbhati** [comment] 2019-10-04 08:24
> i tried to install next@9.0.8-canary.3, but the same error occurred

Are you sure you are on "next@9.0.8-canary.3 ? "

**Comment by royalbhati** [comment] 2019-10-04 08:28
If this doesnt work try this workaround suggested by @arunpdl for this [same issue](https://github.com/zeit/next-plugins/issues/541``)

**Comment by Timer** [comment] 2019-10-04 10:47
Please try `next@9.0.8-canary.4` instead.

**Closed** 2019-10-04 13:23 UTC

**Comment by dijer119** [comment] 2019-10-05 01:20
the same error occurred... 

```
 "dependencies": {
    "@zeit/next-css": "^1.0.1",
    "@zeit/next-sass": "^1.0.1",
    "axios": "^0.19.0",
    "classnames": "^2.2.6",
    "next": "^9.0.8-canary.4",
    "node-sass": "^4.12.0",
    "prettier": "^1.18.2",
    "react": "^16.10.1",
    "react-dom": "^16.10.1",
    "sass-loader": "^8.0.0"
  },
```
<img width="1070" alt="스크린샷 2019-10-05 오전 10 19 39" src="https://user-images.githubusercontent.com/3210053/66247620-abaf2a80-e759-11e9-90de-30ddddf37e09.png">

**Comment by Timer** [comment] 2019-10-05 01:25
@dijer119 please provide a fully reproducible project. Otherwise, we cannot fix this.

**Comment by dijer119** [comment] 2019-10-05 01:58
@Timer 
i made sample project
please check it.
https://github.com/dijer119/next-style

**Comment by Timer** [comment] 2019-10-05 02:01
@dijer119 you must remove `HACK_removeMinimizeOptionFromCssLoaders`... this code is causing it to break.

**Comment by dijer119** [comment] 2019-10-05 02:06
@Timer 
If removed, the error below will occur.
Module not found: Can't resolve 'css-loader/locals' in '/Users/dijer/dev/workspace_sa/next-style'

**Comment by Timer** [comment] 2019-10-05 02:23
@dijer119 fix up in https://github.com/zeit/next.js/pull/8970. Will release as `next@9.0.8-canary.5` shortly.

**Comment by dijer119** [comment] 2019-10-05 09:14
@Timer
It's fixed. Thank you.

**Comment by samao** [comment] 2019-10-12 11:27
same issue @9.1.1

**Comment by Timer** [comment] 2019-10-13 02:21
You may need 9.1.2-canary.1.

**Comment by canrozanes** [comment] 2020-03-19 22:11
I'm having the exact same issue while trying to update from next 9.2.1 to 9.3.1.

**Comment by balazsorban44** [comment] 2022-01-30 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
