### ISSUE TITLE
Compile problems during deployment

### ISSUE THREAD

**Issue by monsterooo** [zeit/next.js#11855] opened 2020-04-13 12:16 UTC
# Bug report

## Describe the bug

When I run next build locally everything is fine. But an error occurred when running next build on the server (Ubuntu) online.

## To Reproduce

On Ubuntu 18.4

1. Run `next build`

## Expected behavior

```

> Using external babel configuration
> Location: "/Users/monsterooo/Desktop/git/coderlane/.babelrc"
Creating an optimized production build

Compiled successfully.

Warning: You have opted-out of Automatic Static Optimization due to getInitialProps in pages/_app.
Read more: https://err.sh/next.js/opt-out-auto-static-optimization

Automatically optimizing pages

Page                            Size     First Load
┌ λ /                           3.37 kB      150 kB
├   /_app                       24.5 kB     82.9 kB
├ λ /setting                    895 B        160 kB
├ λ /signup                     2 kB         157 kB
└ λ /test                       2.02 kB      144 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
```

## Screenshots

Compiling on my online server failed

![image](https://user-images.githubusercontent.com/18432680/79119543-2d47db00-7dc3-11ea-90be-198706f2a282.png)

## System information

- OS: Ubuntu 18.4
- Browser None
- Version of Next.js v9.3.0
- Version  of Node   v10.18

## Additional context

What do you think? Or is there a better way to debug. thank you for your time

**Comment by monsterooo** [comment] 2020-04-13 12:19
My webpack configuration

```
webpack(config, options) {
    config.resolve.alias['~'] = path.resolve(__dirname);
    if (!options.isServer) {
      config.resolve.alias['@sentry/node'] = '@sentry/browser'
    }

    return config;
  }
```

**Comment by Timer** [comment] 2020-04-13 17:07
Duplicate of #11742 

Please double check your import matches your filename casing.

**Closed by Timer** 2020-04-13 17:07 UTC

**Comment by balazsorban44** [comment] 2022-01-30 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
