### ISSUE TITLE
Keep scroll on navigation between pages

### ISSUE THREAD

**Issue by BramDecuypere** [zeit/next.js#10010] opened 2020-01-09 14:56 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I'm currently struggling to find a good way to always keep the scroll height when navigating between 2 pages. It would be great to find a document explaining or an example. The component is being unmounted automatically. Which shouldn't be the case in my opinion?

## Describe the solution you'd like

A. Make sure the component stays alive when navigating from and to component. So the scroll height will be on the same spot.

## Describe alternatives you've considered

On navigation, I'm currently scrolling towards the correct scrollheight, but with inconsistent behaviour.

**Comment by timneutkens** [comment] 2020-01-09 15:01
Duplicate of #8193

**Closed by timneutkens** 2020-01-09 15:01 UTC

**Comment by balazsorban44** [comment] 2022-01-30 16:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
