### ISSUE TITLE
`http://localhost:3000/_error` reloads indefinitely

### ISSUE THREAD

**Issue by lcswillems** [zeit/next.js#8768] opened 2019-09-17 12:17 UTC
# Bug report

## Describe the bug

`http://localhost:3000/_error` reloads indefinitely.

## To Reproduce

```
yarn create next-app test
cd test
yarn dev
```

And go to `http://localhost:3000/_error`.

## Expected behavior

I expect to have a 404 error, similar to calling `http://localhost:3000/_document`, `http://localhost:3000/_app` or any other non-existing page.

## System information

- OS: Linux
- Browser (if applies): Chrome
- Version of Next.js: 9.0.5

**Comment by ijjk** [comment] 2019-09-17 14:31
Hi this appears to be a duplicate of #8036 Closing in favor of that one

**Closed by ijjk** 2019-09-17 14:31 UTC

**Comment by balazsorban44** [comment] 2022-01-31 04:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
