### ISSUE TITLE
withRouter hoc, useRouter hook not working anymore after canary upgrade

### ISSUE THREAD

**Issue by gurkerl83** [zeit/next.js#9105] opened 2019-10-16 19:57 UTC
# Bug report

## Describe the bug

The application uses withRouter hoc and useRouter hook to get the current pathname from router. After upgrading from 9.1.2-canary.3 to 9.1.2-canary.4 the application responds with "property 'pathname' of null".

The error occurs using the withRouter hoc.

Next 9.1.2-canary.4 introduces changes to the context.

This is probably related to modifications made in makePublicRouterInstance of packages/next/pages/_app.tsx.

Or to changes made with ComposedComponent in packages/next/client/with-router.tsx.

Important: Started the app in both dev and prod mode. The wired thing is that prod is starting while on dev i get the reported error.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2]

**Comment by timneutkens** [comment] 2019-10-16 23:07
As per the issue template please provide a clear and concise reproduction. We have tests to ensure `withRouter` and `useRouter` work.

---

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior

A clear and concise description of what you expected to happen.

## Screenshots

If applicable, add screenshots to help explain your problem.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2]

## Additional context

Add any other context about the problem here.

**Comment by devknoll** [comment] 2019-10-17 14:12
Actually @timneutkens I think I have a hunch of what's happening. If you used `withRouter` before #9083, you'd get a `makePublicRouterInstance(router)` during SSR, whereas now you'll only get a `router`, which maybe prevents you from reading e.g. `pathname`?

**Comment by Timer** [comment] 2019-10-17 15:26
Closing as the user did not provide a reproduction. We'll be happy to take a look if you can show us how to reproduce this!

**Closed by Timer** 2019-10-17 15:26 UTC
Labels: Type: Needs Investigation, priority: low

**Comment by gurkerl83** [comment] 2019-10-17 17:36
Thanks for looking into it. I just looked at my import statements, and they are the reason for the problem reported. I am on typescript; for this reason, I require WithRouterProps.

Previously I used because WithRouterProps are only available from this package.
=> working up until 9.1.2-canary.3
import { withRouter, WithRouterProps } from 'next/dist/client/with-router';

From 9.1.2-canary.4 upwards, I needed to adjust the imports, and it is working again with the following.

import { withRouter } from 'next/router';
import { WithRouterProps } from 'next/dist/client/with-router';

Thx, sry for the confusion.

**Comment by lasseborly** [comment] 2019-10-31 12:13
I'm also encountering this problem when upgrading to 9.1.2.
`this.context` seems to be `null` when passed to the component which results in `router` being `null`. I don't have the time to make a complex sandbox right now but will have to at some point.

**Comment by macrozone** [comment] 2019-11-08 13:20
> I'm also encountering this problem when upgrading to 9.1.2.
> `this.context` seems to be `null` when passed to the component which results in `router` being `null`. I don't have the time to make a complex sandbox right now but will have to at some point.

seems to be related to https://github.com/zeit/next.js/issues/9350

**Comment by balazsorban44** [comment] 2022-01-30 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
