### ISSUE TITLE
style miss after Router.push when use webpack splitChunks

### ISSUE THREAD

**Issue by okyping** [zeit/next.js#11876] opened 2020-04-14 10:23 UTC
# Bug report
When using

`
import Link from 'next/link'
export default () =>
  <div>
    <Link href="/about">
      <a>here</a>
    </Link>
    to read more
  </div>
`

or

`
import Router from 'next/router'
export default () =>
  <div>
    Click <span onClick={() => Router.push('/about')}>here</span> to read more
  </div>
`

and then use webpack optimization.splitChunks to optimize project packaging. eg:

splitChunks: {
            chunks: 'initial',
            minSize: 30000,
            maxSize: 0,
            minChunks: 1,
            maxAsyncRequests: 5,
            maxInitialRequests: 3,
            automaticNameDelimiter: '~',
            name: true,
            cacheGroups: {
                vendors: {
                    test: /[\\/]about[\\/]/,
                    priority: 100
                }
            }
        }

when jump to `/about`, the about.[hash].js was loaded, but the about.[hash].css was not loaded，so the style was invalid .

## Describe the bug

style miss after route jump，because only js dependencies are loaded, css dependencies will not be loaded

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to  xxx.com
2. router to  xxx.com/about

**Comment by timneutkens** [comment] 2020-04-14 11:22
Duplicate of https://github.com/zeit/next.js/discussions/11869

Highly recommend not editing the webpack configuration, especially as the changes made seem incorrect.

**Closed** 2020-04-14 11:30 UTC

**Comment by balazsorban44** [comment] 2022-01-30 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
