### ISSUE TITLE
Outdated example using hoist-non-react-statics

### ISSUE THREAD

**Issue by Timer** [zeit/next.js#7340] opened 2019-05-15 12:32 UTC
@timneutkens our team ran into this as well. We're following [this example from the next.js examples/ folder](https://github.com/zeit/next.js/blob/canary/examples/with-react-relay-network-modern/pages/index.js#L16), but with the above change, the `static query = ...` gets dropped by `withRouter`.

What would you recommend in this case? We're planning to use a custom `withRouter` that doesn't drop our statics in some places, and remove `withRouter` in some others - but it doesn't feel like a great solution.

I get where you're coming from RE: bundle size, but I think a common expectation when using an HOC like `withRouter` is that it doesn't mess with your component beyond adding some props, and generally Just Works.

_Originally posted by @holmesal in https://github.com/zeit/next.js/issues/6790#issuecomment-492549741_

**Comment by exogen** [comment] 2019-05-29 03:25
FYI, this is currently breaking our upgrade to 8.x, since we attach statics to various components that then use `withRouter`. We very surprised to see that `withRouter` no longer hoists them.

**Comment by timneutkens** [comment] 2019-08-10 13:13
Going to close this as we have `useRouter` now.

**Closed by timneutkens** 2019-08-10 13:13 UTC

**Comment by balazsorban44** [comment] 2022-01-31 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
