### ISSUE TITLE
Production prerendering with SASS and URQL

### ISSUE THREAD

**Issue by erickm** [zeit/next.js#8549] opened 2019-08-29 07:59 UTC
Hi,

I've run into a problem while running my next.js app in production. I use next.js with [URQL](https://github.com/FormidableLabs/urql) and the [ZEIT SASS package](https://github.com/zeit/next-plugins/tree/master/packages/next-sass) for next.js. When i run the app in dev mode it runs fine while navigating the routes. After i build the app and start it in production i run into a problem though.

If i go to my second route directly (localhost:3000/test, without a graphql query) and try navigating to a route with a query (localhost:3000/) it won't execute the query and stays on the initial route (localhost:300/test). I first reported a bug with the guys from URQL (https://github.com/FormidableLabs/urql/issues/411) but they couldn't help me.

To reproduce my issue i created a repo to check out: https://github.com/erickm/next-urql-sass/tree/master/examples/3-ssr-with-nextjs.

It looks like the error occurs while passing the data props to a custom component (only when using the sass function, without the sass pacakge it works fine).

To reproduce:
1. checkout the repo & install
2. `yarn build && yarn start`
3. navigate to `localhost:3000/test`
4. try to go to the home page (here is where i get stuck)

When i remove withSass in the next.config.js and remove the sass imports and sytles, build it and start it again it works fine.

For reference i created a gif:
![navigating](https://user-images.githubusercontent.com/2747197/63921600-635a6980-ca43-11e9-9d9e-9e1d6c331138.gif)

**Comment by timneutkens** [comment] 2019-08-29 11:00
Duplicate of https://github.com/zeit/next-plugins/issues/282

**Closed by timneutkens** 2019-08-29 11:00 UTC

**Comment by danjebs** [comment] 2020-10-23 23:37
@erickm I was wrestling with setting up SSR with Preact/Next all day till I went through your repro repo - saved my goat's cheese! Hat tip + potentially useful discussion here https://github.com/FormidableLabs/urql/discussions/1069

**Comment by balazsorban44** [comment] 2022-01-29 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
