### ISSUE TITLE
Site pages navigation turns each page to render from server, but why if pages prefetched?

### ISSUE THREAD

**Issue by qqqqqz** [zeit/next.js#9839] opened 2019-12-26 19:56 UTC
When i use next.js the <Link> component, it s okey described in documentation and mentioned, that by default it turns prefetching each page ( on which the link is refered to). But i click on link for navigating- the page forced to render from server-side again, but why if its prefetched?

Just create <Link> navigation bar and navige, simply each page rendered from server. But in documentation it says , that page prefetched  by default if <Link> used.

It can be reproduced on each simple example with navigations

As i expected, it is that when i enter site url- the first page load should be rendered from server, and when, if i click some l ink to other site page, it should be rendered on the client side. But now each site navigation rendered from server-  why?

**Comment by ijjk** [comment] 2019-12-26 20:14
Hi, please follow the issue template. For client-side navigation to work properly you must `next/link` or `next/router`. A normal `a` tag will still trigger a full navigation causing a render on the server. Also, if you provide an invalid `href` value (e.g. a non-page) for `next/link` or `next/router` it will fallback to triggering a server render.

I'm gonna close this since a reproduction wasn't provided

**Closed by ijjk** 2019-12-26 20:14 UTC

**Comment by qqqqqz** [comment] 2019-12-26 21:31
@ijjk but why it triggering a server render, if pages that addressed inside the <Link> are prefetched, and its mentioned in documentation

**Comment by ijjk** [comment] 2019-12-26 21:37
Hi, it shouldn't be if you are using `next/link` and `next/router` correctly. If you can provide a reproduction where this isn't the case we'd be happy to investigate it!

**Comment by balazsorban44** [comment] 2022-01-30 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
