### ISSUE TITLE
API route works locally but not in production

### ISSUE THREAD

**Issue by tenjojeremy** [zeit/next.js#8383] opened 2019-08-15 20:54 UTC
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone https://github.com/tenjojeremy/test-nextjs-simple.git
2. run `yarn`
3. run `yarn start`
4. open localhost
5. you should see 3 posters
![posters](https://user-images.githubusercontent.com/25231946/63126077-12477180-bf7d-11e9-8392-44d335cf7964.png)

3. run `now`
4. open production site 
5. you will see a 500 error
![500](https://user-images.githubusercontent.com/25231946/63126152-3c009880-bf7d-11e9-9dc4-b828fd5c2d93.png)

6. open runtime logs in your dashboard
7. see
![error](https://user-images.githubusercontent.com/25231946/63125928-cac0e580-bf7c-11e9-8e1b-c9a7d9275d02.png)

## Expected behavior

Should display 3 movie posters in production not a 500 error

**Comment by huv1k** [comment] 2019-08-16 12:02
Hey @tenjojeremy, thanks for reporting this. This should be fixed with this PR #8334

**Comment by tenjojeremy** [comment] 2019-08-16 12:06
@huv1k  Great, thank you.

**Comment by timneutkens** [comment] 2019-11-09 21:30
Closing this as duplicate of #8251

**Closed by timneutkens** 2019-11-09 21:30 UTC
Labels: Type: Bug

**Comment by balazsorban44** [comment] 2022-01-30 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
