### ISSUE TITLE
`next build` slows down due to "__tests__" directories within "pages/"

### ISSUE THREAD

**Issue by mikenikles** [zeit/next.js#2026] opened 2017-05-20 05:10 UTC
I noticed `next build` started to take quite some time, so long in fact that it started to fail with an exit code 137 when I deploy to `now`. It turns out `__tests__` directories within `pages/` caused it. Once I deleted them, which includes Jest snapshot files, `next build` took about a minute and worked fine when deploying to `now`.

My apologies if this has been discussed already, but I couldn't find anything on Github or in Slack. Is this a known issue? Do others have their test files within `pages/`?

**Comment by timneutkens** [comment] 2017-05-20 06:12
Duplicate of https://github.com/zeit/next.js/issues/1914

**Closed by timneutkens** 2017-05-20 06:12 UTC
