### ISSUE TITLE
IE (Internet Explorer) Error 💩

### ISSUE THREAD

**Issue by philcockfield** [zeit/next.js#473] opened 2016-12-22 07:09 UTC
Running a simple page that references nothing other than React within Next.js on IE9...11 causes the following error:

![image](https://cloud.githubusercontent.com/assets/185555/21417816/f79e2242-c881-11e6-84af-f2dc96971731.png)

This occurs with both next.js version `1.2.3` and `2.0.0-beta.0`.

An example of this on IE9 can be seen here (courtesy of @arunoda):

https://www.browserling.com/browse/win/vista/ie/9/https%3A%2F%2F37a02b6c.ngrok.io%2Fabout

The code which is throwing the error seems related to stylesheets:

```
Object.assign(StyleSheet.prototype, {
  getSheet: function getSheet() {
    return sheetForTag(last(this.tags));
  },
  inject: function inject() {
    var _this = this;

    if (this.injected) {
      throw new Error('already injected stylesheet!');
    }
    if (isBrowser) {
      this.tags[0] = makeStyleTag();
    } else {
  ...
```

`Object.assign` is not in ES5 and so this is perhaps a babel related problem where an external library has been referenced that has not been transpiled.

This will not be showing up as an error in Chrome/Firefox (and all the other "big boy browsers") as they have started to implement some of the ES6 spec natively.

**Comment by philcockfield** [comment] 2016-12-22 07:38
TEMPORARY HACK.  To work around this until this is fixed, you can add:

        <script
          type='text/javascript'
          src='https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.20.0/polyfill.min.js' />

to the page.

**Comment by arunoda** [comment] 2016-12-22 08:20
Here's the source of the issue: https://github.com/threepointone/glamor/issues/155

**Comment by luisrudge** [comment] 2016-12-22 16:59
I think polyfills should be added manually if the dev needs to support old browsers

**Comment by arunoda** [comment] 2016-12-22 17:12
@luisrudge actually it's a problem of glamor. It's not doing babel transpiling properly.

**Comment by philcockfield** [comment] 2016-12-22 23:05
@luisrudge I agree with @arunoda.  `Object.assign` transpiles via babel just fine when used within a consuming project.  But it's the NextJS bundle itself which is delivering some un-transpiled code within it.

**Comment by arunoda** [comment] 2016-12-22 23:09
@philcockfield I already send a PR for glamor and I hope they'll accept it and cut a new release.
See: https://github.com/threepointone/glamor/pull/166

**Comment by philcockfield** [comment] 2016-12-22 23:16
Rock and roll @arunoda!  Awesome 💯

**Comment by thisguychris** [comment] 2016-12-25 08:50
@arunoda next.js is using Object.assign.  It's under the utils function https://github.com/zeit/next.js/blob/master/lib/utils.js#L20, the #513 fixes this with just adding a simple transform.  

I do believe this fix #513 is better instead of adding the whole babel-polyfill as a dependency.  babel-polyfill is actually pretty big, and adding that should be on the userland instead of the library.

This same fix applies in glamor, instead of adding babel-polyfill, its better to add this transform.

**Comment by arunoda** [comment] 2016-12-25 10:26
@thisguychris yes Next.js Object.assign and many other ES2015+ features.
Actually, babel's transform runtime is pretty clever and it doesn't include the whole shims/polyfills.

Check the transpiled code of the above mentioned [utils.js](https://gist.github.com/arunoda/dfcc495a78cd907d008634ab4e67bb35#file-utils-js-L7)

So, the issue is not in the Next.js code base and our use of babel-runtime is pretty efficient. If glamor didn't fix this issue, we may need to hot fix it.

**Comment by thisguychris** [comment] 2016-12-25 11:20
@arunoda oh that's good to know! looks like they fixed it in v6 and up, Our app is still in v5 😂

**Comment by arunoda** [comment] 2016-12-27 12:32
Guys, now glamor has a fix for this issue.
We've bumped the glamor version in master and it should work properly.

**But Next.js apps only work on IE9+ versions only.**
That's because of our use of history API.

**Comment by arunoda** [comment] 2016-12-30 10:09
I hope we could close this now.
See^^^

**Closed by arunoda** 2016-12-30 10:09 UTC
Labels: Is Upstream, Type: Bug

**Comment by philcockfield** [comment] 2016-12-30 17:30
👍
