### ISSUE TITLE
NextJS build breaks when importing a non pre-compiled library (one that has been run through babel but not webpack)

### ISSUE THREAD

**Issue by linasmnew** [zeit/next.js#11264] opened 2020-03-21 23:29 UTC
# Bug report

## Describe the bug
Running into an issue where importing CSS files within my nextApp works perfectly fine, however, installing a library that has only been transpiled (with babel) but not compiled with a module bundler like webpack breaks the build because one of its files has a css import - the same library works perfectly with regular react + webpack setup.

(This also doesn't seem limited to CSS, the same happens with images, or any non JS modules it seems like for that matter.)

The error is:

> Module not found: Can't resolve './style.css' in 'name_of_third_party_package/lib/js/components'

Also tried extending webpack through next.config.js with no luck:

next.config.js

```
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const cssLoaders = ['css-loader']
const sassLoaders = ['css-loader', 'sass-loader']

module.exports = {
  webpack: config => {
    config.module.rules.push(
      {
          test: /\.css$/,
          loader: [
              MiniCssExtractPlugin.loader,
              ...cssLoaders
          ]
      },
      {
          test: /\.scss$/,
          loader: [
              MiniCssExtractPlugin.loader,
              ...sassLoaders
          ]
      }
    )
    config.plugins.push(
      new MiniCssExtractPlugin(),
    )
    return config
  }
}

```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create the most basic fresh next.js app using latest version
2. Import CSS file and observe how it works perfectly
2. Now yarn install or link a library that has been transpiled (with babel) but not compiled with a module bundler like webpack, and one of its files has a CSS import (pretty sure it can be any non JS import)
3. Try to yarn build your nextJS app and observe it crashing with error saying CSS module not found

## Expected behavior
I expect it to bundle the CSS assets (applies to other non JS assets too) with my own assets in my NextJS app, i.e. in this case the CSS should be combined with my own CSS.

## Additional context
**Note: Replicating above steps with regular react + webpack app using the same webpack loaders works perfectly fine, hence why it feels like a nextJS issue.**

**Comment by timneutkens** [comment] 2020-03-23 08:36
Duplicate of https://github.com/zeit/next.js/issues/706

**Closed by timneutkens** 2020-03-23 08:36 UTC

**Comment by balazsorban44** [comment] 2022-01-30 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
