### ISSUE TITLE
_next/static/style.css net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by Jero786** [zeit/next.js#5641] opened 2018-11-09 12:50 UTC
# Bug report
After update version 7, is not longer working the hot reload.

## Describe the bug

Not longer works the hot reload, I force to refresh manually the browser in order to update my scss (I'm using `next-sass`)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `npm run dev`
2. `open browser with port defined and you will able to show the bug`

## Expected behavior
After change my sass files, the browser should update their style properly.

## Screenshots
This is the console log of chrome with the error:

<img width="827" alt="screen shot 2018-11-09 at 9 40 39 am" src="https://user-images.githubusercontent.com/1815487/48263062-9889c280-e403-11e8-911f-a5cfb79837ce.png">

## System information
 - OS: MacOs 10.13.6
 - Browser chrome
- Package dependencies: 
```
 "@zeit/next-sass": "^1.0.2-canary.0",
    "babel-polyfill": "^6.26.0",
    "classnames": "^2.2.6",
    "cross-fetch": "^2.2.2",
    "express": "^4.16.4",
    "fs": "0.0.1-security",
    "immutable": "^3.8.2",
    "lodash": "^4.17.10",
    "next": "^7.0.2-canary.21",
    "next-redux-wrapper": "^2.0.0",
    "node-sass": "4.9.4",
    "prop-types": "^15.6.2",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-notification-system": "^0.2.17",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-devtools-extension": "^2.13.5",
    "redux-immutable": "^4.0.0",
    "redux-thunk": "^2.3.0"
```

my dev dependencies:
```
"devDependencies": {
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^8.2.6",
    "babel-jest": "22.4.3",
    "babel-plugin-module-resolver": "^3.1.1",
    "chai": "^4.1.2",
    "enzyme": "3.2.0",
    "enzyme-adapter-react-16": "1.5.0",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^17.0.0",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.10.0",
    "husky": "^0.14.3",
    "jest": "22.0.1",
    "lint-staged": "^7.3.0",
    "prettier-eslint": "^8.8.2",
    "react-addons-test-utils": "15.6.2",
    "react-test-renderer": "16.2.0",
    "sinon": "^6.1.5",
    "superagent": "^4.0.0-beta.5",
    "supertest": "^3.3.0"
  }
```

my next.config.js

```
const withSass = require('@zeit/next-sass');
const getRoutes = require('./routes');

module.exports = {
	assetPrefix: process.env.NODE_ENV === 'production' ? '/{reponame}' : '',
	exportPathMap: getRoutes,
	generateBuildId: async () => {
		const id = process.env.BUILD_ID;
		return id;
	}
};

module.exports = withSass();
```
my _document

```
// Libs
import Document, {Head, Main, NextScript} from "next/document";

export default class MyDocument extends Document {
    render() {
        return (
            <html lang="en">
            <Head>
                <link rel="stylesheet" href="/_next/static/style.css"/>
            </Head>
            <body>
            <Main/>
            <NextScript/>
            </body>
            </html>
        );
    }
}

```
NOTE: if I remove the link import from here, seems like it works, but when I change the page, the other page is completely un-styled 
 
## Additional context

I try a lot of things, such remove node_module, npm install again, add empty style into _app, everything that I found out there, and nothing seems like works for this bug. 

I will really appreciate if someone have a cue about what's going on.

**Comment by timneutkens** [comment] 2018-11-09 13:29
Possibly related to https://github.com/zeit/next-plugins/issues/282 🤔

**Comment by Jero786** [comment] 2018-11-09 13:34
@timneutkens maybe, but the worst  part of the bug is this error, maybe I could re-name the title of the bug for `Uncaught ReferenceError: dll_xxxxxx is not defined`

<img width="787" alt="error" src="https://user-images.githubusercontent.com/1815487/48265225-bdcdff00-e40a-11e8-98b4-8bdb2308102b.png">

Thank you for you quick response @timneutkens !

**Comment by timneutkens** [comment] 2018-11-09 13:37
Btw this doesn't work correctly:

```
const withSass = require('@zeit/next-sass');
const getRoutes = require('./routes');

module.exports = {
	assetPrefix: process.env.NODE_ENV === 'production' ? '/{reponame}' : '',
	exportPathMap: getRoutes,
	generateBuildId: async () => {
		const id = process.env.BUILD_ID;
		return id;
	}
};

module.exports = withSass();
```

It should be:

```
const withSass = require('@zeit/next-sass');
const getRoutes = require('./routes');

module.exports = withSass({
	assetPrefix: process.env.NODE_ENV === 'production' ? '/{reponame}' : '',
	exportPathMap: getRoutes,
	generateBuildId: async () => {
		const id = process.env.BUILD_ID;
		return id;
	}
});
```

**Comment by Jero786** [comment] 2018-11-09 13:43
@timneutkens Thank you! I replace it :) .... but unfortunately the error is still there.  :(

**Comment by awcross** [comment] 2018-11-10 01:05
I'm getting this error, as well.

```

**Comment by awcross** [comment] 2018-11-10 01:08
Can confirm. I'm getting the `ReferenceError` error, as well.

package.json
```
"dependencies": {
    "@zeit/next-css": "^1.0.1",
    "next": "^7.0.2",
    "react": "^16.6.1",
    "react-dom": "^16.6.1"
},
"devDependencies": {
    "babel-plugin-inline-react-svg": "^1.0.1",
    "eslint-config-xo-react": "^0.16.0",
    "eslint-plugin-react": "^7.7.0",
    "postcss-nested": "^4.1.0",
    "postcss-preset-env": "^6.4.0",
    "xo": "^0.20.3"
},
"babel": {
    "presets": [
        "next/babel"
    ],
    "plugins": [
        "inline-react-svg"
    ]
}
```

**Comment by timneutkens** [comment] 2018-11-10 01:19
Would be really helpful for me if you could provide a minimal repository that I can run 🙏

**Comment by awcross** [comment] 2018-11-10 06:16
@timneutkens Not sure what the issue was but I couldn't reproduce the error with a new repo. I then went back to the original and reinstalled the deps and no more error. 🤷‍♂️

**Comment by timneutkens** [comment] 2018-11-10 07:11
Looks like development mode vs production mode to me

**Comment by timneutkens** [comment] 2018-11-12 16:11
I'm going to close this issue as there is no clear reproduction

**Closed by timneutkens** 2018-11-12 16:11 UTC

**Comment by Jero786** [comment] 2018-11-16 22:19
@timneutkens The error about `Uncaught ReferenceError: dll_xxxxxx is not defined` it still there and you could reproduce it with the following [example](https://github.com/Jero786/nextjs-issue-5641), which is basically the first step of the getting started.

**Comment by tscanlin** [comment] 2019-08-23 08:15
I'm noticing that it only happens when the chrome dev tools are open, not closed. But like you said firefox is fine. Very strange..

**Comment by iMerica** [comment] 2020-01-07 03:37
I was also getting 404s on my CSS bundle. In my case, the problem was not related to Next.js, the problem is serving cached HTML that refers to css files that are no longer in the file system (which can happen easily when self-deploying).

**Steps to Reproduce**
- Configure caching for 1 day (in memcache, redis, whatever).
- Do a deployment.
- Request the page. (page is now in the cache).
- Do a deployment.
- Request the same page. 
- The cached HTML content refers to CSS that is no longer in the filesystem. 💣 💥 .

**Solution**
Bust caches upon deploys, or come up with some other clever caching strategy.

**Comment by digitalsanity** [comment] 2020-12-08 01:51
I had _next/ static chunk errors that I tracked down to needing to remove a final slash from my nginx proxy_pass URL.

**Comment by rehanpunjwani** [comment] 2021-09-28 11:13
I want import styles.css dynamically using link but style.css is not present in static folder and getting 404 error.

**Comment by balazsorban44** [comment] 2022-01-27 17:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
