### ISSUE TITLE
nextjs.org/learn/excel/typescript example does not work as intended

### ISSUE THREAD

**Issue by morgansliman** [zeit/next.js#8502] opened 2019-08-24 10:38 UTC
# Examples bug report

## Example name

TypeScript

## Describe the bug

There are two places where the expected outcome of the example is not what happened for me locally. First, no `tsconfig.json` was created for me upon following all steps up to that point. However, once I created my own `tsconfig.json` file to set the `"strict": true` setting, the dev process auto-filled it with some default settings. 

Second, even with strict set to `true`, I am still seeing the same issue described [in this issue](https://github.com/zeit/next.js/issues/8076), despite it being labeled as fixed. No errors are shown either in browser or in the server console, and the user agent displays in the browser as usual.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Follow the example instructions here:
https://nextjs.org/learn/excel/typescript

## Expected behavior

Expected the example to behave locally as the instructions explain it will.

## System information

- OS: macOS
- Browser: Brave Version 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)
- Version of Next.js: 9.0.4
- Typescript: 3.5.3

**Comment by Timer** [comment] 2019-08-24 16:43
This is fixed in Next.js 9.0.5+, which is being released now. 😄 Thanks for reporting!

**Closed by Timer** 2019-08-24 16:43 UTC

**Comment by balazsorban44** [comment] 2022-01-31 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
