### ISSUE TITLE
How to use module.exports in Next.js

### ISSUE THREAD

**Issue by antonioOrtiz** [zeit/next.js#8114] opened 2019-07-25 18:51 UTC
In my next.js app, I am trying to expose this `env` object in my `next.config.js` following this [prescription][1] to my app;

    //next.config.js

    const withCSS = require('@zeit/next-css');
    
    module.exports = withCSS({
      webpack(config) {
        config.module.rules.push({
          test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
          use: {
            loader: 'url-loader',
            options: {
              limit: 100000,
              name: '[name].[ext]'
            }
          }
        });
        return config;
      }
    });
    
      //trying to expose the env {} below

        module.exports = {
          env: {
            DEVELOPMENT_DB_DSN: 'mongodb+srv://antonioHillfinder:foo@hillfinder-qjxuo.azure.mongodb.net/development?retryWrites=true&w=majority',
            PRODUCTION_DB_DSN: 'mongodb+srv://antonioHillfinder:bar@hillfinder-qjxuo.azure.mongodb.net/production?retryWrites=true&w=majority',
            TEST_DB_DSN: 'mongodb+srv://antonioHillfinder:foobar@hillfinder-qjxuo.azure.mongodb.net/test?retryWrites=true&w=majority'
          }
        };

I tried this too:

    var withCSS = require('@zeit/next-css');
    
    
    module.exports = {
      withCSS: withCSS({
        webpack(config) {
          config.module.rules.push({
            test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
            use: {
              loader: 'url-loader',
              options: {
                limit: 100000,
                name: '[name].[ext]'
              }
            }
          });
          return config;
        }
      }),
      env: {
        DEVELOPMENT_DB_DSN: `mongodb+srv://antonioHillfinder:foo@hillfinder-qjxuo.azure.mongodb.net/development?retryWrites=true&w=majority`,
        PRODUCTION_DB_DSN: `mongodb+srv://antonioHillfinder:bar@hillfinder-qjxuo.azure.mongodb.net/production?retryWrites=true&w=majority`,
        TEST_DB_DSN: `mongodb+srv://antonioHillfinder:foobar@hillfinder-qjxuo.azure.mongodb.net/test?retryWrites=true&w=majority`
      }
    };

And I'm trying to use them here:

    var express = require('express')
    var next = require('next')
    var session = require('express-session')
    var MongoStore = require('connect-mongo')(session)
    var cookieParser = require('cookie-parser')
    var bodyParser = require('body-parser')
    var cors = require('cors')
    var morgan = require('morgan')
    var HttpStatus = require('http-status-codes')
    
    var PORT = process.env.PORT || 8016
    var dev = process.env.NODE_ENV !== `production`;
    
    function processNODEENVCheckerAndServerRuntimeConfigSetter(ENV) {
      var environment,
        environments = {
          'production': () => {
            environment = process.env.PRODUCTION_DB_DSN; //trying to use them here
            return environment;
          },
          'test': () => {
            environment = process.env.TEST_DB_DSN; //trying to use them here
            return environment;
          },
          'default': () => {
            environment = process.env.DEVELOPMENT_DB_DSN; //trying to use them here
            console.log("environment ", environment);
            return environment;
          },
        };
      (environments[ENV] || environments['default'])();
    
      return environment
    }
    
    var db = processNODEENVCheckerAndServerRuntimeConfigSetter(process.env.NODE_ENV)
    
    var NextApp = next({ dev })
    var handle = NextApp.getRequestHandler()
    
    var mongoose = require('mongoose')
    
    NextApp.prepare()
      .then(() => {
        const app = express()
        mongoose.connect(db, { useNewUrlParser: true })
        mongoose.Promise = global.Promise
    
        mongoose.connection
          .on('connected', () => {
            console.log(`Mongoose connection open on ${db}`)
          })
          .on('error', err => {
            console.log(`Connection error: ${err.message}`)
          })
    
        app.use(bodyParser.json())
        app.use(bodyParser.urlencoded({ extended: true }))
        app.use(morgan('dev'))
    
        app.use(cookieParser())
    
        session({
          secret: 'very secret 12345',
          resave: true,
          saveUninitialized: false,
          store: new MongoStore({ mongooseConnection: mongoose.connection })
        })
    
        app.use(cors())
    
        app.use('/auth', require('./auth'))
    
        app.get('*', (req, res) => {
          return handle(req, res)
        })
    
        app.use(errorHandler, function (error, req, res, next) {
          res.json({ message: error.message })
        })
    
        app.listen(PORT, err => {
          if (err) throw err
          console.log(`> Ready on http://localhost:${PORT}`)
        })
      })
      .catch(err => {
        console.error(err)
      })

In the end the app just breaks and I get this error...

    environment  undefined
    
    Compiled successfully!
    
    Note that pages will be compiled when you first load them.
    { MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
        at new MongooseError (/Users/antoniopavicevac-ortiz/Dropbox/developer_folder/hillfinder/node_modules/mongoose/lib/error/mongooseError.js:10:11)
        at NativeConnection.Connection.openUri (/Users/antoniopavicevac-ortiz/Dropbox/developer_folder/hillfinder/node_modules/mongoose/lib/connection.js:519:11)
        at Mongoose.connect (/Users/antoniopavicevac-ortiz/Dropbox/developer_folder/hillfinder/node_modules/mongoose/lib/index.js:314:15)
        at NextApp.prepare.then (/Users/antoniopavicevac-ortiz/Dropbox/developer_folder/hillfinder/server/index.js:68:14)
        at process._tickCallback (internal/process/next_tick.js:68:7)
      message:
       'The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.',
      name: 'MongooseError' }
    [nodemon] clean exit - waiting for changes before restart

Not sure why I get `undefined` from `console.log("environment ", environment);` in the `var db = processNODEENVCheckerAndServerRuntimeConfigSetter(process.env.NODE_ENV)
` statement/function?

  [1]: https://nextjs.org/docs#build-time-configuration

**Comment by ijjk** [comment] 2019-07-25 18:59
Closing in favor of spectrum thread [here](https://spectrum.chat/next-js/general/how-to-use-module-exports-in-next-js~2bf80039-8f64-4ea6-8127-bca80ec055d9)

**Closed by ijjk** 2019-07-25 18:59 UTC

**Comment by balazsorban44** [comment] 2022-01-31 10:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
