### ISSUE TITLE
Page size huge increase when updating from 9.0.2 to 9.3.3?

### ISSUE THREAD

**Issue by amaidah** [zeit/next.js#11532] opened 2020-03-31 22:09 UTC
Trying to upgrade from 9.0.2 to 9.3.3 and finding that 9.3.3 increases bundle size heavily. Was there a change in the calculation? I'm finding this very surprising.

Next 9.0.2 React 16.8.6
![image](https://user-images.githubusercontent.com/16659483/78079566-3b2c4380-7361-11ea-95f9-5e4e153d1c73.png)

Next 9.3.2 React 16.13.1
![image](https://user-images.githubusercontent.com/16659483/78079605-4a12f600-7361-11ea-8706-cb0221e83736.png)

**Comment by ijjk** [comment] 2020-03-31 22:34
This appears to be a duplicate of https://github.com/zeit/next.js/issues/11389

**Comment by timneutkens** [comment] 2020-04-01 09:35
Yep we'll track it in #11389

**Closed by timneutkens** 2020-04-01 09:35 UTC

**Comment by balazsorban44** [comment] 2022-01-30 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
