### ISSUE TITLE
First readme example doesn't work.

### ISSUE THREAD

**Issue by FateRiddle** [zeit/next.js#1030] opened 2017-02-08 02:09 UTC
Created folder zeit-next-test, npm init --y, npm i -S next, populated /pages/index.js as instructed, added script "dev":"next", npm run dev. Errors.

npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@3.10.9
3 info using node@v7.2.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle zeit-next-test@1.0.0~predev: zeit-next-test@1.0.0
6 silly lifecycle zeit-next-test@1.0.0~predev: no script for predev, continuing
7 info lifecycle zeit-next-test@1.0.0~dev: zeit-next-test@1.0.0
8 verbose lifecycle zeit-next-test@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle zeit-next-test@1.0.0~dev: PATH: /usr/local/lib/node_modules/.npm_npminstall/npm/3.10.6/npm/bin/node-gyp-bin:/Users/Riddle/code/test/zeit-next-test/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle zeit-next-test@1.0.0~dev: CWD: /Users/Riddle/code/test/zeit-next-test
11 silly lifecycle zeit-next-test@1.0.0~dev: Args: [ '-c', 'next' ]
12 silly lifecycle zeit-next-test@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle zeit-next-test@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: zeit-next-test@1.0.0 dev: `next`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/.npm_npminstall/npm/3.10.6/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/.npm_npminstall/npm/3.10.6/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid zeit-next-test@1.0.0
16 verbose cwd /Users/Riddle/code/test/zeit-next-test
17 error Darwin 15.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
19 error node v7.2.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error zeit-next-test@1.0.0 dev: `next`
22 error Exit status 1
23 error Failed at the zeit-next-test@1.0.0 dev script 'next'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the zeit-next-test package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     next
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs zeit-next-test
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls zeit-next-test
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

page.json:

{
  "name": "zeit-next-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "next"
  },
  "keywords": [],
  "author": "Fate Riddle <fateriddle@foxmail.com>",
  "license": "MIT"
}

**Comment by eezing** [comment] 2017-02-09 00:56
@FateRiddle Not sure if this will help, but your NPM could use an update: ```$ sudo npm update npm```. After that, delete zeit-next-test/node_modules, ```$ npm install``` and give it another shot.

**Comment by timneutkens** [comment] 2017-02-11 23:37
Tried using the following steps. Can't reproduce.

1. `mkdir next-1030` (doesn't matter what name you use)
2. create `package.json` as defined below:
```json
{                                                                                       
  "name": "zeit-next-test",                                                             
  "version": "1.0.0",                                                                   
  "description": "",                                                                    
  "main": "index.js",                                                                   
  "scripts": {                                                                          
    "dev": "next"                                                                       
  },                                                                                    
  "keywords": [],                                                                       
  "author": "Fate Riddle fateriddle@foxmail.com",                                       
  "license": "MIT",                                                                     
  "dependencies": {                                                                     
    "next": "^1.2.3"                                                                    
  }                                                                                     
} 
```
3. `npm install`
4. create `pages/index.js`
```
export default () => (                                                                  
  <div>Welcome to next.js!</div>                                                        
)
```
4. `npm run dev`

**Comment by timneutkens** [comment] 2017-02-11 23:38
Closing this as not reproduceable. Please re-open if needed.

**Closed by timneutkens** 2017-02-11 23:38 UTC
Labels: Type: Question

**Comment by k00k** [comment] 2017-02-24 19:03
Just leaving a comment here in case it helps anyone else, be sure you don't have anything else running on the same port already. I forgot about a process I had that was running on localhost:3000 already.

**Comment by carterax** [comment] 2017-12-01 15:20
I had the same issue on my windows machine but i resolved it by simply creating the pages directory and including the index.js in it
