### ISSUE TITLE
Next build failed 

### ISSUE THREAD

**Issue by KInGATiLLa** [zeit/next.js#12311] opened 2020-04-29 09:10 UTC
# Bug report

## Describe the bug

next build script failed

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Expected behavior
2. See error

## Build error:
`
> eservice-dms@0.1.0 build C:\Users\khgal\Documents\smartub\dms
> next build

Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

> Using external babel configuration
> Location: "C:\Users\khgal\Documents\smartub\dms\.babelrc"
Creating an optimized production build ...
<--- Last few GCs --->
) [8528:0000024DBE80D050]   114737 ms: Mark-sweep 2042.1 (2071.7) -> 2040.5 (2076.9) MB, 633.6 / 0.0 ms  (+ 451.3 ms in 77 steps since start of marking, biggest step 11.6 ms, walltime since start of marking 1104 ms) (average mu = 0.063, current mu = 0.017) [8528:0000024DBE80D050]   115785 ms: Mark-sweep 2046.8 (2076.9) -> 2045.7 (2081.9) MB, 620.6 / 0.0 ms  (+ 408.3 ms in 78 steps since start of marking, biggest step 15.8 ms, walltime since start of marking 1048 ms) (average mu = 0.041, current mu = 0.018) 

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x027a8e7008d1 <JSObject>
    0: builtin exit frame: stringify(this=0x027a8e71ec89 <Object map = 000000E39F783549>,2,0x006bfe9c01b9 <null>,0x0086c217ffd1 <Object map = 00000167F9B4A029>,0x027a8e71ec89 <Object map = 000000E39F783549>)

    1: /* anonymous */(aka /* anonymous */) [000003EB354A9C91] [C:\Users\khgal\Documents\smartub\dms\node_modules\next\dist\build\webpack\plugins\react-loadable-plugin.js:24] [bytecode=0000...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7739B363F napi_wrap+128063
 2: 00007FF773952836 v8::base::CPU::has_sse+35142
 3: 00007FF7739534F6 v8::base::CPU::has_sse+38406
 4: 00007FF774169F4E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF774152021 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF77401E57C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF7740297D0 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF7740262F4 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF77401BB13 v8::internal::Heap::CollectGarbage+1283
10: 00007FF77401A184 v8::internal::Heap::AddRetainedMap+2452
11: 00007FF774041E1F v8::internal::Factory::NewRawTwoByteString+95
12: 00007FF773D2FC9B v8::internal::StringStream::ClearMentionedObjectCache+9579
13: 00007FF773F54C1D v8::internal::TimedHistogram::Stop+2093
14: 00007FF773F565DB v8::internal::TimedHistogram::Stop+8683
15: 00007FF773F58674 v8::internal::TimedHistogram::Stop+17028
16: 00007FF773F576AE v8::internal::TimedHistogram::Stop+12990
17: 00007FF773F5C606 v8::internal::TimedHistogram::Stop+33302
18: 00007FF773F58859 v8::internal::TimedHistogram::Stop+17513
19: 00007FF773F5B280 v8::internal::TimedHistogram::Stop+28304
20: 00007FF7740E3804 v8::internal::Builtins::builtin_handle+84900
21: 00007FF7745B4EDD v8::internal::SetupIsolateDelegate::SetupHeap+546893
22: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
23: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
24: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
25: 00007FF7745330BC v8::internal::SetupIsolateDelegate::SetupHeap+14892
26: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
27: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
28: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
29: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
30: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
31: 00007FF7745330BC v8::internal::SetupIsolateDelegate::SetupHeap+14892
32: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
33: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
34: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
35: 00007FF7745330BC v8::internal::SetupIsolateDelegate::SetupHeap+14892
36: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
37: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
38: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
39: 00007FF7745330BC v8::internal::SetupIsolateDelegate::SetupHeap+14892
40: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
41: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
42: 00007FF7745330BC v8::internal::SetupIsolateDelegate::SetupHeap+14892
43: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
44: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
45: 00007FF774539D8C v8::internal::SetupIsolateDelegate::SetupHeap+42748
46: 00007FF774589392 v8::internal::SetupIsolateDelegate::SetupHeap+367874
47: 00007FF774556F2D v8::internal::SetupIsolateDelegate::SetupHeap+161949
48: 00007FF7745371AC v8::internal::SetupIsolateDelegate::SetupHeap+31516
49: 00007FF774077CC0 v8::internal::Execution::CallWasm+1536
50: 00007FF774077DB3 v8::internal::Execution::CallWasm+1779
51: 00007FF774078192 v8::internal::Execution::TryCall+354
52: 00007FF77405A1A5 v8::internal::MicrotaskQueue::RunMicrotasks+501
53: 00007FF7739CF8D1 node::CallbackScope::~CallbackScope+593
54: 00007FF7739CFC44 node::CallbackScope::~CallbackScope+1476
55: 00007FF7739C8D33 v8::internal::interpreter::BytecodeNode::operand_scale+179
56: 00007FF77394FAA3 v8::base::CPU::has_sse+23475
57: 00007FF773944EF1 v8::internal::Scope::locals+203505
58: 00007FF773A00577 uv_timer_stop+775
59: 00007FF7739FD03B uv_async_send+331
60: 00007FF7739FC7DC uv_loop_init+1212
61: 00007FF7739FC9A4 uv_run+244
62: 00007FF77391AD43 v8::internal::Scope::locals+31043
63: 00007FF77397A3D3 node::Start+275
64: 00007FF7738267AC RC4_options+339628
65: 00007FF77466BE08 v8::internal::SetupIsolateDelegate::SetupHeap+1296248
66: 00007FF8329A7BD4 BaseThreadInitThunk+20
67: 00007FF832BECE51 RtlUserThreadStart+33
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! eservice-dms@0.1.0 build: `next build`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the eservice-dms@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\khgal\AppData\Roaming\npm-cache\_logs\2020-04-29T08_59_04_805Z-debug.log
`

## System information

- OS: [Ubuntu: 18.04]
- Browser (if applies) [chrome]
- Version of Next.js: [e.g. 9.3.5]
- Version of Node.js: [e.g. 12.16.2]

**Comment by timneutkens** [comment] 2020-04-29 09:21
```
Steps to reproduce the behavior, please provide code snippets or a repository:

Go to Expected behavior
See error
```

I'm not sure how these are clear and concise steps to reproduce as asked for in the issue template.


Probably a duplicate of https://github.com/zeit/next.js/issues/12280

**Closed** 2020-04-29 15:04 UTC

**Comment by balazsorban44** [comment] 2022-01-30 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
