### ISSUE TITLE
iframe link does not work when the client renders in iOS Chrome

### ISSUE THREAD

**Issue by myriky** [zeit/next.js#5169] opened 2018-09-14 14:37 UTC
# Examples bug report

## Describe the bug
I want to implement web2app using iframe on a specific page.

It occur only on iOS Chrome

In the case of clientside rendering, web2app does not work.
web2app only works for serverside rendering.

Is there anyone who has had this problem?

You can check the issue from the link below.

https://next-iamport-nvvdvrxjku.now.sh/ (modified)

## To Reproduce

1. open 'https://next-iamport-nvvdvrxjku.now.sh/' on iOS chrome
2. click button to next page on client-side rendering
3. make sure the Google Map or Instargram is open. (it doesn't work on client-side rendering)

4. refresh to load the page by server-side rendering
5. make sure the Google Map or Instargram is open. (it work!!!)

## Expected behavior
web2app is working

it doesn't work only CHROME!!!
safari has work perfectly!

## Screenshots
https://next-iamport-nvvdvrxjku.now.sh/ (modified)

## System information
 - OS: iOS 11.4.1
 - Browser : Chrome 68.0.3440.83
 - Version of Next.js: 6.1.

## Additional context

ah........ 도와주세요

**Comment by danielr18** [comment] 2018-09-14 14:53
Can you try using `target="top"` in the a tags?

**Comment by myriky** [comment] 2018-09-14 15:03
target="top"
target="_top"

Still no.
Not in client-side rendering,
server-side rendering works.

**Comment by myriky** [comment] 2018-09-14 15:06
It still doesn't work on target="_blank"

**Comment by danielr18** [comment] 2018-09-14 15:09
Would you mind sharing the repository?

**Comment by myriky** [comment] 2018-09-14 15:43
@danielr18 of course.
[https://github.com/myriky/next-iframe](https://github.com/myriky/next-iframe)

**Comment by timneutkens** [comment] 2019-08-09 15:35
Going to close this as the issue has been open for almost a year.

**Closed by timneutkens** 2019-08-09 15:35 UTC
Labels: good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-31 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
