### ISSUE TITLE
A position fixed siderbar not working when route changed with "Link" tag 

### ISSUE THREAD

**Issue by selvesandev** [zeit/next.js#8881] opened 2019-09-27 15:50 UTC
# Bug report

## Fixed Sidebar Not working after route change.

I have implemented a fixed sidebar in my next app using `react-sticky-box`. The sticky sidebar is working perfectly fine when the page is reloaded from the browser's reload button but stops working once the page is changed clicking the next.js's  Link tag. 

## System information

- OS: macOS
- Browser  chrome
- Version of Next.js : 9.0.6

**Comment by efstathiosntonas** [comment] 2019-11-04 10:40
did you find a solution on this?

you could use this:
```
import { Router } from 'next/router';

componentDidMount() {
     Router.events.on('routeChangeComplete', this.handleRouteChange);
}

  componentWillUnmount() {
      Router.events.off('routeChangeComplete', this.handleRouteChange);
  }

this.handleRouteChange = async path => {
// do whatever you want like rest api calls etc.
}
```

**Comment by timneutkens** [comment] 2020-01-02 23:19
Duplicate of #8193

**Closed by timneutkens** 2020-01-02 23:19 UTC

**Comment by balazsorban44** [comment] 2022-01-30 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
