### ISSUE TITLE
Allow trailing slashes for folders

### ISSUE THREAD

**Issue by lcswillems** [zeit/next.js#8913] opened 2019-09-30 13:20 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I created a `account` folder in the `pages` folder. And in this `account` folder, I added a `index.js` file.

I would like to reach this page through `/account/`, but I get a 404 error. It is only reachable through `/account`.

## Describe the solution you'd like

When I create a folder, I would like to be able to reach it with a trailing slash.

**Comment by Janpot** [comment] 2019-09-30 13:28
I think this is a duplicate of https://github.com/zeit/next.js/issues/5214

**Comment by lcswillems** [comment] 2019-09-30 13:52
I have not written that I "MUST". I wrote that "I would like to". Please don't change my wording.

**Comment by Janpot** [comment] 2019-09-30 14:14
Sorry, that's not how I meant it. What I meant is: you could just *only* link to that page without a trailing slash. Unless something inside your project requirements makes this impossible. If it's impossible I'm interested in what dictates this requirement.

I'm only asking out of interest, not trying to put certain words in your mouth. Apologies if it seemed that way, the capitals were only meant as emphasis.

**Comment by lcswillems** [comment] 2019-09-30 14:59
Okay, I see what you mean.

Yes, I could link to that page without a trailing slash, and I currently do. But the URL would be more meaning full if I could add a trailing slash.

For the user, `/account` means the account page, but `/account/` means the account section of the website, i.e. that they are likely other pages in this section.

**Comment by czebe** [comment] 2019-10-02 06:58
Our proxy appends trailing slash to any routes without it.
I agree with @lcswillems: users can enter the URL with the trailing slash, which results in a 404.
I feel it very hacky to remove the slashes manually, could `next` offer any workarounds?

**Comment by bitjson** [comment] 2019-10-02 18:57
Just to add – some users regularly remove a part of the URL when navigating e.g. documentation, and some percentage of them leave the trailing slash, e.g.: 
- from `/section/subsection/page`
- user removes the final two segments to get a higher-level view: `/section/`
- user sees a 404

I think a better default would be for Next.js to always automatically redirect to either with or without the trailing slash.

**Comment by ajhool** [comment] 2019-11-01 02:26
@Janpot the reason that I *must* use a trailing slash is because Social Login / OAuth federation providers require a trailing slash in their redirect URLs.

**Comment by lcswillems** [comment] 2019-11-01 09:17
Maybe it will be solved with the new RFC on custom routing? (https://github.com/zeit/next.js/issues/9081)

**Comment by timneutkens** [comment] 2019-11-09 22:53
Duplicate of #619

**Closed by timneutkens** 2019-11-09 22:53 UTC

**Comment by balazsorban44** [comment] 2022-01-30 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
