### ISSUE TITLE
with-firebase-cloud-messaging not working with firebase@7.5.0

### ISSUE THREAD

**Issue by booz24443** [zeit/next.js#9571] opened 2019-11-29 16:32 UTC
with-firebase-cloud-messaging Example compatibility issue with firebase@7.5.0
err:
index.js:1 FirebaseError: Installations: Missing App configuration value: "projectId" (installations/missing-app-config-values).

to reproduce run exact example code with following dependenies:
  "dependencies": {
    "express": "^4.17.1",
    "firebase": "^7.5.0",
    "localforage": "^1.7.3",
    "next": "^8.1.0",
    "react": "^16.8.3",
    "react-dom": "^16.8.3"
  },
  "devDependencies": {
    "next-offline": "^4.0.6"
  }

**Comment by Timer** [comment] 2019-12-03 17:58
Closing as the issue template was not followed. We need a full reproduction, but it seems like you did not configure Firebase.

**Closed by Timer** 2019-12-03 17:58 UTC

**Comment by balazsorban44** [comment] 2022-01-30 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
