### ISSUE TITLE
Get the path to the `static` folder

### ISSUE THREAD

**Issue by lcswillems** [zeit/next.js#8769] opened 2019-09-17 14:08 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I would like to get the path to the static folder.

Such a function / variable is built-in in other frameworks like Laravel: https://laravel.com/docs/6.x/helpers#method-public-path

## What I tried

I tried to get it with `__dirname` or `./` or `process.cwd()`, it works but the command depends either on the location of the file containing it or the location where the script is executed. 

Hence, this is not convenient, because I have to modify my command if I move my file or execute the script from another place. For example, my app works locally but not on production using Now.

**Comment by gurkerl83** [comment] 2019-09-25 21:54
This ability is also relevant for other plugins such as next-i18next. Here the static folder / in the future perhaps the public folder includes translation files which are required to load from a deployed, server near function. 

Hopefully one of the main contributors can shine some light on that issue, thx.

**Comment by StarpTech** [comment] 2019-09-29 19:49
don't know if I understan your issue correctly. Files are served with the static directory as described [here](https://github.com/zeit/next.js#static-file-serving-eg-images). You can just use `/static/<any-file>`.

**Comment by lcswillems** [comment] 2019-09-30 07:37
I would like to read the file using `fs.readFileSync`, not to get through http. As @gurkerl83 mention it, it is useful for internationalization and reading locales defined in the `static` folder.

**Comment by StarpTech** [comment] 2019-09-30 07:47
Then read the file relative to your next.js root project "static" is fixed.

**Comment by gurkerl83** [comment] 2019-09-30 07:52
It is probably related with this issue - https://github.com/zeit/next.js/issues/8251. A merge request exists https://github.com/zeit/next.js/pull/8334

**Comment by lcswillems** [comment] 2019-09-30 07:58
If I use a relative path, then if I move the file containing the code, I need to modify the code of the file for example. If my code is in a package, then the path is different, etc... This is not ideal from my point of view.

**Comment by Timer** [comment] 2019-10-18 05:36
Duplicate of https://github.com/zeit/next.js/issues/8251#issuecomment-526465232

**Closed by Timer** 2019-10-18 05:36 UTC

**Comment by balazsorban44** [comment] 2022-01-31 02:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
