### ISSUE TITLE
Amp with custom server(expressJS)

### ISSUE THREAD

**Issue by Ich-bin-naoya** [zeit/next.js#8714] opened 2019-09-12 02:32 UTC
# How to implement amp HELP ME

I am using expressJS as a custom server.

Now I have a question about how to implement amp page with custom server 

I  do prepare a next.config.js for custom server which is like this code

```next.config.js
module.exports = withTypescript({
  webpackDevMiddleware: config => {
     return config;
  }
})

```

Then I tried this code on pages/index.js

export const config = { amp:true }

The powered by Amp is not shown on google chrome’s console 

Please help me

**Comment by Timer** [comment] 2019-09-12 03:17
Hi, you'll need to provide a full reproduction for us to help you. You seem to have ignored the issue template.

I'll close this as questions belong on our Spectrum.

**Closed by Timer** 2019-09-12 03:17 UTC

**Comment by balazsorban44** [comment] 2022-01-31 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
