### ISSUE TITLE
Change default root url

### ISSUE THREAD

**Issue by sepiropht** [zeit/next.js#2289] opened 2017-06-16 15:13 UTC
I have an next/js app behind nginx with custom server  node/express . 
I launch it to port 3000. Nginx redirect the request myserver.com/mynextapp/ to port 3000 , but this is not working. 
I can see the page server rendered, but the js doesn't working . In browser tool network  i got 404 response  for app.js and page/, because  the request is myserver.com/_next/228ef92e59d376f055fc2c6d01c93b82/app.js instead of myserver.com/mynextapp/_next/228ef92e59d376f055fc2c6d01c93b82/app.js
It worked well when i simply opened the port 3000 in myserver.com but i try to avoid that.
Any idea ?
Thanks

**Comment by timneutkens** [comment] 2017-06-17 08:56
This is a duplicate of https://github.com/zeit/next.js/issues/257. Please see that issue for some community solutions 👍

**Closed by timneutkens** 2017-06-17 08:56 UTC

**Comment by qwang06** [comment] 2017-06-19 16:21
I ran into this issue as well and none of the solutions in #257 seem to resolve this.

I ended up modifying the server/index.js file and updating the routes in the method defineRoutes:
`
      Object.keys(routes).map(route => {
        routes[this.renderOpts.assetPrefix + route] = routes[route];
      });
`

I know this isn't the best solution right now but it's the only thing that works. Hopefully support for something like this is available in the future so I don't have to straight up modify core code.

**Comment by sepiropht** [comment] 2017-06-20 14:22
ok thanks for this, i will check that !

**Comment by radeno** [comment] 2017-07-11 13:46
@qwang06 how did you modify predefined next server routes?
It is something i need too. By i don't want to modify original file.
