### ISSUE TITLE
issue when regenerating build

### ISSUE THREAD

**Issue by aditya-axa** [zeit/next.js#11767] opened 2020-04-09 03:09 UTC
# Bug report

## Describe the bug
If we have generated a build already and trying to generate build again getting following error

`
(node:45607) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/xxx/src/client/.next'
(node:45607) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:45607) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. generate build
2. try to generate build again
3. getting above mentioned error

## Expected behavior

It should regenerate build i.e., delete and create .next folder again

## System information

- OS: macOS
- Browser (if applies) NA
- Version of Next.js: 9.3.4

**Comment by ijjk** [comment] 2020-04-09 04:12
Hi, this sounds like a duplicate of https://github.com/zeit/next.js/issues/11748 and https://github.com/zeit/next.js/issues/11601

**Comment by aditya-axa** [comment] 2020-04-09 05:55
works fine after upgrading to 10.18 thanks @ijjk

**Closed** 2020-04-09 05:56 UTC

**Comment by balazsorban44** [comment] 2022-01-30 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
