### ISSUE TITLE
Can't go from a page not containing a css file to another containing one

### ISSUE THREAD

**Issue by MarchWorks** [zeit/next.js#7116] opened 2019-04-23 11:27 UTC
# Examples bug report

## Example name
with-next-css

## Describe the bug
Impossible to go from one page which doesn't contain an imported css file to a one containing an imported css file

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository: https://github.com/MarchWorks/with-next-css-issue
1. Go to 'index page'
1. Click on 'About'
2. See error

## System information
 - Version of Next.js: 8.1.0

**Comment by timneutkens** [comment] 2019-04-23 12:21
Duplicate of https://github.com/zeit/next-plugins/issues/282

**Closed by timneutkens** 2019-04-23 12:21 UTC
