### ISSUE TITLE
[BUG] react-hot-loader not saving state

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [zeit/next.js#11914] opened 2020-04-15 13:09 UTC
[BUG]
---
 react-hot-loader not saving state!

solution:
---
add `import "react-hot-loader"` to top BEFORE all react usage

temporarry solution:
---
`npm i -D react-hot-loader`

`next.config.js`

```javascript
module.exports = {
  webpack(config, options) {

    if (options.dev && !options.isServer) {
      let entryHandler = config.entry

      config.entry = async function () {
        let entries = await entryHandler.apply(this, arguments)
        let mainArr = entries['main.js']

        if (!mainArr.includes('react-hot-loader')) {
          mainArr.unshift('react-hot-loader')
        }

        return entries
      }
    }

    return config
  }
}

```

Now components retain state after reboot. Actually, you could manually add `import react-hot-loader` at the top of EVERY page =) (if you add it to `_app.js` thats not working, cuz pages imported BEFORE _app.js) but the creators of next.js had to add this

**Comment by timneutkens** [comment] 2020-04-15 13:23
Duplicate of https://github.com/zeit/next.js/discussions/11885

**Closed by timneutkens** 2020-04-15 13:23 UTC
