### ISSUE TITLE
Fix for Ant Design Example :)

### ISSUE THREAD

**Issue by cupcakearmy** [zeit/next.js#12310] opened 2020-04-29 08:22 UTC
# Bug report

## Describe the bug

The [example for ant design](https://github.com/zeit/next.js/tree/canary/examples/with-ant-design) is broken right now.

## To Reproduce

1. Download repo, `yarn`, `yarn next build`

## Solution

If you add `@zeit/next-css` and wrap it around the existing config it works :)

**Comment by iaurg** [comment] 2020-04-29 11:24
Can I try it? @cupcakearmy using next-css, what about it: https://github.com/zeit/next.js/blob/master/errors/built-in-css-disabled.md ?

**Comment by cupcakearmy** [comment] 2020-04-29 11:35
What do you mean? :)
I found that if you add the withCSS around the config in the and design example it works again :D

**Comment by iaurg** [comment] 2020-04-29 13:01
Yeah, with next-css this works. My question is about descontinuation of with-css, but I think this is for other uses. 

I will send the, PR. Thanks.

**Comment by cupcakearmy** [comment] 2020-04-29 14:23
Ah ok, did not know that it was being discontinued so I was confused :) Thanks!

**Comment by cupcakearmy** [comment] 2020-04-29 14:23
Feel free to close when merged :)

**Comment by Rapdash** [comment] 2020-05-04 23:04
@iaurg Are you still working on this? I'd be happy to hop in & fix it.

**Comment by tywmick** [comment] 2020-05-05 18:25
Hey, found this issue via the "good first issue" tag and thought I'd give it a shot! It looks like the issue @cupcakearmy ran into was fixed by #11837 ("antd-4 with built-in css support"), though, which was just merged four days ago, but I am finding another bug now where the DatePicker crashes the page.

I bootstrapped the example using `npm init next-app --example with-ant-design with-ant-design-app`, then `npm run dev`'d and found that the page did load and nearly everything worked fine, but clicking on the DatePicker now crashes the page:

![nextjs-antd-example](https://user-images.githubusercontent.com/5317080/81100913-4ed84600-8edb-11ea-93e1-b4b86be1078a.gif)

Just to make sure, @cupcakearmy, was this the issue you encountered, or was the whole page failing to load without `withCSS`?

If this DatePicker bug is something different, should I open up a new issue or just keep tracking it here? I'll work on fixing it in the meantime. 👍🏼

**Comment by cupcakearmy** [comment] 2020-05-05 18:48
Oh nice, looks like most of it I working :)
No my problem was that is was not even building correctly. Not even a normal button

**Comment by tywmick** [comment] 2020-05-06 22:26
Phew, found the culprit for this new DatePicker bug: [antd-dayjs-webpack-plugin](https://github.com/ant-design/antd-dayjs-webpack-plugin). I've created a new PR #12580 to fix that, and I guess this issue can be closed as having been fixed by #11837?

**Comment by cupcakearmy** [comment] 2020-05-06 22:58
Should i close the issue then? Seems to be not related to next anymore right?

**Comment by tywmick** [comment] 2020-05-07 15:31
Yeah I'd say close this one 👍🏼

**Closed** 2020-05-07 15:33 UTC
Labels: good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-30 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
