### ISSUE TITLE
Extra character `/` added in path once app deployed

### ISSUE THREAD

**Issue by dbrrt** [zeit/next.js#5955] opened 2018-12-28 02:20 UTC
# Bug report

## Describe the bug
When I'm deploying a nextjs app, I've got the character `/` appended at the end of the path, which is not appearing during development.

## To Reproduce

1) in pages folder, create a component (such as `home.js`)
2) In development, path will be `/home` if following structure `pages/home.js`
3) Once deployed (e.g. : `netlify`), path will be `/home/`

## System information
 - OS: macOS 10.13
 - Browser: chrome
 - Version of Next.js: 7.0.2

**Comment by timneutkens** [comment] 2018-12-28 09:58
Duplicate of #5214

**Comment by dbrrt** [comment] 2018-12-28 14:01
Sounds great. Would be awesome to get such a feature.

**Comment by c0b41** [comment] 2018-12-31 16:04
@dbrrt do you using Netlify [`Pretty Urls`](https://www.netlify.com/docs/redirects/#trailing-slash) ? maybe problem this

**Comment by dbrrt** [comment] 2019-01-02 02:02
@c0b41 No, I'm not using any asset optimization. 
I think the solution is there : https://github.com/zeit/next.js/blob/canary/packages/next-server/lib/router/router.js#L56

**Comment by martpie** [comment] 2019-02-22 14:37
When using Caddy web server, you get the same problems. 

Nuxt.js solved it by providing an option for this: https://nuxtjs.org/api/configuration-generate#subfolders

**Closed** 2019-04-22 16:55 UTC
Labels: Feature: Export, Type: Feature Request

**Comment by dbrrt** [comment] 2019-04-23 22:06
Thanks !
