### ISSUE TITLE
npm init next-app creates a project that uses yarn

### ISSUE THREAD

**Issue by pjaws** [zeit/next.js#10647] opened 2020-02-23 16:37 UTC
# Bug report

## Describe the bug

Running `npm init next-app` creates a new Next.js project that uses Yarn, rather than npm. Given, the fact that I'm using npm to create the project, and the docs offer two options for getting started, one with npm and one with Yarn, this is completely unexpected behavior.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Read getting started docs
2. Choose the `npm` option
3. Run `npm init next-app`
4. Get a project that uses Yarn

## Expected behavior

It should create a project that uses npm for package management.

Here ya go, Tim!

**Comment by timneutkens** [comment] 2020-02-23 21:38
Already answered as per https://github.com/zeit/next.js/issues/10642#issuecomment-590069187

This is expected behavior as you have yarn installed.

**Comment by pjaws** [comment] 2020-02-24 16:31
How could you possibly think that running npm init would create a project
with yarn? This is absolutely not expected behavior for the end user. I've
noticed this happening in many Next.is issues. You come in and make some
short comment then close the ticket without any further investigation or
conversation.

This is at the very least a documentation issue. It is not obvious at all
that when you offer an npm option and a yarn option, that choosing the npm
option will lead to the project being created with yarn. Whether or not I
have yarn installed is completely irrelevant.

**Comment by timneutkens** [comment] 2020-02-24 16:52
@lfades let's update the docs to just mention `npx`, npx is just a tool to execute a package from npm, it's unrelated to the npm cli.

**Comment by timneutkens** [comment] 2020-02-24 16:54
> How could you possibly think that running npm init would create a project
with yarn? 

I'm saying it's expected behavior and implemented this way by design, here's the `yarn` check:
https://github.com/zeit/next.js/blob/canary/packages/create-next-app/index.ts#L101

**Comment by pjaws** [comment] 2020-02-24 17:01
Sorry, I guess we were misunderstanding each other, and that’s my fault. I
meant unexpected behavior from the user’s point of view.

I should have mentioned from the start that I felt this was a documentation
issue, not a code issue, though I do still feel it’s odd DX. Anyway, the
problem can definitely be solved by a short line in the docs. I was going
to add a PR myself, but I wasn’t sure how you all would want to phrase it,
or which method was preferred (—use-npm or npx).

**Comment by nkovacic** [comment] 2020-03-15 20:38
I also agree with pjaws. Even if we have have yarn installed, create-next-app should have a switch to use npm instead of yarn if its detected.

**Comment by Janpot** [comment] 2020-04-03 13:42
FYI: Both `npm` and `yarn` should set an environment variable [`$npm_execpath`](https://github.com/yarnpkg/yarn/issues/5063). Maybe that can be checked before the installation check to pick the right package manager?

**Comment by timneutkens** [comment] 2020-04-05 11:30
@tsriram did some investigation into how to detect npm here: https://github.com/zeit/next.js/issues/11628#issue-593239674

**Comment by tsriram** [comment] 2020-04-07 08:25
This should be fixed in #11683. I guess this issue can be closed once the new version is published.

**Closed** 2020-04-07 08:28 UTC
Labels: Documentation

**Comment by onomated** [comment] 2020-04-25 17:19
@tsriram is there anyway to fix this in existing codebases?

**Comment by vschoener** [comment] 2020-04-26 11:42
Just run into the same issue today and was surprised next install by using yarn instead of npm.

Doc says:

```
npm init next-app
# or
yarn create next-app
```

So can you explain (or fix the documentation) because I'm really lost.

**Comment by mbrookson** [comment] 2020-05-04 21:00
Anyone who comes here, I don't think it's well documented but I found you can install with npm using the `--use-npm` flag.

e.g.

```
npx create-next-app my-app --use-npm

# or 

npm init next-app my-app --use-npm
```

Hope this helps 🙂

**Comment by yardz** [comment] 2020-11-18 17:03
> Anyone who comes here, I don't think it's well documented but I found you can install with npm using the `--use-npm` flag.
> 
> e.g.
> 
> ```
> npx create-next-app my-app --use-npm
> 
> # or 
> 
> npm init next-app my-app --use-npm
> ```
> 
> Hope this helps 🙂

I was having the same problem and the documentation says nothing about it. What a terrible usability, I have yarn because another project just runs with it. And if so, am I forced to use yarn? Shame on you vercel, shame on you...

**Comment by Timer** [comment] 2020-11-18 17:13
FYI running `npm init` with npm v7 will no longer use Yarn.

**Comment by yardz** [comment] 2020-11-18 17:48
Thank you for deleting my comment. Very democratic, transparent and honest... If i don't like what was said, i'll shut you up.

**Comment by balazsorban44** [comment] 2022-01-29 03:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
