### ISSUE TITLE
Error: MobX observer: Store 'store' is not available! Make sure it is provided by some Provider

### ISSUE THREAD

**Issue by 7elven** [zeit/next.js#1032] opened 2017-02-08 07:04 UTC
When I try example Mobx

Error: MobX observer: Store 'store' is not available! Make sure it is provided by some Provider
    at http://localhost:3000/_next/-/commons.js:8459:46
    at Array.forEach (native)
    at http://localhost:3000/_next/-/commons.js:8456:17
    at _fn.render (http://localhost:3000/_next/-/commons.js:8435:31)
    at _fn.render (http://localhost:3000/_next/-/main.js:7616:30)
    at _fn.withHandleError (http://localhost:3000/_next/-/main.js:1962:17)
    at _fn [as render] (http://localhost:3000/_next/-/main.js:2004:24)
    at http://localhost:3000/_next/-/commons.js:28328:21
    at measureLifeCyclePerf (http://localhost:3000/_next/-/commons.js:27607:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:3000/_next/-/commons.js:28327:25)

**Comment by sakulstra** [comment] 2017-02-08 14:57
I think this is a duplicate of #899 and eventually even #1003 ?

**Comment by timneutkens** [comment] 2017-02-08 15:06
@sakulstra Totally right. Closing.

**Closed by timneutkens** 2017-02-08 15:06 UTC
