### ISSUE TITLE
Latest file-loader not working with nextJs 9.1

### ISSUE THREAD

**Issue by jaqua** [zeit/next.js#9763] opened 2019-12-16 21:58 UTC
The example for [semanticUI implementation](https://github.com/zeit/next.js/tree/canary/examples/with-semantic-ui) is not working for the latest file-loader (5.0.2). Using the latest version will break all icons.

File loader until 4.3.0 is working, it's breaking if using 5.0.0

**Comment by timneutkens** [comment] 2019-12-16 22:22
Closing this as it doesn't follow the issue template.

**Closed by timneutkens** 2019-12-16 22:22 UTC

**Comment by balazsorban44** [comment] 2022-01-30 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
