### ISSUE TITLE
Cannot run dev after 9.4

### ISSUE THREAD

**Issue by jose-donato** [zeit/next.js#12752] opened 2020-05-11 22:26 UTC
# Bug report

## Describe the bug

Cannot run dev server after upgrading to 9.4

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. next

## Screenshots

![image](https://user-images.githubusercontent.com/43375532/81618088-93ce1200-93de-11ea-9af8-3de5dbe80de4.png)

## System information

- OS: ubuntu server 18.04
- Browser (if applies) chrome
- Version of Next.js: [e.g. 9.4]
- Version of Node.js: [e.g. 12.16.1]

**Comment by Jarred-Sumner** [comment] 2020-05-11 23:10
When I've seen an error like this before, it was usually fixed by `rm -rf node_modules .next && yarn install`

It sounds like its trying to use a DLL file that no longer exists, so clearing the cache might make it do the right thing

**Comment by jose-donato** [comment] 2020-05-11 23:12
it is strange cause i switched the chrome profile to another and it worked

**Comment by Timer** [comment] 2020-05-12 04:04
Closing as user said it's resolved after switching chrome profile

**Closed by Timer** 2020-05-12 04:04 UTC

**Comment by balazsorban44** [comment] 2022-01-30 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
