### ISSUE TITLE
with-hashed-statics not working after building

### ISSUE THREAD

**Issue by gijo-varghese** [zeit/next.js#4949] opened 2018-08-13 10:50 UTC
Already searched in the issues. Similar ones: https://github.com/zeit/next.js/issues/3324, https://github.com/zeit/next.js/issues/3023

Hashed file names only works on running `npm run start`. Not working after `npm run build && npm run export`

## To Reproduce
1. Clone https://github.com/zeit/next.js/tree/canary/examples/with-hashed-statics
2. `npm run build && npm run export`

## Expected behavior
after building, `out/_next/static/file.txt` should be `out/_next/static/file.[hash].txt` 

## System information
 - Version of Next.js: 6.1.1

**Comment by timneutkens** [comment] 2018-08-13 18:12
The example should be updated to use webpack instead of babel to handle this.

**Comment by giovannigiordano** [comment] 2018-09-05 12:30
I have opened a [pull request](https://github.com/zeit/next.js/pull/5100).

**Comment by giovannigiordano** [comment] 2018-09-05 13:27
@gijo-varghese This has been resolved.
https://github.com/zeit/next.js/pull/5100
@timneutkens I think this issue can be closed.

**Comment by timneutkens** [comment] 2018-09-05 13:28
You're right 👍

**Comment by timneutkens** [comment] 2018-09-05 13:29
@giovannigiordano just a tip: if you add `fixes #PRNUMBER` eg `fixes #4949` GitHub will automatically close the issue that the PR fixed 👍

**Closed** 2018-09-05 13:28 UTC
Labels: good first issue, help wanted

**Comment by giovannigiordano** [comment] 2018-09-05 13:30
Thanks, i usually use Bitbucket. For the next commit I will use this format in the commit messages.

**Comment by timneutkens** [comment] 2018-09-05 13:36
👌 No worries, just teaching something new 😄

**Comment by gijo-varghese** [comment] 2018-09-05 13:40
Sorry guys I've moved to plain ReactJS, too many bugs!

**Comment by timneutkens** [comment] 2018-09-05 13:58
> too many bugs!

Elaborate?

**Comment by lifeiscontent** [comment] 2019-07-29 22:50
@timneutkens do you know how I can load custom fonts from a fonts.css file in the `/static` folder?

**Comment by balazsorban44** [comment] 2022-01-31 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
