### ISSUE TITLE
Dynamic import() 6.x.x issue

### ISSUE THREAD

**Issue by lolcoolkat** [zeit/next.js#4127] opened 2018-04-08 15:30 UTC
Wanted to create another issue for this, as this is a very import bug that is occurring; which hopefully can be fixed soon :(

Same issue/behavior as https://github.com/zeit/next.js/issues/3775.

Example code:

```
const LoadProfile = dynamic(import('../components/Profile/LoadProfile'), {
  loading: () => <div>Loading Profile...</div>
})

const Profile = ({ username }) => (
  <App title="Profile">
    <article>
      <h1>Profile ({username})</h1>
      <LoadProfile username={username} />
    </article>
  </App>
)
```

Any updates on when this can be fixed? I'm kinda in a standstill rn and without using dynamic imports it will severely hurt the performance of my application.

Thanks for any support/help!

**Comment by timneutkens** [comment] 2018-04-08 15:31
No need to open new issues. Duplicate of #3775

**Closed by timneutkens** 2018-04-08 15:31 UTC
