### ISSUE TITLE
Example using Next JS with Google Ad Sense 

### ISSUE THREAD

**Issue by JaeDukSeo** [zeit/next.js#9619] opened 2019-12-04 08:47 UTC
# Feature request
Example using Next JS with Google Ad Sense 

## Is your feature request related to a problem? Please describe.
Yes, having an example would be good

A clear and concise description of what you want and what your use case is.
Running a next js app with Example using Next JS with Google Ad Sense 

## Describe the solution you'd like
the example of Example using Next JS with Google Ad Sense

**Comment by timneutkens** [comment] 2019-12-04 10:43
Duplicate of #4838

**Closed by timneutkens** 2019-12-04 10:43 UTC

**Comment by balazsorban44** [comment] 2022-01-30 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
