### ISSUE TITLE
read-page.js  JSON$parse.component Error Beta 11

### ISSUE THREAD

**Issue by SerkanDayicik** [zeit/next.js#597] opened 2017-01-01 08:03 UTC
Win 10
Node v6.9.2
NPM 3.10.9

Using Examle ssr-caching folder not changing any thing

Npm Run Dev Command After Error read-page.js 48 line

Error 
https://gist.github.com/SerkanDayicik/e867a72a171b6e1a6d1f87e5f0a654a9

next 2.0.0-beta.11

**Comment by arunoda** [comment] 2017-01-01 11:10
Mee too.

**Comment by SerkanDayicik** [comment] 2017-01-01 12:07
i Try on ubuntu and not any error This bug only windows

**Comment by msand** [comment] 2017-01-01 16:57
This fixes the exception. But not the underlying reason for different behavior on windows, which comes from this regex not matching the windows path segment separator https://github.com/arunoda/next.js/blob/370189b75d34c4ef1c562f2fa170776482b32d9a/server/build/plugins/json-pages-plugin.js#L6

**Comment by nkzawa** [comment] 2017-01-01 17:07
@msand yeah, make sense 👍  Could you send the PR for fixing the regex if possible ?

**Comment by msand** [comment] 2017-01-01 18:03
@nkzawa https://github.com/zeit/next.js/pull/601/commits/91f30d21813491de8cd03af6444edc37c6331cb0 this works in windows

**Comment by DarkAdmiral** [comment] 2017-01-01 19:16
can confirm that beta.5 is last version working in windows

**Comment by ryancole** [comment] 2017-01-01 22:12
Looks like you all have identified the cause of this, already. I just wanted to chime in, as another Windows user, and say that I'm also encountering this issue with beta 12. Below is the error output ...

```
SyntaxError: Unexpected token m in JSON at position 0
    at JSON.parse (<anonymous>)
    at _callee$ (C:\Users\Ryan\Projects\league\packages\league-client\node_modules\next\dist\server\read-page.js:48:32)
    at tryCatch (C:\Users\Ryan\Projects\league\packages\league-client\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\Ryan\Projects\league\packages\league-client\node_modules\regenerator-runtime\runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Ryan\Projects\league\packages\league-client\node_modules\regenerator-runtime\runtime.js:116:21)
    at step (C:\Users\Ryan\Projects\league\packages\league-client\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\Ryan\Projects\league\packages\league-client\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
SyntaxError: Unexpected token m in JSON at position 0
    at JSON.parse (<anonymous>)
    at _callee$ (C:\Users\Ryan\Projects\league\packages\league-client\node_modules\next\dist\server\read-page.js:48:32)
    at tryCatch (C:\Users\Ryan\Projects\league\packages\league-client\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\Ryan\Projects\league\packages\league-client\node_modules\regenerator-runtime\runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Ryan\Projects\league\packages\league-client\node_modules\regenerator-runtime\runtime.js:116:21)
    at step (C:\Users\Ryan\Projects\league\packages\league-client\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\Ryan\Projects\league\packages\league-client\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
```

**Comment by DarkAdmiral** [comment] 2017-01-02 06:53
> But, for me beta 5 still has this error now. (it did not used to)

Try to remove .next folder and do a npm install again.

But you are right, the bug still exists with beta 12.

**Comment by SerkanDayicik** [comment] 2017-01-02 06:57
@ryancole  u can fix changing this line not complety fix but.
node_modules/next/dist/server/build/plugins/json-pages-plugin.js

Line 35  /^bundles\/pages.*\ **TO** /^bundles[/\\]pages.*\

**Comment by harmonous** [comment] 2017-01-02 11:48
me too, this bug occurs when I running example custom-server and custom-server-express on Windows 10. But Windows 7 run smooth.

**Comment by nkzawa** [comment] 2017-01-02 16:06
Closed via https://github.com/zeit/next.js/pull/611

**Closed by nkzawa** 2017-01-02 16:06 UTC
Labels: Type: Bug
