### ISSUE TITLE
Not prefetching _error makes it impossible to display ‘You are offline’

### ISSUE THREAD

**Issue by kachkaev** [zeit/next.js#6283] opened 2019-02-13 08:48 UTC
# Bug report

## Describe the bug

I've got an [Apollo](https://github.com/zeit/next.js/tree/canary/examples/with-apollo)-powered Next.js app where all pages are prefetched via `<Link prefetch />`. Because of that, only GraphQL queries need to be executed when navigating. When a critical `<Query />` on a page like `/posts` or `/post/abc` results in an error, I re-throw this error to let it be handled by the `_error` page. There I've got something like:

```js
  public static getInitialProps({ query, res, err }) {
    const statusCode = res ? res.statusCode : err ? err.statusCode : null;
    let errorType = statusCode && statusCode < 500 ? `${statusCode}` : "5xx";
    if (err && err.message.indexOf("Network error") === 0) {
      errorType = "000";
    }
    return {
      errorType,
    };
  }
```

Thanks to this trick, when a person goes offline while browsing my website, they see:

> ### Network error
> This page could not be loaded because there is a problem with your internet connection. You can try to <1>reload it</1> or return to the <2>previous page</2>, which should be still available.

The method no longer works after upgrading to Next 8, because `_error` does not get preloaded. A white page is shown when a critical GraphQL query is not fulfilled due to a network error.

I understand that not prefetching the `_error` pages saves a bit of bandwidth and network issues are generally rare, but still curious what workaround to use after upgrading from Next 7 to Next 8. If the website audience is mostly on mobile phones, network loss is not that unexpected.

## To Reproduce

I can provide an MWE if necessary.

## System information
 - Version of Next.js: 8.0.0

**Comment by sheerun** [comment] 2019-02-13 18:23
Yeah, I think _error.js should be included in each page instead of prefetching and wasting network request

**Comment by MarchWorks** [comment] 2019-03-25 20:09
Can't an option get added to `next.config.js` to let the developer choose?

**Comment by kachkaev** [comment] 2019-04-18 10:47
Any thoughts on this one? 🙂

**Comment by timneutkens** [comment] 2020-01-02 20:21
Going to close this as this issue didn't get thumbs up in almost a year. In your particular case the 404 is a state of the UI and it should be handled while rendering, not by re-throwing an error.

**Closed by timneutkens** 2020-01-02 20:21 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-30 17:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
