### ISSUE TITLE
Debugging clientside with VS Code 

### ISSUE THREAD

**Issue by davidfells** [zeit/next.js#7679] opened 2019-06-26 15:09 UTC
After following the directions in the guide, I am unable to hit breakpoints in Code for the React application. I've found no way, using Next 8, to get source maps emitted, and I think that is likely related. As it stands when I launch Chrome from Code, nothing happens. Also when launching from Code, you don't get all of your Chrome plugins, so I have tried using an attach process and starting Chrome with CLI parameters for debugging, and that does not work either. 

Any input would be appreciated - I think the docs need to be updated to better reflect the complete set of requirements around debugging.

**Comment by timneutkens** [comment] 2019-06-27 12:26
Next.js actually does output sourcemaps. But this seems related to #4571

Duplicate of #4571

**Closed by timneutkens** 2019-06-27 12:26 UTC

**Comment by balazsorban44** [comment] 2022-01-31 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
