### ISSUE TITLE
API routes hang when error is thrown

### ISSUE THREAD

**Issue by Timer** [zeit/next.js#9463] opened 2019-11-19 18:18 UTC
API routes appear to hang instead of falling back to a default 500 page when an error is unhandled.

**Comment by timneutkens** [comment] 2019-11-19 18:43
I believe this was fixed in next@canary 🤔 there was a bug in the serverless target

**Comment by Timer** [comment] 2019-11-20 04:45
This was in the normal server target, during dev mode. I'll try to reproduce later -- we ran into this bug during today's training.

**Closed** 2020-01-02 23:47 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-30 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
