### ISSUE TITLE
typescript: webpackExclude and webpackInclude magic comments don't work

### ISSUE THREAD

**Issue by Ciantic** [zeit/next.js#10978] opened 2020-03-11 15:50 UTC
# Bug report

## Describe the bug

The code works fine, and I can use it but I get these errors in the console, meaning it was trying to bundle stuff it shouldn't.

I have a dynamic import for sandbox mode, and it has code like this:

```typescript
dynamic((): any => {
    return import(
        /* webpackExclude: /scss/ */
        `./components/${componentName}`
    ).then((module: any) => {
        // ...
    });
});
```

Yet it produces errors like this:

```
./src/components/Advertisements.module.scss
Module build failed: Error: Final loader (./node_modules/next/dist/build/webpack/loaders/error-loader.js) didn't return a Buffer or String

./src/components/Building.module.scss
Module build failed: Error: Final loader (./node_modules/next/dist/build/webpack/loaders/error-loader.js) didn't return a Buffer or String

./src/components/ContactInfo.module.scss
Module build failed: Error: Final loader (./node_modules/next/dist/build/webpack/loaders/error-loader.js) didn't return a Buffer or String

./src/components/_lib.scss
Module build failed: Error: Final loader (./node_modules/next/dist/build/webpack/loaders/error-loader.js) didn't return a Buffer or String
```

It's trying to bundle scss files during the import and fails for some reason, the `module.scss` imports work fine.

I have also added to `tsconfig.json` a setting `"removeComments": false` but it didn't seem to help.

**Edit 1**: Looks like the magic comments work at some level, e.g. adding `/* webpackIgnore: true */` creates whole lot of different errors. But it seems like the exclusion and inclusions does not

## System information

- Version of Next.js: 9.3

**Comment by timneutkens** [comment] 2020-03-11 19:46
You can't rely on this behavior as it's webpack-specific and can change at any time in any release. In general it's a bad idea to use
```
`./components/${componentName}`
```
This will cause a reference of *every file in every directory* under the components directory to be included in a list in the bundle.

Closing this as there's nothing to investigate/change on the Next.js side.

**Closed by timneutkens** 2020-03-11 19:46 UTC

**Comment by Ciantic** [comment] 2020-03-11 20:01
Okay if it's not supported. That import is only during development mode, hence "sandbox".

**Comment by gyto23** [comment] 2020-10-19 15:12
@timneutkens I think this should be mention in nextJs documentations in order to prevent people doing this in the future. I had this issue for months and I could find it for a while because I did not know where to find it.

**Comment by balazsorban44** [comment] 2022-01-29 09:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
