### ISSUE TITLE
What is your experience with shared nextJS components for different projects ?

### ISSUE THREAD

**Issue by vanGalilea** [zeit/next.js#3623] opened 2018-01-26 10:20 UTC
Hi all,

What is your experience regarding an external shared nextJS components module and it's implementation in different projects. 
Basically what we have now is 2 projects that have around 80% of the same code (react components) and we would like to have the 80% code reusable in both nextJS projects (and other future projects).

We currently have an external modules using nextJS with the reusable components, which is linked with npm link to the 2 projects that using the reusable models, everything is going well besides one problem we're experiencing:

The styles of an imported reusable component (written in styled-jsx) are being loaded few seconds after the html is being loaded (so basically you see an image with no style and around 500 ms later you see that the style kicks in).

So how can you make sure there is no delay when loading the styling and would could be the problem causing it ?

And last but not least what is your experience with shared components and later reusing them in different projects ?

tnx

**Comment by dav-is** [comment] 2018-01-26 12:53
Sounds like either SSR isn’t setup for your CSS, or the SSR’s CSS isn’t in the head.

**Comment by vanGalilea** [comment] 2018-01-26 15:13
The css is being loaded oke, but with with delay.

**Comment by timneutkens** [comment] 2018-01-26 15:54
The problem is that there's 2 versions of styled-jsx in this case. And styled-jsx uses a singleton module to keep track of the styles that are rendered on the server. Next.js v5 will allow you to customize the webpack configuration to include certain modules to be transpiled. Removing the requirement to have styled-jsx as a dependency. Which will solve this issue :+1:

**Comment by timneutkens** [comment] 2018-01-26 15:55
More improvements for code sharing are planned for after v5 👍

**Comment by steida** [comment] 2018-02-06 03:27
@timneutkens Do you have an idea how to use Next.js 5 webpack for another targets like React Native or GraphQL backend?

**Comment by tomaswitek** [comment] 2018-02-06 11:06
FYI @vanGalilea @timneutkens I've had a similar problem with `styled-components`. You can't use 2 instances of `styled-compoennts` right now as well. https://github.com/styled-components/styled-components/pull/1324#issuecomment-362547727

**Comment by tomaswitek** [comment] 2018-02-06 11:18
Since [Zones](https://zeit.co/blog/next5#zones) are already released.
I think a lot of questions about sharing code will arise now.
That's why I wanted to prepare an example with shared component in the [with-zones example](https://github.com/tomaswitek/next.js/tree/feature/workspaces-with-zones/examples/with-zones).
My idea was to use [yarn workspaces](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/).
[Something simliar](https://github.com/facebook/create-react-app/tree/next/packages/react-scripts/template#how-to-set-up-a-monorepo) was [merged few days ago](https://github.com/facebook/create-react-app/pull/3741) by the CRA community.
The question is how do we transpile the shared components?
@timneutkens do you have an idea?
Here is my actual state: https://github.com/tomaswitek/next.js/tree/feature/workspaces-with-zones/examples/with-zones

**Comment by merrywhether** [comment] 2018-04-07 05:00
I've run into this same issue, developing a shared component library of components that use styled-jsx resulting in FOUC. Is https://github.com/zeit/styled-jsx/issues/64 the solution to this problem?

**Comment by mentrie** [comment] 2018-05-22 12:18
@tomaswitek Were you able to push further than this ^? How do you handle transpilation of the shared components and ensure that changes in the shared components are automatically reflected in the workspaces?

**Comment by merrywhether** [comment] 2018-06-11 21:52
As an update, I've worked around the FOUC from a library of shared components by exporting a "bound" version of the styled-jsx flush methods, and then in `_document.js`'s `getInitialProps`, I do something like:

```
const page = context.renderPage();
const sharedStyles = moreUIFlush();
...
return {
  ...page,
  sharedStyles,
  ...
};
```

And then in the associated `render()`:

```
return (
  <html>
    <Head>
      {this.props.sharedStyles}
....
);
```

(next itself takes care of flushing and rendering all of the styled-jsx in your app proper).

This is a nice way to workaround https://github.com/zeit/styled-jsx/issues/64.

**Comment by timneutkens** [comment] 2018-12-31 00:39
Let's track this in #706

**Closed by timneutkens** 2018-12-31 00:39 UTC
