### ISSUE TITLE
Dynamic routing: support both `/post` and `post/[id]` without two bundles

### ISSUE THREAD

**Issue by borekb** [zeit/next.js#8443] opened 2019-08-20 13:17 UTC
_Previously [a thread on Spectrum](https://spectrum.chat/next-js/general/dynamic-routing-with-optional-parameters-how-to-avoid-two-bundles~27679250-3f59-4fa4-916d-3ff77a88fed1)._

I need to support these routes:

```
/posts
/posts/1
/posts/2
```

As mentioned in the [dynamic routing RFC](https://github.com/zeit/next.js/issues/7607), a workaround can be implemented like this:

```js
// pages/posts/[id].js
export default () => <h1>Post no. {router.query.id}</h1>

// pages/posts.js
export { default } from './posts/[id]'
```

However, as these are two entrypoints, it creates two bundles, so when I navigate to `/posts` and then to `/posts/1`, I am waiting for a new bundle to load.

Ideally, there would be a way to tell Next.js that all the post-related routes should be handled by a single page component. We might need to wait for non-filesystem-based routing: https://github.com/zeit/next.js/issues/8241.

**Comment by Timer** [comment] 2019-12-23 15:45
Closing as part of #9081

**Closed by Timer** 2019-12-23 15:45 UTC

**Comment by balazsorban44** [comment] 2022-01-30 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
