### ISSUE TITLE
routeChangeStart fires twice when the url has query param

### ISSUE THREAD

**Issue by gaoljie** [zeit/next.js#10875] opened 2020-03-06 20:24 UTC
# Bug report

## Describe the bug

routeChangeStart fires twice when the url has query param,

## To Reproduce

I add routerChange Listener on app componentDidmount
```
  const handleRouterChange = (url: string) => {
      window.dataLayer.push({ event: "PageLoaded", path: url });
    };

    Router.events.on("routeChangeStart", handleRouterChange);
```

Then I visited the homepage with this url: localhost:3000?utm=test

the routeChangeStart was fired twice

![image](https://user-images.githubusercontent.com/10665889/76119876-28faf780-5fa5-11ea-91d1-ef184883ccb2.png)

## Expected behavior

the event should only be fired once

## System information

- OS: macOS
- Browser: chrome
- Version of Next.js: 9.1.3

**Comment by ijjk** [comment] 2020-03-06 21:22
Possible duplicate of: https://github.com/zeit/next.js/issues/9557
Related to: https://github.com/zeit/next.js/issues/8259

**Comment by appriseevi** [comment] 2020-04-02 19:50
the routeChangeStart it not firing at all. I added the event listener to the _app componentDidMount hook But I got no logs!

**Comment by clarencejychan** [comment] 2020-04-04 07:28
^ i'm also having the same problem that the routeChangeStart is not firing

**Comment by appriseevi** [comment] 2020-04-04 09:46
...the event is fired only when you click a link that navigates to another route. The first time you open the page it will not fire!

**Comment by timneutkens** [comment] 2020-04-06 07:35
> ...the event is fired only when you click a link that navigates to another route. The first time you open the page it will not fire!

This is correct behavior, especially when using analytics libraries to track page changes.

**Comment by timneutkens** [comment] 2020-04-06 07:36
This is indeed a duplicate of #9557

**Closed by timneutkens** 2020-04-06 07:36 UTC

**Comment by balazsorban44** [comment] 2022-01-30 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
