### ISSUE TITLE
Image Events aren't fired

### ISSUE THREAD

**Issue by StarpTech** [zeit/next.js#7047] opened 2019-04-16 11:55 UTC
# Bug report

## Describe the bug

No image event handlers are fired. I can't see the output in the console. When I try it with [plain](https://jsfiddle.net/6nfxdbzp/) react it works.

## To Reproduce

Try the snippet in any component.
```jsx
          <img
            src="https://lh3.googleusercontent.com/proxy/ogwfaF0iwa05OnTNQFyD0rZ384sAN74p5xwJE6qfJmrEFcmgxlXo4zg22lrlaLcaS_hp9pFCu8s8QZ-GgDy37DxWVOHpq2B4IV35vb4wgHBWfJiYqI_AVARVMaguPane4Raedg=w530-h212-p-rw"
			onError={() => {
              console.log('#############Error##############')
            }}
            onLoad={() => {
              console.log('#############Load##############')
            }}
          />
```
or [this](https://www.javascriptstuff.com/detect-image-load/) component.

## Expected behavior
onLoad or OnError should be executed

## System information
 - OS: Ubuntu
 - Browser chrome
 - Version of Next.js: 8.0.4

**Comment by StarpTech** [comment] 2019-04-16 17:18
After I had some strange issues with jsx undefined issues during prefetching and route change events I removed it completly and imported my styles with a simple `import './styles.scss'`. This also fixed this issue. Really strange.

**Comment by aralroca** [comment] 2019-04-18 10:37
I have a similar issue with the `onError`. Only is fired sometimes using SSR... Navigating, always is firing the event (always that the image have an error). But the problem start happening reloading the page.

```
<img {...props} onError={onErrorImage}  />
```

```
function onErrorImage(e) {
    e.target.src = fallbackSrc
 }
```

And sometimes, reloading the page, instead of loading the fallback image... Is loading this:

![image](https://user-images.githubusercontent.com/13313058/56355428-8b54d900-61d6-11e9-9967-cccd3f9ce28e.png)

Without firing the `onError` event... :(

**Comment by StarpTech** [comment] 2019-04-18 10:47
@aralroca I have the exact same issue.

**Comment by aralroca** [comment] 2019-04-18 15:27
I guess that the problem is that the `onError` event is fired before the JS is downloaded. It is possible? I dunno how to fix it. Any tip?

**Comment by StarpTech** [comment] 2019-04-18 18:27
> I guess that the problem is that the onError event is fired before the JS is fully downloaded. It is possible? I dunno how to fix it. Any tip?

I don't think so because I also had issues with `onload` and the image was definitly available.

@aralroca I could worarkound it with:

```jsx
  const [noImage, setNoImage] = useState(true);
  let imageEl = null;

  const imageRefCb = image => {
    if (image) {
      imageEl = image;
      if (image.complete) {
        setNoImage(false);
      }
    }
  };

  useEffect(() => {
    imageRefCb(imageEl);
  });

           <img
              src={imageUrl}
              alt={name}
              ref={imageRefCb}
              onError={() => setNoImage(true)}
              onLoad={() => setNoImage(false)}
            />
```
I think it can happen that the image is `complete` before the event handles are attached.

**Comment by aralroca** [comment] 2019-04-18 23:01
I did a similar workaround, I explained here:

* https://github.com/facebook/react/issues/15446#issuecomment-484709466

However, is not 100% ideal because the fallback image is added after hydration and not before. This causes that if the image is loaded before the hydration, first is displaying the broken image status from the browser, and then, after the hydration, is displaying the correct fallback image.

For me the ideal is to catch the image error before the hydration to change to the fallback image ASAP as possible. And avoiding the broken image status from the browser.

**Comment by nick-barth** [comment] 2019-08-05 14:09
`  const [noImage, setNoImage] = useState(true);
  let imageEl = null;

  const imageRefCb = image => {
    if (image) {
      imageEl = image;
      if (image.complete) {
        setNoImage(false);
      }
    }
  };

  useEffect(() => {
    imageRefCb(imageEl);
  });

  return (
    <>
        <img
          className="hero__bg-image"
          onLoad={() => this.setState({ noImage: false })}
          src={`/static/imgs/hero/${props.game}.jpg`}
          alt={props.game}
          ref={imageRefCb}
          onLoad={() => setNoImage(false)}
        />
        <div
          className={`hero__overlay ${!noImage && "hero__overlay--loaded"}`}
        />`

Even with @starptech's workaround, I'm still experiencing huge differences on dev and production in regards to image loading.

**Comment by nickLeidman** [comment] 2019-09-17 07:21
I have similar issue with images. OnLoad event works only with external images. For example: 
```
import React, { useState } from "react";

export default props => {
	const [catLoaded, setCatLoaded] = useState(false);
	const [externalPhotoLoaded, setExternalPhotoLoaded] = useState(false);
	return (
		<>
			<div>
				<img
					style={{ width: 400 }}
					src="/static/img/cat.jpg"
					onLoad={() => setCatLoaded}
				/>
				{catLoaded ? <p>Local cat is here!</p> : ""}
			</div>
			<div>
				<img
					style={{ width: 400 }}
					src="https://upload.wikimedia.org/wikipedia/commons/5/5e/21-224-5054_NNP_Synevyr_RB_18.jpg"
					onLoad={() => setExternalPhotoLoaded(true)}
				/>
				{externalPhotoLoaded ? <p>External photo is here!</p> : ""}
			</div>
		</>
	);
};
```

Here are two images, one of them is local and another is external, onLoad event fires only on external one, though clearly both are loaded. I have created [repository](https://github.com/nickLeidman/next-images-issue) which reproduces this issue. May be someone has a clue for why this is happening and is there a fix for that?

**Comment by kimnh-0823** [comment] 2019-11-21 13:03
Hello, I have the same issue in my `Avatar` component. I just want to display a fallback image when the avatar is broken. But, `onError` is not fire. Here is my code:

```javascript
class Avatar extends React.Component {
  componentDidMount() {
    this.$el.addEventListener('error', (event) => {
      const fallbackImage = getFallbackImage(
        event.target.getAttribute('src'),
        event.target.dataset,
      )

      event.target.setAttribute('src', fallbackImage)
      event.target.setAttribute('srcset', `${fallbackImage} 1x`)
    }, { once: true })
  }

  render() {
    const { image, size, alt } = this.props
    const className = _trimEnd(`v-avatar ${this.props.className}`)
    const srcAttrs = getImages(image, size)

    return (
      <img
        ref={$el => this.$el = $el} // eslint-disable-line
        {...{ className, ...srcAttrs, alt }}
      />
    )
  }
}
```

**Comment by kimyvgy** [comment] 2019-11-21 13:05
Hello, I have the same issue in my `Avatar` component. I just want to display a fallback image when the avatar is broken. But, `onError` is not fire. Here is my code:

```javascript
class Avatar extends React.Component {
  componentDidMount() {
    this.$el.addEventListener('error', (event) => {
      const fallbackImage = getFallbackImage(
        event.target.getAttribute('src'),
        event.target.dataset,
      )

      event.target.setAttribute('src', fallbackImage)
      event.target.setAttribute('srcset', `${fallbackImage} 1x`)
    }, { once: true })
  }

  render() {
    const { image, size, alt } = this.props
    const className = _trimEnd(`v-avatar ${this.props.className}`)
    const srcAttrs = getImages(image, size)

    return (
      <img
        ref={$el => this.$el = $el} // eslint-disable-line
        {...{ className, ...srcAttrs, alt }}
      />
    )
  }
}
```

Anyone here for help?

**Comment by timneutkens** [comment] 2020-01-02 20:44
Closing this as it's upstream in React: https://github.com/facebook/react/issues/15446

**Closed by timneutkens** 2020-01-02 20:44 UTC
Labels: Is Upstream

**Comment by balazsorban44** [comment] 2022-01-30 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
