### ISSUE TITLE
Antd Pagination can't work at Production mode when I updating next to 3.0.6

### ISSUE THREAD

**Issue by hadg** [zeit/next.js#2849] opened 2017-08-25 12:17 UTC
Antd's Pagination can't work at Production mode when I updating next to 3.0.6
Since I upgraded the next to 3.0.6, I found that Antd Pagination component can't work in Production mode, but it was running well in development mode.

This is the error I get in the browser console (next 3.0.6, Production mode):
Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=object&args[]=%20Check%20the%20render%20method%20of%20%60a%60. 

![360 -296690704](https://user-images.githubusercontent.com/4592450/29713398-eeb8147e-89d0-11e7-9ef7-6762669c8a36.jpg)

When I roll back the version to 2.4.1, everything is fine

| Tech    | Version |
|---------|---------|
| next    |    3.0.6     |
| node    |    8.0.0     |
| OS      |     widows&linux    |
| browser |   chrome      |
| antd|    2.12.6     |

**Comment by thinnakrit** [comment] 2017-08-25 13:56
I have this problem, I fixed by the downgrade to use version 3.0.2

**Comment by hadg** [comment] 2017-08-25 15:20
@thinnakrit I tried it, but it did not work, but thank you :)

**Comment by supra28** [comment] 2017-08-29 06:43
Hey, How did you deduce it was the pagination component?
I have the same problem so I downgraded it to 2.4.9
this is the issue https://github.com/zeit/next.js/issues/2810

**Comment by sunchenyang** [comment] 2017-08-30 09:50
@hadg  did you solve this problem?

**Comment by hadg** [comment] 2017-08-30 14:34
@supra28 Because I found that only in the page containing the pagination component will appear problem, and I also tested a page that only contained pagination component and then reported error. Confirmed that the pagination component is indeed caused, your mistake is also caused by the pagination component?

**Comment by hadg** [comment] 2017-08-30 14:35
@sunchenyang nope

**Comment by supra28** [comment] 2017-08-31 04:21
@hadg , I don't know I haven't tested it, but people have reported problems with form as well and I'm using both pagination and forms on several pages. I'll try to isolate the problem when I get enough time, I have downgraded to version 2.4.9 for the time being.

**Comment by hadg** [comment] 2017-08-31 09:16
@supra28 I have a lot of forms on the page but no problem, I hope you can find a solution to the problem;)

**Comment by whphhg** [comment] 2017-09-13 08:02
I'm having the same problem if Antd Pagination is present in any component.

**Comment by fxh615** [comment] 2017-09-15 03:07
use next/dynamic  may work

**Comment by whphhg** [comment] 2017-09-15 09:55
I've tried using all examples in https://github.com/zeit/next.js/#dynamic-import but no luck.

**Comment by afc163** [comment] 2017-09-15 10:23
I can't reproduce it by using https://github.com/zeit/next.js/tree/v3-beta/examples/with-ant-design . And import Pagination in `pages/index.js`.

- antd@2.13.1
- next@3.2.2

```bash
npm run build
npm start
```

<img width="569" alt="image" src="https://user-images.githubusercontent.com/507615/30478177-8eeeda8c-9a42-11e7-88e1-12cbb2d80fc2.png">

It works fine, is anyone can make a reproduible, minimal demo?

**Comment by supra28** [comment] 2017-09-15 11:10
@afc163 Render the Pagination component on the client side and you'll see the error.

**Comment by whphhg** [comment] 2017-09-15 15:19
I'm trying to find the minimal possible example using the website I've posted above, but so far I found that if you remove _any_ page from the `pages/` directory the issue is gone. As soon as you have more than 4 pages the issue is there.

Digging more.

**Comment by fxh615** [comment] 2017-09-20 02:25
@whphhg  did you solve this problem?

**Comment by whphhg** [comment] 2017-09-20 07:11
No, I've reverted to `next@2.4.9` which doesn't have the production problem. I've managed to create the minimal reproducible example [here](https://github.com/whphhg/nextjs-issue-2849) after 4-5 hours of reducing everything as much as I could.

**Comment by fxh615** [comment] 2017-09-27 02:47
let antd components render on client side may ok. @whphhg

**Comment by MickaelBZH** [comment] 2017-10-04 16:56
I had this issue ... and believe it or not, but removing pages/index.js which I don't use fixes it. 

But someone should seriously look at this issue ... one of the weirdest issue I've seen.

**Comment by chhuang** [comment] 2017-10-10 00:50
This is not only the pagination, I'm getting error #130 with datepicker, tooltip and popover. Only in production build, dev is fine.

**Comment by haneefghanim** [comment] 2017-11-05 20:59
Also getting a similar error with the react-datepicker and react-slider libraries.

**Comment by JonathanWbn** [comment] 2017-11-15 11:34
Same here with react-infinite-calendar. All fine in dev, 130 error when build.

**Comment by whphhg** [comment] 2018-01-24 21:50
Updating to `next@4.2.3` and `antd@3.1.4` solved the issue for me.

**Closed** 2018-03-16 12:19 UTC
