### ISSUE TITLE
Performance measurement of page compiling.

### ISSUE THREAD

**Issue by patryk-janik** [zeit/next.js#9905] opened 2020-01-02 13:44 UTC
Hey!
We've made a lot of migration in our company some time ago (monorepo, typescript, and bit.dev decentralized components library) and now we have a performance issue with website compiling.
In short, our page compiles sometimes more than 40second 😮  
I would like to find a cause of it. I'm wondering if this is a typechecking problem or compiling problem and go deeper with it. I mean e.g. why compilations cost us so much time?
For now, I have just 
![image](https://user-images.githubusercontent.com/54390399/71669758-19c1b880-2d6e-11ea-8f0c-c846737cb2c8.png)
This is only information if typescript checking is running or compilation. How to make more details about this process?
I would be interested in data like how much time each step costs me, what files are checked/compiled.
Are there any available tools, plugin or whatever existing already that can help me with finding a cause of my performance issue?

**Comment by Timer** [comment] 2020-01-02 14:03
Please try disabling development-time type checking:
```js
// next.config.js
module.exports = {
  typescript: {
    ignoreDevErrors: true,
  },
}
```

**Comment by patryk-janik** [comment] 2020-01-02 15:11
@Timer I have turned it off and still got this performance issue. It looks like we eliminated typeschecks from a potential cause list. But how to see deeply why compilation time takes so long, what files are compiled? Maybe there are some circular dependencies somewhere, how to track them out?

**Comment by Timer** [comment] 2020-01-02 15:45
Analyzing this performance issue requires generic webpack instrumentation, there's no hooks exposed directly by Next.js — any webpack tracing instructions should work!

See https://webpack.js.org/plugins/profiling-plugin/

**Comment by timneutkens** [comment] 2020-01-02 15:47
There is an internal profiling mechanism that I built into Next.js on top of the webpack profiling plugin under the `experimental.profiling` flag. It gives clearer results as it includes both compilation runs in one profile.

**Comment by timneutkens** [comment] 2020-01-02 15:52
I'll close this issue as it's not actionable from our side.

Generally this is something that we investigate for companies under enterprise support. Feel free to email enterprise@zeit.co about that.

**Closed by timneutkens** 2020-01-02 15:52 UTC

**Comment by balazsorban44** [comment] 2022-01-30 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
