### ISSUE TITLE
Using <Link> in Edge will result in an error

### ISSUE THREAD

**Issue by BosenY** [zeit/next.js#8011] opened 2019-07-17 09:50 UTC
# Bug report

## Describe the bug

Use the Link component to jump when in the Edge browser.

## To Reproduce

```js
<div className={`${baseClassName}-lists`}>
              {resultList.map((item, index) => {
                return (
                  <div className={`${baseClassName}-lists-item`} key={item.districtId}>
                    {loader ? (
                      <MyLoader />
                    ) : (
                      <Link 
                      href={`/destinationDetail?destinationId=${item.districtId}`} 
                      as={`${host}${config.prefix}/${ReplaceHorizontalLine(item.englishName || item.name)}-${item.districtId}/`}>
                        <a
                          title={item.name}
                          target="_self"
                          onClick={() => {

                            window['__bfi'].push(['_tracklog', '102358', `click_index=${index + 1}&click_name=${item.name}`])
                          }}>
                          <div className="img-warp">
                            <LazyLoad once={true} resize={true}>
                              <img src={handlePicUrl(item.coverImage, 500, 280)} alt={item.name} onError={e => handleImageError(e)} />
                            </LazyLoad>
                          </div>

                          <p>{item.name}</p>
                        </a>
                      </Link>
                    )}
                  </div>
                )
              })}
            </div>
```
I use <Link> to jump to another page on one page, then other browsers are fine, but Edge will report an error.
## Expected behavior

Can jump normally.

## Screenshots

![zm0k1600000108k8a59CD](https://user-images.githubusercontent.com/16064272/61367069-7bc05b80-a8bd-11e9-88d3-5137f7160935.png)

## System information

- OS: [Windows]
- Browser Edge 15.15063
- Version of Next.js: v8.1.1-canary.34

**Comment by BosenY** [comment] 2019-07-17 10:50
Visit https://www.styled-components.com

Click on the releases tab using Edge and it will reappear

**Comment by MarchWorks** [comment] 2019-07-17 11:19
That version is very old I don't get the error with Edge 44.18362.1.0

**Comment by lfades** [comment] 2019-07-17 16:33
@BosenY I tried using the same edge version in Windows but I'm still unable to reproduce this issue. It works okay

**Comment by lfades** [comment] 2019-07-17 16:34
@MarchWorks Latest is actually 18 for the html browser, but in any case I haven't managed to see it fail, I'm closing it for now

**Closed by lfades** 2019-07-17 16:34 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
