### ISSUE TITLE
__NEXT_DATA__.dataManager is undefined, crashes loading

### ISSUE THREAD

**Issue by Nickman87** [zeit/next.js#7638] opened 2019-06-22 22:56 UTC
# Bug report

## Describe the bug

After upgrading to next.js 8.1.0 I get the following error when I try to load my deployed website:
SyntaxError: Unexpected token u in JSON at position 0

It seems to occure during the rehydration on the client side during `JSON.parse(window.__NEXT_DATA__.dataManager);` where dataManager is undefined.

## Expected behavior

The page should just load, there are no special things happening on the server.

## Screenshots

![image](https://user-images.githubusercontent.com/870416/59969619-26a95800-9552-11e9-9358-157fe387300b.png)

## System information

- OS: windows (Azure web app)
- Browser: I am using chrome
- Version of Next.js: 8.1.0

## Additional context

After downgrading back to 8.0.1, everything works as expected.

**Comment by timneutkens** [comment] 2019-06-23 10:49
Please provide a full reproduction. It sounds like you're doing something non-standard causing Next.js to break.

**Comment by Nickman87** [comment] 2019-06-23 12:08
I will try to see if I can get a minimal setup working!

**Comment by Timer** [comment] 2019-07-18 13:21
Closing as it's been about a month with no reproduction. We'll be happy to reopen if a reproduction is put together!

**Closed by Timer** 2019-07-18 13:21 UTC
Labels: Can't Reproduce

**Comment by simmbiote** [comment] 2020-01-16 10:17
I also am now encountering this, only in production and with no significant change.

@Nickman87 did you manage to get past this?

@Timer or @timneutkens can you offer some insights to assist me in debugging:
What is dataManager for?
In which instances would it be excluded from the __NEXT_DATA__ content (as it is in this case, causing the app to break)?

**Comment by Nickman87** [comment] 2020-01-16 10:27
@simmbiote I had some crazy custom config to change the bundles, as far as I know, I updated that one with the new information I could find inside the basic webpack config.
That is the only thing I can remember changing to be able to upgrade next.

**Comment by timneutkens** [comment] 2020-01-16 10:28
@simmbiote you could upgrade to the latest version of Next.js, not sure why it wouldn't be included, maybe you upgraded and are caching something?

**Comment by simmbiote** [comment] 2020-01-16 10:45
@timneutkens ok thanks will try to upgrade to 9.2 (currently on 9.1.7).
I realize now, this started to happen after setting up a new provider (React Context api) - I wrapped my components inside my <Layout> component with the new provider ie. <SiteProvider></SiteProvider>. Trying to avoid Redux. Not sure if that information is useful.

**Comment by Timer** [comment] 2020-01-16 17:47
`dataManager` references no longer exist in Next.js. If you're encountering this, it's due to custom code:
![image](https://user-images.githubusercontent.com/616428/72549258-5ad1c680-385e-11ea-8d4a-7bea3608efcf.png)

**Comment by balazsorban44** [comment] 2022-01-30 16:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
