### ISSUE TITLE
Unable to import module 'now__launcher': Error

### ISSUE THREAD

**Issue by skaptox** [zeit/next.js#7724] opened 2019-07-01 23:25 UTC
# Bug report

## Describe the bug

I am trying deploy my app to now but I am getting this error. It works fine locally (now dev and yarn dev)

![image](https://user-images.githubusercontent.com/29805241/60471741-09504a00-9c34-11e9-8117-b23c493398fb.png)

> 2019-07-01T22:56:53.680Z  preparing cache ...
> 2019-07-01T22:56:53.686Z  producing cache file manifest ...
> 2019-07-01T22:56:56.011Z  cache file manifest produced
> 2019-07-01T22:57:35.622Z  START RequestId: 892f0269-c7b8-42ae-ab86-09684960bebc Version: $LATEST
>                           Unable to import module 'now__launcher': Error
>                           Original error: Cannot find module '/var/task/../assets/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node'
>                               at Object.wPNL (/var/task/page.js:120179:17)
>                               at __webpack_require__ (/var/task/page.js:23:31)
>                               at Object.XpdW (/var/task/page.js:84200:12)
>                               at __webpack_require__ (/var/task/page.js:23:31)
>                               at Object.g1pB (/var/task/page.js:99917:27)
>                               at __webpack_require__ (/var/task/page.js:23:31)
>                               at Object.Ou8q (/var/task/page.js:66490:14)
>                               at __webpack_require__ (/var/task/page.js:23:31)
>                               at Object.BYZf (/var/task/page.js:22732:12)
>                               at __webpack_require__ (/var/task/page.js:23:31)
>                           END RequestId: 892f0269-c7b8-42ae-ab86-09684960bebc
>                           REPORT RequestId: 892f0269-c7b8-42ae-ab86-09684960bebc	Duration: 17.18 ms	Billed Duration: 100 ms 	Memory Size: 3008 MB	Max Memory Used: 139 MB	
> 2019-07-01T22:57:38.064Z  START RequestId: 8d49a238-f9b7-4fdf-abc3-63665b6cdef2 Version: $LATEST
>                           Unable to import module 'now__launcher': Error
>                           Original error: Cannot find module '/var/task/../assets/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node'
>                               at Object.wPNL (/var/task/page.js:89020:17)
>                               at __webpack_require__ (/var/task/page.js:23:31)
>                               at Object.XpdW (/var/task/page.js:66409:12)
>                               at __webpack_require__ (/var/task/page.js:23:31)
>                               at Object.g1pB (/var/task/page.js:76404:27)
>                               at __webpack_require__ (/var/task/page.js:23:31)
>                               at Object.Ou8q (/var/task/page.js:54326:14)
>                               at __webpack_require__ (/var/task/page.js:23:31)
>                               at Object.BYZf (/var/task/page.js:18512:12)
>                               at __webpack_require__ (/var/task/page.js:23:31)
>                           END RequestId: 8d49a238-f9b7-4fdf-abc3-63665b6cdef2
>                           REPORT RequestId: 8d49a238-f9b7-4fdf-abc3-63665b6cdef2	Duration: 13.40 ms	Billed Duration: 100 ms 	Memory Size: 3008 MB	Max Memory Used: 121 MB	

Next.config.js

```module.exports = () => {
  /* eslint-disable */
  const withLess = require("@zeit/next-less");
  const lessToJS = require("less-vars-to-js");
  const withImages = require("next-images");

  const fs = require("fs");
  const path = require("path");
  // Where your antd-custom.less file lives
  const themeVariables = lessToJS(
    fs.readFileSync(path.resolve(__dirname, "./assets/css/theme.less"), "utf8")
  );
  // fix: prevents error when .less files are required by node
  if (typeof require !== "undefined") {
    require.extensions[".less"] = file => {};
  }


 // https://github.com/zeit/next.js/issues/6073
  const withAssetRelocator = (nextConfig = {}) => {
    return Object.assign({}, nextConfig, {
      webpack(config, options) {
        const { isServer } = options;

        if (isServer) {
          config.node = Object.assign({}, config.node, {
            __dirname: false,
            __filename: false
          });

          config.module.rules.unshift({
            test: /\.(m?js|node)$/,
            parser: { amd: false },
            use: {
              loader: "@zeit/webpack-asset-relocator-loader",
              options: {
                outputAssetBase: "assets",
                existingAssetNames: [],
                wrapperCompatibility: true,
                escapeNonAnalyzableRequires: true
              }
            }
          });
        }

        if (typeof nextConfig.webpack === "function") {
          return nextConfig.webpack(config, options);
        }
        return config;
      }
    });
  };

  return withAssetRelocator(
    withImages(
      withLess({
        lessLoaderOptions: {
          javascriptEnabled: true,
          modifyVars: themeVariables // make your antd custom effective
        },
        target: "serverless"
      })
    )
  );
};
```

now.json

```{
  "version": 2,
  "name": "hola",
  "builds": [
    {
      "src": "next.config.js",
      "use": "@now/next",
      "config": { "maxLambdaSize": "50mb" }
    }
  ]
}
```
packages.json
```{
  "name": "create-next-example-app",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "acorn": "^6.1.1",
    "antd": "^3.20.0",
    "babel-plugin-import": "^1.12.0",
    "firebase": "^6.2.4",
    "isomorphic-unfetch": "3.0.0",
    "less": "^3.9.0",
    "less-vars-to-js": "^1.3.0",
    "next": "^8.1.0",
    "next-images": "^1.1.2",
    "next-redux-wrapper": "^3.0.0-alpha.3",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-alice-carousel": "^1.15.1",
    "react-dom": "^16.8.6",
    "react-redux": "^7.1.0",
    "redux": "^4.0.1",
    "regenerator-runtime": "^0.13.2",
    "reqwest": "^2.0.5",
    "xhr2": "^0.2.0"
  },
  "devDependencies": {
    "@zeit/next-less": "^1.0.1",
    "@zeit/webpack-asset-relocator-loader": "^0.5.7"
  }
}
```
babelrc
```{
  "presets": ["next/babel"],
  "plugins": [["import", { "libraryName": "antd", "style": false }]]
}
```

According to [this ](https://github.com/zeit/next.js/issues/5750#issuecomment-442313585) I tried the following but it did not work either. (the same error)

```
const { PHASE_PRODUCTION_SERVER } =
  process.env.NODE_ENV === "development"
    ? {}
    : !process.env.NOW_REGION
    ? require("next/constants")
    : require("next-server/constants");

module.exports = (phase, { defaultConfig }) => {
  if (phase === PHASE_PRODUCTION_SERVER) {
    // Config used to run in production.
    return {};
  }

  // ✅ Put the require call here.
  const withCSS = require("@zeit/next-css");

  const withLess = require("@zeit/next-less");
  const lessToJS = require("less-vars-to-js");
  const withImages = require("next-images");

  const fs = require("fs");
  const path = require("path");
  // Where your antd-custom.less file lives
  const themeVariables = lessToJS(
    fs.readFileSync(path.resolve(__dirname, "./assets/css/theme.less"), "utf8")
  );
  // fix: prevents error when .less files are required by node
  if (typeof require !== "undefined") {
    require.extensions[".less"] = file => {};
  }

  // https://github.com/zeit/next.js/issues/6073
  const withAssetRelocator = (nextConfig = {}) => {
    return Object.assign({}, nextConfig, {
      webpack(config, options) {
        const { isServer } = options;

        if (isServer) {
          config.node = Object.assign({}, config.node, {
            __dirname: false,
            __filename: false
          });

          config.module.rules.unshift({
            test: /\.(m?js|node)$/,
            parser: { amd: false },
            use: {
              loader: "@zeit/webpack-asset-relocator-loader",
              options: {
                outputAssetBase: "assets",
                existingAssetNames: [],
                wrapperCompatibility: true,
                escapeNonAnalyzableRequires: true
              }
            }
          });
        }

        if (typeof nextConfig.webpack === "function") {
          return nextConfig.webpack(config, options);
        }
        return config;
      }
    });
  };

  return withAssetRelocator(
    withImages(
      withLess({
        lessLoaderOptions: {
          javascriptEnabled: true,
          modifyVars: themeVariables // make your antd custom effective
        },
        target: "serverless",

        analyzeServer: ["server", "both"].includes(process.env.BUNDLE_ANALYZE),
        analyzeBrowser: ["browser", "both"].includes(
          process.env.BUNDLE_ANALYZE
        ),
        bundleAnalyzerConfig: {
          server: {
            analyzerMode: "static",
            reportFilename: "../bundles/server.html"
          },
          browser: {
            analyzerMode: "static",
            reportFilename: "../bundles/client.html"
          }
        }
      })
    )
  );
};
```

**Comment by ijjk** [comment] 2019-07-02 20:01
Hi, does removing the `if (typeof require !== 'undefined')` part fix the build error? I'm not able to reproduce from the provided info. 

Note: we have updated the [with-ant-design-less](https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less) example to not need this workaround.

**Comment by Timer** [comment] 2019-07-02 20:06
Hi @skaptox! If the above change doesn't fix it, please downgrade `@zeit/webpack-asset-relocator-loader` to `0.5.5` and it should work.

**Comment by skaptox** [comment] 2019-07-02 22:04
> Hi, does removing the `if (typeof require !== 'undefined')` part fix the build error? I'm not able to reproduce from the provided info.
> 
> Note: we have updated the [with-ant-design-less](https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less) example to not need this workaround.

Hello @ijjk , thanks for answering. When I used that config I got the following error.

> Using external babel configuration
> Location: "/home/ignisgravitas/workspace/kiwi/shopping/.babelrc"
> Build error occurred
TypeError: (0 , _styleChecker.default) is not a function
    at Object.g5iu (/home/ignisgravitas/workspace/kiwi/shopping/.next/serverless/pages/index.js:101063:55)
    at __webpack_require__ (/home/ignisgravitas/workspace/kiwi/shopping/.next/serverless/pages/index.js:23:31)
    at Object.3PeW (/home/ignisgravitas/workspace/kiwi/shopping/.next/serverless/pages/index.js:5506:36)
    at __webpack_require__ (/home/ignisgravitas/workspace/kiwi/shopping/.next/serverless/pages/index.js:23:31)
    at Object.lbd2 (/home/ignisgravitas/workspace/kiwi/shopping/.next/serverless/pages/index.js:108842:36)
    at __webpack_require__ (/home/ignisgravitas/workspace/kiwi/shopping/.next/serverless/pages/index.js:23:31)
    at Object.G9T2 (/home/ignisgravitas/workspace/kiwi/shopping/.next/serverless/pages/index.js:44877:18)
    at __webpack_require__ (/home/ignisgravitas/workspace/kiwi/shopping/.next/serverless/pages/index.js:23:31)
    at Module.iEYB (/home/ignisgravitas/workspace/kiwi/shopping/.next/serverless/pages/index.js:103308:14)
    at __webpack_require__ (/home/ignisgravitas/workspace/kiwi/shopping/.next/serverless/pages/index.js:23:31)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```module.exports = () => {
  /* eslint-disable */
  const withLess = require("@zeit/next-less");
  const lessToJS = require("less-vars-to-js");
  const withImages = require("next-images");

  const fs = require("fs");
  const path = require("path");
  // Where your antd-custom.less file lives
  const themeVariables = lessToJS(
    fs.readFileSync(path.resolve(__dirname, "./assets/css/theme.less"), "utf8")
  );

  const withAssetRelocator = (nextConfig = {}) => {
    return Object.assign({}, nextConfig, {
      webpack(config, options) {
        const { isServer } = options;

        if (isServer) {
          config.node = Object.assign({}, config.node, {
            __dirname: false,
            __filename: false
          });

          config.module.rules.unshift({
            test: /\.(m?js|node)$/,
            parser: { amd: false },
            use: {
              loader: "@zeit/webpack-asset-relocator-loader",
              options: {
                outputAssetBase: "assets",
                existingAssetNames: [],
                wrapperCompatibility: true,
                escapeNonAnalyzableRequires: true
              }
            }
          });
        }

        if (typeof nextConfig.webpack === "function") {
          return nextConfig.webpack(config, options);
        }
        return config;
      }
    });
  };

  return withAssetRelocator(
    withImages(
      withLess({
        lessLoaderOptions: {
          javascriptEnabled: true,
          modifyVars: themeVariables // make your antd custom effective
        },
        target: "serverless",
        webpack: (config, { isServer }) => {
          if (isServer) {
            const antStyles = /antd\/.*?\/style.*?/;
            const origExternals = [...config.externals];
            config.externals = [
              (context, request, callback) => {
                if (request.match(antStyles)) return callback();
                if (typeof origExternals[0] === "function") {
                  origExternals[0](context, request, callback);
                } else {
                  callback();
                }
              },
              ...(typeof origExternals[0] === "function" ? [] : origExternals)
            ];

            config.module.rules.unshift({
              test: antStyles,
              use: "null-loader"
            });
          }
          return config;
        }
      })
    )
  );
};
```
> Hi @skaptox! If the above change doesn't fix it, please downgrade `@zeit/webpack-asset-relocator-loader` to `0.5.5` or upgrade to `0.5.8` and it should work.

Hello @Timer, downgrade @zeit/webpack-asset-relocator-loader to 0.5.5 solved the problem. Thank you.

**Comment by ijjk** [comment] 2019-07-02 23:10
Closing since the issue appears to be resolved. Feel free to reply if you're still encountering trouble with this.

**Closed by ijjk** 2019-07-02 23:10 UTC

**Comment by balazsorban44** [comment] 2022-01-31 13:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
