### ISSUE TITLE
[with-sentry] back button doesn't work after some errors

### ISSUE THREAD

**Issue by netmet12** [zeit/next.js#6783] opened 2019-03-25 16:07 UTC
## Example name
with-sentry

## Describe the bug
After hitting an error, going back doesn't take you the previous page, it get's stuck in the error display. This error was reproducible in the example as well as my large app

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to https://with-sentry-example.watchmaxx.now.sh/
2. Click on a link
3. Press the back button
4. It doesn't go back, 

## Expected behavior
Going back should take you back

## System information
 - Version of Next.js: 8

**Comment by netmet12** [comment] 2019-04-03 18:14
I've got a little bit of clarity on this now, I still don't have a solution though.

This is an issue that a lot of people face with error boundaries, the error needs to be reset.

This is a bit of a hacky workaround, it only works if you click on a second like twice for some reason. But at least it works. If I could listen to beforePopState the same way I could listen to routeChangeStart it might help. I'd appreciate feedback.
 I added this listener to my constructor in _app.js
`Router.events.on("routeChangeStart", this.handleRouteChange);`

and then this function that clears / resets the error state when navigating elsewhere, i.e. to a working route
```
handleRouteChange = () => {
  if (this.state.hasError) {
      this.setState({
        hasError: false,
        errorEventId: undefined
      });
    }
  };
```

Here are some relevant links
https://stackoverflow.com/questions/48121750/browser-navigation-broken-by-use-of-react-error-boundaries
https://github.com/facebook/react/issues/11846
https://github.com/facebook/react/issues/14049
https://www.reddit.com/r/reactjs/comments/7vxt6m/recovering_from_a_react_error_boundary/+&cd=6&hl=en&ct=clnk&gl=us

**Comment by linus-amg** [comment] 2019-04-13 10:33
hi @netmet12 the `for some reason` might be because the route change already got triggered - but the `hasError` state was still true. You could try re-executing the last route after your setState, then it might works always, not only on the second click.

**Comment by leerob** [comment] 2019-04-23 17:47
Should be addressed here https://github.com/zeit/next.js/pull/7119.

**Comment by Timer** [comment] 2019-07-18 13:05
https://github.com/zeit/next.js/pull/7360 was merged 👍

**Closed by Timer** 2019-07-18 13:05 UTC
Labels: good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-31 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
