### ISSUE TITLE
next/router & next/link don't work on iphones with ios version 10.x.x 

### ISSUE THREAD

**Issue by WEN-JY** [zeit/next.js#9934] opened 2020-01-04 02:16 UTC
# Bug report

## Describe the bug
my nextjs version is 9.1.7-canary.14,but it's still not work when I downgrade to 9.0.0 
here the code is:
```
import Router from 'next/router';
...
handleClick = (index) => {
        Router.push('/user');
    };
...
<div onClick={this.handleClick}>click</div>
```
I've tried :
import {withRouter} from'next/router'
import Link from'next/link'
and all above don't  work on ios10.x.x 
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. create-next-app next-demo
2. cd next-demo and create a new test page file in pages folder 'test.js',and then type some code in this file 

```
import React from 'react'
const Test = (props) => (
  <div>
    test
  </div>
)
export default Test 
```
3. and add router to home page:
import {useRouter}from 'next/router'
const router=useRouter()
the whole test content in home.js is:
```
import React from 'react'
import {useRouter}from 'next/router'
const Home = () => {
  const router=useRouter()
  const handleClick=()=>{
    console.log('click')
    router.push('/test')}
  return (
  <div>
      <h1 className="title" onClick={handleClick}>welcome to Next!</h1>
  </div>
)}
export default Home
```
4. 
start developing,run yarn dev,you will find that all above works well ,you click the h1 tag and page changed, but this will not work on ios 10.x.x

## Expected behavior

next/router support ios10.x.x

## Screenshots

![image](https://user-images.githubusercontent.com/36290410/71758467-fb2d0000-2eda-11ea-948e-6e82ae03e795.png)

## System information

- OS:ios10.0.1 and ios10.2 and  ios10.3  are tested,not work 
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js:9.1.7 &9.0.0 &9.1.7-canary.14

**Comment by timneutkens** [comment] 2020-01-04 11:59
Duplicate of #9851

**Closed by timneutkens** 2020-01-04 11:59 UTC

**Comment by balazsorban44** [comment] 2022-01-30 17:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
