### ISSUE TITLE
Can't run dev and build after upgrade from 9.2.1 to 9.3 [SCSS Modules]

### ISSUE THREAD

**Issue by dszymczuk** [zeit/next.js#11061] opened 2020-03-13 20:30 UTC
# Bug report
After migrate from NExt 9.2.1 to Next 9.3 and using the built-in sass feature.
When trying to build I've got error (I've changed some paths):

```shell
next build

Using external babel configuration
Location: "/PATH_TO_PROJECT/src/client/.babelrc"
Creating an optimized production build

Failed to compile.

./PATH_TO_SCSS/OffersFilterMobile.module.scss 1:21
Module parse failed: Identifier directly after number (1:21)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
$mobileMenuHeight: 60px;
| $inputAddressWidth: 100%;
|

Build error occurred
Error: > Build failed because of webpack errors
```

When try to run `npm run dev` I've got:

```shell
> NODE_ENV_CONFIG=.env.dev node index.js

> Using external babel configuration
> Location: "PATH_TO_PROJECT/src/client/.babelrc"
[ error ] ./src/pages/_app.scss 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import "../scss/variables";
|
| body {
[ wait ]  compiling ...
[ error ] ./src/pages/_app.scss 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import "../scss/variables";
|
| body {
> Ready on http://localhost:4000
[ event ] build page: /_error
[ wait ]  compiling ...
[ error ] ./src/components/TopMenu/topMenu.module.scss 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import "../../scss/mobileMixins";
|
|
{ Error: Cannot find module 'PATH_TO_PROJECT/src/client/.next/server/static/development/pages/_document'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.loadComponents (PATH_TO_PROJECT/src/client/node_modules/next/dist/next-server/server/load-components.js:24:25)
    at DevServer.findPageComponents (PATH_TO_PROJECT/src/client/node_modules/next/dist/next-server/server/next-server.js:521:60)
    at DevServer.renderErrorToHTML (PATH_TO_PROJECT/src/client/node_modules/next/dist/next-server/server/next-server.js:803:33)
    at DevServer.renderErrorToHTML (PATH_TO_PROJECT/src/client/node_modules/next/dist/server/next-dev-server.js:15:811)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
[ error ] ./src/pages/_app.scss 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import "../scss/variables";
|
| body {

```

## Describe the bug
I'm trying to migrate to Next 9.3 and use the built-in sass feature.

## To Reproduce
* Remove `@zeit/next-sass`  from `next.config.js` and `package.json`
* Remove .next folder
* Add saas `npm install sass`
* Build application

## Expected behavior
Build successfully.

## System information
* OS: macOS Mojave 10.15.3
* Version of Next.js: 9.3.0
* Version of Node: 10.16.0
* Version of npm: 6.14.2

## Additional context
My `next.config.js`

```js
const withCSS = require('@zeit/next-css');
const withImages = require('next-images');
const withSourceMaps = require('@zeit/next-source-maps')({
  devtool: 'hidden-source-map'
});
const withPlugins = require('next-compose-plugins');

const path = require('path');

const NODE_ENV_CONFIG = process.env.NODE_ENV_CONFIG || '.env.dev';
const configPath = path.resolve(__dirname, './envs/', NODE_ENV_CONFIG);
const { parsed: localEnv } = require('dotenv').config({ path: configPath });


const isProduction = process.env.NODE_ENV === "production";

const cssConfig = {
  cssModules: false,
  ignoreOrder: true,
};

const nextConfig = {
  env: localEnv,
  poweredByHeader: false,
  webpack(config, options) {
    config.module.rules.push({
      // test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
      test: /\.(eot|woff|woff2|ttf)$/,
      use: {
        loader: 'url-loader',
        options: {
          limit: 100000,
          name: '[name].[ext]'
        }
      }
    });
    return config
  }
};

module.exports = withPlugins([
  [withImages],
  [withCSS, cssConfig],
  [withSourceMaps],
], nextConfig);
```

Some packages from `package.json` which should be related to this issue.

```json
  "dependencies": {
    "@zeit/next-css": "^1.0.1",
    "@zeit/next-source-maps": "0.0.4-canary.1",
    "axios": "^0.18.1",
    "bootstrap": "^4.4.1",
    "classnames": "^2.2.6",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "next": "^9.3.0",
    "next-compose-plugins": "^2.2.0",
    "next-images": "^1.2.0",
    "react": "^16.13.0",
    "react-dom": "^16.13.0",
    "react-helmet": "^5.2.1",
    "react-redux": "^5.1.2",
    "react-router-bootstrap": "^0.24.4",
    "react-router-dom": "^4.3.1",
    "react-scripts": "^3.3.0",
    "redux": "^4.0.4",
    "redux-devtools-extension": "^2.13.5",
    "redux-form": "^7.4.2",
    "sass": "^1.26.3"
  },
  "devDependencies": {
    "@babel/cli": "^7.7.5",
    "@babel/core": "^7.7.5",
    "@babel/node": "^7.7.4",
    "@babel/preset-env": "^7.7.6",
    "@testing-library/react": "^9.4.0",
    "babel-jest": "^25.1.0",
    "enzyme": "^3.7.0",
    "enzyme-adapter-react-16": "^1.15.1",
    "jest": "^25.1.0",
    "nightwatch": "^1.3.2"
  },
```

**Comment by timneutkens** [comment] 2020-03-14 09:37
Please add a complete reproduction. However looking at your next.config.js you're adding @zeit/next-css which disables all built-in styling support to avoid conflicts.

**Comment by dszymczuk** [comment] 2020-03-15 17:22
I removed `@zeit/next-css` but the next error appeared.

Failed to compile.

```shell
./PATH_TO_PROJECT/map/OffersMap.module.scss
CssSyntax error: Selector ":global(img[src*="gstatic.com/"],img[src*="googleapis.com/"])" is not pure (pure selectors must contain at least one local class or id) (103:1)

  101 | .infoWindowPrice {
  102 |   text-align: center;
> 103 | }
      | ^
  104 |
  105 | :global(img[src*="gstatic.com/"], img[src*="googleapis.com/"]) {
```

I can see that built-in solution doesn't support `:global` . How can I fix it?
I some cases I can't move globals to different file.

**Comment by timneutkens** [comment] 2020-03-16 10:41
If you want to select global items you have to prefix it with a local class, eg:

```
.local-class :global(.global-class) {
  color: 'red'
}
```

**Comment by timneutkens** [comment] 2020-03-16 10:42
Going to close this issue as it's not actionable (no complete reproduction was provided) and seems to be related to using next-css/next-sass instead of built-in support.

**Closed by timneutkens** 2020-03-16 10:42 UTC
Labels: Please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-30 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
