### ISSUE TITLE
Link with activeClassName

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#141] opened 2016-10-28 16:48 UTC
Similar to react-router's `Link`, it would be nice to be able to customize CSS when a link is active, e.g with an `activeClassName` property.

**Comment by nkzawa** [comment] 2016-10-28 17:18
duplicate of  https://github.com/zeit/next.js/issues/127

**Comment by sedubois** [comment] 2016-11-03 17:31
This isn't a duplicate, right now there is no way to style a link specifically when a route is active. React-router provides this in [147](https://github.com/ReactTraining/react-router/blob/6eeb7ad358f987520f5b519e48bdd31f725cbade/modules/isActive.js) + [233](https://github.com/ReactTraining/react-router/blob/6eeb7ad358f987520f5b519e48bdd31f725cbade/modules/PatternUtils.js) LOCs.

**Comment by nkzawa** [comment] 2016-11-03 18:19
ohhh, sorry!

It might be nice to have the `activeClassName` property, but you can manually detect if a route is active and set any class to the Link anyway ?

**Comment by luisrudge** [comment] 2016-11-04 14:35
this would be super nice to have indeed!

**Comment by sedubois** [comment] 2016-11-04 14:39
@nkzawa manually detecting requires 2 things:
- passing the router URL all the way from the page root down to the component having the Link. Either it pollutes all the intermediate component signatures or need to set up a contextType.
- comparing the router URL with the Link's href. As shown in react-router above (isActive method), it's not trivial.

Would be great to have Next take care of this instead of every user reimplementing it.

**Comment by viankakrisna** [comment] 2017-01-01 09:25
Or maybe a withLocation HOC. And wrap Link with that HOC. Then import that instead of `next/link`

**Comment by arunoda** [comment] 2017-01-01 10:09
One way to support is provide a way to get current state of the router using `next/router`. But it's not working on the Server.

So, what ever thing we need to done inside a `componentDidMount` hook.
@nkzawa If we allow `next/router` on the server (Just for SSR) this would be great.
Is there's any chance we could support it?

**Comment by trevordmiller** [comment] 2017-01-16 06:14
Below is my current workaround. The key part is `const isActive = window.location.pathname === route.path` which works for me, but if you have query params and such would need a bit more logic. I agree it would be nice to have this as a render callback argument from `next/link` :)

# Navigation.js
```
import React from 'react'
import Link from 'next/link'

const routes = [
  {
    path: '/',
    title: 'Home',
  },
  {
    path: '/about',
    title: 'About',
  },
  {
    path: '/blog',
    title: 'Blog',
  },
]

export default () => (
  <nav style={{
    background: uiGroups.backgroundShade,
    display: 'flex',
  }}>
    {routes.map((route, index) => {
      const isActive = window.location.pathname === route.path
      return (
        <Link 
          key={index}
          href={route.path}
        >
          <a style={{
            textDecoration: 'none',
            padding: spacing.medium,
            background: isActive ? uiGroups.background : uiGroups.backgroundShade,
            color: isActive ? uiGroups.userCurrentState : uiGroups.gray3,
          }}>
            {route.title}
          </a>
        </Link>
      )
    })}
  </nav>
)
```

**Comment by trevordmiller** [comment] 2017-01-16 06:23
Nevermind, that doesn't work with server refresh

**Comment by timneutkens** [comment] 2017-01-16 06:59
I'm thinking it might be implemented using `componentDidMount` since it's only executed client side. I'm not sure if it's executed every route change though.

**Comment by mallendeo** [comment] 2017-01-16 07:08
@trevordmiller you can use `getInitialProps` on your top-level pages.

```js
import React from 'react'
import Thing from '../components/Thing'

export default class extends React.Component {
  static async getInitialProps ({ req }) {
    return { pathname: req && req.url }
  }

  render () {
    return (
      <Thing pathname={this.props.pathname} />
    )
  }
}
```

Then in your component
```js
const isActive = window.location.pathname === route.path || pathname === route.path
```

**Comment by bassbump** [comment] 2017-02-03 03:51
I think this would be a very good addition to the Links, I wonder if Zeit did it on zeit.co the way @mallendeo described

**Comment by hieuhlc** [comment] 2017-04-02 05:12
Hey guys is this feature currently still developing?

**Comment by arunoda** [comment] 2017-04-02 10:17
I think this is pretty easy to do without core support.

**Comment by hieuhlc** [comment] 2017-04-02 10:35
I tried adding active classname in componentDidMount but it doesn't seem right. At first render active classname does not occur.

**Comment by mtford90** [comment] 2017-04-09 08:06
@arunoda do you have a good example of how to implement this given that it's pretty easy?

I use query parameters within my app and I've had to do some fairly ugly stuff to get the active class names to render the same on both client & server. Core support would be much nicer.

**Comment by andrewmclagan** [comment] 2017-04-21 03:03
We are doing something like this: pesudo code

````javascript
import Router from 'next/router';

const isActiveRoute = path => {
    return this.props.pathname === path;
}

isActiveRoute.getInitialProps = ({ isServer, pathname }) => {
  if (isServer) {
    return { pathname };
  } else {
    return { pathname: Router.pathname };
  }
}

export default isActiveRoute;
````

**Comment by steida** [comment] 2017-04-21 23:32
@andrewmclagan It's not so easy. 

This usage can't handle URL change:

`<Component isActive={Router.isActive('/path/to/check')} />`

URL changes, so whenever we need to handle URL change, we need higher order component to enforce rerender. Something like `injectUrl(PageHeader)`

**Comment by andrewmclagan** [comment] 2017-04-22 03:31
@steida yeah i figured that would be the case.

What about a wrapping component that uses context (as in my example above) that passes a className or isActive property to the child component?

**Comment by bassbump** [comment] 2017-04-22 08:30
fwiw I still think this should be built into `next/link`

**Comment by steida** [comment] 2017-04-23 01:18
> I think this is pretty easy to do without core support.

> Do you have a good example of how to implement this given that it's pretty easy?

> Use the `title`, Luke.

That's how I am doing it in [Este](https://github.com/este/este).

```jsx
// @flow
import A from './a';
import Box from './box';

const HeaderA = ({ children, href, title }) => (
  <A
    backgroundColor="primary"
    bold
    color="white"
    href={href}
    isActive={title === children}
    paddingHorizontal={0.5}
    paddingVertical={0.5}
    prefetch
  >
    {children}
  </A>
);

type PageHeaderProps = { title: string };

const PageHeader = ({ title }: PageHeaderProps) => (
  <Box
    backgroundColor="primary"
    flexDirection="row"
    flexWrap="wrap"
    marginVertical={0.5}
    paddingHorizontal={0.5}
  >
    <HeaderA href="/" title={title}>Home</HeaderA>
    <HeaderA href="/about" title={title}>About</HeaderA>
  </Box>
);

export default PageHeader;
```

**Comment by ayazhussein** [comment] 2017-05-21 10:57
The solution I found (might not be the best one) is to use 
```path-to-regexp classnames```  packages and I made a util function that checks if the route is active by passing the props to my nav component...

```javascript
// ./lib/activePath.js
import pathToRegexp from "path-to-regexp";

export function activePath(currentPath, path , options) {
  const regexPath = pathToRegexp(path, options);

  const result = regexPath.exec(currentPath);
  return result;
}

```

```javascript 
// ./component/Header.js
import React, { Component } from 'react';
import Link from "next/link";
import { activePath } from "../lib/activePath";
import classnames from "classnames";
class Header extends Component {
  render() {
    const { url } = this.props;
    const { pathname } = url;
    return (
      <header>
        <nav className="navbar navbar-toggleable-md navbar-light bg-faded">
          <button className="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon" />
          </button>
          <a className="navbar-brand">Title</a>
          <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div className="navbar-nav">
              <Link href="/">
                <a className={classnames("nav-item nav-link", { active: activePath(pathname, "/", { strict: true }) })}>Home <span className="sr-only">(current)</span></a>
              </Link>
              <Link href="/about">
                <a className={classnames("nav-item nav-link", { active: activePath(pathname, "/about", { strict: true }) })} >About</a>
              </Link>
              <Link href="/about/us">
                <a className={classnames("nav-item nav-link", { active: activePath(pathname, "/about/us", { strict: true }) })} >About US</a>
              </Link>
              <Link href="/contact">
                <a className={classnames("nav-item nav-link", { active: activePath(pathname, "/contact", { strict: true }) })} >Contact</a>
              </Link>
            </div>
          </div>
        </nav>
      </header >
    );
  }
}

export default Header;
```
the header is in my layout component so I have to pass the props to it on every page so that the header would have access to url props...

I'm open to other solutions too :D

**Comment by arunoda** [comment] 2017-05-21 17:57
Guys, we are going to implement a new API to make these simple.
See: https://github.com/zeit/next.js/issues/2032

**Comment by andrewmclagan** [comment] 2017-05-21 23:50
@arunoda Thanks I feel this was always going to be the right direction. We basically took the HOC route ourselves.

**Comment by postor** [comment] 2017-06-13 08:09
hi guys, I made it using `next-routes` which makes one route define for both server side and client side, example here https://hello-next-lhafgwnfxp.now.sh/ and code here https://github.com/postor/nextjs-boilerplate

**Comment by timneutkens** [comment] 2017-07-02 11:55
We'll merge the withRoute HOC after v3 has been released. Then this will be possible. https://github.com/zeit/next.js/pull/2352

**Closed by timneutkens** 2017-07-02 11:55 UTC
Labels: Nice to have, Type: Enhancement
