### ISSUE TITLE
Using a src subdirectory

### ISSUE THREAD

**Issue by mschipperheyn** [zeit/next.js#1179] opened 2017-02-16 12:25 UTC
I notice that Next.js assumes that all source code is basically put in the root, e.g. pages directory.

I prefer to keep a separate src directory, so it's clear what's source and what is not (build, passwords, etc). Is this possible / easy? How do I do it?

**Comment by sedubois** [comment] 2017-02-16 13:03
Duplicate of https://github.com/zeit/next.js/issues/819

**Closed** 2017-02-16 13:12 UTC
