### ISSUE TITLE
How to remove core-js from bundles

### ISSUE THREAD

**Issue by fabiospampinato** [zeit/next.js#8883] opened 2019-09-27 17:12 UTC
# Bug report

## Describe the bug

`core-js` is getting loaded in my bundles, multiple times actually, both in my `main.js` file and my `_app.js` file, and I have no use for it.

## To Reproduce

It's the default behavior, the default hello-world example should reproduce this.

## Expected behavior

There should be a way to get rid of `core-js` from my bundles, as I don't even need to target old browsers. How do I do that?

I've tried setting the following `.babelrc` file and `core-js` is still getting loaded:

```json
{
  "presets": [
    ["next/babel", {
      "preset-env": {
        "useBuiltIns": false,
        "targets": {
          "chrome": 76,
          "node": 11
        }
      },
      "transform-runtime": {
        "corejs": false
      }
    }]
  ]
}
```

**Comment by timneutkens** [comment] 2019-09-27 17:30
Duplicate of #6931

**Closed by timneutkens** 2019-09-27 17:30 UTC

**Comment by fabiospampinato** [comment] 2019-09-27 17:34
@tim-phillips Isn't the other issue about removing core-js in the future from Next.js by default? What I need is to remove it in the present.

**Comment by balazsorban44** [comment] 2022-01-31 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
