### ISSUE TITLE
The analyze-bundles example has a console error

### ISSUE THREAD

**Issue by saltycrane** [zeit/next.js#6361] opened 2019-02-20 02:21 UTC
# Examples bug report

## Example name
`analyze-bundles`

## Describe the bug
After following the ["Download manually" instructions](https://github.com/zeit/next.js/tree/canary/examples/analyze-bundles#download-manually), there is an error in the terminal and the page at http://localhost:3000/ displays "Internal Server Error"

## To Reproduce
1. `curl https://codeload.github.com/zeit/next.js/tar.gz/canary | tar -xz --strip=2 next.js-canary/examples/analyze-bundles`
2. `cd analyze-bundles`
3. `npm install`
4. `npm run dev`
5. See the following error:

```
 ERROR  Failed to compile with 1 errors                                          6:03:15 PM

 error  in ./node_modules/next/dist/client/next-dev.js

Module parse failed: Unexpected token (34:6)
You may need an appropriate loader to handle this file type.
|
|
> import('./noop');
| var _window = window,
|     assetPrefix = _window.__NEXT_DATA__.assetPrefix;

 @ multi ./node_modules/next/dist/client/next-dev
```

## Expected behavior
Expect to see no errors.

## System information
 - OS: macOS 10.14.2
 - Browser: Chrome 72
 - Version of Next.js: 8.0.1
 - Node: v10.15.0
 - npm: v6.8.0

## Additional context

Looks to be caused by https://github.com/zeit/next.js/issues/6259

**Comment by timneutkens** [comment] 2019-02-20 13:46
Duplicate of #6240

**Closed by timneutkens** 2019-02-20 13:46 UTC
