### ISSUE TITLE
How to add another module.exports redirects() in next.config.js

### ISSUE THREAD

**Issue by Fazlur00** [zeit/next.js#10463] opened 2020-02-08 16:03 UTC
const withCSS = require('@zeit/next-css');
module.exports = withCSS({
    webpack: function (config) {
        config.module.rules.push({
            test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
            use:{
                loader:'url-loader',
                options:{
                    limit:100000,
                    name:'[name].[ext]'
                }
            }
        })
        return config
    }
})

**Comment by ijjk** [comment] 2020-02-10 22:10
Hi, if you are asking how to leverage the new experimental redirects which should only be used when experimenting as they are not stable yet, you can do so with the below config. Also note: CSS is built-in to Next.js since [v9.2](https://nextjs.org/blog/next-9-2) so we recommend you update to that version and remove `@zeit/next-css` since it has some known bugs which are resolved in the built-in support 

If you update to the latest version you can use the redirects with the below config
```js
module.exports = {
  experimental: {
    redirects() {
      return [
        // redirects here
      ]
    }
  }
}
```

If you need to continue using `@zeit/next-css` you can use the below config
```js
const withCSS = require("@zeit/next-css");

module.exports = withCSS({
  webpack: function(config) {
    config.module.rules.push({
      test: /.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
      use: {
        loader: "url-loader",
        options: {
          limit: 100000,
          name: "[name].[ext]"
        }
      }
    });
    return config;
  },
  experimental: {
    redirects() {
      return [
        // redirects here
      ]
    }
  }
});
```

Please follow the issue template in the future

**Closed by ijjk** 2020-02-10 22:10 UTC

**Comment by balazsorban44** [comment] 2022-01-30 13:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
