### ISSUE TITLE
Imported Error component doesn't get changes from _error.js

### ISSUE THREAD

**Issue by ReTWi** [zeit/next.js#10015] opened 2020-01-09 18:48 UTC
# Bug report

## Describe the bug

As sad in [docs](https://nextjs.org/docs/advanced-features/custom-error-page#reusing-the-built-in-error-page), you can reuse the built-in error page. But changes to _error.js page doesn't change apperance for imported Error component.

## To Reproduce

- _error.js was changed.
- index.js render Error component.
- changes not visible

[Codesandbox example.](https://codesandbox.io/s/cold-water-gl2nu?fontsize=14&hidenavigation=1&theme=dark)

## Expected behavior

Error component should look like _error.js page.

## System information

OS: macOS 10.15.2
Browser: Chrome 79.0.3945.88
Version of Next.js: 9.1.7

## Additional context

Also typescript omplains about `Property 'statusCode' does not exist on type 'Response'`.
![Image](https://i.imgur.com/mczDY7I.png)

**Comment by timneutkens** [comment] 2020-01-09 19:53
`next/error` exposes the built-in error component as per the documentation. If you want to use your own _error you can import it directly.

The typescript error is unrelated, you're doing a `fetch()` and assigning it to `res` which is not the `res` from the getInitialProps context.

**Closed by timneutkens** 2020-01-09 19:53 UTC

**Comment by balazsorban44** [comment] 2022-01-30 16:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
