### ISSUE TITLE
Moving .jsx components from Create-React-App

### ISSUE THREAD

**Issue by valorloff** [zeit/next.js#2847] opened 2017-08-25 09:10 UTC
I'm trying move .jsx components looks like: 
```
class Header extends React.Component {
  constructor(props) {
............................................
}
render() {
    return 
    (
    <div className="nav-container">
      <a id="top"></a>
        <nav>
          <div className="nav-utility">
            <div className="module left">
 ..........................)
```
from production ready CreateReactApp to new next.js project and once faced with module parse fail:
```
Module parse failed: /home/orloff/projects/dst-next/src/app/components/layout/header.jsx Unexpected token (40:6)
You may need an appropriate loader to handle this file type.
| render() {
|     return
|     ( <div>Header</div>
|   //   <div className="nav-container">
|   //     <a id="top"></a>

 @ ./components/App.js 11:14-44
 @ ./pages?entry
 @ multi ./pages?entry
```
what is correct way solve it?

**Comment by Florian-R** [comment] 2017-08-25 09:13
This is caused by the jsx extension. See #2391 and #2699

**Comment by timneutkens** [comment] 2017-08-25 09:36
Closing as duplicate

**Closed by timneutkens** 2017-08-25 09:36 UTC

**Comment by valorloff** [comment] 2017-08-25 09:43
Thanks!
i'm add content of examples/with-jsx/next.config.js and next llaunched properly

**Comment by valorloff** [comment] 2017-08-25 10:55
but not working properly:
`yarn build-next && yarn build-firebase`
```
> Using "webpack" config function defined in next.config.js.
> Failed to build on /tmp/53bd3882-64aa-43bd-9ad1-3cdc2e54cc93
{ Error: ./components/App.js
Module not found: Error: Can't resolve './layout/header' in '/home/valaoffice/projects/dst-next/src/app/components'
resolve './layout/header' in '/home/valaoffice/projects/dst-next/src/app/components'
```
though
header.jsx in place, what is wrong?

**Comment by valorloff** [comment] 2017-08-25 13:31
```
using description file: /home/valaoffice/projects/dst-next/src/app/package.json (relative path: ./components)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /home/valaoffice/projects/dst-next/src/app/package.json (relative path: ./components)
    using description file: /home/valaoffice/projects/dst-next/src/app/package.json (relative path: ./components/layout/header)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/valaoffice/projects/dst-next/src/app/components/layout/header doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/valaoffice/projects/dst-next/src/app/components/layout/header.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /home/valaoffice/projects/dst-next/src/app/components/layout/header.json doesn't exist
      as directory
        /home/valaoffice/projects/dst-next/src/app/components/layout/header doesn't exist
[/home/valaoffice/projects/dst-next/src/app/components/layout/header]
[/home/valaoffice/projects/dst-next/src/app/components/layout/header.js]
[/home/valaoffice/projects/dst-next/src/app/components/layout/header.json]
[/home/valaoffice/projects/dst-next/src/app/components/layout/header]
 @ ./components/App.js 11:14-40
```
but in next.config.js explicitly defined:

```
module.exports = {
  distDir: "../functions/next",
  // Add extensions
  pagesExtensions: [
    'js',
    'jsx',
    'json'],
```
