### ISSUE TITLE
Error page rendering twice

### ISSUE THREAD

**Issue by kochis** [zeit/next.js#2980] opened 2017-09-24 18:54 UTC
We are using the custom `_error.js` page, and we're seeing an issue where anything other than a `404` from a server error is rendering the error page twice.

It looks like it's rendering once on the server (the render HTML only has 1 error page), but also rendering an _additional_ error page on the client.

I'm not sure if this is a bug, or if there is something wrong with the way we're handling the error (we're letting next handle the uncaught error). Any guidance would be appreciated.

I've created an example that replicates the issue here: 

https://github.com/kochis/next.js/tree/duplicate-error-example/examples/duplicate-error-pages

**Screenshot**

![screen shot 2017-09-24 at 3 11 20 pm](https://user-images.githubusercontent.com/814934/30785818-acb889ce-a13a-11e7-96df-4f026d142889.png)

**Comment by timneutkens** [comment] 2017-09-25 06:11
Duplicate of https://github.com/zeit/next.js/issues/2573, lets track it there

**Closed by timneutkens** 2017-09-25 06:11 UTC
