### ISSUE TITLE
[Improvement] Reduce number of extra divs

### ISSUE THREAD

**Issue by vanesyan** [zeit/next.js#3095] opened 2017-10-15 08:47 UTC
Hello there! Firstly, thank you for a such great product. As I've said in title, there can be made improvement to minimize output from extra `div`s.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
No extra `div`s necessary. 

## Current Behavior
Some part of code is wrapper with `div` to make it possible to be returned by React (extended old behavior of React, changed since introduction of Fibers).

## Context
Since next.js version 4 supports only React 16+, we can use some of it's new possibilities, such as 
component that returns only it's children:

```js
const Fragment = ({ children }) => children;
```
By using the `Fragment` we can replace all `div` that act only as wrapper (for instance in `<NextScript />`).

**Comment by timneutkens** [comment] 2017-10-15 10:22
Duplicate of #2708

**Comment by timneutkens** [comment] 2017-10-15 10:22
I'll fix this sometime 👍

**Closed by timneutkens** 2017-10-15 10:22 UTC
