### ISSUE TITLE
ReferenceError: 'Promise' is not defined on IE11 for ^2.0.0-beta.25

### ISSUE THREAD

**Issue by manuelro** [zeit/next.js#1138] opened 2017-02-14 22:25 UTC
Just a `ReferenceError: 'Promise' is not defined` on Internet Explorer 11 for `^2.0.0-beta.25`.

Here is the full error log: 
```
ReferenceError: 'Promise' is not defined
   at updateOnClient (http://localhost:3000/_next/-/commons.js:16822:3)
   at mount (http://localhost:3000/_next/-/commons.js:16800:3)
   at componentWillMount (http://localhost:3000/_next/-/commons.js:16741:7)
   at Anonymous function (http://localhost:3000/_next/-/main.js:16665:11)
   at measureLifeCyclePerf (http://localhost:3000/_next/-/main.js:16392:5)
   at ReactCompositeComponent.performInitialMount (http://localhost:3000/_next/-/main.js:16664:9)
   at ReactCompositeComponent.mountComponent (http://localhost:3000/_next/-/main.js:16575:7)
   at ReactReconciler.mountComponent (http://localhost:3000/_next/-/main.js:1493:5)
   at ReactMultiChild.Mixin.mountChildren (http://localhost:3000/_next/-/main.js:21058:11)
   at ReactDOMComponent.Mixin._createContentMarkup (http://localhost:3000/_next/-/main.js:17995:9)
```

**Comment by sergiodxa** [comment] 2017-02-14 22:30
IE doesn't support Promises, and I suppose Next.js isn't polyfilling it, you can use Polyfill.io (https://polyfill.io/v2/docs/) to support Promises in IE. Just add it in your `pages/_document.js` to it's loaded in each page before the client-side render.

**Comment by timneutkens** [comment] 2017-02-14 22:47
Duplicate of https://github.com/zeit/next.js/issues/975. For now you can indeed add polyfill.io or any other Promise polyfill for that matter.

**Closed by timneutkens** 2017-02-14 22:47 UTC

**Comment by manuelro** [comment] 2017-02-14 22:52
Good to know. Thanks!

**Comment by Musikero31** [comment] 2018-02-14 03:42
http://kangax.github.io/compat-table/es6/

You can check it here.
