### ISSUE TITLE
Next 8.1.0 doesn't server-side render

### ISSUE THREAD

**Issue by MicroBenz** [zeit/next.js#7064] opened 2019-04-17 10:22 UTC
# Bug report

## Describe the bug

After upgrade Nextjs from 8.0.4 to 8.1.0, it doesn't server-side render anymore. It's become client-side render apps instead. But the weird thing is the redux store + styled-components are server-side render correctly. But the site content doesn't server-side render.

## To Reproduce

Using Nextjs 8.1.0 -> Build -> Running apps -> See the result!

## Expected behavior
The apps should server-side rendered.

## Screenshots
![image](https://user-images.githubusercontent.com/9103800/56279874-25fbdc00-6133-11e9-9712-3a9369b0c780.png)

The entry `<div id="_next">` should not be an empty div.

## System information
 - OS: Linux Server (node:8.12.0-alpine image)
 - Version of Next.js: 8.1.0

**Comment by tangye1234** [comment] 2019-04-18 03:24
maybe you get the wrong properties in _document.js getInitialProps.
SSR static data is changed into the _document.js component props，if you forget to fetch the super.getInitialProps or forget to use `await`, then you will get a broken SSR.

**Comment by nhulongctk35** [comment] 2019-04-19 01:53
I got the same issue when upgrade to *8.1.0*

**Comment by timneutkens** [comment] 2019-04-19 05:47
Please provide a reproduction. It's impossible to help otherwise.

**Comment by MicroBenz** [comment] 2019-04-22 04:08
@timneutkens I just upgrade Next.js version from 8.0.4 to 8.1.0 and it's break without changing my codebase.

**Comment by timneutkens** [comment] 2019-04-22 07:44
@MicroBenz again:

> Please provide a reproduction. It's impossible to help otherwise.

**Comment by funwhilelost** [comment] 2019-04-24 02:00
> Maybe you get the wrong properties in _document.js getInitialProps.
> SSR static data is changed into the _document.js component props，if you forget to fetch the super.getInitialProps or forget to use `await`, or maybe you forget to propagate the result to the child document properties then you will get a broken SSR.

@tangye1234 can you provide some more details?  I'm trying to understand why my current app is getting data for getInitialProps, then server-side-rendering the page, but then and `<Link />` is causing the getInitialProps to run on each navigation event.  It's already pre-rendered all that prop data.

**Comment by nhulongctk35** [comment] 2019-04-25 06:25
Oops. I fixed the issue by update the middle like this.
```server.use(nextI18NextMiddleware(nextI18next));```
This issue is not related to upgrade nextjs to latest version. Please check the setting of i18n in the your `server.js` file.

**Comment by Timer** [comment] 2019-04-29 13:16
All,

We're unable to reproduce this so I'm going to close this issue since it's been over a week.

If anyone is able to provide a reproducible demo, we'd be more than happy to take a look!

Thanks.

**Closed by Timer** 2019-04-29 13:16 UTC
Labels: Can't Reproduce

**Comment by WardVH** [comment] 2019-06-19 09:54
> Oops. I fixed the issue by update the middle like this.
> `server.use(nextI18NextMiddleware(nextI18next));`
> This issue is not related to upgrade nextjs to latest version. Please check the setting of i18n in the your `server.js` file.
> 
> ```
>   const server = express();
> 
>   server.use(nextI18NextMiddleware(nextI18next));```
> ```

@nhulongctk35 how exactly did this change fixed the issue for you?

**Comment by patheticGeek** [comment] 2019-12-29 20:49
> > Oops. I fixed the issue by update the middle like this.
> > `server.use(nextI18NextMiddleware(nextI18next));`
> > This issue is not related to upgrade nextjs to latest version. Please check the setting of i18n in the your `server.js` file.
> > ```
> >   const server = express();
> > 
> >   server.use(nextI18NextMiddleware(nextI18next));```
> > ```

I don't have a translation. What did you exactly do?

**Comment by balazsorban44** [comment] 2022-01-30 11:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
