### ISSUE TITLE
Importing external components with images has broken images

### ISSUE THREAD

**Issue by Maaaz-Shaheen** [zeit/next.js#8025] opened 2019-07-18 08:02 UTC
# Bug report

## Describe the bug

I have two projects. One is a react project library of reusable components and the other is a Next.js one. I am making a component in the react project and using an img tag in that component with the src of the img tag being imported in the component.js file. 

However, upon importing this component in the Next.js project and attempting to use it there, I get the following error and the images show up as broken.

Warning: Prop `src` did not match. Server: "[object Object]" Client: "{correct reference here}"

Upon inspecting the images, it can be seen that all their src attributes have been set to "src=[object Object]. 

The images do load up on the first time you run it in the dev environment, but break upon refreshing and stay broken.

The img srcs get replaced by [object Object]. This should not happen and the img should render.

## To Reproduce

1) Make react component in a separate project and use an img tag in it. Import a image and set it as the src attribute of the img tag.

2) Import the component in your Next.js project and use it. The image will show up broken and src will be src="[object Object]" and the error will show up in the console.

## Expected behavior

From what I understand, Next requires such resources like images to be stored in the static folder.  However, that does not apply here. The external component uses its own image and it shows up broken. 

## Screenshots

# System information

- OS:Windows
- Version of Next.js: 8.1.0

## Additional context

 Next.config.js file

![Screenshot (64)](https://user-images.githubusercontent.com/25780644/61440032-11aac380-a95c-11e9-855e-ef22ca4ae925.png)

**Comment by Timer** [comment] 2019-07-18 16:06
Closing this as it did not follow the issue template: (1) we need a reproducible example and (2) support requests belong on [Spectrum](https://spectrum.chat/next-js). Thanks!

**Closed by Timer** 2019-07-18 16:06 UTC

**Comment by balazsorban44** [comment] 2022-01-31 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
