### ISSUE TITLE
if is secondary directory project use Router.push('/test?=123') then use npm

### ISSUE THREAD

**Issue by gitforalan** [zeit/next.js#9742] opened 2019-12-14 01:38 UTC
1.this is secondary directory and npm run export cdn is mobile 

2.can help check why js file is 404 if use npm run export  
error path http://localhost:8080/mobile/_next/static/runtime/main-aa30553951ce84819708.js

2.like this Router.push('/ slot?Type=123') Only then will this kind of error occur only rooter no have query is work like this  Router.push('/ slot') it's ok 

3.Is it a problem of route mapping?

4.u can try use Router.push('/test?type=1212')  will 404 in secondary directory then use npm run export           

thanks 
- OS: [e.g. macOS]
<img width="1335" alt="93d7c835-8d5a-40a1-bbee-3db2199c6211-%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202019-12-13%20%E4%B8%8B%E5%8D%886 44 10" src="https://user-images.githubusercontent.com/20920428/70841316-6c394480-1e54-11ea-807e-941da2d193c3.png">
<img width="497" alt="bd1a7ed9-cc27-4a51-9cb2-94c236aa9515-%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202019-12-13%20%E4%B8%8B%E5%8D%887 03 47" src="https://user-images.githubusercontent.com/20920428/70841317-6cd1db00-1e54-11ea-9fab-0e40b8ae0cc5.png">

- Browser  [chrome]
- Version of Next.js: [e.g. 9.1.5]

**Comment by ijjk** [comment] 2019-12-14 03:08
Hi, please use the issue template. It sounds like you are looking for `assetPrefix` see [here](https://github.com/zeit/next.js#cdn-support-with-asset-prefix) for info on this option.

Closing as this doesn't appear to be an issue with Next.js itself

**Closed by ijjk** 2019-12-14 03:08 UTC

**Comment by balazsorban44** [comment] 2022-01-30 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
