### ISSUE TITLE
When request to /static/*  makes the application node server crash

### ISSUE THREAD

**Issue by snaerth** [zeit/next.js#9400] opened 2019-11-13 13:15 UTC
# Bug report

Critical bug!!!!!
Make a request to /static/* anything or just even /static.
What happens is that the application just hangs and then the node server badly crashes. See image below of the crash

## To Reproduce

1. Run 'yarn dev'
2. Go to 'http://localhost:3000/static/favicons/apple-icon-152x152.png'

## Expected behavior

A 404 page would appear

## Screenshots

This is the error when the server crashes
![image](https://user-images.githubusercontent.com/8678089/68766643-2439be80-0617-11ea-8015-b55c9f1372ea.png)

## System information

- OS: macOS
- Browser Chrome
- A version of Next.js: 9.1.3

## Additional context

We found out the hard way why our servers where always crashing

**Comment by Timer** [comment] 2019-11-13 21:56
This is already fixed in the latest Next.js `canary` version -- please upgrade.

**Closed** 2019-11-13 21:57 UTC

**Comment by snaerth** [comment] 2019-11-14 08:47
@Timer Yes this specific error only happens on development, but I get an Internal server error in production, but I should get 404 page. Also when I am running next.js with an express server this error prompts when I navigate to /static/anything

![image](https://user-images.githubusercontent.com/8678089/68840841-64527d00-06bb-11ea-85c2-06a052475f66.png)

**Comment by balazsorban44** [comment] 2022-01-30 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
