### ISSUE TITLE
Animation enhancement

### ISSUE THREAD

**Issue by atwaves** [zeit/next.js#1230] opened 2017-02-21 13:45 UTC
Now if using "/components/layout", layout component is unmounting and animations don't work

layout.render:

```
const { pathname } = this.props.url
let key = pathname.split('/')[ 1 ] || 'root'

return (
<TransitionGroup>
   { React.cloneElement( this.props.children, { key: key } ) }
</TransitionGroup>
)
```
sorry for my bad english
need to implement transitions
![req](https://cloud.githubusercontent.com/assets/9660479/23167347/1fa51e8c-f855-11e6-82c7-e8a4d3dc7852.jpg)

**Comment by timneutkens** [comment] 2017-02-21 21:38
Seems like a duplicate of https://github.com/zeit/next.js/issues/88. Could you verify this and move your feedback there? Much appreciated ❤️

**Comment by arunoda** [comment] 2017-02-21 23:20
Yes. This is related to #88.
This is a valid issue. Have a look at the #88 for more info and workarounds.

My comment: https://github.com/zeit/next.js/issues/88#issuecomment-273582899

**Closed by arunoda** 2017-02-21 23:20 UTC
