### ISSUE TITLE
`getServerProps` does not work with native Node.js modules (`fs`, `child_process`...)

### ISSUE THREAD

**Issue by timsuchanek** [zeit/next.js#11950] opened 2020-04-16 13:55 UTC
# Bug report

## Describe the bug

In a `getServerProps` handler, I would like to use `fs`. However, I get this error:
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '/Users/tim/code/repros/next-child-process/src'
    at /Users/tim/code/repros/next-child-process/node_modules/webpack/lib/Compilation.js:925:10
    at /Users/tim/code/repros/next-child-process/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /Users/tim/code/repros/next-child-process/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /Users/tim/code/repros/next-child-process/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /Users/tim/code/repros/next-child-process/node_modules/neo-async/async.js:2830:7
    at /Users/tim/code/repros/next-child-process/node_modules/neo-async/async.js:6877:13
    at /Users/tim/code/repros/next-child-process/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /Users/tim/code/repros/next-child-process/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /Users/tim/code/repros/next-child-process/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/tim/code/repros/next-child-process/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /Users/tim/code/repros/next-child-process/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /Users/tim/code/repros/next-child-process/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/tim/code/repros/next-child-process/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /Users/tim/code/repros/next-child-process/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/tim/code/repros/next-child-process/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /Users/tim/code/repros/next-child-process/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
```
I get the same error when importing something from `child_process`.

## To Reproduce

Full reproduction here:
https://github.com/timsuchanek/next-child-process

## System information

- OS: MacOS, but also Linux in Now
- Version of Next.js: 9.3.5
- Version of Node.js: 12

**Comment by timneutkens** [comment] 2020-04-16 14:17
You have a typo in your application. It's not `getServerProps` but `getServerSideProps`.

**Comment by smakosh** [comment] 2020-04-16 15:46
This works fine with a postgres database but not with a SQLite database, I assume because lambda functions are stateless

**Comment by couetilc** [comment] 2020-04-17 00:02
You can use server-side packages in `getServerSideProps` by wrapping the code block in the following if statement.

```js
export default getServerSideProps(ctx) {
  if (typeof window === "undefined") {
    // place server code here
    const fs = await import('fs').default;
    // fs...
  }
}
```

**Comment by Timer** [comment] 2020-04-17 00:11
@couetilc that is not accurate or suggested. The imports should be made top level!

**Comment by Timer** [comment] 2020-04-17 00:12
Closing due to typo in code. Please use `getServerSideProps`!

Demo:
https://next-code-elimination.now.sh/s/do-SLaChg

**Closed by Timer** 2020-04-17 00:12 UTC

**Comment by timsuchanek** [comment] 2020-04-17 06:10
Thanks! It was indeed a typo.

**Comment by balazsorban44** [comment] 2022-01-30 07:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
