### ISSUE TITLE
URL resolving different between server and dev-server

### ISSUE THREAD

**Issue by santialbo** [zeit/next.js#8135] opened 2019-07-27 12:29 UTC
# Bug report

## Describe the bug
When using `experimental.publicDirectory` and dynamic routing with the following setup

```
/pages
  [slug].js
/public
  robots.txt
```
If you hit `/robots.txt`:

- On dev server it resolves to the [slug].js page
- On build server it resolves to the robots.txt file

## To Reproduce

Described above

## Expected behavior

I would expect dev-server to also resolve that route to the robots.txt file.

## System information

- OS: macOS
- Version of Next.js: 9.0.2

**Comment by timneutkens** [comment] 2019-07-27 12:32
Duplicate of #8008

**Closed by timneutkens** 2019-07-27 12:32 UTC

**Comment by balazsorban44** [comment] 2022-01-31 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
