### ISSUE TITLE
React invalid hook call (local linking)

### ISSUE THREAD

**Issue by josias-r** [zeit/next.js#12142] opened 2020-04-23 16:30 UTC
There is this [known bug](https://github.com/facebook/react/issues/13991) w/ React and Webpack which causes an invalid hook call error when two versions of React are present, which can happen when you locally link them for example with `npm link`.

I have the same problem w/ NextJS now and a locally linked package. There is actually a workaround, which is adding a Webpack alias for react, react-dom and react-dom-router. So I thought this bug wouldn't be a problem since I can apply that workaround inside my next.config.js file.

I was wrong. Adding the following lines did actually resolve the `next build` errors, but during development usage with `next`, I still have the Invalid hook calls errors.
```
webpack(config, { defaultLoaders, dev }) {
      // enable local dev
      config.resolve.alias["react"] = join(__dirname, "node_modules/react");
      config.resolve.alias["react-router"] = join( __dirname, "node_modules/react-router");
      config.resolve.alias["react-router-dom"] = join(__dirname, "node_modules/react-router-dom");
      return config;
}
```

Do I have to set the alias somewhere else for development?

**Comment by josias-r** [comment] 2020-04-23 17:35
I have now found a very hacky workaround (in the comment of the linked issue), which is the following:

In my "library-package" I run `npm link ../path/to/my/nextjs-project/node_modules/react`. Before linking it with `npm link` and then `npm link library-package` inside my "nextjs-project"

**Comment by jamesmosier** [comment] 2020-04-23 18:36
Do either of these issues that seem to be related help at all?

https://github.com/zeit/next.js/issues/9022
https://github.com/zeit/next.js/issues/11363

**Comment by timneutkens** [comment] 2020-04-24 09:19
Looks like a duplicate of #9022 indeed.

**Closed by timneutkens** 2020-04-24 09:19 UTC

**Comment by balazsorban44** [comment] 2022-01-30 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
