### ISSUE TITLE
Setting fallback to true errors build

### ISSUE THREAD

**Issue by FrancoTanzarella** [zeit/next.js#12846] opened 2020-05-13 18:12 UTC
# Bug report

## Describe the bug

Just updated to 9.4 to use getStaticPaths and getStaticProps because I'm trying to get around this issue [#3294 ](https://github.com/zeit/now/issues/3294) but now I get the following errors when I do yarn build.

 `Error occurred prerendering page "/blog/post/[id]". Read more: https://err.sh/next.js/prerender-error:TypeError: Cannot read property '0' of undefined`

Setting fallback to false gives me no build errors.

```
const Post = ({posts}) => {
    const post = posts[0];
    const router = useRouter();

    if(router.isFallback) {
        return (
            <Layout>
                <CenterContent>
                    Loading ...
                </CenterContent>
                <Footer />
            </Layout>
        )
    } 

    return (
            <Layout>
                <CenterContent>
                    <article>
                        <Header>
                            <h1>{post.title.rendered}</h1>
                        </Header>
                        {post.better_featured_image
                            ?   <Figure>
                                    <ImageResponsive {...post.better_featured_image} />
                                </Figure>
                            :   null}

                        <Main dangerouslySetInnerHTML={{__html: post.content.rendered}} />
                        
                    </article>
                </CenterContent>
                <Footer />
            </Layout>
    );
}

export async function getStaticPaths() {
    const res = await fetch(${process.env.blogApiLive}/posts);
    const posts = await res.json();
    const paths = posts.map(post => /blog/post/${post.slug});
    
    return { paths, fallback: true }
}

export async function getStaticProps(context) {
    const res = await fetch(${process.env.blogApiLive}/posts?slug=${context.params.id});
    const posts = await res.json();

    return { props: {posts} }
}
```

Am I missing something?

On a side note, in this release, fetch is now included but when I run yarn build without something like node-fetch or isomorphic-unfetch I get this error

`ReferenceError: fetch is not defined
    at getStaticPaths (C:\projects\originnext\.next\server\static\DuTV4FL6_E6-lnBspZfBz\pages\blog\post\[id].js:2790:15`

So it seems like a package to do fetch is still required?
## System information

- OS: [Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 9.4.0]
- Version of Node.js: [e.g. 10.16.3]

**Comment by Timer** [comment] 2020-05-13 19:08
You're accessing a post before checking if you need to render the fallback:
```
const post = posts[0];
```

Move this code to after the if branch.

Also, that `fetch` bug was fixed on the latest `next@canary` version.

**Closed by Timer** 2020-05-13 19:08 UTC

**Comment by brisa-pedronetto** [comment] 2020-09-07 21:23
@Timer Hey Joe, I think you pointed out the correct answer to the problem. Nevertheless, Im wondering if Next is trying to render a page that doesn't even exist during build ("/blog/post/[id]")?

The getStaticPaths is rightly defining all possible paths at this point, but at build time there's this weird path ("/blog/post/[id]") that suffers a render attempt, breaking the build process.

This means that, in order to skip that attempt, we'd need to check if the props are ok, even though we *know* the props are ok for the paths we listed in getStaticPaths.

Just wondering if you have any thoughts on this or if that's just how things are for the time being. Thanks!

**Comment by Joshanity17** [comment] 2020-10-16 14:30
> @Timer Hey Joe, I think you pointed out the correct answer to the problem. Nevertheless, Im wondering if Next is trying to render a page that doesn't even exist during build ("/blog/post/[id]")?
> 
> The getStaticPaths is rightly defining all possible paths at this point, but at build time there's this weird path ("/blog/post/[id]") that suffers a render attempt, breaking the build process.
> 
> This means that, in order to skip that attempt, we'd need to check if the props are ok, even though we _know_ the props are ok for the paths we listed in getStaticPaths.
> 
> Just wondering if you have any thoughts on this or if that's just how things are for the time being. Thanks!

I am experiencing this issue right now. What would be the solution for this?

**Comment by ryanditjia** [comment] 2020-10-18 05:55
@Joshanity17 I ran into the same issue and was able to fix it with a one-liner:

```
// setup
export async function getStaticProps(context) {
  const data = await ...

  return {
    props: {
      data
    }
  }
}

// the page component
export default function MyPage({ data }) {
  if (!data) return null // this is the one-liner check

  // rest of actual component code
}
```

**Comment by Joshanity17** [comment] 2020-11-14 15:36
> @Joshanity17 I ran into the same issue and was able to fix it with a one-liner:
> 
> ```
> // setup
> export async function getStaticProps(context) {
>   const data = await ...
> 
>   return {
>     props: {
>       data
>     }
>   }
> }
> 
> // the page component
> export default function MyPage({ data }) {
>   if (!data) return null // this is the one-liner check
> 
>   // rest of actual component code
> }
> ```

This ones work. But ain't sure what's the catch with this kind of workaround.

**Comment by ryanditjia** [comment] 2020-11-17 12:58
Since the introduction of Next.js v10, I’ve removed the workaround code. `fallback: 'blocking'` works well for me.

**Comment by frames75** [comment] 2021-04-14 11:01
Here same issue with `"next": {"version": "10.0.9"}`, and using `fallback: true`.

`run dev` works ok but `run build` gets this error, trying to prerender page "/foo/[id]".

@ryanditjia solution works, but this issue must be a bug not solved.

**Comment by kikeonline** [comment] 2021-05-01 00:00
For some reason I set `fallback: true` but when I receive the router is always `isFallback: false`.

**Comment by khangahs** [comment] 2021-06-28 16:05
@ryanditjia the solution works for some reasons; however, this is a known bug and should be addressed to the maintainers.

**Comment by tayloraucoin** [comment] 2021-08-17 05:18
The documented example does not work for me. Cannot build after a new path is created. 

`"next": "^10.0.6"`

```
> Build error occurred
Error: Export encountered errors on following paths:
	/shop/e33a18e7-da55-4e6c-b4d9-7720eee9d1e9
```

```
import { useRouter } from "next/router";

const Shop = (props) => {
  const router = useRouter();
  if (router.isFallback) return <div>Loading...</div>;

  return <... />;
};

export async function getStaticPaths() {
  const shopPathsResponse = await queryApollo(QUERY_SHOP_PATHS);
  return {
    fallback: true, // "blocking" also fails with the same error
    paths: shopPathsResponse.data.shops.nodes.map((s) => {
      return {
        params: {
          shop: s.slug,
        },
      };
    }),
  };
}

export async function getStaticProps({ params }) {
  const res = await ...
  return {
    props: {
      res: res?.data?.shopBySlug,
      shop: params?.shop,
    },
    revalidate: 1,
  };
}

export default Shop;

```

**Comment by tayloraucoin** [comment] 2021-08-18 03:21
Figured out my problem. The build error wasn't very descriptive - but if you scroll farther up and look for it you can find a more detailed error. 

Mine was something erring in the page ui for freshly created shops that didn't have all the attributes

**Comment by balazsorban44** [comment] 2022-01-27 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
