### ISSUE TITLE
/pages/one/index.js works, but /pages/one/two/index.js does not

### ISSUE THREAD

**Issue by tashburn** [zeit/next.js#2392] opened 2017-06-28 17:38 UTC
If I have `/pages/one/index.js`, the URL `/one` resolves to the `index.js`. Great.

But if I have `/pages/one/two/index.js`, the URL `/one/two` does _not_ resolve to `index.js`. I get `error: Cannot GET /one/two`. The URL `/one/two/index.js` does not work either, as I'd expect.

I think nesting like this should work.

**Comment by timneutkens** [comment] 2017-06-28 17:43
Duplicate of https://github.com/zeit/next.js/issues/619

**Closed by timneutkens** 2017-06-28 17:43 UTC
