### ISSUE TITLE
custom distDir generates 404 error and hot reload doesn't work properly anymore

### ISSUE THREAD

**Issue by paulbrie** [zeit/next.js#1873] opened 2017-05-04 11:34 UTC
Hi,

If I use a custom distDir:
- the following error appears in the console: `http://myUrl/_next/-/page/_error` / 404 not found
- hot reloading does not work properly anymore

If I go back to the default, it goes away.

my `next.config.js` file:

```
// see source file server/config.js
module.exports = {
  webpack: null,
  poweredByHeader: false,
  distDir: '.build',
  assetPrefix: ''
}
```
Thanks,
Paul

**Comment by ivome** [comment] 2017-05-04 17:49
Duplicate of #1803 ? 
What version are you using? This seems to be working for me on the newly released 2.3.0

**Comment by paulbrie** [comment] 2017-05-04 18:39
Hi, it works well with 2.3.0. I was working with 2.2.0. Thanks!

**Comment by timneutkens** [comment] 2017-05-06 21:41
Closing this 👍

**Closed by timneutkens** 2017-05-06 21:41 UTC
