### ISSUE TITLE
Link's Next.js doesn't work when use Ant Design

### ISSUE THREAD

**Issue by yussenn** [zeit/next.js#9385] opened 2019-11-12 16:13 UTC
# Examples bug report

## Example name

with-ant-design-less
https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less

## Describe the bug

When I click on a Link to a page that uses any antd component, it doesn't work and when I click on a Link to a page that doesn't use any antd component, it works.

## To Reproduce

I create a codesandbox to reproduce te bug https://codesandbox.io/s/nextjs-ant-design-8t41c
 - Click on "Go to page with antd" doesn't work
 - Click on "Go to page without antd"  works

## Expected behavior

The Link redirect to page that uses antd

## System information

Dependencies: 
    "@zeit/next-less": "1.0.1",
    "antd": "3.25.1",
    "babel-plugin-import": "1.12.2",
    "less": "3.10.3",
    "less-vars-to-js": "1.3.0",
    "next": "latest",
    "null-loader": "3.0.0",
    "react": "^16.7.0",
    "react-dom": "^16.7.0"

**Comment by ijjk** [comment] 2019-11-13 02:43
Hi, this is appears to be a duplicate of https://github.com/zeit/next-plugins/issues/282. We are looking into fixing this and opened a RFC [here](https://github.com/zeit/next.js/issues/8626)

**Closed by ijjk** 2019-11-13 02:43 UTC

**Comment by geocine** [comment] 2019-11-13 08:47
I also experience this issue

**Comment by balazsorban44** [comment] 2022-01-30 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
