### ISSUE TITLE
API Routes not ready when fetching data from getInitialProps

### ISSUE THREAD

**Issue by torresandres** [zeit/next.js#8160] opened 2019-07-29 15:49 UTC
I'm working on a webapp that fetchs data from our API. On my `pages/index.js` I'm fetching some shipments data on the `getInitialProps`, the usual thing, right?

I've started working on a second page and I need the same data so I thought about API routes to have more control on the front end and normalize some data. My API route looks like this:

`/pages/api/shipments.js`
```
import Axios from 'axios'; 

export default async (req, res) => {
  let shipments = [];

  await Axios.get('*******')
    .then(response => shipments = response.data.shipments)
    .catch(err => console.log);

  res.json({ shipments });
}
```
Now, this works just fine when accessing it from `http://localhost:3000/api/shipments` but  when the `/api/shipment` is inside of a page's `getInitialProps` method it trhows the following:
```connect ECONNREFUSED 127.0.0.1:80 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)```

`pages/index.js`
```
import Axios from 'axios';

const Homepage extends React.Component {
  static async getInitialProps() {
    let shipments = [];

    await Axios.get('/api/shipments').then(response => {
      console.log(response);
    });

    return {
      shiptments
    }
  }

  // ...
}
```

Now, if I move the fetch call into `componentWillMount` it doesn't work neither, but it works on the `componentDidMount` method.

It seems that API routes are only available once the app is mounted but not before, so server side funcionality like pages' getInitialProps methods are affected.

As a developer I expect (if possible) API routes to be binded/mounted before the pages so the latter can fetch data from the server side of the app. If not, I'm forced to call our external API on getInitialProps and this API routes only when the page is mounted.

I'm using Next.js version 9.0.2.

Thanks in advance,

**Comment by djsilcock** [comment] 2019-07-29 19:14
Is this on server side? It looks like you are serving your app on `127.0.0.1:3000` but your serverside getInitialProps is trying to access `127.0.0.1:80/api/...`
You could try

    import Axios from 'axios';

    const Homepage extends React.Component {
      static async getInitialProps(ctx) {
        let shipments = [];
        const axioscfg=ctx.req?{baseURL:'http://localhost:3000'}:{}
        await Axios.get('/api/shipments',axioscfg).then(response => {
          console.log(response);
        });

        return {
          shiptments
        }
      }

  // ...
}

**Comment by torresandres** [comment] 2019-07-29 19:39
@djsilcock You're right, I understand now why it breaks, and I can workaround this issue for now so thank you.

However, I still believe both Next.js features **page's getInitialProps** and **API routes** should get along right off the bat, because this removes the ease of this two amazing features. Do you think is possible to have api routes ready before actual pages so the latter can consume them?

**Comment by timneutkens** [comment] 2019-07-30 13:04
> Do you think is possible to have api routes ready before actual pages so the latter can consume them?

The API routes are available immediately when you boot up the server. The problem you're having particular is that your fetching library makes the assumption that the server is going to run on port 80. Hence why you have to adjust the base url.

I'm going to close this issue as it is a question and ignores the issue template. The issue template clearly says questions should be posted on https://spectrum.chat/next-js.

**Closed by timneutkens** 2019-07-30 13:04 UTC

**Comment by balazsorban44** [comment] 2022-01-31 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
