### ISSUE TITLE
CSS chunks are served with max-age=0

### ISSUE THREAD

**Issue by znarf** [zeit/next.js#10182] opened 2020-01-21 11:17 UTC
# Bug report

When using the new integrated CSS support in `9.2.0`, CSS chunks are served with `max-age=0` in the `Cache-Control` header.

## To Reproduce

- Create a global CSS: `_app.css`: `body { background-color: red }`
- Link CSS in `_app.js`: `import './_app.css'` 
- Build the app: `npm run build`
- Start the app in production environment: `npm run start`
- Inspect the `Cache-Control` header of the CSS chunk being served

## Current behavior 

```public, max-age=0```

## Expected Behavior

```public, max-age=31536000, immutable```

## System information

- Version of Next.js:  9.2.0

## Additional context

It's similar to an issue that was previously raised for the `next-css` plugin: https://github.com/zeit/next.js/issues/5464

**Comment by Timer** [comment] 2020-01-21 12:52
Fixed via #10184

**Closed** 2020-01-21 13:19 UTC
Labels: Type: Bug

**Comment by balazsorban44** [comment] 2022-01-30 15:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
