### ISSUE TITLE
 Login through getInitialProps, how to set the session?

### ISSUE THREAD

**Issue by devmsg** [zeit/next.js#4241] opened 2018-05-01 11:18 UTC
eg
![image](https://user-images.githubusercontent.com/15261658/39471095-e07f6814-4d73-11e8-9a11-145103755637.png)
![image](https://user-images.githubusercontent.com/15261658/39471098-e4ce5588-4d73-11e8-905a-f5e7363f1af0.png)
![image](https://user-images.githubusercontent.com/15261658/39471124-fdff5a3e-4d73-11e8-926b-9a733926a656.png)

work process：
client ->  node ->  server api

**Comment by mellet** [comment] 2018-05-01 13:26
Take a look at [with-firebase-auth](https://github.com/zeit/next.js/tree/canary/examples/with-firebase-authentication)

If you look at the [server file](https://github.com/zeit/next.js/blob/canary/examples/with-firebase-authentication/server.js), you can see the `/api/login` that it injects the session into the `req`.
You can then get it in get initial props from `ctx.req.session`.

**Example flow:**
- Login Page: User writes in username/password, you do a axios post request to /api/login with the payload.
- `/api/login`: Performs user validation, creates a cookie and injects it into the `req` objects and does a `res.redirect` to your profile page.

You could then create a `HOC` that does something like this:
```javascript
export function withAuth(Component) {
  return class extends React.Component {
    static async getInitialProps(ctx) {
       const user = ctx.cookie ? ctx.cookie : //get client side cookie (jscookie)
       return user
    }

    componentWillMount(){
      // If your using redux / mobx, this is usuaully where I add the user into the store
      const { user, store } = this.props
      store.signedInUser(user)
    }
    ...
  }
```

**Comment by timneutkens** [comment] 2018-05-01 14:52
Please follow the issue template 🙏, also there's already an issue about authentication 👍 

Duplicate of #153

**Closed by timneutkens** 2018-05-01 14:52 UTC

**Comment by iamgreyy** [comment] 2018-12-14 10:51
> Take a look at [with-firebase-auth](https://github.com/zeit/next.js/tree/canary/examples/with-firebase-authentication)
> 
> If you look at the [server file](https://github.com/zeit/next.js/blob/canary/examples/with-firebase-authentication/server.js), you can see the `/api/login` that it injects the session into the `req`.
> You can then get it in get initial props from `ctx.req.session`.
> 
> **Example flow:**
> 
> * Login Page: User writes in username/password, you do a axios post request to /api/login with the payload.
> * `/api/login`: Performs user validation, creates a cookie and injects it into the `req` objects and does a `res.redirect` to your profile page.
> 
> You could then create a `HOC` that does something like this:
> 
> ```js
> export function withAuth(Component) {
>   return class extends React.Component {
>     static async getInitialProps(ctx) {
>        const user = ctx.cookie ? ctx.cookie : //get client side cookie (jscookie)
>        return user
>     }
> 
>     componentWillMount(){
>       // If your using redux / mobx, this is usuaully where I add the user into the store
>       const { user, store } = this.props
>       store.signedInUser(user)
>     }
>     ...
>   }
> ```

u forgot to await WrappedComponent getInitialProps

**Comment by nitin-malhotra** [comment] 2019-04-12 12:22
Hi all i was finding the answer for this issue and my code successfully works using this
```
  static async getInitialProps(ctx) {
    
    let url = req ? req.protocol + '://' + req.get('host') : '';
    const res = await fetch(url + '/dashboardData/',{
        headers: {
            cookie: ctx.req ? ctx.req.headers.cookie : null ,
        }
    })
    const json = await res.json()
      if (json && json.error) {
              return { 'error': 'Something went wrong' }

      }
      return {
        data : json.data
      }
      
  }
