### ISSUE TITLE
.babelrc.js Not Compatible with Next 7

### ISSUE THREAD

**Issue by loganwedwards** [zeit/next.js#5503] opened 2018-10-23 00:48 UTC
# Bug report

## Describe the bug

`Components` directory modules not resolving using `babelrc.js`. 

## To Reproduce

Create a `.babelrc.js` file using a custom express server (taken from the docs).
1. Install dependencies (Try on Next 6 first to see it working)
2. Start the server `node server.js`
3. See error

Terminal output:
```bash
These dependencies were not found:

* components/Footer in ./components/Layout.js
* components/Header in ./components/Layout.js

To install them, you can run: npm install --save components/Footer components/Header
server mode = development
> Ready on http://localhost:3000
```

### .babelrc.js
```
const env = require('./env-config')
module.exports = {
  presets: [
    [
      'next/babel',
      {
        'preset-env': {
          targets: {
            browsers: ['IE >= 11', 'cover 99.5%']
          },
          useBuiltIns: 'entry'
        }
      }
    ]
  ],
  plugins: [
    [
      'module-resolver',
      { root: ['./'], alias: { components: './components' } }
    ],
    ['transform-define', env],
    ['inline-react-svg'],
    [
      'babel-plugin-styled-components',
      { ssr: true, displayName: true, preprocess: false }
    ],
    ['@babel/plugin-transform-object-assign']
  ]
}
```
### package.json (some pieces omitted for clarity)
```
{
  "dependencies": {
    "@babel/core": "^7.0.0",
    "animejs": "2.2.0",
    "axios": "0.17.1",
    "babel-plugin-module-resolver": "3.1.1",
    "bowser": "^1.9.3",
    "compression": "1.7.2",
    "dotenv": "^5.0.1",
    "es6-promise": "4.2.4",
    "express": "4.16.3",
    "grid-styled": "4.0.0",
    "isomorphic-fetch": "2.2.1",
    "lodash": "^4.17.11",
    "moment": "2.21.0",
    "moment-timezone": "0.5.14",
    "next": "7.0.2",
    "next-redux-wrapper": "1.3.5",
    "path-match": "1.2.4",
    "polished": "1.9.0",
    "prop-types": "15.6.0",
    "react": "16.5.2",
    "react-dom": "16.5.2",
    "react-measure": "2.0.2",
    "react-modal": "^3.4.4",
    "react-redux": "5.0.6",
    "react-resize-detector": "^2.3.0",
    "react-responsive": "^4.0.5",
    "react-responsive-redux": "^0.5.0",
    "react-transition-group": "2.2.1",
    "react-waypoint": "8.0.0",
    "rebass": "^1.0.7",
    "redux": "3.7.2",
    "redux-thunk": "2.2.0",
    "styled-components": "3.2.6"
  },
  "devDependencies": {
    "@babel/cli": "^7.0.0",
    "@babel/core": "7.1.2",
    "@babel/plugin-transform-object-assign": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.4",
    "babel-plugin-inline-react-svg": "1.0.1",
    "babel-plugin-styled-components": "^1.8.0",
    "babel-plugin-transform-define": "^1.3.0",
    "eslint": "^5.7.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-config-standard-react": "^7.0.2",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-node": "^7.0.1",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-react": "^7.11.1",
    "eslint-plugin-standard": "^4.0.0",
    "husky": "^0.14.3",
    "lint-staged": "^6.0.0",
    "redux-devtools-extension": "^2.13.2",
    "rimraf": "^2.6.2",
    "standard": "^12.0.1"
  },
  "scripts": {
    "precommit": "lint-staged",
    "lint": "npx eslint .",
    "lint:fix": "npx eslint . --fix",
    "test": "npx eslint .",
    "dev": "rimraf node_modules/.cache/babel-loader && node server.js",
    "build": "export NODE_ENV=production && rimraf node_modules/.cache/babel-loader && next build",
    "start": "export NODE_ENV=production && node server.js"
  },
  "lint-staged": {
    "*.{js,jsx,css,md}": [
      "npm run lint:fix",
      "git add"
    ]
  },
}
```

## Expected behavior
Up through Next `6.x`, a `.babelrc.js` file is used to extend Babel functionality for Next build an runtime steps. There is no documentation indicating that this file type is deprecated. However, the Next docs do mention compatibility with Babel 7's new `babel.config.js`. I expected the upgrade to work as before.

## System information
 - OS: [macOS]
 - Version of Next.js: [7.0.2]
- All presets/plugin for Babel should be 7.x compatible

## Additional context

I also noticed some vague build issues with `build-manifest.json`, but other threads indicated that this logged output is sort of a red herring and that this issue would resolve when the underlying problems were addressed. In my case, I found this to be consistent with others' experiences.

**Comment by Yzrsah** [comment] 2019-02-24 05:18
This is not a problem with Next.js

.babelrc.js and babel-plugin-module-resolver both work reliably with Next

Remove all of the stuff from your setup and test with those two pieces only, and you will see that it works.

You should close the issue

**Comment by Yzrsah** [comment] 2019-02-24 05:25
.babelrc.js + babel-plugin-module-resolver has been tested and works reliably with Next.js

- Create a new Next.js example
- Add .babelrc.js
- Add `[ 'module-resolver', { root: ['./'], alias: { components: './components' } } ]` to .babelrs.js plugins

# Outcome:
*Works reliably*

@loganwedwards Remove all of the stuff from your setup and test with those two pieces only, and you will be successful

@timneutkens the issue is closable

**Comment by Yzrsah** [comment] 2019-02-24 05:27
.babelrc.js + babel-plugin-module-resolver has been tested and works reliably with Next.js

- Create a new Next.js example
- Add .babelrc.js
- Add `[ 'module-resolver', { root: ['./'], alias: { components: './components' } } ]` to .babelrc.js plugins

## Outcome:
*Works reliably*


@loganwedwards Remove all of the stuff from your setup and test with those two pieces only, and you will be successful

@timneutkens the issue is closable

**Comment by timneutkens** [comment] 2019-02-24 12:40
Thanks @Yzrsah!

**Closed by timneutkens** 2019-02-24 12:40 UTC
Labels: Type: Needs Investigation
