### ISSUE TITLE
Warning: the 'url' property is deprecated. https://err.sh/next.js/url-deprecated, why this warning will occur

### ISSUE THREAD

**Issue by hopperhuang** [zeit/next.js#4504] opened 2018-05-31 06:35 UTC
# Question about Next.js

i am curious about why this warning will occur. now i am using next.js 6.0.0 to develop my client side app. i have never use the 'url' property in my page-level component, for my page -level component is generated by an hoc -- withDvaReduxHoc. never have i used the 'url' properiy, but dispear to me, i think is unreasonable for i have never use the feature my cause warning.

or other props have use the 'url'  property, when i get that props ? i have use pathname and query in my apps, but i use these props in getInitialProps life-cycle method, not the render method,  will these properites cause an warning ? and these props will be deprecated in the future ? if not, i couldn't find out what cause this warning.

can u explain these to me?

**Comment by timneutkens** [comment] 2018-05-31 10:00
Duplicate of #4284

**Closed by timneutkens** 2018-05-31 10:00 UTC
