### ISSUE TITLE
Upgrade 'chokidar' dependency to v3

### ISSUE THREAD

**Issue by dacarley** [zeit/next.js#12857] opened 2020-05-14 05:22 UTC
# Bug report

## Describe the bug

When installing `next`, yarn provides a warning about the `chokidar` dependency:

`warning next > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `yarn add next`
2. See error

## Expected behavior

No warning

**Comment by timneutkens** [comment] 2020-05-14 18:48
Will highly depend on shipping this: https://github.com/webpack/watchpack/issues/130

**Comment by paulmillr** [comment] 2020-05-15 19:38
note that some folks can't get their work done with webpack 5 which has a brand-new and not too stable file watcher

>I've been absolutely struggling to get webpack watching on v5 working with a not-too-complex React/Redux app within Docker. It works totally fine on my Linux host, but once it's in a Docker container, it's like flipping a coin to see whether or not events get properly propagated. I'm going to drop a more robust repro case in the Webpack 5 beta thread, but it's worth noting here that I'm concerned about moving to 5 just because of Watchpack 2 alone.

**Comment by timneutkens** [comment] 2020-05-25 12:21
Closing this as part of https://github.com/zeit/next.js/issues/13341

**Closed by timneutkens** 2020-05-25 12:21 UTC

**Comment by balazsorban44** [comment] 2022-01-30 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
