### ISSUE TITLE
_error.jsx statusCode returns undefined if page not found

### ISSUE THREAD

**Issue by KonradLinkowski** [zeit/next.js#8136] opened 2019-07-27 14:36 UTC
# Bug report

## Describe the bug

_error.jsx statusCode returns undefined if page not found

## To Reproduce

https://github.com/ritz078/transform/blob/master/pages/_error.tsx

## Expected behavior

statusCode should be set to 404

## System information

- Windows 10
- Chrome
- 9.0.2

## Additional context
https://github.com/ritz078/transform/issues/137

**Comment by huv1k** [comment] 2019-07-29 08:06
Hey @KonradLinkowski, your `_app.tsx` needs to extend `next/app`, otherwise it's going to be just functional component and it isn't going to handle request properly.

**Comment by huv1k** [comment] 2019-07-29 21:13
I am closing this because it's not a problem with next.

**Closed by huv1k** 2019-07-29 21:13 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
