### ISSUE TITLE
Local (start dev) problem with Routing in official Getting Started project.

### ISSUE THREAD

**Issue by kegriz** [zeit/next.js#5524] opened 2018-10-25 14:24 UTC
# Bug report

## Describe the bug

When I add for example 5 files in "pages" folder, and add classic "Link" routing - it works until I do 1-2 minutes break. After 2 minutes when I try to use site there work only 2 routes - rest don't react. Hot reload still works fine, everything works good except this routing. (hrefs with reload works good - only SPA style routing breaking after 2 minutes awaiting.

## To Reproduce

1. Download my repo from: [https://github.com/kegriz/next-routing-issue](https://github.com/kegriz/next-routing-issue)
2. install packages: yarn (or nmp install)
3. start dev project: yarn run dev (or npm run dev)
4. open website at http://localhost:3000
5. click on every subpage by links
6. last click on for example "aaa"
7. wait 2 minutes without any activity

## Expected behavior
After this time there should by only 2 links working correctly.

## System information
 - OS: [ MacOS Mojave(10.14) ]
 - Browser [chrome & safari]
 - Version of Next.js: [7.0.2]
- node: v10.11.0
- npm 6.4.1
- tested on 3 computers

## Additional context

-Hot Reload still working.
-Classic (no SPA) link works.

**Comment by insanepl** [comment] 2018-10-26 12:57
I also encountered that bug.

**Comment by malimccalla** [comment] 2018-11-05 08:33
Got this happening too. It may be related to #5478

**Comment by timneutkens** [comment] 2018-12-31 13:01
Going to close this as duplicate of #5598

**Closed by timneutkens** 2018-12-31 13:01 UTC
Labels: Type: Needs Investigation
