### ISSUE TITLE
nextjs [production static] click link throw error but  press F5 _app reloaded

### ISSUE THREAD

**Issue by shipcake** [zeit/next.js#7419] opened 2019-05-24 11:10 UTC
hi. I record the gif video please help me
https://i.ibb.co/N3T0L2C/nextjserror.gif

import Link from 'next/link'

**Comment by ijjk** [comment] 2019-05-24 15:12
Hi, can you show the errors you're getting in the console tab?

**Comment by ijjk** [comment] 2019-05-24 15:20
Closing in favor of [spectrum thread](https://spectrum.chat/next-js/general/production-help-me-next-link-not-work-in-some-page-i-must-refresh-this-page~6f1a3b93-238a-4423-b261-807a261ffda6)

**Closed by ijjk** 2019-05-24 15:20 UTC

**Comment by balazsorban44** [comment] 2022-01-31 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
