### ISSUE TITLE
Custom fonts are incorrectly deleted by dev server in Next 9

### ISSUE THREAD

**Issue by ElizurHz** [zeit/next.js#8618] opened 2019-09-04 08:32 UTC
# Bug report

## Describe the bug

I have several local custom fonts by using `@font-face` in css. When I use a custom server like [custom-server-express](https://github.com/zeit/next.js/tree/canary/examples/custom-server-express) locally, the fonts will be packed to `/static/fonts` of my output dir first, and then when I visit any page on localhost, those fonts are removed and I got 404 for those font files.

However, this works fine on Next 8.0.3.

And in next.config.js I use [`next-fonts`](https://www.npmjs.com/package/next-fonts) to parse these font files

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Put any font file in /static folder and import it by @font-face in a css file
`@font-face` example:
```css
@font-face {
  font-family: 'Noto Sans Arabic';
  font-style: normal;
  font-weight: 400;
  src: url(/static/font/NotoSansArabic-Regular.ttf) format('truetype');
}
```
2. Use `next-fonts` in next.config.js, follwing the guide of the package [`next-fonts`](https://www.npmjs.com/package/next-fonts)
```javascript
// next.config.js
const withFonts = require('next-fonts');
module.exports = withFonts();
```
3. Run a dev server locally
4. Visit any page on localhost

## Expected behavior

Fonts should not be deleted incorrectly and can be access by url.

## Screenshots

Got 404 when first loading of the page and requesting fonts, and the fonts and icons(I use icomoon) on the page display incorrectly:
![image](https://user-images.githubusercontent.com/6180013/64237470-007b3d80-cf2f-11e9-875c-f3b603887c1b.png)

Before visiting a page:
![image](https://user-images.githubusercontent.com/6180013/64237050-2ce28a00-cf2e-11e9-94cc-1278d3de588f.png)

After visiting a page (all fonts are deleted):
![image](https://user-images.githubusercontent.com/6180013/64237113-471c6800-cf2e-11e9-8dd1-b46fb9c84cf0.png)

## System information

- OS: macOS 10.14.6 & Win 10
- Browser: Chrome 76.0.3809.132
- Version of Next.js: 9.0.5

**Comment by timneutkens** [comment] 2020-01-02 22:32
Please create a full reproduction including a repository.

**Comment by kszitt** [comment] 2020-01-12 09:23
You can try this
``` jsx
// next.config.js
const withPlugins = require ("next-compose-plugins");
const withFonts = require('next-fonts');
const sass = require("@zeit/next-sass");
const css = require('@zeit/next-css');

const nextConfig = {
  webpack: (config, options) => {
    
    return config;
  }
};

module.exports = withPlugins([
  sass,
  css,
  [withFonts, {
    assetPrefix: 'https://example.com',
  }]
], nextConfig);
```

**Comment by timneutkens** [comment] 2020-03-16 10:44
Going to close this issue as a complete reproduction (including all files not just a config file) was not provided while it was asked for.

**Closed by timneutkens** 2020-03-16 10:44 UTC
Labels: Please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-30 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
