### ISSUE TITLE
Different slug names for the same dynamic path

### ISSUE THREAD

**Issue by Alecell** [zeit/next.js#9130] opened 2019-10-18 18:10 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Yes. I have an user case that makes sense have two or more dinamic routes in the same folder.

## A clear and concise description of what you want and what your use case is.

When we use dynamic routes we cant use different slug names for the same dynamic path as it throws the error ` 'You cannot use different slug names for the same dynamic path.'`.

Example:
This works:
![image](https://user-images.githubusercontent.com/13935760/67116253-702f4a00-f1b6-11e9-88a6-06e81d2223ea.png)

This dont (throws the error on `yarn dev`):
![image](https://user-images.githubusercontent.com/13935760/67116324-9228cc80-f1b6-11e9-9415-158c104807f4.png)

* The difference between both is that on second example I have 2 dinamic paths inside [city] ([valuezone] and [neighborhood]) and on first I have only [valuezone].

The point is that the `valuezone` is our bussiness name to a group of `neighborhoods` and we have some neighborhoods under our `valuezone` and some out of it. So, we have 2 types of url.

1) The neighborhood is under a mapped valuezone
`/comprar/[realtyType]/[state]/[city]/[valuezone]/[neighborhood]`

2) The neighborhood wont have a mapped valuezone
`/comprar/[realtyType]/[state]/[city]/[neighborhood]`

To archieve the behavior  I need to add both `[valuezone]` and `[neighborhood]` under `[city]`, but this throws the error I describe above.

## Describe the solution you'd like

It would be awesome if we could use thing like the second image, as we redirect especifying the path and the variables we want, that dont leaves doubts of what path we want to render.

## Describe alternatives you've considered

In my especific case if I just change the order of [neighborhood] and [valuezone] the problem is solved, but this only works because I have only one conditional path, in other user cases I cant see an solution with friendly URL.

**Comment by lfades** [comment] 2019-10-20 01:20
The issue in the second example is that you have 2 dynamic routes in the same level, `[valuezone]` and `[neighborhood]` can't be in the same level, because a dynamic route will always handle all routes that aren't handled by a static page, so if you have 2, it creates a conflict.

If what you want is to handle the following routes:
-  `/comprar/[realtyType]/[state]/[city]/[valuezone]/[neighborhood]`
- `/comprar/[realtyType]/[state]/[city]/[neighborhood]`

You only need to have `[valuezone]` and remove `[neighborhood]`, then `[valuezone]/index.js` will handle the following routes:

-  `/comprar/[realtyType]/[state]/[city]/[valuezone]/[neighborhood]` - Handled by `[valuezone]/[neighborhood]/index.js`
- `/comprar/[realtyType]/[state]/[city]/[valuezone]` - In this case instead of having `[neighborhood]` we have `[valuezone]`, so you can consider `[valuezone]/index.js` to be the `[neighborhood]` page.

I'm closing the issue for now, feel free to continue the conversation.

**Closed by lfades** 2019-10-20 01:20 UTC

**Comment by BramDecuypere** [comment] 2020-03-23 12:27
@lfades And how would you go about this structure. Because I have the feeling I need different routes at the same level. Or I'm missing the point of some specs in Next.js

`/[lang]/[overview]` --> Which will give me an overview of the products with different routes in different languages

`/[lang]/[about]` --> will give me different slugs of the about page. I tried multiple things, but these are easy to happen in bigger application, no?

How would you deal with this situation?

**Comment by carylaw** [comment] 2020-03-27 09:15
@lfades 
how about 

`/creditcard/[token]` POST
`/creditcard/[cardId]` DELETE

using same level but different method?

**Comment by lfades** [comment] 2020-03-27 16:17
@carylaw You can use a single API route and check for the method with a conditional:

```

**Comment by lfades** [comment] 2020-03-27 16:18
@BramDecuypere I currently don't have an answer for your use case, but the team knows about it and we'll be investing into i18n soon :+1:

**Comment by matigda** [comment] 2020-04-24 10:25
@lfades is there any progress on that?

**Comment by matigda** [comment] 2020-04-27 11:46
Also another issue is that if there is something like [productPage].js on root level, then all assets requests ( that are in public directory ) are being redirected there. So all assets return 404. 

Is there any topic where I can put those things? :)

**Comment by flybayer** [comment] 2020-05-18 15:02
This is a very significant limitation.

We're trying to use a restful style page structure as shown below, but this fails.

```
└── projects
    ├── [id]
    │   └── edit.tsx
    ├── [id].tsx
    ├── [projectId]
    │   └── tasks
    │       ├── [id]
    │       │   └── edit.tsx
    │       ├── [id].tsx
    │       ├── index.tsx
    │       └── new.tsx
    ├── index.tsx
    └── new.tsx
```

Supporting this definitely requires more complexity inside the Next router and a compile step check to ensure duplicate pages don't exist (ex. `projects/[id]/edit` and `projects/[projectId]/edit`). 

But I think it's very worth the effort.

**Comment by advancingu** [comment] 2020-07-08 21:37
> @BramDecuypere I currently don't have an answer for your use case, but the team knows about it and we'll be investing into i18n soon +1

Any news on this? Running into the same issue where route strings need to be localized.

**Comment by BramDecuypere** [comment] 2020-07-09 08:02
> > @BramDecuypere I currently don't have an answer for your use case, but the team knows about it and we'll be investing into i18n soon +1
> 
> Any news on this? Running into the same issue where route strings need to be localized.

We currently decided not to localize our URL's although not perfect, it's not worth for us spending more time on these issues. **What we do now though (for blogs at least), is have them come from our CMS and store the alternate links of the blogs inside the page as well. So we know there is always a link we can refer too.** 

Maybe that might help, we could also do that for the other pages, now that I think of it, but like I said, not worth my time right now. I believe Next is working on a build in solution, so I would hate to spend time working around the issue and then have them release a standardized feature out of the box...

Best of luck anyways!

**Comment by fabb** [comment] 2020-10-08 10:49
> You only need to have `[valuezone]` and remove `[neighborhood]`, then to handle the paths:
> 
> * `/comprar/[realtyType]/[state]/[city]/[valuezone]/[neighborhood]` - Handled by `[valuezone]/[neighborhood]/index.js`
> * `/comprar/[realtyType]/[state]/[city]/[valuezone]` - In this case instead of having `[neighborhood]` we have `[valuezone]`, so you can consider `[valuezone]/index.js` to be the `[neighborhood]` page.

@lfades not possible in my case because I'm mixing SSG and SSR pages:

```
└── pages
    ├── [seopath].tsx (SSR page)
    ├── [type]
    │   └── detailsearch.tsx (SSG page)
```

We currently need to have our own internal dynamic routing solution which we would like to replace with the native next.js one, especially now since 9.5.3 where Links and Router.push correctly resolve native next.js dynamic paths.

**Comment by kylekirkby** [comment] 2020-12-11 11:14
Any update on this? Seems pretty bad that we can't handle localized routes... 
@timneutkens @lfades 

![nextjs-illegalstructure](https://user-images.githubusercontent.com/4564433/101897119-f4eedb80-3ba1-11eb-8198-a81ed379a114.PNG)

Why is this structure not supported? Seems completely logical. Without this, no localized routes??

**Comment by BramDecuypere** [comment] 2021-03-05 14:40
@lfades Just here to let you know we still don't have a solution for this case? Same for a page that only needs to be rendered in one language?

**Comment by vikaskhunteta** [comment] 2021-03-08 07:55
in WordPress both posts and pages execute from same path, for e.g. site.com/page or site.com/post
even archive pages too execute from same path for e.g. site.com/blog which lists all posts or site.com/category which would list all posts of particular category.

I don't want to create different routes or don't want to use query parameters, what I want is when a Link component href attribute has [...post] dynamic route it should call [...post].js file in the root, when href has [...page] dynamic route it must call [...page].js file not [....post].js and same for category route, when Link has [...category] href it should call [...category].js file, does this make sense?

**Comment by vadimcasap** [comment] 2021-09-08 15:04
> in WordPress both posts and pages execute from the same path, for e.g. site.com/page or site.com/post
> even archive pages to execute from the same path for e.g. site.com/blog which lists all posts or site.com/category which would list all posts of a particular category.
> 
> I don't want to create different routes or don't want to use query parameters, what I want is when a Link component href attribute has [...post] dynamic route it should call [...post].js file in the root when href has [...page] dynamic route it must call [...page].js file not [....post].js and same for category route when Link has [...category] href it should call [...category].js file, does this make sense?

So first of all let's take in mind that WordPress routing works/points in the same place (index.php) and also need to take in mind that adding new post or page (which initial was the same) are selected by query to the database, 

So when you have a slug and check to the database into posts table and found it WordPress understands that a post was found and loads the single-post.php overwise if a page with that slug is found then it loads the single-page.php. 

You can use the same logic in your project but for this, you will need to have a single component and to make differentiation by logic, and I guess it's not a good practice to do it in this way.

**Comment by wellitongervickas** [comment] 2021-12-14 02:58
have you tried this approach?
![image](https://user-images.githubusercontent.com/19244632/145924412-0cad7bac-ae86-44d0-9f8c-9b2f52ec5dd1.png)

- pages
-- transactions
---- [...type].ts (will match any route /transactions/**/**/**.....)
---- [uuid].ts (will match only /transactions/uuid)

as we saw below, we can match these values using query params. But taking a look into the documentation, there are many [caveats](https://nextjs.org/docs/routing/dynamic-routes#caveats)

![2021-12-13 23-56-36](https://user-images.githubusercontent.com/19244632/145925060-53137e9c-bb72-4762-9d65-d33b4bccc33d.gif)

**Comment by balazsorban44** [comment] 2022-01-27 03:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
