### ISSUE TITLE
Using callbacks in an API page throws "API resolved without sending a response"

### ISSUE THREAD

**Issue by mattcarlotta** [zeit/next.js#11432] opened 2020-03-28 17:36 UTC
# Bug report

When using middleware callbacks in an API page, the warning: `API resolved without sending a response for /api/signedin, this may result in stalled requests` is thrown despite a response always being returned.

## To Reproduce

Within an API page, add middleware callback functions -- which take some time to resolve -- that wrap the final destination function.

**Reproducible example** (codesandbox is a bit wonky and not show the warning, so it'll require an additional refresh within the `Browser` tab and waiting a few seconds before it displays -- check `Terminal` for warning): 
[![Edit API Callback Warning](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cocky-fire-9tvyj?fontsize=14&hidenavigation=1&theme=dark)

In case of the codesandbox not working, here's a screenshot (this example somewhat mimics [a local repo](https://i.imgur.com/Xm4t78C.png) I'm currently working on, which throws the same warnings):
 ![6MBscsA.png](https://i.imgur.com/6MBscsA.png).

## Expected behavior

Not to throw a warning.

## System information

- OS: Ubuntu 18.04 LTS
- Browser: Chrome
- Version of Next.js: 9.3.2

## Additional context

Wrapping each callback function within a Promise, as mentioned [here](https://github.com/zeit/next.js/issues/10439#issuecomment-583214126), doesn't seem to suppress the warning.

**Comment by lfades** [comment] 2020-03-28 19:17
Known issue, we currently thinking on a solution for this. Closing as duplicated of #10589 and #10777

**Closed by lfades** 2020-03-28 19:17 UTC

**Comment by balazsorban44** [comment] 2022-01-30 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
