### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by Slowlydev** [zeit/next.js#11118] opened 2020-03-16 17:48 UTC
# Bug report

## Description of the Bug

I get the error:
TypeError: Cannot read property 'map' of undefined

but only if i do it in projects/index.js 
when i put it in pages/index.js it works

## To Reproduce

dependencies:
@zeit/next-sass: 1.0.1
framer-motion: 1.9.0 (not in use right now)
isomorphic-unfetch: 3.0.0
next": 9.3.0",
node-sass": 4.13.1
react: 16.13.0
react-dom: ^16.13.0

/pages/index.js:
```js
import Layout from "../components/layout";
import Intro from "../components/landing/intro";
import Projects from "../components/landing/projects";
import About from "../components/landing/about";

const Index = () => (
    <Layout>
        <Intro />
        <Projects />
        <About />
    </Layout>
);

export default Index;
```

../components/landing/projects/index.js
```js
import fetch from "isomorphic-unfetch";

import Card_holder from "../../common/card_holder";
import Card from "../../common/card";

const Projects = props => (
    <div className="projects">
        <h1>Projects</h1>
        <Card_holder>
            {props.projects.map(project => (
                <Card key={project.id} href={project.url_link}>
                    <h2>{project.title}</h2>
                    <p>{project.description}</p>
                    <a href={project.url_link}>
                        <div className="card-url">{project.link}</div>
                    </a>
                </Card>
            ))}
        </Card_holder>
    </div>
);

Projects.getInitialProps = async function () {
    const res = await fetch(
        "https://my-json-server.typicode.com/Slowlydev/slowly-dev-api/projects"
    );
    const data = await res.json();
    return {
        projects: data
    };
};

export default Projects;
```

## Expected behavior

It should display two cards with the information that it got from the api

## System information

- OS: Windows
- Version of Next.js: 6.2.2

**Comment by ijjk** [comment] 2020-03-16 19:11
Hi, `getInitialProps` is only called for page components in your `pages` folder not any component located outside of the `pages` folder. That is why it is working when it's in `pages/index.js` and not working when in your `components` folder. See [here](https://nextjs.org/docs/api-reference/data-fetching/getInitialProps#recommended-use-getstaticprops-or-getserversideprops-instead) for more info about `getInitialProps` in our docs.

I'm going to close this since it doesn't seem to be a bug and is the expected behavior

**Closed by ijjk** 2020-03-16 19:11 UTC

**Comment by Slowlydev** [comment] 2020-03-16 19:49
Okey thx for replying, i managed to make it work now i learned wath props are for :D

**Comment by balazsorban44** [comment] 2022-01-30 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
