### ISSUE TITLE
Serverless Next Canary: Cannot find module .next/dist/bundles/pages/_error

### ISSUE THREAD

**Issue by jgautheron** [zeit/next.js#3559] opened 2018-01-10 15:15 UTC
I'm trying to run the latest version of Next (4.3-canary1 since it fixes an issue with `babel-runtime`) in AWS Lambda using `claudia` for packaging and `express` combined with `aws-serverless-express`.

Once the package deployed, I'm getting an error when querying the proxy API, ex.
`https://xxxxx.execute-api.eu-west-1.amazonaws.com/latest/`

Next drops `Internal Server Error` and in the logs I get the following:
```
{ Error: Cannot find module /var/task/.next/dist/bundles/pages/_error
at _callee$ (/var/task/node_modules/next/dist/server/resolve.js:220:19)
at tryCatch (/var/task/node_modules/regenerator-runtime/runtime.js:62:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/var/task/node_modules/regenerator-runtime/runtime.js:296:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/task/node_modules/regenerator-runtime/runtime.js:114:21)
at step (/var/task/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
at /var/task/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13 code: 'ENOENT' }
```

I pushed a simple project to reproduce that issue easily: https://github.com/jgautheron/next-serverless.

**EDIT**: it seems that this issue is tightly linked to 4.3, it works if I use the 4.2 and make sure that `next/node_modules/babel-runtime` exists.

**Comment by kylealwyn** [comment] 2018-01-11 03:28
related: https://github.com/zeit/next.js/issues/3533

**Comment by timneutkens** [comment] 2018-01-18 15:28
Closing as duplicate of #3533

**Closed by timneutkens** 2018-01-18 15:28 UTC
