### ISSUE TITLE
Newly generated app is failing

### ISSUE THREAD

**Issue by amclin** [zeit/next.js#9114] opened 2019-10-17 17:06 UTC
# Bug report

## Describe the bug
A newly generated app using `create-nextjs-app` fails to run. Libraries are failing to import, resulting in 500 errors.

## To Reproduce
Create a new app using create-nextjs-app. Start the app in dev mode, and attempt to visit the homepage.

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `npx create-nextjs-app`
2. Options:
    * directory "myapp"
    * use yarn or npm, error happens with both
    * use default settings for yarn or npm
    * Do not use "canary" version of Next
3. `cd myapp`
4. `npm run dev`
5. Open http://localhost:3000 in a web browser

## Expected behavior
Default generic Index page shows

## Actual behavior
<img width="616" alt="Screen Shot 2019-10-17 at 11 58 02 AM" src="https://user-images.githubusercontent.com/105728/67030625-68e43f80-f0d5-11e9-91d3-3358f02f9ba8.png">

```
[ error ] ./pages/_app.js
Attempted import error: 'injectGlobal' is not exported from 'styled-components'.
{ Error: Cannot find module '/Users/amclin/git/foo/myapp/.next/build-manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.loadComponents (/Users/amclin/git/foo/myapp/node_modules/next/dist/next-server/server/load-components.js:25:9)
    at DevServer.findPageComponents (/Users/amclin/git/foo/myapp/node_modules/next/dist/next-server/server/next-server.js:335:40)
    at DevServer.renderErrorToHTML (/Users/amclin/git/foo/myapp/node_modules/next/dist/next-server/server/next-server.js:466:35)
    at DevServer.renderErrorToHTML (/Users/amclin/git/foo/myapp/node_modules/next/dist/server/next-dev-server.js:17:802)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module '/Users/amclin/git/foo/myapp/.next/build-manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.loadComponents (/Users/amclin/git/foo/myapp/node_modules/next/dist/next-server/server/load-components.js:25:9)
    at DevServer.findPageComponents (/Users/amclin/git/foo/myapp/node_modules/next/dist/next-server/server/next-server.js:335:40)
    at DevServer.renderErrorToHTML (/Users/amclin/git/foo/myapp/node_modules/next/dist/next-server/server/next-server.js:466:35)
    at DevServer.renderErrorToHTML (/Users/amclin/git/foo/myapp/node_modules/next/dist/server/next-dev-server.js:17:802) code: 'MODULE_NOT_FOUND' }
```

## System information

- OS: OSX Mojave
- Browser (if applies) n/a
- Version of Next.js: 9.1.1

## Additional context
n/a

**Comment by ijjk** [comment] 2019-10-17 17:16
Hi, we don't maintain `create-nextjs-app` and it looks like that package has been deprecated. The one we maintain is `create-next-app`

**Comment by amclin** [comment] 2019-10-17 17:20
I just figured that out. I don't know what `create-nextjs-app` is resolving to, as there is no package with that name on the NPMJS.org registry.

**Comment by ijjk** [comment] 2019-10-17 17:36
It should be resolving to this package https://www.npmjs.com/package/create-nextjs-app I'm gonna close this since it's not really an issue with Next.js itself

**Closed by ijjk** 2019-10-17 17:36 UTC

**Comment by balazsorban44** [comment] 2022-01-31 02:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
