### ISSUE TITLE
Module parse failed: Unexpected token (36:6) You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by waltzaround** [zeit/next.js#7452] opened 2019-05-29 01:16 UTC
# Bug report

## Describe the bug

Next.js fails to compile

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. run `npm run dev` on http://github.com/voluntarily/vly2
2. watch the logs

Logs return
```
[ error ] ./node_modules/next/dist/client/next-dev.js 36:6
Module parse failed: Unexpected token (36:6)
You may need an appropriate loader to handle this file type.
| 
| 
> import('./noop'); // Support EventSource on Internet Explorer 11
| 
| if (!window.EventSource) {
mongodb connected at: mongodb://localhost/vly2
Voluntari.ly running on http://localhost:3122/ Be Awesome
(node:81825) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'issuer' of null
    at findEntryModule (/Users/walt/dev/vly2/node_modules/next/dist/server/hot-reloader.js:60:16)
    at erroredPages (/Users/walt/dev/vly2/node_modules/next/dist/server/hot-reloader.js:68:29)
    at HotReloader.getCompilationErrors (/Users/walt/dev/vly2/node_modules/next/dist/server/hot-reloader.js:308:33)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:81825) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:81825) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:81825) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'issuer' of null
    at findEntryModule (/Users/walt/dev/vly2/node_modules/next/dist/server/hot-reloader.js:60:16)
    at erroredPages (/Users/walt/dev/vly2/node_modules/next/dist/server/hot-reloader.js:68:29)
    at HotReloader.getCompilationErrors (/Users/walt/dev/vly2/node_modules/next/dist/server/hot-reloader.js:308:33)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:81825) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

```
## Expected behavior
I expect the site to render

**Comment by ijjk** [comment] 2019-05-29 02:59
Looks like this is a duplicate of #6240 I'm closing this now, if it doesn't appear to be a duplicate feel free to reply with additional information.

**Closed by ijjk** 2019-05-29 02:59 UTC

**Comment by waltzaround** [comment] 2019-07-18 11:52
All good @ijjk

**Comment by balazsorban44** [comment] 2022-01-31 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
