### ISSUE TITLE
404: page not found error when Deployment on Nginx's reverse proxy

### ISSUE THREAD

**Issue by manishbalyan** [zeit/next.js#2051] opened 2017-05-23 17:22 UTC
hey, i am deploying my nextjs app on nginx  where django is running on nginx. i want my nextjs app to run on **mydomain/something** but its not working giving 404 page not found error whereas when i run it on mydomain/ it work fine.
please suggest something how i can run it. i followed your wiki link but its not working.do i need to change my server.js file which is like this.

`const next = require('next')
const routes = require('./routes')
const app = next()
const handler = routes.getRequestHandler(app)

// Without express.js
const {createServer} = require('http')
app.prepare().then(() => {
  createServer(handler).listen(4000, err => {
    if (err) throw err
    console.log('> Ready on http://192.168.90.12:4000')
  })
})`

**Comment by hchoriq** [comment] 2017-05-23 17:38
What's your nginx directive for /something?

**Comment by timneutkens** [comment] 2017-05-23 18:43
Somewhat a duplicate of https://github.com/zeit/next.js/issues/257, it's not possible at the moment.

**Closed** 2017-05-23 18:43 UTC
