### ISSUE TITLE
Spread syntax is not polyfilled in Edge 18

### ISSUE THREAD

**Issue by ussuritiger** [zeit/next.js#12719] opened 2020-05-11 13:51 UTC
# Bug report

## Describe the bug
Spread syntax is not polyfilled in Edge 18 that results in the error "Expected identifier, string or number".

## System information
- OS: Windows 10
- Browser: Edge 18
- Version of Next.js: 9.3.6
- Version of Node.js: 13

**Comment by timneutkens** [comment] 2020-05-11 17:29
Closing as no reproduction was provided.

**Closed by timneutkens** 2020-05-11 17:29 UTC

**Comment by ussuritiger** [comment] 2020-05-11 18:38
The issue is caused by third party package so not an issue of Next.js.

**Comment by twobit** [comment] 2020-09-29 03:11
@ussuritiger I ran into the same issue, do you remember which dependency was causing the error?

**Comment by ussuritiger** [comment] 2020-10-01 16:25
Hey @twobit, in our case the issue was caused by the @sindresorhus/slugify package which targets Node.js environment.

**Comment by balazsorban44** [comment] 2022-01-29 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
