### ISSUE TITLE
next export issue

### ISSUE THREAD

**Issue by sagargjasani** [zeit/next.js#8261] opened 2019-08-06 14:42 UTC
# next export res.end is not a function

###

**Comment by huv1k** [comment] 2019-08-06 14:54
Hey @sagargjasani, this was fixed in latest canary. Could you try it with the latest canary and see if it fixes your problem?

**Comment by sagargjasani** [comment] 2019-08-07 12:36
sorry... still not working....

###here is error
![image](https://user-images.githubusercontent.com/43398662/62623206-ef460d80-b93d-11e9-9e6a-7079b173f0e1.png)

###here is my package.json
![image](https://user-images.githubusercontent.com/43398662/62623251-08e75500-b93e-11e9-9498-eac7f7845e2a.png)

**Comment by huv1k** [comment] 2019-08-07 13:01
You still don't have the latest canary, to install it: `npm install next@canary`

**Comment by sagargjasani** [comment] 2019-08-07 14:24
now it says **API pages are not supported in export
  copying "static build" directory**

![image](https://user-images.githubusercontent.com/43398662/62630715-1a842900-b94d-11e9-95ee-84b65afeff15.png)

**Comment by Timer** [comment] 2019-08-07 14:40
This is expected. You cannot "export" a site that has API routes, nor host on Netlify via just `next export`.

Maybe try [deploying with ZEIT Now instead](https://nextjs.org/learn/basics/deploying-a-nextjs-app/deploying-to-zeit-now), since it supports API Routes!

**Closed by Timer** 2019-08-07 14:40 UTC

**Comment by balazsorban44** [comment] 2022-01-31 09:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
