### ISSUE TITLE
Feature request:Nested Routing

### ISSUE THREAD

**Issue by blackraindrop** [zeit/next.js#9340] opened 2019-11-07 16:16 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I'd like to have multiple levels of nested layout.

For example, the following directory structure:

```
+ pages/
  - index.js
  + users
    - index.js
    + [id]
      - posts.js
      - orders.js
  - about.js
```

The home page,users page and about page have the same main layout, and ths user's posts and orders page have the same sub layout.

## Describe the solution you'd like

When there is _layout.js in the directory, a nested route will be generated, with _layout.js as the layout of the directory.

For example, the following directory structure:

```
+ pages/
  - _layout.js
  - index.js
  + users
    - index.js
    + [id]
      - _layout.js
      - posts.js
      - orders.js
  - about.js
```

The layout file returning a React component, and rendering the child components via props.children.It also has static function getInitialProps. The layout and page can load data at the same time when the page loads, 

```
/* _layout.js */

const Layout = (props) => (
    <>
      <Header />
      { props.children }
      <Footer />
    </>
);

Layout.getInitialProps = async (context) => {
  return {}
}

export default Layout
```

**Comment by timneutkens** [comment] 2020-01-03 00:20
Duplicate of #8193

**Closed by timneutkens** 2020-01-03 00:20 UTC

**Comment by balazsorban44** [comment] 2022-01-30 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
