### ISSUE TITLE
The latest version of styled-components throws error

### ISSUE THREAD

**Issue by drejohnson** [zeit/next.js#2304] opened 2017-06-18 17:14 UTC
Using the 'with-styled-components' example and upgrading styled-components to v2.1.0 results in the error: `Unfortunately nesting is not supported by styled-jsx`

**Comment by Sly777** [comment] 2017-06-19 16:07
+1. I cannot use styled-components on my project after upgrade new versions. I added screenshot below.

next.js: **3.0.0-beta16**
styled-components: **2.1.0**
react: **15.6.1**
react-dom: **15.6.1**

![image](https://user-images.githubusercontent.com/694940/27294505-0e629d44-551a-11e7-8a28-4172f2037591.png)

**Comment by drejohnson** [comment] 2017-06-19 16:13
I got it to work by setting `"preprocess": true` in the babel styled-component plugin

```
"plugins": [
    ["styled-components", {
      "ssr": true,
      "displayName": true,
      "preprocess": true
    }]
  ]
```

**Comment by Sly777** [comment] 2017-06-19 23:14
Thanks @drejohnson! It works. But I think there's a conflict between styled-jsx and styled-components (even we disabled styled-jsx) also "preprocess" feature is experimental. That means they can change or remove this feature on future releases.

**Comment by Cinamonas** [comment] 2017-06-20 13:00
@drejohnson, unfortunately, `preprocess` introduces other issues. For example, you can no longer reference other styled components:

```js
const Item = styled.div`
  border: 1px solid black;
`;

const Name = styled.h2`
  font-size: 14px;
  
  ${Item}:hover & {
    text-decoration: underline;
  }
`;
```

**Comment by drejohnson** [comment] 2017-06-20 14:27
@Cinamonas Nice catch! I just reverted back to v2.0.0 for now. I hope this gets resolved soon!

**Comment by markthethomas** [comment] 2017-06-27 13:09
seeing this too, frustrating. Interested in helping find a fix! :)

**Comment by Cinamonas** [comment] 2017-06-28 16:47
Since `styled-components` clashes with `styled-jsx`, I decided to investigate how I can remove the latter from the pipeline. This is how I do it for now:

```js
// babel-preset.js
const preset = require('next/babel');

preset.plugins = removeStyledJsx(preset.plugins);

module.exports = preset;

function removeStyledJsx(plugins) {
  return plugins.filter(plugin => plugin.indexOf('styled-jsx') === -1);
}
```
```js
// .babelrc
{
  "presets": [
    "./babel-preset" // instead of `next/babel`
  ],
  // …
}
```

This fixes the issue and allows removing experimental `preprocess: true` from `babel-plugin-styled-components` options.

**Comment by timneutkens** [comment] 2017-07-02 08:13
Closing this as duplicate of #2384

**Closed by timneutkens** 2017-07-02 08:13 UTC
