### ISSUE TITLE
 Error: Cannot find module 'es-to-primitive/es6'

### ISSUE THREAD

**Issue by IliasHad** [zeit/next.js#7367] opened 2019-05-16 23:33 UTC
# Bug report

## Describe the bug

Cannot find module 'es-to-primitive/es6'

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1: Follow Started Documentation on https://nextjs.org/docs
 1: Npm run dev

[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3000 ...
[ error ] ./node_modules/next-server/dist/lib/router-context.js
Error: Cannot find module 'es-to-primitive/es6'
[ wait ]  compiling ...
[ error ] ./node_modules/next-server/dist/lib/router-context.js
Error: Cannot find module 'es-to-primitive/es6'

## System information
 - OS: Windows 10
 - Browser : Chrome
 - Version of Next.js: 8.1.0

**Comment by timneutkens** [comment] 2019-05-17 08:59
Can you provide a full reproduction? I can't reproduce.

**Comment by IliasHad** [comment] 2019-05-17 13:45
Packages.json
{
  "name": "coding",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "directories": {
    "lib": "lib"
  },
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "next": "^8.1.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  }
}

Pages/index.js

function Home() {
    return <div>Welcome to Next.js!</div>;
  }
  
  export default Home;

**Comment by timneutkens** [comment] 2019-05-18 12:06
I still can't reproduce. Maybe you have a `.babelrc` somewhere up the directory tree.

**Comment by Timer** [comment] 2019-06-14 15:03
Closing as user likely has resolved. If not, please let us know!

**Closed by Timer** 2019-06-14 15:03 UTC
Labels: Can't Reproduce
