### ISSUE TITLE
Next.js should have a better way to measure performance

### ISSUE THREAD

**Issue by housseindjirdeh** [zeit/next.js#8070] opened 2019-07-23 04:59 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

There are a number of user performance metrics that can be used to measure the performance of a site (TTI, FP, FCP, etc...), but they only provide a high-level overview. Including more specific and granular metrics to different parts of Next.js can help:

1. Assess where performance bottlenecks are 
2. Find out how users are actually experiencing Next.js sites in the wild with real user data 

There is also another [open issue](#6242) that covers a similar problem (better logging).

## Describe the solution you'd like

Including some base user metrics to begin withcan be a good start:

* Time it takes for hydrate/render to begin (from page load _or_ link click)
* Hydration/render time

PR #8069 addresses this. By using the User Timing API, we can also surface this information for any public Next.js site through [HTTP Archive](https://httparchive.org).

Moving forward, this can be fine-tuned to better mark idle-times, etc.. through different approaches. We can also expand this to set marks in other points of a rendering lifecycle (such as `getInitialProps`). Hopefully we can also use this issue to further discuss what metrics are missing.

## Describe alternatives you've considered

[next-rum](https://github.com/godaddy/next-rum) is a third party solution that aims to solve a similar problem.

**Comment by Timer** [comment] 2019-08-09 19:50
Resolved in #8069!

**Closed by Timer** 2019-08-09 19:50 UTC

**Comment by balazsorban44** [comment] 2022-01-31 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
