### ISSUE TITLE
Hot reloading of linked modules doesn't work on server

### ISSUE THREAD

**Issue by maerzhase** [zeit/next.js#5463] opened 2018-10-16 15:12 UTC
# Bug report
When working with next and a linked module, the hot reloading doesn't work on the server but only on the client.

## Describe the bug

When you have a linked module inside the `node_modules` folder the module is only replaced on the client but not on the server. This means that you have to restart the whole next application in order to render the updated module on the server.
When the module is a `React.Component` and the output change this even results in inconsistent rendering between server and client shown in a error message in the console.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Setup clean next-js app
2. Link a module via `npm link my-module`
3. Import the module anywhere e.g. `pages/index`
4. Start next-js in dev mode
5. Change your linked module e.g. add `console.log` or if `React.Component` change render method. this will trigger a reload (see terminal)
6. Changes are only visible in the client. server still loads the previous version of the module (probably from cache)

## Expected behavior
The `require.cache` gets cleared properly so the linked module will be re-required also on the server. so client and server stay in sync.

**Comment by maerzhase** [comment] 2018-10-17 09:55
I did some investigation on this bug and I can confirm that the linked modules are still coming from `require.cache`. 

I added the following function to `build/webpack/plugins/nextjs-require-cache-hot-reloader.js`:

```
const deleteMyModule = () => {
  const myModuleIds = Object.keys(require.cache).filter(key => /my-module/.test(key));
  myModuleIds.forEach(id => delete require.cache[id]);
}
```

But this was not enough. Additional to clearing the linked module from `require.cache` you have to delete the page (e.g. `/\.next\/server\/static\/development\/pages\/index.js/`) and the `/\.next\/server\/ssr-module-cache.js/`. 

When this is done it works as expected and the server also reloads the changed module and renders it accordingly. 

I see different solutions to this problem. The question is if you consider that a "bug" in `next-js` and we should find a nice solution on supporting this behavior or we should make a small webpack plugin that solves this problem.

**Comment by timneutkens** [comment] 2018-12-31 12:32
Going to close this in favor of #5638

**Closed by timneutkens** 2018-12-31 12:32 UTC
Labels: Type: Enhancement

**Comment by cherniavskii** [comment] 2019-03-10 11:00
Hi @timneutkens ,

Sorry for commenting on closed issue, but I don't think issue you've linked is relevant here.

The issue @maerzhase described is not related to importing external files from upper folder or even transpiling node_modules.
The issue is that server bundle doesn't rebuild when linked package content has changed.
This results in having outdated package in server bundle and up to date package in client bundle, which makes hard developing linked package.

Would you consider reopening this issue?
I'm working on creating minimal reproduction example.

**Comment by timneutkens** [comment] 2019-03-10 11:27
@cherniavskii what you're explaining seems to be similar to https://github.com/zeit/next.js/issues/5620 🤔

**Comment by cherniavskii** [comment] 2019-03-10 11:32
@timneutkens Thanks for looking into this!
Indeed, it looks similar.
Meanwhile, I've created *minimal* reproduction example here: https://github.com/cherniavskii/nextjs-npm-link-issue

I'll try to apply suggested solution locally and check if it helps

**Comment by cherniavskii** [comment] 2019-03-10 11:41
@timneutkens I've applied fix suggested in https://github.com/zeit/next.js/issues/5620#issuecomment-436734690 to `nextjs-require-cache-hot-reloader.js` in my `node_modules`, then removed `.next` folder.
Nothing changed :/

**Comment by vjpr** [comment] 2019-03-10 13:32
@cherniavskii I had a lot of trouble working with linked modules. A reproduction would help. 

Are you working in a monorepo? Or is this like an `npm link` situation?

I am working on upgrading my monorepo Next project to v8.0.3 right now so am fixing similar issues.

**Comment by maerzhase** [comment] 2019-03-10 13:57
@vjpr the issue I described refered to npm link situations.

**Comment by maerzhase** [comment] 2019-03-10 14:01
@cherniavskii I made a webpack
pluginto temporary solve this problem in the projects i am working on: https://www.npmjs.com/package/webpack-clear-require-cache-plugin

**Comment by cherniavskii** [comment] 2019-03-10 14:30
@vjpr same here, monorepo has nothing to do with this issue

**Comment by cherniavskii** [comment] 2019-03-10 14:47
@maerzhase didn't manage to make this work in my reproducing example - adding plugin has no effect

**Comment by maerzhase** [comment] 2019-03-10 15:04
@cherniavskii did u see the section on how to configure it for next js? i can take a look later, atm i am afk

**Comment by cherniavskii** [comment] 2019-03-10 15:13
@maerzhase yeah, but no success

**Comment by maerzhase** [comment] 2019-03-10 17:56
@cherniavskii I created a fork from your example and added the plugin. take a look:
https://github.com/maerzhase/nextjs-npm-link-issue

**Comment by cherniavskii** [comment] 2019-03-11 08:23
@maerzhase thanks for looking into this!
Did you try to change `package/index.js` file and reload page (without reloading server)?
Because it behaves just like before - server bundle doesn't get updated. See:

![nextjs-npm-link-patch](https://user-images.githubusercontent.com/13808724/54109541-3657c300-43df-11e9-9d19-0c6c99b8ff43.gif)

**Comment by maerzhase** [comment] 2019-03-11 12:24
@cherniavskii hmm jeah thats exactly what i did and to me it solves the problem. now i am super confused why it would only work for me....

![nextjs-reload](https://user-images.githubusercontent.com/1128485/54123812-002b3b00-4401-11e9-951a-b3d4443944c7.gif)
