### ISSUE TITLE
Cannot npm install from github

### ISSUE THREAD

**Issue by matt1as** [zeit/next.js#382] opened 2016-12-12 10:16 UTC
The current version on github version does not install via npm install

    root@2cc7a4204924:/usr/src# npm install git+https://github.com/zeit/next.js

>  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN Bryderi@ No repository field.
> npm WARN Bryderi@ No license field.
> npm ERR! Linux 4.4.27-moby
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "git+https://github.com/zeit/next.js"
> npm ERR! node v7.2.0
> npm ERR! npm  v3.10.9
> npm ERR! path /usr/src/node_modules/next/dist/bin/next
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR! syscall chmod
> 
> npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/src/node_modules/next/dist/bin/next'
> npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/src/node_modules/next/dist/bin/next'
> npm ERR! enoent This is most likely not a problem with npm itself
> npm ERR! enoent and is related to npm not being able to find a file.
> npm ERR! enoent 
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /usr/src/npm-debug.log

**Comment by thisguychris** [comment] 2016-12-13 05:11
@matt1as this is not a bug, the reason why its failing is the compiled version is built and is not included in git, namely `dist` folder.

**Comment by arunoda** [comment] 2016-12-13 06:29
This is a legit usecase, specially when trying out unmerged PRs.
But, this makes code reviewing difficult.

We've two options here:

1. Add the `dist` directory to GIT
2. Write a `postInstall` npm script to build the dist if it's not there.

I think option 2 is a good idea, but we need to deal with some other issues. 

@rauchg @nkzawa What do you guys think?

**Comment by nkzawa** [comment] 2016-12-13 07:41
> Write a postInstall npm script to build the dist if it's not there.

To make this work, you have to install `devDependencies` too, which I think would be troublesome.

I wonder if we can just recommend to use `npm link` to test PRs or the master.
If you'd like to use it in production, you can add `dist` to Git in your forked repository.

**Comment by arunoda** [comment] 2016-12-13 07:51
> To make this work, you have to install devDependencies too, which I think would be troublesome.

Yeah. I got that. It's doable, but it's questionable whether we need to do it or not.

> I wonder if we can just recommend to use npm link to test PRs or the master.
> If you'd like to use it in production, you can add dist to Git in your forked repository.

This is good. We need to add it.

**Comment by thisguychris** [comment] 2016-12-14 10:45
so what the verdict here? just add a readme for npm link? @arunoda / @nkzawa ?

**Comment by aesopwolf** [comment] 2016-12-14 20:21
I'm not sure if `npm link` will work. The next server boots, but then displays the following error on the html page itself:

```
Error in ./pages/index.js?entry
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/aesopwolf/Documents/web-registration/pages"
    at /Users/aesopwolf/Documents/next.js/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/aesopwolf/Documents/next.js/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/Users/aesopwolf/Documents/next.js/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/Users/aesopwolf/Documents/next.js/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/Users/aesopwolf/Documents/next.js/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Users/aesopwolf/Documents/next.js/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/aesopwolf/Documents/next.js/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/aesopwolf/Documents/next.js/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/aesopwolf/Documents/next.js/node_modules/babel-loader/lib/index.js:41:20)
```

I have my project `web-registration` and the `next.js` folder sitting parallel to each other in my Documents folder. Is there a better way to do this? Do I have to put my next.js fork into my project folder itself? That seems kind of weird.

**Comment by matt1as** [comment] 2016-12-15 08:55
If I do `npm link` on my host machine, running osX, everything works fine. If I do `npm link` in my Docker container I get the same behaviour as trying to install from github directly

> root@1294c7041597:/usr/src# git clone https://github.com/zeit/next.js.git
> root@1294c7041597:/usr/src# link next.js
> ...
> ... Lots of packages installing
> ...
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm info build /usr/local/lib/node_modules/next
> npm info linkStuff next@1.2.3
> npm ERR! Linux 4.4.27-moby
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "link" "next.js/"
> npm ERR! node v7.2.0
> npm ERR! npm  v3.10.9
> npm ERR! path /usr/local/lib/node_modules/next/dist/bin/next
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR! syscall chmod
> 
> npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/next/dist/bin/next'
> npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/next/dist/bin/next'
> npm ERR! enoent This is most likely not a problem with npm itself
> npm ERR! enoent and is related to npm not being able to find a file.
> npm ERR! enoent

**Comment by eric-burel** [comment] 2017-01-22 17:45
Hi,

This issue is tricky, because the README on the master introduces interesting functionnalities that do not seem to exist in the lastest stable release.
Therefore the reflex to enjoy them is to track the master branch in npm, and then we obtain this issue with `fsevents`, which is quite unclear. 

In the end, what's the best way to track the master branch ? Could it be documented ?

**Comment by timneutkens** [comment] 2017-01-22 17:48
We're working on master released as `next@beta`. Stable will be 🔜 when all crical bugs have been resolved.

**Comment by eric-burel** [comment] 2017-01-22 18:00
Amazing, thank you! Indeed that's be great to get this documented. I guess many users do not use Next for its stability but indeed want the beta features, at least for now. And this would prevent most people from encountering this issue.

**Comment by timneutkens** [comment] 2017-01-22 18:04
@eric-burel fair point: `*NOTE! the README on the master branch might not match that of the latest stable release! *` doesn't cover `next@beta`

**Comment by timneutkens** [comment] 2017-02-17 12:31
Closing this in favor of #303

**Closed by timneutkens** 2017-02-17 12:31 UTC
Labels: Nice to have
