### ISSUE TITLE
Duplicate meta tags when using Head both in custom document and page

### ISSUE THREAD

**Issue by Manc** [zeit/next.js#9794] opened 2019-12-20 08:46 UTC
# Bug report

**Edit +++ ON HOLD** I just had a lightbulb moment. I will post my discovery/misunderstanding in the next few hours. This ticket can probably be closed then, but I have to test my new theory first…

## Describe the bug

Multiple (duplicate) meta tags such as `charSet` and `viewport` are rendered in `<head>` section of the HTML output when the `<Head>` component is used in both a custom `_document` and a page file.

Even relying on the default injection of `<meta charSet="utf-8"/>` (i.e. not specifying that tag at all) results in having two of the same tags in the output HTML, one from Document and one from the page.

I also end up with two `viewport` meta tags, one from Document and one from the page.

## To Reproduce

I have created (failing) tests here: https://github.com/Manc/next.js/tree/test-head-document

1. Clone repository `git@github.com:Manc/next.js.git`
2. Check out branch `test-head-document`
3. `yarn install`
4. `yarn testonly --testPathPattern "app-document" -t "It dedupes head tags with the same key"`

## Expected behavior

I expect the meta tags with the same `key` to override the meta tags from the custom Document (`_document`).

I expect only to have one `charset` and one `viewport` tag in the whole rendered HTML.

## System information

- OS: macOS
- Version of Next.js: latest or `canary` branch

## Other

I'm pretty new to Next.js and don't really know how it all works yet. I hope the test I provided helps somebody more experienced to fix this or maybe give me a hint. Thanks!

My suspicion is that the `Head` component of the Document (`import { Head } from 'next/document'`) and the `Head` component used in the page (`import Head from 'next/head'`) might be completely separate and don't "communicate" with each other, each doing their own thing twice.

**Comment by xiaokyo** [comment] 2019-12-20 09:07
I had the same problem

**Comment by Manc** [comment] 2019-12-20 12:41
OK, here we go… As suspected earlier I finally worked it out.

Apparently, the correct way of using the two different (!) `Head` components is to prepare the meta tags etc. only in the page component or other components, but **not** in the `_document.js` file. In the `_document` only include it from `next/document` like `<Head />` without any children.

To clarify…

```TypeScript
// pages/_document.tsx

import Document, { Head, Main, NextScript } from 'next/document'; // We import `Head` from `next/document`!

class MyDocument extends Document {
	public render() {
		return (
			<html lang="en">
				<Head /> // Do not add any children here!
				<body>
					<Main />
					<NextScript />
				</body>
			</html>
		);
	}
}

export default MyDocument;
```

```TypeScript
// pages/examplepage.tsx

import React from 'react';
import Head from 'next/head'; // We import `Head` from `next/head `!
import Layout from '../components/layout';

class ExamplePage extends React.Component {
	render() {
		return (
			<Layout>
				<Head>
					<title>Example page</title>
					<meta name="description" content="Example page description" />
				</Head>

				<h1>Example page</h1>
			</Layout>
		);
	}
}

export default ExamplePage;
```

And then in the `Layout` component you can define default meta tags and headers, but not in the `_document` itself.

I was used to the way [react-helmet](https://github.com/nfl/react-helmet) works. There you can set defaults at top level and override/add values in children, but you always use the same component. Here we use two different components with the same name, which, I guess, caused the confusion.

**Comment by gothy** [comment] 2019-12-21 13:54
@Manc why have you closed this issue? It's clearly a bug.

`_document.js` is the place to specify common the defaults for the whole site like charset and viewport.

Not we've them duplicated with "defaults" later. Even using `key` prop like in this test scenario 
https://github.com/zeit/next.js/blob/18a9c7e371efc4c487f9c3599c3211ce30009d6c/test/integration/client-navigation/pages/head-duplicate-default-keys.js

doesn't help. In my case, I've got two viewport tags, first one is mine 

```<meta name="viewport" content="width=device-width, initial-scale=1"/>```

defined in `_document.js` using `next/head` and then the default one later

```<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"/>```

The same with `charSet`. 
Please, reopen this issue, maybe we'll get an explanation.

**Comment by Manc** [comment] 2019-12-21 14:00
@gothy You might be right, it's probably best to get the opinion of the Next.js team, what the intended usage is.

If we are supposed to defined defaults in the `_document.js`, which makes sense, then it looks like a bug indeed. If one is supposed to prepare all the head tags outside `_document.js` (as described in my previous comment), then it should be made clearer and maybe the `Head` component of `next/head` should not even accept children.

**Comment by timneutkens** [comment] 2019-12-22 11:19
`next/head` should be used in _app / pages.

_document is only for the initial document HTML and if you're going to override on the page level it won't work as we simply won't know about it on the client-side as _document is server-side only.

**Comment by gothy** [comment] 2019-12-23 10:00
@timneutkens thanks for clarifying! 

I had the impression, `_document.js` should contain all of the basic\shared\non-dynamic things like charset, viewport, manifest, icons, etc.

If I move the `<meta charSet="utf-8" />` to the `_app.js`, I'm getting 

`Error: A charset attribute on a meta element found after the first 1024 bytes.`

from validator.w3.org . I'm not sure if that's super bad, but it's not clear how can I avoid this without  putting this tag first inside the `_document.js` `<Head>` since there's a huge list of i18n strings is being embedded in `_document.js`. Anything listed in `_app.js` is serialized after initial portion during SSR.

I've seen [this PR](https://github.com/zeit/next.js/pull/9084) on deprecating `next/head`. It would be great if the new take on this static\dynamic head handling will take W3 validation into account.

And  thanks for Next 🚀😀

**Comment by timneutkens** [comment] 2019-12-23 10:53
As said _document is for the initial html, so head elements that never change are fine there. In general you don’t need to add a charset as next comes with UTF-8 by default.

**Comment by gothy** [comment] 2019-12-23 11:05
Yes. The (W3 validator) issue arises only when you've got something big serialized into the head in `_document.js`, since charset meta tag always comes after that.

**Comment by Manc** [comment] 2019-12-23 11:06
My experience was, if I remember correctly now, as soon as I start adding defaults in the _document head, I end up with duplicate meta tags.

@gothy I also wanted to follow the recommendation to set charSet as far at the top as possible. This does not seem to be guaranteed if you rely on Next's defaults.

My solution (workaround?) is, as described above, do not set any defaults in the _document head, only in pages etc. For example, I use a `Layout` component, used by all pages and I set my default meta tags there and override them in individual pages.

**Comment by timneutkens** [comment] 2019-12-23 14:14
@Manc yeah that's correct, defaults in _document is fine, if you want to *override* however you need everything available client-side so that we can actually dedupe and recalculate the items.

**Comment by timneutkens** [comment] 2019-12-23 14:15
I'll close the issue now that it's cleared up.

**Closed by timneutkens** 2019-12-23 14:15 UTC

**Comment by rscharfer** [comment] 2020-03-30 06:46
I think this is still a problem.  We have to have some things in our document.js `<Head>` which will "push down" all other tags in the `<head>`. The result is that the charSet meta is too far down the document according to things like W3 validator.  There is no solution for this currently.

**Comment by nicoqh** [comment] 2020-04-03 18:00
Adding an example what @rscharfer talks about for reference:

_document.js
```jsx
<Html>
  <Head>
    <meta charSet="utf-8" /> {/* Trying to add this at the very top of <head> */}
    {/* scripts, RSS feed etc. */}
  </Head>
</Html>
```

This will lead to duplicate meta charset tags.

And without adding the tag explicitly, Next will add it *after* your custom tags, which in this example would be way too far down. Adding the tag in a page component doesn't work either; Next will *append* it.

**Comment by nicklouloudakis** [comment] 2020-04-07 13:41
Is there a way to prevent the extra addition of the charSet meta tag in the `lib/head.js` file, even explicitly (for instance, by using a flag)? In general, its usage is problematic: the tag is inserted way too low in the head, therefore causing site validation to throw errors. This seems to be problematic, even if head is added to the `_app.js` file.

**Comment by hk86** [comment] 2020-06-02 22:02
I have the same issue. I set my meta viewport in _document.js. Still a second meta viewport is added:

`<meta name="viewport" content="width=device-width"/>`

I do not set it myself.

**Comment by craighillwood** [comment] 2020-06-05 16:40
A solution I found for this was to leave the `_document` as is, but add the `viewport` metadata in a `next/head` component inside each page. This will cause the "page" `viewport` metadata to override the default one set by `_document` and leaves the `charset` metadata (set by `_document`) at the very top.

I ended up creating a custom `Head` component (that uses `next/head`) which already sets the `viewport` metadata (so I don't have to repeat it on every page).

I'm using the SSG of Next.js, so maybe this doesn't apply for SSR pages, don't know. Hope it helps 👍

**Comment by switz** [comment] 2020-06-30 09:04
Also seeing a duplicate meta viewport overriding the one I specify:

<img width="482" alt="image" src="https://user-images.githubusercontent.com/990166/86106867-1abe7300-ba8f-11ea-88ae-61be0312498c.png">

**Comment by consciousnessdev** [comment] 2020-07-04 09:43
> A solution I found for this was to leave the `_document` as is, but add the `viewport` metadata in a `next/head` component inside each page. This will cause the "page" `viewport` metadata to override the default one set by `_document` and leaves the `charset` metadata (set by `_document`) at the very top.
> 
> I ended up creating a custom `Head` component (that uses `next/head`) which already sets the `viewport` metadata (so I don't have to repeat it on every page).
> 
> I'm using the SSG of Next.js, so maybe this doesn't apply for SSR pages, don't know. Hope it helps +1

Do you also use redux? because, i'd same problem when i declare next/head in pages/index.js it not show meta, but when i placing it in withReduxStore (custom wrapper for redux store like with-redux-store.js in this link : https://github.com/vercel/next.js/issues/8240), it generate double meta tag on detail page.

**Comment by norfish** [comment] 2020-07-21 13:24
maybe next/head should not have the default meta, like viewport and charset

as overwrite in every page is not a good idea

**Comment by TriStarGod** [comment] 2020-07-21 19:58
I keep seeing Next/Head with meta tags and style sheet refs in both _document and _app files in nextjs examples. Are there any advantages in just setting it in _document?

**Comment by sbstnjvf** [comment] 2020-07-22 12:04
> I have the same issue. I set my meta viewport in _document.js. Still a second meta viewport is added:
> 
> `<meta name="viewport" content="width=device-width"/>`
> 
> I do not set it myself.

Also getting this.

**Comment by nevnein** [comment] 2020-07-23 11:03
Either this should be reopened, or the examples should be cleared up: i.e. the [Google Analytics example](https://github.com/vercel/next.js/blob/canary/examples/with-google-analytics/pages/_document.js) has script tags in the `<Head>` component of the `_document`, but doing so puts the aforementioned scripts before the `charset` declaration, and as noted in this issue there is with no way to override this without duplication.

So either offer a way to override, or document explicitly that you should avoid putting scripts (or anything actually) in the <Head> of the `_document` if you want it to come after the `charset` declaration (which should be in the first 1024 bytes).

Of course I'd rather have the override, as it solves even the viewport meta tag problem.

**Comment by hk86** [comment] 2020-07-26 22:12
I haven't found a fix. More a workaround. I set

```
import Head from 'next/head';
<Head>
  <meta key="viewport" name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, viewport-fit=cover" />
</Head>   
```
at `_app`. If I set it at `_document`

```
import { Head } from 'next/document';
<Head>
  <meta key="viewport" name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, viewport-fit=cover" />
</Head>   
```

I end up with a second viewport:
```
<meta key="viewport" name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, viewport-fit=cover" />
<meta name="viewport" content="width=device-width"/>
```

**Comment by valse** [comment] 2020-09-04 08:47
> Either this should be reopened, or the examples should be cleared up: i.e. the [Google Analytics example](https://github.com/vercel/next.js/blob/canary/examples/with-google-analytics/pages/_document.js) has script tags in the `<Head>` component of the `_document`, but doing so puts the aforementioned scripts before the `charset` declaration, and as noted in this issue there is with no way to override this without duplication.
> 
> So either offer a way to override, or document explicitly that you should avoid putting scripts (or anything actually) in the of the `_document` if you want it to come after the `charset` declaration (which should be in the first 1024 bytes).
> 
> Of course I'd rather have the override, as it solves even the viewport meta tag problem.

You're right and I'm putting head scripts in my Layout component with next/head

**Comment by jaybytez** [comment] 2020-09-14 16:02
I updated on this issue: https://github.com/vercel/next.js/discussions/17020

We have this issue with our TMS.  And realized anytime we have a script that does a document.head.append, a meta-tag gets duplicated in the Head.  If we just add a script to our Layout, which basically does a document.createElement and then document.head.append, a meta-tag gets duplicated.  If I add multiple calls to this, then multiple meta-tags get duplicated.  The interesting part, is I am not even adding meta-tags to the Head, I am adding div tags to the head and it just randomly duplicates a meta-tag.

**Comment by Hamrouniasma13** [comment] 2021-02-24 18:18
Hi guys , who is familiar with Head next js and know how all entries should have a key or name to prevent 2 entries.(avoid duplicating tags).

**Comment by Hamrouniasma13** [comment] 2021-02-24 18:18
![Uploading image.png…]()

**Comment by offero** [comment] 2021-03-22 00:01
I'm here trying to figure out how to specify these tags and I'm still confused.

**Comment by jperezlatimes** [comment] 2021-03-23 21:52
I've removed `_document.js` from my project entirely and am only using 'next/head' for `<title/>` and `<meta name="description"/>` and I'm still seeing duplicate charset and description meta tags.

**Comment by chozzz** [comment] 2021-03-29 23:04
The way it works for me is by giving the metas a **name** property with the following structure;

**_document.tsx**
```
    return (
      <Html lang="en">
        <Head /> // From next/document
        ...
      </Html>
    )
```

**Layout.tsx**
```
const Layout: React.FunctionComponent = ({children}) => {
  return (
    <div className="content font-play position-relative">
      <Head> // from next/head
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content={META_DESCRIPTION} />
        <meta name="theme-color" content="#06263C" />

        <meta name="og:title" property="og:title" content={META_TITLE} />
        <meta name="og:type" property="og:type" content="website" />
        <meta name="og:url" property="og:url" content={META_URL} />
        <meta name="og:image" property="og:image" content={META_URL + "/logo512.png"} />
        <meta name="og:description" property="og:description" content={META_DESCRIPTION} />

        <meta name="twitter:title" property="twitter:title" content={META_TITLE} />
        <meta name="twitter:card" property="twitter:card" content="website" />
        <meta name="twitter:site" property="twitter:site" content={META_TWITTER} />
        <meta name="twitter:creator" property="twitter:creator" content={META_TWITTER} />
        <meta name="twitter:url" property="twitter:url" content={META_URL} />
        <meta name="twitter:image" property="twitter:image" content={META_URL + "/logo512.png"} />
        <meta name="twitter:description" property="twitter:description" content={META_DESCRIPTION} />

        <link rel="apple-touch-icon" href={META_URL + "/logo512.png"} />
        <link rel="canonical" href={META_URL} />
        <link rel="manifest" href={META_URL + "/manifest.json"} />
        <meta name="robots" content="index,follow" />
      </Head>
      {children}
    </div>
  );
}
```

And **_app.tsx**
```
function App({ Component, pageProps }: AppProps): JSX.Element {
  const queryClient = new QueryClient();
  return (
    <QueryClientProvider client={queryClient}>
      <Hydrate state={pageProps.dehydratedState}>
        <Provider store={store}>
          <main className="main-container position-relative" data-testid="main-container">
            <HeaderComp />
            <Layout>
              <Component {...pageProps} />
            </Layout>
            <FooterComp />
            <ScrollToTop />
          </main>
        </Provider>
      </Hydrate>
    </QueryClientProvider>
  );
}
```

**Comment by gremo** [comment] 2021-03-30 09:24
Why the issue was closed? Is the default behavior? I't documented? For me `_document.js` was the right place to look for and put this kind of stuff, but as noticed... we get duplicate `<meta>` tag. Putting in `_app.js` solves the issue.

```javascript
// _document.js
import Document, { Head, Html, Main, NextScript } from 'next/document';
import classNames from 'classnames';

export default class extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);

    return { ...initialProps };
  }

  render() {
    return (
      <Html>
        <Head />
        <body className={classNames({
          'debug-screens': 'development' === process.env.NODE_ENV,
        })}>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
```

```javascript
// _app.js
/* eslint-disable react/prop-types */
import '../styles/globals.css'
import Head from 'next/head';

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}
```

**Comment by chozzz** [comment] 2021-03-31 22:20
The way I solved this is, I created a `CustomHead` extending `head` from `next/document` and use it in my `_document.tsx`.

**DocumentHead.tsx**

```
import React from "react";
import { Head } from "next/document";

function dedupeHead(elems: React.ReactElement<any, string>[]) {
  const result: React.ReactElement[] = [],
    mapper: { [key: string]: number } = {};

  if (elems) {
    for (let i = 0, len = elems.length; i < len; i++) {
      const elem = elems[i],
        type = elem.type,
        props = elem.props;

      /** Dedupe */
      switch (type) {
        case "meta":
          let key = props.itemprop || props.property || props.name;

          if (key) {
            if (Object.prototype.hasOwnProperty.call(mapper, key)) {
              // This meta is already in the result,
              // Replace the one in result with this
              const dupeMetaIdx = mapper[key];
              result[dupeMetaIdx] = elem;
            } else {
              // Save the elem's index in result.
              mapper[key] = result.push(elem) - 1;
            }
          } else {
            // Do not handle deduping for unknown case
            result.push(elem);
          }

          break;
        default:
          // Do not handle deduping for unknown case
          result.push(elem);
          break;
      }
    }
  }

  return result;
}

class DocumentHead extends Head {
  render() {
    this.context.head = dedupeHead(this.context.head);
    return super.render();
  }
}

export default DocumentHead;
```

**Comment by kiril-daskalov** [comment] 2021-05-13 14:47
Up

**Comment by seanislegend** [comment] 2021-08-21 12:08
I've also struggled with this one this week, and couldn't find a solution that was satisfactory. @chozzz's comment led me to what I was looking for, but I simplified the custom head to only remove the duplicate charset since that is was the only duplicated tag.

In `_document`:
```
class DocumentHead extends Head {
    render() {
        this.context.head = this.context.head.filter(item => !item.props?.charSet);
        return super.render();
    }
}
```

Use this `DocumentHead` component instead of Next's `Head` component (the `next/document` version, of course). From here you simply need to add the charset tag as the first child of `DocumentHead` and this ensures it appears as close to the document start as possible:
```
render() {
        return (
            <Html lang="en">
                <DocumentHead>
                    <meta charSet="utf-8" />
                    ... etc
```

It seems clear that either charset should not be provided by default or there should be support for opting out of using it.

**Comment by jcubic** [comment] 2021-09-29 22:45
If this is not a bug, please document at least how to use the library. Right now you can set `<meta charset/>` as the first tag.

**Comment by chozzz** [comment] 2022-01-24 01:22
As of next.js 12 - I no longer use my solution above. Adding `key` props to the meta tags solve the issue for me.

**Comment by andiemmadavies** [comment] 2022-02-06 01:54
@chozzz, same here, doing the following (specifying the key prop) in Next.js 12 has fixed it:
