### ISSUE TITLE
Scss variables from webpack not working 9.3.0

### ISSUE THREAD

**Issue by tankpower1** [zeit/next.js#10958] opened 2020-03-11 08:17 UTC
Hi, 
for my project i needed to pass a variable from webpack to scss which i managed to do in v9.2.2 but since updating to 9.3.0 it doesn't seem to work. This is my current code:

<pre>
webpack(config) {

        let isDev = ENVIRONMENT !== 'production';

        config.module.rules.forEach(rule => {

            if (rule.test && rule.test.toString().includes('.scss')) {

                rule.use.forEach(el => {

                    if (el.loader && el.loader === 'sass-loader') {

                        el.options.data = `$isDev: ${isDev};`;
                    }
                })

            }
        });

        return config;
    }
</pre>

**Comment by timneutkens** [comment] 2020-03-11 11:21
Closing as the issue template was not followed. https://github.com/zeit/next.js/issues/new/choose

**Closed by timneutkens** 2020-03-11 11:21 UTC

**Comment by balazsorban44** [comment] 2022-01-30 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
