### ISSUE TITLE
Document how to do stuff differently server-side vs. client-side

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1229] opened 2017-02-21 12:07 UTC
In Slack and in issues there comes repeatedly the question of how to do stuff differently server-side vs. client-side. I added a note in Wiki related to this: https://github.com/zeit/next.js/wiki/FAQ but it's obviously not clear enough.

I think it would be nice to add to README:
- that e.g in `getInitialProps` you can use `process.browser` var to check where you are (which AFAIK is better than `!!ctx.req` because this one still returns `true` on the first client-side render...?)
- that `componentDidMount` only runs client-side, so can add client-only code there. More generally, precise which React lifecycle methods are client-only.
- or suggest to use something like <NoSSR> component in render, or other libraries which render server-side only above-the-fold (link to examples, e.g https://github.com/zeit/next.js/tree/master/examples/progressive-render?)
- note that these should hopefully be exceptions, and it's nice to strive for code which is as universal as possible

**Comment by knipferrc** [comment] 2017-02-21 16:16
Would also be nice to know how to write ES6 code on the server side.

**Comment by sergiodxa** [comment] 2017-02-21 17:58
@knipferrc Node.js already support ES6, only modules aren't supported.

**Comment by knipferrc** [comment] 2017-02-21 18:29
@sergiodxa but cant I use babel-cli or something to get all the import, export and module stuff somehow?

**Comment by sakulstra** [comment] 2017-02-21 18:57
@sedubois there's a slack channel? maybe one could add that to the readme too ;)

**Comment by sedubois** [comment] 2017-02-21 19:02
@sakulstra there's a slack badge at the top of the README

**Comment by rauchg** [comment] 2017-02-21 19:36
@knipferrc we want to provide a server API that you can run vanilla (`node x.js`), that's why we don't transpile server code. But we might introduce `next start server.js` with transpilation in the future. It depends on how close Node modules support is.

Honestly, transpilation brings performance down. Something that I think about often is that Next.js could have an opportunity soon to bring some sanity back to development by avoiding transpilation during development (or keeping it at a minimum)[1], and only doing it upon `next build` for multi-platform support.

[1] This is supported by the fact that Node is now tracking V8 very closely, and almost everyone develops on a modern browser with great ES support

</tangent>

**Comment by timneutkens** [comment] 2017-02-27 20:00
> But we might introduce next start server.js with transpilation in the future. It depends on how close Node modules support is.

I believe @bnb mentioned it being around 1,5 years out :sweat_smile:

**Comment by MrLoh** [comment] 2017-04-01 22:04
So ES6 import syntax is still quite far away. according to [this](http://stackoverflow.com/questions/37132031/nodejs-plans-to-support-import-export-es6-es2015-modules) at least another year:

> At the current point in time, there are still a number of specification and implementation issues that need to happen on the ES6 and Virtual Machine side of things before Node.js can even begin working up a supportable implementation of ES6 modules. Work is in progress but it is going to take some time — We’re currently looking at around a year at least.

So hopefully it will arrive sometime in 2018, but in the meantime, I'd really like some option to just write the same code on server and client, this is a really annoying mental overhead to remember to import syntaxes. And some features like object destructuring would also be really nice to use on the server side. So is there any workaround for now at least, or any way in which one could contribute to making the proposed `next start server.js` reality?

**Comment by tconroy** [comment] 2017-08-05 01:30
Hey @MrLoh, just wondering if you found a clean way to implement this? `babel-node` works decently for dev work but curious what the process would entail for a deploy.

**Comment by sergiodxa** [comment] 2017-08-05 02:23
@tconroy you need to use Babel to generate files in disk with the code of your server and then use `node built/index.js` or something like that.

**Comment by MrLoh** [comment] 2017-08-05 07:16
@tconroy I ended up doing something like this: 

.babelrc:
```json 
{
  "env": {
    "server": {
      "presets": [["env", {
        "targets": {
          "node": ["current"]
        }
      }]]
    },
    "test": {
      "presets": [["env", {
        "targets": {
          "node": ["current"]
        }
      }]]
    },
    "development": {
      "presets": ["next/babel"]
    },
    "production": {
      "presets": ["next/babel"]
    }
  },
  "plugins": [
    ["root-import"],
    ["transform-object-rest-spread"],
    ["transform-flow-strip-types"],
    ["import", [
      {"libraryName": "antd"},
      {"libraryName": "lodash", "libraryDirectory": "/", "camel2DashComponentName": false}
    ]]
  ]
}
```

Than my start script looks like:
```
    "develop": "NODE_ENV=server nodemon --inspect -w server.js -w api server.js --exec babel-node",
    "build": "NODE_ENV=development next build & NODE_ENV=server babel server.js -d .dist & NODE_ENV=server babel api -d .dist/api"
    "start": "NODE_ENV=production node .dist/server.js",
```

Then I have a .env that contains `BABEL_ENV=development`

Which is called first thing in `server.js` changing the environment for the client code from `server` to `development`

**Comment by tconroy** [comment] 2017-08-05 16:46
Worked great, thanks @MrLoh!

**Comment by lorensr** [comment] 2019-08-22 06:43
> that e.g in getInitialProps you can use process.browser var to check where you are

Worth noting that it has to be referenced as `process.browser` exactly. I get `process is not defined` error when navigating to the page with this code:

![image](https://user-images.githubusercontent.com/251288/63491859-44c60280-c486-11e9-8298-467e1cd062bc.png)

Fixed by changing to:

```js
Index.getInitialProps = ({ query }) => {
  return { query, browser: process.browser }
}
```

**Closed** 2019-12-23 15:07 UTC
Labels: Documentation

**Comment by balazsorban44** [comment] 2022-01-30 19:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
