### ISSUE TITLE
with-yarn-workspaces example does not work with typescript and next 9.0

### ISSUE THREAD

**Issue by msreekm** [zeit/next.js#9295] opened 2019-11-03 17:06 UTC
# Examples bug report
yarn workspace example does not with typescript and next 9.0

## Example name
with-yarn-workspaces

## Describe the bug
from the next/examples folder - https://github.com/zeit/next.js/tree/canary/examples/with-yarn-workspaces , if i make the shared code as typescript files , i get the error module not found! I was able to fix it by adding next-typescript in next.config.js ,then the code works, but I start getting this warning -"@zeit/next-typescript is no longer needed since Next.js has built-in support for TypeScript now. Please remove it from your next.config.js and your .babelrc. " .so what is the correct way to add support to typescript in local shared code? I tried adding .babelrc with "presets": ["next/babel"] also.
here is the repo with all the above changes- https://github.com/msreekm/next-yarn-workspaces

## To Reproduce
1. clone repo
2. run yarn dev
3. see the warning @zeit/next-typescript is no longer needed since Next.js has built-in support for TypeScript now in console.

## Expected behavior
use typescript shared code without typescript warnings.

**Comment by jamesmosier** [comment] 2019-11-16 00:33
Did you follow [this guide](https://nextjs.org/docs#typescript) to get Typescript setup?

I followed these steps with success...

1. `yarn create next-app --example with-yarn-workspaces with-yarn-workspaces-app`
2. `cd with-yarn-workspaces-app/packages/web-app`
3.  `touch tsconfig.json`
4. `yarn add --dev typescript @types/react @types/node`
5. `yarn dev`

**Comment by Timer** [comment] 2019-11-20 18:39
Closing as it should be working when following new instructions as mentioned above ☝️

**Closed by Timer** 2019-11-20 18:39 UTC
Labels: Type: Example, good first issue, help wanted

**Comment by MatejBransky** [comment] 2020-02-05 07:48
@jamesmosier 
It should be noted that there is some problem with watcher: https://github.com/martpie/next-transpile-modules/issues/9

So I had to do these steps:

1. `yarn create next-app --example with-yarn-workspaces <project-folder-name>`
1. `cd <project-folder-name>/packages/web-app`
1. create empty `tsconfig.json`
1. `yarn add --dev typescript @types/react @types/node`
1. update `next.config.js`: **(new)**
```js
const withTM = require('next-transpile-modules');

// Tell webpack to compile the "bar" package
// https://www.npmjs.com/package/next-transpile-modules
module.exports = withTM({
	transpileModules: ['bar'],
	webpack(config) {
		config.resolve.symlinks = true; // source: https://github.com/martpie/next-transpile-modules/issues/9#issuecomment-498766367
		return config;
	}
});
```
6. `yarn dev`

**Comment by milesrichardson** [comment] 2020-03-11 19:36
This fixes the watcher problem for me, but files in the top level of the package being imported are not included in hot reloads.

**Comment by Albert-Gao** [comment] 2020-05-17 07:10
![image](https://user-images.githubusercontent.com/18282328/82138105-ff4a3080-9871-11ea-8a58-224410b4260e.png)

Does not work...

**Comment by balazsorban44** [comment] 2022-01-30 04:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
