### ISSUE TITLE
Keywords of next.js

### ISSUE THREAD

**Issue by LuckyPigeon** [zeit/next.js#9210] opened 2019-10-27 02:52 UTC
# Question about Next.js

CDNJS would like to add next.js as its library, but we can't find the keyword field in the `package.json` file, it would be nice if you can add some keywords in package.json file.

GitHub Issues are reserved for Bug reports and Feature requests. The best place to get your question answered is to post it on https://spectrum.chat/next-js.

**Comment by timneutkens** [comment] 2019-10-27 10:49
> CDNJS would like to add next.js as its library

I'm not sure what you mean by this. I'm going to close the issue as the issue template was not followed.

**Closed by timneutkens** 2019-10-27 10:49 UTC

**Comment by balazsorban44** [comment] 2022-01-31 01:25
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
