### ISSUE TITLE
About Amp with nextjs

### ISSUE THREAD

**Issue by 15997111963** [zeit/next.js#9359] opened 2019-11-09 06:33 UTC
![image](https://user-images.githubusercontent.com/40592585/68524139-14ac3400-02fe-11ea-9b73-30cabb19e1dc.png)
![image](https://user-images.githubusercontent.com/40592585/68524155-44f3d280-02fe-11ea-8dac-1901b93e0d67.png)
How do I write it in JSX

**Comment by ijjk** [comment] 2019-11-09 06:49
Hi, you should see an error in your console explaining how to handle this in Next.js. Are you not seeing one? 

As per https://github.com/zeit/next.js/issues/6800#issuecomment-477175709 you can use `data-amp-bind-text="something"` instead.

I'm going to close this as it's a duplicate of #6800

**Closed by ijjk** 2019-11-09 06:49 UTC

**Comment by 15997111963** [comment] 2019-11-09 06:53
Thank you for your answer

**Comment by balazsorban44** [comment] 2022-01-30 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
