### ISSUE TITLE
Ant design styles are not loading

### ISSUE THREAD

**Issue by kartikpandey2** [zeit/next.js#7757] opened 2019-07-05 10:47 UTC
I am trying to integrate ant design in NextJS. I done that by following the example given on NextJS repo. But now I also want to use css modules along with antd. So I changed next.config file and add css-loader to use css-modules. But now antd styles are not loading. If I remove css-modules from next.config then antd styles are working.

My config file: https://github.com/kartikpandey2/Next-Issue/blob/master/next.config.js

what I am doing wrong .?

**Comment by ijjk** [comment] 2019-07-05 17:29
Closing in favor of spectrum thread [here](https://spectrum.chat/next-js/general/adding-antd-with-nextjs~d0259596-d74e-45c2-a9aa-7c42175f497a)

**Closed by ijjk** 2019-07-05 17:29 UTC

**Comment by balazsorban44** [comment] 2022-01-31 13:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
