### ISSUE TITLE
Support baseUrl in tsconfig

### ISSUE THREAD

**Issue by ambigram1984** [zeit/next.js#7935] opened 2019-07-12 18:30 UTC
When using the `baseUrl` property in`tsconfig.json`, Next 9 fails to build with the following error:
`Module not found: Can't resolve ...`

This is resolved but updating the import path to be absolute.

When running `tsc` on the same directory, the relative import works.

## Expected behavior

The `baseUrl` in `tsconfig.json` is used when running `next build`

## To Reproduce

Update tsconfig to use `baseUrl` compiler option:

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "baseUrl": "."
  },
  "exclude": ["node_modules"],
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"]
}
```

Assuming a directory structure of:
```
components
  |--> Layout.tsx
pages
  |--> index.tsx
```

Import file using relative path:
```jsx
  // pages/index.js
  import Layout from 'components/layout'

  export default (props) => <Layout>Welcome!</Layout>
```

package.json
```json
"dependencies": {
    "next": "^9.0.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
  },
"devDependencies": {
   "typescript": "^3.5.3"
}
```

**Comment by PabloSzx** [comment] 2019-07-13 19:44
I needed this feature so i made a workaround using [tsconfig-paths-webpack-plugin](https://www.npmjs.com/package/tsconfig-paths-webpack-plugin)

My next.config.js ended like this


![Code_-_Insiders_NJxLaKK5R0](https://user-images.githubusercontent.com/8672915/61175880-f3704c80-a584-11e9-9f28-4c091cb7d179.png)

**Comment by Timer** [comment] 2019-07-14 10:11
Duplicate of https://github.com/zeit/next.js/issues/7779

**Closed by Timer** 2019-07-14 10:11 UTC

**Comment by EricVanDerDijs** [comment] 2019-08-15 03:19
@PabloSzx Thanks a lot for that comment, I have been looking for solutions for this for a long while now.

**Comment by sakulstra** [comment] 2019-08-18 14:10
@PabloSzx does this actually work for you?

I tried adding as next.config.js
```
const TsconfigPathsPlugin = require("tsconfig-paths-webpack-plugin");

module.exports = {
  webpack: (config, options) => {
    if (config.resolve.plugins) {
      config.resolve.plugins(new TsconfigPathsPlugin());
    } else {
      config.resolve.plugins = [new TsconfigPathsPlugin()];
    }

    return config;
  },
  target: "serverless"
};
```
and 
```
    "baseUrl": "."
```
inside the tsconfig, but root imports still don't seem to be working (may be due to me mixing js and tsx files).

**Comment by PabloSzx** [comment] 2019-08-18 16:42
@sakulstra i just made a Next 9 template repository which uses TypeScript and tsconfig-paths-webpack-plugin https://github.com/PabloSzx/Next-TypeScript-Paths

**Comment by HosseinAgha** [comment] 2019-10-14 13:58
@PabloSzx you need to [use `.push` here](https://github.com/PabloSzx/Next-TypeScript-Paths/blob/master/next.config.js#L6) instead of calling `plugins` as a function

**Comment by zhengrenzhe** [comment] 2019-12-24 14:52
> @PabloSzx does this actually work for you?
> 
> I tried adding as next.config.js
> 
> ```
> const TsconfigPathsPlugin = require("tsconfig-paths-webpack-plugin");
> 
> module.exports = {
>   webpack: (config, options) => {
>     if (config.resolve.plugins) {
>       config.resolve.plugins(new TsconfigPathsPlugin());
>     } else {
>       config.resolve.plugins = [new TsconfigPathsPlugin()];
>     }
> 
>     return config;
>   },
>   target: "serverless"
> };
> ```
> 
> and
> 
> ```
>     "baseUrl": "."
> ```
> 
> inside the tsconfig, but root imports still don't seem to be working (may be due to me mixing js and tsx files).

config.resolve.plugins is an array, should be this:

```
if (config.resolve.plugins) {
      config.resolve.plugins.push(new TsconfigPathsPlugin());
} else {
      config.resolve.plugins = [new TsconfigPathsPlugin()];
}
```

:D

**Comment by blainegarrett** [comment] 2020-04-07 23:24
@zhengrenzhe @PabloSzx Out of curiosity, do you have the `tsconfig-paths-webpack-plugin` installed as a devDependecy or normal dependency. I was surprised to find that running the prod build errored on the import in next.config. For some reason, I thought next.config would be moot in a production build. I normally only use it for the runtimeConfig. I'm wondering if there is a performance hit with it running in the built production app... or maybe at that point its just a useless import?

**Comment by PabloSzx** [comment] 2020-04-07 23:33
It doesn't matter in the final build, and the path equivalents are made in compilation time. 

Although, there is an experimental official support for this feature 
#11293

**Comment by timneutkens** [comment] 2020-04-08 07:37
You'll probably want to use the experimental support from #11293 indeed. It'll be on stable very soon.

**Comment by regalstreak** [comment] 2020-09-01 20:24
For me, restarting the Next.js dev server worked haha

**Comment by balazsorban44** [comment] 2022-01-29 15:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
