### ISSUE TITLE
[BUG] @zeit/next-stylus breaking Link component

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [zeit/next.js#11923] opened 2020-04-15 17:55 UTC
`next.config.js:`

```javascript
const withStylus = require('@zeit/next-stylus')
module.exports = withStylus()
```

`files:`

![image](https://user-images.githubusercontent.com/60403187/79370300-163bf100-7f5b-11ea-9819-c67c8b730dfe.png)

`index.js:`
```javascript
import Link from "next/link"


export default function () {
  return <div>
    <h1>HOME</h1>

    <Link href="/news">
      <a>to news</a>
    </Link>
  </div>
}
```

`news.js:`
```javascript
import Link from "next/link"
import './news.styl'  //<- problem here

export default function () {
  return <div>
    <h1>News</h1>

    <Link href="/">
      <a>home</a>
    </Link>
  </div>
}
```

`news.styl:`
```stylus
.lol
	background-color red
```

Action
====
1) open `localhost:3000/`
2) click `news` link
3) link not work

Reason
---
1) if we remove `import css from './news.styl'` row from `news.js` file, link on home page will work.
2) if we add `import css from './news.styl'` on `news.js` and `index.js` files, link will work

I think this is a problem with dynamic loading of modules
---

**Comment by timneutkens** [comment] 2020-04-16 08:34
Duplicate of https://github.com/zeit/next-plugins/issues/282

Please follow the issue template.

**Closed by timneutkens** 2020-04-16 08:34 UTC

**Comment by balazsorban44** [comment] 2022-01-30 07:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
