### ISSUE TITLE
Error: Cannot read property '__html' of undefined when defining a custom Document with getInitialProps

### ISSUE THREAD

**Issue by markbrocato** [zeit/next.js#9087] opened 2019-10-15 18:34 UTC
# Bug report

## Describe the bug

If you defined a `pages/_document.js` with `getInitialProps`, and return `styles`, you get this error when loading the app with `?amp=1` in the URL:

```js
Error: Cannot read property '__html' of undefined when defining a custom Document.getInitialProps
```

## To Reproduce

Use the _document.js from Material UI's example here: https://github.com/mui-org/material-ui/blob/master/examples/nextjs/pages/_document.js

The error goes away if you comment out:

```js
    styles: [
      <React.Fragment key="styles">
        {initialProps.styles}
        {sheets.getStyleElement()}
      </React.Fragment>,
    ],
```

## Expected behavior

An AMP response should be rendered without error.

## System information

- OS: macOS
- Browser: chrome
- Version of Next.js: 9.1.1

**Comment by Janpot** [comment] 2019-10-15 19:57
related:
https://github.com/zeit/next.js/issues/9041
https://github.com/zeit/next.js/issues/7856

**Comment by timneutkens** [comment] 2020-05-01 11:51
Going to close this issue as it hasn't had activity for a few months. I believe the issue has been fixed by Olivier 👍

**Closed by timneutkens** 2020-05-01 11:51 UTC
Labels: good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-30 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
