### ISSUE TITLE
Error when i'm trying to deploy nextjs on cloud functions

### ISSUE THREAD

**Issue by jackmatrix** [zeit/next.js#2467] opened 2017-07-05 08:21 UTC
I am trying to make nextjs works together with firebase cloud functions. 

When i am testing locally, there is no problem my app works perfectly.

However when i am deploying there is an error related to this line 

`const app = next({ dev : false })`

When i put this line, my functions cannot be deployed and i get this message 

`Deploy Error: Function load error: Error: cannot communicate with function.`

I don't understand because i don't have this issue in local testing. 

Then when i comment this line. It's okay i can deploy my functions. However there is no possibility to use next.js . So this is the problem. 

I have this error even without using any nextjs stuff in my functions. Just the fact to declare the line 

`const app = next({ dev : false })` prevent my app to deploy

any suggestions ?

**Comment by timneutkens** [comment] 2017-07-05 18:49
Duplicate of https://github.com/zeit/next.js/issues/2017. TLDR: I wouldn't use it cause it causes overhead on each request.

**Closed by timneutkens** 2017-07-05 18:49 UTC
