### ISSUE TITLE
Router.push error on IE 11 from V9.1.5

### ISSUE THREAD

**Issue by kartikag01** [zeit/next.js#9998] opened 2020-01-08 19:12 UTC
# Bug report
Router.push error on IE 11 from V9.1.5

## Describe the bug
After updating to 9.1.5, next js starts to give error on IE11 when Router.push encountered
`SCRIPT7002: XMLHttpRequest: Network Error 0x80700013, Could not complete the operation due to error 80700013.`

## Expected behavior

Page Navigation should happen.

## Screenshots

![image](https://user-images.githubusercontent.com/10574227/72007959-6991fb00-3218-11ea-954f-1c5fb2960a21.png)

## System information

- OS: Windows
- Browser IE 11
- Version of Next.js: [9.1.5,9.1.6, 9.1.7]

**Comment by ijjk** [comment] 2020-01-08 19:26
Hi, we test our production suite in ie11, Safari, Firefox, and Chrome and it is passing on the latest releases. The above error looks to be a CORS issues as it mentions the `Acess-Control-Allow-Origin`. The only time we add CORS headers is in development for our hot-reloader. Are you using a custom server that is heading CORS headers which are incompatible with the environment you're testing in? Are you seeing any errors with a production build?

If you can provide a reproduction we would be happy to look into this!

**Comment by kartikag01** [comment] 2020-01-09 16:18
Yes, error is same on production build also,
It might be because of dynamic import.
I will add sample code repo in day or so.
We are not using any custom server.

**Comment by timneutkens** [comment] 2020-03-20 12:08
Closing as a reproduction was not provided.

**Closed by timneutkens** 2020-03-20 12:08 UTC
Labels: Please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-30 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
