### ISSUE TITLE
[nextjs 9 API] how to use Express lib like  app.use(...) inside page/api ??

### ISSUE THREAD

**Issue by shipcake** [zeit/next.js#7910] opened 2019-07-12 02:33 UTC
I came to nextJS 9.0 . I happy easy to use API And Client Together. but I want to move external API into NEXTJS project (page/api) Graphql  workfine. but External API Keep IP and location in middleware.

I use lib external API  below. 
request-ip
express-ip

PS.graphql I use apollo-server-micro and I pass bodyParser:off in graphql

**Comment by PabloSzx** [comment] 2019-07-12 19:58
<img width="237" alt="Code_-_Insiders_DbbI75Oh4t" src="https://user-images.githubusercontent.com/8672915/61154978-a83f3680-a4bd-11e9-856e-fef7526a8fd1.png">
this way, you could have another file to define the express() and use some common middlewares

**Comment by ShanonJackson** [comment] 2019-07-13 07:20
@PabloSzx i don't understand as there is a huge lack of documentation (atleast i haven't been able to find much) on Next.JS 9's new express-style routes.

Does the above syntax use express instead of NextJS 9 backend? or are they one and the same?

**Comment by timneutkens** [comment] 2019-07-13 20:09
Adding `express` will greatly reduce performance of the API endpoint. We'll be adding a helper for middleware soon. But I'm going to close this issue as it ignored the issue template.

**Closed by timneutkens** 2019-07-13 20:09 UTC

**Comment by htunnicliff** [comment] 2019-07-28 18:07
@timneutkens – Is there an active PR or RFC for the middleware helper you mentioned? I'd be happy to contribute if help is welcome.

**Comment by rafaelcg** [comment] 2019-09-13 13:54
For anyone in the future looking for this feature, what you need is probably [API Routes](https://nextjs.org/blog/next-9#api-routes).

**Comment by htunnicliff** [comment] 2020-12-01 22:18
I ended up creating a library to implement middleware easily on Next.js API routes: [`next-api-middleware`](https://github.com/htunnicliff/next-api-middleware)

**Comment by balazsorban44** [comment] 2022-01-29 02:12
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
