### ISSUE TITLE
Dynamic route not working via Links

### ISSUE THREAD

**Issue by rajat1saxena** [zeit/next.js#9072] opened 2019-10-14 16:12 UTC
# Bug report

## Describe the bug
I have a dynamic route like this: `/pages/post/[id]/[slug].js`. To go to such routes, in my app I've built links as follows:
```
<Link
    href={`/post/[id]/[slug]`}
    as={`/post/${props.id}/${props.slug}`}>
```
When I click such links for the very first time, some script loads (From Chrome's Network Tab: http://localhost:3000/_next/static/development/pages/post/%5Bid%5D/%5Bslug%5D.js) but I am not taken to the post i.e. `/post/123/demo-post`. But when I deliberately put this address in the URL bar or right-click the link to open in a new tab, I can see my page correctly.

## Expected behavior

Clicking the `Link` should take me to the desired page. 

One more thing is that, if I visit the post directly by entering the address or right clicking, then I can go back to the home page (by clicking the site logo) and come back to the post again by clicking the Link normally and it loads instantaneously.

## System information

- OS: Windows 10 (Home)
- Browser Chrome
- Version of Next.js: 9.1.1

**Comment by Timer** [comment] 2019-10-14 16:33
Are you using `next-css`?

**Comment by rajat1saxena** [comment] 2019-10-14 17:06
@Timer Yes.

**Comment by Timer** [comment] 2019-10-14 18:00
Be sure you import DraftJS in your Custom App and not an individual page!

Closing in favor of https://github.com/zeit/next.js/issues/8626

**Closed by Timer** 2019-10-14 18:00 UTC

**Comment by rajat1saxena** [comment] 2019-10-14 19:05
I put `import 'draft-js/dist/Draft.css'` in `_app.js` and still got the same error.

**Comment by Timer** [comment] 2019-10-15 12:54
You could try out the new experimental CSS support by setting `{ experimental: { css: true } }` in your `next.config.js` -- otherwise we'll need to wait for the feature to go stable.

**Comment by balazsorban44** [comment] 2022-01-31 02:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
