### ISSUE TITLE
apolloClient is a shadowed variable in withApollo

### ISSUE THREAD

**Issue by savnik** [zeit/next.js#9813] opened 2019-12-23 13:39 UTC
# Examples bug report

## Example name

with-apollo

## Describe the bug

apolloClient is a shadows variables as it is defined in both a local scope and the containing scope. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://github.com/zeit/next.js/blob/canary/examples/with-apollo/lib/apollo.js
2. Find line 20 to see definition of apolloClient in local scope. https://github.com/zeit/next.js/blob/b95228ed89fa163056945210f4ebd3554165f390/examples/with-apollo/lib/apollo.js#L20
3. Scroll down to line 47 to find definition in outer scope. https://github.com/zeit/next.js/blob/b95228ed89fa163056945210f4ebd3554165f390/examples/with-apollo/lib/apollo.js#L47

## Additional context

Shadowing makes it impossible to access the variable in the containing scope and obscures to what value an identifier actually refers.

**Comment by timneutkens** [comment] 2020-01-03 10:14
Fixed in #9917

**Closed by timneutkens** 2020-01-03 10:14 UTC
Labels: good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-30 17:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
