### ISSUE TITLE
Requesting for wrong js file when using getServerSideProps and dynamic routes and <Link>

### ISSUE THREAD

**Issue by StarpTech** [zeit/next.js#11660] opened 2020-04-04 11:34 UTC
# Bug report

## Describe the bug

As an example: Use the post's example in the [documentation](https://nextjs.org/docs/basic-features/data-fetching#simple-example-1). I have a page `/pages/stores/index.js` and `/pages/stores/[slug].js`. When I wrap `next/link` around these links I get different behavior. 

Click on `/stores` will fetch 
1. (**200**) `/_next/static/development/pages/stores.js`
2. (**200**) `_next/data/development/stores.json`

and render my page properly.

but click on `/stores/foo` will fetch
1. (**404**) `_next/static/development/pages/stores/foo.js`
2. (**200**) Hard reload of document `/stores/foo`

and render my page properly.

## To Reproduce

Create posts/post examples with `getServerSideProps` and wrap the link to the pages with `next/link`. **Use client-side routing**.

## Expected behavior

At least it should not return status code 404 but I would also expect that the page can be rendered on client-side in the same way as `/stores`

Next: 9.3.4

**Comment by StarpTech** [comment] 2020-04-04 12:33
Related https://github.com/zeit/next.js/issues/8207

**Comment by StarpTech** [comment] 2020-04-04 12:41
As described in #8207 there are workarounds:

```jsx
 <Link href="/stores/[slug]" as={`/stores/${slug}`}></Link>
```

as long as it's not fixed properly I would recommend throwing a better error message and referring to https://nextjs.org/docs/api-reference/next/link#dynamic-routes

**Comment by Timer** [comment] 2020-04-15 05:58
Duplicate of #8207. This is a result of an invalid Link, as you mentioned above.

**Closed by Timer** 2020-04-15 05:58 UTC

**Comment by balazsorban44** [comment] 2022-01-30 07:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
