### ISSUE TITLE
Unable to use external module with SASS and CSS

### ISSUE THREAD

**Issue by meienberger** [zeit/next.js#9661] opened 2019-12-08 13:39 UTC
# Bug report

## Describe the bug

I'm trying to add wix-style-react plugin inside my NextJS project but I'm unable to build. Inside their [documentation](https://github.com/wix/wix-style-react), they say they use  Stylable, SASS and CSS Modules.

When I install the plugin and build, I get the following error :

> Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import '../common';

I tried both following methods :

1. Using next-sass inside my `next.config.js`

```js
// next.config.js
const withSass = require('@zeit/next-sass')

module.exports = withSass({
  cssModules: true
})
```

This way I got another error warning me about a .css file

> Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .root {
|   display: inline-block;
|   text-overflow: ellipsis;

2. Using next-css in combination with next-sass

```js
// next.config.js
const withSass = require('@zeit/next-sass')
const withCss = require('@zeit/next-css')

module.exports = withCss(
  withSass({
    cssModules: true,
  })
)
```

With this config, I get again the same error as with no config

## To Reproduce

1. Create a new blank project with `create-next-app`
2. Install the module `yarn add wix-style-react`
3. Build `yarn build`

## System information

- OS: macOS
- Version of Next.js: 9.1.4

**Comment by timneutkens** [comment] 2019-12-08 14:49
Closing in favor of #8626

**Closed by timneutkens** 2019-12-08 14:49 UTC

**Comment by balazsorban44** [comment] 2022-01-30 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
