### ISSUE TITLE
Glamor style tag always included

### ISSUE THREAD

**Issue by khrome83** [zeit/next.js#1036] opened 2017-02-08 13:45 UTC
The glamor style tag is always included regardless of use of glamor. This is in `2.0.0-beta.24`.

`<style type="text/css" data-glamor=""></style>` is present within the DOM upon rendering dev or final build.

Take for example this `_document.js` fragment.

```
import Document, { Head, Main, NextScript } from 'next/document'

export default class MyDocument extends Document {
  static async getInitialProps ({ renderPage }) {
    const page = renderPage()
    return { ...page }
  }

  render () {
    return (
      <html>
        <Head>
          <title>Site Title</title>
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
        <style jsx global>{`
          html, body {
            background-color: #f00;
            font-size: 16px;
            color: #fef;
          }
          p {
            color: red;
          }
        `}</style>
      </html>
    )
  }
}
```

**Comment by timneutkens** [comment] 2017-02-08 13:47
Duplicate of https://github.com/zeit/next.js/issues/989

**Closed by timneutkens** 2017-02-08 13:47 UTC
