### ISSUE TITLE
Access to bundle files in Document.getInitialProps

### ISSUE THREAD

**Issue by tills13** [zeit/next.js#9492] opened 2019-11-21 22:19 UTC
# Feature request

Passing through `files` (and perhaps other build information) into `Document`s' `getInitialProps` would allow users of NextJS more advanced functionality around asset distribution. For example, our specific use case involves [server-pushing (via CloudFlare)](https://www.cloudflare.com/website-optimization/http2/serverpush/) the assets to the client. As it stands, we have to either: 

1. hardcode the assets we'd like to push (hand-generate the URLs)
2. (untested) pass `res` through `Document`'s props and add the appropriate header there (`this.props.files` is available here). This feels awful, and I'm not sure if it would work in all situations / if it breaks anything else as `res` isn't serializable.

## Describe the solution you'd like

`files` and other build-time information to be passed into `Document.getInitialProps`

## Describe alternatives you've considered

None

**Comment by timneutkens** [comment] 2020-01-03 00:56
Going to close this as no other 👍 were added.

**Closed by timneutkens** 2020-01-03 00:56 UTC

**Comment by balazsorban44** [comment] 2022-01-30 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
