### ISSUE TITLE
Version 9.1.6 build error

### ISSUE THREAD

**Issue by alabobriggs** [zeit/next.js#9854] opened 2019-12-27 23:46 UTC
# Bug report
upgraded next.js version from 9.1.4 to 9.1.6 and got a `unknown: Unexpected token (7524:8)` error. When I reversed to 9.1.4 the error was fixed

## Describe the bug
got an error when I ran `npm run build` on version 9.1.6 of next.js when I reversed the version to 9.1.4 it was resolved. Also got this build error on zeit now
```
ailed to compile.

unknown: Unexpected token (7524:8)

> Build error occurred
Error: > Build failed because of webpack errors
    at build (/home/alabo/Documents/developers/kushnap/node_modules/next/dist/build/index.js:9:900)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kushnap@1.0.0 build: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kushnap@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alabo/.npm/_logs/2019-12-27T23_00_58_197Z-debug.log

```

## To Reproduce
1. Upgrade next.js version to version 9.1.6. (I was on version 9.1.4)
2. Run `npm run build` which will run next build script
3. See error

## Expected behavior
It is meant to build succesfully but it gave this error

## Screenshots
![Screenshot from 2019-12-28 00-42-40](https://user-images.githubusercontent.com/38571291/71536012-4491b400-290b-11ea-8191-153b791ab308.png)

## System information

- OS: elementary os 5.1
- Version of Next.js: 9.1.6

**Comment by Timer** [comment] 2019-12-28 00:18
We're not going to be able to fix this without a full reproducible demo! Please provide one. 🙏

**Comment by jack2ky** [comment] 2019-12-28 08:04
This might not be helpful, but I used Material-UI react and I received errors. one error said it was coming from a file named something like commons-434kj.js page. It said the error had to do something with "makeStyle". Anyways I did npm exact version 9.1.3. And the errors went away. 

Also to confuse things more (unintentionally) only some of my pages showed error.

Sorry I didn't get a chance to write down all errors and make a reproducible thing. I just didn't want to see the errors anymore.

I want to let you not what happened. **Downgrading worked**

Thanks for your work.

**Comment by alabobriggs** [comment] 2019-12-28 09:32
> We're not going to be able to fix this without a full reproducible demo! Please provide one.

Should I provide a full project folder?

**Comment by alabobriggs** [comment] 2019-12-28 09:33
> This might not be helpful, but I used Material-UI react and I received errors. one error said it was coming from a file named something like commons-434kj.js page. It said the error had to do something with "makeStyle". Anyways I did npm exact version 9.1.3. **And the errors went away**.
> 
> Also to confuse things more (unintentionally) only some of my pages showed error.
> 
> Sorry I didn't get a chance to write down all errors and make a reproducible thing. I just didn't want to see the errors anymore.
> 
> I wanted to let you know what happened. **Downgrading worked**
> 
> Thanks for your work.

Mine refused to build for hours. Immediately I downgraded it worked

**Comment by timneutkens** [comment] 2019-12-28 12:13
> Should I provide a full project folder?

At least some way for us to look into it. It's almost impossible without a reproduction as you can imagine.

**Comment by alabobriggs** [comment] 2019-12-28 19:42
> > Should I provide a full project folder?
> 
> At least some way for us to look into it. It's almost impossible without a reproduction as you can imagine.

Okay I will provide one

**Comment by alabobriggs** [comment] 2019-12-29 21:36
@Timer please can I add you to the existing repo?

**Comment by Ravindersingh1526** [comment] 2019-12-30 05:04
same issue thanks for reopen
an unexpected error has occurred in production build and following error shown in the console
TypeError: C.map is not a function
    at O (index.js:1)
    at vo (commons.d8f8bdfe8c5516f68f92.js:1)
    at Qo (commons.d8f8bdfe8c5516f68f92.js:1)
    at Tl (commons.d8f8bdfe8c5516f68f92.js:1)
    at wi (commons.d8f8bdfe8c5516f68f92.js:1)
    at Ci (commons.d8f8bdfe8c5516f68f92.js:1)
    at Ei (commons.d8f8bdfe8c5516f68f92.js:1)
    at commons.d8f8bdfe8c5516f68f92.js:1
    at t.unstable_runWithPriority (commons.d8f8bdfe8c5516f68f92.js:1)
    at $c (commons.d8f8bdfe8c5516f68f92.js:1)

**Comment by alabobriggs** [comment] 2019-12-30 06:09
I just fixed the error by adding a dev package [here](https://github.com/lucleray/next-progressbar) to show build progress and I updated my next.config.js from
```
const withPlugins = require("next-compose-plugins");
const withCSS = require('@zeit/next-css')
const withBabelMinify = require('next-babel-minify')

const nextConfigs = {
    webpack: (config) => {
        // Fixes npm packages that depend on `fs` module
        config.node = {
            fs: "empty"
        };
        config.plugins = [
            ...config.plugins
        ]
        return config;
    },
    target: 'serverless'
}

module.exports = withPlugins(
    [
        // plugin to import css
        withCSS({
            cssModules: true
        }),

        withBabelMinify()
    ], 
    nextConfigs
);
```
to 

```
const withPlugins = require("next-compose-plugins");
const withCSS = require('@zeit/next-css')
const withBabelMinify = require('next-babel-minify')
const withProgressBar = require('next-progressbar')

const nextConfigs = {
    webpack: (config) => {
        // Fixes npm packages that depend on `fs` module
        config.node = {
            fs: "empty"
        };
        config.plugins = [
            ...config.plugins,
        ]
        return config;
    },
    target: 'serverless'
}

module.exports = withPlugins(
    [
        withCSS({}),
        withBabelMinify(),
        withProgressBar({})
    ], 
    nextConfigs
);
```

and this made the build process way faster moving from about 2 mins to 40s
![Screenshot from 2019-12-30 07-06-40](https://user-images.githubusercontent.com/38571291/71570000-2f678180-2ad3-11ea-8265-92a74fd08764.png)


Thanks everyone for your support

**Comment by Timer** [comment] 2019-12-30 13:33
Closing as OP said problem was resolved and has removed our access from repo before we could take a look. Also, using `next-babel-minify` is likely causing a double minification step.

**Closed by Timer** 2019-12-30 13:33 UTC
Labels: Can't Reproduce

**Comment by alabobriggs** [comment] 2019-12-30 14:20
**Just incase anyone lands here in the future.**
The recommended fix provided by @Timer  was to adjust the next.config.js as most of the modules there wasn't being used. The config was trimed from

``` sh

const withPlugins = require("next-compose-plugins");
const withCSS = require('@zeit/next-css')
const withBabelMinify = require('next-babel-minify')
const withProgressBar = require('next-progressbar')

const nextConfigs = {
    webpack: (config) => {
        // Fixes npm packages that depend on `fs` module
        config.node = {
            fs: "empty"
        };
        config.plugins = [
            ...config.plugins,
        ]
        return config;
    },
    target: 'serverless'
}

module.exports = withPlugins(
    [
        // plugin to import css
        withCSS({}),
        withBabelMinify(),
        withProgressBar({
            progressBar: {
                fancy: true
            }
        })
    ], 
    nextConfigs
);
```

to

```
module.exports = {
	experimental: { css: true },
}

```
NOTE:
Experimantal above was added for some css features that are currently in development.
Global css files linked in `_document.js` head was imported in `app.js`

**Comment by anasalpure** [comment] 2020-09-15 19:14
i think you must instal webpack then retry to Build your broject
**npm install --save-dev webpack**

**Comment by tesshsu** [comment] 2020-10-19 14:56
Hi
I follow @anasalpure and still got the same error, any updated ? tks

**Comment by mjhcc365** [comment] 2021-02-01 07:17
is there anyone?

**Comment by Mahbub-Hasan1** [comment] 2021-07-03 10:27
same problem 😥
``
$ npm run build

> yeender@0.1.0 build
> next build

info  - Loaded env from D:\WebSite-Client-Pro\shabnam-priyanka-apo\yeender.com\New folder\yeender-solution\.env.local
info  - Using webpack 5. Reason: no custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  
info  - Creating an optimized production build  
Failed to compile.

HookWebpackError: <css input>:11:2: Missed semicolon


> Build error occurred
Error: > Build failed because of webpack errors
    at D:\WebSite-Client-Pro\shabnam-priyanka-apo\yeender.com\New folder\yeender-solution\node_modules\next\dist\build\index.js:17:924
    at async Span.traceAsyncFn (D:\WebSite-Client-Pro\shabnam-priyanka-apo\yeender.com\New folder\yeender-solution\node_modules\next\dist\telemetry\trace\trace.js:6:584) 
``

**Comment by balazsorban44** [comment] 2022-01-28 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
