### ISSUE TITLE
Dynamic routing to page with antd Table doesn't work

### ISSUE THREAD

**Issue by Shaquu** [zeit/next.js#9534] opened 2019-11-26 15:48 UTC
# Bug report

## Describe the bug

Dynamic routing to page with ant.design Table component doesn't work.
Bug only appears on build. On dev run it works properly.

## To Reproduce

I have two pages: Main and Sub.
Sub page contains component which contains Table component.
When I go from Main page to Sub page via Link (dynamic routing) then nothing happens and I am not redirected to Sub page. When I type Sub page url manually to browser bar then Sup page loads.

## Expected behavior

I should be redirected to Sup page via Link (dynamic routing).

## Additional context

I am using latest versions for antd, nextjs, typescript.

Firstly I was using Table component in Sub page directly. (Sub has Table)
Importing via below code didn't work and caused above error:
`import { Table } from 'antd'`
I have fixed it with importing Table directly
`import Table from 'antd/lib/table'`

Later on I had to move Table component to sub component. And both import doesn't work now.  (SomeComponent has Table, Sub has SomeComponent)

next.config.js
```javascript
/* eslint-disable */
const withLess = require('@zeit/next-less')
const lessToJS = require('less-vars-to-js')
const fs = require('fs')
const path = require('path')

// Where your antd-custom.less file lives
const themeVariables = lessToJS(
    fs.readFileSync(path.resolve(__dirname, './assets/theme.less'), 'utf8')
)

module.exports = withLess({
    exportTrailingSlash: false,
    lessLoaderOptions: {
        javascriptEnabled: true,
        modifyVars: themeVariables, // make your antd custom effective
    },
    webpack: (config, { isServer }) => {
        if (isServer) {
            const antStyles = /antd\/.*?\/style.*?/
            const origExternals = [...config.externals]
            config.externals = [
                (context, request, callback) => {
                    if (request.match(antStyles)) return callback()
                    if (typeof origExternals[0] === 'function') {
                        origExternals[0](context, request, callback)
                    } else {
                        callback()
                    }
                },
                ...(typeof origExternals[0] === 'function'
                    ? []
                    : origExternals),
            ]
            config.externals.exclude = /node_modules\/(?!(os)\/).*/

            config.module.rules.unshift({
                test: antStyles,
                use: 'null-loader',
            })
        }
        return config
    },
})
```

.babelrc
```json
{
    "presets": ["next/babel"],
    "plugins": [
        [
            "import",
            {
                "libraryName": "antd",
                "style": true
            }
        ]
    ]
}
```

**Comment by ijjk** [comment] 2019-11-26 16:00
Hi, this is appears to be a duplicate of #9385 and https://github.com/zeit/next-plugins/issues/282. We are looking into fixing this and opened a RFC [here](https://github.com/zeit/next.js/issues/8626)

**Closed by ijjk** 2019-11-26 16:00 UTC

**Comment by Shaquu** [comment] 2019-11-27 08:25
Temporary solution until guys finish RFC.

Create empty css file (I am using less so it was empty.less for me) in your static folder (my folder is assets but you can just use any folder following your structure).
Then import it in the _app.js (in my case it is _app.tsx since I use typescript everywhere).

So my _app.tsx starts with:
```javascript
import '../assets/empty.less'

import App from 'next/app'
import React from 'react'
//Other code
```

Now problem with routing to sites with Table and DataPicker is resolved.
I don't have to import Table styles anywhere beside importing Table component itself.
`import {Table} from 'antd'`

**Comment by balazsorban44** [comment] 2022-01-30 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
