### ISSUE TITLE
Serverless : Build only one page

### ISSUE THREAD

**Issue by romainquellec** [zeit/next.js#6543] opened 2019-03-06 11:27 UTC
# Feature request
Add a param -page to next build for target:serverless

## Is your feature request related to a problem? Please describe.
I'm using serverless framework with CircleCI and build phase can be very long

## Describe the solution you'd like
As I can detect which page is modified, I can only build the lambda associated and deploy only this lambda with serverless.

**Comment by rauchg** [comment] 2019-03-07 04:10
> As I can detect which page is modified

What if you modify a dependency of the page? How do you detect that ?

**Comment by romainquellec** [comment] 2019-03-20 11:13
Well, you can't always know, but it works most of the time.
I think this improvement can be usefull for serverless-nextjs-plugin (This serverless plugin can also deploy one page, so good combination)

**Comment by ferezoz** [comment] 2019-08-16 05:38
This would help when using `serverless` target on Firebase Cloud Functions to build and deploy separate bundles(Lambdas) for each function with its own folder with something like this:
```
+---folder1/   <----------(For index.js page)
    +----firebase.json
    +----functions/
        +----next/
        +----node_modules/
        +----index.js
        +----package.json
+---folder2/   <----------(For about.js page)
    +----firebase.json
    +----functions/
        +----next/
        +----node_modules/
        +----index.js
        +----package.json
```

We would need to `firebase deploy --only functions:functionName` to not overwrite existing deployed functions.

We could even configure custom build directories for each page in `next.config.js` like this:

```js
// next.config.js
module.exports = {
  distDir: {
    index: 'folder1/functions/next',
    about: 'folder2/functions/next'
 }
};
```

I know that if you just use one folder to deploy your functions they will all share the entire next app bundle and it wouldn't scale because it will get bigger in size with each page added but I think thats already happening when using `server` target for bundling a single serverless function, it is still increasing its size with every page and that will not scale as well.

I'm just trying to find ways to use `serverless` with Firebase Cloud Functions. 🙂

**Comment by timneutkens** [comment] 2020-01-02 20:30
Closing this as there haven't been 👍 on the initial issue.

**Closed by timneutkens** 2020-01-02 20:30 UTC
Labels: Type: Feature Request

**Comment by dvargas92495** [comment] 2021-04-28 03:04
Hey I'm looking to do this as well. My goal is to sort of do ISR but while maintaining SSG. So the workflow is:
- User updates a piece of data
- Event hook detects the data update and calls my lambda
- Lambda updates single page dependent on that data

So what I'm looking for help with is the last step. I'm hoping to run a `next build` type command to build the single HTML page to deploy to my S3 bucket. Ideally I'd like to avoid using the whole `serverless` for this one workflow. Any modules available that could help with this or plans to support something similar in Next?

**Comment by balazsorban44** [comment] 2022-01-28 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
