### ISSUE TITLE
[Next 9.0.0] New Api-route doesn't work on prod

### ISSUE THREAD

**Issue by victorDecroix** [zeit/next.js#7826] opened 2019-07-09 09:35 UTC
# Examples bug report

## Example name

api-routes

## Describe the bug

The new API route works on a dev server but not on a production server

## To Reproduce

https://github.com/zeit/next.js/tree/master/examples/api-routes

1. `npm run build`
2. `npm run start`
3. click on **Luke Skywalker**
4. Error message : `Error: Cannot find module for page: /api/people/1`

## Expected behavior

Should work like on the dev server

## Screenshots

![image](https://user-images.githubusercontent.com/1516347/60877043-9a947180-a26f-11e9-9e99-2e04b8361866.png)

## System information

- OS: [Linux Mint 19.1 Cinnamon]
- Version of Next.js: [9.0.0]

**Comment by Timer** [comment] 2019-07-09 10:47
This was fixed in `next@canary`. Thanks for the report!

**Closed by Timer** 2019-07-09 10:47 UTC

**Comment by jerrynim** [comment] 2019-07-10 06:18
i had same issue, thanks for fix!!

**Comment by balazsorban44** [comment] 2022-01-31 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
