### ISSUE TITLE
nextjs 5 to 8 performance worse off

### ISSUE THREAD

**Issue by hammaduzair** [zeit/next.js#7683] opened 2019-06-27 06:14 UTC
We migrated from next 5 to 8 only to see that google page insight score has reduced from ~30 to ~20. Also on splitting common.js into minSize of 3kb to maxSize of 150kb the score was further reduced to 8.

Shouldn't the default webpack config for nextjs 8 have improved the score?

P.S - I posted this on spectrum forum as well as reddit, got no response

**Comment by ijjk** [comment] 2019-06-27 22:57
Did you change any other aspects of your app? This sounds inaccurate. Can you post additional details a link to a repo? A score of 30 seems like there are non-performant aspects to the application that aren't Next.js related.

**Comment by ijjk** [comment] 2019-06-28 00:28
Closing in favor of the spectrum thread [here](https://spectrum.chat/next-js/general/nextjs-5-to-8-performance-worse-off~6f223eb9-ca72-4758-9ca2-32e90c54bce8)

**Closed by ijjk** 2019-06-28 00:28 UTC

**Comment by balazsorban44** [comment] 2022-01-31 13:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
