### ISSUE TITLE
Network error with graphQL Apollo client

### ISSUE THREAD

**Issue by HadiAkmal** [zeit/next.js#1762] opened 2017-04-19 17:35 UTC
I can open page B from page A with `<Link>` and page B was successful in showing data taken from graphql. However when I refresh page B, I'm getting this error:

> Network error: request to https://api.graph.cool/simple/v1/cixmkt2ul01q00122mksg82pn failed, reason: write EPROTO 101057795:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:openssl\ssl\s23_clnt.c:769:

I already set up custom route in server.js but still having this problem with page B. Custom route does worked with other page with no graphql. That means I can refresh the page with no problem.

What cause this problem and how can I solve this? Thanks in advance.

**Comment by JustasPolis** [comment] 2017-04-19 19:14
Create a sample repo with an error and add it here, so it would be easy to reproduce and check what's wrong :).

**Comment by Goluis** [comment] 2017-04-20 00:05
It's maybe cause you're not sending the headers in server side so only the client works fine.
```js
// getInitialProps
const headers = ctx.req ? ctx.req.headers : {}
const client = initClient(headers)

// graphqlClient.js
function createClient (headers) {
  return new ApolloClient({
    ssrMode: !process.browser,
    dataIdFromObject: result => result.id || null,
    networkInterface: createNetworkInterface({
      uri: process.GRAPHQL_URL,
      opts: {
        credentials: 'same-origin',
        headers
      }
    })
  })
}

export const initClient = (headers) => {
  if (!process.browser) {
    return createClient(headers)
  }
  if (!apolloClient) {
    apolloClient = createClient(headers)
  }
  return apolloClient
}
```

**Comment by HadiAkmal** [comment] 2017-04-20 17:47
My project use redux with graphql. I use the example from https://github.com/zeit/next.js/tree/master/examples/with-apollo-and-redux to fix the problem. I now can refresh the page and get the graphql data.

Thanks all

**Comment by arunoda** [comment] 2017-05-02 19:30
I'm gonna close this since I hope this is fixed.

**Closed** 2017-05-06 21:54 UTC
