### ISSUE TITLE
NPM run dev not working at next@9.1.4 and apollo-redux example

### ISSUE THREAD

**Issue by Mehran91z** [zeit/next.js#9601] opened 2019-12-03 06:12 UTC
# NPM run dev throws an error

## Example name
**with-apollo-and-redux**

## Describe the bug
According to [this example repo](https://github.com/zeit/next.js/tree/canary/examples/with-apollo-and-redux), after using `npx` and `npm install`, cant run `npm run dev` and it throws this error:
`[ error ] ./node_modules/next/dist/client/dev/amp-dev.js
Error: [BABEL] ...\with-apollo-and-redux-app\node_modules\next\dist\client\dev\amp-dev.js: Cannot find module './src/data'`

`
Require stack:
...\with-apollo-and-redux-app\node_modules\core-js-compat\helpers.js`
`...\with-apollo-and-redux-app\node_modules\core-js-compat\get-modules-list-for-target-version.js`
`...\with-apollo-and-redux-app\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js`
`...\with-apollo-and-redux-app\node_modules\@babel\preset-env\lib\index.js`
`...\with-apollo-and-redux-app\node_modules\next\dist\build\babel\preset.js`
`...\with-apollo-and-redux-app\node_modules\next\dist\build\webpack\loaders\next-babel-loader.js`
`...\with-apollo-and-redux-app\node_modules\loader-runner\lib\loadLoader.js`
`...\with-apollo-and-redux-app\node_modules\loader-runner\lib\LoaderRunner.js`
`...\with-apollo-and-redux-app\node_modules\webpack\lib\NormalModule.js`
`...\with-apollo-and-redux-app\node_modules\webpack\lib\NormalModuleFactory.js`
`...\with-apollo-and-redux-app\node_modules\webpack\lib\Compiler.js`
`...\with-apollo-and-redux-app\node_modules\webpack\lib\webpack.js`
`...\with-apollo-and-redux-app\node_modules\next\dist\server\hot-reloader.js`
`...\with-apollo-and-redux-app\node_modules\next\dist\server\next-dev-server.js`
`...\with-apollo-and-redux-app\node_modules\next\dist\server\next.js`
`...\with-apollo-and-redux-app\node_modules\next\dist\server\lib\start-server.js`
`...\with-apollo-and-redux-app\node_modules\next\dist\cli\next-dev.js`
`...\with-apollo-and-redux-app\node_modules\next\dist\bin\next`

But in next@9.1.3 there is no issue and its working well.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run `npx create-next-app --example with-apollo-and-redux with-apollo-and-redux-app`
2. Run `cd with-apollo-and-redux-app`
3. Run `npm install`
4. Run `npm run dev`
5. The error shown in command prompt

## Expected behavior
npm dev running on http://localhost:3000 ....

## System information
- OS: Windows 10
- Version of Next.js: 9.1.4

**Comment by Timer** [comment] 2019-12-03 13:37
Duplicate of #9590. Please try again as the `core-js` publish has been fixed.
https://github.com/zloirock/core-js/issues/710

**Closed by Timer** 2019-12-03 13:37 UTC

**Comment by shubhzade** [comment] 2021-08-02 17:42
thanx bro

**Comment by balazsorban44** [comment] 2022-01-28 01:27
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
