### ISSUE TITLE
Build never exist after upgrading to canary.35 or 8.1.0

### ISSUE THREAD

**Issue by sarkistlt** [zeit/next.js#7088] opened 2019-04-19 17:49 UTC
After upgrading from 8.0.5-canary.34 to 35 or 8.1.0, build will never exit.
It does build, so if I will exit manually and export or start, everything works, but the issue is, after project was built and all pages are listed in cli, build doesn't exit automatically.

Can't provide code to replicate, because having this issue on production project that I can't share, any other projects work perfectly fine with 8.1.0.

Expected behavior:
- exit script after build completed

package.json
```json
    "@material-ui/core": "^3.9.3",
    "formik": "^1.5.0",
    "next-redux-wrapper": "^1.3.5",
    "next": "8.0.5-canary.34",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "redux": "^4.0.0",
    "react-redux": "^5.1.0",
    "@babel/cli": "^7.4.3",
    "@babel/core": "^7.4.3",
    "@babel/node": "^7.2.2",
    "@babel/plugin-proposal-export-default-from": "^7.2.0",
    "@babel/preset-flow": "^7.0.0",
```

next.config.js
```js
const defaultConfig = require('./config/default.json');
const stagingConfig = require('./config/staging.json');
const productionConfig = require('./config/production.json');

const { NODE_ENV } = process.env;
const extendConfig = NODE_ENV === 'production' ? productionConfig : NODE_ENV === 'staging' ? stagingConfig : {};

module.exports = {
  pageExtensions: ['jsx'],
  crossOrigin: 'anonymous',
  assetPrefix: extendConfig.CDN || '',
  generateBuildId: () => {
    const { version } = require('./package.json');
    return version;
  },
  env: {
    ...defaultConfig,
    ...extendConfig,
  },
};
```

.babelrc.js
```js
module.exports = {
  presets: [
    '@babel/preset-flow',
    'next/babel',
  ],
  plugins: [
    ['import', { libraryName: 'antd' }],
    '@babel/plugin-proposal-export-default-from',
    'add-module-exports',
  ],
};
```

**Comment by timneutkens** [comment] 2019-04-21 17:40
> Can't provide code to replicate, because having this issue on production project that I can't share, any other projects work perfectly fine with 8.1.0.

This makes it impossible for us to look into the issue. So I'll close the issue for now to not leave it open and never looked into.

**Closed by timneutkens** 2019-04-21 17:40 UTC

**Comment by chuyik** [comment] 2019-04-25 03:04
@sarkistlt @timneutkens 
I finally reproduced the problem, you should check if there's any `setInterval` code that runs on the top level, which blocks the build process to exit.
If so, make sure they only run on the client side but not SSR stage.

### reproduce code
```js
// pages/index.js
function Index () {
  return <div />
}

setInterval(() => console.log('this line blocks the build'), 500)

export default Index
```

## screenshot
![image](https://user-images.githubusercontent.com/6262943/56706946-7d103b00-6749-11e9-9154-7fbde63a695f.png)

**Comment by sarkistlt** [comment] 2019-04-25 04:17
@chuyik hm interesting, thanks for the update, unfortunately that's not the issue in my case. Will add more information after debugging.

**Comment by sarkistlt** [comment] 2019-04-25 04:32
@chuyik @timneutkens actually after updating to `8.1.1-canary.10` issue is fixed

**Comment by kachkaev** [comment] 2019-04-26 22:17
Similar issue here. `yarn build` fails after version `8.0.5-canary.35` (works for `8.0.5-canary.34`). What happens with `8.0.5-canary.35`,  `8.1.0` and `8.1.1-canary.0` is that a code in one of my app's TS files ends up being executed. It exits with non-zero, because a required env variable is missing. This may be to do with some AMP stuff, but I'm not sure.

For `next@8.1.1-canary.1` through `next@8.1.1-canary.4` the build script works again. Starting `next@8.1.1-canary.5`, I see a TypeScript error, which follows `Compiled successfully` and the list of pages. This can be to do with ongoing work to deprecate `@types/next` and `@zeit/next-typescript`.
