### ISSUE TITLE
Component doesn't invoke render method when router was changed by <Link> on production.

### ISSUE THREAD

**Issue by denny7** [zeit/next.js#9276] opened 2019-11-01 10:21 UTC
# Bug report

## Describe the bug

I use <Link> component for navigations in my Project. In development mode everything works fine but when I build for production I have a problem. When I navigate to some URL using `<Link>` it goes to that URL, component  invokes `getInitialProps` (client side) but not invokes `render` method after that. As a result I receive a blank screen. When I refresh the page component invokes `getInitialProps` (server side) and then `render` method as expected.

```
<Link href='/my-favorites'>
    <a>Favorites</a>
</Link>
```

I have my-favorites.js file in pages directory

## Expected behavior

Not receive blank screen when use `<Link>` component on production.

## System information

- OS: [macOS]
- Browser (if applies) [chrome]
- Version of Next.js: [9.1.2]

**Comment by timneutkens** [comment] 2019-11-01 10:36
The issue template asks for a clear and concise reproduction. We won't be able to help you based on the description you've provided.

**Comment by Timer** [comment] 2019-11-02 02:46
Closing until a reproduction is provided. Thanks!

**Closed by Timer** 2019-11-02 02:46 UTC

**Comment by balazsorban44** [comment] 2022-01-31 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
