### ISSUE TITLE
Allow to give name to routes and use them in Link

### ISSUE THREAD

**Issue by lcswillems** [zeit/next.js#8721] opened 2019-09-12 20:06 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I would like to be able to give names to routes and to use these names in the Link component, as it is already the case:
- in the Laravel framework for example (https://laravel.com/docs/5.8/routing#named-routes)
- in the Next-routes package (https://github.com/fridays/next-routes) but it is not maintained anymore.

## Describe alternatives you've considered

Currently, I define in my pages a `props` variable that is a dictionary containing the `path` of the page and the `name` of the page.

**Comment by timneutkens** [comment] 2019-09-13 10:47
This won't work with how the router works, you link to pages. We don't ship a routes manifest. And if we do had one adding this feature would make a routes manifest larger for no particular reason.

**Comment by Timer** [comment] 2019-10-18 05:40
Closing as described above. This just isn't how our router works, and probably never will (for size reasons). Thanks!

**Closed by Timer** 2019-10-18 05:40 UTC

**Comment by balazsorban44** [comment] 2022-01-31 02:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
