### ISSUE TITLE
Styles loaded after initial render in production mode using ant design with less

### ISSUE THREAD

**Issue by cfaure004** [zeit/next.js#8826] opened 2019-09-22 21:12 UTC
# Examples bug report

## Describe the bug

When using a complete copy of with-ant-design-less sample, styles are loaded after an initial page render when nextjs is built to production

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less
2. Clone the repository
3. Install dependencies and build in production mode
4. Start in production mode

## Expected behavior

Styles should be loaded before initial render

## Screenshots

![65225171-edd33d80-dac4-11e9-84d2-9d5f0fb7903d](https://user-images.githubusercontent.com/23209488/65394427-38d3a600-dd8e-11e9-8867-960666893757.gif)

## System information

- OS: macOS
- Browser (if applies) chrome
- Version of Next.js: latest

## Additional context

I tried to deploy using my nextjs app using now and same issue is happening.

**Comment by cfaure004** [comment] 2019-09-23 16:55
https://spectrum.chat/next-js/general/with-ant-design-less-style-flash-on-load~521fe7f8-1ba7-4da0-bf6e-6a81921ae9a5 

Overriding _app.js is a way to fix it !

**Comment by carlosbaraza** [comment] 2019-09-24 14:39
Not sure this would help, but I import Antd in the following way:

`styles/antd.less`:
```
@import "../../node_modules/antd/dist/antd.less";
@import "./antd-variables.less";
```

`next.config.js`:
```js
const withPlugins = require("next-compose-plugins");
const less = require("@zeit/next-less");

module.exports = withPlugins([
  [less, { lessLoaderOptions: { javascriptEnabled: true } }]
]);
```

**Comment by cfaure004** [comment] 2019-10-07 13:12
> https://spectrum.chat/next-js/general/with-ant-design-less-style-flash-on-load~521fe7f8-1ba7-4da0-bf6e-6a81921ae9a5
> 
> Overriding _app.js is a way to fix it !


No really working... For exemple, when i'm using Drawer from ant design, transition isn't working.

**Comment by LBC100** [comment] 2019-10-08 08:58
I am experiencing the same problem. Request a solution. help me

**Comment by LBC100** [comment] 2019-10-09 02:44
> 不确定这是否有帮助，但我可以通过以下方式导入Antd，而不会弄乱webpack配置：
> 
> `styles/antd.less`：
> 
> ```
> @import "../../node_modules/antd/dist/antd.less";
> @import "./antd-variables.less";
> ```
> 
> `next.config.js`：
> 
> ```js
> const  withPlugins  =  require（“ next-compose-plugins ”）;
> const  less  =  require（“ @ zeit / next-less ”）;
> 
> 模块。出口 =  withPlugins（[
>   [less，{lessLoaderOptions ： {javascriptEnabled ： true }}]
> ]）;
> ```
> 
> `_app.js`：
> 
> ```js
> 导入 “ ../styles/antd/antd.less ” ;
> 
> ...
> ```
> 
> 这似乎工作正常。

My latest experiment, doesn't work

**Comment by LBC100** [comment] 2019-10-15 03:38
> # Examples bug report
> ## Describe the bug
> When using a complete copy of with-ant-design-less sample, styles are loaded after an initial page render when nextjs is built to production
> 
> ## To Reproduce
> Steps to reproduce the behavior, please provide code snippets or a repository:
> 
> 1. Go to https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less
> 2. Clone the repository
> 3. Install dependencies and build in production mode
> 4. Start in production mode
> 
> ## Expected behavior
> Styles should be loaded before initial render
> 
> ## Screenshots
> ![65225171-edd33d80-dac4-11e9-84d2-9d5f0fb7903d](https://user-images.githubusercontent.com/23209488/65394427-38d3a600-dd8e-11e9-8867-960666893757.gif)
> 
> ## System information
> * OS: macOS
> * Browser (if applies) chrome
> * Version of Next.js: latest
> 
> ## Additional context
> I tried to deploy using my nextjs app using now and same issue is happening.

Has your problem been solved?

**Comment by cfaure004** [comment] 2019-10-15 06:13
I manage to find a temporary solution by not putting style element in Next.Js Head. I don't know why, but when putting style element in Head, it is working at initial render but when navigation between page using Link (from next/link), style element is happened again in the tree.

`
class MyApp extends App {

    render() {
        const { Component, pageProps } = this.props;

        return (
            <Layout className="custom-layout">
                {/* Fixes flash of unstyled content for first load, not in NextJs Head because causing issue */}
                <style
                    id='holderStyle'
                    dangerouslySetInnerHTML={{
                        __html: `
              *, *::before, *::after {
                transition: none!important;
              }
            `
                    }}
                />
                {/* Enf fixing flash unstyled content */}
                <Head>
                    {/* SEO */}
                    .....
                </Head>
                  <Component {...pageProps} />
            </Layout>
        );
    }
}

if (typeof window !== "undefined") {
    window.onload = () => {
        document.getElementById("holderStyle").remove();
    };
}


export default MyApp;
`

**Comment by MihaiWill** [comment] 2019-10-18 14:29
@cfaure004 is the solution still working for you? I tried but, the Antd still loads with a flash....

**Comment by cfaure004** [comment] 2019-10-19 08:04
> @cfaure004 is the solution still working for you? I tried but, the Antd still loads with a flash....

Yes it's working well using my previous comment !

**Comment by Timer** [comment] 2020-01-21 13:57
Duplicate of #9830

**Closed by Timer** 2020-01-21 13:57 UTC
Labels: good first issue, help wanted

**Comment by faizullah11** [comment] 2021-01-15 07:22
use  <script>0</script> after body in _documetn.js will fix this. with next.js 9.5.x.

**Comment by balazsorban44** [comment] 2022-01-28 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
