### ISSUE TITLE
Allow having an _app-like file for subpages 

### ISSUE THREAD

**Issue by ckastbjerg** [zeit/next.js#12933] opened 2020-05-15 15:28 UTC
# Feature request

First of all, thanks for building an awesome framework! :) 

## Is your feature request related to a problem? Please describe.

I have a use-case for which it would be nice to share layout (and persist state) across multiple subpages. Similar to what the [`_app`](https://nextjs.org/docs/advanced-features/custom-app) file allows for the entire application. In my specific case, I have a stateful sidebar component that I want to display on multiple subpages.

## Describe the solution you'd like

I was wondering if you've thought about supporting an `_app`-like file for subpages (e.g. named `_page`). I haven't considered any technical limitations or challenges that this might entail. But I was thinking about a folder structure like this:

- `some-page-folder`
  - `_page.tsx` (similar to `_app.tsx`)
  - `subpage.tsx` (automatically "wrapped" in `_page.tsx`)

## Describe alternatives you've considered

I've considered ditching next pages for this specific case, but I just like the simplicity of leveraging folder structure for pages. I've also considered modifying the `_app` file to accommodate my use-case, but that seems like a workaround to me.

Currently, I've added a `_page` in my own project which I then manually import for each subpage. It solves sharing the component. But it doesn't solve persisting state.

**Comment by timneutkens** [comment] 2020-05-25 12:17
Duplicate of #8193

**Closed by timneutkens** 2020-05-25 12:17 UTC

**Comment by balazsorban44** [comment] 2022-01-30 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
