### ISSUE TITLE
Support languages other than JS

### ISSUE THREAD

**Issue by cia48621793** [zeit/next.js#1454] opened 2017-03-18 07:33 UTC
Currently, the example 'with-typescript' is using an ugly 'concurrently' to run asynchronously with next.js.
I tried to modify the webpack loaders but no hope,  next.js required files be in filesystem/.next folder, not memory. Now I can't use my lovely CoffeeScript for API construction😖. I have to launch external project for that.

**Comment by timneutkens** [comment] 2017-03-18 07:47
Closing this as duplicate of https://github.com/zeit/next.js/issues/1245

**Closed by timneutkens** 2017-03-18 07:47 UTC
