### ISSUE TITLE
Page doesn't change if in subdirectory (e.g. ./pages/test/index.jsx)

### ISSUE THREAD

**Issue by nathfreder** [zeit/next.js#6292] opened 2019-02-13 18:17 UTC
# Bug report

## Describe the bug
Using `next/link` to visit a page inside a directory only changes the URL but doesn't load the page unless you reload the website.

```
.
├── index.jsx
└── test
    └── index.jsx (broken)
```
## To Reproduce
1. Create a page at `./pages/test/index.jsx` with the following contents
```jsx
export default () => <p>Test Page</p>
```
2. Create another page at `./pages/index.jsx` with the following contents
```jsx
import Link from 'next/link'

export default () => <Link href="/test">Go to Test</Link>
```
3. Visit `/test` in your browser
4. Notice that the page says *Test Page*
5. Visit `/`
6. Click *Go to Test*
7. Notice that the URL changed but the page didn't
8. Reload the website
9. Notice that the page is now `/test` again

## Expected behavior
The user should be sent to where they want to go without having to reload the page.

## Screenshots
![2019-02-13 13-58-27 2019-02-13 13_59_55](https://user-images.githubusercontent.com/40307305/52733014-02cc7900-2f98-11e9-9c81-a55bf2ebb82a.gif)

## System information
 - OS: macOS
 - Browser (if applies) Firefox Developer Edition 66.0b7
 - Version of Next.js: `^8.0.1`

**Comment by Timer** [comment] 2019-02-14 13:45
Closing as a duplicate of #6285, thanks!

**Closed by Timer** 2019-02-14 13:45 UTC
