### ISSUE TITLE
Resolver with promise doesn't work in api-routes-server-and-client-test on SSR

### ISSUE THREAD

**Issue by georgii-ivanov** [zeit/next.js#9241] opened 2019-10-30 00:44 UTC
Using next.js example [api-routes-apollo-server-and-client](https://github.com/zeit/next.js/tree/canary/examples/api-routes-apollo-server-and-client). When I'm trying to implement delay in `apollo/resolvers.js` this way:

```
export const resolvers = {
  Query: {
    viewer (_parent, _args, _context, _info) {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve({ id: 1, name: 'John Smith', status: 'cached' });
        }, 1000);
      })
    }
  }
}
```

[![enter image description here][1]][1]

This doesn't work in SSR. The data is empty in the SSR apollo state but user data expected `{ id: 1, name: 'John Smith', status: 'cached' }`.

I'm using that also with sequelize to fetch the data from database and it doesn't work too. I guess the reason is the same.

Maybe I'm doing something wrong.

Client-side part works fine (data are displayed after React hydratation).

If we're doing static object instead of Promise:

```
export const resolvers = {
  Query: {
    viewer (_parent, _args, _context, _info) {
      return { id: 1, name: 'John Smith', status: 'cached' };
    }
  }
}
```

Everything works fine and this puts object to initial state returned from SSR server with correct static markup...

[![enter image description here][2]][2]

**What am I expecting?**

I want just server render graphql requiest, finish promises, the put the data to apollo state for SSR and does the SSR for SEO purposes. Because for now if I connect to the database - it doesn't work at all (nothing's rendered. just empty page because rendering was interrupted by something).

  [1]: https://i.stack.imgur.com/Eziry.png
  [2]: https://i.stack.imgur.com/AXfV3.png

**Comment by azure-may** [comment] 2019-11-09 04:31
Hi georgii-ivanov,
Do I understand correctly that you only need to set a timer for your return value?  You may be able to use the setTimeout function without the promise:

export const resolvers = {
  Query: {
    viewer (_parent, _args, _context, _info) {
      setTimeout(() => {
          return { id: 1, name: 'John Smith', status: 'cached' };
        }, 1000);
      })
    }
  }

Or do you need the promise to wait for the data to be fetched before returning your resolve value?

**Comment by georgii-ivanov** [comment] 2019-11-11 00:34
@azure-may Yes. I need wait 1 second (blocking request) and then render the data

**Comment by azure-may** [comment] 2019-11-16 06:49
Hi @georgii-ivanov, I wasn't able to figure out how to return a promise from the Query, but I did find some useful resources that discuss SSR using Next.js and Apollo.  Perhaps they will be helpful: 
Next discussion board: https://spectrum.chat/next-js/general/next-js-with-apollo-react-hooks~2142b39e-90f1-4e3c-bd3e-8924c8781368
Code sandbox code sample: https://codesandbox.io/s/with-apollo-o221g?from-embed 
The second link demonstrates how to promisify the getInitialProps and getDataFromTree to initialize apollo.  
Best of luck!

**Comment by georgii-ivanov** [comment] 2019-11-25 05:21
@azure-may  In your example, we do fetches on localhost but using this example I mentioned we use apollo-link-schema instead which gives us don't run local fetches because it's supposed to have client/server on the same place.

**Comment by timneutkens** [comment] 2020-05-01 11:50
Going to close this issue as it hasn't had activity for a few months.

**Closed by timneutkens** 2020-05-01 11:50 UTC
Labels: Type: Example, good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-30 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
