### ISSUE TITLE
Webpack 4 support right now.. 

### ISSUE THREAD

**Issue by simonjoom** [zeit/next.js#4332] opened 2018-05-11 00:41 UTC
Here my work for webpack4 (i just did tested on browser only )

A little boilerplate using no babelified code of source nextJs inside with feature like hot-reload completely working with css,css and js

I changed a bit the core of nextjs to make all works .. i wait for any questions

https://github.com/simonjoom/NextJs4Reloaded

Please read
https://github.com/simonjoom/NextJs4Reloaded#feature-tested

**Comment by timneutkens** [comment] 2018-05-11 11:04
As said on twitter I wouldn't recommend using this since it removes a lot of features / is not tested. But we can sure copy a few things.

Either way there's no need for an extra issue.

Duplicate of #3923

Thanks for sharing 🙏

**Closed by timneutkens** 2018-05-11 11:04 UTC
