### ISSUE TITLE
[v8, FF] Navigation in development works in part only

### ISSUE THREAD

**Issue by haf** [zeit/next.js#7222] opened 2019-05-02 21:02 UTC
# Bug report

## Describe the bug
I've read through https://github.com/zeit/next.js/issues/5478 and I'm on v8 (^8.1.0 to be specific). I've added the same Router event listeners as in that thread:

<img width="1052" alt="Screenshot 2019-05-02 at 22 53 25" src="https://user-images.githubusercontent.com/193115/57106276-3a43f980-6d2d-11e9-9fe6-39233c8f0a80.png">

When clicking a link in Firefox, it does not always navigate. Even when force-reloading the page does it start navigating upon click. But as you can see, it does not always happen; some navigation events successfully navigate. The server reports no errors.

<img width="497" alt="Screenshot 2019-05-02 at 22 56 25" src="https://user-images.githubusercontent.com/193115/57106397-87c06680-6d2d-11e9-999f-24341c13dd1b.png">

It would seem Chromium always navigates, at least during my testing so far.

## To Reproduce

I'm afraid I don't have any steps to reproduce, as I've been able to work for three full work days in Firefox without experiencing the problem, with nextjs.

## Expected behavior
`Link`s should work in dev.

## System information
 - OS: macOS
 - Browser: Firefox 66.0.3 (64-bit)
 - Version of Next.js: 8.1.0

**Comment by timneutkens** [comment] 2019-05-03 08:56
I'm not sure what to do with this issue 😅 I guess it can be closed if there is no reproduction.

**Comment by haf** [comment] 2019-05-03 10:09
Just because you can't reproduce it doesn't mean it's not an issue, like the other thread taught us all. I guess one thing that could be done is increase logging verbosity around all the sites that have assumptions and expectations about how the hot reloading with chunks and pages works, and have me output those logs?

**Comment by timneutkens** [comment] 2019-05-03 10:37
> Just because you can't reproduce it doesn't mean it's not an issue

Without a reproduction this issue will just stay open forever though.

**Comment by haf** [comment] 2019-05-03 10:44
It reproduces consistently over here. Can I screenshare then?

**Comment by revskill10** [comment] 2019-05-03 12:34
@haf A reproduction doesn't mean only source code. It could be a guide how to, which clearly helps maintainers reproduce and eventually fix your issues.

**Comment by haf** [comment] 2019-05-03 15:36
@revskill10 I would if I could. I'm fully aware of what a repro is; sometimes the repro is at the "customer"'s machine, however. Am I do randomly code for three days until this error happens again, just so I have a repro without proprietary code in it? Right, I can't, but I have a repro that actually happens *every* time locally, so if we could do the magic you'd do on your local development machines, but remote, it's as good as a repro, IMO.

**Comment by huv1k** [comment] 2019-05-07 10:14
Could you please provide reproduction repo? And steps to follow? There is no other way how to debug issues like this. This would be super helpful 🙏

**Comment by Timer** [comment] 2019-07-18 13:09
This has gone multiple months without a reproduction. Closing issue.

**Closed by Timer** 2019-07-18 13:09 UTC
Labels: Can't Reproduce

**Comment by balazsorban44** [comment] 2022-01-31 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
