### ISSUE TITLE
Looks like date Objects are passed as strings when coming from getInitialProps

### ISSUE THREAD

**Issue by PookMook** [zeit/next.js#9352] opened 2019-11-08 16:56 UTC
# Bug report

## Describe the bug

When a date object is passed to a Page via getInititialProps, the SSR seems to be working as intended, but as soon as the .js is loaded, date objects are replaced by strings.

## To Reproduce

Made a dummy page to test this behavior specifically in a previous project https://github.com/MakeItHappenDev/raidCalendar/blob/master/pages/test.js
you can check it live here https://calendar.classicwowtools.com/test
Interesting things happen when you enable throttling and disable the cache, the SSR looks fine, but the client side switch the date object to a string 

## Expected behavior

Date object should stay date objects. I guess in most cases it's not a problem as you fetchData from an API in JSON already, but maybe people want to process everything server side for some reasons?

## Screenshots

https://youtu.be/Itf3ehNiy0s

## System information

- OS: Windows over WSL and now.sh
- Browser: firefox
- "next": "^9.0.2",

**Comment by kachkaev** [comment] 2019-11-08 16:58
> Date object should stay date objects. 

That's not possible, because Next.js does `JSON.stringify(initialPropsObtainedOnTheServer)`. The same applies to class instances and other non-serializable data.

**Comment by PookMook** [comment] 2019-11-08 17:14
So the best thing to do is just to re "datetify" in the component itself, it's just a minor disagreement I guess.
And to avoid any problem, JSON.stringify in the getInitialProps itself, so you can jungle object/string between SSR and client side

**Comment by kachkaev** [comment] 2019-11-08 17:19
Or you can just use unix time stamps in your initial props, which you later convert to date objects or other structures when needed.

**Comment by PookMook** [comment] 2019-11-08 18:16
Perfect, I'll deal with it this way then.
Maybe getInitialProps should also stringify props on the SSR for consistency's sake

**Comment by timneutkens** [comment] 2019-11-08 20:31
> Maybe getInitialProps should also stringify props on the SSR for consistency's sake

This unfortunately creates a large performance overhead hence why we don't do that in particular.

I'll close the issue as @kachkaev explained it well. getInitialProps is serialized to JSON.

**Closed by timneutkens** 2019-11-08 20:31 UTC

**Comment by hugejile** [comment] 2020-01-13 11:59
i have exactly same problem

**Comment by balazsorban44** [comment] 2022-01-30 16:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
