### ISSUE TITLE
next/error component cause high CPU

### ISSUE THREAD

**Issue by xifanii** [zeit/next.js#11944] opened 2020-04-16 10:48 UTC
# Bug report
next/error component cause high CPU

## Describe the bug
next/error component cause high CPU

## Expected behavior

//pages/temp.js
import React from 'react';
import Error from 'next/error';

export default () => ;

// use ab to request

ab -n 20000-c 20 http://xxx.test.com/temp

// result:

cpu high usage
blocking Request (response too long)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by timneutkens** [comment] 2020-04-16 11:38
Which version of Next.js are you using?

**Comment by Timer** [comment] 2020-04-22 04:23
This was fixed in Next.js 9.3.5 and newer. Please upgrade.

**Closed by Timer** 2020-04-22 04:23 UTC

**Comment by balazsorban44** [comment] 2022-01-30 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
