### ISSUE TITLE
The screen automatically zooms in when tapping on a material-ui TextField on ios devices

### ISSUE THREAD

**Issue by niloofarmzk** [zeit/next.js#7176] opened 2019-04-27 05:35 UTC
# Bug report

## Describe the bug
Since i have upgraded my project to next.js 8, when i tap on some of the TextFields, the screen suddenly zooms in. it only happens on ios devices. i downgraded my app to next.js 7 again just to be sure and the problem was solved.

## System information
 - OS: ios
 - Browser : all kinds
 - Version of Next.js: 8.0.4

**Comment by notrab** [comment] 2019-04-27 09:47
@niloofarmzk this is expected behaviour on iOS. It's possible the previous version was disabling scaling via a `meta` tag but if your font is less than `16px` it'll automatically zoom the field on focus.

**Comment by timneutkens** [comment] 2019-04-27 10:48
Next 8.0.4 includes a viewport meta tag by default. cc @developit

**Comment by niloofarmzk** [comment] 2019-04-27 11:29
> @niloofarmzk this is expected behaviour on iOS. It's possible the previous version was disabling scaling via a `meta` tag but if your font is less than `16px` it'll automatically zoom the field on focus.

Is there a way that we can disable scaling manually?

**Comment by notrab** [comment] 2019-04-27 14:51
@niloofarmzk You can but it's not recommended. `<meta name="viewport" content="width=device-width, user-scalable=no" />
`

**Comment by niloofarmzk** [comment] 2019-04-28 06:43
@notrab actually i have this meta tag in my _document.js file: `<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>` but it doesn't seem to be working.
is there a possibility that it is being overwritten by some other meta tag in next.js 8?

**Comment by MarchWorks** [comment] 2019-04-28 08:14
@niloofarmzk put the meta tag inside `_app`

**Comment by niloofarmzk** [comment] 2019-04-29 05:11
> @niloofarmzk put the meta tag inside `_app` here is why #6919

thanks!that worked.

**Comment by MarchWorks** [comment] 2019-04-30 12:07
@niloofarmzk you should close this if there is no problem

**Comment by huv1k** [comment] 2019-05-07 09:53
Thanks @MarchWorks, closing because resolved.

**Closed by huv1k** 2019-05-07 09:53 UTC
