### ISSUE TITLE
Links do not work in production but work in development

### ISSUE THREAD

**Issue by waqaar145** [zeit/next.js#9670] opened 2019-12-09 16:19 UTC
I have built a Next.js & Express.js application that works fine in development but in production there are few links in navigation bar and at some other places that do not work. And also after built I get some 404 like these. Here are few
```
https://example.com/_next/static/uskRfKy1t9bdwHxqyX7Ct/pages/question.js net::ERR_ABORTED 404 (Not Found)
GET https://example.com/_next/static/uskRfKy1t9bdwHxqyX7Ct/pages/profile.js net::ERR_ABORTED 404 (Not Found)
```

I have 3 links in navigation bar Home, Questions, Notifications. Home & Questions link do not work when I am on certain page, but Notification link do work from each page. I do not understand why this is happening.

`<Button className={classes.button}><Link href='/index' as="/"><a className={classes.link}>Home</a></Link></Button> <Button className={classes.button}><Link href='/questions' as="/questions"><a className={classes.link}>Questions</a></Link></Button> <Button className={classes.button}><Link href='/notifications'><a className={classes.link}>Notifications</a></Link></Button>`
I have tried different things to make it work but I could not succeed.
Everything works in development

Next.js - 9.1.4

**Comment by ijjk** [comment] 2019-12-09 19:45
Hi, can you provide additional details the above information makes it look like you are using `href` and `as` incorrectly on `next/link` which is causing Next.js to attempt to `prefetch` non-internal pages

**Comment by sharique-asghar** [comment] 2019-12-20 06:57
@waqaar145 Please provide some additional information like how and where you are importing `styles` which is common to each page and please check the developer tool's network panel and put the filter to JS and see which JS files are getting loaded at your `home page`. 

I faced somewhat similar issue in which from homepage i was unable to navigate to `campaigns page` but when i go to `admin page` and then tried to go to `campaigns page` then it worked.

So i found out that some styles.js was getting loaded in `admin page` which was needed by nextjs to render the `campaign page` which was utilising those styles.

So coming to the solution, i would say that do check these files getting loaded at your `home/index page` first before navigating to other pages:

<img width="370" alt="Screenshot 2019-12-20 at 12 23 13 PM" src="https://user-images.githubusercontent.com/54579474/71236011-cab66500-2323-11ea-997a-1a96a401c1d6.png">

I hope this would help.

**Comment by timneutkens** [comment] 2019-12-20 10:14
Going to close this as the issue template wasn't followed and there is no reproduction provided.

In the future please follow the issue template.

https://github.com/zeit/next.js/issues/new/choose

https://github.com/zeit/next.js/issues/new?template=8.Question_about_next.md

```
# Question about Next.js

GitHub Issues are reserved for Bug reports and Feature requests. The best place to get your question answered is to post it on https://spectrum.chat/next-js.
```

**Closed by timneutkens** 2019-12-20 10:14 UTC
Labels: Can't Reproduce

**Comment by digitalsanity** [comment] 2020-12-08 01:48
I had a similar issue here, and it was because my nginx SSL termination was using a final slash in proxy_pass.  After removing the final slash, everything was fine.  Lost 2-3 hours today tracking this down ..

**Comment by balazsorban44** [comment] 2022-01-29 01:24
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
