### ISSUE TITLE
Styles do not get applied from _document.js with getInitialProps are called

### ISSUE THREAD

**Issue by khrome83** [zeit/next.js#1035] opened 2017-02-08 13:36 UTC
As of next version `"next": "^2.0.0-beta.22"`

Whenever you use a `_document.js` fragment to overwrite the default construction of the page document, styles are not applied when `getInitialProps()` is used.

If you comment out `getInitialProps()`, then styles will be applied. They DO NOT however hot load, and require a page refresh. Change to use `<styled jsx global>` does not resolve issue.

Expected that `styled jsx` applies styles (global or not) regardless of the use of `getInitalProps()`. Also expected to hot load like any other page in the application.

```
import Document, { Head, Main, NextScript } from 'next/document'

export default class MyDocument extends Document {
  static async getInitialProps ({ renderPage }) {
    const page = renderPage()
    return { ...page }
  }

  render () {
    return (
      <html>
        <Head>
          <title>Site Title</title>
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
        <style jsx global>{`
          html, body {
            background-color: #f00;
            font-size: 16px;
            color: #fef;
          }
          p {
            color: red;
          }
        `}</style>
      </html>
    )
  }
}
```

**Comment by khrome83** [comment] 2017-02-08 13:39
Can validate that this occurs with `next@2.0.0-beta.24` as well.

**Comment by timneutkens** [comment] 2017-02-08 13:44
Duplicate of https://github.com/zeit/next.js/issues/885

**Closed by timneutkens** 2017-02-08 13:44 UTC

**Comment by khrome83** [comment] 2017-02-08 13:47
@timneutkens this is not a duplicate. 

These styles are not within the <head>. Additionally it is not just the missing hot reloading, these styles are NOT applied if `getInitialProps()` is called. This is definitely not a duplicate ticket. Please reopen.

**Comment by timneutkens** [comment] 2017-02-08 13:53
From Arunoda's reply on that ticket:
> Not exactly sure about how this happens.
But you should not styles like this with the custom document.
Whole purpose of the custom document should to customize your HTML page. Inside the custom layout, we don't have access to the React app.
So, try to move your styles to a common layout.
See this related discussion: #873 (comment)

From my reply on that ticket:
> `<style>{`.welcome { color: red; }`}</style>` will be global. Using just the `<style>` fixes your issue 👍 

The issue here is that you're using styled-jsx inside of `<Document />` also, `<Document />` is not hot reloaded by design afaik. The way to go here as Arunoda said is using a layout HOC: https://github.com/zeit/next.js/tree/master/examples/layout-component

**Comment by khrome83** [comment] 2017-02-08 13:56
Ok that makes sense. Thank you very much I understand now.

**Comment by timneutkens** [comment] 2017-02-08 13:57
Sorry for closing it without the actualy explanation 😅
