### ISSUE TITLE
next 9.3.5 context.req.url does not remove /_next/data/<hash> from path

### ISSUE THREAD

**Issue by pipja** [zeit/next.js#12267] opened 2020-04-28 06:02 UTC
# Bug report

## Describe the bug

context.req.url on 9.3.0 returns `<host>/<api>/<endpoint>`
context.req.url on 9.3.5 returns `<host>/_next/data/<hash>/<api>/<endpoint>`

## To Reproduce

Hit any page that should fire a data request to api endpoint inside a getServerSideProps function.
Have server do a console.log(context.req.url) and check server console the output.

## Expected behavior

On 9.3.0 environment: context.req.url inside getServerSideProps (context) should return `<host>/<api>/<endpoint>`
On 9.3.5 environment: context.req.url inside getServerSideProps (context) should return `<host>/<api>/<endpoint>`

## Screenshots

[9.3.0](https://imgur.com/qDSaQbj)

[9.3.5](https://imgur.com/izLhxA1)

## System information

- OS: Windows 10
- Version of Next.js: 9.3.0, 9.3.5
- Version of Node.js: 12.13.1

**Comment by timneutkens** [comment] 2020-04-28 08:46
Why are you reading `req.url` to begin with 🤔

**Comment by pipja** [comment] 2020-04-28 10:36
We have a very specific use-case due to legacy system reason:
- The front-end generate nice looking url something along the line of '/search/key1-value1/key2-value2/key3-value3/etc.' which will then need to be converted into key/value parameters in the form of 'search?key1=value1&key2=value2&key3=value3' which hit the API.
- req.url is used to read the nice url from the browser request and translate into parameterised key/value pairs and forwarded to the actual API.

We were also looking configuration options to bypass NextJS's API proxying altogether so we don't need to do this, but it seems like there is no such config and the only way is for us to write quite a lot of fetching code to bypass it ourselves.

**Comment by timneutkens** [comment] 2020-04-28 10:39
> The front-end generate nice looking url something along the line of '/search/key1-value1/key2-value2/key3-value3/etc.' which will then need to be converted into key/value parameters in the form of 'search?key1=value1&key2=value2&key3=value3' which hit the API.

> req.url is used to read the nice url from the browser request and translate into parameterised key/value pairs and forwarded to the actual API.

`params` holds the path from a dynamic path segment which should have you covered for this.


> We were also looking configuration options to bypass NextJS's API proxying altogether so we don't need to do this, but it seems like there is no such config and the only way is for us to write quite a lot of fetching code to bypass it ourselves.

I'm not sure what you're referring to 🤔

**Comment by pipja** [comment] 2020-04-28 10:41
> I'm not sure what you're referring to 🤔
Maybe it's more of an implementation issue on our end, so please ignore that bit :)

**Comment by jgpacker** [comment] 2020-04-30 03:18
I might have a similar case to @pipja 
While we can theorically use other parameters given by `getServerSideProps`, it's much easier to implement and test this kind of URL analysis and transformation based on the URL the end-user sees, instead of relying on (current path + [slug] + querystring).
This kind of analysis might seem overkill, but it can be specially helpful if you want to detect and transform older URL patterns as well as the new ones.

**Comment by timneutkens** [comment] 2020-05-25 12:50
You already know the prefix based on the page in the pages directory. I'm going to close this issue based on that it's asking to change an expected behavior that we're not planning to change as it would introduce bugs.

Feel free to open a discussion about your questions: https://github.com/zeit/next.js/discussions

**Closed by timneutkens** 2020-05-25 12:50 UTC

**Comment by balazsorban44** [comment] 2022-01-30 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
