### ISSUE TITLE
getInitialProps() missing from dynamic import

### ISSUE THREAD

**Issue by rscotten** [zeit/next.js#9857] opened 2019-12-28 02:06 UTC
# Bug report

## Describe the bug

When using `next/dynamic` for dynamic imports of a page-component that contains `getInitialProps`, the `getInitialProps` function from the imported dynamic component is missing.  

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```typescript
// src/modules/about.tsx

import React from "react";
import { NextPage, NextPageContext } from "next";

interface Props {
  userAgent?: string;
  test: string;
}

const About: NextPage<Props> = ({ userAgent, test }: NextPageContext) => {
  return (
    <p>User Agent: {userAgent}</p>
    <p>Test: {test}</p>
  );
};

About.getInitialProps = async ({ req }: NextPageContext) => {
  const userAgent = req ? req.headers["user-agent"] : navigator.userAgent;
  console.log('getInitialProps has run')
  return { userAgent, test: "can you see me?" };
};

export default About;
```

```typescript
// src/pages/about.ts

import dynamic from "next/dynamic";

const Page = dynamic(() => import(`../modules/about`));

export default Page;
```

The rendered page is missing the `userAgent` and `test` props, and there is no log of `getInitialProps` having run in the console.

## Expected behavior

The dynamically imported `Page` component contains `Page.getInitialProps` from `About.getInitialProps`;

## System information

- OS: macOS
- Browser: Chrome 79.0.3945.88
- Version of Next.js: 9.1.6

**Comment by rscotten** [comment] 2019-12-28 02:10
Just in case anyone is wondering, I know I can easily import this page normally (i.e. without using a dynamic import).  This is just a minimalist example of the problem.

**Comment by rscotten** [comment] 2019-12-28 02:12
In addition to a function component, I've also tried the class approach to creating the `About` component, and the problem persists.

**Comment by timneutkens** [comment] 2019-12-28 12:21
`dynamic()` does not return the component itself, it returns a component that has an "eventual" render of the component, and there is no way to copy over static properties reliably (and would cause inconsistency if we tried).

**Comment by timneutkens** [comment] 2019-12-28 12:22
Going to close this as it's not a bug and we're not planning to change the behavior.

**Closed by timneutkens** 2019-12-28 12:22 UTC

**Comment by rscotten** [comment] 2019-12-28 18:15
@timneutkens Thanks for the quick response.  

Is this documented anywhere?  I don't see it here: https://nextjs.org/docs/advanced-features/dynamic-import

I think it would save people some time if somebody added a short paragraph summarizing your answer. :)

**Comment by timneutkens** [comment] 2019-12-28 19:20
Feel free to send a PR! 🙏

**Comment by balazsorban44** [comment] 2022-01-30 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
