### ISSUE TITLE
Next.js bundle request 404s if no pages/index.js file is present

### ISSUE THREAD

**Issue by timteeling** [zeit/next.js#10372] opened 2020-01-31 20:48 UTC
# Bug report

## Describe the bug
If an app does not have an `index.js` file, `main-[hash].js` still requests its bundle on every page load in production mode (not dev mode). This results in a 404 to a bundle that doesn't exist.

I know this is kind of an odd use case... but hear me out. Some apps might decide not to have a page resolving to their root so that means no `pages/index.js` file.

This could happen if an app has to live at a subdirectory or if someone wants to redirect from their root URL elsewhere. We use Next with a custom server to route someone who comes to root and redirects them to a login page if they're unauthed or to their dashboard if they are authed.

## To Reproduce
Here's my reproduction: https://github.com/timteeling/nextjs-no-homepage. It tweaks `create-next-app` but it could be a custom server doing redirects instead of from next.config.js instead and result is the same.

1. Visit https://no-homepage.now.sh with your network tab open 
2. Site will redirect to `/about`
3. You'll see a 404 for https://no-homepage.now.sh/_next/static/KJ6xXlaQHHBoDlDQgw-lk/pages/index.js that was requested by https://no-homepage.now.sh/_next/static/runtime/main-495ccf74597393e741c8.js

I'm guessing the line in source in question is here:
https://github.com/zeit/next.js/blob/d04d9766986e3890a0ad66479b06e3fd00bbed6b/packages/next/client/page-loader.js#L147

## Expected behavior

`main-[hash].js` shouldn't make a request to a nonexistent bundle.

## Screenshots
<img width="1375" alt="Screen Shot 2020-01-31 at 3 18 25 PM" src="https://user-images.githubusercontent.com/1896786/73571619-ff4a3000-443c-11ea-91c4-ce587c48c2db.png">

## System information

- OS: macOS
- Browser (if applies): any
- Version of Next.js: 9.2

## Additional context
Not exactly sure the best way to address this as I haven't dug fully into `page-loader.js` to see what would happen if we changed `scriptRoute` to just:

```js
let scriptRoute = `${route}.js`
```

**Comment by ijjk** [comment] 2020-01-31 20:57
Hi, this is because you still have a link pointing to `/` or `pages/index.js`. When you have use `next/link` we automatically prefetch the page when the link is in the viewport to provide as fast client transition as possible unless you manually set `prefetch={false}` on the link.

<img width="1392" alt="Screen Shot 2020-01-31 at 14 54 56" src="https://user-images.githubusercontent.com/22380829/73573762-cbb9d680-4439-11ea-99a8-fa0b54a02b68.png">

I'm going to close this since it doesn't appear to be an issue and is working as expected. if you are still having trouble feel free to reply with additional details

**Closed by ijjk** 2020-01-31 20:57 UTC

**Comment by timteeling** [comment] 2020-01-31 21:03
@ijjk Thanks! I did not know that was happening with prefetching.

Interesting behavior though that the `<Link>` component doesn't do a check if a page does in fact exist. Is there some sort of list of pages output and stored in something like `NEXT_DATA` at build time you could check before trying to load a bundle for it?

**Comment by ijjk** [comment] 2020-01-31 21:08
We don't ship a list of every page in an application as this doesn't scale very well since the manifest we increase for each page. Instead we currently rely on the user to specify the page so that we know exactly what bundle we should be fetching.

We do have an issue open discussing making this more seamless for dynamic routes [here](https://github.com/zeit/next.js/issues/8207)

**Comment by balazsorban44** [comment] 2022-01-30 14:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
