### ISSUE TITLE
next/error title prop not documented and doesn't work

### ISSUE THREAD

**Issue by varna** [zeit/next.js#9234] opened 2019-10-29 10:51 UTC
# Bug report
Error page title prop is not documented and doesn't work.

## Describe the bug

Error page in source code has a prop `title`. Even if I provide this prop, title on output is not updated.

## To Reproduce

```js
import Error from 'next/error'

return <Error statusCode={status} title={statusText} />
```

## Expected behavior

I can see provided `statusText` on page and as tab name.

**Comment by danielr18** [comment] 2019-10-30 14:50
@varna I restarted the sandbox and server, and it's now working, were you using CodeSandbox by any chance?

**Comment by jamesmosier** [comment] 2019-11-09 01:22
I wasn't able to recreate this using Next version `9.1.1`. Is this still an issue for you @varna ?

**Comment by Timer** [comment] 2019-11-09 20:03
Closing as 2x users have said it's solved now, thanks!

**Closed by Timer** 2019-11-09 20:03 UTC
Labels: Type: Needs Investigation, good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-30 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
