### ISSUE TITLE
Add apiDir config option

### ISSUE THREAD

**Issue by cj** [zeit/next.js#8165] opened 2019-07-29 17:09 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Next.js v9.0.0 hard codes the root API directory path to `/pages/api`

Making this a config option would allow for a better separation of concerns.

We consider pages just that, pages, each one relates to a page you can visit, where as the API is the API an endpoint we consume. Because we are also connecting to a graphql backend to consume our data (which allows you to request everything in a single request) and since the release of serverless pre-rendering we are creating an endpoint for each of our pages to consume, i.e. api/pages/index etc... so right now that looks like /pages/api/pages/index, which gets confusing.

## Describe the solution you'd like

A config option to be able to specify the API direction path.

```js
const path = require('path')

module.exports = {
  apiDir: path.resolve(__dirname, 'api'),
}
```

## Describe alternatives you've considered

n/a

## Additional context

https://spectrum.chat/next-js/general/next-9-is-there-a-config-option-to-change-where-the-api-dir-is-located~81da11ce-cd38-4fb5-bcda-9e95ee07db14

**Comment by bugchecker** [comment] 2019-12-03 17:01
Another case: I'm trying to generate dynamic css through next api, but continue to use `/api` prefix for other (not next) REST server.

**Comment by timneutkens** [comment] 2020-01-02 21:33
Duplicate of #8123

**Closed by timneutkens** 2020-01-02 21:33 UTC
Labels: Type: Feature Request

**Comment by balazsorban44** [comment] 2022-01-30 17:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
