### ISSUE TITLE
Excessive chrome instances opening when `testonly` is run

### ISSUE THREAD

**Issue by mulholio** [zeit/next.js#6061] opened 2019-01-15 12:10 UTC
# Bug report

## Describe the bug

Running `testonly` crashes my computer due to the numerous (50+) Chrome instances it opens for testing.

## To Reproduce

1. Fork a fresh copy of next.js repo
2. Clone to local machine
3. `yarn` to install dependencies
4. `yarn run bootstrap` as state in contributing.md
5. `yarn testonly`
6. Tests run and open windows and gradually slow down my machine until it crashes and needs restarting.

## Expected behaviour
I am not entirely sure whether this is a bug that causes the issue or whether this is something that just needs a warning in contributing.md. I'm running a 2016 15" MacBook pro so hopefully this isn't an issue with not having enough specs.

## Screenshots
![chromes](https://user-images.githubusercontent.com/20966690/51179590-ee745e00-18bd-11e9-9347-d7b4e3a1f5fc.jpg)

## System information
 - OS: macOS 10.14.2
 - Version of Next.js: 7.0.2 (Canary as of 15th Jan)

**Comment by timneutkens** [comment] 2019-01-15 12:30
This is not a bug, our integration tests run `chromedriver` which interacts with chrome. As the contributing.md outlines you can run single tests: https://github.com/zeit/next.js/blob/canary/contributing.md#to-run-tests

Closing as duplicate of #5895

**Closed by timneutkens** 2019-01-15 12:30 UTC

**Comment by mulholio** [comment] 2019-01-15 12:49
Okay, worth putting a warning then? Save others crashing their computers too.
