### ISSUE TITLE
Trailing slashes does not do SSR + not working on page reload

### ISSUE THREAD

**Issue by CodeMiner84** [zeit/next.js#9118] opened 2019-10-17 19:53 UTC
# Bug report

## Describe the bug

Trailing slashes doesn't work. When I am clicking on links on my site everything is fine. All routes are ended with trailing slashes. Only problem is that those route doesn't work when I refresh page manually. Then I got 404 error. When I remove trailing slash - it works. So
`/about/` works when Im clicking from app on that route
`/about/` does not work when I enter this route manually or I refresh the page
`/about` works all the time

One more this. When Im on homepage and click on `/about` - it is ok, but on page view there is no SSR of content of my page. Only layout is generated, but the content of the does not exists.

Page content is appearing only when I remove trailing slash - then ssr is working.
I have this:
```javascipt
module.exports = {
  exportTrailingSlash: true,
}
```
in next.config.js

## Expected behavior

trailish slashes routes should work on refresh, also SSR should works also on trailish slashes routes

## System information

- OS: chrome
- Browser: chrome
- Version of Next.js: 9.1.1

**Comment by armspkt** [comment] 2019-10-30 04:02
I have the same issue when I deploy this on now.sh
then I tried this on firebase hosting , it works, I think it might happen with now.sh only.

**Comment by ajhool** [comment] 2019-11-01 02:32
Duplicate of #8913

**Closed** 2019-11-01 02:56 UTC

**Comment by balazsorban44** [comment] 2022-01-31 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
