### ISSUE TITLE
Switch to React 16 NOW

### ISSUE THREAD

**Issue by stevefan1999** [zeit/next.js#3000] opened 2017-09-27 00:59 UTC
Since the official React 16 package is released, It's time for Next.js 4.0 to roll out too!

Related PR: https://github.com/zeit/next.js/pull/2996

**Comment by MAPESO** [comment] 2017-09-27 04:16
@stevefan1999 They are likely already in development.
Note that **version 3.0** was released recently😄

**Comment by timneutkens** [comment] 2017-09-27 05:59
@stevefan1999 there's already 2 PRs ready to be checked and merged, also 2 issues. So I don't see the need for creating another. + we have an issue template which kindly asks you to check if the issue is already in the issue tracker 😄

**Closed by timneutkens** 2017-09-27 05:59 UTC
