### ISSUE TITLE
next build hangs forever after upgrade to v8

### ISSUE THREAD

**Issue by gugiserman** [zeit/next.js#7667] opened 2019-06-25 15:48 UTC
# Bug report

## Describe the bug
I've upgraded to Next.js 8 and noticed my `next build` (which is triggered by `yarn build`) leaves process hanging forever and doesn't exit it. So, my CI is timing out and we can't push the upgrade to production yet.

## To Reproduce
Simply running `next build`. Here's my current `next.config.js`:

```js
const webpack = require('webpack')
const path = require('path')
const package = require('./package.json')
const DotenvPlugin = require('dotenv-webpack')
const withProgressBar = require('next-progressbar')
const withOffline = require('next-offline')
const withCSS = require('@zeit/next-css')
const isProduction = process.env.NODE_ENV === 'production'

module.exports = withOffline(withCSS(withProgressBar({
  progressBar: {
    profile: true,
  },

  workboxOpts: {
    runtimeCaching: [
      {
        urlPattern: /^https?.*/,
        handler: 'networkFirst',
        options: {
          cacheName: 'name-v' + package.version,
          expiration: {
            maxEntries: 50,
            maxAgeSeconds: 7 * 24 * 60 * 60,
            purgeOnQuotaError: true,
          },
        },
      },
    ],
  },

  webpack: (config, { isServer }) => {
    config.plugins.push(new DotenvPlugin({
      systemvars: isProduction,
    }))

    if (!isServer) {
      config.module.rules.unshift({
        test: /\.worker\.js$/,
        use: [{
          loader: 'worker-loader',
          options: {
            inline: true,
          },
        }],
      })
    }

    /**
     * Hotfix for new webpack hot reload bug
     */
    if (!isServer) {
      config.output.globalObject = 'self'
    }

    return config
  },
})))
```

## Expected behavior
Process should exit after compilation is successful.

## Screenshots
<img width="561" alt="Screen Shot 2019-06-25 at 12 30 18" src="https://user-images.githubusercontent.com/4623123/60112853-f8d93480-9746-11e9-98ca-7278b545a087.png">

## System information

- OS: macOS Mojave 10.14.3 (but same thing occurs in CircleCI, which I believe runs some Linux distro)
- Browser (if applies): N/A
- Version of Next.js: ^8.1.0

## Additional context

Not many changes, I simply upgraded Next from v7 to v8. It also seems to have no warnings of peer dependencies compatibility issues. Everything else is running fine. If I `ctrl+C` the build process and run `yarn start`, everything is working just fine. Development server is working perfectly as well.

I found similar issues (https://github.com/zeit/next.js/issues/7567, https://github.com/zeit/next.js/issues/4647, https://github.com/zeit/next.js/issues/6419) suggesting to install `next-progressbar`, removing `node_modules`, `yarn.lock`, `package-lock.json`, `.next` directory etc. I did all of that but absolutely nothing changed this outcome.

Any thoughts? Thanks 😅

**Comment by Timer** [comment] 2019-06-25 19:04
Can you please try `next@canary`? I assume one of your pages is establishing a connection or similar and never allows the process to exit.

**Comment by gugiserman** [comment] 2019-06-25 21:40
> Can you please try `next@canary`? I assume one of your pages is establishing a connection or similar and never allows the process to exit.

Works (`^8.1.1-canary.57`)!

<img width="575" alt="Screen Shot 2019-06-25 at 18 39 17" src="https://user-images.githubusercontent.com/4623123/60135646-913bdd00-9778-11e9-8be6-43fc4327877d.png">

**Comment by jcurlier** [comment] 2019-06-26 03:32
+1

**Comment by Timer** [comment] 2019-06-26 12:02
Closing this because you said it works @gugiserman!

**Closed by Timer** 2019-06-26 12:02 UTC

**Comment by erikreyna** [comment] 2019-07-03 17:43
Updating to canary also fixed for me.

**Comment by keshav100** [comment] 2019-07-17 07:22
Same issue I am facing with firebase. Help me

**Comment by yosagar** [comment] 2019-07-19 17:22
Upgrading Next.js to latest `next@latest` solved my issue(Build bundling stuck for forever). 

NOTE: kindly avoid next@8.1.0. As I ran into build bundling stuck issue as wasted a week to figure out the issue.

**Comment by balazsorban44** [comment] 2022-01-31 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
