### ISSUE TITLE
Nextjs custom server typescript memory leak...

### ISSUE THREAD

**Issue by RayLuxembourg** [zeit/next.js#10461] opened 2020-02-08 09:19 UTC
# Bug report

## Describe the bug
memory leak.
On my server i have rest api that handles requests coming from getInitialProps.
The server sometimes uses apollo-fetch to get data from other api.
emotion js is used for styling.
That's mainly what the app does.
I am running another service with nodejs and have no issues at all.
I followed the examples but couldn't fix the memory leak.
While inspecting the memory leak, I could only see webpack strings growing.

## To Reproduce
Create custom server with typescript. 
Use apollo fetch 
Use emotion
Use mongoose
Use lru-cache

...

## Expected behavior
Stable service.
## Screenshots
[image](https://i.imgur.com/mo5uzQul.png)
## System information
google cloud kubernetes

**Comment by timneutkens** [comment] 2020-02-08 13:27
This issue is not actionable.

**Comment by RayLuxembourg** [comment] 2020-02-08 16:40
> This issue is not actionable from our side as no reproducible demo is provided.

I have no idea how to add complete reproduction . Shouldn’t there be documentation on how to avoid memory leaks on custom server ? Or cases?

**Comment by travis-joe** [comment] 2020-02-13 03:49
I facing this situation either, using ts run a custom server,  after 10 days or more, memory leak, cpu peaks, finally system broken.

**Comment by RayLuxembourg** [comment] 2020-02-13 09:22
I think that this is clear that, nextjs doesn't have clear guidelines on how to avoid memory leaks and do and don'ts.
It is not a normal nodejs application and it has to have specific guidelines on how to develop without memory leaks.

**Comment by kachkaev** [comment] 2020-02-13 09:27
Could it be just the growing size of [`lru-cache`](https://www.npmjs.com/package/lru-cache) rather than the memory leak? What if your storage settings are just very generous?

**Comment by Timer** [comment] 2020-02-14 20:56
Closing as low activity for a week. There is no special way to troubleshoot memory issues in a Next.js app versus normal Node apps.

**Closed by Timer** 2020-02-14 20:56 UTC
Labels: Please add a complete reproduction

**Comment by RayLuxembourg** [comment] 2020-02-26 11:55
> Could it be just the growing size of [`lru-cache`](https://www.npmjs.com/package/lru-cache) rather than the memory leak? What if your storage settings are just a bit too generous? One way or the other, I’m not sure how the maintainers can help given a rather vague problem definition and lack of reproduction example.
> 
> Debugging memory leaks in Next.js servers is no different to debugging leaks in Express or a plain node process. I’m not sure what guidance specific to Next.js could be written down.

I have tried to manage everything related to lru-cache but the app is still increasing in memory usage over time.
I seriously don't know what to do. Next.js doesn't offer any guidelines to avoid memory leaks.
It's an SSR react application there is lots of holes for memory leaks.
I am running my app in production for more then a year now.
I have 2k visitors per day, more than 20k pages. and around 40k requests per day.

Please share some documentation on what things can cause memory leaks in SSR nextjs application.
from styling, webpack,babel, to caching. 
![Screen Shot 2020-02-26 at 13 53 33](https://user-images.githubusercontent.com/15327989/75342666-886b5000-589f-11ea-94ab-fbca1f8b58ff.png)

**Comment by RayLuxembourg** [comment] 2020-02-27 01:19
It might have been the cache. Nice drop finally happened after few hours.
<img width="535" alt="Screen Shot 2020-02-27 at 3 18 06" src="https://user-images.githubusercontent.com/15327989/75403276-e5065380-590f-11ea-817c-49d48b983fd8.png">

**Comment by RayLuxembourg** [comment] 2020-03-03 22:34
Countless reports that next.js has memory leaks and all issues are closed without resolve.
<img width="1676" alt="Screen Shot 2020-03-04 at 0 03 57" src="https://user-images.githubusercontent.com/15327989/75826272-d2789800-5daf-11ea-9567-0d0f9c701c57.png">
<img width="356" alt="Screen Shot 2020-03-04 at 0 32 59" src="https://user-images.githubusercontent.com/15327989/75826281-d5738880-5daf-11ea-8e16-e76e61a902a0.png">

**Comment by madeinspace** [comment] 2020-04-21 22:42
I have the exact same problem, using azure and I get the same memory behaviour with a same type of graph you're showing. @RayLuxembourg  did you end up resolving this issue?

[
<img width="1076" alt="Screenshot 2020-04-22 08 39 13" src="https://user-images.githubusercontent.com/188750/79921218-20874f00-8475-11ea-9166-5484f72e67a2.png">
](url)

**Comment by Timer** [comment] 2020-04-21 22:53
This should be fixed in the latest version of Next.js. What version are you on?

**Comment by madeinspace** [comment] 2020-04-21 23:20
> This should be fixed in the latest version of Next.js. What version are you on?

great news! I'm on version 9.2.1

**Comment by Timer** [comment] 2020-04-22 02:51
Please upgrade to 9.3.5 or newer and let us know!

**Comment by madeinspace** [comment] 2020-04-26 23:15
@Timer Unfortunately reporting that the latest version didn't fix my memory leak issue. What has changed in that version that made you guys think this would be addressed? perhaps  overlooked something, my custom server is pretty simple though (https://github.com/madeinspace/EcoNext/blob/master/server.js)

**Comment by AlbericTrancart** [comment] 2020-04-29 07:58
Hello! Having the same issue than @madeinspace. Same type of memory behavior with Next on Azure. Updated to 9.3.5 but didn't fix it.
I will try to reproduce this in my local env but any reference to other issues might help.

**Comment by madeinspace** [comment] 2020-04-30 01:20
I'm using styled-components too and I'm seing there are some potential issues with this too, @AlbericTrancart are you using SC too?

**Comment by omeraplak** [comment] 2020-05-08 12:22
Hello,
Having the same issue. Updated to 9.3.6 but didn't fix it. We are also using typescript and styled component.

**Comment by elliottcrif** [comment] 2020-07-19 04:22
Hello haveing the same issue. @RayLuxembourg Have you figured out the issue?

**Comment by macrozone** [comment] 2020-08-04 09:12
@elliottcrif @RayLuxembourg did you guys try to update 9.5.x ? I had rarely seen out of memory problems in previous versions, but with 9.5.x it happens **very often**. So i am wondering if its also much worse for you on 9.5.x ?

**Comment by JulienKode** [comment] 2020-08-05 14:02
Hello I have the same issue, it is now fixed ?

**Comment by timdavish** [comment] 2020-08-12 16:09
@macrozone I have been experiencing `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory` server crashes in development at an increasing frequency, and I've recently updated to 9.5.x

It's at the point where it's *severely* impacting DX, needing to manually restart the app server every 5 minutes.

Adding `NODE_OPTIONS=\"--max-old-space-size=4096\"` in front of my start script seems to help for now..

**Comment by murilozilli** [comment] 2020-10-29 00:39
They probably dont want to help resolve this as they want you to use Vercel servers.

**Comment by kurtobando** [comment] 2021-06-10 15:52
Hello team,

I have the same behavior with my custom server 
![image](https://user-images.githubusercontent.com/38178537/121556472-7daddd80-ca46-11eb-9b53-c611d8ab0312.png)

```
const express = require("express")
const next = require("next")

const port = parseInt(process.env.PORT, 10) || 3000
const dev = process.env.NODE_ENV !== "production"
const app = next({ dev })
const handle = app.getRequestHandler()

app.prepare().then(() => {
    const server = express()

    server.all("*", (req, res) => {
        return handle(req, res)
    })

    server.listen(port, (err) => {
        if (err) throw err

        console.log(`> Ready on http://localhost:${port}`)
    })
})

```

At the moment, I am running in httpd with passenger. 

Any recommendation or experience for this behavior?

**Comment by RayLuxembourg** [comment] 2021-08-30 18:35
Update. I have dropped using nextjs as both frontend and backend and instead, I just use it to render React on the server-side.
I use nest.js as dedicated backend.

**Comment by timwaddell** [comment] 2021-09-15 13:57
We had some big memory issues and it turned out being express in front of nextjs
Hopefully this can help others if you have implemented similar?

**Comment by maidi29** [comment] 2021-11-09 15:40
@timwaddell  Did you manage to find out if the memory leak came from a certain implementation inside the custom server? We also experience memory issues on our production system using a custom server.

We are still investigating our issues  trying to localize the origin... We also tried to use version where the next handler was not called at all (next was not used, instead we served files from a local volume) and had no memory issues there, so the custom server itself does not have the issue, but somehow the retrival of the next pages. We use app.renderToHTML() to get the next pages. 

Any further information about memory issues in combination with a custom server would be useful to us

**Comment by macso-hwangoh** [comment] 2021-12-15 03:17
I have been experiencing the same error on Azure. I followed https://alberic.trancart.net/2020/05/how-fixed-first-memory-leak-nextjs-nodejs/ to recreate the memory leak locally as well.

Not only does this eventually cause a segmentation fault on my webapp but the same occurs for the default Next.js web app example suggested in https://nextjs.org/learn/basics/create-nextjs-app/setup:

`hwangoh@LAPTOP-C6317PJA:~/codes/nextjs-blog$ npm run dev

> @ dev /home/hwangoh/codes/nextjs-blog
> NODE_OPTIONS='--inspect' next dev

Debugger listening on ws://127.0.0.1:9229/d3348316-7a9d-4893-8eff-981acc66d243
For help, see: https://nodejs.org/en/docs/inspector
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 604 ms (158 modules)
Debugger attached.
wait  - compiling / (client and server)...
(node:22471) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 client/ listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit

(Use `node --trace-warnings ...` to show where the warning was created)
(node:22471) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 server/ listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
event - compiled client and server successfully in 517 ms (174 modules)
Segmentation fault
npm ERR! code ELIFECYCLE
npm ERR! errno 139
npm ERR! @ dev: `NODE_OPTIONS='--inspect' next dev`
npm ERR! Exit status 139
npm ERR!

npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hwangoh/.npm/_logs/2021-12-15T02_46_18_159Z-debug.log`

This error is easily reproducible. Simply use `npm run dev` on the example webapp and load the local server with 25 requests per second as instructed in the link https://alberic.trancart.net/2020/05/how-fixed-first-memory-leak-nextjs-nodejs/. However I should mention that Chrome inspect heap snapshots do not indicate a consistent increase in memory but eventually a segmentation fault will occur.

**Comment by balazsorban44** [comment] 2022-01-27 03:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
