### ISSUE TITLE
The inconsistency of Router between V1 and V2

### ISSUE THREAD

**Issue by Huxpro** [zeit/next.js#693] opened 2017-01-07 19:17 UTC
TL;DR. Next V2 will switch entire page instead of re-rendering current page when routeChange, which is inconsistent with Next V1.

I have elaborated this issue under <https://github.com/zeit/nextgram/issues/8>.

**Comment by arunoda** [comment] 2017-01-08 01:18
This is something we need to investigate.
I'll use nextgram for this.

**Comment by Huxpro** [comment] 2017-01-08 08:17
@arunoda Nice.

FWIW, I have forked a next@2.0.0 version of nextgram at <https://github.com/Huxpro/nextgram/tree/next-2.0>. Which have updated `package.json` and have migrated from `next/css` to `styled-jsx`, should reduce some time.

**Comment by arunoda** [comment] 2017-01-11 08:32
Okay. Here's what going on here. 
On nextgram it uses a `.push()` method of props. That API's was wrong and we re-wrote it.

By going through the nextgram, it seems like we need to bring back the functionality of that API again. But, I don't know whether it's a good idea to bring it back?

/ cc @rauchg @nkzawa 

Basically, here's what's happening in that API.

* We change the URL of the route via push state
* But it doesn't render the component assign to that URL
* But render the current component
* And pass query params of the current URL into that.

I smell bad for such an API.

Let's see how to fix this in a different way.

**Comment by arunoda** [comment] 2017-01-11 09:22
Okay, here next 2 style version of nextgram.

Live: https://nextgram-ivveyxguig.now.sh
Repo : https://github.com/arunoda/nextgram
PR: https://github.com/zeit/nextgram/pull/9

**Comment by nkzawa** [comment] 2017-01-11 09:39
@arunoda I think it should keep the original behavior which shows a modal over the list when you click a link, but doesn't show the list on SSR.

**Comment by arunoda** [comment] 2017-01-11 09:41
@nkzawa okay. That's possible. Let's do that.

**Comment by arunoda** [comment] 2017-01-11 10:09
Done.

**Comment by arunoda** [comment] 2017-01-11 10:16
@Huxpro could you send me a PR with the updated styled-jsx syntax.

**Comment by rauchg** [comment] 2017-01-11 19:52
@huxpro can you confirm the API now behaves as intended?

**Comment by nkzawa** [comment] 2017-01-13 06:46
Please check https://github.com/zeit/nextgram/pull/9

**Closed by nkzawa** 2017-01-13 06:46 UTC
Labels: Type: Bug

**Comment by Huxpro** [comment] 2017-01-13 21:07
@nkzawa @arunoda @rauchg 

Thx guys I found @nkzawa have updated `style-jsx` part. So basically @arunoda uses `push(url, as=url)` to achieve 'universal routing' without changing code in Next, kinda cheating on `<Page>` with a crafted url. How clever! Glad to see such flexibility.

so I just removed all react imports to make it more 'next smell' since react is a implementation details, and replaced imperatively router call to `<Link>`. Please check out <https://github.com/zeit/nextgram/pull/11>

BTW, I am still concerning about how to do nestedly or partially re-rendering between Page to Page in Next. Well, that is an enhancement and not related to this issue.

**Comment by rauchg** [comment] 2017-01-13 21:09
Yep `as` is one of the neatest things out there. Massive simplification

**Comment by arunoda** [comment] 2017-01-14 00:54
BTW: I need to thank @nkzawa for showing me this simplest solution. I was using a custom server, but it's not needed in this way.
