### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by hushino** [zeit/next.js#9442] opened 2019-11-18 02:38 UTC
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [git-amp-firt-example](https://github.com/zeit/next.js/tree/canary/examples/amp-first)
2. Run

## System information

- OS: Windows 10 update november 14
- Version of Next.js: 9.1 (npx create-next-app)
-Node.js: v12.13.0, v13
## Additional context

`<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7885D094F napi_wrap+124431
 2: 00007FF788572696 v8::base::CPU::has_sse+34502
 3: 00007FF788573356 v8::base::CPU::has_sse+37766
 4: 00007FF788D76F4E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF788D5EF91 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF788C2C85C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF788C37C00 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF788C34734 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF788C29FC3 v8::internal::Heap::CollectGarbage+1283
10: 00007FF788C2C9AA v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1770
11: 00007FF788C23053 v8::base::CPU::has_vfp3+467
12: 00007FF78851E73C v8::internal::wasm::SignatureMap::Freeze+120892
13: 00007FF78851D6E0 v8::internal::wasm::SignatureMap::Freeze+116704
14: 00007FF788619AAB uv_async_send+331
15: 00007FF78861924C uv_loop_init+1212
16: 00007FF788619414 uv_run+244
17: 00007FF78853B892 EVP_CIPHER_CTX_buf_noconst+30946
18: 00007FF788599263 node::Start+275
19: 00007FF78845666C RC4_options+339308
20: 00007FF789255D58 v8::internal::SetupIsolateDelegate::SetupHeap+1301368
21: 00007FF94D627BD4 BaseThreadInitThunk+20
22: 00007FF94D9ACED1 RtlUserThreadStart+33
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

With 4gb for node options, any code change result in the same error.

**Comment by jamesmosier** [comment] 2019-11-18 03:01
I was able to run this example without the above error. I think this is likely an issue specific to your machine. I'd instead search on Stackoverflow for possible solutions or maybe ask there.

**Comment by hushino** [comment] 2019-11-18 03:04
I run in two pc with same version of SO and node and gets the error.

**Comment by dan-turner** [comment] 2019-11-18 03:47
It is likely related to this:

https://github.com/zeit/next.js/issues/7929
https://github.com/zeit/now/issues/3307

Are you perhaps requesting a resource that does not exist (i.e. something that would normally be a 404)?  There seems to be a problem in the current version of now/next that in the scenario causes max CPU and memory leaks.

**Comment by ijjk** [comment] 2019-11-18 17:36
Hi, are you still encountering this on the latest `canary` of Next.js `v9.1.4-canary.8`? 

As mentioned above, I'm also not able to reproduce this on Windows 10 Pro (build 17763.864) or Mac OS X Mojave 10.14.6

**Comment by hushino** [comment] 2019-11-18 19:02
I switch to manjaro Linux and not have the problem with same files, but I can confirm the issue is related to

**Comment by ijjk** [comment] 2019-11-18 22:24
Closing in favor of https://github.com/zeit/now/issues/3307 as mentioned above

**Closed by ijjk** 2019-11-18 22:24 UTC
Labels: Can't Reproduce

**Comment by vocoWone** [comment] 2020-04-14 03:51
I have the same issu, my reason is that there are too many routes, just reduce the route.

**Comment by paritosh-34** [comment] 2020-08-10 07:57
In my case, it was a pretty stupid mistake.
I had this layout component which sets the header and sidebar component and returns with its children in the main section.
I don't know what happened but I called the layout component inside the layout component resulting in a recursive layout call which hanged my laptop 3 times :p

(Just wanted to add that for beginners...)

**Comment by romeerez** [comment] 2020-10-01 23:26
> I switch to manjaro Linux and not have the problem with same files, but I can confirm this issue is related to [issues zeit 3307](https://github.com/zeit/now/issues/3307) .
> Can close this.

I'm running manjaro Linux too, high five!
But seeing this issue

**Comment by ceessay** [comment] 2020-12-17 11:20
In my case I had to remove this line `  target: "serverless",` from my `next.conf.js` file

```
const withCSS = require("@zeit/next-css");

module.exports = withCSS({
  target: "serverless", // <== removed this line
  webpack: function (config) {
    config.module.rules.push({
      test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
      use: {
        loader: "url-loader",
        options: {
          limit: 100000,
          name: "[name].[ext]",
        },
      },
    });
    return config;
  },
});
```

Don't know what it implies yet as a beginner in react/nextjs

**Comment by nandorojo** [comment] 2021-01-11 00:36
I get this running `next build` on next 10, anyone else figured that out?

**Comment by ollydixon** [comment] 2021-01-15 11:51
Anyone find a solution for this? We see this error through our Docker Configurations, only with NextJS, one of the worse frameworks we've ever dealt with for deployment...

**Comment by dark-swordsman** [comment] 2021-04-20 01:38
> I had this layout component which sets the header and sidebar component and returns with its children in the main section.

Yep, same exact thing here. I wanted to make a custom `Head` component so I can simplify the top of my pages. It was as follows:

```jsx
import Head from 'next/head';

function Head({ title }) {
  return (
    <Head>
      <title>{title}</title>
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}

export default Head;
```

I'm sure you can see the issue, lol. Just renaming it to something else worked.

I did try to also do `import * as NextHead from 'next/head';` but that didn't seem to work. Though, not a big deal.

**Comment by RacketyWater7** [comment] 2021-06-25 07:45
> > I had this layout component which sets the header and sidebar component and returns with its children in the main section.
> 
> Yep, same exact thing here. I wanted to make a custom `Head` component so I can simplify the top of my pages. That way a simple `<Head title={} />` would do the trick. It was as follows:
> 
> ```js
> import Head from 'next/head';
> 
> function Head({ title }) {
>   return (
>     <Head>
>       <title>{title}</title>
>       <link rel="icon" href="/favicon.ico" />
>     </Head>
>   );
> }
> 
> export default Head;
> ```
> 
> I'm sure you can see the issue, lol. Just renaming it to something else like `CustomHead` worked.
> 
> I did try to also do `import * as NextHead from 'next/head';` but that didn't seem to work. Though, not a big deal.

Thanks a lot. Mine was the same problem. And it resolved it. Thankyouuuuuu

**Comment by NKANGIJAFARI** [comment] 2021-07-30 18:08
I faced the same issue, updated my node version to 14, it stayed just to back to read my code and realised i was naming the functional component Card, and also the return being Card yet not imported from reactstrap, so it was doing a recursive.

**Comment by tigerabrodi** [comment] 2021-10-19 05:12
> I faced the same issue, updated my node version to 14, it stayed just to back to read my code and realised i was naming the functional component Card, and also the return being Card yet not imported from reactstrap, so it was doing a recursive.

@NKANGIJAFARI Yes! Exactly this happened to me, or something similar, the pages' name was the same as one of its inner component :weary: 

Finally solved this :smile: 

Appreciated! :revolving_hearts:
