### ISSUE TITLE
Automatic checks against circular module dependencies

### ISSUE THREAD

**Issue by kachkaev** [zeit/next.js#9461] opened 2019-11-19 15:56 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Last week, we faced a pretty odd bug in one of our Next.js apps, which took quite some time to investigate. As it turned out, the problem occurred because of circular module dependencies, but this was quite hard to figure out. When you have a circular dependency, certain imports become undefined on module init and this has a high potential of breaking things.

## Describe the solution you'd like

Ideally, I would like Next.js to track circular dependencies and show developers a helpful error message if there are any. Perhaps, this could even be a default behaviour as I can't imagine a healthy project where circular dependencies would be justified. A just-migrated legacy codebase could be the only exception, maybe.

## Describe alternatives you've considered

I used to use webpack's [circular-dependency-plugin](https://www.npmjs.com/package/circular-dependency-plugin) back in the day. Seems like it works in a Next.js project too – here's my integration:

```
yarn add -D circular-dependency-plugin
```

```js
// next.config.js
module.exports = require("next-compose-plugins")([
  require("@next/bundle-analyzer")({ enabled: process.env.ANALYZE === "true" }),
  require("@zeit/next-source-maps")(),
  // require("a-bunch-of-other-plugins")(),
  (nextConfig) => ({
    ...nextConfig,
    webpack: (config, options) => {
      if (!options.isServer) {
        const CircularDependencyPlugin = require("circular-dependency-plugin")
        config.plugins.push(
          new CircularDependencyPlugin({
            exclude: /node_modules/,
            failOnError: true,
            allowAsyncCycles: false,
            cwd: process.cwd(),
          }),
        )
      }
      if (typeof nextConfig.webpack === "function") {
        return nextConfig.webpack(config, options)
      }
      return config
    },
  }),
])
```

I know that the detection of circular dependencies can be turned into a [Next.js plugin](https://github.com/zeit/next-plugins), but believe there’s value in adding this check to the Next.js core. We can start with an option like `{ future: { reportCircularDependencies: true }}`, which would become default one day.

If there are strong reasons why `circular-dependency-plugin` should not become a part of the framework's core, I'm OK with implementing the plugin as a fallback. The only thing that I'm worried about is that my poor knowledge of Next.js internals may lead to a wrong set of `circular-dependency-plugin` options, so they won't do the right job in some apps.

WDYT folks?

**Comment by timneutkens** [comment] 2019-11-19 18:48
Might be nice, but I don't want to add extra webpack plugins right now. We can have a look into this eventually.

**Comment by Timer** [comment] 2019-11-20 18:22
Circular dependencies are tough, because they are permitted per spec.
ES Modules have live bindings, so this should work except in a few edge cases where the computation of each variable depends on the other.

**Comment by kachkaev** [comment] 2019-11-21 17:08
I did not know circular dependencies are enabled by the spec, but I used to contribute to working codebases, which did have circular deps. The problem they bring is that the code becomes fragile so a subtle change in one file can unpredictably start breaking things in totally different corner of the app. Showcasing app's components in additional tools like [docz](https://github.com/doczjs/docz) can also make them behave differently. What is the most painful about circular deps in my experience is that they may cause exceptions in production build while the dev app works just fine (probably because of HMR). My arms just covered with goosebumps when I remembered how I was debugging that 😅

Next.js is an opinionated framework, the goal of which is to keep devs in the [pit of success](https://blog.codinghorror.com/falling-into-the-pit-of-success/). Checking apps against circular deps by default looks to me like a feature that is fully aligned with this philosophy. If someone prefers to have circular deps and knows what they're doing, they can turn the check off just as `{ typescript: { ignoreDevErrors: true }}`.

**Comment by timneutkens** [comment] 2020-01-03 00:46
It's really tricky to do this check as it ties into resolving and can significantly slow down the compilation process whereas we want to improve performance in development / during builds. Hence why I'm going to close this PR for now. Might investigate sometime in the future.

**Closed by timneutkens** 2020-01-03 00:46 UTC

**Comment by balazsorban44** [comment] 2022-01-30 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
