### ISSUE TITLE
Font Flashing

### ISSUE THREAD

**Issue by kennetpostigo** [zeit/next.js#3270] opened 2017-11-12 06:43 UTC
I've been trying to setup fonts with next.js and I got them working by putting the font files in `static`, using them in an `index.css`, and then using `<Link />` in the `<Head />` to bring them in. However when running next.js in production settings I get a "font flash" every time I navigate to a different page the text on the screen will be rendered in the default browser font and then rerender in the font I use in the `index.css` causing a flash. Anyone got any clues on how to stop the flashing from happening?

## Expected Behavior
Fonts and index.css loaded once and ready to use prior to page rendering, so that no flashing occurs on initial page load and navigating between pages.

## Current Behavior
Initial Page load text flashes between fonts and navigating between pages flashing continues to occur, even when navigating to pages that have already been visited. Fonts and all static content is loaded again every time you navigate between pages. 

## Steps to Reproduce (for bugs)
1. Grab some font files
2. Put them in static
3. create a index.css file and set some elements to use that font
4. `<Link />` to it in `<Head />` from a Page component that will render routes/views as children

## Context
I'm trying to use fonts

## Your Environment

| Tech    | Version |
|---------|------------|
| next       |     4.1.4      |
| node      |    8.9.1       |
| os          |     osx         |
| browser |     chrome |

**Comment by liweinan0423** [comment] 2017-11-14 12:32
1. ensure you are using html `<link />` element but not a `<Link />` component.
2. ensure the server generated HTML has the `<link />` in the `<head />` element.

If all the above conditioned is met, I guess you are using Chrome and encountering a bug of Chrome network speed API. There is a feature that when detecting slow network, Chrome will render system default font to avoid web page from being blocked by the font resources.

You can refer to https://stackoverflow.com/questions/42342133/slow-network-is-detected-fallback-font-will-be-used-while-loading-angular-app

**Comment by timneutkens** [comment] 2017-11-16 10:29
This is caused by Next re-rendering the page on page change. Trying using `<style jsx global>` to set the font-face. This works really well in an app I'm building 👍 I'm going to close this since it's not something we can fix in the short term. But there's issues about the re-rendering of the whole page 👍

**Closed** 2017-11-16 10:29 UTC
