### ISSUE TITLE
Build fails when importing Firestore and using target serverless

### ISSUE THREAD

**Issue by ferezoz** [zeit/next.js#8797] opened 2019-09-19 06:45 UTC
# Bug report

## Describe the bug

Build fails when importing `Firestore` and using `target: 'serverless'` even after upgrading `next` to at least version 9.0.4 as mentioned here: https://github.com/zeit/next.js/issues/6073#issuecomment-467589586.

`Module not found: Can't resolve 'memcpy' in '.../node_modules/bytebuffer/dist'`

## To Reproduce

1. package.json:
```js
"dependencies": {
    "firebase": "^6.5.0",
    "next": "^9.0.5",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
```
2. firebase.js:
```js
import firebase from 'firebase/app';
import 'firebase/firestore';

const config = {
  ...
};

const firebaseApp = !firebase.apps.length
  ? firebase.initializeApp(config)
  : firebase.app();

const firestore = firebaseApp.firestore();

export default firebaseApp;

export { firestore };
```
3. next.config.js:
```js
module.exports = {
  target: 'serverless',
};
```

## Expected behavior

Build should succeed.

## Screenshots

![image](https://user-images.githubusercontent.com/12140600/65217834-bf307500-da7a-11e9-9032-9a2d0042fcbd.png)

## System information

- Version of Next.js: 9.0.5
- Version of firebase: 6.5.0

## Additional context

It works on local `next dev`.

**Comment by timneutkens** [comment] 2019-09-21 08:50
This is fixed through the `experimental-serverless-trace` right @Timer?

**Comment by Timer** [comment] 2019-09-21 12:50
Yes, setting `target: 'experimental-serverless-trace'` should fix this issue. 

FYI: @ferezoz due to the way Firebase is designed, it's not compatible with `target: 'serverless'` -- we introduced a new mode to fix this (`experimental-serverless-trace`)!

**Comment by Timer** [comment] 2019-09-21 12:50
We should look at de-experimentalizing this (because it's no longer experimental).

**Comment by ferezoz** [comment] 2019-09-21 21:28
@Timer Thank you it worked!
Whats the difference between `experimental-serverless-trace` and `serverless`? Because I see the build emits lambdas as well. Should I need to consider something?

**Comment by Timer** [comment] 2019-09-22 01:08
The difference is that `serverless` bundles `node_modules` and `experimental-serverless-trace` does not!

Bundling `node_modules` is very problematic for server-side code, as it may rely on compiled binaries (like gRPC for Firestore) or reading certain files from the file-system (`fs.readFileSync()`).
Bundling these modules means the files they're looking for no longer exist -- so it's generally not safe to do so.

This problem doesn't exist for client-side code because there's no concept of external files in the browser.

All things considered (ready-to-go `.zip` lambdas), `experimental-serverless-trace` output size should be identical or slightly smaller than a functioning-equivalent `serverless` output.

----

> Should I need to consider something?

If you're deploying to ZEIT Now: Nope! We automatically handle and optimize lambda size for you.

If you're self-hosting via `next start`: Don't delete the `node_modules` folder! It'll be required by your lambdas.

**Comment by ferezoz** [comment] 2019-09-23 02:23
Thank you for the explanation! 🙂 I'm using ZEIT Now so I don't need anything else.
The issue is fixed for me, should I close the ticket or maybe you want it open to track the de-experimentalization?

**Comment by timneutkens** [comment] 2019-09-23 07:46
This is tracked somewhere else right now, so let's close this issue 👍

**Closed by timneutkens** 2019-09-23 07:46 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 01:26
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
