### ISSUE TITLE
I don't known what happed, many link tag create in client side

### ISSUE THREAD

**Issue by Random-Wang** [zeit/next.js#9481] opened 2019-11-21 08:26 UTC
# Question about Next.js

GitHub Issues are reserved for Bug reports and Feature requests. The best place to get your question answered is to post it on https://spectrum.chat/next-js.
```html
<head>
  <meta
    name="viewport"
    content="width=device-width,minimum-scale=1,initial-scale=1"
  />
  <meta charset="utf-8" />
  <link rel="icon" href="/static/favicon.ico" />
  <link rel="stylesheet" href="/static/font/iconfont.css" />
  <script src="/static/script/hm.js"></script>
  <meta
    name="viewport"
    content="width=device-width,minimum-scale=1,initial-scale=1"
  />
  <meta name="next-head-count" content="5" />
  <style data-styled="" data-styled-version="4.4.0"></style>
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/article/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/label/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/label/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/article/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/article/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/label/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/label/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/article/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/article/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/label/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/label/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/label/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/article/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/article/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/label/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/label/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/article/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/article/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/label/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/label/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/article/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/article/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/label/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/label/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/article/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/article/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/label/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/label/%5Bid%5D.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/bFgJrOScjbsI_tgs7wvCL/pages/article/%5Bid%5D.js"
    as="script"
  />
</head>

```

**Comment by ijjk** [comment] 2019-11-21 19:24
Hi, these are added automatically by Next.js when a link to one of those pages is visible in the viewport. 

Closing since it's not an issue

**Closed by ijjk** 2019-11-21 19:24 UTC

**Comment by Random-Wang** [comment] 2019-11-22 04:42
if I don't wont this, haw can I do.
Because it makes the document look less beautiful,and is repeat.
And also traffic costs money.
I need to turn it off when money is more important than experience

**Comment by Random-Wang** [comment] 2019-11-22 04:43
It would be better if it were configurable

**Comment by timneutkens** [comment] 2019-11-22 09:30
https://nextjs.org/docs#prefetching-pages

**Comment by balazsorban44** [comment] 2022-01-30 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
