### ISSUE TITLE
with-ant-design-less can't work together with cssModule

### ISSUE THREAD

**Issue by phakphumi** [zeit/next.js#8156] opened 2019-07-29 09:42 UTC
# Examples bug report

## Example name

[with-ant-design-less](https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less)

## Describe the bug

Using ant-design-less with cssModule makes all ant design style disappear.

## To Reproduce

1. Go to 'next.config.js'
2. Add this code snippets into withLess option
```
cssModules: true,
cssLoaderOptions: {
  importLoaders: 1,
  localIdentName: '[local]___[hash:base64:5]',
},
```
3. Save
4. All ant design style is gone

## Expected behavior

The example should apply ant design style when cssModule option is set to true.

## Screenshots

**Before apply cssModule**
<img width="1280" alt="Screen Shot 2562-07-29 at 16 35 22" src="https://user-images.githubusercontent.com/10301881/62038030-29692e00-b21f-11e9-8ec7-636ffed39abf.png">

**After apply cssModule**
<img width="1280" alt="Screen Shot 2562-07-29 at 16 36 41" src="https://user-images.githubusercontent.com/10301881/62038034-2a9a5b00-b21f-11e9-96e0-951e4db6e40d.png">

## System information

- OS: macOS
- Browser: Any browser
- Version of Next.js: 9.0.2

**Comment by phakphumi** [comment] 2019-07-29 14:15
After taking the time to research I found that setting cssModule to `true` turn the whole project to use cssModule but some node_modules like `antd` doesn't implement by using cssModule.

So, I customized @zeit/next-less to support work like this.

next-antd-less.config.js
```
var cssLoaderConfig = require('@zeit/next-css/css-loader-config');

module.exports = (nextConfig = {}) => {
  return Object.assign({}, nextConfig, {
    webpack: (config, options) => {
      if (!options.defaultLoaders) {
        throw new Error(
          'This plugin is not compatible with Next.js versions below 5.0.0 https://err.sh/next-plugins/upgrade'
        );
      }

      const { dev, isServer } = options;
      const {
        cssModules,
        cssLoaderOptions,
        postcssLoaderOptions,
        lessLoaderOptions = {},
      } = nextConfig;

      options.defaultLoaders.less = cssLoaderConfig(config, {
        extensions: ['less'],
        cssModules,
        cssLoaderOptions,
        postcssLoaderOptions,
        dev,
        isServer,
        loaders: [
          {
            loader: 'less-loader',
            options: lessLoaderOptions,
          },
        ],
      });

      config.module.rules.push({
        test: /\.less$/,
        exclude: /node_modules/,
        use: options.defaultLoaders.less,
      });

      // disable antd css module
      config.module.rules.push({
        test: /\.less$/,
        include: /node_modules/,
        use: cssLoaderConfig(config, {
          extensions: ['less'],
          cssModules: false,
          cssLoaderOptions: {},
          dev,
          isServer,
          loaders: [
            {
              loader: 'less-loader',
              options: lessLoaderOptions,
            },
          ],
        }),
      });

      if (isServer) {
        const antStyles = /antd\/.*?\/style.*?/;
        const origExternals = [...config.externals];
        config.externals = [
          (context, request, callback) => {
            if (request.match(antStyles)) return callback();
            if (typeof origExternals[0] === 'function') {
              origExternals[0](context, request, callback);
            } else {
              callback();
            }
          },
          ...(typeof origExternals[0] === 'function' ? [] : origExternals),
        ];
  
        config.module.rules.unshift({
          test: antStyles,
          use: 'null-loader',
        });
      }

      if (typeof nextConfig.webpack === 'function') {
        return nextConfig.webpack(config, options);
      }

      return config;
    }
  });
};
```

then use it in next.config.js
```
const withNextAntdLess = require('./next-antd-less.config');
module.exports = withNextAntdLess({
    cssModules: true,
    cssLoaderOptions: {
      importLoaders: 1,
      localIdentName: '[local]___[hash:base64:5]',
    },
})
```

In my case, it usually works. Hopefully, It will help someone to solve the problem to work with antd together with cssModule.

Related example/issues/modules which I use to compose the solution. #8054 #7957 [with-ant-design-less](https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less) [next-antd-aza-less](https://github.com/sdli/next-antd-aza-less)

Anyway, if there is an official solution for this issue it will be very good. In my opinion, it will be a common issue.

**Comment by peterhung101** [comment] 2019-08-05 07:08
Thanks for sharing! Your code build fine for me too except that it showed the following error when I actually added my own .css file

![圖片](https://user-images.githubusercontent.com/29172282/62445110-0e07a100-b792-11e9-8818-ec8389fb6278.png)

I need to add the following to the above next-antd-less.config.js to make it work:
`            ......
                        options: lessLoaderOptions,
                    },
                ],
            });

             **config.module.rules.push({
                test: /\.css$/,
                exclude: /node_modules/,
                use: options.defaultLoaders.less
            })**

            config.module.rules.push({
                test: /\.less$/,
           ......

**Comment by phakphumi** [comment] 2019-08-05 14:11
In my opinion, the proper way to solve your error is wrap the next-antd-less.config.js with @zeit/next-css

eg.
```
const withNextAntdLess = require(‘./next-antd-less.config.js
const withCss = require(‘@zeit/next-css’)

export.modules = withCss(withNextAntdLess({
  ...youtOptions,
})
```

Adding your own rule may fine too, but I think using the official loader may better.

**Comment by phucvo0709** [comment] 2019-08-13 03:32
> After taking the time to research I found that setting cssModule to `true` turn the whole project to use cssModule but some node_modules like `antd` doesn't implement by using cssModule.
> 
> So, I customized @zeit/next-less to support work like this.
> 
> next-antd-less.config.js
> 
> ```
> var cssLoaderConfig = require('@zeit/next-css/css-loader-config');
> 
> module.exports = (nextConfig = {}) => {
>   return Object.assign({}, nextConfig, {
>     webpack: (config, options) => {
>       if (!options.defaultLoaders) {
>         throw new Error(
>           'This plugin is not compatible with Next.js versions below 5.0.0 https://err.sh/next-plugins/upgrade'
>         );
>       }
> 
>       const { dev, isServer } = options;
>       const {
>         cssModules,
>         cssLoaderOptions,
>         postcssLoaderOptions,
>         lessLoaderOptions = {},
>       } = nextConfig;
> 
>       options.defaultLoaders.less = cssLoaderConfig(config, {
>         extensions: ['less'],
>         cssModules,
>         cssLoaderOptions,
>         postcssLoaderOptions,
>         dev,
>         isServer,
>         loaders: [
>           {
>             loader: 'less-loader',
>             options: lessLoaderOptions,
>           },
>         ],
>       });
> 
>       config.module.rules.push({
>         test: /\.less$/,
>         exclude: /node_modules/,
>         use: options.defaultLoaders.less,
>       });
> 
>       // disable antd css module
>       config.module.rules.push({
>         test: /\.less$/,
>         include: /node_modules/,
>         use: cssLoaderConfig(config, {
>           extensions: ['less'],
>           cssModules: false,
>           cssLoaderOptions: {},
>           dev,
>           isServer,
>           loaders: [
>             {
>               loader: 'less-loader',
>               options: lessLoaderOptions,
>             },
>           ],
>         }),
>       });
> 
>       if (isServer) {
>         const antStyles = /antd\/.*?\/style.*?/;
>         const origExternals = [...config.externals];
>         config.externals = [
>           (context, request, callback) => {
>             if (request.match(antStyles)) return callback();
>             if (typeof origExternals[0] === 'function') {
>               origExternals[0](context, request, callback);
>             } else {
>               callback();
>             }
>           },
>           ...(typeof origExternals[0] === 'function' ? [] : origExternals),
>         ];
>   
>         config.module.rules.unshift({
>           test: antStyles,
>           use: 'null-loader',
>         });
>       }
> 
>       if (typeof nextConfig.webpack === 'function') {
>         return nextConfig.webpack(config, options);
>       }
> 
>       return config;
>     }
>   });
> };
> ```
> 
> then use it in next.config.js
> 
> ```
> const withNextAntdLess = require('./next-antd-less.config');
> module.exports = withNextAntdLess({
>     cssModules: true,
>     cssLoaderOptions: {
>       importLoaders: 1,
>       localIdentName: '[local]___[hash:base64:5]',
>     },
> })
> ```
> 
> In my case, it usually works. Hopefully, It will help someone to solve the problem to work with antd together with cssModule.
> 
> Related example/issues/modules which I use to compose the solution. #8054 #7957 [with-ant-design-less](https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less) [next-antd-aza-less](https://github.com/sdli/next-antd-aza-less)
> 
> Anyway, if there is an official solution for this issue it will be very good. In my opinion, it will be a common issue.

how to add withSass in config

**Comment by Timer** [comment] 2019-08-15 13:34
Closing as this example does not showcase CSS Modules itself. Feel free to create a new example combining the two, if you'd like.

**Closed by Timer** 2019-08-15 13:34 UTC

**Comment by babymum7** [comment] 2020-07-24 14:24
> > After taking the time to research I found that setting cssModule to `true` turn the whole project to use cssModule but some node_modules like `antd` doesn't implement by using cssModule.
> > So, I customized @zeit/next-less to support work like this.
> > next-antd-less.config.js
> > ```
> > var cssLoaderConfig = require('@zeit/next-css/css-loader-config');
> > 
> > module.exports = (nextConfig = {}) => {
> >   return Object.assign({}, nextConfig, {
> >     webpack: (config, options) => {
> >       if (!options.defaultLoaders) {
> >         throw new Error(
> >           'This plugin is not compatible with Next.js versions below 5.0.0 https://err.sh/next-plugins/upgrade'
> >         );
> >       }
> > 
> >       const { dev, isServer } = options;
> >       const {
> >         cssModules,
> >         cssLoaderOptions,
> >         postcssLoaderOptions,
> >         lessLoaderOptions = {},
> >       } = nextConfig;
> > 
> >       options.defaultLoaders.less = cssLoaderConfig(config, {
> >         extensions: ['less'],
> >         cssModules,
> >         cssLoaderOptions,
> >         postcssLoaderOptions,
> >         dev,
> >         isServer,
> >         loaders: [
> >           {
> >             loader: 'less-loader',
> >             options: lessLoaderOptions,
> >           },
> >         ],
> >       });
> > 
> >       config.module.rules.push({
> >         test: /\.less$/,
> >         exclude: /node_modules/,
> >         use: options.defaultLoaders.less,
> >       });
> > 
> >       // disable antd css module
> >       config.module.rules.push({
> >         test: /\.less$/,
> >         include: /node_modules/,
> >         use: cssLoaderConfig(config, {
> >           extensions: ['less'],
> >           cssModules: false,
> >           cssLoaderOptions: {},
> >           dev,
> >           isServer,
> >           loaders: [
> >             {
> >               loader: 'less-loader',
> >               options: lessLoaderOptions,
> >             },
> >           ],
> >         }),
> >       });
> > 
> >       if (isServer) {
> >         const antStyles = /antd\/.*?\/style.*?/;
> >         const origExternals = [...config.externals];
> >         config.externals = [
> >           (context, request, callback) => {
> >             if (request.match(antStyles)) return callback();
> >             if (typeof origExternals[0] === 'function') {
> >               origExternals[0](context, request, callback);
> >             } else {
> >               callback();
> >             }
> >           },
> >           ...(typeof origExternals[0] === 'function' ? [] : origExternals),
> >         ];
> >   
> >         config.module.rules.unshift({
> >           test: antStyles,
> >           use: 'null-loader',
> >         });
> >       }
> > 
> >       if (typeof nextConfig.webpack === 'function') {
> >         return nextConfig.webpack(config, options);
> >       }
> > 
> >       return config;
> >     }
> >   });
> > };
> > ```
> > 
> > 
> > then use it in next.config.js
> > ```
> > const withNextAntdLess = require('./next-antd-less.config');
> > module.exports = withNextAntdLess({
> >     cssModules: true,
> >     cssLoaderOptions: {
> >       importLoaders: 1,
> >       localIdentName: '[local]___[hash:base64:5]',
> >     },
> > })
> > ```
> > 
> > 
> > In my case, it usually works. Hopefully, It will help someone to solve the problem to work with antd together with cssModule.
> > Related example/issues/modules which I use to compose the solution. #8054 #7957 [with-ant-design-less](https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less) [next-antd-aza-less](https://github.com/sdli/next-antd-aza-less)
> > Anyway, if there is an official solution for this issue it will be very good. In my opinion, it will be a common issue.
> 
> how to add withSass in config

chào bạn, mình cũng đang gặp vấn đề tương tự bạn còn file config không ?

**Comment by SolidZORO** [comment] 2020-08-05 13:22
If you use Next.js > 9.3, you can try [`next-plugin-antd-less`](https://github.com/SolidZORO/next-plugin-antd-less) Use Antd (with Less) with Next.js, Zero Dependency on other Next-Plugins.

**Comment by balazsorban44** [comment] 2022-01-29 18:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
