### ISSUE TITLE
YC W20 company needs help! Deployments to Google Cloud fail with multiple instances.

### ISSUE THREAD

**Issue by brennanerbz** [zeit/next.js#11094] opened 2020-03-16 02:45 UTC
I'm deploying a next.js to Google Cloud app engine. Whenever I deploy the project to AE with multiple instances, it throws this error: net::err_aborted 404 for one or many of the core files.

**Comment by brennanerbz** [comment] 2020-03-16 02:46
It usually says that the /build/ or /_next/_index.js can't be reached.

**Comment by brennanerbz** [comment] 2020-03-16 02:46
It's perfectly fine with 1 App Engine instance.

**Comment by brennanerbz** [comment] 2020-03-16 03:31
GET https://hyphy.tv/_next/static/gwNEOzop8Q8zCbcJBaQlm/pages/index.js net::ERR_ABORTED 404

**Comment by brennanerbz** [comment] 2020-03-16 03:32
Happy to hop on a zoom with someone who can help. We're doing demo day tomorrow and need this fixed.

**Comment by brennanerbz** [comment] 2020-03-16 03:51
Looking into this https://github.com/zeit/next.js/issues/786#issuecomment-337037343

**Comment by brennanerbz** [comment] 2020-03-16 04:53
This doesn't seem to help: https://github.com/nexdrew/next-build-id

**Comment by timneutkens** [comment] 2020-03-16 08:19
Duplicate of https://github.com/zeit/next.js/discussions/11093

**Closed by timneutkens** 2020-03-16 08:19 UTC

**Comment by balazsorban44** [comment] 2022-01-30 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
