### ISSUE TITLE
Constraints for dynamic routing?

### ISSUE THREAD

**Issue by Baukaalm** [zeit/next.js#9059] opened 2019-10-13 07:43 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
/[entity] => matched as all values

and always i add strong check conditions in gip
```
Gender.getInitialProps = async ({ query }) => {
  if (!['mens', 'womens', 'kids'].includes(query.gender)) {
    return { errorCode: 404 };
   }
or
 if (!allowedGroupCatalogs.includes(query.groupId)) {
    return { errorCode: 404, items: {} }
  }

and added conditions in client-side page
  if (errorCode) {
    return <Error statusCode={errorCode} />;
  }

```
I want to have a chance, use to that example
```
/:entity(allowedValue1|allowedvalue2)
```

**Comment by timneutkens** [comment] 2019-10-13 13:11
Duplicate of #8053

**Closed by timneutkens** 2019-10-13 13:11 UTC

**Comment by balazsorban44** [comment] 2022-01-31 02:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
