### ISSUE TITLE
Chrome hanging after multiple refreshes when only one tab is open

### ISSUE THREAD

**Issue by benallfree** [zeit/next.js#7343] opened 2019-05-15 14:16 UTC
# Bug report

## Describe the bug

When using `now dev`, I sometimes get the multiple tabs warning and application hangs even though only one tab is open.

## To Reproduce

This happens most frequently when I have the debugging console open and do a browser refresh.

## Expected behavior

Expect the application to refresh.

## System information
 - OS: OS X 10.14.4
 - Chrome 74.0.3729.131 (Official Build) (64-bit)
 - Version of Next.js: ^8.1.0

**Comment by ijjk** [comment] 2019-05-15 15:09
This warning has been removed in the latest canary of Next.js since we now share one SSE connection instead of using multiple which increased the risk of hitting browser set connection limits. I'm going to close this, feel free to reply with additional details if you are still having trouble with this in the latest version of Next.js

**Comment by benallfree** [comment] 2019-05-15 18:24
Looks like the warning is gone, but it still hangs.

**Comment by ijjk** [comment] 2019-05-15 20:51
Can you reproduce the hanging without `now dev`? If not this is probably related to `now dev`. What version of `now` are you using. You can check with `now --version`.

**Comment by benallfree** [comment] 2019-05-15 21:13
Good thought, and yes, it's unrelated to `now`.

https://github.com/benallfree/nextjs-canary-minimal-hang

I can try resetting  Chrome or rebooting, but I kind of feel like I have the tiger by the tail here, is it worth troubleshooting further to see if we can identify what would be causing this?

**Comment by benallfree** [comment] 2019-05-15 21:23
Maybe a clue... even after I stop the localhost server and completely exit the terminal, even after restarting Chrome, I can still hit localhost:3000 and load the site. In Incognito mode or in a different Chrome profile, I get a `refused to connect` error as expected.

As if some process has not fully exited?

`ps -ef | node` shows nothing. Really weird.

**Comment by ijjk** [comment] 2019-05-15 21:26
Yeah, I'm not able to reproduce it refreshing the page more than five times I've tried doing it pretty fast too. This might be related to your chrome set up since you mentioned it gives you the `refused to connect` in incognito but not in normal mode so it could be hitting the cache. 

If it was related to Next.js it should be reproducible in incognito or a different Chrome profile also.

**Comment by benallfree** [comment] 2019-05-15 21:27
I think there is a ServiceWorker not exiting or something.

![image](https://user-images.githubusercontent.com/1068356/57810838-9d666080-771d-11e9-9ff7-950dd399507c.png)

**Comment by ijjk** [comment] 2019-05-15 21:30
Next.js doesn't register a service worker so this is probably a stale one that was never cleared. You can clear it under the `Application` tab in the Chrome dev tools. I'm gonna close this now since that appears to be what was causing the issue.

**Closed by ijjk** 2019-05-15 21:30 UTC

**Comment by benallfree** [comment] 2019-05-15 21:35
Sure enough, that was it. Would this have been registered through `now`? Or what is the recommended way of detecting this problem?

![image](https://user-images.githubusercontent.com/1068356/57811265-aad01a80-771e-11e9-9c3a-43a156847782.png)

**Comment by ijjk** [comment] 2019-05-15 21:43
No problem. `now` doesn't register a service-worker either so there might have been another application that used `localhost:3000` that registered one at some point that didn't get cleaned up. I usually develop in incognito mode to prevent stuff like that.
