### ISSUE TITLE
Example for transpile a custom service Worker

### ISSUE THREAD

**Issue by porfirialex** [zeit/next.js#9192] opened 2019-10-24 09:56 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
we can add a project example of how to transpile with webpack and register a custom service worker file.

**Comment by ragingwind** [comment] 2019-10-25 01:39
@Timer I would like to take this

**Comment by Timer** [comment] 2019-10-27 23:44
@ragingwind go ahead!

**Comment by timneutkens** [comment] 2020-01-03 00:07
Going to close this as it's been open for months and no PR was made.

**Closed by timneutkens** 2020-01-03 00:07 UTC
Labels: Type: Example, good first issue, help wanted

**Comment by mbustosp** [comment] 2020-01-07 12:43
Any advice about how to do it? I have the same enquiry

**Comment by balazsorban44** [comment] 2022-01-30 16:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
