### ISSUE TITLE
Invalid hook call. Hooks can only be called inside of the body of a function component. 

### ISSUE THREAD

**Issue by webdevsyd** [zeit/next.js#7626] opened 2019-06-21 04:10 UTC
# Bug report

## Describe the bug
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

## To Reproduce

<details>
<summary>Details</summary>
So the error points on this code

```

static async getInitialProps (ctx) {
    const sheet = new ServerStyleSheet()
    const originalRenderPage = ctx.renderPage
    const {
      req: { locale, localeDataScript }
    } = ctx
    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: App => props => sheet.collectStyles(<App {...props} />)
        })

      const initialProps = await Document.getInitialProps(ctx)
      return {
        ...initialProps,
        userAgent: ctx.req.headers['user-agent'],
        helmet: Helmet.renderStatic(),
        locale,
        localeDataScript,
        styles: (
          <>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </>
        )
      }
    } finally {
      sheet.seal()
    }
  }
```

</details>

## Screenshots
![Screen Shot 2019-06-21 at 12 10 08 PM](https://user-images.githubusercontent.com/15810023/59897059-8a7e3480-941d-11e9-942f-b082ce1ee766.png)

## Additional context
I suspect that it treats the `ctx.renderPage = () => ` as a react hooks.

**Comment by c0b41** [comment] 2019-06-22 02:28
what version using styled-components? because i have same problem, but only version 5 beta broken currently

**Comment by paintedbicycle** [comment] 2019-06-22 08:09
This happens to me sometimes when I update dependencies.

I delete `node_modudes`, `dist/` and 'package-lock.json'`, then re-run `npm install` and restart the app. Seems to always fix it.

**Comment by timneutkens** [comment] 2019-06-22 17:05
Please provide a clear and concise reproduction. I don't think this is related to Next.js based on the description provided so I'll close the issue until a full reproduction is provided. There are 2 possibilities in which this happened as described in the error message:
- you have 2 versions of react, maybe through installing external deps
- you are using hooks somewhere that is not in the render tree, maybe the stacktrace means you're trying to use hooks inside getInitialProps?

**Closed by timneutkens** 2019-06-22 17:05 UTC

**Comment by curran** [comment] 2019-06-25 06:14
I'm experiencing this as well, after updating a bunch of dependencies. Difficult to pinpoint the cause. FWIW I did clear out `node_modules` and `package-lock.json`, and it did not solve the issue.

My stack trace pointed to the following line as the source of the error:

```
  3 | export default class DefaultDocument extends Document {
  4 |   static async getInitialProps (ctx) {
> 5 |     return await Document.getInitialProps(ctx);
  6 |   }
```

This seems like pretty standard boilerplate for Next, unless I'm missing something that changed in one of the recent major versions?

**Comment by webdevsyd** [comment] 2019-06-25 06:30
> I'm experiencing this as well, after updating a bunch of dependencies. Difficult to pinpoint the cause. FWIW I did clear out `node_modules` and `package-lock.json`, and it did not solve the issue.
> 
> My stack trace pointed to the following line as the source of the error:
> 
> ```
>   3 | export default class DefaultDocument extends Document {
>   4 |   static async getInitialProps (ctx) {
> > 5 |     return await Document.getInitialProps(ctx);
>   6 |   }
> ```
> 
> This seems like pretty standard boilerplate for Next, unless I'm missing something that changed in one of the recent major versions?

Yeah, i also checked if I have a 2 different react and react-dom. The result is I only have 1 which is both version 16.8.6. I'm running out of things to check.

**Comment by curran** [comment] 2019-06-25 06:36
Same here. I'm embarking on trying to put together a minimal reproduction repo.

**Comment by curran** [comment] 2019-06-25 06:54
Full stack trace in case it might be useful:

```
{ Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at invariant (/home/curran/repos/vizhub/packages/ui/node_modules/react/cjs/react.development.js:88:15)
    at resolveDispatcher (/home/curran/repos/vizhub/packages/ui/node_modules/react/cjs/react.development.js:1436:28)
    at useMemo (/home/curran/repos/vizhub/packages/ui/node_modules/react/cjs/react.development.js:1491:20)
    at ConnectFunction (/home/curran/repos/vizhub/packages/ui/node_modules/react-redux/lib/components/connectAdvanced.js:131:41)
    at processChild (/home/curran/repos/vizhub/packages/web/node_modules/react-dom/cjs/react-dom-server.node.development.js:2888:14)
    at resolve (/home/curran/repos/vizhub/packages/web/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (/home/curran/repos/vizhub/packages/web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (/home/curran/repos/vizhub/packages/web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at renderToString (/home/curran/repos/vizhub/packages/web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3646:27)
    at render (/home/curran/repos/vizhub/packages/web/node_modules/next-server/dist/server/render.js:86:16)
    at renderPage (/home/curran/repos/vizhub/packages/web/node_modules/next-server/dist/server/render.js:211:20)
    at Function.value (/home/curran/repos/vizhub/packages/web/.next/server/static/development/pages/_document.js:830:41)
    at _callee$ (/home/curran/repos/vizhub/packages/web/.next/server/static/development/pages/_document.js:2276:77)
    at tryCatch (/home/curran/repos/vizhub/packages/web/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/curran/repos/vizhub/packages/web/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/curran/repos/vizhub/packages/web/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/home/curran/repos/vizhub/packages/web/.next/server/static/development/pages/create-visualization.js:1026:24)
    at _next (/home/curran/repos/vizhub/packages/web/.next/server/static/development/pages/create-visualization.js:1048:9)
    at /home/curran/repos/vizhub/packages/web/.next/server/static/development/pages/create-visualization.js:1055:7
    at new Promise (<anonymous>)
    at new F (/home/curran/repos/vizhub/packages/web/node_modules/core-js/library/modules/_export.js:36:28)
    at Function.<anonymous> (/home/curran/repos/vizhub/packages/web/.next/server/static/development/pages/create-visualization.js:1044:12)
    at Function.getInitialProps (/home/curran/repos/vizhub/packages/web/.next/server/static/development/pages/_document.js:2290:33)
    at Object.loadGetInitialProps (/home/curran/repos/vizhub/packages/web/node_modules/next-server/dist/lib/utils.js:42:35)
    at Object.renderToHTML (/home/curran/repos/vizhub/packages/web/node_modules/next-server/dist/server/render.js:218:36)
    at processTicksAndRejections (internal/process/next_tick.js:81:5) name: 'Invariant Violation', framesToPop: 1 }
```

**Comment by paintedbicycle** [comment] 2019-06-25 09:08
@curran Did you also delete the build folder? You only mention 2 of 3 that I suggested. The error message seems like a red herring each time - it seems to have more to do with miss-matched versions and out of date dependencies and builds than it does hooks.

**Comment by curran** [comment] 2019-06-25 11:22
Thanks @paintedbicycle for the tip! I tried `rm .next/ -rf`, and the error persists.

I'm seeing this in dev mode, so I don't believe the build folder (`.next`) would be related.

**Comment by paintedbicycle** [comment] 2019-06-25 11:29
Ah, ok I have a slightly different set up than you. I have `/src/` and `/dist/`

**Comment by dancancro** [comment] 2019-08-24 01:10
I'm grappling with this one too. I don't use styled-components. I tried deleting node_modules etc. without luck. I tried adding aliases and resolves for `react` in my next.config.js file and package.json without luck. I'm using react 16.8.6, react-dom 16.8.6, and next 9.0.4. `npm ls` says there's only one of each. The app uses material-ui. I am not using any npm links.  I only use two hooks, `useState`, [like this](https://github.com/dancancro/questions/blob/invalid-hook-call/components/ContactUsDialog/index.jsx#L13-L18).

The repo is here: https://github.com/dancancro/questions/tree/invalid-hook-call

The error is here: https://gist.github.com/dancancro/2dfafb053aaaedfade406fd4f67eb68a

**Comment by dbeaudway** [comment] 2019-10-13 15:49
For those who are still encountering this error after troubleshooting all the proposed fixes, double-check that you are using the correct directory casing when running your project. I continued to have problems on my PC and discovered this was the reason why.

[https://stackoverflow.com/questions/58365151/hooks-error-invalid-hook-call-using-nextjs-or-reactjs-on-windows/58365152#58365152](Stackoverflow post)

**Comment by brycelund** [comment] 2020-03-11 05:27
I had a node_modules folder in a parent directory up the tree that was causing issues. I deleted that and it started working as expected,

**Comment by conan** [comment] 2020-05-27 16:44
@brycelund this fixed it for me, after a day of checking for duplicate reacts and ensuring my hooks were done by the book. Thanks! I can't understand why this is an issue

**Comment by kishankanugula** [comment] 2020-10-13 19:24
> I don't use next, but I do work on an SSR react app and ran into the same issue. The thing that ended up fixing it was to modify my webpack externals configuration to keep `react` and `react-dom` inside the webpack bundle.
> 
> I still have no idea why that fix worked - it makes me wonder whether there's something about the webpack runtime + nodejs requires that can result in multiple copies of a lib floating around at runtime.

@tstirrat15 I am also having the same issue. Can you please share the webpack externals config which fixed the issue? Thanks a lot.

**Comment by tstirrat15** [comment] 2020-10-16 18:17
@kishankanugula I don't have access to that code anymore. It was using [webpack-node-externals](https://github.com/liady/webpack-node-externals) and adding `react` and `react-dom` to the `allowList`, though.

**Comment by cianfoley-nearform** [comment] 2020-12-18 11:13
> I had a node_modules folder in a parent directory up the tree that was causing issues. I deleted that and it started working as expected,

Well done @brycelund, tried everything to resolve to one version of react, really not sure what is going on that it is going above the root directory of the project

**Comment by linhnle** [comment] 2020-12-21 08:05
I got the problem because I used Powershell. I try to use command prompt and the problem does not happen any more. Anyone can explain me what happens when I use Powershell.

**Comment by joemaffei** [comment] 2021-02-04 22:53
Somewhat related to @dbeaudway's [comment](https://github.com/vercel/next.js/issues/7626#issuecomment-541430221), it's possible to get this error when running the project from a symlinked folder. For example, if the real path to your project is `C:/Projects/my-app` but you have a symlink to the Projects folder, say at `C:/Users/UserName/Projects`. Running the project from `C:/Users/UserName/Projects/my-app` won't work.

**Comment by stereobooster** [comment] 2021-09-15 22:24
https://github.com/vercel/next.js/issues/17592#issuecomment-920425814

**Comment by djowvani** [comment] 2022-01-04 23:11
I'm using:
```
"next": "^10.0.5",
"react": "^17.0.1",
"react-dom": "^17.0.1",
"styled-components": "^5.2.1",
```

Tried so many links related to this issue, plus all of the suggested above by the book, still can't seem to get it going...
Always when I hover this span and trigger the hook, it crashes.
Anyone still having this issue? Such a simple implementation, so tricky to make it work tho...

This is my custom hook:
```
import { useState, useEffect } from "react";

export const useMutateCursorContent = (visibility, content) => {
  const [isCursorContentVisible, setIsCursorContentVisible] = useState(false);
  const [cursorContent, setCursorContent] = useState("");

  useEffect(() => {
    setIsCursorContentVisible(visibility);
    setCursorContent("hover testing");
  });

  return { isCursorContentVisible, cursorContent };
};
```
This is my custom hook call:
```
import { useMutateCursorContent } from "@/hooks/useMutateCursorContent";

const WordCloud = ({ data }) => {
  const customRenderer = (tag, size, color) => {
    return (
      <WordCloudSpan
        value={tag.value}
        size={size}
        color={color}
        onHover={() => useMutateCursorContent(true, tag)}
      />
    );
  };

  return (
    <StyledContainer>
      <StyledWordCloud
        tags={data}
        renderer={customRenderer}
      />
    </StyledContainer>
  );
};
export default WordCloud;

```
If it helps, this is my stacktrace:

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (react-dom.development.js:14906)
    at useState (react.development.js:1508)
    at useMutateCursorContent (useMutateCursorContent.js:4)
    at Object.onHover (WordCloud.js:13)
    at handleHover (WordCloudSpan.js:5)
    at onMouseLeave (WordCloudSpan.js:12)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070)
    at executeDispatch (react-dom.development.js:8243)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275)
    at processDispatchQueue (react-dom.development.js:8288)
    at dispatchEventsForPlugins (react-dom.development.js:8299)
    at react-dom.development.js:8508
    at batchedEventUpdates$1 (react-dom.development.js:22396)
    at batchedEventUpdates (react-dom.development.js:3745)
    at dispatchEventForPluginEventSystem (react-dom.development.js:8507)
    at attemptToDispatchEvent (react-dom.development.js:6005)
    at dispatchEvent (react-dom.development.js:5924)
    at unstable_runWithPriority (scheduler.development.js:468)
    at dispatchUserBlockingUpdate (react-dom.development.js:5894)
```

**Comment by tstirrat15** [comment] 2022-01-06 19:13
@djowvani https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level

You can't put a hook call into a callback. A hook needs to be called at the same time in the same location on every render cycle. It's not related to this issuel.

**Comment by balazsorban44** [comment] 2022-02-05 20:04
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
