### ISSUE TITLE
Next version 7 error: "Plugin 0 ... provided an invalid property of "default""

### ISSUE THREAD

**Issue by tashburn** [zeit/next.js#4302] opened 2018-05-07 21:10 UTC
Here's the error

```
Error: Plugin 0 specified in "/home/ubuntu/grok/source/node_modules/next/babel.js" provided an invalid property of "default" (While processing preset: "/home/ubuntu/grok/source/node_modules/next/babel.js")
    at Plugin.init (/home/ubuntu/grok/source/node_modules/babel-register/node_modules/babel-core/lib/transformation/plugin.js:131:13)
    at Function.normalisePlugin (/home/ubuntu/grok/source/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
    at /home/ubuntu/grok/source/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/home/ubuntu/grok/source/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/home/ubuntu/grok/source/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at /home/ubuntu/grok/source/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
    at /home/ubuntu/grok/source/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/home/ubuntu/grok/source/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)

```

And here's the dependencies and babel config of my `package.json`

```
{
  "dependencies": {
    "@babel/core": "7.0.0-beta.44",
    "@babel/plugin-proposal-decorators": "7.0.0-beta.44",
    "@babel/polyfill": "7.0.0-beta.44",
    "@babel/preset-env": "7.0.0-beta.44",
    "@babel/preset-stage-0": "7.0.0-beta.44",
    "@babel/register": "7.0.0-beta.44",
    "auto-sni": "2.3.2",
    "body-parser": "1.18.2",
    "chalk": "2.3.0",
    "compression": "1.7.2",
    "cookie-parser": "1.4.3",
    "cookies": "0.7.1",
    "credential": "2.0.0",
    "elasticlunr": "0.9.5",
    "encode32": "1.1.0",
    "expect": "22.0.3",
    "express": "4.16.2",
    "express-await": "0.0.4",
    "express-brute": "1.0.1",
    "express-force-ssl": "0.3.2",
    "express-graceful-exit": "0.4.1",
    "fingerprintjs2": "1.5.1",
    "forcedomain": "0.8.1",
    "glamor": "2.20.40",
    "glamorous": "4.11.2",
    "goby": "1.1.2",
    "google-id-token-verifier": "0.2.3",
    "helmet": "3.12.0",
    "homoglyph": "1.1.2",
    "immutable": "3.8.2",
    "is-hotkey": "0.1.2",
    "isomorphic-unfetch": "2.0.0",
    "js-base64": "2.4.3",
    "js-cookie": "2.2.0",
    "json-stringify-safe": "5.0.1",
    "json5": "1.0.1",
    "jsonfile": "4.0.0",
    "jwt-simple": "0.5.1",
    "keymaster": "1.6.2",
    "luxon": "1.1.0",
    "material-ui": "0.20.0",
    "mobx": "4.1.1",
    "mobx-react": "5.0.0",
    "next": "6.0.0",
    "next-cookies": "1.0.2",
    "node-ssh": "5.1.1",
    "nodemailer": "4.6.3",
    "nodemailer-mailgun-transport": "1.3.6",
    "nprogress": "0.2.0",
    "pg": "7.4.0",
    "platform": "1.3.4",
    "prop-types": "15.6.0",
    "react": "16.3.1",
    "react-anime": "2.0.1",
    "react-dnd": "2.5.4",
    "react-dnd-html5-backend": "2.2.4",
    "react-dom": "16.3.1",
    "react-html-email": "3.0.0",
    "react-keydown": "1.7.0",
    "react-modal": "3.1.10",
    "react-ripples": "1.1.2",
    "react-scroll": "1.7.5",
    "react-select": "1.1.0",
    "react-stickynode": "1.4.0",
    "react-tap-event-plugin": "3.0.2",
    "react-tooltip": "3.4.0",
    "react-transition-group": "2.2.1",
    "react-youtube": "7.5.0",
    "redirect-https": "1.1.5",
    "request-ip": "2.0.2",
    "slate": "0.33.5",
    "slate-auto-replace": "0.9.0",
    "slate-html-serializer": "0.6.2",
    "slate-react": "0.12.5",
    "textversionjs": "1.0.2",
    "universal-analytics": "0.4.16",
    "url-parse": "1.2.0",
    "uuid": "3.1.0",
    "webpack-bundle-analyzer": "2.9.1",
    "webpack-bundle-size-analyzer": "2.7.0",
    "winston": "2.4.1",
    "winston-loggly-bulk": "2.0.2"
  },
  "devDependencies": {
    "@babel/core": "7.0.0-beta.44",
    "@types/jest": "22.1.1",
    "@types/node": "9.4.7",
    "@types/react-dom": "16.0.4",
    "@zeit/next-typescript": "0.0.10",
    "babel-core": "^7.0.0-bridge.0",
    "babel-plugin-module-resolver": "3.0.0",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "concurrently": "3.5.1",
    "cross-env": "5.1.3",
    "jest": "22.4.3",
    "nodemon": "1.14.7",
    "typescript": "2.8.1"
  },
  "babel": {
    "presets": [
      "next/babel"
    ],
    "plugins": [
      "transform-decorators-legacy",
      [
        "module-resolver",
        {
          "root": [
            "."
          ]
        }
      ]
    ]
  }
}
```

**Comment by timneutkens** [comment] 2018-05-07 21:12
Duplicate of #4227
Duplicate of #4296
Duplicate of #4291

**Closed by timneutkens** 2018-05-07 21:12 UTC
