### ISSUE TITLE
Using the <progress> element from within a component causes high CPU

### ISSUE THREAD

**Issue by fling** [zeit/next.js#6567] opened 2019-03-07 22:32 UTC
# Bug report

## Describe the bug

If you use the `<progress>` HTML element within a component it causes a high CPU.

## To Reproduce

1. Add the `<progress>` HTML to a component
2. Include one or more instances of the components to a page
3. Reload and view system activity. The more instances of the component, the higher the CPU

## System information
 - OS: macOS
 - Browser (if applies): Safari
 - Version of Next.js: 8

**Comment by timneutkens** [comment] 2019-03-07 22:34
I imagine this is either related to React or you can reproduce with plain HTML.

Could you try reproducing this with plain HTML?

**Comment by timneutkens** [comment] 2019-08-10 12:30
Going to close this as there was no reply.

**Closed by timneutkens** 2019-08-10 12:30 UTC

**Comment by balazsorban44** [comment] 2022-01-31 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
