### ISSUE TITLE
SyntaxError: Strict mode does not allow function declarations in a lexically nested statement in IOS 9.x.

### ISSUE THREAD

**Issue by yanghuabei** [zeit/next.js#7178] opened 2019-04-27 12:03 UTC
# Bug report

## Describe the bug

SyntaxError: Strict mode does not allow function declarations in a lexically nested statement in IOS 9.x.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. install next.js 8.1.0
2. build and start server
3. open page in ios8 or ios9 safari

## Expected behavior
page should work.

## Screenshots
![image](https://user-images.githubusercontent.com/6822885/56849469-44c65380-6927-11e9-9bd4-8a0de7decf7c.png)

![image](https://user-images.githubusercontent.com/6822885/56849465-3841fb00-6927-11e9-9826-8676ccf06a81.png)

## System information
 - OS: ios8, ios9
 - Browser: safari
 - Version of Next.js: 8.1.0

**Comment by keenjaan** [comment] 2019-04-28 02:00
@yanghuabei some problem with you，8.0.3 is well

**Comment by e2goon** [comment] 2019-05-06 12:29
Also in IE10

**Comment by pedrommenezes** [comment] 2019-05-09 17:16
It also happens to me in 2 different applications using next@8.1.0. Had to downgrade them to make it work.

**Comment by weishiji** [comment] 2019-05-15 10:07
It also happens to me 

- Version of Next.js: 8.1.0

**Comment by fionawhim** [comment] 2019-05-15 13:15
I can confirm that this is fixed in the latest, 8.1.1-canary.28, and probably since canary 20.

#7014 removed putting async-to-promises around the Next.js client code.

**Comment by ijjk** [comment] 2019-05-15 15:03
As @fionawhim mentioned, this was fixed when we made `async-to-promises` experimental and is no longer enabled by default. I'm going to close this now, if you are still having trouble with this on the latest canary please reply with additional details.

**Comment by developit** [comment] 2019-05-16 12:35
This is actually _not_ caused by async-to-promises. It's caused by Terser defaulting to the `inline=3` setting, which is inlining functions where it is unsafe to do so. It can also cause performance issues.

**Comment by JulesAU** [comment] 2019-06-03 23:21
@ijjk  Is there any backport of this fix (or another way to enable it) on the stable 8.1.0 branch? We're seeing lots of this in production logs.

**Comment by Timer** [comment] 2019-06-11 14:19
This will be fixed by https://github.com/zeit/next.js/pull/7554.

**Closed** 2019-06-11 17:34 UTC
Labels: Type: Bug, Type: Needs Investigation

**Comment by Timer** [comment] 2019-06-11 17:59
Published as `8.1.1-canary.51`. 🙏

**Comment by makarov-foot** [comment] 2019-06-19 09:04
after updating to 8.1.1 - canary custom ts-node (from examples folder) config went down. "Next.js now provides ts support from scratch"...

**Comment by MichaelIT** [comment] 2019-07-29 02:14
emmm, I think it is no related to terser.
In `v8.1.0`, I can fixed it by adding
```
if (!isServer) {
      // console.log(JSON.stringify(config));
      config.module.rules.push({
        test: /\.(tsx|ts|js|mjs|jsx)$/,
        include: [
          /next-server[\\/]dist[\\/]lib/,
          /next[\\/]dist[\\/]client/,
          /next[\\/]dist[\\/]pages/,
          /[\\/](strip-ansi|ansi-regex)[\\/]/,
        ],
        exclude: path => {
          if (
            /next-server[\\/]dist[\\/]lib/.test(path) ||
            /next[\\/]dist[\\/]client/.test(path) ||
            /next[\\/]dist[\\/]pages/.test(path) ||
            /[\\/](strip-ansi|ansi-regex)[\\/]/.test(path)
          ) {
            return false;
          }
          return /node_modules/.test(path);
        },
        use: defaultLoaders.babel,
      });
    }
```
to file next.config.js after review the code of #7014
