### ISSUE TITLE
ref doesn't work with dynamically imported components

### ISSUE THREAD

**Issue by juancampa** [zeit/next.js#4957] opened 2018-08-15 05:22 UTC
# Bug report

## Describe the bug

When a component is wrapped in `next/dynamic` the passed `ref` should be a ref to the imported component, not an instance of `NoSsr` or `LoadableComponent`

## To Reproduce

1. Import a component using `next/dynamic`
2. Use said component in `render` passing a `ref` (use a function to received the ref)

Result: the function is called with either a `NoSSR` component or a `LoadableComponent` instead of an instance of the component imported in step 1

## Expected behavior

The function gets called with an instance of the dynamically loaded component

## System information

 - Version of Next.js: `6.1.1-canary.4`

## Additional context

Didn't try with `createRef` but it shouldn't make a difference

**Comment by timneutkens** [comment] 2018-08-15 19:40
Please create a minimal reproducible example in a github repo so it's easier to reproduce.

**Comment by juancampa** [comment] 2018-08-16 02:38
Sure, here it is:

https://github.com/juancampa/next-bug

It should work with clone, `yarn` and `yarn run dev`

**Comment by timneutkens** [comment] 2018-08-16 02:54
Expecting this to be one of the cases for the new `createRef` API

**Comment by HaNdTriX** [comment] 2018-08-17 09:28
Adding `React.forwardRef` might be problematic since

1. we [haven't dropped](https://github.com/zeit/next.js/blob/canary/package.json#L155-L156) react support of React <16.3 
2. support of other rendering engines like [preact](https://preactjs.com/) will be dropped as well.
3. [react-loadable](https://github.com/jamiebuilds/react-loadable) doesn't support `forwardRefs` so we might need to implement it there first in order to get the actual child instead of the `<LoadableComponent>`.

**Comment by HaNdTriX** [comment] 2018-08-17 11:52
## Solution

@juancampa You can use the `forwardRef` api to implement it yourself.

`pages/index.js`

```js
import React from 'react'
import dynamic from 'next/dynamic';

// Dynamically imported component
const Component = dynamic(import('../components/Component'));
const ForwardedRefComponent = React.forwardRef((props, ref) => (
  <Component {...props} forwardedRef={ref} />
))

export default class Index extends React.Component {
  constructor(props) {
    super(props)
    this.myRef = React.createRef();
  }

  componentDidMount() {
    console.log('this.myRef', this.myRef)
  }

  render() {
    return <ForwardedRefComponent ref={this.myRef}/>;
  }
}
```

`components/Component.js`

```js
export default ({ forwardedRef }) => (
  <div ref={forwardedRef}>
    Hi from Component
  </div>
)
```

Please note you can also omit the `forwardRef` api and pass the ref as `forwardedRef` in directly.

[Example](https://github.com/HaNdTriX/next-bug/commit/14a2e124e1d01ff90100fc2863f31de275887369)

## Issues adding this functionality to next.js

I don't think it makes sense to implement it in next now since:

- react-loadable needs to implement it first
- we need to deprecate React <16.3
- won't work with other rendering engines (e.g. preact)

**Comment by timneutkens** [comment] 2018-08-17 18:28
Thanks @HaNdTriX

**Comment by mohsinulhaq** [comment] 2018-10-03 15:47
@HaNdTriX what if we want to set ref on the `Component` component itself?

**Comment by timneutkens** [comment] 2018-10-17 12:16
Going to close this as the issue has been answered and @HaNdTriX's reasoning is correct.

**Closed by timneutkens** 2018-10-17 12:16 UTC

**Comment by muhaimincs** [comment] 2019-10-14 07:13
is this going to be official workaround?

**Comment by phattranky** [comment] 2020-01-28 13:46
> @HaNdTriX what if we want to set ref on the `Component` component itself?

Then, you can simply user other Component wrap all component using `ref`. Then use dynamic on WrapperComponent. So the child component will use like usual

**Comment by xfause** [comment] 2020-03-16 16:40
> ## Solution
> @juancampa You can use the `forwardRef` api to implement it yourself.
> 
> `pages/index.js`
> 
> ```js
> import React from 'react'
> import dynamic from 'next/dynamic';
> 
> // Dynamically imported component
> const Component = dynamic(import('../components/Component'));
> const ForwardedRefComponent = React.forwardRef((props, ref) => (
>   <Component {...props} forwardedRef={ref} />
> ))
> 
> export default class Index extends React.Component {
>   constructor(props) {
>     super(props)
>     this.myRef = React.createRef();
>   }
> 
>   componentDidMount() {
>     console.log('this.myRef', this.myRef)
>   }
> 
>   render() {
>     return <ForwardedRefComponent ref={this.myRef}/>;
>   }
> }
> ```
> 
> `components/Component.js`
> 
> ```js
> export default ({ forwardedRef }) => (
>   <div ref={forwardedRef}>
>     Hi from Component
>   </div>
> )
> ```
> 
> Please note: You can also omit the `forwardRef` api and pass the ref as `forwardedRef` in directly.
> 
> [Example](https://github.com/HaNdTriX/next-bug/commit/14a2e124e1d01ff90100fc2863f31de275887369)
> 
> ## Issues adding this functionality to next.js
> I don't think it makes sense to implement it in next now since:
> 
> * react-loadable needs to implement it first
> * React <16.3 needs to be deprecated first
> * won't work with other rendering engines (e.g. preact)

how can i do with the custom Component not wroten by myself ?
I cant set
 `<div ref={forwardedRef}>
    Hi from Component
  </div>`

**Comment by matiastucci** [comment] 2020-08-18 01:18
I'm trying to use `forwardRef` on an external component but `ref.current` is not the actual ref. Not sure if I'm missing something. Can anyone take a look, please?

Here it's my code: https://codesandbox.io/s/objective-benz-qh4ec?file=/pages/index.js:63-73

**Comment by alvelig** [comment] 2020-12-15 09:00
If you can't modify an imported component, then you'll have to hack into the DOM.

My workaround (or maybe it's just a forgotten canonical way?) is the following:
```
const Component = () => {
  const ref = useRef();
  const id = useState(shortid());
  const DynamicComponent = eval('div') // Put whatever variable that contains your dynamic component
  useEffect(() => {
    ref.current = document.getElementById(id);
  }, [DynamicComponent]);
  return <DynamicComponent id={id} />
}
```

Be aware of that if you change your dynamic component due to some conditions, you need to add this conditions to use effect so the ref is updated with your component.

**Comment by matiastucci** [comment] 2021-01-28 23:07
@alvelig thanks for the response!

Sadly, I'm not sure if I follow this part:

`eval('div') // Put whatever variable that contains your dynamic component`

Can you explain it more, please?

Thanks 🙏

**Comment by fcFn** [comment] 2021-02-22 16:05
@matiastucci You have to wrap your component in a custom component and pass the ref through it (NB: when passing the ref don't use `ref` attribute, use some other name such as `forwardedRef` as in the example).

See your modified example: https://codesandbox.io/s/busy-jennings-cxll6

**Comment by giacomoalonzi** [comment] 2021-04-14 16:12
> @matiastucci You have to wrap your component in a custom component and pass the ref through it.
> 
> See your modified example: https://codesandbox.io/s/relaxed-pine-b8f5z.
> 
> Note that you can use the [custom prop way](https://gist.github.com/gaearon/1a018a023347fe1c2476073330cc5509) without using `forwardRef` (example: https://codesandbox.io/s/busy-jennings-cxll6).

In your example the ref is null, is this the proper result?

**Comment by fcFn** [comment] 2021-04-19 11:38
@giacomoalonzi If you check the console pane (not the terminal pane), you'll see that the ref is not null after the editor renders.

**Comment by igormartimiano** [comment] 2021-05-13 20:04
@fcFn Much appreciated, thanks!

**Comment by ical10** [comment] 2021-05-27 08:28
> ## Solution
> @juancampa You can use the `forwardRef` api to implement it yourself.
> 
> `pages/index.js`
> 
> ```js
> import React from 'react'
> import dynamic from 'next/dynamic';
> 
> // Dynamically imported component
> const Component = dynamic(import('../components/Component'));
> const ForwardedRefComponent = React.forwardRef((props, ref) => (
>   <Component {...props} forwardedRef={ref} />
> ))
> 
> export default class Index extends React.Component {
>   constructor(props) {
>     super(props)
>     this.myRef = React.createRef();
>   }
> 
>   componentDidMount() {
>     console.log('this.myRef', this.myRef)
>   }
> 
>   render() {
>     return <ForwardedRefComponent ref={this.myRef}/>;
>   }
> }
> ```
> 
> `components/Component.js`
> 
> ```js
> export default ({ forwardedRef }) => (
>   <div ref={forwardedRef}>
>     Hi from Component
>   </div>
> )
> ```
> 
> Please note: You can also omit the `forwardRef` api and pass the ref as `forwardedRef` in directly.
> 
> [Example](https://github.com/HaNdTriX/next-bug/commit/14a2e124e1d01ff90100fc2863f31de275887369)
> 
> ## Issues adding this functionality to next.js
> I don't think it makes sense to implement it in next now since:
> 
> * react-loadable needs to implement it first
> * React <16.3 needs to be deprecated first
> * won't work with other rendering engines (e.g. preact)

Thanks a bunch! Works with my `next.js` + `typescript` project, you just need to add simple snippets below in `Component.ts`:

```ts
interface ComponentProps {
  forwardedRef: React.ForwardedRef<any>;
}

const Component: React.FC<ComponentProps> = ({ forwardedRef }) => {
...
}
```

**Comment by balazsorban44** [comment] 2022-01-28 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
