### ISSUE TITLE
Build process doesn't end

### ISSUE THREAD

**Issue by DMomplaisirASC** [zeit/next.js#7766] opened 2019-07-07 06:05 UTC
# Bug report

## Describe the bug

I keep trying to run "next build", and it won't work. I've tried deleting the .next folder, and I've ran both yarn and npm (after deleting yarn.lock, and package-lock, respectively)
## To Reproduce

Checkout 

1.Clone  https://github.com/AmherstStudent/amherst-student-site/tree/code-clean
2. Run yarn && yarn build
3. See error

## Expected behavior

Finished build process

## System information

- Windows
- Version of Next.js:  v8. canary

**Comment by masives** [comment] 2019-07-08 12:16
I don't see any error 
![image](https://user-images.githubusercontent.com/18038829/60809419-e6b9b600-a18a-11e9-88f4-9ddeb2c2aae0.png)

**Comment by DMomplaisirASC** [comment] 2019-07-08 19:20
Not git master - the branch of code-clean isn't working. My apolgize I should have made it clearer.

**Comment by masives** [comment] 2019-07-09 11:41
```

./components/Article/Image.js
Module not found: Can't resolve '../Basics/Card' in '/home/jozef-piecyk-10clouds/nextjs/amherst-student-site/client/components/Article'

```

You're trying to import file `Card` (Uppercase) while you only have `card.js` (lowercase) in the directory you're importing module from. After fixing this I got error that it cannot resolve components/Article/AuthorCard, again filename is authorcard. Make sure that filename and path in import is the same. You can use eslint or some extension to help you with this (like PathIntellisense for VSCode)

**Comment by Timer** [comment] 2019-07-19 02:26
Closing as I'm guessing this case-sensitivity problem ended up fixing the build. Please let us know if you still need help! ☝️

**Closed by Timer** 2019-07-19 02:26 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
