### ISSUE TITLE
Error was not caught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document

### ISSUE THREAD

**Issue by mderazon** [zeit/next.js#10313] opened 2020-01-28 18:07 UTC
# Bug report
Following the tutorial [first steps](https://nextjs.org/learn/basics/getting-started/setup), expecting to see a 404 page when running `npm run dev` but seeing an empty screen with the following error in console:
```
localhost/:1 GET http://localhost:3000/ 404 (Not Found)
Navigated to http://localhost:3000/
react-dom.development.js:27773 Download the React DevTools for a better development experience: https://fb.me/react-devtools
index.js:1 Error was not caught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at initializeBuildWatcher (http://localhost:3000/_next/static/runtime/main.js?ts=1580234262737:6291:39)
    at http://localhost:3000/_next/static/runtime/main.js?ts=1580234262737:7260:40
console.<computed> @ index.js:1
(anonymous) @ next-dev.js:6
Promise.catch (async)
(anonymous) @ next-dev.js:6
./node_modules/next/dist/client/next-dev.js @ next-dev.js:6
__webpack_require__ @ bootstrap:792
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js?ts=1580234262737:1
on-demand-entries-utils.js:5 GET http://localhost:3000/ 404 (Not Found)
(anonymous) @ on-demand-entries-utils.js:5
handleMessage @ eventsource.js:1
on-demand-entries-utils.js:5 GET http://localhost:3000/ 404 (Not Found)
(anonymous) @ on-demand-entries-utils.js:5
handleMessage @ eventsource.js:1
```

## To Reproduce

Chrome 80 which will be released in Feb has some important changes for 3rd party cookie policy:
https://blog.chromium.org/2019/10/developers-get-ready-for-new.html
https://web.dev/samesite-cookies-explained/

To reproduce this error on chrome 79, turn these two flags on:
> chrome://flags/#cookies-without-same-site-must-be-secure
> chrome://flags/#same-site-by-default-cookies

Then follow the tutorial and see the blank page when starting the dev server

## Expected behavior
To see a 404 page

## Screenshots
![image](https://user-images.githubusercontent.com/717076/73292086-51027880-41f9-11ea-88d2-5cebd86b2ec9.png)

## System information
Next: 9.2.1
Node:  v12.13.1
OS: Ubuntu 19.10
Chrome: Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by rafaelalmeidatk** [comment] 2020-01-28 20:13
This does not happen with me even if I turn the flags on. The issue may be with the `Block third-party cookies and site data` option on Chrome's settings, when I turned it on it stopped working on my browser too. My error is different tho:

![image](https://user-images.githubusercontent.com/11896398/73301370-696e9500-41f1-11ea-8fe0-08b5d0db5185.png)

**Comment by lfades** [comment] 2020-01-28 20:22
Thank you for the report, checking it out right now 🕵

**Comment by lfades** [comment] 2020-01-28 21:40
I enabled the flags, followed the steps and it worked as expected, so I'm unable to reproduce the issue. I'm on Windows and that may be why it's working for me.

Can you check if there are extensions trying to set cookies? that may be what's causing it.

**Comment by rafaelalmeidatk** [comment] 2020-01-28 22:37
@lfades I reproduced again without any extensions or apps enabled, it is kinda inconsistent tho. Here are my steps:

1. Turn both flags on.
2. Start the dev server, go to localhost:3000, everything is ok (you can see the 404 page)
3. Reload the page, everything is ok
4. With the page still open, stop the dev server and start it again, refresh the page and it will crash.

You may need to repeat step 4 a few times

**Comment by rafaelalmeidatk** [comment] 2020-01-28 22:46
I did more testing and looks like the error is very situational:

- It doesn't happen if you have a index.js page
- It doesn't happen if you try to go to a 404 page in a specific page (e.g. `localhost:3000/foo`), only in the root (`/`)
- It doesn't happen if you have at least one page inside the `pages` folder

Also, nothing of this is true if you have a `pages/foo.js` file, access `localhost:3000/foo`, delete the file  and reload the server, then it will crash on all routes, what

**Comment by lfades** [comment] 2020-01-28 22:52
@rafaelalmeidatk It wasn't the case for me in the cases you mentioned 🤔 - Can you share a repo with the issue? or specific steps to make it break

**Comment by rafaelalmeidatk** [comment] 2020-01-28 23:02
Sure, here are all the steps:
1. Turn this flag on: `chrome://flags/#cookies-without-same-site-must-be-secure`
2. Turn this flag on: `chrome://flags/#same-site-by-default-cookies`
3. Restart the browser
4. On the terminal: `$ mkdir crash-test`
5. `$ cd crash-test`
6. `$ npm init -y`
7. `$ npm install --save react react-dom next`
8. `$ mkdir pages`
9. Add this to the scripts:
```
"scripts": {
  "dev": "next",
  "build": "next build",
  "start": "next start"
}
```
10. `$ npm run dev`
11. Go to http://localhost:3000/, see the 404
12. Stop the dev server
13. Start it again
14. Refresh the page, see the error

**Comment by JohannesHome** [comment] 2020-01-30 09:24
There is a similar error with disabled `localStorage` in general. 

When doing so for chrome see [stack-overflow](https://superuser.com/questions/298922/chrome-chromium-disable-html5-localstorage-and-databases-for-all-webpages-or) on how to do it. And using the described scenario of @rafaelalmeidatk the app will fail when accessing the page.

The problem for this specific case for me seems to be that the [prerender-indicator](https://github.com/zeit/next.js/blob/canary/packages/next/client/dev/prerender-indicator.js) is accessing the `localStorage` without testing if it is enabled : 
https://github.com/zeit/next.js/blob/81fd704681fcac4d241e6f94bb45232ddc403e72/packages/next/client/dev/prerender-indicator.js#L43
https://github.com/zeit/next.js/blob/81fd704681fcac4d241e6f94bb45232ddc403e72/packages/next/client/dev/prerender-indicator.js#L74

Not sure if this relates to the other issues.

**Comment by tsvecak** [comment] 2020-04-07 16:19
> edit: looks like it only happens with NPM, I tried to reproduce it using yarn and it works normally.

It happens in my case using both npm and yarn. Just following nextJs tutorial leads to this if you block cookies in your browser.

**Comment by dohomi** [comment] 2020-05-22 14:52
This happens to my `http://localhost:3000/` environment on Storyblok. Is there any possibility that the integration of Storyblok and NextJS can be improved?

**Comment by lfades** [comment] 2020-05-25 23:56
Closing as the issue can't be reproduced anymore in the latest Next.js or with any of the steps provided in here. It was most likely fixed after replacing [HMR with Fast Refresh](https://nextjs.org/blog/next-9-4#fast-refresh)

If the issue persists, feel free to create a new issue with a valid reproduction

**Closed by lfades** 2020-05-25 23:56 UTC

**Comment by dohomi** [comment] 2020-05-26 00:20
@lfades the issue is present for all Storyblok backends. I run on newest stable version of NextJS and the issue just got introduced with FastRefresh

**Comment by lfades** [comment] 2020-05-26 16:56
@dohomi In that case please create a new issue with a reproduction that we can take a look at 🙏

**Comment by codejamninja** [comment] 2020-10-15 21:13
This issue still happens in the latest nextjs when behind an iframe.

```
Error was not caught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at initializeBuildWatcher (webpack-internal:///./node_modules/next/dist/client/dev/prerender-indicator.js:47:38)
    at eval (webpack-internal:///./node_modules/next/dist/client/next-dev.js:96:40)
eval @ next-dev.js?53bc:97
Promise.catch (async)
eval @ next-dev.js?53bc:32
eval @ next-dev.js?53bc:32
./node_modules/next/dist/client/next-dev.js @ main.js?ts=1602796145388:1377
__webpack_require__ @ webpack.js?ts=1602796145388:873
checkDeferredModules @ webpack.js?ts=1602796145388:46
webpackJsonpCallback @ webpack.js?ts=1602796145388:33
(anonymous) @ webpack.js?ts=1602796145388:1015
(anonymous) @ webpack.js?ts=1602796145388:1023
```

**Comment by indify-co** [comment] 2020-12-02 21:08
+1 on @codejamninja's comment

**Comment by timneutkens** [comment] 2020-12-03 13:33
> +1 on @codejamninja's comment

Update to the latest version of Next.js, the prerender indicator was removed.

**Comment by funwhilelost** [comment] 2020-12-24 22:42
> Update to the latest version of Next.js, the prerender indicator was removed.

Specifically the v9 or v10?  I haven't review the v10 updates yet and want to avoid breaking changes.

**Comment by balazsorban44** [comment] 2022-01-29 00:11
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
