### ISSUE TITLE
with-apollo does not work after `npm run build`

### ISSUE THREAD

**Issue by gibsonjoshua55** [zeit/next.js#7330] opened 2019-05-14 13:51 UTC
# Examples bug report

## Example name
with-apollo

## Describe the bug
The example runs with `npm run dev`, but when the project is run after `npm run build` then `npm run start`, the page load creates a 500 internal server error.  See below for the full error.

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. `npx create-next-app --example with-apollo with-apollo-app`
2. `cd with-apollo-app`
3. `npm run build`
4. `npm run start`

## Expected behavior
The example project should run correctly without any modifications.  As it is, there is an internal server error in the base project when the project is built for production rather than ran off of the dev server.

## System information
 - OS: macOS
 - Browser: Chrome
 - Version of Next.js: 8.1.0

## Error
```
Error while running `getDataFromTree` { Invariant Violation: Invariant Violation
    at new InvariantError (PATH/with-apollo-app/node_modules/react-apollo/node_modules/ts-invariant/lib/invariant.js:16:28)
    at Object.finish [as children] (PATH/with-apollo-app/node_modules/react-apollo/react-apollo.cjs.js:22:59)
    at a.render (PATH/with-apollo-app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:64)
    at a.read (PATH/with-apollo-app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:58)
    at renderToStaticMarkup (PATH/with-apollo-app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:53:181)
    at process (PATH/with-apollo-app/node_modules/react-apollo/react-apollo.cjs.js:1043:20)
    at process._tickCallback (internal/process/next_tick.js:68:7) framesToPop: 1, name: 'Invariant Violation' }
{ Invariant Violation: Invariant Violation
    at new InvariantError (PATH/with-apollo-app/node_modules/react-apollo/node_modules/ts-invariant/lib/invariant.js:16:28)
    at Object.finish [as children] (PATH/with-apollo-app/node_modules/react-apollo/react-apollo.cjs.js:22:59)
    at a.render (PATH/with-apollo-app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:64)
    at a.read (PATH/with-apollo-app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:58)
    at renderToString (PATH/with-apollo-app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:53:83)
    at render (PATH/with-apollo-app/node_modules/next-server/dist/server/render.js:86:16)
    at renderPage (PATH/with-apollo-app/node_modules/next-server/dist/server/render.js:211:20)
    at Function.value (PATH/with-apollo-app/.next/server/static/LklYisY6_HqrmKOShcflL/pages/_document.js:812:41)
    at Object.loadGetInitialProps (PATH/with-apollo-app/node_modules/next-server/dist/lib/utils.js:42:35)
    at Object.renderToHTML (PATH/with-apollo-app/node_modules/next-server/dist/server/render.js:218:36) framesToPop: 1, name: 'Invariant Violation' }
```

**Comment by Mohamed-Abubucker** [comment] 2019-05-14 18:00
Hi, 
 me too facing the same issue. its stopped my work. please suggest me an idea to resolve this.

**Comment by lfades** [comment] 2019-05-14 21:41
Hi guys, I reproduced the issue and confirmed that it works in the latest release of `next@canary`, can you again there 🙏 ?

**Comment by gibsonjoshua55** [comment] 2019-05-15 17:54
Running it with `next@canary` worked for me

**Comment by lfades** [comment] 2019-05-16 02:53
@gibsonjoshua55 Amazing, I'm going to close this issue now because it's working in canary and the next release will be out soon.

**Closed by lfades** 2019-05-16 02:53 UTC
