### ISSUE TITLE
provide example with react-router v6

### ISSUE THREAD

**Issue by sessionboy** [zeit/next.js#12110] opened 2020-04-22 15:26 UTC
# Feature request
Provide examples of using react-router in next.

The `next/router` is great, but it is too simple and can usually cope with general applications, but it is very difficult when it comes to complex applications.
I hope to use more professional and powerful routing tools, such as react-router, which is the industry leader.
Hope team can provide the official example of [react-router v6](https://github.com/ReactTraining/react-router/releases).

**Comment by rafaelalmeidatk** [comment] 2020-04-23 06:57
Currently Next doesn't support react-router, you can track the progress in #1632

**Comment by timneutkens** [comment] 2020-04-23 07:53
Duplicate of #1632

**Closed by timneutkens** 2020-04-23 07:53 UTC

**Comment by balazsorban44** [comment] 2022-01-30 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
