### ISSUE TITLE
Can't get the status code on client side

### ISSUE THREAD

**Issue by lcswillems** [zeit/next.js#8912] opened 2019-09-30 08:50 UTC
# Bug report

## Describe the bug

I use this code to get the status code:

```
Page.getInitialProps = ({ res, err }) => {
  const statusCode = res ? res.statusCode : err ? err.statusCode : null;
  return { statusCode };
};
```

but it doesn't always give me the status code.

## To Reproduce

1. Clone this repository: https://github.com/lcswillems/next-bug

2. `yarn dev`

3. Go to `http://localhost:3000/djhfdkfjkh` (an error page):

![image](https://user-images.githubusercontent.com/5437552/65862952-8ee8b080-e36f-11e9-8879-cc558118779e.png)

The status code is **404**.

4. Go to the home page by clicking on the link

5. Go back to the error page by clicking on the back history arrow:

![image](https://user-images.githubusercontent.com/5437552/65863120-d707d300-e36f-11e9-9e2b-9b8455826284.png)

6. The status code is now **null**.

![image](https://user-images.githubusercontent.com/5437552/65863172-f141b100-e36f-11e9-8317-1ca101c2ce1c.png)

## Expected behavior

I would expect it to be 404.

## System information

- OS: linux
- Browser (if applies) : chrome
- Version of Next.js: 9.0.7

**Comment by c0b41** [comment] 2019-09-30 09:01
`getInitialProps` only call server side.

**Comment by lcswillems** [comment] 2019-09-30 09:03
No, it is called on server side and client side. In my example, it is called on both.

**Comment by timneutkens** [comment] 2019-09-30 09:17
`res` is only available on the server side so it's expected and not a bug based on your code. However it seems that you're referring to `/_error` and that the documentation is slightly different from the actual `getInitialProps` we use internally. The correct method would be:

```js
Page.getInitialProps = ({ res, err }) => {
  const statusCode = res && res.statusCode ? res.statusCode : err ? err.statusCode : 404
  return { statusCode };
};
```

To split that out:

```
if(res && res.statusCode) {
  return res.statusCode
} else {
  if(err) {
    return err.statusCode
  }
  return 404
}
```

If `/_error` is rendered without an `err` it's a 404 basically. I'll update the docs!

**Comment by timneutkens** [comment] 2019-09-30 09:19
Fixed in https://github.com/zeit/next.js/commit/0bcd1fc39bb07f67b94238a0e867e9c3fe73a163

**Comment by lcswillems** [comment] 2019-09-30 09:20
Okay thank you for your fast answer!

**Closed by timneutkens** 2019-09-30 09:19 UTC

**Comment by balazsorban44** [comment] 2022-01-31 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
