### ISSUE TITLE
SyntaxError: JSON5: invalid end of input at 1:1

### ISSUE THREAD

**Issue by hieusmiths** [zeit/next.js#12509] opened 2020-05-05 10:06 UTC
# Bug report
SyntaxError: JSON5: invalid end of input at 1:1

I can't understand how to it error occur.

Thank you.

**Comment by jamesmosier** [comment] 2020-05-05 14:14
You'll need to provide a code sample in order for this to be investigated.

**Comment by timneutkens** [comment] 2020-05-06 09:06
Closing this as the issue template was ignored.

**Comment by mekeor** [comment] 2020-05-16 17:53
@hieusmiths, i also came across this issue. i think it was because i had an *empty* `jsconfig.json` file in the root directory of my repository. i think the issue was solved after i put `{}` into this file so that it was valid json.

**Closed** 2020-05-18 16:07 UTC

**Comment by thinkjrs** [comment] 2020-10-22 16:28
@mekeor Thanks--you helped trigger my memory! 

I experienced this due to an empty `tsconfig.json`, as I had not yet run the dev server. Having previously setup Jest and other scaffolding items, attempting to lint was throwing the `SyntaxError` since, in fact, my empty `tsconfig.json` was not valid JSON. 

Of course this is [well documented](https://nextjs.org/docs/basic-features/typescript), but probably an easy miss for myself and others when moving quickly. Hope this helps any future travelers.

**Comment by balazsorban44** [comment] 2022-01-29 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
