### ISSUE TITLE
Getting a directory list when using `src/pages` and `now dev`

### ISSUE THREAD

**Issue by rudeayelo** [zeit/next.js#9007] opened 2019-10-09 09:07 UTC
# Bug report

## Describe the bug

When using Next's new `src/pages` support through `now dev` (because I'm using `now secrets`) I'm getting a directory list view listing only the _package.json_ instead of the `index` page.

## To Reproduce

1. Create a new Next app `npx create-next-app now-dev-src-pages`
2. Move the `pages` and the `components` directory to an `src` folder in the root folder
3. Launch dev mode using `now dev` 

## Expected behavior

When visiting `http://localhost:3000` I should see the `src/pages/index.js` page contents.

## Screenshots

![image](https://user-images.githubusercontent.com/140042/66467493-d0bada80-ea84-11e9-9003-f9b9610df64d.png)

## System information

- OS: [macOS]
- Version of Next.js: 9.1.1

## Additional info

Visiting `http://localhost:5000` instead, I get to see the actual expected behaviour.

**Comment by ijjk** [comment] 2019-10-09 11:27
Hi, this appears to be a duplicate of https://github.com/zeit/now/issues/3133 I opened a PR addressing it there and am going to close this issue in favor of that one

**Closed by ijjk** 2019-10-09 11:27 UTC

**Comment by balazsorban44** [comment] 2022-01-31 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
