### ISSUE TITLE
weird render for first time render from server

### ISSUE THREAD

**Issue by vitthaljkulkarni** [zeit/next.js#9570] opened 2019-11-28 07:05 UTC
![Better1](https://user-images.githubusercontent.com/57615109/69784128-11101c80-11db-11ea-9df2-e070834d4978.jpg)
# Bug report

## Describe the bug

I have an issue with render from the server. On the first load of the page, the layout goes for a toss. However it is corrected on subsequent renders via navigating the pages. Surprisingly the weired layout also appears on a browser refresh. I have tested it with both Chrome and Microsoft Edge but same problem.
The app was created using standard boilerplate 'create-next-app' and then I just added a few of my pages. See screenshots below
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'app url'
2. See how weird the layout is.
3. Navigate away to any other page and come back again and see how the layout is again.
4. Do a browser refresh and see how weird the layout is again.

## Expected behavior

The layout should be consistent and clean.

## Screenshots
![Error1](https://user-images.githubusercontent.com/57615109/69784129-12414980-11db-11ea-84ae-a6ea90817af5.jpg)

![Better1](https://user-images.githubusercontent.com/57615109/69784326-84b22980-11db-11ea-9aa8-4ec57a48576f.jpg)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2]

**Comment by timneutkens** [comment] 2019-11-28 09:09
```
Go to 'app url'
See how weird the layout is.
Navigate away to any other page and come back again and see how the layout is again.
Do a browser refresh and see how weird the layout is again.
```

Which app url? No repository is provided which means this issue is not actionable.

I'm going to close this as a clear and concise reproduction is needed to help you.

**Closed by timneutkens** 2019-11-28 09:09 UTC
Labels: Can't Reproduce

**Comment by vitthaljkulkarni** [comment] 2019-11-28 15:04
See attached screenshot please. Also app at http://junkbonds.herokuapp.com/Vitthal On 28 Nov 2019 14:39, Tim Neutkens <notifications@github.com> wrote:Go to 'app url'
See how weird the layout is.
Navigate away to any other page and come back again and see how the layout is again.
Do a browser refresh and see how weird the layout is again.

Which app url? No repository is provided which means this issue is not actionable.
I'm going to close this as a clear and concise reproduction is needed to help you.

**Comment by balazsorban44** [comment] 2022-01-30 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
