### ISSUE TITLE
Deploying to AWS errors

### ISSUE THREAD

**Issue by abelovic** [zeit/next.js#923] opened 2017-01-29 22:46 UTC
I'm trying to get the Apollo example to run on AWS and its failing.

My package.json

{
  "name": "apollo",
  "version": "1.0.0",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start -p 8081"
  },
  "cacheDirectories": [
    "nextjs/node_modules"
  ],
  "dependencies": {
    "apollo-client": "^0.8.1",
    "es6-promise": "^4.0.5",
    "graphql": "^0.9.1",
    "graphql-tag": "^1.2.3",
    "isomorphic-fetch": "^2.2.1",
    "next": "^2.0.0-beta.20",
    "react-apollo": "^0.9.0",
    "react-redux": "^5.0.2",
    "redux": "^3.6.0",
    "redux-thunk": "^2.1.0"
  },
  "author": "",
  "license": "ISC"
}

In the above I changed the following:

- Added isomorphic-fetch and es6-promise packages (even though it worked locally) or it would fail. Seemed to fix that error.
- Added cacheDirectories (from deployment Heroku repo). Didn't see any other advice that aplpied to this case.
- Changed the port in the start to run on 8081 (AWS Beanstalk uses this)
- Use https://codeship.com to run npm install and npm run build before hand so it should be built correctly. 

Everything runs perfectly on my local box but fails when trying to run on AWS :(

AWS Container options:

Proxy server: nginx
Node version: 6.9.1
Node command: npm start

AWS Environment variables:

NODE_ENV: production
PORT: 8081

Here is the AWS error log:

-------------------------------------
/var/log/nodejs/nodejs.log
-------------------------------------
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/app/current/.next/dist/pages/_error.js:7:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module '/home/rof/src/github.com/abelovic/apollo/node_modules/next/node_modules/babel-runtime/core-js/object/get-prototype-of'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/app/current/.next/dist/pages/_error.js:7:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }

> apollo@1.0.0 start /var/app/current
> next start -p 8081

> Ready on http://localhost:8081

> apollo@1.0.0 start /var/app/current
> next start -p 8081

> Ready on http://localhost:8081
{ Error: Cannot find module '/home/rof/src/github.com/abelovic/apollo/node_modules/next/node_modules/react/react.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/app/current/.next/dist/pages/index.js:7:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module '/home/rof/src/github.com/abelovic/apollo/node_modules/next/node_modules/babel-runtime/core-js/object/get-prototype-of'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/app/current/.next/dist/pages/_error.js:7:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module '/home/rof/src/github.com/abelovic/apollo/node_modules/next/node_modules/babel-runtime/core-js/object/get-prototype-of'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/app/current/.next/dist/pages/_error.js:7:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }

I get an internal server error when trying to run the site...

Any help/suggestions would be greatly appreciated!

**Comment by arunoda** [comment] 2017-01-30 02:25
Seems like you don't have `node_modules` available when the Next.js app is started.

**Comment by abelovic** [comment] 2017-01-30 18:34
@arunoda Thanks for your response - I think you were on the right track. To test this, I downloaded the zip from S3 and ran it locally and I get the following error:

"next" is not recognized as an internal or external command, operable program or batch file.

What is interesting is that next *is* in my node_modules folder and the .next folder exists as you would expect it. If I run "npm install next" again it works correctly (only installing next and nothing else).

What I am doing is running npm install and then npm run build in (codeship) and then copying everything over to AWS. Can you think of a reason why only the next module does not install correctly? Every other module works fine and I only have to reinstall next for it to work :/

I guess I could try to do the npm install/next build with ebextensions config file in AWS but I would rather do it in codeship so I can catch errors (with my continuous deploys) before trying to move it out to AWS

Thanks again for your help!

**Comment by abelovic** [comment] 2017-01-30 18:39
Also here are the commands I run in codeship before sending to AWS:

nvm 6.9.1
npm install
npm run build

**Comment by timneutkens** [comment] 2017-01-30 19:22
@abelovic what do you run on the server? `npm run start`?

**Comment by abelovic** [comment] 2017-01-30 20:17
Yeah. I have set the following in the container options in the AWS console configuration:

Node command:

**npm run start**
 Command to start the Node.js application. If an empty string is specified, app.js is used, then server.js, then "npm start" in that order.

...and from my json package above I specify the port (because that's what nginx is configured to listen on in EB):

...
"start": "npm run start -p 8081"
....

Other AWS settings I have:

Container options: 

Proxy server: nginx (default)
Node version: 6.9.1 (latest AWS supports which I match in my build)
Gzip Compression: true (default)

Environment Properties (not sure if I needed these but set them anyways):

NODE_ENV: production
PORT: 8081

**Comment by benhjames** [comment] 2017-01-31 16:35
Possible dupe of #198 and by extension #360?

The build path `/var/app/current` doesn't match the runtime path `/home/rof/src/github.com/abelovic/apollo`, so the output of absolute paths by webpack may cause it to fail. Rebuilding on AWS would fix up the absolute paths to match - I guess that's why you're seeing that behaviour. :)

**Closed** 2017-06-11 21:33 UTC
Labels: Type: Question

**Comment by costasapostolopoulos** [comment] 2018-02-07 17:31
@abelovic I am getting the same error and it was working find a few days ago. Have you found the issue why this is happening?
