### ISSUE TITLE
Last two canary releases haven’t been published to npm

### ISSUE THREAD

**Issue by 4cm4k1** [zeit/next.js#6095] opened 2019-01-20 22:42 UTC
The latest canary release of `next` available on npm is `8.0.0-canary.7`. Not sure why?

**Comment by timneutkens** [comment] 2019-01-20 22:43
Not entirely sure why, it's caused by lerna for sure, I've asked @dav-is to look into it.

**Comment by dav-is** [comment] 2019-01-21 15:26
The issue had to do with the committed `yarn.lock` file being out of date.

Fixed and released `8.0.0-canary.10` :+1:

**Closed by dav-is** 2019-01-21 15:26 UTC
Labels: Priority: OMG Maximum, Type: Bug

**Comment by timneutkens** [comment] 2019-01-21 15:51
Sorry for the inconvenience 🙏
