### ISSUE TITLE
Astroturf css template broken after v9.0.3

### ISSUE THREAD

**Issue by vinpac** [zeit/next.js#8523] opened 2019-08-26 18:07 UTC
# Bug report

## Describe the bug

Using `css` template to define styles with `astroturf` stopped working in `next@9.0.3`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to example `with-astroturf`
2. Change `styled.button` to:
```
const s = css`
  .button {
    color: black;
    border: 1px solid black;
    background-color: white;

    &.primary {
      color: blue;
      border: 1px solid blue;
    }

    &.color-green {
      color: green;
    }
  }
`
```

3. See error
```
[ wait ]  compiling ...
[ error ] ./pages/index-s.css
AstroturfLoaderError: /Users/murdock/lab/sandbox/next.js/examples/with-astroturf/pages/index-s.css: Unexpected token (2:2)

  1 | 
> 2 |   .button {
    |   ^
  3 |     color: black;
  4 |     border: 1px solid black;
  5 |     background-color: white;
ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/astroturf/loader.js):
AstroturfLoaderError: /Users/murdock/lab/sandbox/next.js/examples/with-astroturf/pages/index-s.css: Unexpected token (2:2)
```

## Expected behavior

Styles should be compiled without any errors

## Screenshots

![image](https://user-images.githubusercontent.com/9030018/63711977-07a99980-c813-11e9-9ac7-9c76e46a834d.png)

## System information

- OS: macOS
- Version of Next.js: v9.0.5

## Additional context

- I didn't test in a project without Typescript
- At version v9.0.2 it was working with no errors

**Comment by timneutkens** [comment] 2020-01-02 22:02
Closing as no pr was opened.

**Closed by timneutkens** 2020-01-02 22:02 UTC

**Comment by balazsorban44** [comment] 2022-01-30 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
