### ISSUE TITLE
Embedding scripts with multiple Head components.

### ISSUE THREAD

**Issue by Lyonsclay** [zeit/next.js#1181] opened 2017-02-16 16:03 UTC
I am making a basic blog and I want to embed a CodePen and a Github gist in different locations of the page. It appears that Next.js only recognizes one Head component per page. 

My question is how to place these components at different places on the page and make sure they all load with initial page load.

```
import React from 'react'
import Head from 'next/head'
const title = 'Animation Basics'
const P1 = 'Put it on the Graphics Card.'
const CodePen1 = () => (
  <div>
    <Head>
      <script async src="https://production-assets.codepen.io/assets/embed/ei.js"></script>
    </Head>
    <p data-height="256" data-theme-id="light" data-slug-hash="WwVeQM" data-default-tab="result" data-user="Lyonsclay" data-embed-version="2" data-pen-title="Shadowing CSS Animation - static" data-preview="true" className="codepen">See the Pen <a href="https://codepen.io/Lyonsclay/pen/WwVeQM/">Shadowing CSS Animation - static</a> by Clay Morton (<a href="http://codepen.io/Lyonsclay">@Lyonsclay</a>) on <a href="http://codepen.io">CodePen</a>.</p>
  </div>
)
const P2 = 'Don\'t get too crazy or nothing. Just focus on declaring the result of the animation rather than how to get there.'
const Gist1 = () => (
  <Head>
    <script async src="https://gist.github.com/Lyonsclay/7bea4d320269a377eba25bc69a7e57b3.js?file=ShadowDom.js"></script>
  </Head>
)

export default () => (
  <div>
    <h3>{title}</h3>
    <p>{P1}</p>
    <CodePen1/>
    <p>{P2}</p>
    <Gist1 />
  </div>
)
```

**Comment by impronunciable** [comment] 2017-02-16 16:22
Hi @Lyonsclay `next.js` is actually loading both scripts

![screen shot 2017-02-16 at 1 19 10 pm](https://cloud.githubusercontent.com/assets/165799/23029829/890bde74-f44a-11e6-90d8-922fb1a77df1.png)

The issue is `https://gist.github.com/Lyonsclay/7bea4d320269a377eba25bc69a7e57b3.js?file=ShadowDom.js` uses `document.write` to inject the code and you are placing it in the `<head>` so that would (at least) not be rendered.

One way to make this work is to remove the `<Head>` wrapper from the gist and remove the `async` tag and just add the gist wherever you want to place it in the document.

Again, as this is not a `next` related bug I'm closing. Feel free to reopen if you find out this was actually a `next` issue and thanks for reporting :)

**Closed by impronunciable** 2017-02-16 16:22 UTC

**Comment by Lyonsclay** [comment] 2017-02-16 16:38
Hi @impronunciable! I did put the Github gist script outside of the Head component at first, but then it doesn't seem to load unless I refresh the page. 

```
import React from 'react'
import Head from 'next/head'
const title = 'Animation Basics'
const P1 = 'Put it on the Graphics Card.'
const CodePen1 = () => (
  <div>
    <Head>
      <script async src="https://production-assets.codepen.io/assets/embed/ei.js"></script>
    </Head>
    <p data-height="256" data-theme-id="light" data-slug-hash="WwVeQM" data-default-tab="result" data-user="Lyonsclay" data-embed-version="2" data-pen-title="Shadowing CSS Animation - static" data-preview="true" className="codepen">See the Pen <a href="https://codepen.io/Lyonsclay/pen/WwVeQM/">Shadowing CSS Animation - static</a> by Clay Morton (<a href="http://codepen.io/Lyonsclay">@Lyonsclay</a>) on <a href="http://codepen.io">CodePen</a>.</p>
  </div>
)
const P2 = 'Don\'t get too crazy or nothing. Just focus on declaring the result of the animation rather than how to get there.'
const Gist1 = () => (
  <script src="https://gist.github.com/Lyonsclay/7bea4d320269a377eba25bc69a7e57b3.js?file=ShadowDom.js"></script>
)

export default () => (
  <div>
    <h3>{title}</h3>
    <p>{P1}</p>
    <CodePen1/>
    <p>{P2}</p>
    <Gist1 />
  </div>
)
```

**Comment by impronunciable** [comment] 2017-02-16 16:44
@Lyonsclay It uses document.write, it will work just when you refresh the page. Take a look at this to see if it helps you https://stackoverflow.com/questions/30429361/how-to-embed-a-gist-using-reactjs

**Comment by Lyonsclay** [comment] 2017-02-16 16:46
Thanks @impronunciable that Stackoverflow post looks promising:)
