### ISSUE TITLE
"Unexpected fiber popped" / "An unexpected error has occurred"

### ISSUE THREAD

**Issue by ryaninvents** [zeit/next.js#8886] opened 2019-09-28 00:10 UTC
# Bug report

## Describe the bug

At least two of the NextJS examples do not work when run "out of the box".

## To Reproduce

1. Follow the steps in either of these two READMEs:
    - [nextjs-with-typescript](https://github.com/mui-org/material-ui/blob/master/examples/nextjs-with-typescript/README.md)
    - [hello-world](https://github.com/zeit/next.js/blob/canary/examples/hello-world/README.md)
2. Run `npm install && npm run dev`.
    - React will report "Unexpected fiber popped" and "Unexpected pop" in the console.
    - In the Material UI example, buttons will not demonstrate the ripple effect when clicked. In my application, the effects are more severe, leading to loss of interactivity.
3. Deploy using `npx now`. Resulting application will report errors.
    - [nextjs-with-typescript](https://nextjs-with-typescript.ryaninvents.now.sh/) deployment
    - [hello-world](https://hello-world.ryaninvents.now.sh/) deployment

## Expected behavior

Given examples work when deployed and run.

## System information

- OS
    - Development: Ubuntu 18.04 LTS
    - Deployment: Zeit Now platform
- Browser: Reproducible in Chrome and Firefox
- Version of Next.js: 9.0.6 (current `latest`)

**Comment by martindavid** [comment] 2019-09-28 00:38
I got this error as well. Did some debugging, and found out it's happening on React `16.10.0`. If you're using `16.9.0` it works fine.

**Comment by willtrking** [comment] 2019-09-28 00:42
Same issue here, and same resolution as @martindavid

**Comment by ogdenstudios** [comment] 2019-09-28 03:13
Same issue here. Just going through the [getting started tutorial](https://nextjs.org/learn/basics/getting-started/setup) and the index page isn't clearing, rendering itself twice, etc. etc.

**Comment by Timer** [comment] 2019-09-28 03:19
Hi everyone! Like the error message suggests, this may be a bug with React 16.10.

Please **downgrade** to `16.9.0` for the time being. I've opened an issue in the React project to track this: https://github.com/facebook/react/issues/16938.

Thanks!

**Comment by timneutkens** [comment] 2019-09-28 10:45
Keeping this open until the PR is on stable.

**Comment by timneutkens** [comment] 2019-09-28 10:50
Just released a new canary (will be on npm soon) https://github.com/zeit/next.js/releases/tag/v9.0.7-canary.9

**Comment by timneutkens** [comment] 2019-09-28 12:59
Released on stable too: https://github.com/zeit/next.js/releases/tag/v9.0.7.

Note that in general we do not ship stable versions on weekends but this issue affects basically everyone getting started with Next.js / React and everyone upgrading.

**Comment by timneutkens** [comment] 2019-09-28 13:02
I'm going to close this issue as the patch has been merged on both canary/stable and this is an upstream issue raised by @timer here: https://github.com/facebook/react/issues/16938

**Closed by timneutkens** 2019-09-28 13:02 UTC
Labels: Is Upstream

**Comment by acdlite** [comment] 2019-09-28 18:31
This is now fixed in [v16.10.1](https://github.com/facebook/react/releases/tag/v16.10.1).

However, it's more like a workaround to fail gracefully because the behavior is not supported. It only accidentally worked in 16.9. We will warn in a future minor.

So we need to figure out how to address this in Next.

More context here: https://github.com/facebook/react/issues/16938#issuecomment-536207871

**Comment by ryaninvents** [comment] 2019-09-30 14:13
Thanks so much for your help identifying and fixing this! Sorry I didn't recognize that it was an upstream error; I made some incorrect assumptions based on the error message.

**Comment by balazsorban44** [comment] 2022-01-31 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
