### ISSUE TITLE
Add Fauna Auth Example

### ISSUE THREAD

**Issue by johnpolacek** [zeit/next.js#9501] opened 2019-11-22 20:23 UTC
# Add Fauna Authentication Example

Love the new `with-graphql-faunadb` example. I was able to add an Auth0 login to it from your other example, but would love to see an example of how to use [FaunaDB User Authentication](https://app.fauna.com/tutorials/authentication) with next.js, if possible. Having an example of an integrated graphql solution for data and auth that doesn’t require a page redirect would be 💯 !

What do you say @lfades @fauna-brecht ?

**Comment by fauna-brecht** [comment] 2019-11-25 11:04
Yes, that sounds definitely like a good idea! 
We will look into that

**Comment by j0lv3r4** [comment] 2019-12-04 17:33
I have code in a project that can serve as an example that does exactly this. It's using Python, tho, but shouldn't be a problem to refactor it with Node.

I can work in a PR if @fauna-brecht isn't too close to do it.

**Comment by fauna-brecht** [comment] 2019-12-04 17:36
At the moment my list is indeed still full with other things :/. Would be
great to have such an example.

**Comment by waptik** [comment] 2020-02-06 09:49
> I have code in a project that can serve as an example that does exactly this. It's using Python tho, but shouldn't be a problem to refactor it to Node.
> 
> I can work in a pull request if @fauna-brecht isn't too close to do it.

I saw the repo earlier this week. It looks great.
Any news about the node version of the API?

**Comment by j0lv3r4** [comment] 2020-02-06 15:53
hey thanks, @waptik. Take a look at the example that got merged https://github.com/zeit/next.js/tree/canary/examples/with-cookie-auth-fauna

**Closed** 2020-02-06 16:30 UTC
Labels: good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-30 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
