### ISSUE TITLE
Client side routing break in production

### ISSUE THREAD

**Issue by geekyoperand** [zeit/next.js#10755] opened 2020-02-29 20:08 UTC
# Bug report
The intention is to import a CSS file from a third party library that resides in a folder within node_modes. This CSS chunk is not bundled on initial page load (which is fine, I assume, because the client hasn't navigated to the page where the import happens - yet).
But as soon as one tries to navigate to the page that has the import statement (via client-side routing), nothing seems to happen.

## Describe the bug

I am getting a CSS break issue while routing from one link to another on client-side in production build only. In development build, it is working fine.

## To Reproduce

1. Go to this link http://ec2-3-134-112-176.us-east-2.compute.amazonaws.com:3000/english-test.
2. Click on header title Fluency Hub on the top left header.
3. You will get navigated to another page you can see the page with broken CSS.
4/ Now, refresh the page its CSS works well but after again repeating these steps gave issue only in the production build.
5. If you are cloning the repo then just clone the repo from this link https://github.com/geekyoperand/fluencyhub.git. 
6. Now run the ```npm run start:staging``` for producing issue which will run a production build of next.js.
7. If you run just ```npm run start``` It will work well because it will run a development build.

## Expected behaviour
CSS must not get breaked while performing client-side routing in the production.

## Screenshots
after client side routing expected :
![image](https://user-images.githubusercontent.com/52500177/75614235-c21caf00-5b5c-11ea-8451-15c07805b4d7.png)

after client-side routing current :
![image](https://user-images.githubusercontent.com/52500177/75614217-a3b6b380-5b5c-11ea-9d82-fc5c28890738.png)

## System information

- OS: macOS, Windows
- Browser : chrome
- Version of Next.js: 9.2.0

**Comment by timneutkens** [comment] 2020-03-01 14:26
https://github.com/geekyoperand/fluencyhub/blob/master/next.config.js#L6

You're using next-css which means likely what you're running into is: https://github.com/zeit/next-plugins/issues/282

It can be resolved by using built-in CSS support: https://nextjs.org/blog/next-9-2

Closing as duplicate of https://github.com/zeit/next-plugins/issues/282

**Closed by timneutkens** 2020-03-01 14:26 UTC

**Comment by geekyoperand** [comment] 2020-03-01 18:06
> https://github.com/geekyoperand/fluencyhub/blob/master/next.config.js#L6
> 
> You're using next-css which means likely what you're running into is: [zeit/next-plugins#282](https://github.com/zeit/next-plugins/issues/282)
> 
> It can be resolved by using built-in CSS support: https://nextjs.org/blog/next-9-2
> 
> Closing as duplicate of [zeit/next-plugins#282](https://github.com/zeit/next-plugins/issues/282)

@timneutkens I have tried removing the next-css as suggested by you as I read the blog carefully but still not able to fix my issue. I have updated my repo.
Can you try once running at your locally and suggest a better method?

**Comment by balazsorban44** [comment] 2022-01-30 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
