### ISSUE TITLE
getStaticProps does not work in _app.js

### ISSUE THREAD

**Issue by desmap** [zeit/next.js#13303] opened 2020-05-24 07:57 UTC
# Bug report

## Describe the bug

getStaticProps does not work in `_app.js` but only in other `pages/` files. Since this is not documented I assume it's a bug.

If this was intended but just not documented, then this should be treated as a feature request.

## To Reproduce

https://github.com/desmap/next-minirepo and check the top of the page which shows 'undefined and welcome!'

## Expected behavior

Top of the page should show 'Hello and welcome'

## System information

- OS: 18.04
- Version of Next.js: 9.4.2
- Version of Node.js: 12.16.3

## Motivation

I try to get a dir full of reducers for redux without stating them explicitly once at build.

**Comment by desmap** [comment] 2020-05-24 10:24
Just found this https://github.com/zeit/next.js/discussions/10949 where it's stated that this is an initial restriction for getServerSideProps. Not clear why getStaticProps is also restricted since it doesn't affect the app at run-time.

**Comment by timneutkens** [comment] 2020-05-24 13:39
> Not clear why getStaticProps is also restricted since it doesn't affect the app at run-time.

It's the same implementation

Duplicate of #12434

**Closed by timneutkens** 2020-05-24 13:39 UTC

**Comment by balazsorban44** [comment] 2022-01-30 03:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
