### ISSUE TITLE
Route definition in page files

### ISSUE THREAD

**Issue by pragmaticivan** [zeit/next.js#5558] opened 2018-10-30 21:27 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
Would be nice to define a route with params inside the page file instead of defining it in the server file.

## Describe the solution you'd like
The file would have a reserved export `route` that should be an Object.

```js
import React from 'react'

export const route = {
  path: '/products/:id',
  method: 'get',
};

export default class extends React.Component {
  static async getInitialProps({ req }) {
    const id = req.params.id;
    return { id }
  }

  render() {
    return (
      <div>
        Hello World {this.props.id}
      </div>
    )
  }
}
```

or 

```js
import React from 'react'

export default class extends React.Component {

  static route = {
    path: '/products/:id',
    method: 'get',
  };

  static async getInitialProps({ req }) {
    const id = req.params.id;
    return { id }
  }

  render() {
    return (
      <div>
        Hello World {this.props.id}
      </div>
    )
  }
}
```

## Additional context
That would keep development simple when you need url params defined.

**Comment by goldenshun** [comment] 2018-11-27 05:47
The static `route` definition fits well with the current framework (it doesn't compromise code splitting like `react-router` or other routers out there). I rather like keeping the route definition local to the page that will serve it because it makes the impact of code or route changes more obvious.

`req` is a server only parameter in `getInitialProps` so I don't think you can pass the params along with it. An alternative would be to pass `params` as a separate property or to merge them with `query`, which is how [next-routes](https://github.com/fridays/next-routes) works.

A few downsides to this approach:
- No clear way to control resolution order
- Loading all routes requires loading all page files. This might conflict with next's just-in-time compilation in dev mode.

**Comment by pragmaticivan** [comment] 2018-11-27 06:43
I'm not very familiar with the core implementation of the framework, but I assume the default routing system based on pages does just the same thing, it creates routes based on the filename. Adding a route constant or even defining it as a static attribute of the component just like `getInitialProps` would be reasonable the current implementation as it will be just overwriting the routing.

`getInitialProps` for instance, already receives `req` (ex: https://github.com/zeit/next.js/#fetching-data-and-component-lifecycle) I don't think there is nothing new here.

About the next just in time compilation, I agree, seems to be a problem.

Thanks for taking the time and taking a look at this @goldenshun !

**Comment by goldenshun** [comment] 2018-11-27 06:50
Read further in the docs for `getInitialProps` and you'll see this:

> req - HTTP request object (server only)

**Comment by pragmaticivan** [comment] 2018-11-27 06:55
> For the initial page load, getInitialProps will execute on the server only. getInitialProps will only be executed on the client when navigating to a different route via the Link component or using the routing APIs.

Not sure what would be the issue here. When navigating via client, this becomes a XHR request, right?

**Comment by goldenshun** [comment] 2018-11-27 07:00
No, `req` is undefined when navigating on the client. What xhr request would it be?

**Comment by goldenshun** [comment] 2018-11-28 02:58
Now you lost me @pragmaticivan. What problem are you trying to solve with all of that?

**Comment by pragmaticivan** [comment] 2018-11-28 04:08
The first one in the task. Defining a routing system in the component Page without needing to defining it using a server file, and be able to manage the initial props on SSR + SPA using relatively the same code.

**Comment by timneutkens** [comment] 2019-08-09 15:50
Closing this as #7607 has landed.

**Closed by timneutkens** 2019-08-09 15:50 UTC
Labels: Type: Feature Request

**Comment by balazsorban44** [comment] 2022-01-31 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
