### ISSUE TITLE
Stuck at compiling

### ISSUE THREAD

**Issue by Glutch** [zeit/next.js#7458] opened 2019-05-29 16:18 UTC
# Examples bug report

## Example name

[Fetching Data for Pages](https://nextjs.org/learn/basics/fetching-data-for-pages/setup)

## Describe the bug

```
> Ready on http://localhost:3000
[ wait ]  compiling ...
[ event ] client pings, but there's no entry for page: /_error
[ event ] build page: /post
[ wait ]  compiling ...
```

## To Reproduce

git clone https://github.com/zeit/next-learn-demo.git
cd next-learn-demo
cd 6-fetching-data
npm install
npm run dev

## Expected behavior

Compiling to complete

## System information

- OS: macOS
- Browser: Chrome
- Version of Next.js: 8.0.3

**Comment by ijjk** [comment] 2019-05-29 18:00
This is fixed in the latest version of Next.js `next@canary`. It's not stuck on compiling and you can see it completed by navigating to the address in the browser. It appears stuck from the complete log not being output with a custom server on that version.

**Closed by ijjk** 2019-05-29 18:00 UTC

**Comment by balazsorban44** [comment] 2022-01-31 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
