### ISSUE TITLE
./node_modules/puppeteer/lib/WebSocketTransport.js Module not found: Can't resolve 'ws'

### ISSUE THREAD

**Issue by frantallukas10** [zeit/next.js#9739] opened 2019-12-13 18:38 UTC
here is my repository with my example: https://github.com/frantallukas10/youtu-get/tree/master/demo

I created npm package https://www.npmjs.com/package/youtu-get which use puppeteer package 

I try to create demo for my package... this demo is web page where I used next.js

when I run my command on demo npm run dev I got this error:
![image](https://user-images.githubusercontent.com/16817166/70823374-03b08000-1de0-11ea-811d-0f0db07a66f3.png)

**Comment by ijjk** [comment] 2019-12-13 20:38
Hi, please follow the issue template. The above issue is due to you trying to import the package into your client-side bundle which is not supported. See `ws`'s readme [here](https://github.com/websockets/ws/blob/a4b9e0befb4106620dac93727b0c64c1f76d7423/README.md) explaining this. 

You can use your package server side only by adding an API route that you call to leverage the package.

Closing as this isn't an issue related to Next.js itself

**Closed by ijjk** 2019-12-13 20:38 UTC

**Comment by balazsorban44** [comment] 2022-01-30 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
