### ISSUE TITLE
Cannot read property 'getCompilationErrors' of undefined

### ISSUE THREAD

**Issue by dinfyru** [zeit/next.js#7044] opened 2019-04-16 08:55 UTC
reproduce https://github.com/dinfyru/nextjs-fastifay-reproduce-rendertohtml

next js - 8.0.4
fastify - 2.2.0
error when `app.renderToHTML(req.raw, reply.res, pagePath, queryParams)`

```
TypeError: Cannot read property 'getCompilationErrors' of undefined
    at DevServer.getCompilationError (/home/dinfy/Desktop/work/showcase/front-teasers/node_modules/next/dist/server/next-dev-server.js:162:47)
    at DevServer.renderToHTML (/home/dinfy/Desktop/work/showcase/front-teasers/node_modules/next/dist/server/next-dev-server.js:100:43)
```

**Comment by dinfyru** [comment] 2019-04-21 06:36
any ideas?

**Comment by chrishpowell** [comment] 2019-05-01 11:54
Where is renderToHTML documented?  I see uses of it  but NO documentation.

**Comment by Timer** [comment] 2019-06-14 15:29
Can you remove the usage of arrow functions and see if that fixes is? We may need to bind to the proper `this` within the `app` instance.

**Comment by timneutkens** [comment] 2019-08-10 13:32
Closing this as there was no reply.

**Closed by timneutkens** 2019-08-10 13:32 UTC

**Comment by balazsorban44** [comment] 2022-01-31 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
