### ISSUE TITLE
[Dynamic Routing] When accessing the directory root, I want to match the dynamic root instead of 404

### ISSUE THREAD

**Issue by lightsound** [zeit/next.js#9071] opened 2019-10-14 16:02 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I want to match `**/[foo].tsx` when I access `/` with `**/[foo].tsx` but no `**/index.tsx`. But now, it redirects to 404 page.

I'd like to use SSR at first, but once reaching the browser, I'd like to use shallow transition.

The following situations are possible on the UI:
```
Home | About | Blog
^^^^
 ↑
This route is "/" or "/home".

I want "Home" to be displayed on both "/" and "/home".
```

## Describe the solution you'd like

If `**/[foo].tsx` exists and `**/index.tsx` does not exist, when we access `/`, matching `**/[foo].tsx`.

## Describe alternatives you've considered

I considered following solutions.

- Creating `index.tsx`

```
foo
|-[bar].tsx
|-index.tsx
```
However, this method causes SSR twice, for example, transitioning from `/` to `/about`.

- Using server (302) redirect.

But, this method makes `/` route unusable.

**Comment by timneutkens** [comment] 2019-10-14 19:34
Duplicate of #8053

**Closed by timneutkens** 2019-10-14 19:34 UTC

**Comment by balazsorban44** [comment] 2022-01-31 02:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
