### ISSUE TITLE
SSR outside pages folder

### ISSUE THREAD

**Issue by ndn-rishbh123** [zeit/next.js#8471] opened 2019-08-22 06:34 UTC
# Question about Next.js

Can we do SSR on any page outside pages folder??

**Comment by revskill10** [comment] 2019-08-22 06:56
Currently, no. You have to wait until React releases Suspense on server, then you can.

**Comment by timneutkens** [comment] 2019-08-22 13:29
Your question is quite vague 🤔 Also it ignores the issue template so I'm going to close it. Questions should be posted on https://spectrum.chat/next-js.

**Closed** 2019-08-22 13:29 UTC

**Comment by balazsorban44** [comment] 2022-01-31 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
