### ISSUE TITLE
Next.js Learn E2-lazy-loading-modules build issue

### ISSUE THREAD

**Issue by tsukhu** [zeit/next.js#7093] opened 2019-04-21 07:34 UTC
# Examples bug report

## Example name
Lazy Loading Modules
https://github.com/zeit/next-learn-demo.git 
Step : E2-lazy-loading-modules

## Describe the bug
npm run dev causes runtime issues and the server does not start. Faces the same issue with E3 as well.
I am using Windows 10 for the tutorials

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
`npm install`
`npm run dev`

## Expected behavior
The app starts on port 3000

## Screenshots
```
C:\workspace\next-learn-demo\E2-lazy-loading-modules>npm run dev

> hello-next@1.0.0 dev C:\workspace\next-learn-demo\E2-lazy-loading-modules
> node server.js

[ error ] ./node_modules/next/dist/client/next-dev.js 36:6
Module parse failed: Unexpected token (36:6)
You may need an appropriate loader to handle this file type.
|
|
> import('./noop'); // Support EventSource on Internet Explorer 11
|
| if (!window.EventSource) {
> Ready on http://localhost:3000
TypeError: Cannot read property 'issuer' of null
    at findEntryModule (C:\workspace\next-learn-demo\E2-lazy-loading-modules\node_modules\next\dist\server\hot-reloader.js:60:16)
    at erroredPages (C:\workspace\next-learn-demo\E2-lazy-loading-modules\node_modules\next\dist\server\hot-reloader.js:68:29)
    at HotReloader.getCompilationErrors (C:\workspace\next-learn-demo\E2-lazy-loading-modules\node_modules\next\dist\server\hot-reloader.js:308:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'issuer' of null
    at findEntryModule (C:\workspace\next-learn-demo\E2-lazy-loading-modules\node_modules\next\dist\server\hot-reloader.js:60:16)
    at erroredPages (C:\workspace\next-learn-demo\E2-lazy-loading-modules\node_modules\next\dist\server\hot-reloader.js:68:29)
    at HotReloader.getCompilationErrors (C:\workspace\next-learn-demo\E2-lazy-loading-modules\node_modules\next\dist\server\hot-reloader.js:308:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
## System information
 - OS: Windows 10
 - Version of Next.js: 8.0.3 (https://github.com/zeit/next-learn-demo.git)

## Additional context

The same issue is in the E3 example as well and cannot proceed further in the tutorial.

**Comment by morcs** [comment] 2019-04-21 15:18
I'm getting the same issue on MacOS:

```
➜  E2-lazy-loading-modules git:(master) npm run dev

> hello-next@1.0.0 dev /Users/morcs/code/next-learn-demo/E2-lazy-loading-modules
> node server.js

[ error ] ./node_modules/next/dist/client/next-dev.js 36:6
Module parse failed: Unexpected token (36:6)
You may need an appropriate loader to handle this file type.
|
|
> import('./noop'); // Support EventSource on Internet Explorer 11
|
| if (!window.EventSource) {
```

**Comment by morcs** [comment] 2019-04-21 15:47
I had another issue in the E2 example when I changed the `require`s to `await import`s. I was able to get around this by deleting `node_modules` and `package-lock.json`, then do `yarn install` (rather than `npm install`)

**Comment by timneutkens** [comment] 2019-04-21 17:55
Duplicate of #6240

**Closed by timneutkens** 2019-04-21 17:55 UTC

**Comment by tsukhu** [comment] 2019-04-23 08:50
@morcs Thank you .. using the steps you mentioned did the trick for me as well.
