### ISSUE TITLE
IE11 Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by lailo-ch** [zeit/next.js#2859] opened 2017-08-28 10:42 UTC
Hi y'all

I'm using Next.js V3.0.3 and I'm having problem on IE11 with the following error;

```
Object doesn't support property or method 'assign'
TypError: Object doesn't support property or method 'assign' 
```

## Steps to Reproduce (for bugs)
1. Create a next.js app
2. use `{...oneObject, ...secondObject}` in your code
3. build
4. run

## Context
It's working on Chrome desktop/mobile and it's working on Safari desktop/mobile. It's working on Microsoft Edge but not IE11.

## Your Environment
| Tech    | Version |
|---------|---------|
| next    | 3.0.3 |
| node    | 8.1.0 |
| npm    | 5.0.3 |
| OS      | macOS 0.12.6  |
| browser | Internet Explorer 11 |

Is there any solution to this problem or a hotfix?

Thanks for your help.

**Comment by renancouto** [comment] 2017-08-28 11:59
You can use a [polyfill](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) for that

**Comment by timneutkens** [comment] 2017-08-28 16:45
Duplicate of https://github.com/zeit/next.js/issues/2468

**Closed by timneutkens** 2017-08-28 16:45 UTC
