### ISSUE TITLE
Props from getInitialProps lost on page refresh

### ISSUE THREAD

**Issue by hajdun** [zeit/next.js#5663] opened 2018-11-12 12:53 UTC
# Bug report

## Describe the bug

I use getInitialProps on pages to fetch data and populate the page with it.
If I directly visit the page (I write the address in the search bar of the browser or click a link)
data is fetched properly, page is displayed.

```
class SomeClass extends Component {
  constructor(props) {
    super(props)
  }

  static async getInitialProps () {

    let res = undefined
      try {
        res = await someRequest()
      } catch (err) {
        console.log("Requests failed", err)
      }
    }

    return {      res    }
  }
(...)
  render () {
    const { res } = this.props;
    return (
      <SomeComponent res={res} />

```
I also checked the example (https://github.com/zeit/next.js#fetching-data-and-component-lifecycle) but I see no difference.

## To Reproduce
1. Go to '/somepage'
2. Everything fetched and rendered
3. Refresh page  '/somepage'
4. All props are lost ("res" deleted)
no related error is shown

## Expected behavior
Props are not lost, page can be refreshed as in the example and/or helpful error message is shown

## System information
 - OS: Ubuntu
 - Version of Next.js: "next": "^5.1.0",

## Additional context
 "react": "^16.3.1",
same behavior with isomorphic-unfetch and isomorphic-fetch
 "isomorphic-unfetch": "^2.1.1",

I use redux, but I don't store page props there.

**Comment by timneutkens** [comment] 2018-11-12 13:21
The most logical explanation would be that your request fails, because then it would be set to undefined as per your code. This is definitely not a bug in Next.js as we have tests for getInitialProps behavior and it hasn't changed in 1,5 years. If you provide a full reproduction we might be able to help. This is a question so I'm going to close the issue as per the issue template asking questions to be posted on https://spectrum.chat/next-js.

**Closed by timneutkens** 2018-11-12 13:21 UTC

**Comment by hajdun** [comment] 2018-11-12 13:34
First page load is successful so this does not explain my problem.
