### ISSUE TITLE
Jest test fails  Error: Uncaught [TypeError: Cannot read property 'prefetched' of undefined]

### ISSUE THREAD

**Issue by LdsDannyStaten** [zeit/next.js#10087] opened 2020-01-14 18:10 UTC
# Bug report
Running the test in jest with 9.1.6 passes, but running it in 9.1.7 fails
## Describe the bug
```jsx
import React from "react";
import Link from "next/link";
const ExampleComponent = () => (
  <Link href="/more"><a href="/more">More</a></Link>
);
export default ExampleComponent;
```
when we attempt to mount this using jest for our test running, it gives the error 
Error: Uncaught [TypeError: Cannot read property 'prefetched' of undefined]

## To Reproduce
Attempt to mount a next Link using jest testing will fail with the error above.

## Expected behavior
Expected to pass the jest test without that error
## System information
We tested this with both a windows and linux/mac environment.
- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: the problem starts on 9.1.7
.

**Comment by Timer** [comment] 2020-01-14 18:41
This has been fixed on `next@canary`. Please upgrade.

**Closed by Timer** 2020-01-14 18:41 UTC

**Comment by balazsorban44** [comment] 2022-01-30 16:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
