### ISSUE TITLE
with-styled-jsx-postcss example is broken (since beta.21)

### ISSUE THREAD

**Issue by sarukuku** [zeit/next.js#1125] opened 2017-02-14 08:11 UTC
I'm talking about [this](https://github.com/zeit/next.js/tree/master/examples/with-styled-jsx-postcss).

To reproduce just follow the steps on the readme. When running `npm run dev` you'll get an error:
```
 ERROR  Failed to compile with 1 errors

 error  in ./pages?entry

Module build failed: TypeError: unknown: Duplicate declaration "_JSXStyle"
  1 | import _JSXStyle from 'styled-jsx/style';
  2 | import React from 'react';
> 3 | import _JSXStyle from 'styled-jsx/style';
    |        ^
  4 | export default (function () {
  5 |   return React.createElement(
  6 |     'div',
    at File.buildCodeFrameError (/Users/Joonas/test/with-styled-jsx-postcss/node_modules/babel-core/lib/transformation/file/index.js:431:15)
    at Scope.checkBlockScopedCollisions (/Users/Joonas/test/with-styled-jsx-postcss/node_modules/babel-traverse/lib/scope/index.js:398:27)
    at Scope.registerBinding (/Users/Joonas/test/with-styled-jsx-postcss/node_modules/babel-traverse/lib/scope/index.js:592:16)
    at Scope.registerDeclaration (/Users/Joonas/test/with-styled-jsx-postcss/node_modules/babel-traverse/lib/scope/index.js:516:14)
    at Object.Declaration (/Users/Joonas/test/with-styled-jsx-postcss/node_modules/babel-traverse/lib/scope/index.js:176:36)
    at NodePath._call (/Users/Joonas/test/with-styled-jsx-postcss/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/Joonas/test/with-styled-jsx-postcss/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/Joonas/test/with-styled-jsx-postcss/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/Joonas/test/with-styled-jsx-postcss/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/Joonas/test/with-styled-jsx-postcss/node_modules/babel-traverse/lib/context.js:103:17)

 @ multi ./~/next/dist/client/webpack-hot-middleware-client ./pages?entry

> Ready on http://localhost:3000

```

Everything works well with `beta.20` but after that nope.

**Comment by sarukuku** [comment] 2017-02-14 08:12
@giuseppeg you're probably related to this somehow? 😄

**Comment by timneutkens** [comment] 2017-02-14 09:47
Duplicate of https://github.com/zeit/next.js/issues/964

**Closed by timneutkens** 2017-02-14 09:47 UTC
