### ISSUE TITLE
with-jest example is broken

### ISSUE THREAD

**Issue by andrewBalekha** [zeit/next.js#4311] opened 2018-05-08 15:45 UTC
## Expected Behavior
After installing example and running `yarn test` the test should pass

## Current Behavior
After running `yarn test` we are getting an error
```
Plugin 0 specified in "/with-jest-app/node_modules/next/babel.js" provided an invalid property of "default" (While processing preset: "/with-jest-app/node_modules/next/babel.js")
```

## Steps to Reproduce (for bugs)
go to https://github.com/zeit/next.js/tree/canary/examples/with-jest and follow readme installation steps

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     v6    |
| node    |     v8.9.4    |
| OS      |   High Sierra      |

**Comment by timneutkens** [comment] 2018-05-08 15:52
Duplicate of #4263
Fixed in https://github.com/zeit/next.js/pull/4278

I'll ask @fouad to add support for the `canary` branch in create-next-app

**Closed by timneutkens** 2018-05-08 15:52 UTC
