### ISSUE TITLE
Infinitely slow first page render. 

### ISSUE THREAD

**Issue by flizana** [zeit/next.js#9367] opened 2019-11-10 16:27 UTC
I have a bunch of pages with antd components and others without. In production, when I initially load (by clicking on a Link) a page with antd components it takes forever to load. If I type the URL directly in the address bar, then the page with antd components loads fine. Every second or third time I click on the Link the navigation works correctly. The only issue I am having is when I click on a Link the first time. FWIW, the size of the pages that contain antd components is 647 kB. I do not knows if this is because of server resources or because of a bug in Next.js. I also know that this happens in production as well as development. I also had to do a workaround to get antd styles working, as shown in the following code snippets.

````
next.config.js

/* eslint-disable */
const withLess = require('@zeit/next-less')
const lessToJS = require('less-vars-to-js')
const fs = require('fs')
const path = require('path')

// Where your antd-custom.less file lives
const themeVariables = lessToJS(
  fs.readFileSync(path.resolve(__dirname, './assets/style.less'), 'utf8')
)

module.exports = withLess({
  compress: false,
  lessLoaderOptions: {
    javascriptEnabled: true,
    modifyVars: themeVariables, // make your antd custom effective
  },
  webpack: (config, { isServer }) => {
    if (isServer) {
      const antStyles = /antd\/.*?\/style.*?/
      const origExternals = [...config.externals]
      config.externals = [
        (context, request, callback) => {
          if (request.match(antStyles)) return callback()
          if (typeof origExternals[0] === 'function') {
            origExternals[0](context, request, callback)
          } else {
            callback()
          }
        },
        ...(typeof origExternals[0] === 'function' ? [] : origExternals),
      ]

      config.module.rules.unshift({
        test: antStyles,
        use: 'null-loader',
      })
    }
    return config
  },
})
````

````
.babelrc

{
  "presets": ["next/babel"],
  "plugins": [
    [
      "import", {
        "libraryName": "antd",
        "style": true
      }
    ]
  ]
}
````

````
Next.js version: 9.0.8
antd version: 3.24.3
@zeit/next-less version: 1.0.1
````

**Comment by timneutkens** [comment] 2019-11-10 16:50
I'm pretty sure it's a duplicate of https://github.com/zeit/next-plugins/issues/282

**Closed by timneutkens** 2019-11-10 16:50 UTC

**Comment by zacksinclair** [comment] 2020-05-19 19:52
@flizana did you ever resolve this? i have the exact same issue w/ basically the same set up for antd. 

I dont believe it is the zeit/next-plugins#282 issue that @timneutkens linked, as it happens on directly accessing a url (as opposed to clicking a link)

**Comment by balazsorban44** [comment] 2022-01-30 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
