### ISSUE TITLE
double backslah in pages-manifest.json causing windows / unix  compatibility issue

### ISSUE THREAD

**Issue by Huaoe** [zeit/next.js#5757] opened 2018-11-28 09:57 UTC
# Bug report

## Describe the bug

pages-manifest.json and __precacheManifest are outed with "\\" in path on Windows which causes error when copied in UNIX production

## To Reproduce

Build on Windows -> deploy on UNIX

## Expected behavior

{"/_app":"static\\\\_Dv~cWWKlkG5i2~aGcOyE\\\pages\\\\_app.js",
should be
{"/_app":"static/_Dv~cWWKlkG5i2~aGcOyE/pages/_app.js",

## System information
 - OS: Windows
 - Version of Next.js: 7.0.2

## Fix
To fix the issue on pages-manifest.json ; I guess __precacheManifest is from next-offline and I'll investigate there

\next\dist\build\webpack\plugins\pages-manifest-plugin.js
L59:
            pages["/".concat(pagePath.replace(/\\/g, '/'))] = name.replace(/\\/g, '/');

**Comment by timneutkens** [comment] 2018-11-28 11:01
Duplicate of #4920

**Closed by timneutkens** 2018-11-28 11:01 UTC
