### ISSUE TITLE
Stack traces for exceptions inside getInitialProps() show babel internals

### ISSUE THREAD

**Issue by wilsonpage** [zeit/next.js#5028] opened 2018-08-25 08:57 UTC
# Bug report

## Describe the bug

When an exception is thrown inside a page's `getInitialProps()` the stack trace shows internal Babel `regenerator-runtime` code instead of recognisable app code. This make it hard to debug.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Throw an `Error` inside `getInitialProps()`
2. See stack-trace like above.

## Expected behavior

A stack trace that shows library and application code only, not transpiled code.

## Screenshots

<img width="931" alt="image" src="https://user-images.githubusercontent.com/1020551/44616729-f3703c80-a84c-11e8-9d29-b2d929edc3c7.png">

## System information
 - Version of Next.js: `6.1.1`

**Comment by timneutkens** [comment] 2018-08-25 12:35
Duplicate of #4613, please try `next@canary` there's been quite some improvements on the stacktraces front.

**Closed by timneutkens** 2018-08-25 12:35 UTC
