### ISSUE TITLE
pages/404 can not have getInitialProps/getServerSideProps

### ISSUE THREAD

**Issue by ebidel** [zeit/next.js#10919] opened 2020-03-10 05:14 UTC
# Bug report

## Describe the bug

A custom pages/404.tsx:

```
import React from 'react';
export default = () => <h1>This is the 404 page</h1>;
```

causes an internal server error on the dev server. The log error complains about `getInitialProps`;
note: we have a custom _app.tsx file that uses `getInitialProps`.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. create the 404 page above
2. create a custom _app that uses getInitialProps.

## Expected behavior

No error or suggests using _error.js. Note: using a _error.js works for us.

## Screenshots

<img width="910" alt="Screen Shot 2020-03-09 at 10 07 27 PM" src="https://user-images.githubusercontent.com/238208/76281522-87003700-6252-11ea-8e97-206a97f6612e.png">

## System information

- OS: [e.g. macOS, Windows] macos
- Browser (if applies) [e.g. chrome, safari] chrome
- Version of Next.js: 9.3.0

**Comment by ssig33** [comment] 2020-03-10 07:20
I have a similar problem.

if pages/[id].js is following 
``` js
export default ()=> <h1>something...</h1> 
```

For example, we can access the following URL:

- /1
- /2
- /hogehoge
- **/404**

but, **/404** can not be generated on ```next build```

**Comment by chiqui3d** [comment] 2020-03-10 23:37
Same problem here:

Example:

```js
import Head from "next/head";
import HeaderTop from "../components/Header/HeaderTop";
import HeaderMainWithBackground from "../components/Header/HeaderMainWithBackground";
import S404 from "../components/Sections/S404";
import Footer from "../components/Sections/Footer";


export default (props) => {
    return (
        <>
            <Head>
                <title>{props.t('Error.title')}</title>
                <meta name="description" content={props.t('Error.description')} />
            </Head>
            <HeaderTop/>
            <HeaderMainWithBackground background="asdasd.jpg" pageName={props.t('Error.name')} {...props}/>
            <S404 {...props}/>
            <Footer {...props}/>
        </>
    )
};
```

**Comment by ijjk** [comment] 2020-03-11 15:22
Hi, it looks like the `` `pages/404` can not have getInitialProps/getServerSideProps, https://err.sh/zeit/next.js/404-get-initial-props`` error was being shown incorrectly in development which should be addressed in https://github.com/zeit/next.js/pull/10974. 

Note: having `getInitialProps` in `_app` does prevent the 404 page from being statically optimized and you are strictly not allowed to use `getInitialProps` or `getServerSideProps` in `pages/404` even if you do use `getInitialProps` in `_app`

**Closed** 2020-03-11 16:18 UTC

**Comment by balazsorban44** [comment] 2022-01-30 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
