### ISSUE TITLE
Provide performance metrics

### ISSUE THREAD

**Issue by ValentinH** [zeit/next.js#7497] opened 2019-06-04 18:37 UTC
I'm migrating an application to Next.js and one requirement that we have is to be able to monitor the application (using Prometheus for example).
For example, I would like to monitor the rendering time of the application or the data-fetching time (during getInitialProps) on the server.

Is this something already supported? If no, would it be possible to add some mechanism to track those timings?

**Comment by Janpot** [comment] 2019-06-04 18:59
One idea could be to add a [Server-Timing header/trailer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing). Not sure if that would be enough for your use case.

**Comment by timneutkens** [comment] 2019-06-04 20:20
I'm going to close this as it ignores the issue template. However I'd be happy to look into providing more metrics. We've already investigated bits around this.

**Closed by timneutkens** 2019-06-04 20:20 UTC

**Comment by ValentinH** [comment] 2019-06-04 20:23
Does it means I need to open a new issue following the template? Do you have any link to the investigations you did? :)

**Comment by timneutkens** [comment] 2019-06-04 20:28
Sure open a new issue provide a clearer pathway to what you're suggesting 👍

**Comment by balazsorban44** [comment] 2022-01-31 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
