### ISSUE TITLE
Next.js 9 API route works on Get Request but not Post request

### ISSUE THREAD

**Issue by zluo01** [zeit/next.js#7960] opened 2019-07-14 15:06 UTC
# Question about Next.js
I try to modified some of the api to use post instead of get. 
I have request code like this with normal fetch
```
 const response = await fetch(`${process.env.SERVER}/api/lyric?id=${song.song_id}`);
```
It will get to the file inside ./page/api and resolve, however, if I change to code to following
```
 const response = await fetch(`${process.env.SERVER}/api/lyric`, {
                    method: 'POST',
                    body: JSON.stringify({id: song.song_id})
                });
```
It will give me 404 not found. I wonder what is the problem here ?

Thank you

**Comment by huv1k** [comment] 2019-07-14 16:52
Hey @zluo01, provide full reproduction, from your issue it's hard to guess what could be wrong. You can check [integration test](https://github.com/zeit/next.js/blob/canary/test/integration/api-support/test/index.test.js#L46-L56) for `POST`.

**Comment by colemahatmccreary** [comment] 2019-07-18 20:30
Were you able to figure this out? The documentation for API routes is pretty minimal, and I'm also receiving a 404 response for POST requests sent to a route that worked fine for GET requests

**Comment by zluo01** [comment] 2019-07-18 23:47
> Were you able to figure this out? The documentation for API routes is pretty minimal, and I'm also receiving a 404 response for POST requests sent to a route that worked fine for GET requests

Sorry no, I use Get and put stuff inside headers instead and I do not have time to produce a full reproduction.

**Comment by stoplion** [comment] 2019-07-24 07:06
Why is this closed? I would think documenting this is pretty important

**Comment by timneutkens** [comment] 2019-07-24 10:59
@stoplion what would you like to have documented? Can you create an issue following the issue template for it?

**Comment by stoplion** [comment] 2019-07-25 04:31
Sure

**Comment by TommySorensen** [comment] 2019-08-15 07:14
I also see the 404 in our project with the following: 

```
const res = await fetch('/api/bookings', {
        method: 'POST',
        body: JSON.stringify({ hungry: true }),
        headers: {
          'Content-Type': 'application/json',
        },
      })
      const data = await res.json()
```

It dosent matter what the content is in the `api/bookings` file. It will never be hit. I'm using `now dev` to run the project on localhost

**Comment by huv1k** [comment] 2019-08-15 13:24
@TommySorensen this should be fixed in the latest canary

**Comment by danielfein** [comment] 2019-08-16 03:42
Was this ever answered? Is there a way to POST to a Next v9 API Route?

**Comment by TommySorensen** [comment] 2019-08-16 06:22
> Was this ever answered? Is there a way to POST to a Next v9 API Route?

Yes. Just posting to the api routes will work just fine. Use [this example](https://github.com/zeit/next.js/tree/canary/examples/api-routes) and change the get to post. Thats what i did. Worked like a charm 😉

**Comment by lifeiscontent** [comment] 2019-08-17 02:11
@huv1k any idea on a release?

**Comment by huv1k** [comment] 2019-08-17 13:29
@lifeiscontent release of what?

**Comment by lifeiscontent** [comment] 2019-08-17 21:41
@huv1k on when the next release of next.js will come out with this fix

**Comment by TommySorensen** [comment] 2019-08-18 10:34
@lifeiscontent There is no bug to fix. I tested it my self. POST work just fine if you use of the NextJS examples. It's properly something in your application. Please provide example of the full code, so we can help with the investigation 👍

**Comment by maddhruv** [comment] 2019-09-18 16:11
easy deasy
in your _custom server_
do

```js
server.use((req, res) => app.getRequestHandler()(req, res))
```

**Comment by thgh** [comment] 2019-10-16 15:19
Repro:
```
npx create-next-app --example with-firebase-authentication with-firebase-authentication-app
```

Add file api/test.js
```
export default (req, res) => {
  console.log('api test', req.method)
  res.json('ok')
}
```

Add request handler in server.js:
```
server.use((req, res) => app.getRequestHandler()(req, res))
```

Run `yarn dev` (or `node server.js`)

Send POST to http://localhost:3000/api/test

Expected: console logs `api test POST`
Actual: no logs, request stays pending until timeout

**Comment by Timer** [comment] 2019-10-16 21:43
You need to update the example:
```
  server.get('*', (req, res) => {
    return handle(req, res)
  })
```

needs to be:
```
  server.all('*', (req, res) => {
    return handle(req, res)
  })
```

**Closed by Timer** 2019-10-16 21:43 UTC

**Comment by epranka** [comment] 2019-12-18 09:17
If anyone has this issue yet with a custom express server, it can occur while using multiple body parsers, because NextJs api routes enables it by default. Use only express body parser, or only NextJs body parser. How to disable NextJs body parser documented there: https://nextjs.org/docs#api-middlewares

**Comment by rscotten** [comment] 2019-12-31 18:36
@epranka Man, it took me hours to figure this one out.  I couldn't make any POST requests to my API route using the Firebase Cloud Functions server.  Disabling the body parser made it possible.  

@thgh I had the same problem: POST requests would hang, but GET requests would work fine.  Disabling the body parser fixed it.

**Comment by cooervo** [comment] 2020-01-30 09:27
@TommySorensen answer solved it for me: 
  server.get("*", (req, res) => handle(req, res));
  server.post("*", (req, res) => handle(req, res));

**Comment by amardeepsingh20** [comment] 2020-03-23 13:36
> @epranka @thgh, Man, it took me hours to figure this one out.
> 
> I'm using the Firebase Cloud Functions server, and I couldn't make any POST requests to my API route. POST requests would hang, but GET requests would work fine. And if I was using the local NextJS dev server, POST requests would also work fine.
> 
> Disabling the body parser when using Firebase Cloud Functions fixed it.
> 
> Apparently Firebase Cloud Functions comes with its own body parser, and it conflicts with the NextJS one. So you have to disable the body parser for Firebase Cloud Functions, but enable it for local development using the NextJS dev server.
> 
> So basically drop this in your `pages/api/[yourEndPoint].js`:
> 
> ```js
> export const config = {
>   api: {
>     bodyParser: process.env.NODE_ENV !== 'production'
>   }
> };
> ```

Thanks! Was facing the exact same issue. Resolved with your fix. Its surprising that Firebase functions do not give any config to turn off automatic body parsing.

**Comment by rohit267** [comment] 2020-11-04 16:19
so we have to use custom server, got it but getting the parsed body inside api route would have solved many problems.

**Comment by OZZlE** [comment] 2021-04-13 13:02
We had in our ExpressJs `server.js` this: `server.use(bodyParser.json())` which made all POST request return 504 and not even log any console.log, because we didn't know about Next.js Api routes (weird name for Controller/BE)

Changed it to be route specific: https://github.com/expressjs/body-parser#express-route-specific and then it works :)

**Comment by SonicCodes** [comment] 2021-05-07 17:59
> I also see the 404 in our project with the following:
> 
> ```js
> const res = await fetch('/api/bookings', {
>   method: 'POST',
>   body: JSON.stringify({ hungry: true }),
>   headers: {
>     'Content-Type': 'application/json',
>   },
> })
> const data = await res.json()
> ```
> 
> It dosent matter what the content is in the `api/bookings` file. It will never be hit. I'm using `now dev` to run the project on localhost
> 
> **Update**
> I found out that it worked fine with the `now dev` but it did not work with my `server.js` file due to i had not handled post requests. If you simply add a handler for post request, everything will work fine:
> 
> ```js
> server.post('*', (req, res) => {
>   return handle(req, res)
> })
> ```

Hmm, I wonder why no one gave attention to that (get -> get, post -> post) 😆 , thanks, you saved my day.

**Comment by balazsorban44** [comment] 2022-01-28 09:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
