### ISSUE TITLE
Files copied with CopyWebPackPlugin disappear

### ISSUE THREAD

**Issue by HoraceShmorace** [zeit/next.js#3444] opened 2017-12-12 16:33 UTC
Files copied to '/static' using CopyWebpackPlugin are successfully created, but then are deleted right after the console messages 'Building page ...'.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Files copied by CopyWebpackPlugin to '/static' don't subsequently get removed by the build process.
## Current Behavior

Files copied by CopyWebpackPlugin to '/static' get copied, then deleted by the build process.

## Steps to Reproduce (for bugs)

Run `npm run dev` with the following next.config.js (note that I'm copying a file from the `workbox-sw` npm package, but it can be any file):
```
const path = require('path')
const CopyWebpackPlugin = require('copy-webpack-plugin')

module.exports = {
  webpack: (config, { dev }) => {
    config.plugins.push(
      new CopyWebpackPlugin([
      {
        from: path.join(__dirname, 'node_modules/workbox-sw/build/importScripts/workbox-sw.dev.v2.1.2.js'),
        to: path.join(__dirname, 'static/scripts/workbox.js')
      }
    ]))
    
    return config
  }
}
```

## Context

Can't copy files at build time.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    4.1.4     |
| node    |     9.2.0    |
| OS      |    OS X 10.11.6      |
| browser |    Chrome 62     |
| etc     |         |

**Comment by Mikhail-Fiadosenka** [comment] 2017-12-13 12:32
Didn't reproduced in my environment - static files were copied and were present after build.
But I linked static files in _document.js as per comment in this [issue](https://github.com/zeit/next.js/issues/299#issuecomment-263146962).

**Comment by wltnet** [comment] 2018-02-18 00:24
I have the same problem. it deletes files when using npm run dev.  
while next build && next start doesn't <-- but no hot reloading..

**Comment by timneutkens** [comment] 2018-02-18 00:31
`webpack` is ran twice, once for the server, once for the client, the solution might be as simple as:

```
const path = require('path')
const CopyWebpackPlugin = require('copy-webpack-plugin')

module.exports = {
  webpack: (config, { dev, isServer }) => {
if(isServer) {
return config
}
    config.plugins.push(
      new CopyWebpackPlugin([
      {
        from: path.join(__dirname, 'node_modules/workbox-sw/build/importScripts/workbox-sw.dev.v2.1.2.js'),
        to: path.join(__dirname, 'static/scripts/workbox.js')
      }
    ]))
    
    return config
  }
}

```

If you want to implement workbox try https://github.com/hanford/next-offline

There's not much that we can change in Next.js to fix this issue, so I'm going to close it.

**Closed by timneutkens** 2018-02-18 00:31 UTC

**Comment by clementprdhomme** [comment] 2018-02-26 16:05
@timneutkens I also use the plugin `CopyWebpackPlugin` and the files are still deleted when I run `npm run dev`, even if I add the condition.

```js
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.plugins.push(
        new CopyWebpackPlugin([
          {
            context: 'node_modules/widget-editor/dist/images/',
            from: '**/*',
            to: 'static/images/widget-editor/'
          }
        ])
      );
    }

    return config;
  }
};
```

**Comment by chami** [comment] 2018-04-11 23:17
i had to use gulp for this.

**Comment by timneutkens** [comment] 2018-04-12 08:46
@clementprdhomme it's fixed in Next 5.1.

**Comment by Organizzzm** [comment] 2019-03-15 15:27
It still reproduce

**Comment by clementprdhomme** [comment] 2019-04-03 11:45
Hey @Organizzzm,

I'm using Next 7.0.2 and it works for me with this code:
```js
const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {
  webpack: (config, { isServer }) => {
    config.plugins.push(
      new CopyWebpackPlugin([
        {
          from: path.join(__dirname, 'node_modules/widget-editor/dist/images'),
          to: path.join(__dirname, 'static/images/widget-editor/')
        }
      ])
    );
    return config;
  }
};
```

Make sure you use `path.join`.
