### ISSUE TITLE
Monaco Editor example doesn't work

### ISSUE THREAD

**Issue by danielpaz6** [zeit/next.js#13117] opened 2020-05-19 22:29 UTC
# Bug report

Monaco Editor Example doesn't work
Link: https://github.com/zeit/next.js/tree/canary/examples/with-monaco-editor

( The error logs could be found down in this issue )

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://github.com/zeit/next.js/tree/canary/examples/with-monaco-editor
2. Use the command there to install the package
3. Use `npm run dev` 

## Expected behavior

The expected behavior is to display the monaco editor.

## System information

- OS: Windows
- Browser: Chrome
- `package.json`:

```
{
  "name": "with-monaco-editor",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@zeit/next-css": "^1.0.1",
    "monaco-editor": "^0.20.0",
    "monaco-editor-webpack-plugin": "^1.9.0",
    "next": "9.3.1",
    "next-fonts": "^1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-monaco-editor": "^0.34.0"
  }
}
```
- Node version:

```
$ node --version
v12.16.1
```

## Additional context

The error I receive:

```
[ ready ] compiled successfully - ready on http://localhost:3000
[ event ] build page: /
[ wait ]  compiling ...
[ error ] ./node_modules/monaco-editor/esm/vs/base/browser/ui/codiconLabel/codicon/codicon.css
ModuleParseError: Module parse failed: Unexpected character ' ' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
Could not find files for /index in .next/build-manifest.json
ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character ' ' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (D:\monaco-editor\node_modules\webpack\lib\NormalModule.js:469:19)
    at D:\monaco-editor\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\monaco-editor\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:373:3       
    at iterateNormalLoaders (D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\monaco-editor\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\monaco-editor\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at D:\monaco-editor\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
    at D:\monaco-editor\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:367:11      
    at D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:182:20      
    at context.callback (D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\monaco-editor\node_modules\mini-css-extract-plugin\dist\loader.js:112:14 
    at D:\monaco-editor\node_modules\webpack\lib\Compiler.js:343:11
    at D:\monaco-editor\node_modules\webpack\lib\Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\monaco-editor\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:22:1)
    at AsyncSeriesHook.lazyCompileHook (D:\monaco-editor\node_modules\tapable\lib\Hook.js:154:20)
    at D:\monaco-editor\node_modules\webpack\lib\Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\monaco-editor\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (D:\monaco-editor\node_modules\tapable\lib\Hook.js:154:20)
    at D:\monaco-editor\node_modules\webpack\lib\Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\monaco-editor\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (D:\monaco-editor\node_modules\tapable\lib\Hook.js:154:20)
    at D:\monaco-editor\node_modules\webpack\lib\Compilation.js:1414:32
ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character ' ' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (D:\monaco-editor\node_modules\webpack\lib\NormalModule.js:469:19)
    at D:\monaco-editor\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\monaco-editor\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:373:3       
    at iterateNormalLoaders (D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\monaco-editor\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\monaco-editor\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at D:\monaco-editor\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
    at D:\monaco-editor\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:367:11      
    at D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:182:20      
    at context.callback (D:\monaco-editor\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\monaco-editor\node_modules\mini-css-extract-plugin\dist\loader.js:112:14 
    at D:\monaco-editor\node_modules\webpack\lib\Compiler.js:343:11
    at D:\monaco-editor\node_modules\webpack\lib\Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\monaco-editor\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:22:1)
    at AsyncSeriesHook.lazyCompileHook (D:\monaco-editor\node_modules\tapable\lib\Hook.js:154:20)
    at D:\monaco-editor\node_modules\webpack\lib\Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\monaco-editor\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (D:\monaco-editor\node_modules\tapable\lib\Hook.js:154:20)
    at D:\monaco-editor\node_modules\webpack\lib\Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\monaco-editor\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (D:\monaco-editor\node_modules\tapable\lib\Hook.js:154:20)
    at D:\monaco-editor\node_modules\webpack\lib\Compilation.js:1414:32
```

I also tried to tell someone else to reproduce these steps and he got this error:

<img src="https://i.imgur.com/4ZkZkUk.png" />

It also happened to someone else in this discussion: https://github.com/zeit/next.js/discussions/13114#discussioncomment-16489

**Comment by danielpaz6** [comment] 2020-05-20 08:21
**Update:**

I found out that if you use the exactly versions from the package.json and not upgrade it, it means to change it from:

```
  "dependencies": {
    "@zeit/next-css": "^1.0.1",
    "monaco-editor": "^0.20.0",
    "monaco-editor-webpack-plugin": "^1.9.0",
    "next": "9.3.1",
    "next-fonts": "^1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-monaco-editor": "^0.34.0"
  }
```

to:

```
  "dependencies": {
    "@zeit/next-css": "1.0.1",
    "monaco-editor": "0.20.0",
    "monaco-editor-webpack-plugin": "1.9.0",
    "next": "9.3.1",
    "next-fonts": "1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-monaco-editor": "0.34.0"
  }
```

it does work.
So I guess this bug related to some updated version?

By the way, even if it works, it makes a warning:

```
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled
```

**Comment by jensmeindertsma** [comment] 2020-05-20 13:39
This probably should be converted to using the build in CSS support, I'll submit a PR.

**Comment by TodorTotev** [comment] 2020-05-25 07:33
Should be fixed as of now.

**Closed** 2020-05-25 07:45 UTC
Labels: good first issue, help wanted

**Comment by dukeliberal** [comment] 2021-04-26 05:20
Same issue still open in latest version.

**Comment by futhr** [comment] 2021-05-09 02:38
@todortotev FYI the example is outdated due to that @zeit/next-css is deprecated.

**Comment by balazsorban44** [comment] 2022-01-28 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
