### ISSUE TITLE
Routing error for urls with trailing slash since 5.0.0

### ISSUE THREAD

**Issue by hyperborea** [zeit/next.js#3876] opened 2018-02-23 14:55 UTC
- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Both URLs /foo and /foo/ should render the contents of /pages/foo/index.js.

## Current Behavior

/foo works fine, but /foo/ causes a 404 error on SSR and only reconciles later at client side rendering.

## Steps to Reproduce (for bugs)

1. create minimal next.js project
2. create /pages/foo/index.js including e.g. `export default () => <div>hello world</div>`
3. test url /foo/, should throw 404 on SSR

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   5.0.0      |
| node    |     8.9.0    |

**Comment by timneutkens** [comment] 2018-02-23 19:49
Fixed in `next@canary`

**Closed by timneutkens** 2018-02-23 19:49 UTC

**Comment by lkbr** [comment] 2018-04-26 16:41
Unless I'm mistaken, I don't think this is fixed. I've tried to produce a minimal example to demonstrate.

page | url | client | server
--|--|--|--
/pages/simple.js | /simple | ✅ | ✅
/pages/simple.js | /simple/ | ✅ | 404
/pages/nested/index.js | /nested | ✅ | ✅
/pages/nested/index.js | /nested/ | ✅ | 404
/pages/blog.js | /blog/first (parameterized route copied from [example](https://github.com/zeit/next.js/tree/canary/examples/parameterized-routing)  | ✅ | 404

- live example: https://next-slashes.now.sh/
- code: https://github.com/lkbr/next-slashes

It is my understanding that the last 2 - "/pages/nested/index.js" and "/pages/blog.js" should not 404 on the server.

**Comment by kheruc** [comment] 2018-04-26 17:00
I can also confirm the bug. 
For my production site, I "fixed" it by redirecting urls with slashes to urls without them using this code in nginx config:
`rewrite ^/(.*)/$ /$1 permanent;`
Not sure if redirects are possible on Now, I use a custom server.

**Comment by mydearxym** [comment] 2018-05-18 02:06
still not fix in next 6.x

**Comment by NathanielHill** [comment] 2018-06-14 16:54
This is fixed :tada:
https://zeit.co/blog/new-static-deployments

**Comment by lkbr** [comment] 2018-06-14 17:17
That's great but I believe that doesn't help non static deployments or apps not hosted with Now.

**Comment by NathanielHill** [comment] 2018-06-14 18:39
Ah, good point on static apps hosted elsewhere. I've never had a trailing slash issue with dynamic deployments, so this fixes the problem for me and likely several other people.

**Comment by eugeneross** [comment] 2018-09-13 13:09
@timneutkens any status when this will be fixed for non-static deployments / static deployments hosted elsewhere?

**Comment by iamstarkov** [comment] 2018-09-19 23:39
I filed a new issue with minimal reproducible repository in #5214

**Comment by aluminick** [comment] 2018-12-10 06:50
If you want trailing slash, you can just do this. `<Link href='/about' as='/about/'><a>about</a></Link>` but if you're using [fridays/next-routes](https://github.com/fridays/next-routes) this is not possible. So I have a [fork](https://github.com/aluminick/wtp-next-routes) where you can add `trailingSlash` as prop. Hope this helps

**Comment by aripekkako** [comment] 2019-08-27 09:46
This is still not working in next@9.0.4

/pages/nested/index.js | /nested/ | ✅ | 404
-- | -- | -- | --

**Comment by reginpv** [comment] 2019-12-19 03:47
> That's great but I believe that doesn't help non static deployments or apps not hosted with Now.

Having this issue now

**Comment by Shaquu** [comment] 2020-01-07 09:11
@reginpv what is your config in _next.config.js_?
For me setting _trailingSlash_ to _false_ made that work.

**Comment by reginpv** [comment] 2020-01-07 14:20
@Shaquu Looks like updating to latest fixed this for me, I'm not seeing the issue now. Will continue to monitor and if ever saw the issue again will report

**Comment by RobertoPrevato** [comment] 2020-05-13 21:22
I am seeing the same issue now, but only when I refresh the page. It's even funnier, because I am using a project template with TypeScript, that for some reason always adds a trailing slash to the URL I define in `Link` components.

For example: I write ```Link href="/about"```, it gets changed to "/about/". It works when I navigate, but then if I refresh the page, the route doesn't match anymore the "about.tsx" page, or "about/index.tsx" (doesn't make a difference). I don't see the same issue when using the default starter template with ES.

**Comment by balazsorban44** [comment] 2022-01-30 01:27
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
