### ISSUE TITLE
Why is a.less mixed with b.less in a chunk file?

### ISSUE THREAD

**Issue by songshuzhong** [zeit/next.js#9121] opened 2019-10-18 03:02 UTC
# a.tsx
import '../styles/a.less';

#b.tsx
import '../styles/b.less';

**Comment by Timer** [comment] 2019-10-18 04:06
Closing this as Next.js doesn't support Less (or CSS). If you need help with your custom configurations, please open a support request on https://spectrum.chat/next-js.

**Closed by Timer** 2019-10-18 04:06 UTC

**Comment by balazsorban44** [comment] 2022-01-31 02:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
