### ISSUE TITLE
Unable to navigate to a page that has been disposed

### ISSUE THREAD

**Issue by alexanderte** [zeit/next.js#5335] opened 2018-09-29 22:37 UTC
# Bug report

## Describe the bug

It is not possible to navigate to a page after it has been disposed by the server.

## To Reproduce

https://github.com/alexanderte/next-dispose-issue

Steps to reproduce the behavior, please provide code snippets or a repository:
1. `npm run dev`
1. Go to http://localhost:3000/a
2. Navigate between pages A, B, and C – which does work
2. Go to another tab, do something else for about a minute
3. See server console message that one of the pages have been disposed
4. Navigate between pages A, B, and C – and one of the links doesn’t work anymore

## Expected behavior
Even though a page has been disposed I would expect it to be re-created and to not break navigation.

## System information
 - OS: Windows
 - Browser: Chrome, Firefox
 - Version of Next.js: 7.01

**Comment by timneutkens** [comment] 2018-12-31 01:34
Duplicate of #5598

**Closed by timneutkens** 2018-12-31 01:34 UTC
