### ISSUE TITLE
Is it possible to build a site with an AMP site with Next.js that pulls data from a headless CMS?

### ISSUE THREAD

**Issue by kompounder** [zeit/next.js#7492] opened 2019-06-04 00:55 UTC
1) I am looking to build a website with full AMP support, that pulls all of its data from a headless CMS such as Contentful or Prismic. I also recently learned that Next.js announced support for AMP. Is it feasible to build this with Next.js?

2) Regarding Next.js support for static exports, if a part of the site should not be static (e.g. for member only content, etc), is it possible for me to build this in a hybrid way - i.e. most of the website using next.js static export, and the rest dynamic?

Thank you.

**Comment by ijjk** [comment] 2019-06-04 04:16
1. Yes, this is feasible. You can use `getInitialProps` to load data from your CMS and render it with AMP.
2.  This is also possible but currently experimental see the [RFC here](https://github.com/zeit/next.js/issues/7355). You can test it out by setting `experimental.autoExport` to `true` on the latest canary of Next.js `next@canary`. This will automatically export pages without `getInitialProps` as HTML

**Comment by kompounder** [comment] 2019-06-04 04:31
Thank you @ijjk. On #2, if all of the website's content is served from a CMS (so I would have to use getInitialProps for every page?), but a part of the website is best kept static (e.g. public blog posts) while others are dynamic (e.g. member only content), then are there any workarounds today to implement this in hybrid mode? It seems that the autoExport feature would detect getInitialProps on every page in this case.

**Comment by ijjk** [comment] 2019-06-04 16:48
It is not currently supported to have a page auto exported when it has `getInitialProps`. We might add a way to opt-in to this after we investigate it further but it is still an experimental feature for now. A workaround you could do is to use the `next export` command with an `exportPathMap` to only exports the pages you are wanting exported

**Comment by timneutkens** [comment] 2019-06-04 20:24
I'm going to close this issue as it doesn't follow the issue template.

**Closed by timneutkens** 2019-06-04 20:24 UTC

**Comment by balazsorban44** [comment] 2022-01-31 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
