### ISSUE TITLE
Static PDF failing to load

### ISSUE THREAD

**Issue by hatchli** [zeit/next.js#11614] opened 2020-04-02 21:21 UTC
# Bug report

The following error is received when attempting to load a static .pdf file in the public dir:
```
../common/src/assets/pdf/sample.pdf 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

## To Reproduce

next.config.js
```
const withPlugins = require("next-compose-plugins");
const withTM = require("next-transpile-modules");
const withOptimizedImages = require("next-optimized-images");
const withFonts = require("next-fonts");
const withCSS = require("@zeit/next-css");
const CopyWebpackPlugin = require("copy-webpack-plugin");
module.exports = {
  env: {
    STRIPE_PUBLIC_KEY: "your_stripe_public_key_here",
    API_URL: "http://localhost:4000/shop/graphql"
  },
  webpack: (config, { isServer }) => {
    // Fixes npm packages that depend on `fs` module
    if (!isServer) {
      config.node = {
        fs: "empty"
      };
    }
    // config.module.rules.push({
    //   test: /\.pdf$/,
    //   use: [
    //       {
    //           loader: 'file-loader',
    //       },
    //   ]
    // })
    config.module.rules.push({
      test: /\.(png|svg|jpg|gif|pdf)$/,
      use: [
        {
          loader: "file-loader",
          options: {
            name: "[name].[ext]"
          }
        }
      ]
    });

    config.resolve.modules.push(__dirname);

    config.resolve.alias = {
      ...config.resolve.alias
    };

    return config;
  }
};

module.exports = withPlugins(
  [
    new CopyWebpackPlugin([
      { from: "./sample.pdf" },
      { from: "node_modules/pdfjs-dist/cmaps/", to: "cmaps/" }
    ]),
    [
      withTM,
      {
        transpileModules: ["reusecore", "common"]
      }
    ],
    [
      withOptimizedImages,
      {
        mozjpeg: {
          quality: 90
        },
        webp: {
          preset: "default",
          quality: 90
        }
      }
    ],
    withFonts,
    withCSS
  ],
  {
    distDir: "../../dist/functions/next"
  }
);
```

Where the pdf is actually rendered:

```
import React, { Component } from "react";
import { Document, Page } from "react-pdf";
import { pdfjs } from "react-pdf";
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

import pdf from '../../../common/src/assets/pdf/sample.pdf'

export default class Render extends Component {
  state = {
    numPages: null,
    pageNumber: 1
  };

  onDocumentLoadSuccess = document => {
    const { numPages } = document;
    this.setState({
      numPages,
      pageNumber: 1
    });
  };

  changePage = offset =>
    this.setState(prevState => ({
      pageNumber: prevState.pageNumber + offset
    }));

  previousPage = () => this.changePage(-1);

  nextPage = () => this.changePage(1);

  render() {
    const { numPages, pageNumber } = this.state;

    return (
      <React.Fragment>
        <Document file={pdf} onLoadSuccess={this.onDocumentLoadSuccess}>
          <Page pageNumber={pageNumber} />
        </Document>
        <div>
          <p>
            Page {pageNumber || (numPages ? 1 : "--")} of {numPages || "--"}
          </p>
          <button
            type="button"
            disabled={pageNumber <= 1}
            onClick={this.previousPage}
          >
            Previous
          </button>
          <button
            type="button"
            disabled={pageNumber >= numPages}
            onClick={this.nextPage}
          >
            Next
          </button>
        </div>
      </React.Fragment>
    );
  }
}

```

## Expected behavior

The sample.pdf file should be loaded by file-loader

## System information

- OS:  Windows 10
- Version of Next.js: 9.3.0

**Comment by timneutkens** [comment] 2020-04-03 07:52
Doesn't seem like a bug in Next.js, you're adding custom webpack loaders and configuration. 

Duplicate of #11575

**Closed by timneutkens** 2020-04-03 07:52 UTC

**Comment by balazsorban44** [comment] 2022-01-30 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
