### ISSUE TITLE
Safari freezes when swiping back for NProgress example

### ISSUE THREAD

**Issue by aimeelaplant** [zeit/next.js#6295] opened 2019-02-14 06:27 UTC
# Bug Report

## with-loading example
https://github.com/zeit/next.js/tree/master/examples/with-loading

## Describe the bug
On Safari when you click on a link and then press the back button using the touchpad's SWIPE BACK gesture, NProgress freezes and causes the page to hang and get stuck. 

## To Reproduce
I've created a screen recording to show the bug. Notice after the back swipe gesture, the NProgress bar freezes and I can't swipe up and down.

![](https://media.giphy.com/media/BcgzRpmAyPXgUInyNQ/giphy.gif)

## Expected behavior
This bug does not happen when I press the Safari back and forward buttons (*NOT* the swipe gestures). I've created a recording to show expected behavior:

![](https://media.giphy.com/media/3gQNw4lAadAoHiJowW/giphy.gif)

## System information
 - OS: macOS
 - Browser: Safari
 - Version of Next.js: ^7.0.2

## Additional Context
Here's a repository to check into that has the code to reproduce the behavior: https://github.com/aimeelaplant/next-nprogress

Not sure what is going on here... is there a way to disable NProgress if you press the back button?

**Comment by timneutkens** [comment] 2019-02-14 13:18
Strange 😲 Added good first issue labels.

**Comment by suleymantekin** [comment] 2019-03-26 11:47
Can I work on this issue?

**Comment by timneutkens** [comment] 2019-03-26 11:49
Sure!

**Comment by dYb** [comment] 2019-04-28 03:11
Same problem here,  use requestAnimationRequest to resolve it temporarily, much better but still freezed for a little while
```
Router.events.on('routeChangeStart', (url: string) => {
  console.log('routeChangeStart', url)
  requestAnimationFrame(() => {
    NProgress.start()
    NProgress.set(0.5)
  })
})
```

**Comment by Timer** [comment] 2020-04-15 04:55
Closing as we've fixed a lot of routing issues with Safari in the newest Next.js releases. Please let us know if this still reproduces!

**Closed by Timer** 2020-04-15 04:55 UTC
Labels: good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-30 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
