### ISSUE TITLE
Unable to run dev server, NextJS 9

### ISSUE THREAD

**Issue by SergiusAC** [zeit/next.js#9591] opened 2019-12-02 19:40 UTC
## Problem
I created a project via create-next-app, but when I tried to run dev server I got an error below:
```
[ error ] ./node_modules/next/dist/client/dev/amp-dev.js
Error: [BABEL] C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\next\dist\client\dev\amp-dev.js: Cannot find module './src/data'
Require stack:
- C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\core-js-compat\helpers.js
- C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\core-js-compat\get-modules-list-for-target-version.js
- C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js
- C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\@babel\preset-env\lib\index.js
- C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\next\dist\build\babel\preset.js
- C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\next\dist\build\webpack\loaders\next-babel-loader.js
- C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\loader-runner\lib\loadLoader.js
- C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\webpack\lib\NormalModule.js
- C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\webpack\lib\Compiler.js
- C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\webpack\lib\webpack.js
- C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\next\dist\server\hot-reloader.js
- C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\next\dist\server\next-dev-server.js
- C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\next\dist\server\next.js
- C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\next\dist\server\lib\start-server.js
- C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\next\dist\cli\next-dev.js
- C:\Users\serge\Coding\web\playground\nextjs-tests\bitzprice\node_modules\next\dist\bin\next (While processing: "programmatic item")
```
Packages information:
- next: 9.1.4,
- react: 16.12.0
- react-dom: 16.12.0

My dependency manager is Yarn (1.19.2)

## Expected Behavior
Working dev server

## System Information
- OS: Windows 10 (1903)

**Comment by ericdfields** [comment] 2019-12-02 19:47
Same issue. 

    "next": "^9.1.4",
    "react": "^16.12.0",
    "react-dom": "^16.12.0"

macOS Catalina.

**Comment by ijjk** [comment] 2019-12-02 19:48
Hi, this is most likely related to https://github.com/zloirock/core-js/issues/710 and should be resolved once the corrected package is made available through npm

**Comment by Timer** [comment] 2019-12-02 20:03
Duplicate of https://github.com/zeit/next.js/issues/9590

**Closed by Timer** 2019-12-02 20:03 UTC

**Comment by balazsorban44** [comment] 2022-01-30 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
