### ISSUE TITLE
Potential regression in next/head via v8.0.4-canary.20

### ISSUE THREAD

**Issue by garmeeh** [zeit/next.js#7339] opened 2019-05-15 07:34 UTC
# Bug report

## Describe the bug

Hi, I currently maintain [next-seo](https://github.com/garmeeh/next-seo) and I am in the process of testing [V2](https://github.com/garmeeh/next-seo/pull/53) of the library. I noticed that on the latest version of next that when navigating to another page the head does not update correctly. I started back at V7 of Next worked up to the version it stopped working on.

The last version it works on is [v8.0.4-canary.19](https://github.com/zeit/next.js/releases/tag/v8.0.4-canary.19) and as soon as I update to [v8.0.4-canary.20](https://github.com/zeit/next.js/releases/tag/v8.0.4-canary.20) it stops working. Looking through the commits associated with the version it doesn't seem that they would cause an issue. Any insights that would help debug?

Basic scenario:

- Homepage has a title set (Title A)
- Clicking a <Link> to page b and the title remains as Title A 
- Refreshing the page will see that page title is correctly set

Hope to publish a canary version later of next-seo and provide an example sandbox with the steps to reproduce. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information
 - OS: [e.g. macOS, Windows]
 - Browser (if applies) [e.g. chrome, safari]
 - Version of Next.js: [e.g. 6.0.2]

**Comment by Timer** [comment] 2019-05-15 12:40
Maybe related to https://github.com/zeit/next.js/commit/445d3f0a33a24297711c695b2904f8795d06d728?

Can you revert just this commit and see if it fixes?

**Comment by garmeeh** [comment] 2019-05-15 15:41
🤔 For some reason I can not get the changes to show up in the local `file:` linked version of next when I build it. Tried a good few steps but no joy.

I did manually override the `node_modules` version `head.js` to reflect that change revert but it had no affect. But I wouldn't be confident in doing it that way 😅

**Comment by ijjk** [comment] 2019-05-15 15:44
Hi, can you post a repo with a minimal reproduction? We actually have tests covering this [here](https://github.com/zeit/next.js/blob/4eb48ce9459ccf46750f36537d80f71393b2f484/test/integration/client-navigation/test/index.test.js#L824) which are passing.

**Comment by garmeeh** [comment] 2019-05-15 15:59
Ah... I just published an Alpha version of the `next-seo` so I could create a [minimal repo](https://github.com/garmeeh/temp-repo) for the issue and the issue is not there.

Only difference is that where I am seeing the issue I am referencing the lib directly -> [see here](https://github.com/garmeeh/next-seo/blob/migrate-to-typescript/e2e/pages/_app.tsx#L3)

and on the repo that try's to re-create the issue, I reference the npm module [see here](https://github.com/garmeeh/temp-repo/blob/master/pages/_app.tsx#L3)

Is there any known strange behaviour with `next/head` locally?

**Comment by ijjk** [comment] 2019-05-15 16:38
Interesting 🤔 I'm not finding anything that we changed that would have affected the way you import `next/head`. Could you add repro steps for the error from referencing the lib directly? 

Is it just pulling down the `migrate-to-typescript` branch, `yarn build`, and `yarn test` or are you running them differently?

**Comment by garmeeh** [comment] 2019-05-15 16:45
Yeah so pull down that branch.

Run: npm install, npm run build 

Then I have an e2e folder that I just cd into and install and run that as a normal app. 

If you click around in there you will see the title not updating. 

If you need more info let me know and will write out better info when I’m back my laptop.

**Comment by ijjk** [comment] 2019-05-15 17:43
It looks like this is due to you using two separate Next.js insallations. When you install `next` in the `e2e` folder and then import `../../lib` it imports the `next` installed to your project's `node_modules`.

It works fine if you remove `node_modules`, `next.config.js`, and `.babelrc` from `e2e` and upgrade to `next@canary` in the project then run `yarn next e2e` from the project root.

I'm gonna close this issue now since it doesn't appear to be due to Next.js. If you're still having trouble feel free to reply.

**Closed by ijjk** 2019-05-15 17:43 UTC
Labels: Type: Needs Investigation

**Comment by garmeeh** [comment] 2019-05-15 19:29
🙏 @ijjk  thanks for taking the time to look into this. I'm not sure I would of figured that one out, was on a total different path. Hopefully I didn't waste too much of your time 😅
