### ISSUE TITLE
Doc Links Don't Work

### ISSUE THREAD

**Issue by julmot** [zeit/next.js#3649] opened 2018-02-01 09:23 UTC
The links below the section:

Importing CSS / Sass / Less files

https://github.com/zeit/next.js#importing-css--sass--less-files

don't work.

**Comment by timneutkens** [comment] 2018-02-01 09:52
Duplicate of https://github.com/zeit/next.js/issues/3643, they'll be released soon.

**Closed** 2018-02-01 09:53 UTC
