### ISSUE TITLE
Dynamic imports in StrictMode

### ISSUE THREAD

**Issue by aralroca** [zeit/next.js#6957] opened 2019-04-08 14:54 UTC
# Bug report

Using the `React.StrictMode` wrapper, and inside this wrapper using some dynamic import. Is throwing this warning:

![image](https://user-images.githubusercontent.com/13313058/55733713-9a8d9700-5a1e-11e9-95ef-07206329b895.png)

Is not a "Bug",  everything works. However I reported as a bug because IMO this should be fixed to work perfectly under the strict mode.

## To Reproduce

1. Wrap your app with `<StrictMode><App /></StrictMode>`
2. Use some `dynamic(import('...'))` inside the app
3. Open the dev tools console and see the warning

**Comment by MarchWorks** [comment] 2019-04-08 16:25
So this is the [error](https://reactjs.org/docs/strict-mode.html#identifying-unsafe-lifecycles) that you get and this is what react tell you change to `componentDidMount` [loadable.js](https://github.com/zeit/next.js/blob/canary/packages/next-server/lib/loadable.js#L170-L173) but I think that changing everything to React hooks will be better

**Comment by Timer** [comment] 2019-09-03 12:40
Closing as duplicate of https://github.com/zeit/next.js/issues/8310 which has had more activity.
Thanks!

**Closed by Timer** 2019-09-03 12:40 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 06:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
