### ISSUE TITLE
kudos for many examples -- can you add an example of Docker Compose + CodeceptJS?

### ISSUE THREAD

**Issue by bionicles** [zeit/next.js#10097] opened 2020-01-14 20:55 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I want to develop NextJS locally with Docker Compose because this can run database, api, and nextjs server all with 1 command, and it's easy-ish to deploy these containersets to the cloud. Thank you for making Next and so many examples. 

However it's somewhat unclear how to test nextjs locally with docker-compose (or perhaps i missed a link and this could be published more clearly)

## Describe the solution you'd like

Please add an example of how you think users should test NextJS locally in docker-compose with ideally CodeceptJS

## Describe alternatives you've considered

Currently working on a docker-compose file and just wanted to bring this up as you might know better how to implement such a thing quickly

## Additional context

I want to use CodeceptJS because it has simple test syntax which even non-technical folks could understand, so I can focus more on development and less on figuring out how to write tests https://github.com/Codeception/CodeceptJS

```
Feature('CodeceptJS demo');

Scenario('check Welcome page on site', (I) => {
  I.amOnPage('/');
  I.see('Welcome');
});
```

**Comment by timneutkens** [comment] 2020-01-15 10:12
It's unlikely that someone will send a PR for something this specific, but I'll add the good first issue label.

**Comment by afzalsayed96** [comment] 2020-01-20 14:45
@bionicles [here's](https://github.com/afzalsayed96/next-app) an example with Docker Compose and Jest if it helps.

**Comment by bionicles** [comment] 2020-01-20 19:34
Thanks ... I did get it working over the weekend, and could potentially make a PR

**Comment by timneutkens** [comment] 2020-04-28 08:08
Closing this issue as it's been open for a few months and no example was contributed

**Closed by timneutkens** 2020-04-28 08:08 UTC
Labels: good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-30 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
