### ISSUE TITLE
Build error on Now deployment

### ISSUE THREAD

**Issue by psycura** [zeit/next.js#3407] opened 2017-12-06 08:32 UTC
- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Trying to deploy with now-cli

## Current Behavior
Deployment process end with error 

>  Deploying ******
> > Using Node.js 8.9.1 (default)
> > Ready! https://****** [4s]
> > Initializing…
> > Building
> > ▲ npm install
> > ✓ Using "package-lock.json"
> > ⧗ Installing 48 main dependencies…
> > ✓ Installed 1119 modules [34s]
> > ▲ npm run build
> > > visual_proposal@1.0.0 build /home/nowuser/src
> > > next build
> > > Using external babel configuration
> > > Location: "/home/nowuser/src/.babelrc"
> > > Using "webpack" config function defined in next.config.js.
> > npm ERR! code ELIFECYCLE
> > npm ERR! errno 137
> > npm ERR! visual_proposal@1.0.0 build: `next build`
> > npm ERR! Exit status 137
> > npm ERR!
> > npm ERR! Failed at the visual_proposal@1.0.0 build script.
> > npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> > npm ERR! A complete log of this run can be found in:
> > npm ERR!     /home/nowuser/.npm/_logs/2017-12-06T08_26_26_403Z-debug.log

## Steps to Reproduce (for bugs)
1. clone repo https://github.com/psycura/VisualProposal
2. try to deploy to now

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 4.2.0        |
| node    |  8.9.1       |
| OS      |   windows 10      |
| browser |    chrome     |

**Comment by ShepelievD** [comment] 2017-12-06 13:19
@psycura check this one https://github.com/zeit/next.js/issues/3404
We returned to 4.1.4 version

**Comment by psycura** [comment] 2017-12-06 14:14
nope, it doesnt help

**Comment by MarkLyck** [comment] 2017-12-27 17:22
I'm having this issue as well on next 4.2.1 any idea how to solve it?

**Comment by timneutkens** [comment] 2017-12-27 18:51
@psycura the repository is 404ing for me. Please try upgrading to 4.2.1. Also, a deployment url would be helpful so I can look up the logs on our side 👍

**Comment by MarkLyck** [comment] 2017-12-27 19:42
@timneutkens I have the same error as the poster, if it helps my deployment url is: https://formulastocks-dvlsiyxwxp.now.sh

**Comment by calvinchankf** [comment] 2018-01-01 09:51
i have the same problem....any followup?

**Comment by ShepelievD** [comment] 2018-01-02 08:23
@calvinchankf have u updated the version?

**Comment by MarkLyck** [comment] 2018-01-02 09:59
@ShepelievD I can confirm this still happens on the latest 4.3.0-canary.1 as well. :(

Link to latest failing now deployment: https://formulastocks-pqfilwgthg.now.sh

**Comment by calvinchankf** [comment] 2018-01-02 10:02
@ShepelievD 
my next version is 4.2.1
my now version is 9.0.1

**Comment by timneutkens** [comment] 2018-01-02 10:05
@MarkLyck @calvinchankf checking this out today 👍

**Comment by timneutkens** [comment] 2018-01-02 13:29
@MarkLyck just checked it out, the cause is the instance running out of memory while building. I've checked your app and it looks like you have non-pages inside of the pages directory. This basically causes the amount of processing webpack has to do to grow tremendously. From the test on my laptop `next build` peaked at 1,3GB memory. OSS plan instances have 500MB memory available. Paid plan instances have 1GB memory.

My recommendation is to move all non-pages to a separate folder. It'll both make the build faster (232s on my macbook pro 2017 right now) and use way less memory.

**Comment by calvinchankf** [comment] 2018-01-02 13:53
@timneutkens oh...I still have the problem and here is my error log

my next version is 4.2.1
my now version is 9.0.1

please help 🙏🏻

```
$ now --force
> Deploying ~/Desktop/CURI/curi under xxx@hotmail.com
> Warning! Requested node version 8.8.1 is not available 8.9.3
> Using Node.js 8.9.3 (default)
> Ready! https://hello-next-tfzgzasjkq.now.sh (copied to clipboard) [2s]
> You (xxx@hotmail.com) are on the OSS plan. Your code and logs will be made public.
> NOTE: You can use `now --public` to skip this prompt
> Initializing…
> Building
> ▲ npm install
> ✓ Using "yarn.lock"
> ⧗ Installing 16 main dependencies…
> ✓ Installed 940 modules [9s]
> ▲ npm run build
> > hello-next@1.0.0 build /home/nowuser/src
> > next build
> > Using "webpack" config function defined in next.config.js.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 137
> npm ERR! hello-next@1.0.0 build: `next build`
> npm ERR! Exit status 137
> npm ERR! 
> npm ERR! Failed at the hello-next@1.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nowuser/.npm/_logs/2018-01-02T13_45_24_122Z-debug.log
> Error! The build step of your project failed. To retry, run `now --force`.
```

**Comment by MarkLyck** [comment] 2018-01-03 08:44
@timneutkens that fixed it, but won't load components after clicking Links to other pages now...
 :( (separate issue though) so thanks for explaining the problem!

For others in the future, wouldn't it be good to have a better error than just 137? (I'm sure more people will run into this problem too)

**Comment by 1kohei1** [comment] 2018-01-05 00:46
I have the same problem. Please help 🙏🏻

Deployment: https://zeit.co/kohei/nextjs-playground/gumifngodd/source
Now: 9.0.1
Next: 4.2.1

**Comment by timneutkens** [comment] 2018-03-16 12:26
Going to close this one too, added an explanation about it in the other issue 🙏

**Closed by timneutkens** 2018-03-16 12:26 UTC
