### ISSUE TITLE
SyntaxError: Unexpected identifier when importing @iconscout/react-unicons

### ISSUE THREAD

**Issue by brightloudnoise** [zeit/next.js#7913] opened 2019-07-12 03:28 UTC
# Bug report

## Describe the bug

SyntaxError: Unexpected identifier when importing @iconscout/react-unicons

Possibly related to https://github.com/zeit/next.js/issues/7710

## To Reproduce

https://github.com/brightloudnoise/next-unicons-error

## Expected behavior

Next should import the module and display the React component for the icon. This works correctly using the same import in recent create-react-app.

## System information

- OS: macOS
- Chrome and Safari
- Next.js 9.0.1

**Comment by masives** [comment] 2019-07-15 13:17
It's the issue mentioned here https://github.com/zeit/next.js/issues/7710#issuecomment-507252337

Since this library doesn't ship with commonJS you can have NEXT transpile it during build

next.config.js
```
const withTM = require('next-transpile-modules');

module.exports = withTM({
    transpileModules: ['@iconscout/react-unicons'],
});

```

This works but I'm not sure what is the cost to this solution.

**Comment by brightloudnoise** [comment] 2019-07-17 18:14
Thanks, that works as a short-term solution.

**Comment by timneutkens** [comment] 2020-01-02 21:05
Closing as same as #706

**Closed by timneutkens** 2020-01-02 21:05 UTC
Labels: good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-30 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
