### ISSUE TITLE
Modal like Reddit/Twitter nested in a dynamic route

### ISSUE THREAD

**Issue by marjorg** [zeit/next.js#12566] opened 2020-05-06 17:39 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Not sure if this is intended or a bug, so I'll give it a try with a feature request. 

What I'm trying to do is open a search result in a modal while changing the url from i.e. `example.com/posts/search/hello` to `example.com/posts/[ID]`, but it just navigates to the page instead. If I change the search page to not be a dynamic route (`[term].tsx` to just `term.tsx`) it opens the modal as expected.

Structure:
```
/pages
    /posts
        [postId].tsx
        /search
            [term].tsx
```

## Describe alternatives you've considered

A flow like this would be achievable with a custom server, but I would prefer to keep all the performance optimizations.

## Additional context

Seems like some other people have encountered the same here: https://github.com/zeit/next.js/issues/8023

**Comment by Timer** [comment] 2020-05-06 18:12
Duplicate of https://github.com/zeit/next.js/discussions/11625

**Closed by Timer** 2020-05-06 18:12 UTC

**Comment by marjorg** [comment] 2020-05-06 18:49
@Timer Great, thanks! Does the docs mention this anywhere that I missed?

**Comment by balazsorban44** [comment] 2022-01-30 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
