### ISSUE TITLE
Public runtime config is missing in server-rendered pages when visited from statically optimized pages

### ISSUE THREAD

**Issue by MrOrz** [zeit/next.js#9275] opened 2019-11-01 06:35 UTC
# Bug report

## Describe the bug

It is known that runtime config is not supported in static-optimized pages.
However, [this repo](https://github.com/MrOrz/nextjs-runtime-config-bug) demonstrates that even when runtime config is used only in _server-rendered pages_, the runtime config can **still be missing**, which is not expected.

## To Reproduce

I have constructed a minimal demo app for the bug: https://github.com/MrOrz/nextjs-runtime-config-bug

This demo consists of 2 pages:
- `pages/index.js` - A landing page that contains a link to data page. The page is meant to be static-optimized.
- `pages/data.js` - The data page that depends on `API_URL` in public runtime config (Actually it prints `publicRuntimeConfig.API_URL` directly). This page is meant to be server-rendered.

Reproduction steps are:

1. Clone this repository & `yarn`
2. `yarn build`
3. `API_URL=https://my.api yarn start` and visit `http://localhost:3000`
4. Click "Data page" link on `http://localhost:3000`. Browser will navigate to `http://localhost:3000/data` without full reload.

## Expected behavior

The `/data` page shows:
```
We show data from API URL: https://my.api
```

## Actual behavior

The `/data` page shows:
```
We show data from API URL:
```

Runtime config "API_URL" in server-rendered page does not present.

However, if we visit `http://localhost:3000/data` directly, we can see the API URL again.

## Screenshots

![scenario](https://user-images.githubusercontent.com/108608/68006516-bfe03c00-fcb3-11e9-90ae-7c94fcabeec0.gif)

## System information

- OS: macOS
- Browser (if applies) Google Chrome
- `next`: 9.1.2
- `react`: 16.11.0
- `react-dom`: 16.11.0

## Additional context

[The scenario](https://github.com/MrOrz/nextjs-runtime-config-bug) is the simplified from [this website](https://github.com/cofacts/rumors-site/tree/dev). I want to have a [statically rendered landing page](http://en.cofacts.hacktabl.org/) linking to a [server-rendered article list](http://en.cofacts.hacktabl.org/articles); however, when users go to article list from the landing page, the HTTP requests always fail because API URL in config is not set.

When I deploy the website, I put the built website in [Docker image](https://github.com/cofacts/rumors-site/blob/build/Dockerfile). Production sites and staging sites will share the same docker image to ensure consistency between the two environments; the only difference between them are the API endpoints they connect to, which is [specified in docker-compose file](https://github.com/cofacts/rumors-deploy/blob/master/docker-compose.production.yml#L38). This is why I put API URL in `publicRuntimeConfig` instead of build-time config.

**Comment by Baukaalm** [comment] 2019-11-01 08:14
Added _app.js in your app

```
import React from 'react';
import App from 'next/app';

class MyApp extends App {
  static async getInitialProps({ Component, ctx }) {

    const pageProps = Component.getInitialProps
      ? await Component.getInitialProps(ctx)
      : {};

    return { pageProps };
  }


  render() {
    const { Component, pageProps } = this.props;
    return (
      <div>
              <Component {...pageProps} />       
      </div>
    );
  }
}

export default MyApp
```

**Comment by MrOrz** [comment] 2019-11-01 09:46
@Baukaalm Thanks for the info. Doesn't adding `getInitialProps` to `App` forces all pages to serve from server?

What I wanted is keeping the landing page (`pages/index.js`) optimized as a static page, but I should be able to navigate to server-rendered pages without problem.

**Comment by MrOrz** [comment] 2019-11-01 09:51
A workaround would be replacing
```
// pages/index.js
<Link href="/data">
  <a>
    Data page
  </a>
</Link>
```

to this:
```
<a href="/data">
  Data page
</a>
```

This actually forces the browser to load the full page when navigating from landing page to data page. But it is an acceptable workaround to me, because I want a statically optimized landing page anyway.

**Comment by MrOrz** [comment] 2019-11-01 10:05
I guess another "workaround" I learned from https://github.com/zeit/next.js/issues/7827 is, I can build a API route that proxies stuff to the real API server according to the environment variable. In this case I won't need to put `publicRuntimeConfig.API_URL` in `pages/data.js`, I just need `/api/<the_proxy>`.

Does next.js 9 discourage people from using APIs other than API routes?

**Comment by xyy94813** [comment] 2019-11-04 04:02
I got the same problem.

step 1:

// in `next.config.js`
```js
function getPublicRuntimeConfig () {
    const runtimeConfig = {};
    
    if (process.env.VAR) {
        runtimeConfig.VAR = process.env.VAR;
    }

    return runtimeConfig;
}

module.exports = {
    publicRuntimeConfig: getPublicRuntimeConfig()
}
```

step2:

`yarn run build`

step3:

`VAR=test yarn run start`

```jsx
import getConfig from "next/config";

const Demo = () => {
    return `Demo`;
}

Demo.getInitialProps = async () => {
    const { publicRuntimeConfig } = getConfig();

    // work well in server side, but `publicRuntimeConfig.VAR` is undefined in browser;
    console.log(publicRuntimeConfig.VAR);

    return {};
}
```

**Comment by Timer** [comment] 2019-11-09 20:38
Duplicate of #7844

**Closed by Timer** 2019-11-09 20:38 UTC

**Comment by balazsorban44** [comment] 2022-01-30 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
