### ISSUE TITLE
Tree shaking seems to be broken in antd example

### ISSUE THREAD

**Issue by shkarupa-alex** [zeit/next.js#9141] opened 2019-10-19 18:11 UTC
# Examples bug report

## Example name

with-ant-design

## Describe the bug

Antd v4 (alpha) builds should include only actually used icons. But in `with-ant-design` example all 1Mb of icons are bundled.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Download and unpack two attached archives. Both contain same example but one with nextjs and one with create-react-app
2. Run `npm i` in both examples
3. Run `npm run stats` in both examples
4. See at `icons-svg` size inside `@and-design`. With `create react app` it will be about 9Kb. With nextjs it will be about 800Kb.

[cra-antico4.zip](https://github.com/zeit/next.js/files/3747031/cra-antico4.zip)
[next-antico4.zip](https://github.com/zeit/next.js/files/3747032/next-antico4.zip)

## Expected behavior

Same `antd` snippets should have approximately same budle size with nextjs and create-react-app

## Screenshots
With next
![next](https://user-images.githubusercontent.com/1289725/67149460-80315180-f2bc-11e9-9929-50c0bda9b319.png)

With cra
![cra](https://user-images.githubusercontent.com/1289725/67149468-8cb5aa00-f2bc-11e9-8793-c8740ef81edc.png)

## System information

- OS: MacOS
- Version of Next.js: 9.1.1

**Comment by timneutkens** [comment] 2019-10-19 19:23
Duplicate of #4101

**Closed by timneutkens** 2019-10-19 19:23 UTC

**Comment by balazsorban44** [comment] 2022-01-31 01:26
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
