### ISSUE TITLE
Router doesn't work w/Ant Design

### ISSUE THREAD

**Issue by iamricky** [zeit/next.js#6972] opened 2019-04-09 15:17 UTC
# Bug report

## Describe the bug
`<Link>` will not navigate to pages with Ant Design stylesheets.

## To Reproduce
https://github.com/iamricky/nextjs-bug

## Expected behavior
The app navigates to each route except `/test`. It fails silently w/o errors, so I don't have a way of investigating it. The app **will** navigate to `/test` if the stylesheets on line 11 of `pages/test.js` are omitted or commented out:

```
import 'antd/lib/button/style/css';
import 'antd/lib/checkbox/style/css';
import 'antd/lib/date-picker/style/css';
import 'antd/lib/form/style/css';
import 'antd/lib/input/style/css';
import 'antd/lib/radio/style/css';
import 'antd/lib/select/style/css';
import 'antd/lib/tag/style/css';
```

## System information:
 - OS: macOS 10.13.6
 - Browser: Chrome 73.0.3683.86
 - Version of Next.js: ^8.0.4

**Comment by timneutkens** [comment] 2019-04-09 23:34
Probably a duplicate of https://github.com/zeit/next-plugins/issues/282

**Closed by timneutkens** 2019-04-09 23:34 UTC

**Comment by nuintun** [comment] 2019-04-10 02:16
@timneutkens Any plan to fixed this bug ?

**Comment by iamricky** [comment] 2019-04-10 03:30
Definitely not related to my issue. Moving on to `react-universal-component`. Next seemed promising but if setting up stylesheets is this tedious, I can only assume the the rot runs deep.

**Comment by timneutkens** [comment] 2019-04-10 12:03
It's related to a bug in webpack. webpack doesn't play well with css imports on dynamic entries.

**Comment by shashkovdanil** [comment] 2019-04-11 07:16
Is there at least some work on a fixed bug? Or use CSS-in-JS

**Comment by axu6705** [comment] 2019-06-12 10:09
still can't work.

**Comment by smithyj** [comment] 2019-06-13 07:04
Seems to be unable to work because of antd

**Comment by davidcunha** [comment] 2019-07-17 12:12
I'm trying with next.js 8.1 and antd 3.20 and it still doesn't work. 

I also replicated the scenario from https://github.com/zeit/next.js/blob/canary/examples/with-ant-design-less which doesn't import Antd .css styles. It works perfectly, but besides "Link" not working properly as mentioned in this issue, it loads the globals styles from Antd.

**Comment by davidcunha** [comment] 2019-07-17 14:59
Ok It seems a found a solution:

1 - follow and implement https://github.com/zeit/next.js/blob/canary/examples/with-ant-design-less
2 - in .babelrc put the "style" as false. I'm setting  as false because I don't want to pollute the whol platform with Antd global styles.
3 - import the Antd component you want in the appropriate component or page:

`import { Calendar } from 'antd';`

4 - Finally, not the best option ever, cause it will load the styles of components that are not present in a page. However it's better than having a router than doesn't work. Go to _app.js (if you don't have one create it, or probably it would work if you had _document.js - didn't test it), and load the styles from all the Antd components you will use:

`
import 'antd/lib/calendar/style/index.less';
import 'antd/lib/select/style/index.less';
import 'antd/lib/radio/style/index.less';
`

I'm using .less, but it works with .css too, if you use @zeit/next-css as dependency of course.

**Comment by poulainv** [comment] 2019-11-21 14:43
Thanks @davidcunha fixed my issue as well with CSS. Hoping that https://github.com/zeit/next.js/issues/8626 can resolve that.

**Comment by balazsorban44** [comment] 2022-01-30 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
