### ISSUE TITLE
styled-component overridden on hot reload

### ISSUE THREAD

**Issue by ghost** [zeit/next.js#4068] opened 2018-03-28 02:05 UTC
- [x ] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

My page contains this very basic code:
```
import React from 'react'
import styled from 'styled-components'

const Title = styled.h1`
  color: pink;
  font-size: 50px;
`

export default () => <Title>My page</Title>
```

When I refresh the page, I expect the Title to be of color pink

## Current Behavior

The first time the page is built, the title does appear as pink. When I refresh the page, the pink color is no longer respected.
If I change the color in the code to anything else, and save the file, then the page will update. But again, upon refreshing, the changes are lost again. I have no clue what might be causing this. Any help is appreciated.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |      latest   |
| node    |         |
| OS      |       arch  |
| browser |       vivaldi  |

**Comment by lucleray** [comment] 2018-04-03 18:52
I have the same bug, with a different setup. I have a monorepo with two folders :
- `app`, with my next.js app
- `ui` , with my 'ui library' using styled-components

I have it in an example repo : https://github.com/lucleray/ssr-ui-library

When I update the background color for example, in the ui folder, and save the file, the page updates.
But then, if I refresh the page, the updates are lost.

**Comment by ianregister** [comment] 2018-04-08 21:55
Is this anything to do with the injection order of the style sheets in `<head>`?

**Comment by lucleray** [comment] 2018-04-08 21:57
@ianregister No, the order of the injection in `<head>` is not related

The problem is that the server and the client don't render the same code for stylesheets

**Comment by tvthatsme** [comment] 2018-04-18 07:56
@lucleray, try this:

Make sure you have `babel-plugin-styled-components` as a dependency and in your package.json tell babel that you are doing server-side rendering.

Think that this is just a configuration issue you are facing.

package.json
```json
"babel": {
    "env": {
      "development": {
        "presets": ["next/babel"],
        "plugins": [
          [
            "styled-components",
            {
              "ssr": true,
              "displayName": true
            }
          ]
        ]
      },
      "production": {
        "presets": ["next/babel"],
        "plugins": [
          [
            "styled-components",
            {
              "ssr": true,
              "displayName": false
            }
          ]
        ]
      }
    }
  }

**Comment by valeeum** [comment] 2018-07-25 00:05
having similar issue where any edits to a component (non styles related) will cause an error "Warning: Prop `className` did not match. Server:" on subsequent hard page fresh.  Need to restart server for it to go away.  

@sea129 were you able to fix?

**Comment by chenshuiluke** [comment] 2018-08-11 01:04
Lol, having the same issue here. @valeeum were you able to solve it?

**Comment by lucleray** [comment] 2018-08-19 10:15
I did a bit of research on this issue, and I think it might be link some sort of "webpack caching".

I use the code here as an example of the issue : https://github.com/lucleray/ssr-ui-library

The `app` is using Next.js and has a dependency on the `ui`. I'm using yarn's workspace to link them but it could be a more simple `yarn link`.

On the server-side, the bundle does not include the `ui` module and treats it as `external` (because it's in node_modules).
On the client-side, the bundle includes the `ui` module.

It appears like this in the `.next/static` (client-side) bundles :
```js
/***/ "../ui/bundle.js":
/*!***********************!*\
  !*** ../ui/bundle.js ***!
  \***********************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";


Object.defineProperty(exports, '__esModule', { value: true });

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var styled = _interopDefault(__webpack_require__(/*! styled-components */ "../node_modules/styled-components/dist/styled-components.browser.esm.js"));

const UiButton = styled.button`
  background: black;
`;

exports.UiButton = UiButton;


/***/ }),
```

On the other hand, in the `.next/server` (server-side) bundles, it appears like this :
```js
/***/ "@monorepo/ui":
/*!*******************************!*\
  !*** external "@monorepo/ui" ***!
  \*******************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@monorepo/ui");

/***/ }),
```

What is weird is that `module.exports = require("@monorepo/ui")` should resolve to the `ui` package and just work fine. But it seems like it's cached and does not resolve to the actual `ui` package.

If I change the background color of the button in the `ui` to blue for example. The hot reloader updates the page correctly. But if I refresh, then the page is rendered server-side with the old color (green in my example). It's like the server-side bundle is not resolving the `@monorepo/ui` dependency to go the actual package, but is using a cached version of it.

**Comment by timneutkens** [comment] 2018-08-19 13:00
`require` has a built-in cache (`require.cache`) this is expected behavior for dependencies in node_modules, as we won't bundle anything inside node_modules on the server (for compilation speed).

**Comment by lucleray** [comment] 2018-08-19 22:44
Ok, that makes sense.

So the issue is that the hot-reloader doesn't reload the code changes in external dependencies, on the server-side, right ?

In the example I shared, I expect my code changes to be loaded both on client (which is the case) and server (which is not the case) side in development mode.

**Comment by timneutkens** [comment] 2018-08-20 06:41
> So the issue is that the hot-reloader doesn't reload the code changes in external dependencies, on the server-side, right?

Exactly, we only delete full paths from the require.cache.

**Comment by lucleray** [comment] 2018-08-20 22:18
How do you think I could solve this @timneutkens ?

Should I remove `@monorepo/ui` from the external dependencies so it's bundled in the server-side bundles ? That works but since I'm already transpiling it, wouldn't it better to just require it ?

**Comment by timneutkens** [comment] 2018-11-08 12:07
It might be as easy as using https://github.com/martpie/next-plugin-transpile-modules to enable module compilation.

**Closed by timneutkens** 2018-11-08 12:07 UTC
Labels: good first issue, help wanted

**Comment by jeankvd** [comment] 2019-03-15 00:42
@timneutkens Why was this closed? this issue still exists on the latest version

**Comment by oscargws** [comment] 2019-04-06 13:17
Still having this issue as well

**Comment by asotoglez** [comment] 2019-04-08 20:41
Im still having this issue too

**Comment by Ruegen** [comment] 2019-04-14 01:12
Ditto too here

**Comment by MaxMcKinney** [comment] 2019-04-19 21:07
Also having this issue

**Comment by devprodark** [comment] 2019-09-04 03:50
hi guys, I found a solution. you need a custom document.js, and add babel plugin for styled components. In the root create a _document.js and add the following: 

import Document, { Head, Main, NextScript } from 'next/document'
import { ServerStyleSheet } from 'styled-components'

class MyDocument extends Document {
  static getInitialProps ({ renderPage }) {
    const sheet = new ServerStyleSheet()
    const page = renderPage(App => props => sheet.collectStyles(<App {...props} />))
    const styleTags = sheet.getStyleElement()
    return { ...page, styleTags }
  }

  render () {
    return (
      <html>
        <Head>
          <title>Your site title</title>
          {this.props.styleTags}
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}

export default MyDocument

and:

npm install --save -D babel-plugin-styled-components.


you'll see that hot reload of course works, but also when you refresh page will be styled. 

Cheers.

**Comment by devprodark** [comment] 2019-09-04 03:52
hi guys, I found a solution. you need a custom document.js, and add babel plugin for styled components. In the root create a _document.js and add the following:

import Document, { Head, Main, NextScript } from 'next/document'
import { ServerStyleSheet } from 'styled-components'

class MyDocument extends Document {
  static getInitialProps ({ renderPage }) {
    const sheet = new ServerStyleSheet()
    const page = renderPage(App => props => sheet.collectStyles(<App {...props} />))
    const styleTags = sheet.getStyleElement()
    return { ...page, styleTags }
  }

  render () {
    return (
      <html>
        <Head>
          <title>Your site title</title>
          {this.props.styleTags}
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}

export default MyDocument

and:

npm install --save -D babel-plugin-styled-components.

you'll see that hot reload of course works, but also when you refresh page will be styled.

Cheers.

**Comment by devprodark** [comment] 2019-09-04 03:55
ok people. here is the solution. create an _document.js in root of directory and add this.
`import Document, { Head, Main, NextScript } from 'next/document'
import { ServerStyleSheet } from 'styled-components'

class MyDocument extends Document {
  static getInitialProps ({ renderPage }) {
    const sheet = new ServerStyleSheet()
    const page = renderPage(App => props => sheet.collectStyles(<App {...props} />))
    const styleTags = sheet.getStyleElement()
    return { ...page, styleTags }
  }

  render () {
    return (
      <html>
        <Head>
          <title>Your site title</title>
          {this.props.styleTags}
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}

export default MyDocument`

then npm install --save -D babel-plugin-styled-components

also create a custom app in pages directory, _App.js and add:
`import React from "react";
import App from "next/app";

class MyApp extends App {
  render() {
    const { Component, pageProps } = this.props;
    return <Component {...pageProps} />;
  }
}

export default MyApp;
`

you're all set

**Comment by devprodark** [comment] 2019-09-04 03:56
`import Document, { Head, Main, NextScript } from 'next/document'
import { ServerStyleSheet } from 'styled-components'

class MyDocument extends Document {
  static getInitialProps ({ renderPage }) {
    const sheet = new ServerStyleSheet()
    const page = renderPage(App => props => sheet.collectStyles(<App {...props} />))
    const styleTags = sheet.getStyleElement()
    return { ...page, styleTags }
  }

  render () {
    return (
      <html>
        <Head>
          <title>Your Lord and Savior</title>
          {this.props.styleTags}
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}

export default MyDocument`

**Comment by devprodark** [comment] 2019-09-04 03:57
`return (
      <html>
        <Head>
          <title>Your Lord and Savior</title>
          {this.props.styleTags}
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    )`

**Comment by devprodark** [comment] 2019-09-04 03:58
not sure why github doesn't want me to post this code, but here is the code to return from document.js:

`return (
      <html>
        <Head>
          <title>Your Lord and Savior</title>
          {this.props.styleTags}
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    )`

**Comment by omendez85** [comment] 2019-09-05 00:01
> Also having this issue
> 
> Edit (solution):
> 
> This issue is related to not having the babel config setup correctly. If you look at the official example of NextJS with styled-components you'll notice they have a `.babelrc` file with:
> 
> ```js
> {
>     "presets": ["next/babel"],
>     "plugins": [["styled-components", { "ssr": true }]]
> }
> ```
> 
> Then you must add this plugin to the devDependencies in your `package.json` file
> 
> ```js
> "devDependencies": {
>     "babel-plugin-styled-components": "^1.8.0"
> },
> ```
> 
> Then run your install command, `yarn install` or `npm install` and then you'll be good to go!
> 
> **P.S: Be sure to only have one tab open for your localhost dev work!**

This works, Thanks

**Comment by TheRusskiy** [comment] 2019-11-21 11:19
unfortunately, it's still an issue

**Comment by Igor2122** [comment] 2019-11-30 08:58
not sure how relevant this info will be, but how i fixed it for myself is i followed the example from next repo and integrated the missing bits a pieces 
https://github.com/zeit/next.js/tree/canary/examples/with-typescript-styled-components

**Comment by limitlessloop** [comment] 2020-03-30 15:14
I was using next.js and @MaxMcKinney solution worked for me. Just make sure you have configured the `.babelrc` preferences correctly as it's quite a confusing format or arrays and objects to follow.

This was my `.babelrc` file for example:

```json
{
    "presets": [
        [
            "next/babel",
            {
                "styled-jsx": {
                    "plugins": [
                        "styled-jsx-plugin-postcss"
                    ]
                }
            }
        ]
    ],
    "plugins": [
        [
            "styled-components",
            {
                "ssr": true
            }
        ]
    ]
}
```

**Comment by CalvinKorver** [comment] 2020-05-08 03:39
This issue will occur if you're cloning and building on one of the Next.js examples that don't have the same `package.json` dependencies and `.babelrc` settings. In addition to MaxMckinney solution, ensure that you have the correct dependency in `package.json`. I was outright missing `"styled-components": "^5.0.0"`

**Comment by taiwanhua** [comment] 2020-07-23 06:06
In my case ,just add _app.js and _document.js file under pages floder,it work fine.
` 
// _app.js
import App from 'next/app'
import { ThemeProvider } from 'styled-components'

const theme = {}

export default class MyApp extends App {
    render() {
        const { Component, pageProps } = this.props
        return (
            <ThemeProvider theme={theme}>
                <Component {...pageProps} />
            </ThemeProvider>
        )
    }
}
`
`
// _document.js
import Document from 'next/document'
import { ServerStyleSheet } from 'styled-components'

export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const sheet = new ServerStyleSheet()
    const originalRenderPage = ctx.renderPage

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: (App) => (props) =>
            sheet.collectStyles(<App {...props} />),
        })

      const initialProps = await Document.getInitialProps(ctx)
      return {
        ...initialProps,
        styles: (
          <>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </>
        ),
      }
    } finally {
      sheet.seal()
    }
  }
}


`

**Comment by 521707** [comment] 2020-08-24 11:11
> In my case ,just add _app.js and _document.js file under pages floder,it work fine.
> 
> ```
> // _app.js
> import App from 'next/app'
> import { ThemeProvider } from 'styled-components'
> 
> const theme = {}
> 
> export default class MyApp extends App {
>     render() {
>         const { Component, pageProps } = this.props
>         return (
>             <ThemeProvider theme={theme}>
>                 <Component {...pageProps} />
>             </ThemeProvider>
>         )
>     }
> }
> ```
> 
> ```
> // _document.js
> import Document from 'next/document'
> import { ServerStyleSheet } from 'styled-components'
> 
> export default class MyDocument extends Document {
>   static async getInitialProps(ctx) {
>     const sheet = new ServerStyleSheet()
>     const originalRenderPage = ctx.renderPage
> 
>     try {
>       ctx.renderPage = () =>
>         originalRenderPage({
>           enhanceApp: (App) => (props) =>
>             sheet.collectStyles(<App {...props} />),
>         })
> 
>       const initialProps = await Document.getInitialProps(ctx)
>       return {
>         ...initialProps,
>         styles: (
>           <>
>             {initialProps.styles}
>             {sheet.getStyleElement()}
>           </>
>         ),
>       }
>     } finally {
>       sheet.seal()
>     }
>   }
> }
> ```

How should I use it in the Material-UI?

**Comment by SPeshov** [comment] 2021-01-21 13:41
I had only one component failing and after trying everything from the above examples only this helped:
![Screenshot 2021-01-21 at 14 09 46](https://user-images.githubusercontent.com/800425/105358463-7c465a80-5bf6-11eb-81bd-ae508077e118.png)

It was picking up styles from some other `div` component, so I've tried adding `id` on them hoping that it will resolve somehow but it did no.

The only thing that worked was switching from `div` to some other element type.

**Comment by Jay-flow** [comment] 2021-02-03 07:07
> @lucleray, try this:
> 
> Make sure you have `babel-plugin-styled-components` as a dependency and in your package.json tell babel that you are doing server-side rendering.
> 
> Think that this is just a configuration issue you are facing.
> 
> package.json
> 
> ```json
> "babel": {
>     "env": {
>       "development": {
>         "presets": ["next/babel"],
>         "plugins": [
>           [
>             "styled-components",
>             {
>               "ssr": true,
>               "displayName": true
>             }
>           ]
>         ]
>       },
>       "production": {
>         "presets": ["next/babel"],
>         "plugins": [
>           [
>             "styled-components",
>             {
>               "ssr": true,
>               "displayName": false
>             }
>           ]
>         ]
>       }
>     }
>   }
> ```

Thx, It is work for me :)

**Comment by ConstaXI** [comment] 2021-05-28 18:08
> @lucleray, try this:
> 
> Make sure you have `babel-plugin-styled-components` as a dependency and in your package.json tell babel that you are doing server-side rendering.
> 
> Think that this is just a configuration issue you are facing.
> 
> package.json
> 
> ```json
> "babel": {
>     "env": {
>       "development": {
>         "presets": ["next/babel"],
>         "plugins": [
>           [
>             "styled-components",
>             {
>               "ssr": true,
>               "displayName": true
>             }
>           ]
>         ]
>       },
>       "production": {
>         "presets": ["next/babel"],
>         "plugins": [
>           [
>             "styled-components",
>             {
>               "ssr": true,
>               "displayName": false
>             }
>           ]
>         ]
>       }
>     }
>   }
> ```

Thanks, it worked here!

**Comment by brianwachira** [comment] 2021-08-10 10:01
> Also having this issue
> 
> Edit (solution):
> 
> This issue is related to not having the babel config setup correctly. If you look at the official example of NextJS with styled-components you'll notice they have a `.babelrc` file with:
> 
> ```js
> {
>     "presets": ["next/babel"],
>     "plugins": [["styled-components", { "ssr": true }]]
> }
> ```
> 
> Then you must add this plugin to the devDependencies in your `package.json` file
> 
> ```js
> "devDependencies": {
>     "babel-plugin-styled-components": "^1.8.0"
> },
> ```
> 
> Then run your install command, `yarn install` or `npm install` and then you'll be good to go!
> 
> **P.S: Be sure to only have one tab open for your localhost dev work!**

For ones going through the same issue, this worked for me.
I also got help from this  [article](https://medium.com/swlh/server-side-rendering-styled-components-with-nextjs-1db1353e915e)

**Comment by mateenkiani** [comment] 2021-09-01 06:29
I was having the exact same issue and it was resolved by doing:
`npm i babel-preset-next`
and adding this .babelrc file:
`{
    "presets": ["next/babel"],
    "plugins": [["styled-components", { "ssr": true }]]
}`

**Comment by N3XT14** [comment] 2021-12-25 18:49
I am not using babel but SWC hence I don't have the .rc file. Since the issue is still present. Can anyone suggest what configuration will be needed and where to fix this issue?

**Comment by balazsorban44** [comment] 2022-01-27 01:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
