### ISSUE TITLE
New option to prevent readline.cursorTo and readline.clearScreenDown

### ISSUE THREAD

**Issue by kaelzhang** [zeit/next.js#6815] opened 2019-03-28 02:20 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
`readline.cursorTo` and `readline.clearScreenDown` ([here](https://github.com/zeit/next.js/blob/78bcfa07b2b3f495d7bf4d215b9f5442802fcdf6/packages/next/build/output/store.ts#L25)) help to make the outputs clean for developing react components and pages, but it ruins the outputs when we are doing some testing because it changes the output format, prints so many blank rows and wipes out other outputs such as `console.log`s for debugging purpose.

Besides, managing the outputs and avoiding using plain `console.log`s is a good practice for libraries. 

## Describe the solution you'd like

- Provide an option to disable the feature.
- wrap `unistore` instance into a new class which accepts the option above

Or

Is it possible to allow us to change the unistore subscriber?

## Describe alternatives you've considered
> A clear and concise description of any alternative solutions or features you've considered.

## Additional context
> Add any other context or screenshots about the feature request here.

**Comment by indiejoseph** [comment] 2019-03-28 09:35
+1

**Comment by Janpot** [comment] 2019-03-28 11:35
duplicate of: https://github.com/zeit/next.js/issues/6525
pending PR: https://github.com/zeit/next.js/pull/6758
Related: https://github.com/zeit/next.js/issues/4808

**Closed** 2019-03-28 13:18 UTC
