### ISSUE TITLE
Index path not working on other pages

### ISSUE THREAD

**Issue by mohammadou1** [zeit/next.js#9300] opened 2019-11-03 23:30 UTC
If you check this url 
https://nextstore.itmohou.now.sh/

everything will work fine 
if you go to footer and navigate to about
then press home it will work fine also

but if you went to any error page (any page because there are no pages yet)

and press home
it will get stuck and wont go to home
other pages will work perfectly
i couldnt find the problem

here is the code 
https://github.com/mohammadou1/nextstore

**Comment by mohammadou1** [comment] 2019-11-04 08:01
Please help :( 

I can't figure the issue here.
it doesnt make any sense at all :\

**Comment by timneutkens** [comment] 2019-11-04 09:37
Probably a duplicate of https://github.com/zeit/next-plugins/issues/282

**Closed by timneutkens** 2019-11-04 09:37 UTC

**Comment by balazsorban44** [comment] 2022-01-31 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
