### ISSUE TITLE
SCSS in new CSS Support

### ISSUE THREAD

**Issue by andreupifarre** [zeit/next.js#9961] opened 2020-01-06 15:15 UTC
I tried implementing the new CSS support under the feature flag with `.module.scss` and `.scss` files but I get an error saying that I need an appropriate loader.

How can I load `.scss` files with the new CSS support?

**Comment by Timer** [comment] 2020-01-06 15:19
Sass is not currently supported by the new CSS support.

**Comment by andreupifarre** [comment] 2020-01-06 15:23
That explains it. 
Are you guys planning to add this anytime soon? And is there an alternative way of implementing SASS with it, maybe by using custom loaders in the `next.config.js` or similar?

**Comment by gudvinga** [comment] 2020-01-06 17:59
@andreipfeiffer
In our project we use the next-transpile-modules plugin and, accordingly, custom scss loader in next.config.js
[https://www.npmjs.com/package/next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules)

**Comment by Timer** [comment] 2020-01-06 21:14
The new CSS support will ship stable before we (potentially) add support for Sass.

In the meantime, you can use the legacy Sass plugin.

**Comment by andreupifarre** [comment] 2020-01-08 10:33
@Timer do you mean implementing the new CSS Support along with `@zeit/next-sass` or avoiding new CSS Support altogether if and until SASS is supported?

**Comment by timneutkens** [comment] 2020-01-08 10:35
> or rather avoiding new CSS Support altogether if and until SASS is supported?

This.

**Comment by Epenance** [comment] 2020-01-15 08:52
Would love this too, we have both global styles from thirdparty css frameworks, and then our own styles that we want to be able to scope. Its sad there is no easy way to implement this while we wait.

**Comment by bulutfatih** [comment] 2020-01-16 14:35
Will you support Less too? @Timer @timneutkens

**Comment by Epenance** [comment] 2020-01-16 14:46
> @andreipfeiffer
> In our project we use the next-transpile-modules plugin and, accordingly, custom scss loader in next.config.js
> https://www.npmjs.com/package/next-transpile-modules

Could you give an example of how you make it work?

**Comment by andreipfeiffer** [comment] 2020-01-16 14:56
@Epenance @gudvinga you have tagged the wrong person. I have nothing to do with this issue.

Maybe you wanted to tag @andreupifarre ?

**Comment by timneutkens** [comment] 2020-01-16 15:13
@bulutfatih we won't add it by default as there's a very small percentage using less compared to css and scss/sass.

**Comment by kachkaev** [comment] 2020-01-16 15:34
@timneutkens less support is needed for projects relying on [Ant Design](https://ant.design/), which is a UI library with 300K weekly downloads. A corresponding Next.js example is [`with-ant-design-less`](https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less).

**Comment by timneutkens** [comment] 2020-01-16 16:09
@kachkaev for reference less than 10% of Next.js apps uses less.

Their instruction for create-react-app doesn't use less: https://ant.design/docs/react/use-with-create-react-app

**Comment by kachkaev** [comment] 2020-01-16 16:22
Ant design ships with both less files and css, the latter are a precompiled version of the shipped less styles. Basic setup instructions rely on using css files, which is simple, but does not allow theme customisation. [Customising Theme](https://ant.design/docs/react/customize-theme) involves loading less.

I love Next.js for giving app developers an option to customise webpack – this is what we are doing with Next.js 9.1 + `next-css` + `next-less` to get a customised Ant Design at the moment. Just saying that it it'd be great to see new recipes for less (and sass) files in some centralised place, just to avoid simple setup mistakes.

Note that by pushing Next.js into the community, you reduce developers’ average literacy in webpack matters, because it becomes just an implementation detail of an awesome higher-lever tool  😁  After using Next.js for a couple of years I personally fell much less confident in that I can configure webpack properly myself, and I guess I'm not alone here 😅 ≈5% of Next.js users may sound like a small proportion, but it might still be a big absolute figure given your scale 😉

**Comment by timneutkens** [comment] 2020-01-16 16:36
Might consider investigating adding Less and maintaining support for it under enterprise support, then I can justify adding it long term. Feel free to email enterprise@zeit.co.

**Comment by timneutkens** [comment] 2020-01-19 09:51
Closing this one as #10134 is more complete.

**Closed by timneutkens** 2020-01-19 09:51 UTC
Labels: Type: Feature Request

**Comment by Timer** [comment] 2020-01-23 13:47
Sass support has been experimentally landed. We'd like feedback if you upgrade to `next@canary`!

**Comment by balazsorban44** [comment] 2022-01-30 15:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
