### ISSUE TITLE
with-amp example is not pass AMP Validator

### ISSUE THREAD

**Issue by phongtattuan** [zeit/next.js#3155] opened 2017-10-23 12:53 UTC
Because of AMP restriction, it does not allow custom script, 
But the server rendering include custom script of next.js, so `with-amp` example is not pass AMP Validator.
Can we remove those scripts ?

Thank you.

**Comment by ismamz** [comment] 2017-10-23 16:02
There are two problems:

1. `<meta charset="utf-8" />` appears twice (solution: remove [this line](https://github.com/zeit/next.js/blob/master/examples/with-amp/pages/_document.js#L9))

2. `The attribute 'as' may not appear in tag 'link rel='.`

To remove the `as` attribute from Next.js scripts you can do the following:

Add a `_head.js` file into `/pages` directory (like `_document.js`).

In this file you should extend `Head` and copy 3 methods from main class:
* [getChunkPreloadLink()](https://github.com/zeit/next.js/blob/master/server/document.js#L37)
* [getPreloadDynamicChunks()](https://github.com/zeit/next.js/blob/master/server/document.js#L68)
* [render()](https://github.com/zeit/next.js/blob/master/server/document.js#L81)

```js
// _head.js
import { Head } from 'next/document'

export default class MyHead extends Head {
  getChunkPreloadLink (filename) {
    // remove as='script' in return statement
  }

  getPreloadDynamicChunks () {
    // remove as='script' in return statement
  }

  render () {
    // in return statement remove as='script' from <link rel='preload'... lines
  }
}

// you should redeclare this function because is not exported
function getPagePathname (pathname, nextExport) {
  if (!nextExport) return pathname
  if (pathname === '/') return '/index.js'
  return `${pathname}/index.js`
}
```

`getPagePathname` function has to be declared again because is used by the `render` method.

Finally, you should change `_document.js` and import the extended class `MyHead`:

```js
// _document.js
import Head from './_head'
```

The AMP validation is successful but you get a warning:
```
<link rel=preload> must have a valid `as` value`
```
[Here is a discussion](https://github.com/ampproject/amphtml/issues/2492
) about this warning from the AMP Project repo.

![image](https://user-images.githubusercontent.com/3452011/31898019-6ac488a4-b7ee-11e7-9c4c-f999a412b60b.png)

This is the solution that I've found, probably it's not the best, and it should be reviewed 😉.

Related: #2310

**Comment by phongtattuan** [comment] 2017-10-25 01:01
Thanks so much @ismamz 
That's work

Another problem I am facing is using `styled-jsx` in AMP.
`styled-jsx` will render a tag `<style id='__jsx-178579435'>..</style>` which is not allow on AMP
AMP only allow `<style amp-custom>...</style>`

can we remove the `id` and add `amp-custom` to style tag with styled-jsx ?

**Comment by ismamz** [comment] 2017-10-25 16:20
You can add the `amp-custom` attribute to `<style>` tags generated by styled-jsx, and you can even combine all the CSS code. Look at your `_head.js` file, the `render()` method takes the styles array and you can manipulate them.

However, there are some problems: 1) styled-jsx will add class names to custom amp tags and it's not valid, 2) you are intervening the way of work of styled-jsx.

So, maybe styled-jsx is not the best option for an AMP site in this case.

**Comment by timneutkens** [comment] 2018-05-25 22:19
I'm going to close this as we're going to make some changes to better support AMP soon.

**Closed by timneutkens** 2018-05-25 22:19 UTC

**Comment by wallismith** [comment] 2018-06-04 22:30
@timneutkens thanks for the update. Looking forward to AMP changes soon. We have AMP templates and trying to migrate those to Next soon.

**Comment by robertoaikode** [comment] 2018-07-06 00:23
@timneutkens Great! we hope to receive news soon about an excellent integration of AMP with NextJs :smiley:

**Comment by varungargofb** [comment] 2018-12-20 11:31
@ismamz I'm currently working on AMP with ReactJs, is there a way to have custom attributes in square brackets such as [class] with reactJs on client side as well. As of now, reactJs when re-render all the custom attributes gets eliminated.
Also tried using react-amphtml, but same happened with AmpHelpers.Bind

**Comment by ismamz** [comment] 2018-12-20 15:43
@varungargofb Hi!, I think that this is not a Next.js related question.
But, the only way I found to use that kind of attributes is setting inner HTML.
For example, if you want to reproduce [the example from the amp-bind docs](https://www.ampproject.org/docs/reference/components/amp-bind#a-simple-example):

```jsx
<div dangerouslySetInnerHTML={{__html: '<p [text]="\'Hello \' + foo">Hello World</p>'}}/> 
<button on="tap:AMP.setState({foo: 'amp-bind'})">Say "Hello amp-bind"</button>
```

Other ways like using `React.createElement('p', { '[text]': "'Hello ' + foo" }, 'Hello World');` or `el.setAttribute('[text]', "'Hello ' + foo");` doesn't work.

I hope that helps you.
