### ISSUE TITLE
Error: Cannot find module '.next\server\pages-manifest.json'

### ISSUE THREAD

**Issue by FedeMadoery** [zeit/next.js#6373] opened 2019-02-20 14:33 UTC
# Bug report

## Describe the bug

When starting in prod mode (doing `next build` and `npm start`), this error occurs when I try to navigate to the page in the browser.

When run 'next build && next export', this error occurs immediately.

## To Reproduce

1. Clone the [repo ](https://github.com/LuisBonsembiante/skillmatrix)
2. Run `yarn install`
3. Run `next build`
4. Run `yarn start` or 'npm run start' / Run the 'start' script of package.json
5. Go to localhost:8000 in Chrome
6. Error appear in the console where you ran step 4

## Screenshots
```
Error: Cannot find module 'C:\...\.next\server\pages-manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at getPagePath (C:\...\node_modules\next-server\dist\server\require.js:14:27)
    at Object.requirePage (C:\...\node_modules\next-server\dist\server\require.js:30:22)
    at Object.loadComponents (C:\...\node_modules\next-server\dist\server\load-components.js:15:34)
    at Server.renderToHTMLWithComponents (C:\...\node_modules\next-server\dist\server\next-server.js:196:48)
    at Server.renderToHTML (C:\...\node_modules\next-server\dist\server\next-server.js:202:37)
    at Server.render (C:\...\node_modules\next-server\dist\server\next-server.js:185:33) code: 'MODULE_NOT_FOUND' }
```

## System information
 - OS: [Windows, Linux]
 - Browser: [Chrome]
 - Version of Next.js: [8.0.2-canary.4]

## Additional context

We had had the same error with Version of Next.js: 8.0.0 and 8.0.1

**Comment by LuisBonsembiante** [comment] 2019-02-21 13:09
Hi everybody....Any news about this?.... I need to put a implementation in production and I cant.... thanks...
Regards.... @timneutkens

**Comment by timneutkens** [comment] 2019-02-21 13:15
Feel free to help investigate / solve the issue.

**Comment by LuisBonsembiante** [comment] 2019-02-21 16:46
@timneutkens the deploy function work in your stages?.... we need to know that to check the problem...because if the build-export work for you, is a different issue that if it is doesnt work.

**Comment by timneutkens** [comment] 2019-02-21 16:55
I mean I haven't been able to even look into this issue yet. Hence why I was saying you could investigate it.

**Comment by LuisBonsembiante** [comment] 2019-02-21 17:09
Ok @timneutkens I found a solution for next export and build ...if I put module.exports = { target: 'server'}, in next.config.js....all working fin localy..but if a try to put all in production stage in zeit-now...the logs said me that;]
`Error: No serverless pages were built. https://err.sh/zeit/now-builders/now-next-no-serverless-pages-`
Any idea about that?....

**Comment by timneutkens** [comment] 2019-02-21 20:04
I'm not sure what you mean, how does that relate to this issue?

**Comment by pacocoursey** [comment] 2019-03-06 05:11
Jumping in to say that commenting out `target: 'serverless'` from my `next.config.js` also fixed the local build for me.

**Comment by ijjk** [comment] 2019-03-07 16:50
@FedeMadoery I just pulled down your repository and it appears to be working fine (build, export, and starting). I'm going to close this issue, if you are still having trouble feel free to leave a comment with more info.

**Closed by ijjk** 2019-03-07 16:50 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
