### ISSUE TITLE
Dynamic routes don't work with AWS S3 static hosting

### ISSUE THREAD

**Issue by eshikerya** [zeit/next.js#8430] opened 2019-08-20 04:04 UTC
# Bug report

## Describe the bug
S3 expect encoded url, like ```/page/%5Bid%5D.js``` but next requested the script w/o url encoding ```/page/[id].js```, so S3 give 404 error

## Expected behavior
urlEncode request path

**Comment by Timer** [comment] 2019-08-20 04:13
Feel free to send a PR!

**Comment by eshikerya** [comment] 2019-08-20 04:18
@Timer, any suggestion where this part is located? it would be helpful to know where to start digging...

**Comment by Timer** [comment] 2019-08-20 04:29
These two files, most likely:

https://github.com/zeit/next.js/blob/canary/packages/next/client/page-loader.js
https://github.com/zeit/next.js/blob/canary/packages/next/pages/_document.tsx

**Comment by LeonardPurschke** [comment] 2019-08-20 09:06
I am unsure if I have a similar problem: 
I am trying to create a blog that has a list of all posts (/blog) with a static path. The detail view for every post is implemented with the dynamic-routed-page feature (/post/[uid].js).

I have a link from my list to a detail view and it is working -> I can see the detail view
When I try to request the URL directly I am getting a 404-error.

I am using MAMP locally and firebase hosting for prod - same behaviour.

**Comment by eshikerya** [comment] 2019-08-20 09:13
open console and check network requests. if the script fails to load(/post/[uid].js) open it in new tab and change to ```/post/%5Buid%5D.js```
if script will load, you have same issue

**Comment by eshikerya** [comment] 2019-08-20 09:15
My PR is fixing this issue. so waiting for merge and release

**Comment by ijjk** [comment] 2019-09-18 14:48
Resolved by: https://github.com/zeit/next.js/pull/8435

**Closed by ijjk** 2019-09-18 14:48 UTC
Labels: good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-31 01:26
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
