### ISSUE TITLE
Make GetStaticProps and GetServerSideProps types use generic props

### ISSUE THREAD

**Issue by danilofuchs** [zeit/next.js#11033] opened 2020-03-13 02:00 UTC
# Feature request

The `GetStaticProps` and `GetServerSideProps` typescript types allow us to use the new data fetching methods with typescript, but there is no type check for props content.

## Is your feature request related to a problem? Please describe.

The current implementation is as follows:
```typescript
export type GetStaticProps = (ctx: {
  params?: ParsedUrlQuery
  preview?: boolean
  previewData?: any
}) => Promise<{
  props: { [key: string]: any }
  revalidate?: number | boolean
}>
```

## Describe the solution you'd like

```typescript
export type GetStaticProps<T = {}> = (ctx: {
  params?: ParsedUrlQuery
  preview?: boolean
  previewData?: any
}) => Promise<{
  props: T
  revalidate?: number | boolean
}>
```

This way, when defining a Props interface in our page, we can have type safety:
```typescript
interface Props {
    name: string
}

const Page: NextPage<Props> = (props) => {
    return <div>{props.name}</div>
}

export const getStaticProps: GetStaticProps<Props> = async (context) => {
    const name = await getName(); // string
    return {
        props: {
            name, // yay! Type checked props
        },
    };
};
```

Something very similar would be implemented for `GetServerSideProps`.

## Describe alternatives you've considered

As the new methods are not static properties of pages anymore, we cannot infer them via the page, so the user may need to add the generic `Props` type parameter in many places.

Perhaps the types could have more parameters to allow typing `previewData`?

**Comment by Timer** [comment] 2020-03-13 03:25
Try out `next@canary`, we already added generics!

**Comment by timneutkens** [comment] 2020-03-13 09:58
Fixed by https://github.com/zeit/next.js/pull/10856

**Closed by timneutkens** 2020-03-13 09:58 UTC

**Comment by abhijithvijayan** [comment] 2020-03-25 14:25
What about types in context params?

in `[id].ts`
```
export const getServerSideProps: GetServerSideProps = async (context) => {
    const { id } = context.params;
}
```

I get this error
```
Property 'id' does not exist on type 'ParsedUrlQuery | undefined'.
    27 | 
    28 | export const getServerSideProps: GetServerSideProps = async (context) => {
  > 29 |     const { id } = context.params;
```

**Comment by elias551** [comment] 2020-04-01 14:36
> What about types in context params?
> 
> in `[id].ts`
> 
> ```
> export const getServerSideProps: GetServerSideProps = async (context) => {
>     const { id } = context.params;
> }
> ```
> 
> I get this error
> 
> ```
> Property 'id' does not exist on type 'ParsedUrlQuery | undefined'.
>     27 | 
>     28 | export const getServerSideProps: GetServerSideProps = async (context) => {
>   > 29 |     const { id } = context.params;
> ```
> 
> In VSCODE
> ![Screenshot_20200325_195818](https://user-images.githubusercontent.com/34790378/77547354-194f3e80-6ed3-11ea-8cd4-8c8ced5daf83.png)

You got to check first if context.params is not undefined before destructuring this value

**Comment by reaktivo** [comment] 2020-04-03 08:43
For anyone looking for a getStaticProps driven approach instead:

```
import { GetStaticProps, NextPageContext } from 'next';

export type Await<T> = T extends {
  then(onfulfilled?: (value: infer U) => unknown): unknown;
} ? U : T;

export type ExtractProps<T> = T extends { props: infer P } ? P : never;

export type StaticPageProps<T> = T extends GetStaticProps
  ? ExtractProps<Await<ReturnType<T>>>
  : never;

export type GetStaticPropsContext = Parameters<GetStaticProps>[0];
```

Then you can have your component read `getStaticProps` result:

```
export default function ProductDetailPage(props: StaticPageProps<typeof getStaticProps>) {
  return <>
    // the return type of getPost get's passed
    <h1>{props.post.title}</h1>
   </>;
};

export async function getStaticProps(ctx: GetStaticPropsContext) {
  return {
    post: getPost(ctx)
  }
}
```

**Comment by rubenzup** [comment] 2020-08-12 06:16
Ok but how to solve it? none of @reaktivo  and  @elias551  worked for me.

**Comment by deadcoder0904** [comment] 2020-08-24 15:36
I can't figure it out as well. I've opened up a discussion → https://github.com/vercel/next.js/discussions/16522

**Comment by Pravasith** [comment] 2020-11-24 11:07
> > What about types in context params?
> > in `[id].ts`
> > ```
> > export const getServerSideProps: GetServerSideProps = async (context) => {
> >     const { id } = context.params;
> > }
> > ```
> > 
> > 
> > I get this error
> > ```
> > Property 'id' does not exist on type 'ParsedUrlQuery | undefined'.
> >     27 | 
> >     28 | export const getServerSideProps: GetServerSideProps = async (context) => {
> >   > 29 |     const { id } = context.params;
> > ```
> > 
> > 
> > In VSCODE
> > ![Screenshot_20200325_195818](https://user-images.githubusercontent.com/34790378/77547354-194f3e80-6ed3-11ea-8cd4-8c8ced5daf83.png)
> 
> You got to check first if context.params is not undefined before destructuring this value

` if(params){
        const { slug } = params
    }`

**Comment by jareks** [comment] 2021-03-30 11:53
> You got to check first if context.params is not undefined before destructuring this valu

Under what circumstances `context.params` can be undefined  in getServerSideProps?

**Comment by balazsorban44** [comment] 2022-01-28 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
