### ISSUE TITLE
in example /with-redux-saga/ ，saga can't get action's result on server 

### ISSUE THREAD

**Issue by Mantak** [zeit/next.js#2739] opened 2017-08-09 12:37 UTC
the question is :
sagaA -> put({type: 'startSagaB'}) -> sagaB
when render on server:
if sagaA put an action to start sagaB, the sagaB can't fetch the action

**Comment by timneutkens** [comment] 2017-08-09 15:22
I'm going to close this because it doesn't provide a way to reproduce.

**Closed by timneutkens** 2017-08-09 15:22 UTC

**Comment by zalabinc** [comment] 2017-12-19 02:45
2 steps to attention
1. Saga must running 'on' initial render in server
actually in getInitialProps or you can create HOC 

2. You have to wait until saga task is 'done'
await sagaRun(saga).done 
see https://github.com/zalabinc/nextjs-boilerpate
