### ISSUE TITLE
Add apiDir config option

### ISSUE THREAD

**Issue by cj** [zeit/next.js#8162] opened 2019-07-29 16:41 UTC
It would be great to be able to specify the API dir location, please refer to https://spectrum.chat/next-js/general/next-9-is-there-a-config-option-to-change-where-the-api-dir-is-located~81da11ce-cd38-4fb5-bcda-9e95ee07db14

**Comment by ijjk** [comment] 2019-07-29 16:48
duplicate of #8123

**Closed by ijjk** 2019-07-29 16:48 UTC

**Comment by cj** [comment] 2019-07-29 16:51
@ijjk This is not a duplicate, this is not about changing the API route, it's about changing the API dir location.  Please refer to https://spectrum.chat/next-js/general/next-9-is-there-a-config-option-to-change-where-the-api-dir-is-located~81da11ce-cd38-4fb5-bcda-9e95ee07db14

> @ijjk
>  It's more for organisation and separation of concerns. We consider pages just that, pages, each one relates to a page you can visit, where as the API is the API an endpoint we consume. Because we are also connecting to a graphql backend to consume our data (which allows you to request everything in a single request) and since the release of serverless pre-rendering we are creating an endpoint for each of our pages to consume, i.e. api/pages/index etc... so right now that looks like /pages/api/pages/index, which gets confusing.

**Comment by cj** [comment] 2019-07-29 16:53
i.e. so instead of the dir location being `/pages/api` you could make it just `/api`, the route would not change.

**Comment by cj** [comment] 2019-07-29 16:57
I hope this makes sense 😄 

Ideally it would be great to have both options, `apiDir` and `apiRoutePath` to allow for maximum flexibility.

**Comment by ijjk** [comment] 2019-07-29 17:02
I see, can you open a new feature request issue following the [issue template](https://github.com/zeit/next.js/issues/new?template=2.Feature_request.md)

**Comment by cj** [comment] 2019-07-29 17:11
@ijjk done, sorry about the confusion! https://github.com/zeit/next.js/issues/8165

**Comment by balazsorban44** [comment] 2022-01-31 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
