### ISSUE TITLE
Use HTML Streaming?

### ISSUE THREAD

**Issue by jlei523** [zeit/next.js#3342] opened 2017-11-27 03:46 UTC
On a page with many dynamic components, it can be slow to render the page. If we can stream components down when it's ready asynchronously, we can improve the initial byte speed.

See example:
https://github.com/aickin/react-dom-stream

**Comment by andregoncalvesdev** [comment] 2017-11-27 12:20
it´s available on react16: https://reactjs.org/docs/react-dom-server.html#rendertonodestream

**Comment by timneutkens** [comment] 2017-11-28 13:34
It's something we have to talk about more internally cause a lot of features won't work the way you expect them to when stream rendering (next/head etc) 👍

**Comment by sourcesoft** [comment] 2018-01-29 22:11
The new `styled-components` version 3.1.2 has performance upgrades using the server side streaming in React 16
See https://medium.com/styled-components/v3-1-0-such-perf-wow-many-streams-c45c434dbd03

Would be awesome to use it in Next.js

**Comment by mohammedzamakhan** [comment] 2018-03-09 11:09
Any updates?

**Comment by centinel3** [comment] 2018-03-13 13:44
+1

**Comment by realalexhomer** [comment] 2018-03-13 14:11
This is a big deal for us as we are using styled-components, and mount time is quite long when you have lots of components on the page. We are using something like this but it is far from ideal:

https://gist.github.com/derek-duncan/a71a8c3f6bade9a4a5c988acb13d7c06

**Comment by renet** [comment] 2018-04-25 18:46
+1

Any news on this, @timneutkens? :)

**Comment by scf4** [comment] 2018-07-19 17:01
Would like to see this! @timneutkens

**Comment by Lomkex1** [comment] 2018-10-22 21:21
Any news?

**Comment by yanindeed** [comment] 2018-12-12 01:35
any news on this request?

**Comment by timneutkens** [comment] 2018-12-31 13:41
Closing this as duplicate of #1209

**Closed by timneutkens** 2018-12-31 13:41 UTC
Labels: Type: Enhancement, Type: Exploration
