### ISSUE TITLE
[Next 9] Web worker broken

### ISSUE THREAD

**Issue by steida** [zeit/next.js#7953] opened 2019-07-14 11:50 UTC
After several hours, still no success. Next 8 was ok. I created this issue to track investigations.

```
@app/web
 | > Using external babel configuration
 | > Location: "/Users/steida/dev/nberg/packages/web/babel.config.js"
 | [ info ]  bundled successfully, waiting for typecheck results ...
 | [ wait ]  compiling ...
 | [ info ]  bundled successfully, waiting for typecheck results ...
 | [ ready ] compiled successfully - ready on http://localhost:3000
 | [ event ] build page: /
 | [ wait ]  compiling ...
 | [ info ]  bundled successfully, waiting for typecheck results ...
 | [ ready ] compiled successfully - ready on http://localhost:3000
 | { Error: Cannot find module '/Users/steida/dev/nberg/packages/web/.next/server/static/development/pages/_document'
 |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
 |     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
 |     at Module.require (internal/modules/cjs/loader.js:637:17)
 |     at require (internal/modules/cjs/helpers.js:22:18)
 |     at Object.loadComponents (/Users/steida/dev/nberg/node_modules/next-server/dist/server/load-components.js:17:25)
 |     at DevServer.findPageComponents (/Users/steida/dev/nberg/node_modules/next-server/dist/server/next-server.js:298:40)
 |     at DevServer.renderToHTML (/Users/steida/dev/nberg/node_modules/next-server/dist/server/next-server.js:313:21)
 |     at DevServer.renderToHTML (/Users/steida/dev/nberg/node_modules/next/dist/server/next-dev-server.js:16:198)
 |     at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
 | [ event ] build page: /next/dist/pages/_error
 | [ wait ]  compiling ...
 | [ ready ] compiled successfully - ready on http://localhost:3000
 | [ error ] { Error: Cannot find module '/Users/steida/dev/nberg/packages/web/.next/server/static/development/pages/_document'
 |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
 |     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
 |     at Module.require (internal/modules/cjs/loader.js:637:17)
 |     at require (internal/modules/cjs/helpers.js:22:18)
 |     at Object.loadComponents (/Users/steida/dev/nberg/node_modules/next-server/dist/server/load-components.js:17:25)
 |     at DevServer.findPageComponents (/Users/steida/dev/nberg/node_modules/next-server/dist/server/next-server.js:298:40)
 |     at DevServer.renderErrorToHTML (/Users/steida/dev/nberg/node_modules/next-server/dist/server/next-server.js:362:35)
 |     at DevServer.renderErrorToHTML (/Users/steida/dev/nberg/node_modules/next/dist/server/next-dev-server.js:16:706)
 |     at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
 | { Error: Cannot find module '/Users/steida/dev/nberg/packages/web/.next/server/static/development/pages/_document'
 |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
 |     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
 |     at Module.require (internal/modules/cjs/loader.js:637:17)
 |     at require (internal/modules/cjs/helpers.js:22:18)
 |     at Object.loadComponents (/Users/steida/dev/nberg/node_modules/next-server/dist/server/load-components.js:17:25)
 |     at DevServer.findPageComponents (/Users/steida/dev/nberg/node_modules/next-server/dist/server/next-server.js:298:40)
 |     at DevServer.renderErrorToHTML (/Users/steida/dev/nberg/node_modules/next-server/dist/server/next-server.js:362:35)
 |     at DevServer.renderErrorToHTML (/Users/steida/dev/nberg/node_modules/next/dist/server/next-dev-server.js:16:839)
 |     at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
```

**Comment by steida** [comment] 2019-07-14 11:51
The empty project works, so it must be some dependency. But I have zillions dependencies in the project.

**Comment by steida** [comment] 2019-07-14 12:24
Isn't possible somehow enable webpack debug log or something similar?

**Comment by huv1k** [comment] 2019-07-14 12:32
Hey @steida, could you provide minimal reproduction?

**Comment by steida** [comment] 2019-07-14 12:34
@huv1k I would love, but as I wrote, I had x dependencies plus it is yarn workspace with several packages with TypeScript and Relay and... I have to rebuild the app from scratch, damn 😤.

**Comment by steida** [comment] 2019-07-14 13:51
Omg, I found it. @zeit/next-workers did not work with Next 8 for me, so I had to "fix" it - https://github.com/zeit/next-plugins/pull/461.

This fix breaks Next 9.

**Comment by steida** [comment] 2019-07-14 14:19
OMG, web worker does not work, I will have to configure Webpack like an animal.

**Comment by steida** [comment] 2019-07-14 18:14
I think it's the same issue as https://github.com/zeit/next.js/issues/7873

**Comment by justsee** [comment] 2019-07-16 00:40
You can confirm if it is the same as #7873 by modifying https://github.com/zeit/next.js/commit/c0e07ca2d314ea865f324cc658a9927cdf7cae80 to set window back to undefined in your own node_modules version.

If it is the issue then if you want you can temporarily use a patched 9.0.0 version in your project:

1. fork the next.js repo
1. check out v9.0.0
1. modify the webpack config file to set window to undefined
1. `npm pack` next within packages/next
1. copy that to your dependent project and reference it in package.json using a file reference

and it should resolve that issue for now.

**Comment by timneutkens** [comment] 2019-07-17 14:25
Closing this as duplicate of #7723

**Closed by timneutkens** 2019-07-17 14:25 UTC

**Comment by tky5622** [comment] 2020-01-23 06:32
This issue still seems to exist in next v9.2.

**Comment by elwiski** [comment] 2020-02-18 07:17
Still on "next": "^9.2.1"

**Comment by balazsorban44** [comment] 2022-01-30 13:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
