### ISSUE TITLE
[@next/bundle-analyzer] when enable, it keep open new link in chrome

### ISSUE THREAD

**Issue by bluelovers** [zeit/next.js#10265] opened 2020-01-25 11:45 UTC
# Bug report

## Describe the bug

when enable, it keep open new link in chrome

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. enable @next/bundle-analyzer
2. next dev
3. first will open 2 local file link in chrome 
  .next/analyze/server.html
  .next/analyze/client.html
4. idle a few min
5. it open server.html and client.html again
6. keep loop it from step.4

## Expected behavior

only open once after server start

## Screenshots

![image](https://user-images.githubusercontent.com/167966/73120566-ed830b80-3faa-11ea-9377-87f1d540bae4.png)

## System information

- OS: Windows
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2]

**Comment by timneutkens** [comment] 2020-01-25 16:08
This is expected behavior when your enable bundle analyzer. It’s meant to debug production builds, development output will be incorrect.

**Closed by timneutkens** 2020-01-25 16:08 UTC

**Comment by balazsorban44** [comment] 2022-01-30 15:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
