### ISSUE TITLE
Typescript doesn't work out of the box

### ISSUE THREAD

**Issue by 0xNOP** [zeit/next.js#8501] opened 2019-08-23 21:48 UTC
# Bug report

I wanted to create a new next app using `npx create-next-app` with typescript. I followed all the steps and renamed .js files to .tsx and ran `yarn dev`. According to this blogpost: https://nextjs.org/blog/next-9#built-in-zero-config-typescript-support it should detect that the project is using typescript and add what's necessary but it didn't.

## Screenshots

![image](https://user-images.githubusercontent.com/3116731/63625572-56cbb080-c600-11e9-9b16-04cc84388853.png)

![image](https://user-images.githubusercontent.com/3116731/63625700-ac07c200-c600-11e9-9d94-353f506bf6ff.png)

## System information

- OS: Windows
- Version of Next.js: 9.0.4

**Comment by Timer** [comment] 2019-08-23 23:04
Duplicate of https://github.com/zeit/next.js/issues/8470

**Closed by Timer** 2019-08-23 23:04 UTC

**Comment by balazsorban44** [comment] 2022-01-31 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
