### ISSUE TITLE
Link doesn't work sometimes

### ISSUE THREAD

**Issue by tylermcrobert** [zeit/next.js#9438] opened 2019-11-17 03:47 UTC
# Bug report

## Describe the bug

Sometimes in both development and production I have a problem where <Link /> simply does not work.

## To Reproduce

1. Navigate to certain pages
2. Click link
3. Observe issue

## Expected behavior

Link should navigate me to linked page.

## Screenshots

I can provide screen recording if it is helpful

## System information

- OS: MacOs, phoneOS
- Browser Chrome, Safari
- Version of Next.js: 9

## Additional context

Only happens on certain key pages.

**Comment by tylermcrobert** [comment] 2019-11-17 04:54
Looks like it may be a duplicate of #282. Will do some digging around my project confirm and close if it is

**Comment by timneutkens** [comment] 2019-11-17 05:47
I'm pretty sure it's a duplicate of that issue if you're using next-css/less/sass, please close this issue if you are using one of those so that we can keep tracking it there.

**Closed** 2019-11-17 16:10 UTC

**Comment by balazsorban44** [comment] 2022-01-30 22:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
