### ISSUE TITLE
Lazy Loading Modules section is not working

### ISSUE THREAD

**Issue by JoaoPauloLousada** [zeit/next.js#9014] opened 2019-10-09 18:17 UTC
# Lazy Loading Modules section is not working

## Describe the bug
If you go to the section learn/excel/lazy-loading-modules
on the docs, it's not able to proceed to the next pages on the tujtorial.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'https://nextjs.org/learn/excel/lazy-loading-modules'
2. Click on 'Start Now'
3. Click on 'Next'

## Expected behavior
Go to the next page.

**Comment by ijjk** [comment] 2019-10-09 18:45
Hi, this lesson appears to be working correctly and the issue is not able to be reproduced. I'm going to close this issue, if you are still encountering problems with this please reply with additional details so we can investigate further

**Closed by ijjk** 2019-10-09 18:45 UTC
Labels: Can't Reproduce

**Comment by JoaoPauloLousada** [comment] 2019-10-10 13:16
> Hi, this lesson appears to be working correctly and the issue is not able to be reproduced. I'm going to close this, if you are still encountering problems with this please reply with additional details so we can investigate further

After click on the button "Next", it never goes to the next page. Please confirm if you can't reproduce it. 

![next-error](https://user-images.githubusercontent.com/32400930/66572137-ce20b980-eb46-11e9-9fb8-ef16681f0780.png)

**Comment by ijjk** [comment] 2019-10-10 18:42
@lfades and I aren't able to reproduce this, clicking the next button works as expected for us. 

You might have a bad cache somehow, if you visit the site in incognito mode does it still not navigate on next? What browser/operating system are you using?

**Comment by JoaoPauloLousada** [comment] 2019-10-10 20:29
Ok, I got it. Apparently I'm not able to go to the next page on Brave Browser (which is my default web browser). When I tried it on Chrome, it worked well.
Thank you

**Comment by balazsorban44** [comment] 2022-01-31 02:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
