### ISSUE TITLE
"Did not expect server HTML to contain [..]" during dynamic import

### ISSUE THREAD

**Issue by oMatej** [zeit/next.js#6904] opened 2019-04-05 08:47 UTC
# Bug report

## Describe the bug

Dynamic import of components with "re-export" by `index.js` file leads to following warnings:
`Warning: Did not expect server HTML to contain a <h2> in <div>.`

## To Reproduce

1. Create a file which will export many dynamically imported components, i.e.:
- Import one component directly.
- Import other component through `index.js` with `export { default } from './World'`
```
export const Hello = dynamic(import('./Hello/Hello'));
export const World = dynamic(import('./World'));
```
2. Use both components on page.
3. Run application in `development` mode with `yarn dev` / `npm run dev`.
4. In the browser console there will be mentioned warning.

Here is example repository: https://github.com/oMatej/next-dynamic-import-issue

## Expected behavior
Both types of imports should behave the same.

## System information
 - OS: Ubuntu 18.04.1 LTS
 - Version of Next.js: 8.0.4

**Comment by einarlove** [comment] 2019-05-13 12:30
Having the same issue. Hard to pinpoint the problem but it looks like it fails when trying to import something outside its bundle. ¯\_(ツ)_/¯

**Comment by adam187** [comment] 2019-06-06 07:56
Same issue on Next.js: 8.1.1

**Comment by timneutkens** [comment] 2019-06-06 10:30
Note that it's a bad idea to supress hydration warnings. It will hide problems in your application.

**Comment by cesarvarela** [comment] 2019-06-19 19:53
I'm having the same issue, is this something new to next 8?

**Comment by cesarvarela** [comment] 2019-06-19 20:07
Just tried downgrading my project to next 7, and it fixes the issue.

This is happening to me in dev mode, in production seems to be working fine on both 7 and 8.

**Comment by timneutkens** [comment] 2019-06-22 17:37
Can you try `next@canary`?

**Comment by jacobrask** [comment] 2019-06-22 18:49
I have done that previously, is something recently released?

**Comment by timneutkens** [comment] 2019-06-22 19:02
Yep I think @Timer landed a patch for next/dynamic, not entirely sure if it's directly related, but doesn't hurt to try.

**Comment by Timer** [comment] 2019-06-24 18:25
I confirmed this was fixed by my PR, upgrading to the latest canary will fix this.

**Closed by Timer** 2019-06-24 18:25 UTC
Labels: Type: Needs Investigation
