### ISSUE TITLE
Production Application is really slow over time

### ISSUE THREAD

**Issue by Nelrohd** [zeit/next.js#12625] opened 2020-05-08 04:26 UTC
# Bug report
Application in production mode gets very very slow after few days.

## Describe the bug
I'm using NextJS as the front-end of my back-end and I have an API behind. When I start the app, everything is really fast and smooth but after few days it gets slower and slower until it takes over half a minute to load a page. The API here isn't the problem since I checked my API and everything is returned under 10ms. So I decided to check what was really slow and it was the **static CSS/JS** (`_next/static/css/styles.f8b5845e.chunk.css` for example).

## To Reproduce
I have no idea how to reproduce and since I'm using pm2 to manage my NodeJS process, I tried to look at `pm2 monit` to see anything but everything is normal, CPU and memory are really low and lot of free space on hard disk (even `htop` shows me the same).

## Expected behavior
I would expect the application to run fast and smooth indefinitely.

## Screenshots
None

## System information

- OS: Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-1058-aws x86_64)
- Browser (if applies) Tested under Chrome
- Version of Next.js: 9.1.4
- Version of Node.js: 12.4.1

## Additional context
When I restart my web application with `pm2 restart web`, everything gets super fast as expected, that's my only fix for now...

note: My NextJS application is based on the expressJS custom server example.

**Comment by Timer** [comment] 2020-05-08 04:45
This was fixed in the `9.3.6` release. Please upgrade.

**Closed by Timer** 2020-05-08 04:45 UTC

**Comment by balazsorban44** [comment] 2022-01-30 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
