### ISSUE TITLE
Development server (npm run dev) stops after a bit

### ISSUE THREAD

**Issue by Gino** [zeit/next.js#10384] opened 2020-02-02 20:25 UTC
Hello,

I am not sure if this issue is related to the fact that I am using Next.js but it is a really annoying issue and it might be. I am working on a Macbook Pro with the latest MacOS installed, also using the latest Next.js version with Typescript support and using SASS with TailwindCSS.

When I start up my development server using `npm run dev` or `yarn dev`, it works fine for a couple of minutes. After those minutes, the `localhost:3000` page is not reachable anymore and keeps loading. My terminal does not give any errors or special messages either. I have no clue why this is happening. I tried to reproduce this issue on a Windows machine and it seems to work fine there. It might be an issue that only occurs on my Macbook but I am wondering if someone knows how to resolve this or if someone has a similar issue.

After a couple minutes, the page just becomes unreachable. Everything still compiles after I save a file, the terminal even returns all the messages that it compiled successfully.

I hope someone is able to help me with this issue.

**next.config.js:**
```js
const withSass = require('@zeit/next-sass');

module.exports = withSass();
```

**package.json:**

```json
{
  "name": "project",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@zeit/next-css": "^1.0.1",
    "@zeit/next-sass": "^1.0.1",
    "next": "9.2.1",
    "node-sass": "^4.13.1",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "redux": "^4.0.5",
  },
  "devDependencies": {
    "@types/node": "^13.5.3",
    "@types/react": "^16.9.19",
    "autoprefixer": "^9.7.4",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-config-standard": "^14.1.0",
    "eslint-plugin-import": "^2.20.0",
    "eslint-plugin-node": "^11.0.0",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-react": "^7.18.0",
    "eslint-plugin-standard": "^4.0.1",
    "postcss-loader": "^3.0.0",
    "prettier": "^1.19.1",
    "tailwindcss": "^1.1.4",
    "typescript": "^3.7.5"
  }
}
```

Thanks.

**Comment by timneutkens** [comment] 2020-03-16 10:46
Please try built-in sass support: https://nextjs.org/blog/next-9-3#built-in-sass-support-for-global-stylesheets

This issue does not follow the issue template, which asks for a clear and concise reproduction of the issue. So I'm going to close this issue.

**Closed by timneutkens** 2020-03-16 10:46 UTC

**Comment by balazsorban44** [comment] 2022-01-30 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
