### ISSUE TITLE
High Memory usage on Next.js 9.0.5

### ISSUE THREAD

**Issue by gigantz** [zeit/next.js#8608] opened 2019-09-03 11:32 UTC
# Bug report

We are using heroku and have memory usage limit (512 mb)
So it's important to not have memory problem with nextjs.
After upgrade from 9.0.3 to 9.0.5 we got memory usage x2 higher.

Now to next build we need 900mb+. On 9.0.3 it was 300-400mb
PS. I know it's mostly heroku problem, but it's weird that next 9.0.5 memory usage got that higher

- Browser (if applies) Ubuntu
- Version of Next.js: 9.0.5

**Comment by ematipico** [comment] 2019-09-05 09:19
Related to this: https://github.com/zeit/next.js/issues/7929

**Comment by johannwagner** [comment] 2019-09-10 11:14
We ran into the same issue with GitLab and Kubernetes runner, but with the limit of 2G per build container, so our build container gets killed by the kernel, because we exceeded cgroups limits.

**Comment by timneutkens** [comment] 2020-01-02 22:24
Closing as this issue is impossible to investigate as you can imagine. The issue template was removed except for the title and no reproduction was provided.

Leaving #7929 open.

**Closed by timneutkens** 2020-01-02 22:24 UTC

**Comment by balazsorban44** [comment] 2022-01-30 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
