### ISSUE TITLE
Possibility to configure WebSocket ping port

### ISSUE THREAD

**Issue by ussuritiger** [zeit/next.js#6271] opened 2019-02-12 13:26 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
My development setup consists of multiple Docker containers:
1) Next.js application running in development mode
2) Mock API
3) Proxy that is used in front of Next.js application and mock API containers so one host is used for accessing both the application and API.

Next.js 8.0 has introduced WebSockets based ping approach. This in turn uses randomly assigned port for WebSocket connection and makes it impossible for me to specify which port to open in proxy container to proxy to the application container. This results in refresh of the page every 5 seconds after WebSocket connection fails.

## Describe the solution you'd like
Possibility to configure WebSocket ping port will solve this issue since that specific port can be opened and proxied in the proxy container.

## Describe alternatives you've considered
Solution described above is desired and probably absolutely doable. As an alternative I would consider possibility to specify ping approach: either `fetch` based or WebSocket based.

**Comment by Timer** [comment] 2019-02-12 14:53
Duplicate of https://github.com/zeit/next.js/issues/6248.

**Closed by Timer** 2019-02-12 14:53 UTC
