### ISSUE TITLE
[Next 9.0.0] Router types for url objects

### ISSUE THREAD

**Issue by steida** [zeit/next.js#7802] opened 2019-07-08 21:30 UTC
Router in Next 8 supports url objects `{ pathname: ... }` but types support only string. It's bug or that feature was removed?

**Comment by Timer** [comment] 2019-07-08 21:37
Duplicate of https://github.com/zeit/next.js/issues/7764. Thanks for reporting!

**Closed by Timer** 2019-07-08 21:37 UTC
Labels: Type: Bug, Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
