### ISSUE TITLE
Query params broken in production?

### ISSUE THREAD

**Issue by joyguy55** [zeit/next.js#5292] opened 2018-09-25 23:35 UTC
# Bug report

## Describe the bug

In production this.props.router.query is always empty. Even though the URL indicates a param such as this one ?index=1

I deployed using zeits Now. Everything seems to work fine except for my pages that take dynamic indices. 

## Screenshots

IN PROD w/ NOW
<img width="1370" alt="screen shot 2018-09-25 at 4 28 31 pm" src="https://user-images.githubusercontent.com/14304220/46048931-b19f1400-c0e0-11e8-9eda-e56d6a043a39.png">

LOCALHOST
<img width="1363" alt="screen shot 2018-09-25 at 4 35 48 pm" src="https://user-images.githubusercontent.com/14304220/46049020-1ce8e600-c0e1-11e8-9fa3-e5ea587b9816.png">

CODE
<img width="627" alt="screen shot 2018-09-25 at 4 31 55 pm" src="https://user-images.githubusercontent.com/14304220/46048962-d0050f80-c0e0-11e8-92e5-f916da84b75b.png">

## System information
 - OS: macOS
 - Browser chrome
 - Version of Next.js: 6.1.1

**Comment by timneutkens** [comment] 2018-09-25 23:43
Are you using `next export`?

**Comment by FranciscoMSM** [comment] 2018-12-12 08:39
@timneutkens I'm facing the same issue. Have you close it because there's a current workaround? I'm using v7.0.2

**Comment by timneutkens** [comment] 2018-12-12 10:01
Closed because of no activity and no reproduction. There's 290 open issues so if they become stale we close them to clean up.

**Closed by timneutkens** 2018-12-12 10:01 UTC

**Comment by sunil-jhamnani** [comment] 2019-04-26 06:31
> Are you using `next export`?

Is this issue because of this?
If yes can you suggest any solution to this and why this happens
