### ISSUE TITLE
Separate examples to own repository

### ISSUE THREAD

**Issue by radeno** [zeit/next.js#2836] opened 2017-08-23 12:40 UTC
I think next.js grown up into level when examples could live by own life in separate repository (eg. zeit/next.js-examples). Examples are more about wide community than core development and doesn't require so much quality as core do.
Many pull request are about updating examples or about adding new examples.
Separation could improve dynamism of both projects.

**Comment by timneutkens** [comment] 2017-08-23 19:52
Duplicate of #2681, we're currently not planning to move them out. We've talked about it extensively though 👌 

> Examples are more about wide community than core development and doesn't require so much quality as core do.

I'd like to argue that all code has to be quality cause *many* people will use it.

**Closed** 2017-08-23 19:52 UTC
