### ISSUE TITLE
getInitialProps not working on reload (build)

### ISSUE THREAD

**Issue by kpauletti** [zeit/next.js#7161] opened 2019-04-25 19:09 UTC
# Bug report

## Describe the bug

The getInitalProps function does not seem to be running on page reload. 
I'm trying to pull the id from this path `/approaches/view?id=319`, it works when I navigate using links, but once I refresh the page the `asPath` property is now the path without the query, and the query itself is gone. Any ideas? 

```
const ApproachView = props => <TagView {...props} type="approach" plural="approaches" />;

// ApproachView.getInitialProps = async ({ query: { id }, asPath }) => ({ id, asPath });

ApproachView.getInitialProps = async ctx => {
    console.log('get initial props ran!!');

    return { id: ctx.query.id };
};

export default ApproachView;
```

## To Reproduce

Just reloading the page 

## Expected behavior

Query and path props should persist on reload

## System information
 - OS: Linux
 - Browser: Chrome
 - Version of Next.js: 8.0.3

**Comment by timneutkens** [comment] 2019-04-25 19:57
Please provide a reproduction repository. It's probably something in your code but it's hard to say based on the description.

**Comment by Timer** [comment] 2019-04-29 13:27
Hi @kpauletti! We're closing this because it has been a few days without a reproduction.

We hope you figured it out! If you still need help, feel free to post letting us know.

Thanks!

**Closed by Timer** 2019-04-29 13:27 UTC

**Comment by kpauletti** [comment] 2019-04-29 17:27
Hey @Timer , I actually could not figure out the issue, and I was denied posting a reproduction repo since this is company related work. I ended up just duct-taping it for now, checking for query params on reload in my `componentDidMount`. If I do end up running into this in future projects I'll be sure to go ahead and try to replicate on a public repo. Thanks! 
```
	async componentDidMount() {
		if (!this.props.id || !this.props.tag) {
			const { search } = window.location;
			const { id } = queryString.parse(search);
			const idAsNum = Number(id);
			await this.setState({ id: idAsNum });
			this.fetchTag();
		}
}
```

**Comment by Timer** [comment] 2019-04-29 17:39
@kpauletti sounds good!

**Comment by mudin** [comment] 2020-03-20 14:20
I also have the same issue, if I deploy my site statically using `export`, `getInitialProps` is not calling in page reload

**Comment by timneutkens** [comment] 2020-03-21 16:17
> I also have the same issue, if I deploy my site statically using `export`, `getInitialProps` is not calling in page reload

Sounds expected, after all you did statically export the app and it was generated at build time.

**Comment by balazsorban44** [comment] 2022-01-30 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
