### ISSUE TITLE
Built-In Sass Support

### ISSUE THREAD

**Issue by alejalapeno** [zeit/next.js#10134] opened 2020-01-17 06:59 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

With #8626 it was commented that the various non-css-in-js styling plugins would be deprecated in favor of built-in support. This did not happen, and my tests with the new built-in CSS support and `@zeit/next-sass` even showed Sass to outright fail in cases.

## Describe the solution you'd like

Installation of `node-sass` should enable built-in Sass support, both global and CSS Modules per the original [RFC suggestion](https://github.com/zeit/next.js/issues/8626#issuecomment-528125487).

I've created PR #10133 (as a start) which modified the [CSS webpack config](https://github.com/zeit/next.js/blob/canary/packages/next/build/webpack/config/blocks/css/index.ts) to enable `.scss`, `.sass`, `.module.scss`, and `.modules.sass`. It adds `sass-loader` as the only additional dependency.

## Describe alternatives you've considered

I've considered rewriting `@zeit/next-sass` to cooperate with the current built-in CSS and CSS Module config. This would come with the benefit of not requiring `sass-loader` as another core dependency, but would require a complex setup to gain the same level of benefits, further user config, prolonged maintenance of the plugin, etc.

## Additional context

- Tests focusing on Sass need to be written, but many of the tests for output CSS should work for Sass tests.
- Documentation will need to be updated to remove `@zeit/next-sass` references and include instructions for installing `node-sass` to enable.
- Some additional refactoring may be able to DRY up repetition, but I also didn't want to make individual configurations more difficult by abstracting too much. Because of this some comments from the original implementation are a bit redundant in the sass-loader.
- Error messages skew towards "CSS" verbiage. There could be custom Sass messages, but I think this increases the footprint unnecessarily and Sass becomes CSS so I feel the messages work.

Let me know if this is the correct path forward and if you'd like me to continue contributing towards this feature.

**Comment by Timer** [comment] 2020-01-23 13:27
This feature has been experimentally landed.

**Comment by alejalapeno** [comment] 2020-01-23 16:04
Enabled with an experimental flag in your `next.config.js`
```
module.exports = {
  experimental: { scss: true }
}
```

**Comment by StarpTech** [comment] 2020-01-28 19:16
How should we evaluate if we can't set any sass loader options like `includePaths` ?

**Comment by csirkeee** [comment] 2020-01-31 10:33
Doesn't seem to work together with TypeScript like the built in CSS support does. Reproduction in this repo:
https://github.com/csirkeee/with-scss-typescript

Second to last commit there is the same but with CSS modules, and it seems like TS parsing is set up for that successfully, but if I switch to SCSS it fails to build.

**Comment by StarpTech** [comment] 2020-01-31 11:33
I would open a separate issue @csirkeee

**Comment by alejalapeno** [comment] 2020-01-31 17:37
@csirkeee #10363 addresses this, but I believe is on hold until this release is no longer experimental.

If you want to experiment in the meantime you can create a `scss.d.ts` file in your root with:
```
declare module '*.scss' {
  const content: {[className: string]: string};
  export default content;
}
```
Or add that to your `next-env.d.ts`

**Comment by timneutkens** [comment] 2020-02-01 14:44
@timer Tbh I think it's fine to ship it either way, it's just to bypass TypeScript checking and would still fail on webpack not being able to bundle 👍

**Comment by OscarBarrett** [comment] 2020-02-06 12:56
> How can we set any sass loader options like `includePaths` ?

There is a feature request here https://github.com/zeit/next.js/issues/10339

**Comment by jeremyk** [comment] 2020-02-12 00:10
I tried out the SCSS as a module but it didn't compile the SCSS to CSS so all the nested classes were broken. The outer class worked though.

Also, it is working well when used globally.

**Comment by alejalapeno** [comment] 2020-02-12 01:27
@jeremyk do you have a repo or reproducible example?

**Comment by timneutkens** [comment] 2020-03-11 11:25
Landed in 9.3! https://nextjs.org/blog/next-9-3

**Closed by timneutkens** 2020-03-11 11:25 UTC

**Comment by thadwoodman** [comment] 2020-05-06 15:12
> I tried out the SCSS as a module but it didn't compile the SCSS to CSS so all the nested classes were broken. The outer class worked though.
> 
> Also, it is working well when used globally.

@jeremyk I'm seeing this same issue. Did you ever figure this one out? Not sure if I'm missing something in the docs here.

**Comment by jeremyk** [comment] 2020-05-06 17:02
I was actually using it incorrectly - I thought one only referenced the "outer" or top level classes via the import (as that would give global uniqueness) but you have to reference all the inner ones as well. If you want to opt out of that behavior you can put `:global {}` around a class or block of scss and it will opt out of that (making it work how I thought it would originally). And using `:local {}` inside a global block will revert back to the default behavior. Hope that helps.

**Comment by thadwoodman** [comment] 2020-05-06 17:08
@jeremyk thanks this solved the issue for me! I think this would be really helpful to have in the docs.

**Comment by balazsorban44** [comment] 2022-01-27 14:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
