### ISSUE TITLE
Next.js Removing Error Page After Compiling

### ISSUE THREAD

**Issue by danteissaias** [zeit/next.js#9876] opened 2019-12-30 00:12 UTC
# Bug report

## Describe the bug
Next.js is removing the default error page.
```
[ event ] build page: /next/dist/pages/_error
[ wait ]  compiling ...
[ event ] page was removed /next/dist/pages/_error
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone https://github.com/notepad/notepad
2. Remove `packages/ui/pages/_error.tsx`
3. Install dependencies in each package
4. Run `yarn dev` (note: you have to use yarn2)
5. Trigger a 404

## Expected behavior

Next.js Triggers the Error Page.

## Screenshots

Check logs above.

## System information

- OS: macOS
- Browser: Firefox
- Version of Next.js: ^9.1.5

## Additional context

- Using Yarn v2 with Pnp and Workspaces
- Using TypeScript
- Using Custom Babel Configuration with Styled Components and Decorators
- Using Custom Webpack Configuration with Aliases (alias `~` to apex)

**Comment by danteissaias** [comment] 2019-12-30 00:14
There is a workaround:
- Create a file at `pages/_error.tsx`
- Put the following in the file:
```typescript
export { default } from "next/error"
```

**Comment by ijjk** [comment] 2020-01-02 21:18
Hi, the removing and recompiling is due to `on-demand-entries` which is expected. What it does is evict less used pages per the config [here](https://github.com/zeit/next.js#configuring-the-ondemandentries) to reduce memory usage for large Next.js applications.

I'm going to close this as it isn't an issue and is the expected behavior

**Comment by timneutkens** [comment] 2020-01-02 21:20
The message itself can be made clearer.

**Closed** 2020-01-03 10:43 UTC

**Comment by balazsorban44** [comment] 2022-01-30 17:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
