### ISSUE TITLE
Contenthash of commons chunks differs on different machines

### ISSUE THREAD

**Issue by StarpTech** [zeit/next.js#9469] opened 2019-11-20 12:42 UTC
# Bug report

## Describe the bug

When I build the production branch locally and on the CI I end up with different css chunk names e.g `.next/static/chunks/commons.d4d0b807.chunk.css` with the exact same content. That's the reason why I think it might be related to https://github.com/webpack/webpack/issues/7179#issuecomment-547557053

Important to note is that all **none** `commons` chunks can be reproduced locally and on a remote machine.

## To Reproduce

No easy way to reproduce it. Perhaps someone has already the suspicion of the cause otherwise I will try to reproduce it on a sample project.

I use `@zeit/next-sass` and `@zeit/next-css`

## Expected behavior

The hash of the files should be the same because we didn't change them.

## System information

- OS: Linux
- Version of Next.js: 9.1.3

**Comment by Timer** [comment] 2019-11-20 18:17
I don't think there's anything we can do here, but we might be able to take a look in the future. Feel free to dig into this, but it's likely a webpack issue.

**Comment by StarpTech** [comment] 2019-11-20 19:12
@Timer any hint for a good start? When and where are common chunks generated?

**Comment by timneutkens** [comment] 2019-11-21 01:37
@Timer isn't this related to how module ids are not deterministic, if you delete `.next/records.json` (from the top of my mind, the name has records in it for sure) it would also change between builds on one machine too I believe.

**Comment by Timer** [comment] 2019-11-21 20:39
Partially, but line ending normalization is also at play here. Windows will inherently hash different than Linux `\r\n` / `\n`.

**Comment by StarpTech** [comment] 2019-11-21 20:50
@Timer Regarding line-ending we reproduced it on Linux systems only.

**Comment by Timer** [comment] 2019-11-21 21:02
@StarpTech yup, like @timneutkens pointed out webpack is bad at module hashing and requires a records file (which still doesn't fix the problem in all cases).

I believe this is fixed in webpack 5, so itls just a waiting game.

**Comment by StarpTech** [comment] 2019-11-21 22:32
@Timer That's interesting. When I use a fixed buildId the hashes are deterministic.

```js
 generateBuildId: async () => {
      // For example get the latest git commit hash here
      return 'my-build-id';
    }
```

and I think I know why :smile: the sentry example use the buildId in the source to construct a `release` version so on every new build the content is changed :smile:

**Comment by timneutkens** [comment] 2020-01-03 00:51
Interesting that that affected css though, but guess it's "solved" then.

**Closed by timneutkens** 2020-01-03 00:51 UTC
Labels: Is Upstream, Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-30 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
