### ISSUE TITLE
Export WithRouterProps from next/router

### ISSUE THREAD

**Issue by martpie** [zeit/next.js#9424] opened 2019-11-15 09:18 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Continuation of #7311

`WithRouterProps` (typings) is only available from `'next/dist/client/with-router'`

```
import { WithRouterProps } from 'next/dist/client/with-router';
```

## Describe the solution you'd like

`WithRouterProps` should be accessible from the same module as `withRouter`:

```
import { withRouter, WithRouterProps } from 'next/router';
```

## Describe alternatives you've considered

n/a

## Additional context

It is just for code cleanness, it does not prevent to write any type-safe code.

I can open a PR if Zeit does not have time to do that.

**Comment by timneutkens** [comment] 2019-11-15 17:37
This does not explain any reason why you'd do this, I still don't see a valid reason for having it exposed.

**Comment by martpie** [comment] 2019-11-15 21:41
Assuming we use a class component instead of a function component (happens a lot in older codebase), it is quite essential in order to build the correct props for a component:

```ts
import React from 'react';
import { withRouter } from 'next/router';
import { WithRouterProps } from 'next/dist/client/with-router';

type OwnProps = { /**/ };

type Props = WithRouterProps & OwnProps;

class SomeComponent extends React.Component<Props> {
  // ...

  render () {
    const { router } = props; 

    // ...
  }
}

export default withRouter(SomeComponent);
```

Unless I'm missing something?

**Comment by timneutkens** [comment] 2019-11-15 23:09
Hey @martpie feel free to open a PR, I'd like to check the bundle size difference.

**Comment by timneutkens** [comment] 2020-01-03 00:52
Closing as a PR wasn't opened.

**Closed by timneutkens** 2020-01-03 00:52 UTC
Labels: good first issue, help wanted

**Comment by isaachinman** [comment] 2020-04-14 17:45
@timneutkens I'd like to pick this up - are you still happy to proceed?

**Comment by balazsorban44** [comment] 2022-01-30 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
