### ISSUE TITLE
exporting dynamic routes with sass 

### ISSUE THREAD

**Issue by ercekal** [zeit/next.js#7403] opened 2019-05-22 11:34 UTC
I want to export 3 dynamic routes with sass support however when I run `yarn build` & `yarn export` I only receive one index page. I actually need one index.html page along with 3 folder snd their related index.html pages. Is there a proper way to merge exportPathMap and withSass ?

```const withSass = require('@zeit/next-sass');
const path = require('path');

module.exports = withSass({
  async exportPathMap() {
    // need to find a solution for this... it's a hacky way
    const list = ['slate-bullet', 'bullet_new_navy', 'olive-bullet'];
    const pages = list.reduce(
      (pages, item) =>
        Object.assign({}, pages, {
          [`/products/${item}`]: {
            page: '/products',
            query: { productHandle: item }
          }
        }),
      {}
    );
    return Object.assign({}, pages, {
      '/products': { page: '/products' }
    });
  }
});

module.exports = {
  webpack: (config, { defaultLoaders }) => {
    config.resolve.alias['styles'] = path.join(__dirname, 'styles')
    config.module.rules.push({
      test: /\.scss$/,
      use: [
        defaultLoaders.babel,
        {
          loader: require('styled-jsx/webpack').loader,
          options: {
            type: 'scoped'
          }
        },
        {
          loader: 'sass-loader',
          options: {
            sourceMap: true
          }
        },
        {
          loader: 'sass-resources-loader',
          options: {
            resources: [
              './styles/core/helpers/*.scss',
              './styles/core/type/*.scss',
              './styles/core/grid/_grid.scss'
            ]
          }
        }
      ]
    });

    return config;
  }
};
```

# Question about Next.js

GitHub Issues are reserved for Bug reports and Feature requests. The best place to get your question answered is to post it on https://spectrum.chat/next-js.

**Comment by ijjk** [comment] 2019-05-22 15:48
Closing in favor of the [spectrum thread](https://spectrum.chat/next-js/general/exporting-dynamic-routes-with-sass~32b7f998-f9bf-46da-bb92-a449b2ebfa65)

**Closed by ijjk** 2019-05-22 15:48 UTC

**Comment by balazsorban44** [comment] 2022-01-31 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
