### ISSUE TITLE
Container 'Build' exceeded memory limit.

### ISSUE THREAD

**Issue by kodermax** [zeit/next.js#8272] opened 2019-08-07 09:03 UTC
# Bug report

## Describe the bug

When I use Bitbucket Pipeline for building app, i get an error 
Container 'Build' exceeded memory limit.
But Nextjs 9.0.2 works correct.

## Screenshots
![image](https://user-images.githubusercontent.com/590985/62609865-2ea73680-b90b-11e9-97a3-e19e33f424c9.png)
## System information

 Next.js: [e.g. 6.0.2] 9.0.3

**Comment by timneutkens** [comment] 2019-08-07 09:39
Sorry but we won't be able to look into this issue as there is no actionable information provided like a reproduction, so I'm going to close it.

**Closed by timneutkens** 2019-08-07 09:39 UTC

**Comment by balazsorban44** [comment] 2022-01-31 09:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
