### ISSUE TITLE
Invariant Violation: Unable to find element with ID XX

### ISSUE THREAD

**Issue by shaykyasin** [zeit/next.js#1068] opened 2017-02-10 14:06 UTC
When trying to run next.js on an AWS EC2, the following error was observed

```
Invariant Violation: Unable to find element with ID 109.
    at invariant (https://server.com/_next/-/commons.js:127:319)
    at precacheChildNodes (https://server.com/_next/-/commons.js:153:42)
    at getNodeFromInstance (https://server.com/_next/-/commons.js:162:41)
    at ReactDOMComponent.trapBubbledEventsLocal (https://server.com/_next/-/commons.js:10891:14)
    at CallbackQueue.notifyAll (https://server.com/_next/-/commons.js:1094:22)
    at ReactReconcileTransaction.close (https://server.com/_next/-/commons.js:14780:26)
    at ReactReconcileTransaction.closeAll (https://server.com/_next/-/commons.js:357:888)
    at ReactReconcileTransaction.perform (https://server.com/_next/-/commons.js:356:621)
    at batchedMountComponentIntoNode (https://server.com/_next/-/commons.js:2006:15)
    at ReactDefaultBatchingStrategyTransaction.perform (https://server.com/_next/-/commons.js:35
```

### More Info
- This does not occur when running a local server
- Always happens when a page is requested directly and never through AJAX
- Can be solved by rendering some components after mount

### Eg. next/Head
```jsx
      {
        this.state.mounted &&
        <Head>
          <title>{this.props.title} | Website</title>
          <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        </Head>
      }
```

### Steps to reproduce:
Just create a page with `next/Head`

### Other
- Cloudflare NGINX as reverse proxy
- Next.js 2.0.0-beta.17
- Node.js v7.3.0

**Comment by thangngoc89** [comment] 2017-02-10 16:36
This looks like a hidden bug in React itself: https://github.com/facebook/react/issues/7093

**Comment by shaykyasin** [comment] 2017-02-13 09:31
@arunoda How is this a question and not a bug? Just creating a page with a `next/Head` causes the error to pop up.

**Comment by arunoda** [comment] 2017-02-13 11:18
@shaykyasin I couldn't reproduce this. This seems like something with the way you build the app.
We need a way to reproduce to mark this as a bug.
Could you send us a sample repo?

**Comment by aesopwolf** [comment] 2017-02-14 17:44
I'm experiencing the same issue. Like @shaykyasin, it doesn't happen when running a local server. However, I also see the problem when the page is requested via AJAX.

**Comment by hieuhlc** [comment] 2017-04-09 05:46
@arunoda I encountered this issue today. Here is my repo: git@gitlab.com:holechihieu/pp.git

**Comment by matzero** [comment] 2017-05-14 02:35
Experiencing the same issue here.

**Comment by MaxSvargal** [comment] 2017-05-14 12:08
Show error reveal after switch-over to https

**Comment by lorensr** [comment] 2017-05-20 00:58
Reproduction: 

https://out-jwcahmxnmn.now.sh/

Flashes the correct UI, then gives "An unexpected error has occurred."

Translating the React console error, you get "Unable to find element with ID 10."

https://github.com/lorensr/graphql-leaderboard/tree/8709b39ef7cbffbe931387be2811f2a0332e3609

```
npm run build
now
```

**Comment by lorensr** [comment] 2017-05-20 01:03
@arunoda here are the `data-reactid` in development:

![image](https://cloud.githubusercontent.com/assets/251288/26271641/3a8d70ba-3cce-11e7-92ae-2c2ce48b57fb.png)

**Comment by lorensr** [comment] 2017-05-20 01:08
Mine was due to invalid HTML—fixed by adding a `<tbody>` inside my `<table>`

**Comment by JulianKnodt** [comment] 2017-06-10 19:53
I am also getting this bug, but I was able to remove it somehow by doing this:
![screen shot 2017-06-10 at 12 52 00 pm](https://user-images.githubusercontent.com/7675847/27005858-c86399fa-4ddb-11e7-846a-db8b2b66d7e5.png)
![screen shot 2017-06-10 at 12 53 00 pm](https://user-images.githubusercontent.com/7675847/27005857-c863b8e0-4ddb-11e7-8c06-b7de7cd347b9.png)

**Comment by AlvaroBernalG** [comment] 2017-07-07 14:23
I was getting this error only when I rendered my component from the server. In my case it was because I forgot to add 'jsx' to one of the style tags.

**Comment by kunokdev** [comment] 2017-07-10 13:45
I might be getting this bug due to style tags too. I was ommitting jsx attribubute because I wanted to use css from other file or variable. Everything worked until today. I am searching for fix. @AlvaroBernalG do you have any suggestion related to these style tags?

**Comment by timneutkens** [comment] 2017-07-10 17:11
Lets close this as it's not reproduceable. Will re-open if it's reproduceable.

**Closed by timneutkens** 2017-07-10 17:11 UTC
Labels: Type: Question

**Comment by AlvaroBernalG** [comment] 2017-07-14 10:02
@kunokdev Apologies for the delay. What I am currently doing is having a theme.js file
where I basically export all theme related individual styles (colours, font-families, font-size, shadows), as well as a one variable with all the global classes that I append to my Layout component using the global attribute. Each of my component has its own specific styles that are defined using the scoped style tag.
But then again, I am not really sure if this is the most efficient approach.. I am currently in the process learning through a pet project.

**Comment by caspg** [comment] 2017-08-18 16:40
In my case `<noscript>` was causing this error. To avoid this I had to use `dangerouslySetInnerHTML`:

```jsx
...
const staticMarkup = ReactDOMServer.renderToStaticMarkup(markup)

return <noscript dangerouslySetInnerHTML={{ __html: staticMarkup }} />
```
(Above solution found in https://github.com/zeit/next.js/pull/2767/files)

**Comment by deejayxd07** [comment] 2017-08-31 11:18
I'm having this error and it's only happening on the deployed prod app but doesn't appear locally (even warnings)

**Comment by lfender6445** [comment] 2017-09-17 17:44
For me, the issue occurred because i was rendering children on through react AND a 3rd party lib

```
<Mapbox>{mapLoaded ? children : null}</Mapbox>
```

The map code loads client side only and needs a container div reference so it can inject its `<canvas>` element after the page has loaded. 

By moving the children outside of div reserved for the canvas, react was able to render its own children without being interrupted by nodes injected via 3rd party

```jsx
<div>
  <Mapbox /> {/* <- this element reserverd for canvas / element injection not handled by react */}
  {mapLoaded ? children : null}
```

**Comment by YoungElPaso** [comment] 2017-09-28 15:10
Seemed to happen for me only when I was hot-linking to an image.  Commented out the image, went away.   Now the image is being served from /static/ so we'll see if it comes back.

**Comment by ahmdilloo** [comment] 2017-10-02 11:05
in my case , i used html p (p in p) tag nested and in webpack dev server works without error , when i build
the project and run the code in express and ssr (server side rendering) this error logged.
even though disable ssr in this component , problem not solved .
just change parent tag to <section> solved the problem.
