### ISSUE TITLE
Local Build Successful, but when deploying on ZEIT, I get "Module not found: Can't resolve '../../assets/meAvatar.jpg' "

### ISSUE THREAD

**Issue by snowtothemax** [zeit/next.js#11697] opened 2020-04-06 05:11 UTC
# Bug report
As the title says

## Describe the bug
When i build locally, using npm run build, the build loads just fine as it should. I can then run it using npm start and view it on localhost:3000. I then upload the repository to github and go to watch my project fail to deploy as it has countless times while trying to fix the issue. Here is the log that is reported: 

23:52:18.923  Retrieving list of deployment files...
23:52:19.086  Downloading 52 deployment files...
23:52:47.935  Installing build runtime...
23:52:48.377  Build runtime installed: 442.214ms
23:52:48.736  Looking up build cache...
23:52:48.766  Build cache not found
23:52:49.132  Installing dependencies...
23:52:58.140  npm WARN portfolio@1.0.0 No description
23:52:58.141  npm WARN portfolio@1.0.0 No repository field.
23:52:58.141  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/webpack/node_modules/fsevents):
23:52:58.141  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
23:52:58.141  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/next/node_modules/fsevents):
23:52:58.141  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
23:52:58.141  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
23:52:58.141  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
23:52:58.143  added 682 packages from 263 contributors in 8.675s
23:52:58.402  14 packages are looking for funding
23:52:58.402    run `npm fund` for details
23:52:58.443  Running "npm run build"
23:52:58.626  > portfolio@1.0.0 build /zeit/621d0a52
23:52:58.626  > next build
23:52:59.199  Creating an optimized production build...
23:52:59.213  Attention: Next.js now collects completely anonymous telemetry regarding usage.
23:52:59.213  This information is used to shape Next.js' roadmap and prioritize features.
23:52:59.213  You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
23:52:59.213  https://nextjs.org/telemetry
23:53:05.505  Failed to compile.
23:53:05.505  ./components/TopBarNavigator/index.js
23:53:05.505  Module not found: Can't resolve '../../assets/meAvatar.jpg' in '/zeit/621d0a52/components/TopBarNavigator'
23:53:05.506  > Build error occurred
23:53:05.507  Error: > Build failed because of webpack errors
23:53:05.507      at build (/zeit/621d0a52/node_modules/next/dist/build/index.js:13:900)
23:53:05.519  npm ERR! code ELIFECYCLE
23:53:05.519  npm ERR! errno 1
23:53:05.520  npm ERR! portfolio@1.0.0 build: `next build`
23:53:05.520  npm ERR! Exit status 1
23:53:05.520  npm ERR! 
23:53:05.520  npm ERR! Failed at the portfolio@1.0.0 build script.
23:53:05.520  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
23:53:05.523  npm ERR! A complete log of this run can be found in:
23:53:05.523  npm ERR!     /zeit/.npm/_logs/2020-04-06T04_53_05_520Z-debug.log
23:53:05.532  Error: Exited with 1
23:53:05.532      at ChildProcess.<anonymous> (/zeit/60d2972f44a2442d/.build-utils/node_modules/@now/build-utils/dist/index.js:31349:24)
23:53:05.532      at ChildProcess.emit (events.js:223:5)
23:53:05.532      at ChildProcess.EventEmitter.emit (domain.js:475:20)
23:53:05.532      at maybeClose (internal/child_process.js:1021:16)
23:53:05.533      at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
23:53:07.128  Done with "package.json"

## To Reproduce

1. npm run build
2. npm start and view behavior
3. verify the application works the way I want then upload repo to github.
4. go to ZEIT now and view the building process

## Expected behavior

expect the build to have no errors

## Screenshots
here is my package.json
![package](https://user-images.githubusercontent.com/56100786/78524854-d75bad80-779a-11ea-9ff1-2aa9513e9d19.JPG)

here is my next.config.js
![image](https://user-images.githubusercontent.com/56100786/78524894-fc502080-779a-11ea-9aeb-a0566c16024c.png)

where the issue is said to occur, but actually occurs at every import
![image](https://user-images.githubusercontent.com/56100786/78524955-34effa00-779b-11ea-9e1d-f6e67b50f204.png)

## System information

- OS: Windows 10
- Browser chrome
- Version of Next.js:

**Comment by paulogdm** [comment] 2020-04-06 11:49
Can you provide us a minimal reproducible example?

It seems you are trying to import things that are not in the repository...

**Comment by snowtothemax** [comment] 2020-04-06 15:36
@paulodgm here is the repository that ZEIT is pulling from.

![image](https://user-images.githubusercontent.com/56100786/78576027-bd998500-77f1-11ea-8e7a-8087755e288a.png)

The assets folder contains all of my images needed for the project. This is the same way my root folder is organized locally. I made sure they both had the same files/setup

**Comment by paulogdm** [comment] 2020-04-06 16:06
You should gitignore both `.next/` and `node_modules/`. Please provide a minimal reproduction example in a public repository so we can assist you further.

**Comment by Timer** [comment] 2020-04-13 18:21
This is likely a duplicate of #11742.

**Closed by Timer** 2020-04-13 18:21 UTC

**Comment by warcraft14115** [comment] 2020-04-21 13:46
Got this problem too :| Can't understan why run on localhost very well but deploy make error not found :|

**Comment by warcraft14115** [comment] 2020-04-21 14:56
ok =.= I solved this. Change the name of component from **layout.js to Layout.js** :| Can't understand why :|

**Comment by allindeveloper** [comment] 2020-08-14 00:43
Hello Please i still face this issue


01:39:39 | Failed to compile.
-- | --
01:39:39 | ModuleNotFoundError: Module not found: Error: Can't resolve 'common/src/theme/agency' in '/vercel/2ca039a8/pages'
01:39:39 | > Build error occurred
01:39:39 | Error: > Build failed because of webpack errors
01:39:39 | at build (/vercel/2ca039a8/node_modules/next/dist/build/index.js:15:918)
01:39:39 | at processTicksAndRejections (internal/process/task_queues.js:97:5)
01:39:39 | error Command failed with exit code 1.

**Comment by sauraCactus** [comment] 2020-09-10 07:43
@allindeveloper hey did you manage to resolve this?

**Comment by allindeveloper** [comment] 2020-09-10 07:53
@sauraCactus 
Yeah, i did...
I had to refactor the whole codebase.. i created a new nextjs project from scratch and copied the codes into the new one, and it worked fine.

I actually downloaded the codes from a template.. it worked on my local but was failing to build on vercel...
But after refactoring into a brand new project and copied only the files i needed, everything was fine.

**Comment by alesanchezr** [comment] 2020-10-08 18:32
> ok =.= I solved this. Change the name of component from **layout.js to Layout.js** :| Can't understand why :|

Than you!! This was my problem.

**Comment by archywillhe** [comment] 2020-10-13 15:06
Also there is a bug in my git (macOS v2.21.0) where changing a letter in lowercase in a file name won't be counted as a commit. gosh.

**Comment by sauraCactus** [comment] 2020-10-14 12:59
> Also there is a bug in my git (macOS v2.21.0) where changing a letter in lowercase in a file name won't be counted as a commit. gosh.

I had the same exact problem hahaha even the git one. That was stupid for 30 minutes hahahah.

Thanks for sharing

**Comment by softmarshmallow** [comment] 2020-10-23 16:00
In my case, not a case sensitive related problem, all in CamelCase, also the import is. just wont find the damn thing!
Works on local, fails on vercel build...

**Comment by archywillhe** [comment] 2020-10-26 18:08
> Also there is a bug in my git (macOS v2.21.0) where changing a letter in lowercase in a file name won't be counted as a commit. gosh.

just realised it's not a bug but the default behavoir of git lol need to do `git mv`

**Comment by ibrahmounk** [comment] 2021-02-18 23:52
I am facing this issue too, it is builing very well on local but send me "FATAL Error  ✖ Nuxt Fatal Error                                                         ││   Error: Template src not found:  ││   /vercel/workpath0/node_modules_dev/@nuxt/components/templates/components   ││   /readme.md  23:46:40.163  	Error: Command failed: npx nuxt build --standalone --no-lock --config-file "nuxt.config.js"

**Comment by ibrahmounk** [comment] 2021-02-18 23:52
<img width="1279" alt="Screenshot 2021-02-18 at 4 11 58 PM" src="https://user-images.githubusercontent.com/47242250/108437009-5ab3af80-7244-11eb-810b-ec90044014ca.png">

**Comment by balazsorban44** [comment] 2022-01-28 17:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
