### ISSUE TITLE
getInitialProps receives partial request inside context when running next export

### ISSUE THREAD

**Issue by marlonmarcello** [zeit/next.js#8495] opened 2019-08-23 18:43 UTC
# Bug report

## Describe the bug
`getInitialProps` receives a partial `req` with the passed context when running `next export`.
This is a problem because if fetching from a local `/api/` route, we can't reliably build an absolute URL from its information.

## To Reproduce
1. Go to [repro repo](https://github.com/marlonmarcello/next-req-export)
2. Clone and install deps
3. Then run `yarn export`

## Expected behavior
`req` should be empty so we can skip this step and so data can be fetched when the static files are deployed.
Or a server could be spawned temporarily so local `/api/` routes can be fetched.

**Comment by aried3r** [comment] 2019-11-21 16:38
I think I'm seeing the same behavior when trying to dynamically generating a sitemap (debatable if this shouldn't be a `postexport` script). I tried your repro example and it exhibits the same behavior.

I believe this could be the cause: https://github.com/zeit/next.js/blob/0b18f854ba4397cdcbd6fd5b2a8df8e8f533033d/packages/next/export/worker.js#L59-L74

Using TypeScript, it tells me that `res` should be a [`ServerResponse`](https://nodejs.org/docs/latest-v12.x/api/http.html#http_class_http_serverresponse) but indeed when I log the object it is indeed the `res` with the `headerMocks` and not a real `ServerResponse`.

This works during development, but fails during export.

The component in question:
```ts
// Based on
// https://gist.github.com/henninghall/cc284e96ed555f2f09c14422860113a8
import { NextPage } from "next"
import { readdirSync, statSync } from "fs"

const Sitemap: NextPage = () => null

Sitemap.getInitialProps = async ({ res }) => {
  if (!res || typeof window !== "undefined") return {}

  const folder = "pages"
  const endpoint = "https://www.example.com"

  res.setHeader("content-type", "application/xml")

  let content = readdirSync(folder)
    .map(f => (f === "_app.tsx" ? "" : f))
    .filter(f => !f.startsWith(`_`))
    .filter(f => !f.startsWith(`[`))
    .filter(f => f !== `sitemap.xml.tsx`)
    .map(f => ({
      filename: f,
      updatedAt: statSync(`${folder}/${f}`)
        .mtime.toISOString()
        .substr(0, 10)
    }))
    .map(f => ({ ...f, filename: f.filename.replace(".tsx", "") }))
    .map(f => ({ ...f, filename: `${endpoint}/${f.filename}` }))
    .map(
      f =>
        `<url><loc>${f.filename}</loc><lastmod>${f.updatedAt}</lastmod></url>`
    )
    .join()

  res.end(
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${content}</urlset>`
  )
  return {}
}

export default Sitemap
```

This worked at least once, but now fails to export properly. This is the output:

```console
$ npm run build && npm run export

> website@1.0.0 build /Development/website
> next build

Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Creating an optimized production build

Compiled successfully.

Automatically optimizing pages

Page                              Size     Files  Packages
┌ ⚡ /                             12.1 kB     16         5
├   /_app                         431 kB       0         6
├   /_document
├   /_error                       1.96 kB      0         5
├ ⚡ /impressum                    2.15 kB      9         5
├ σ /sitemap.xml                  1.79 kB      9         5
└ ⚡ /team                         7.85 kB     11         5

σ  (Server)       page will be server rendered (i.e. getInitialProps)
⚡  (Static File)  page was prerendered as static HTML


> website@1.0.0 export /Development/website
> next export

> using build directory: /Development/website/.next
  copying "static build" directory
> No "exportPathMap" found in "next.config.js". Generating map from "./pages"
  launching 3 workers
  copying "public" directory
[ ===] Exporting (0/13)
Error occurred prerendering /sitemap.xml: TypeError: res.end is not a function
    at Function.module.exports.1gvX.Sitemap.getInitialProps (/Development/website/.next/server/static/ryXSju87mLwSGEeqZ56_M/pages/sitemap.xml.js:533:7)
    at loadGetInitialProps (/Development/website/.next/server/static/ryXSju87mLwSGEeqZ56_M/pages/_document.js:3098:33)
    at Function.<anonymous> (/Development/website/.next/server/static/ryXSju87mLwSGEeqZ56_M/pages/_app.js:842:60)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Development/website/.next/server/static/ryXSju87mLwSGEeqZ56_M/pages/_document.js:160:24)
    at _next (/Development/website/.next/server/static/ryXSju87mLwSGEeqZ56_M/pages/_document.js:182:9)
    at /Development/website/.next/server/static/ryXSju87mLwSGEeqZ56_M/pages/_document.js:189:7
    at new Promise (<anonymous>)
    at new F (/Development/website/.next/server/static/ryXSju87mLwSGEeqZ56_M/pages/_document.js:265:28)
    at Function.<anonymous> (/Development/website/.next/server/static/ryXSju87mLwSGEeqZ56_M/pages/_document.js:178:12)
Exporting (13/13)
Error: Export encountered errors
    at _default (/Development/website/node_modules/next/dist/export/index.js:15:734)
[    ] Exporting (13/13)npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! website@1.0.0 export: `next export`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the website@1.0.0 export script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-11-21T16_22_00_074Z-debug.log
```

**Comment by aried3r** [comment] 2019-11-27 15:34
It's not completely clear to me how next.js arrives at this code path. @ijjk, it seems you made the last bigger code change to `worker.js`, could you maybe shed some light on this?

**Comment by timneutkens** [comment] 2020-01-02 22:02
Closing in favor of #9524

**Closed by timneutkens** 2020-01-02 22:02 UTC

**Comment by balazsorban44** [comment] 2022-01-30 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
