### ISSUE TITLE
React Context Does not work inside pages.

### ISSUE THREAD

**Issue by samanmohamadi** [zeit/next.js#4712] opened 2018-07-01 19:18 UTC
## Question
I create a simple React Context to test the React Context API but it seems that is doesn't work as expected or I'm doing something wrong.

TestContext
```
import React from 'react';
export default React.createContext(true);
```

in _app.js
```
import TestContext from './TestContext';
...
render(){
....
 <TestContext.Provider value={false}>
     <Component pageContext={this.pageContext} {...pageProps} />
 </TestContext.Provider>
}
```

inside a page:
```
render() {
        return (
            <TestContext.Consumer>
                {isTrue => isTrue ? 'true' : 'false'}
            </TestContext.Consumer>
        );
    }
```
**output**: true

**Comment by timneutkens** [comment] 2018-07-01 19:31
Duplicate of #4194

**Closed by timneutkens** 2018-07-01 19:31 UTC
