### ISSUE TITLE
using nextjs and animated

### ISSUE THREAD

**Issue by lionelB** [zeit/next.js#1912] opened 2017-05-07 18:51 UTC
I'm using the [animated](https://github.com/animatedjs/animated/) inside a next.js app
Thing work fine but when I try to build the app I'm having an issue
<details>

```
{ Error: ./~/animated/lib/targets/react-dom.js
Module not found: Error: Can't resolve 'react-dom/lib/CSSPropertyOperations' in '/Users/lionel/Code/lumographe/animated-next/node_modules/animated/lib/targets'
resolve 'react-dom/lib/CSSPropertyOperations' in '/Users/lionel/Code/lumographe/animated-next/node_modules/animated/lib/targets'
  Parsed request is a module
  using description file: /Users/lionel/Code/lumographe/animated-next/node_modules/animated/package.json (relative path: ./lib/targets)
    Field 'browser' doesn't contain a valid alias configuration
    aliased with mapping 'react-dom': '/Users/lionel/Code/lumographe/animated-next/node_modules/react-dom/dist/react-dom.min.js' to '/Users/lionel/Code/lumographe/animated-next/node_modules/react-dom/dist/react-dom.min.js/lib/CSSPropertyOperations'
      using description file: /Users/lionel/Code/lumographe/animated-next/node_modules/animated/package.json (relative path: ./lib/targets)
        Field 'browser' doesn't contain a valid alias configuration
      after using description file: /Users/lionel/Code/lumographe/animated-next/node_modules/animated/package.json (relative path: ./lib/targets)
        using description file: /Users/lionel/Code/lumographe/animated-next/node_modules/react-dom/package.json (relative path: ./dist/react-dom.min.js/lib/CSSPropertyOperations)
          as directory
            /Users/lionel/Code/lumographe/animated-next/node_modules/react-dom/dist/react-dom.min.js/lib/CSSPropertyOperations doesn't exist
          no extension
            Field 'browser' doesn't contain a valid alias configuration
            /Users/lionel/Code/lumographe/animated-next/node_modules/react-dom/dist/react-dom.min.js/lib/CSSPropertyOperations doesn't exist
          .js
            Field 'browser' doesn't contain a valid alias configuration
            /Users/lionel/Code/lumographe/animated-next/node_modules/react-dom/dist/react-dom.min.js/lib/CSSPropertyOperations.js doesn't exist
          .json
            Field 'browser' doesn't contain a valid alias configuration
            /Users/lionel/Code/lumographe/animated-next/node_modules/react-dom/dist/react-dom.min.js/lib/CSSPropertyOperations.json doesn't exist

``` 

</details>

I've made a small repo if you want to investigate more https://github.com/lionelB/-animated-next

**Comment by timneutkens** [comment] 2017-05-07 20:56
Hi, thanks for reporting this. The issue seems a duplicate of `#1877`

**Closed** 2017-05-07 20:57 UTC

**Comment by lionelB** [comment] 2017-05-08 09:49
oups sorry, for the duplicate. thanks for your answer too !
