### ISSUE TITLE
Ability to co-locate non-page files in the pages directory

### ISSUE THREAD

**Issue by probablyup** [zeit/next.js#8454] opened 2019-08-20 23:44 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

There are many different methods of codebase organization in the wild and one popular one is to use an `index.js` file for the page component itself and surround it with sibling files for various subviews that are specific to that page.

However, next doesn't support this kind of structure because it automatically assumes _all_ files inside of `pages/` are real pages. 

## Describe the solution you'd like

There already is precedent in the codebase for convention over configuration when it comes to filenaming:

- the `[id].js` pattern for dynamic routing
- the `_(app|document|error).js` pattern for overriding built-in pages

I propose extending the leading-underscore naming pattern such that any file inside `pages/` prefixed with an underscore will not be considered as a public page and can simply live in the folder.

```
pages/
  index.js                  <- page
  accounts/
    index.js                <- page
    _constants.js           <- not a page
    _modal.js               <- not a page
```

## Describe alternatives you've considered

Another prefix I thought of was "$", e.g. `$constants.js` but this felt a little strange to write and actually is [not supported in some filesystems](https://en.wikipedia.org/wiki/Filename).

**Comment by timneutkens** [comment] 2019-08-21 11:37
> However, next doesn't support this kind of structure because it automatically assumes all files inside of pages/ are real pages.

The convention is that all files inside `pages` are pages, it's quite a simple convention that we're not planning to change as of right now.

Introducing something like `_` to mark private pages also has security implications, as there might be accidental exposure of code etc.

Something like this behavior is already possible to achieve by having a separate directory holding this structure and then the public routes would be exposed in `pages`.

**Comment by timneutkens** [comment] 2019-08-28 09:41
It's extensively discussed in #3728 so I'm thinking we should probably close this issue.

@baer for zeit.co we use a combination of the first and second method, we have a `pages`, `components and `lib` directory. Pages generally build up out of components, header, footer etc. and implement the data fetching logic through getInitialProps. There's a bit of duplication but that's not a bad thing as it improves bundling.

**Comment by baer** [comment] 2019-09-09 22:39
🤔I'm a bit surprised to hear you're not on the #3 train. Do you have any conventions around keeping `components` and `lib` in sync with what's in `pages`? With path-based routing, you can't match up names anymore.

**Comment by timneutkens** [comment] 2019-09-10 07:06
We utilize the design system everywhere so we try to avoid introducing page specific components. However if there are page specific components they match the pages folder structure.

**Comment by baer** [comment] 2019-09-11 15:56
I also use a design system but I'm using Next.js for a dynamic logged-in-only web Application. With the level of complexity for each page, it's impractical to avoid page-specific components. To give you a better sense of what I'm talking about, here's a screenshot of our folder structure.

**`/next-app/pages`**

<img width="255" alt="Screen Shot 2019-09-10 at 7 29 34 PM" src="https://user-images.githubusercontent.com/940667/64663683-7422bc00-d401-11e9-9b57-1797e93a6295.png">

**`next-app/src`**

<img width="221" alt="Screen Shot 2019-09-10 at 7 28 36 PM" src="https://user-images.githubusercontent.com/940667/64663671-6e2cdb00-d401-11e9-89d3-304023a9bcba.png">

You can see that I've got three types of files: page entry points in the `/pages` directory, common components in the `/src/components` directory and page-specific components in `/src/pages`. You can see that we've done our best to name each page to match the route name. This keeps things mostly organized but is always a small annoyance trying to figure out where code lives.

Is it uncommon to build mostly-dynamic apps like this using Next.js? If no, are there other patterns you've seen out there for keeping the project well structured?

Note: Now that project structure drives routing, in addition to compiled pages, and with RFCs like the https://github.com/zeit/next.js/issues/8451 coming up, directory structure may be an interesting thing to add to https://github.com/zeit/next.js/issues/8442.

**Comment by timneutkens** [comment] 2019-09-11 21:28
> You can see that I've got three types of files: page entry points in the /pages directory, common components in the /src/components directory and page-specific components in /src/pages. You can see that we've done our best to name each page to match the route name. This keeps things mostly organized but is always a small annoyance trying to figure out where code lives.

So zeit.co is mostly the same except we only have the components directory, so no `src/pages`.

> Is it uncommon to build mostly-dynamic apps like this using Next.js? If no, are there other patterns you've seen out there for keeping the project well structured?

It's not uncommon, however I do think that there's currently no "recommended" folder structure in the docs and we might want to provide some guidance there.

I'll ask some people running larger apps to reply to this issue (if they want to).

> Note: Now that project structure drives routing, in addition to compiled pages, and with RFCs like the #8451 and #8063 coming up, directory structure may be an interesting thing to add to #8442.

Great point, we didn't want to send the tree in particular as it could be sensitive info. But checking based on heuristics would be fine I think 🙏

**Comment by shynome** [comment] 2019-12-02 14:59
@probablyup 
this is so easy, set pageExtensions as below
```js
// next.config.js
module.exports = {
  pageExtensions: ["page.tsx", "api.ts"],
}
```
a file tree like below, and only `/list` page is work
```
pages/
├── api
│   └── pm2
│       ├── index.api.ts
│       └── pm2.ts
├── _app.page.tsx
├── _document.page.tsx
├── list.page.tsx
├── pm2.client.ts
└── theme.ts
```

**Closed** 2020-01-02 22:00 UTC

**Comment by alihesari** [comment] 2020-04-18 16:48
To solve this issue, I added getInitialProps in my component and pass a prop to the component. When the component imported in a page `getInitialProps` function will not run and that the prop will be undefined so I return the current component and otherwise I return 404 error.

Something like:
```
/pages
....  /home.js
........  /components
.........  myComp.js
```

**home.js**
```
import MyComp from "./components/myComp";

const home = ({ course }) => {
    return (
        <>
             <h1>Home page</h1>
             <MyComp />
        </>
    );
}

export default home;
```

**mycomp.js**
```
import Error from 'next/error'

const mycomp = ({ isValid }) => {
   const renderComp = () => {
       if (isValid !== undefined) {
            return <Error statusCode={404} />
        } else {
            return <h2>This is My component</h2>;
        }
   }

    return renderComp();
}

mycomp.getInitialProps = (ctx) => {
    return { isValid: false };
};

export default mycomp;
```

**Comment by GrantGryczan** [comment] 2021-04-07 21:21
> this is so easy, set pageExtensions as below

@shynome but then, instead of `import ... from 'pages/whatever'`, I have to do `import ... from 'pages/whatever/index.page'` which is way more verbose and difficult to read. It is not a good long-term solution.

**Comment by shynome** [comment] 2021-04-08 02:27
> > this is so easy, set pageExtensions as below
> 
> @shynome Good idea, but then, instead of `import ... from 'pages/whatever'`, I have to do `import ... from 'pages/whatever/index.page'` which is way more verbose and difficult to read. It is not a good long-term solution.

@GrantGryczan you still can use `import ... from 'pages/whatever'`, just add `pages/whatever/index.ts` file for export , `index.page.ts` now is just for render page

**Comment by GrantGryczan** [comment] 2021-04-11 12:42
> > > this is so easy, set pageExtensions as below
> > 
> > 
> > @shynome Good idea, but then, instead of `import ... from 'pages/whatever'`, I have to do `import ... from 'pages/whatever/index.page'` which is way more verbose and difficult to read. It is not a good long-term solution.
> 
> @GrantGryczan you still can use `import ... from 'pages/whatever'`, just add `pages/whatever/index.ts` file for export , `index.page.tsx` now is just for render page

@shynome That isn't exactly a clean solution, adding a new file for each page you want to import elsewhere. It would be better if something for this were built into Next. I'm not sure why this issue was closed.

**Comment by shynome** [comment] 2021-04-11 13:21
@GrantGryczan I think one component one file is a good idea, not all components in one file.
but anyway, just follow your favorite way.

**Comment by GrantGryczan** [comment] 2021-04-11 14:02
> @GrantGryczan I think one component one file is a good idea, not all components in one file.
> but anyway, just follow your favorite way.

I did not suggest putting all components in one file. That would not even be possible with Next considering each page must be a separate file. I suggested one file per page. What you are suggesting, on the contrary, is one file per page, plus an additional file for any page I want to import elsewhere.

**Comment by JDansercoer** [comment] 2021-05-21 08:07
@GrantGryczan Why would you ever want to import another page elsewhere? Pages are meant to be standalone components.

**Comment by GrantGryczan** [comment] 2021-05-26 09:44
> @GrantGryczan Why would you ever want to import another page elsewhere? Pages are meant to be standalone components.

There are plenty of use cases. Importing the error page for use on other pages (which in some cases is encouraged in the Next.js docs), importing a TypeScript type from a page (e.g. the type for the page's props), importing something exported from a page which is relevant to that page, etc.

**Comment by rperozin** [comment] 2021-11-11 14:55
> @probablyup this is so easy, set pageExtensions as below
> 
> ```js
> // next.config.js
> module.exports = {
>   pageExtensions: ["page.tsx", "api.ts"],
> }
> ```
> 
> a file tree like below, and only `/list` page and `/api/pm2` api work
> 
> ```
> pages/
> ├── api
> │   └── pm2
> │       ├── index.api.ts
> │       └── pm2.ts
> ├── _app.page.tsx
> ├── _document.page.tsx
> ├── list.page.tsx
> ├── pm2.client.ts
> └── theme.ts
> ```

Absolutely! The NextJS suggest exactly this on their documentation.
https://nextjs.org/docs/api-reference/next.config.js/custom-page-extensions#including-non-page-files-in-the-pages-directory

**Comment by balazsorban44** [comment] 2022-01-27 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
