### ISSUE TITLE
Error: Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by jhenriquevissotto** [zeit/next.js#10997] opened 2020-03-12 10:26 UTC
No redux. No Router. No advanced components.

Just a Hello World with useSate & useEffect produces this error:

"Error: Invalid hook call. Hooks can only be called inside of the body of a function component."

1 - Print of the error message: https://i.imgur.com/rbbOEX9.png
2 - Print of the source code: https://i.imgur.com/S4Vu7je.png
3 - Link of the code with build .next: http://bit.ly/39JFQ6d

And yes, obviously the hooks was called in body of the function.

This error happens since 3 or 6 months agor. I don't know why it wasn't fixed yet. =S

It become impossible to use the Next.js now.

**Comment by JerryCauser** [comment] 2020-03-12 11:37
I tested on my environment and it works correctly. MacOS 10.15.3, node 12.16.1
 What your OS and node version

**Comment by jhenriquevissotto** [comment] 2020-03-12 12:19
Windows 7, node 12. 

This bug already happened with me several and several times.

**Comment by Timer** [comment] 2020-03-12 12:38
Duplicate of #9022

**Closed by Timer** 2020-03-12 12:38 UTC

**Comment by balazsorban44** [comment] 2022-01-30 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
