### ISSUE TITLE
On demand entries issue

### ISSUE THREAD

**Issue by ArnoBuschmann** [zeit/next.js#1319] opened 2017-03-01 02:15 UTC
After starting next.js in dev mode on port 3000, I get the error below repeatedly and the bundle starts to rebuild several times.

Interesting is, that the URL http://localhost:3000/de/home/herzlich-willkommen is not part of that next project at all but from another app I ran before on port 3000.

Im using Chrome and deleting the application storage, local storage, session storage, cookies and cache, the problem remains, even after an entire computer restart (Ubuntu).

Starting on another port, for example:
npm run dev -- -p 3500
and the error is gone.

```
VM41:2 GET http://localhost:3000/de/home/herzlich-willkommen 404 (Not Found)
(anonymous) @ VM41:2
_callee$ @ on-demand-entries-client.js?f6d3b90:27
tryCatch @ runtime.js?57cc4a9:64
invoke @ runtime.js?57cc4a9:299
prototype.(anonymous function) @ runtime.js?57cc4a9:116
step @ asyncToGenerator.js?0a988d4:17
(anonymous) @ asyncToGenerator.js?0a988d4:35
F @ _export.js?1c1f8b5:35
(anonymous) @ asyncToGenerator.js?0a988d4:14
ping @ on-demand-entries-client.js?f6d3b90:58
_callee2$ @ on-demand-entries-client.js?f6d3b90:80
tryCatch @ runtime.js?57cc4a9:64
invoke @ runtime.js?57cc4a9:299
prototype.(anonymous function) @ runtime.js?57cc4a9:116
step @ asyncToGenerator.js?0a988d4:17
(anonymous) @ asyncToGenerator.js?0a988d4:28
on-demand-entries-client.js?f6d3b90:47 Error with on-demand-entries-ping: Unexpected token < in JSON at position 0
```

**Comment by arunoda** [comment] 2017-03-01 03:01
Where exactly you got this error?
On the browser console of `http://localhost:3000/de/home/herzlich-willkommen`?

> After starting next.js in dev mode on port 3000, I get the error below repeatedly and the bundle starts to rebuild several times.

I need to know about what do you mean by this. (A gif or a short video will be awesome)

**Comment by ArnoBuschmann** [comment] 2017-03-01 03:42
Thanks for your quick response, @arunoda 

> Where exactly you got this error?
> On the browser console of http://localhost:3000/de/home/herzlich-willkommen?

Not exactly, I get it on the browser console of ```http://localhost:3000/```.

> I need to know about what do you mean by this. (A gif or a short video will be awesome)

I just retried and indeed the rebuilding happened just once, thereafter the "Unexpeted token" error happened again repeteadly about every 5 seconds:

![console](https://cloud.githubusercontent.com/assets/1889233/23445095/48b9f4a2-fe39-11e6-82ec-7625b4b24452.gif)

**Comment by arunoda** [comment] 2017-03-01 04:09
That's pretty weird. I'll check.

**Comment by timneutkens** [comment] 2017-03-01 06:06
@arunoda this looks like an issue we've seen before Where the output of webpack/Babel to main.js was html instead of json. Idk How this was resolved before though. But it's definitely in the issues list somewhere 🤔

**Comment by timneutkens** [comment] 2017-03-01 06:06
Json = js* on my phone ;)

**Comment by ArnoBuschmann** [comment] 2017-03-01 11:21
I also found out, that this problem is not occuring, when opening a Chrome incognito tab.

**Comment by timneutkens** [comment] 2017-03-01 11:48
@ArnoBuschmann could you check the network panel filtered by xhr. And then open a request to on-demand-entries-ping. Once there can you check the response and send it here if possible.

**Comment by ArnoBuschmann** [comment] 2017-03-01 11:58
@timneutkens filtering the network panel by xhr gives me these kinds of requests:

__webpack_hmr
b9aab665db16b334b7cf.hot-update.json
pages/
next.js

How would I
> And then open a request to on-demand-entries-ping.

?

**Comment by ArnoBuschmann** [comment] 2017-03-01 12:16
And now the ongoing repeatedly rebuilding takes place again, as screenshot it looks like this:
![console2](https://cloud.githubusercontent.com/assets/1889233/23459562/2ffc6006-fe81-11e6-92b5-2e81c442857a.gif)

**Comment by arunoda** [comment] 2017-03-01 12:25
If you are running a custom server, you may need to pass everything in the `/_next/` to the Next's handler.

Anyway, try to reset the cache and try again.

**Comment by ArnoBuschmann** [comment] 2017-03-01 12:31
Resetting the cache has no effect. I'm not running a custom server. As said, the URL /de/home/herzlich-willkommen is from another app (not next.js), which indeed had a custom server. But that app isn't running anymore. But for some reason Chome still has stored the URL, somehow, somewhere.

**Comment by timneutkens** [comment] 2017-03-01 12:32
@arunoda Just came across this: https://webpack.js.org/guides/migrating/#json-loader-is-not-required-anymore. Might be not related at all though.

**Comment by timneutkens** [comment] 2017-03-01 12:34
@ArnoBuschmann @arunoda Also, could you run this in the console: `navigator.serviceWorker.getRegistrations().then(registrations => console.log(registrations))` I'm wondering if there's still a serviceworker registration.

**Comment by ArnoBuschmann** [comment] 2017-03-01 12:40
@timneutkens it returns:
```
navigator.serviceWorker.getRegistrations().then(registrations => console.log(registrations))
Promise__proto__: Promise[[PromiseStatus]]: "resolved"[[PromiseValue]]: undefined
VM351:1 Array[0]length: 0__proto__: Array[0]
```

**Comment by sedubois** [comment] 2017-03-01 12:41
or can just check on chrome://serviceworker-internals ?

**Comment by ArnoBuschmann** [comment] 2017-03-01 12:44
> or can just check on chrome://serviceworker-internals ?
I can't see a next.js related service worker there.

**Comment by sedubois** [comment] 2017-03-01 12:48
Just in case, I think you can delete all of them then try again? Normally they aren't critical.

**Comment by timneutkens** [comment] 2017-03-01 13:04
There are none installed. That's good. wanted to make sure the old prefetcher was removed.

**Comment by ArnoBuschmann** [comment] 2017-03-01 13:59
@sedubois Yep, I have deleted them all, the problem remains.

**Comment by arunoda** [comment] 2017-03-01 14:41
@timneutkens this HTML issue is related to the XHR request and not related to Webpack stuff. on-demands-entries-ping expects a JSON response and in this case, it seems it's not.

**Comment by timneutkens** [comment] 2017-03-01 15:22
Okay 👍

**Comment by arunoda** [comment] 2017-03-02 04:28
@ArnoBuschmann check this is same as with your case: https://github.com/zeit/next.js/issues/1326#issuecomment-283552954

**Comment by ArnoBuschmann** [comment] 2017-03-02 08:51
@arunoda It was different in my case as the production build was running well, while the dev mode was causing this problem.

Weirdly enough, the problem disappeared today :) but I don't know why :(

I guess I could reproduce the problem by letting the other app run again on port 3000 if we need to investigate this further to find out more about the problem. Atm I'm good with having it running properly.

So, should we let this issue stay open or close it? Your choice :)

**Comment by timneutkens** [comment] 2017-03-02 09:57
Hoping it was an issue on your browser's side. I'll close this for now. If it happens again could you send us an example repo to see if we could reproduce it. Thank you very much for reporting / giving feedback ❤️ If it's only happening locally we could use teamviewer to debug 😉

**Closed by timneutkens** 2017-03-02 09:57 UTC
