### ISSUE TITLE
During Build - CSS file are generated twice

### ISSUE THREAD

**Issue by iamkumaran** [zeit/next.js#10038] opened 2020-01-10 18:26 UTC
# Bug report

## Describe the bug

with latest version `v9.1.8-canary.11`, CSS files are generated twice and duplicated. Here's the screenshot,

I'm using the following packages,
```
    "@zeit/next-sass": "^1.0.1",
    "next": "9.1.8-canary.11",
    "node-sass": "4.12.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0"
```
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Repo: 'https://github.com/iamkumaran/next-canary-css-duplicate-demo'
2. `yarn build`
3. `yarn start`
4. Open the page in chrome and goto network tab, there will two CSS files (in that one is duplicate)

## Expected behavior

Duplicate CSS files should not generated.

## Screenshots
![image](https://user-images.githubusercontent.com/10018448/72176576-b1757580-3404-11ea-8b02-aba315cee053.png)

## System information

- macOS
- Next.js v9.1.8-canary.11

**Comment by Timer** [comment] 2020-01-10 21:50
Fixed in `9.1.8-canary.12`. Please give it a try and let us know.

**Closed by Timer** 2020-01-10 21:50 UTC

**Comment by iamkumaran** [comment] 2020-01-11 13:52
Issue is resolved. Verified on `9.1.8-canary.13`

**Comment by balazsorban44** [comment] 2022-01-30 16:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
