### ISSUE TITLE
aws-serverless-express and serverless example

### ISSUE THREAD

**Issue by virzak** [zeit/next.js#4482] opened 2018-05-27 16:17 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
Trying to host the next.js project in AWS turned out to be difficult. Is it possible to create an example with it?

## Describe the solution you'd like
Example should consider scenario where express server is not initialized right away as in https://github.com/zeit/next.js/blob/canary/examples/with-react-i18next/ example

## Describe alternatives you've considered
Tried adding next to https://github.com/awslabs/aws-serverless-express/tree/master/example  
Also tried adding aws-serverless-express to https://github.com/zeit/next.js/tree/canary/examples/custom-server-express  
Neither worked.

**Comment by Enalmada** [comment] 2018-09-05 18:32
The readme should probably also have a warning that serverless solutions introduce latency that may not be appropriate for consumer facing products.  I tested a next.js example on AWS Beanstalk and it consistently returns in about 35ms.   With AWS Lambda, it varies wildly between 150ms and 2.5s when "warm".

**Comment by timneutkens** [comment] 2018-09-05 18:45
I wonder if this is actually Next's fault or AWS Lamba being slow for React SSR 🤔

**Comment by Enalmada** [comment] 2018-09-05 19:32
My guess is that it is nothing to do with React.  I suspect the CloudFront "edge" adds ~100ms avg, the API Gateway adds around ~100ms avg, and the rest of the variation is Lambda sharing resources. You can now do "regional" API Gateway to eliminate the CloudFront edge latency but you give up http->https redirection which is important if you want to serve a public facing site.

**Comment by smcelhinney** [comment] 2018-11-07 10:15
I see `serverless` has a Vue/Nuxt.js example, would this be a good starting point? 

https://github.com/serverless/examples/tree/master/aws-node-vue-nuxt-ssr

**Comment by Prefinem** [comment] 2018-12-04 00:37
Here is a repo of next.js working on lambda with serverless. (or, well, mostly working.  I am still working on building an app around it for some internal work)

https://github.com/Prefinem/aws-lambda-serverless-nextjs

Please feel free to let me know if I am missing something or need to make any changes to support something I am not currently

**Comment by romainquellec** [comment] 2019-01-10 16:26
Will try to make a current project work with next-canary ! (I will add an example if this works as intended)
Thanks for this btw ! Nice work !

**Comment by romainquellec** [comment] 2019-01-22 14:07
Sorry but not available for a simple serverless example. (My example will be with typescript, so not so basic after all)

**Comment by kamleshchandnani** [comment] 2019-03-10 09:22
@timneutkens Actually I am trying to create an example of something like this
1. Nextjs + Serverless
2. Use `serverless-offline` to get it work in dev mode with HMR
3. Use `aws-serverless-express`
3. Deploy it on AWS lambda


I have a sample repo you can have a look at.
https://github.com/kamleshchandnani/nextjs-serverless
But currently whenever I try to run it in dev mode it goes into infinite loading similar to this #2123

Maybe you can share some thoughts on it? I can then send a PR to add it to `examples`

**Comment by timneutkens** [comment] 2020-01-02 19:52
Going to close this as it's had good first issue / help wanted for 1,5 year.

**Closed by timneutkens** 2020-01-02 19:52 UTC
Labels: Type: Example, good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-30 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
