### ISSUE TITLE
Expose granular request timings for logging

### ISSUE THREAD

**Issue by AndrewIngram** [zeit/next.js#6242] opened 2019-02-11 11:18 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

When a request is slow, it can be useful to understand where the bottleneck is. Currently the only thing we can easily see is how long the overall HTTP request took.

## Describe the solution you'd like
I'd like some way of logging (and even visualising), the timings for the following:

1. getInitialProps 
2. React itself rendering the initial response
3. Anything else that we could expect to have a meaningful impact on response times.

## Describe alternatives you've considered
I've tried doing this in user-land, but I couldn't see any obvious ways to hook into the render cycle to expose this information.

**Comment by timneutkens** [comment] 2019-08-09 15:48
Closing this in favor of #8069 and other work Houssein has been doing.

**Closed by timneutkens** 2019-08-09 15:48 UTC
Labels: Type: Feature Request

**Comment by balazsorban44** [comment] 2022-01-31 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
