### ISSUE TITLE
How to make music player continue playing when I move between pages?

### ISSUE THREAD

**Issue by alizamani** [zeit/next.js#8441] opened 2019-08-20 11:56 UTC
I'm using Next.js framework and react-player component to play some music on my site. Everything is good until I navigate to the second page. Then the music player stops and when I go back to the first page, the music starts playing again.

While I want the music to not be interrupted by going to different pages and be an upstream component that I can change the music files from different pages.

What way do you suggest to this case?

**Comment by huv1k** [comment] 2019-08-20 12:10
Hey @alizamani, closing this issue, first of all, please don't create a duplicate on Spectrum and Github. Second of all please follow our issue temple.

**Closed by huv1k** 2019-08-20 12:10 UTC

**Comment by alizamani** [comment] 2019-08-20 12:30
How disappointing. I need help and you teach the rules without any help.

**Comment by timneutkens** [comment] 2019-08-20 12:36
Hey @alizamani the issue template clearly says that questions should be posted on https://spectrum.chat/next-js, the reason for this is that there are many community members on Spectrum willing to help out, more so than here on GitHub issues.

**Comment by MagicMikeChen** [comment] 2021-12-31 03:48
After researching lots days, I solved similar problem with this:

https://nextjs.org/docs/basic-features/layouts

Just make a HOC wrapped the whole _app and set what you want to do in the HOC.

**Comment by balazsorban44** [comment] 2022-01-30 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
