### ISSUE TITLE
building with-amp example fails

### ISSUE THREAD

**Issue by philipheinser** [zeit/next.js#1915] opened 2017-05-08 01:19 UTC
checkout with-amp expanse, install deps with yarn, yarn run build produces an error:

`> Failed to build on /var/folders/96/_4p69_wn5jj32w5tl1prsd640000gn/T/1c702ef9-d328-4aad-a4be-713d02183e83
{ Error: ./pages/_document.js?entry
Module not found: Error: Can't resolve 'react-dom/lib/ReactInjection' in '/Users/philipheinser/Downloads/next.js-master/examples/with-amp/pages'
resolve 'react-dom/lib/ReactInjection' in '/Users/philipheinser/Downloads/next.js-master/examples/with-amp/pages'
  Parsed request is a module
  using description file: /Users/philipheinser/Downloads/next.js-master/examples/with-amp/package.json (relative path: ./pages)
    Field 'browser' doesn't contain a valid alias configuration
    aliased with mapping 'react-dom': '/Users/philipheinser/Downloads/next.js-master/examples/with-amp/node_modules/react-dom/dist/react-dom.min.js' to '/Users/philipheinser/Downloads/next.js-master/examples/with-amp/node_modules/react-dom/dist/react-dom.min.js/lib/ReactInjection'`

**Comment by timneutkens** [comment] 2017-05-08 20:25
Duplicate of #1877

**Closed by timneutkens** 2017-05-08 20:25 UTC
