### ISSUE TITLE
Router.query is incorrect during first render/onMount of a static page

### ISSUE THREAD

**Issue by WillSelway** [zeit/next.js#12716] opened 2020-05-11 13:22 UTC
## Describe the bug

Router.query seems to be incorrect during the first render & on mount (using useEffect) in a statically rendered page. It's fine on 2nd & subsequent renders.

Edit: Produced it on next version 9.3.6 in chrome 81

## To Reproduce
```
import React, { useEffect } from 'react';
import { useRouter } from 'next/router';

export default () => {
	const Router = useRouter();

	useEffect(() => {
		console.log(window.location.href);
		console.log(Router.query);
	}, []);

	return (
		<div>
			test
		</div>
	)
}
```

Going to this page with a query string like 'http://localhost:3000/test?a=1&b=2&c=3', I see the below printed -
```http://localhost:3000/test?a=1&b=2&c=3```
```{}```

## Expected behavior

I would expect Router.query to print out { a: 1, b: 2, c: 3 } on the first render.

## Screenshots

![image](https://user-images.githubusercontent.com/30043784/81553478-0908fb00-937d-11ea-9b15-3509c9c8cb5c.png)

Below is my current work around if anyone else is having this issue or in case anyone can suggest a better workaround.

```
import React, { useRef, useEffect } from 'react';
import { useRouter } from 'next/router';

export default () => {
	const Router = useRouter();

	const RefRenderCount = useRef(0);
	RefRenderCount.current++;

	useEffect(() => {
		if(RefRenderCount.current === 2){
			console.log(Router.query);
		}
	}, [RefRenderCount.current]);

	return (
		<div>
			test
		</div>
	)
}
```

**Comment by ijjk** [comment] 2020-05-11 20:32
Hi, this is the expected behavior to prevent breaking hydration for statically optimized pages, see https://github.com/zeit/next.js/issues/8259 for more info.

I'm going to close this issue in favor of the existing one

**Closed by ijjk** 2020-05-11 20:32 UTC

**Comment by balazsorban44** [comment] 2022-01-30 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
