### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by James-Quigley** [zeit/next.js#5991] opened 2019-01-04 23:39 UTC
Aware of https://github.com/zeit/next.js/issues/5550 but that was closed due to not following template

# Bug report

## Describe the bug

When running the app on now.sh, after visiting the homepage I get an error:
`TypeError: Object(...) is not a function`

## To Reproduce
I'm unable to repro locally, but the issue consistently pops up when deploying on now.sh

## Expected behavior
Would expect the app to run succesfully.

## Screenshots
No screenshots

## System information
 - OS: MacOS
 - Version of Next.js: 7.0.2

## Additional context

I'm using react hooks! Seems like that might be the cause?

**Comment by James-Quigley** [comment] 2019-01-05 06:12
New issue now after implementing those changes. It builds and deploys okay, and instead of crashing when loading the index, my logic pushes a new route onto the router `/auth/login`, but that 404s. Works locally?

**Comment by FabienGreard** [comment] 2019-01-21 12:46
I'm having the same issue when doploying on github  ? Is it due to react hooks ? 

(also I've been doing #5750 (comment), but got error 500 with TypeError: Object(...) is not a function in log) 

However launching now from my macbook works just fine.

**Comment by ngocketit** [comment] 2019-01-22 12:19
Same problem here

**Comment by ngocketit** [comment] 2019-01-22 12:40
Hmm, it turned out it's my own fault. I wrongly imported a default export.

**Comment by FabienGreard** [comment] 2019-01-22 13:46
Looks likes it was due to using an older version of hooks `react@16.0.6-alpha-2` switching to the 16.8.0-alpha.1 (react@next), everything works just perfectly fine !

Is there any possibility to make it works on a custom server ?

**Comment by timneutkens** [comment] 2019-01-28 12:30
@James-Quigley can you check: https://zeit.co/guides/custom-next-js-server-to-routes/

I'm going to close this issue as the original issue was resolved. In case you run into something similar to this original issue feel free to create a new issue with a clear reproduction.

**Closed by timneutkens** 2019-01-28 12:30 UTC
