### ISSUE TITLE
nextjs 9 typescript typings tsconfig.json issues

### ISSUE THREAD

**Issue by beckend** [zeit/next.js#7997] opened 2019-07-16 14:39 UTC
Nextjs will force modify tsconfig.js and add

```
"include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ]
```

This will exclude all other typings you currently have and is a disaster.
You will now have to manually add every typing into that array for your project, maintaining the tsconfig.json is something you want to do.

**Comment by Timer** [comment] 2019-07-16 14:51
@beckend can you explain? I'm closing this because it seems invalid -- it's explicitly adding all `.ts` files.

Are you sure you didn't mean to set `skipLibCheck` to `false`?

**Closed by Timer** 2019-07-16 14:51 UTC

**Comment by beckend** [comment] 2019-07-18 06:59
@timer let us say you have 2 libs, @types/lodash and @types/jest

None of these applies since nextjs is forcing the include to only certain files, remember that these ** does not include node_modules/@types

**Comment by FDiskas** [comment] 2021-03-12 14:52
Same issue for me.
create simple typescript nextjs project and add npm module for example `calendar-month-array`
and typings are ignored - the only way that worked for me is adding another file at the root `calendar-month-array.d.ts`

**Comment by balazsorban44** [comment] 2022-01-28 15:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
