### ISSUE TITLE
Firefox runs reload animation when navigating (🛠 only in development mode)

### ISSUE THREAD

**Issue by albingroen** [zeit/next.js#12050] opened 2020-04-20 15:42 UTC
# Bug report

## Describe the bug

**This occurred in a next.js app set up by following the [manual setup](https://nextjs.org/docs/getting-started#manual-setup)**

In Firefox, a quick refresh is made when navigating from one page to another.
I am just using 2 simple pages.

1. `index.js`
```javascript
import Link from 'next/link'
...
<Link href="/about" />
...
```

2. `about.js`
```javascript
import Link from 'next/link'
...
<Link href="/" />
...
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to terminal
2. `mkdir next-firefox-refresh-test`
3. `yarn init -y`
4. `yarn add next react react-dom`
5. Add the following to `package.json`
```json
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  }
```
5. `mkdir pages && cd pages && touch index.js && touch about.js`
6. Open project in desired code editor
7. Setup a basic functional component in each file and place a `<Link href="{YOUR_LINK}">{YOUR_PAGE}</Link>` in each component's return statement. Link the pages to each other.
8. `yarn run dev`
9. Open **http://localhost:3000** in **Firefox**

## Expected behavior

When clicking the link to the other page, a navigation without a reload/refresh should happen.

## Screenshots

![next-firefox-unwanted-refresh](https://user-images.githubusercontent.com/19674362/79770240-6f29d180-832d-11ea-9a56-2db19e66a86c.gif)

## System information

- OS: **macOS**
- Browser: **Firefox**
- Version of Next.js: **^9.3.5**
- Version of Node.js: **12.8.0**

### What I have tried

- [x] Adding `as="/"` and `as="/about"`
- [x] Different browsers (works in other browsers)
- [x] Setting up the project using [both methods here](https://nextjs.org/docs/getting-started)

**Comment by ijjk** [comment] 2020-04-20 18:57
Hi, Firefox seems to be showing the reload animation on client side navigations but it is not actually doing a full transition as you can see in the below screen recording the entire page isn't reloaded as the entire network requests aren't reloaded and the console isn't cleared as occurs on a full navigation.

![Kapture 2020-04-20 at 13 55 26](https://user-images.githubusercontent.com/22380829/79788742-bb194e00-830e-11ea-9586-1d8d9d8e147a.gif)

**Comment by albingroen** [comment] 2020-04-20 19:37
> Hi, Firefox seems to be showing the reload animation on client side navigations but it is not actually doing a full transition as you can see in the below screen recording the entire page isn't reloaded as the entire network requests aren't reloaded and the console isn't cleared as occurs on a full navigation.
> 
> ![Kapture 2020-04-20 at 13 55 26](https://user-images.githubusercontent.com/22380829/79788742-bb194e00-830e-11ea-9586-1d8d9d8e147a.gif)

Okay I see,

Is there any way to fix the animation being triggered though? It's... kind of ugly 😕

**Comment by ijjk** [comment] 2020-04-20 20:37
This seems to only occur in development and may be triggered in Firefox from the server-sent events connection used for HMR being disconnected and re-connected. The animation isn't triggered on a production site leveraging Next.js like https://zeit.co

![Kapture 2020-04-20 at 15 36 09](https://user-images.githubusercontent.com/22380829/79797372-bd82a480-831c-11ea-8ee6-bf2362777dd2.gif)

**Comment by Timer** [comment] 2020-05-02 05:57
Closing as this is a Firefox feature that we cannot work around.

**Closed by Timer** 2020-05-02 05:57 UTC

**Comment by balazsorban44** [comment] 2022-01-30 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
