### ISSUE TITLE
Next-workers breaks with next@canary

### ISSUE THREAD

**Issue by brad-decker** [zeit/next.js#7723] opened 2019-07-01 22:31 UTC
# Bug report

## Describe the bug
We had a working worker file prior to the update to canary, afterwords we get a 'window is undefined' error and the functionality of our worker is never fired or fulfilled. We are already on the canary of next-workers which has a similar bug fix.

## To Reproduce
1. add next-workers@canary to next.config.js
2. import a worker file
3. see that it loads correctly
4. upgrade to next@canary
5. visit the page that loads the worker and see window is undefined error.

## Expected behavior

Expect the worker to load correctly

## System information

- OS: MacOS
- Browser: Firefox and Chrome tested
- The version of Next.js: Canary

## Additional context

Didn't know whether to report here or next-plugins

**Comment by gragland** [comment] 2019-07-09 00:30
I'm seeing this same issue on Next 9.0. Was working fine until I upgraded.

**Comment by steida** [comment] 2019-07-14 18:26
It's simply impossible to run web worker with TypeScript with Next 9. Related to https://github.com/zeit/next.js/issues/7873

**Comment by justsee** [comment] 2019-07-16 00:42
If the issue you're seeing is around window being undefined you can fix it temporarily: https://github.com/zeit/next.js/issues/7953#issuecomment-511619743

**Comment by Timer** [comment] 2019-08-09 20:03
Duplicate of https://github.com/zeit/next.js/issues/8071

**Closed by Timer** 2019-08-09 20:03 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 01:26
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
