### ISSUE TITLE
removal of <NextScript /> doesnt ditch next-related scripts

### ISSUE THREAD

**Issue by iamstarkov** [zeit/next.js#4634] opened 2018-06-19 22:58 UTC
# Bug report

## Describe the bug

So there is a `./pages/_document.js` and `<NextScript />`, even if you remove it next.js will include all the bundles. I'm curious why `<NextScript />` seems to not matter. Nothing changes if I remove it or add it back.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to https://with-nextscript-llzwhvgbup.now.sh (it is [with-emotion example](https://github.com/zeit/next.js/tree/canary/examples/with-emotion) deployed as is)
2. Check Network tab in dev tools
3. Scripts are being dowloaded
4. Go to https://without-nextscript-vmfhuqxgbt.now.sh (it is [with-emotion example](https://github.com/zeit/next.js/tree/canary/examples/with-emotion) with removed `<NextScript />` and deployed)
2. Check Network tab in dev tools
3. Scripts are **still** being dowloaded

build process is `next build && next export`

## Expected behavior

No scripts should be in place

## Screenshots
N/A

## System information
 - OS: macOS 10.13.4
 - Browser N/A
 - Version of Next.js: latest

## Additional context

kinda related https://spectrum.chat/thread/3f923307-a694-4af5-b000-517a7e26c0d7
I tried to achieve approach described in this tweet https://twitter.com/_davideast/status/1009112973439393795

**Comment by codinronan** [comment] 2018-06-25 06:09
@iamstarkov This does work; but overriding document and removing `<NextScript>` is not enough. You also have to override Head and remove the link preloads:

https://github.com/zeit/next.js/blob/canary/server/document.js#L91

Not all browsers load these, but Chrome definitely does, so that is why you are seeing them in the network tab.

So either create a custom `Head` component that does not preload, or create a pair of components that capture the information and load it later. I will likely be doing something like this at some point.

**Comment by timneutkens** [comment] 2018-06-25 11:17
I'm planning to change the way we render these scripts (no longer hardcoded) so that you can override them in a custom _document.js

**Comment by iamstarkov** [comment] 2018-06-25 18:44
@timneutkens sounds good, thank you

**Comment by iamstarkov** [comment] 2018-09-06 21:56
@timneutkens, do you have any updates or perhaps if one can help any hints how?

**Comment by iamstarkov** [comment] 2018-11-09 16:16
@jpedroribeiro nice, thank you

**Comment by timneutkens** [comment] 2018-12-31 12:54
Going to close this as duplicate of #5054

Just in order to reduce the surface of duplicate issues 👍

**Closed by timneutkens** 2018-12-31 12:54 UTC
Labels: Type: Enhancement
