### ISSUE TITLE
Flex: 1 - react-native-web

### ISSUE THREAD

**Issue by gHashTag** [zeit/next.js#4450] opened 2018-05-22 16:03 UTC
The main style does not work for react-native-web

```javascript 
const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: 'gold',
    justifyContent: 'center'
  },
  text: {
    alignItems: 'center',
    fontSize: 24
  }
})

export default props => (
  <View style={styles.container}>
    <View style={{ position: 'absolute', top: '50%', right: '15%' }}>
      <Text style={{ fontSize: 80, textAlign: 'right' }} >
        Home
      </Text>
    </View>
  </View>
```

Now so
![2018-05-22 18 58 24](https://user-images.githubusercontent.com/6774813/40374642-24198b7a-5df2-11e8-93cd-bf2a91389fe5.png)

It must be so
![2018-05-22 19 00 37](https://user-images.githubusercontent.com/6774813/40374781-730b4638-5df2-11e8-8612-28de19c8634b.png)

**System information**
 - OS: macOS
 - Browser (if applies) all
 - Version of Next.js: 6.0.3

the solution `height: '100%'` does not fit

How to be?

**Comment by timneutkens** [comment] 2018-05-22 16:05
I'm honestly not sure how this relates to Next.js.

**Comment by gHashTag** [comment] 2018-05-22 16:12
This does not apply to Next.js?
https://github.com/zeit/next.js/tree/canary/examples/with-react-native-web

**Comment by gHashTag** [comment] 2018-05-22 16:17
@dcalhoun

**Comment by dcalhoun** [comment] 2018-05-22 16:20
@gHashTag if you create a full test case with Next.js and `react-native-web` and provide a GitHub URL to the test case, I'd be happy to help debug with you.

**Comment by gHashTag** [comment] 2018-05-22 16:26
@dcalhoun Thank you for your attention to my question. [My code is here.](https://github.com/gHashTag/nextmw)

**Comment by timneutkens** [comment] 2018-05-22 16:44
You didn't provide a clear/concise way to reproduce, nor mentioned the specific example. Hence it looking like a random issue. I'll re-open now that it's clear what you meant.

**Comment by timneutkens** [comment] 2018-05-22 16:48
The reason I closed so fast is that this happens multiple times per day and we have 238 other issues to look after. This is the reason we ask for a full reproduction in the issue template. If no clear reproduction is provided we can't really help with the issue anyway.

**Comment by dcalhoun** [comment] 2018-05-23 01:59
@gHashTag based on what you've shared, your issues are not related to Next.js or `react-native-web`. It is a simple misunderstanding of how the Flexbox spec works. I recommend reading up on flexbox guides, like the [MDN Basic Concepts of Flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox). The parent element of your `container` is not a flex element, so `flex: 1` has no impact on the `container` height.

Unrelated, when using `react-native-web`, you should not declare non-dynamic styles inline. You should always use `StyleSheet.create` for performance gains. Here is an example of your test case updated to use flexbox and `StyleSheet.create`.

```js
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

const styles = StyleSheet.create({
  container: {
    alignItems: 'flex-end',
    backgroundColor: 'gold',
    display: 'flex',
    height: '100%',
    justifyContent: 'center',
  },
  text: {
    marginRight: '15%',
    fontSize: 80,
  },
});

export default props => (
  <View style={styles.container}>
    <Text style={styles.text}>Home</Text>
  </View>
);
```

@timneutkens feel free to close this issue.

**Comment by gHashTag** [comment] 2018-05-23 09:53
@dcalhoun wait please

To verify your approval, I install the project using [react-native init](http://facebook.github.io/react-native/docs/getting-started.html#creating-a-new-application) by instructions from the official documentation.
A ready-made example can be taken [here](https://github.com/gHashTag/testRN)
One into one copy the styles from the application with the help of `react-native init`
```javascript
import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View
} from 'react-native';

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' +
    'Cmd+D or shake for dev menu',
  android: 'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit App.js
        </Text>
        <Text style={styles.instructions}>
          {instructions}
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
```
![simulator screen shot - iphone se - 2018-05-23 at 12 36 51](https://user-images.githubusercontent.com/6774813/40417131-b27f2588-5e87-11e8-92d3-573d4a4b238e.png)

And add them to the application created with the help of Next.js

```javascript
import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View
} from 'react-native';

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' +
    'Cmd+D or shake for dev menu',
  android: 'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

export default props => (
  <View style={styles.container}>
    <Text style={styles.welcome}>
      Welcome to React Native!
    </Text>
    <Text style={styles.instructions}>
      To get started, edit App.js
    </Text>
    <Text style={styles.instructions}>
      {instructions}
    </Text>
  </View>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
    },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
```
![2018-05-23 12 34 19](https://user-images.githubusercontent.com/6774813/40417058-8b13a794-5e87-11e8-901a-3566f2d2f1b4.png)

In one case, the styles were applied, in the second there is not.
Where is the truth?

**Comment by gHashTag** [comment] 2018-05-23 10:08
@dcalhoun  Moreover, I collected a webpack with the latest version  react-native-web 0.6.1
[Source](https://github.com/gHashTag/native-web-starter)

Styles are worked out correctly

![2018-05-23 13 05 03](https://user-images.githubusercontent.com/6774813/40418143-3e361e04-5e8a-11e8-9ad5-c775115ebbec.png)

**Comment by dcalhoun** [comment] 2018-05-23 10:47
Add `height: '100%'` to the the top-level `container` element.

**Comment by gHashTag** [comment] 2018-05-23 11:09
@dcalhoun I knew this from the beginning, 

![2018-05-23 14 08 16](https://user-images.githubusercontent.com/6774813/40420972-cdf190c0-5e92-11e8-8578-e9d39d534af0.png)

But I do not use `height: '100%'` in the projects react-native, which means I will need to refactor the styles every time, but this is not very convenient.

Did I understand correctly that Next.js does not support the style `flex: 1` ?

**Comment by timneutkens** [comment] 2018-05-23 11:38
I'm going to close this as @dcalhoun is right. 👍

**Closed by timneutkens** 2018-05-23 11:38 UTC
Labels: good first issue, help wanted

**Comment by dcalhoun** [comment] 2018-05-23 11:43
Instead of adding `display: flex` to the body, target the `<div id="__next" />` element with CSS. The below is updated code [from the RNW example](https://github.com/zeit/next.js/blob/6.0.3/examples/with-react-native-web/pages/_document.js#L10-L15).

```js
// _document.js
// Force Next-generated DOM elements to fill their parent's height.
const normalizeNextElements = `
  #__next {
    display: flex;
    flex-direction: column;
    height: 100%;
  }
`
```

**Comment by gHashTag** [comment] 2018-05-23 11:48
@dcalhoun 
Thank you! wound up
