### ISSUE TITLE
Ability to access `request.body` as a stream in API routes

### ISSUE THREAD

**Issue by kevva** [zeit/next.js#7661] opened 2019-06-25 12:26 UTC
When handling API requests, we always try to parse the body depending on headers etc (see https://github.com/zeit/next.js/blob/canary/packages/next-server/server/api-utils.ts#L12-L39). However, in some cases you maybe don't want to save the whole body into memory but rather pipe it to some other stream to save memory. It'd be nice if we had access to the original `body` somewhere, or if we introduced an option to turn this off.

I initially discovered the use for this when trying to parse `multipart/form-data` which most libraries expect to be a stream, but there might be other uses for this as well.

**Comment by Janpot** [comment] 2019-06-25 13:19
Apparently there will be an opt-out https://github.com/zeit/next.js/pull/7363#issuecomment-496247449

**Comment by huv1k** [comment] 2019-06-28 09:35
This was fixed with #7686 thx for reporting @kevva

**Closed by huv1k** 2019-06-28 09:35 UTC

**Comment by balazsorban44** [comment] 2022-01-31 13:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
