### ISSUE TITLE
generateBuildId could use hash of content

### ISSUE THREAD

**Issue by zacanger** [zeit/next.js#12087] opened 2020-04-22 00:15 UTC
## Feature request

Because the fallback generateBuildId is a nanoid, cache is busted on bundles even if they haven't changed between builds. It's possible to implement your own, of course, but that behavior seems unexpected for users migrating from using their own custom Webpack config. This results in clients re-fetching client-side JS when it's not necessary.

## Describe the solution you'd like

generateBuildId's fallback if not defined in config could be based on a hash (md5, or whatever) of file contents, and preferably be lowercased as well to avoid issues with hosting on S3, middleware in custom servers, etc.

## Describe alternatives you've considered

I started trying to implement it as a custom generateBuildId but figured I should raise the issue here first in case it's something anyone else is considering.

## Additional context

Example: Two builds run right after each other, no changes:
<img width="763" alt="image" src="https://user-images.githubusercontent.com/12520493/79927628-9b148800-83fd-11ea-94a8-605875b83efa.png">

**Comment by timneutkens** [comment] 2020-04-22 08:22
Duplicate of https://github.com/zeit/next.js/issues/6303

**Closed by timneutkens** 2020-04-22 08:22 UTC

**Comment by zacanger** [comment] 2020-04-22 14:37
Ah, for some reason I missed that when searching, my bad.

**Comment by balazsorban44** [comment] 2022-01-30 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
