### ISSUE TITLE
use node's path in registerPage/__NEXT_REGISTER_PAGE 

### ISSUE THREAD

**Issue by DavidSvetlik** [zeit/next.js#1828] opened 2017-04-28 15:38 UTC
Hello,
it seems that nextjs' router has a trouble on Windows filesystem, generating code like this:

`window.__NEXT_REGISTER_PAGE('/page\subpage', function() { ...`

which ultimately leads to syntax error "Invalid Unicode escape sequence"

I am quite new when it comes to node, so I might be wrong, but fix should be in using nodejs "path" utility and its "normalize" or "resolve" functions to generate paths like these. See https://shapeshed.com/writing-cross-platform-node/#use-path-normalize-to-create-reliable-paths

Thank you,
David S.

**Comment by DavidSvetlik** [comment] 2017-04-28 16:25
Note: I created temporary patch for me, editing /next/dist/server/build/plugins/pages-plugin.js, adding after line 42 this following one: 

`routeName = routeName.replace(/\\/, '/');`

**Comment by arunoda** [comment] 2017-05-02 00:14
@DavidSvetlik we should fix this.

**Comment by orhanmaden** [comment] 2017-05-02 06:09
I had the same issue. Applied your fix and it works now. Thanks!

**Comment by kunal-mandalia** [comment] 2017-05-09 12:31
Can confirm, experiencing same issue with `next@2.3.1` (and `next-redux-wrapper@1.1.2`) on Windows

**Comment by arunoda** [comment] 2017-05-10 06:02
I think this is a duplicate of #1841 and we are fixing it with #1930 
Anyway, thanks for the detailed report.

**Closed by arunoda** 2017-05-10 06:02 UTC
Labels: Type: Bug
