### ISSUE TITLE
[BUG] [with-firebase-authentication] getServerSideProps issues

### ISSUE THREAD

**Issue by kohchihao** [zeit/next.js#12139] opened 2020-04-23 15:27 UTC
# Bug report

## Describe the bug

I just cloned the example project `with-firebase-authentication` and followed the instructions within the `README.md` to setup. After running the command `npm run dev` and went to my browser on `localhost:3000`, I received an error within my terminal. 

```
Error: Error serializing `.user` returned from `getServerSideProps` in "/".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value all together.
```
## To Reproduce

1. Go to https://github.com/zeit/next.js/tree/canary/examples/with-firebase-authentication
2. Followed the setup guide exactly.
3. Go to `localhost:3000` to see the webpage
4. See error within page and terminal

## Expected behavior
Expected to see the the `login` button within the page.

## System information

- OS: `macOS`
- Browser: `Chrome`
- Version of Next.js: `^9.3.3`
- Version of Node.js: `v10.16.3`

**Comment by davegomez** [comment] 2020-04-23 22:35
I saw a PR published by @djanda97 21 days ago to update the `getServerSideProps` function. I wonder if he knows if this ever worked or what is necessary to do and is not explained in the example README?

**Comment by kohchihao** [comment] 2020-04-24 01:31
I may have found a fix for the problem. 

Changing within `getServerSideProps`
```
const user = req && req.session ? req.session.decodedToken : null
```
to 
```
const user = req.session && req.session.decodedToken ? req.session.decodedToken : null
```

seems to fix the issue for me.

**Comment by kohchihao** [comment] 2020-04-24 10:33
@timneutkens Can take on this problem and update the example?

**Comment by timneutkens** [comment] 2020-04-24 11:37
Sure!

**Comment by leerob** [comment] 2020-05-13 02:46
https://github.com/zeit/next.js/pull/12204 was merged, this can be closed 😄

**Closed** 2020-05-13 09:01 UTC
Labels: good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-30 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
