### ISSUE TITLE
Expose named exports (of top-level pages)

### ISSUE THREAD

**Issue by craigsssmith** [zeit/next.js#4505] opened 2018-05-31 10:19 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

We're using next.js and MDX together to build a simple documentation site, and our page components are `.mdx` files. MDX supports meta data, which is attached to MDX components via named exports (see https://github.com/mdx-js/mdx#exports), but the next.js renderer doesn't currently expose anything other than the default export, so there's no way to access this meta data in `_app.js`.

## Describe the solution you'd like

From looking at the next.js source code I think the easiest solution would be to attach the named exports to the Component function, in `server/render.js`:

```js
let [ComponentExports, Document, App] = await Promise.all([
  requirePage(page, {dir, dist}),
  require(documentPath),
  require(appPath)
])

const Component = ComponentExports.default || ComponentExports
Component.exports = ComponentExports
```

...and in `server/build/plugins/pages-plugin.js`:

```js
source.add(`__NEXT_REGISTER_PAGE('${routeName}', function() {
    var comp =
`)
source.add(modules)
source.add(`
    var page = comp.default
    page.exports = comp
    return { page: page }
  })
`)
```

Alternatively, instead of attached the named exports to the default export (the component) they could be passed through the renderer independently, but that would be a bigger change.

## Describe alternatives you've considered

We've looked at tackling the issue by modifying the MDX library, but whilst most of our pages will be `.mdx` files, not all of them will. The solution suggested above would support a consistent approach in both MDX and regular page components.

**Comment by balupton** [comment] 2019-01-27 22:54
This is a fantastic proposal. As I've run into the same quarrel myself.

As your post was 8 months ago, have you been able to figure out a workaround the meantime?

**Comment by balupton** [comment] 2019-01-27 22:57
Seems more details at https://github.com/zeit/next.js/issues/4502

**Comment by kate-hall** [comment] 2019-02-26 19:52
I'm also very interested in this, in trying to work with `remark-frontmatter`, I can't access named exports from _app.js either. Did you ever find a solution, @craigsssmith?

**Comment by nayaabkhan** [comment] 2019-03-26 07:02
Seeing how the Next Blog itself handles this requirement, I've found that they use a HOC called `withPost` in their MDX files:

```js
// post.mdx

// this is the default export that acts as a wrapper component for the document
export default withPost({ title: 'Post 1', author: 'Sonny' })
```

```jsx
// withPost.js

const withPost = meta => ({children}) => (<PostLayout meta={meta}>{children}</PostLayout>)
```

Source: https://github.com/zeit/next-site/blob/master/www/components/blog/with-post.js
Usage: https://github.com/zeit/next-site/blob/master/www/pages/blog/next-8.amp.mdx

Although, the proposed solution to make named exports available in `_app.js` still would be the desired solution IMO. This is for whoever might come looking for a workaround here.

**Comment by Timer** [comment] 2019-12-23 15:36
Next.js has exposed all exports for a few versions. Closing as solved.

**Closed by Timer** 2019-12-23 15:36 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-30 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
