### ISSUE TITLE
Accessing props in `next/dynamic` loading component

### ISSUE THREAD

**Issue by alexlafroscia** [zeit/next.js#7906] opened 2019-07-11 18:11 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I'm trying to use `react-quill` in a Next.js application. The component does not support server-side rendering, so I would like to be able to use `next/dynamic` to avoid rendering it in on the server and only render the editor on the client.

I would like to be able to access the props passed to the component created by `dynamic` in the `loading` component, so that I can render a fallback that is more meaningful than just a loading state, that actually contains the content of the editor.

## Describe the solution you'd like

Assuming that I have a dynamic Quill component that looks something like this:

```jsx
const QuillSSRSafe = dynamic(import('react-quill'), {
  ssr: false
})
```

that takes a `value` property for the content of the editor, I would like to be able to define a loading state like this:

```jsx
const QuillSSRSafe = dynamic(import('react-quill'), {
  ssr: false,
  loading: ({ props: { value } }) => (
    <div dangerouslySetInnerHTML={{ __html: value }} />
  )
})
```

Or something to that effect, so that when I render the component like this:

```jsx
<QuillSSRSafe value="<p>My Content</p>" />
```

Both the loading and loaded state can make use of the props.

## Describe alternatives you've considered

* Not using `next/dynamic` and rendering different components on the client or server based on the presence of `document`. This breaks re-hydration, though, and had some weird effects in the DOM. The issue linked to below has an example of how to handle this without `next/dynamic` but I get an error during rehydration about the DOM not matching correctly.
* Just not having the content of the editor visible while loading. This is not ideal, though, as I would like the transition between the SSR content and the editor to be seamless.

## Additional context

Some more information can be found in this GitHub issue for `react-quill`: https://github.com/zenoamaro/react-quill/issues/122

**Comment by alexlafroscia** [comment] 2019-07-11 18:14
Also, if there isn't a technical reason that this is a bad idea, I would love to put together a PR myself to support it! I would love to have a conversation about whether there's a reason that this is a bad idea, though, first, just in case it's not something that you're interested in supporting.

**Comment by ijjk** [comment] 2019-07-12 20:24
Hi, the main reason at the moment to avoid adding this would be to keep compatibility with `React.lazy` which doesn't support passing props to the fallback/loading component. See [here](https://reactjs.org/docs/code-splitting.html#reactlazy) for more info on the support we're going towards.

**Comment by alexlafroscia** [comment] 2019-07-12 21:44
Gotcha -- so the `next/dynamic` abstraction will get replaced with regular ol' `React.lazy` in the future? What's the approach going forward for opting out of SSR for certain components?

**Comment by ijjk** [comment] 2019-07-13 01:14
That is the current goal yeah, we recently deprecated loading [multiple modules](https://github.com/zeit/next.js/blob/canary/UPGRADING.md#nextdynamic-has-deprecated-loading-multiple-modules-at-once) and plan to incrementally match compatibility with `React.lazy`.  

The future approach for opting out of SSR for certain components is still being discussed, although the  `{ ssr: false }`  option has not been planned for deprecation

**Comment by timneutkens** [comment] 2019-07-13 20:19
Actually we're not removing nor deprecating `next/dynamic`. It's still needed because it's a layer on top to do some extra things like injecting rendered script tags etc. It'll be powered by `React.lazy` in the future though.

**Comment by alexlafroscia** [comment] 2019-07-13 21:16
Do you think it would be worthwhile to explore surfacing the props to the `loading` component, then?

**Comment by timneutkens** [comment] 2019-07-14 10:49
@alexlafroscia I don't think the increased bundle size is worth it, but you could open up a PR and see if it increases bundle size so that we can review.

**Comment by timneutkens** [comment] 2019-08-10 13:55
Going to close this as I don't think the increased bundle size is worth adding the feature.

**Closed by timneutkens** 2019-08-10 13:55 UTC

**Comment by kevin940726** [comment] 2020-12-26 14:05
My use case is that I'm trying to pre-render some contents in the `children` prop while the component is still loading on server-side. Taking a client-side only `<Modal>` component for example. I want to dynamically load the `<Modal>` component on client side, but I also want to render its `children` on the page on server-side to prevent layout shift.

```js
// modal.js
export default function Modal({ children }) {
  // Control the modal state locally here...
  return (
    <>
      <button onClick={openModal}>{children}</button>
      <Dialog isOpen={isOpen} />
    </>
  );
}

// my-page.js
const Modal = dynamic(() => import("./modal"), { ssr: false });

<Modal>Click me to open the modal</Modal>;
```

We can't use `React.lazy` here since we don't support `<Suspense>` and `fallback` components yet.

A temporary hack I can think of is to create a singleton for the `loading` component and check if the current component is the `loading` component or not.

```js
const Loading = () => null;
const Modal = dynamic(() => import("./modal"), {
  ssr: false,
  loading: Loading
});

const children = "Click me to open the modal";
Modal === Loading ? <button>{children}</button> : <Modal>{children}</Modal>;
```

It would be a lot easier and cleaner if we could just access the `props` of the loadable component.

```js
const Modal = dynamic(() => import("./modal"), {
  ssr: false,
  loading: ({ children }) => <button>{children}</button>
});

<Modal>Click me to open the modal</Modal>;
```

Is this something we want to support? Or are we planning to create a `<Suspense>` like API to be able to provide a `fallback` node somehow?

**Comment by Fonger** [comment] 2021-02-02 06:23
We need this because we must specify a height from props to prevent [CLS](https://web.dev/cls/), a Core Web Vitals metrics. Without it, we have to add an extra div outside the dynamic loaded component to extend the height.

**Comment by AlexeyToksarov** [comment] 2021-02-17 11:39
You could try to use something like 
```
const ComponentLoader = (props: any) => {
  const DynamicComponent = dynamic(() => import('path-to-component'), {
    ssr: false,
    loading: () => props.children,
  });
  return <DynamicComponent {...props} />;
};
```

**Comment by kevin940726** [comment] 2021-03-01 06:31
For anyone looking for a workaround, we can use context to pass additional props to the `loading` components.

```jsx
const LoadingValueContext = React.createContext();

const QuillSSRSafe = dynamic(() => import('react-quill'), {
  ssr: false,
  loading: () => {
    const value = React.useContext(LoadingValueContext);
    return <div dangerouslySetInnerHTML={{ __html: value }} />
  }
})

export default ({ value }) => (
  <LoadingValueContext.Provider value={value}>
    <QuillSSRSafe value={value} />
  </LoadingValueContext.Provider>
)
```

I created a helper npm package for this: [`next-dynamic-loading-props`](https://github.com/kevin940726/next-dynamic-loading-props) for more general usages.

**Comment by balazsorban44** [comment] 2022-01-28 16:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
