### ISSUE TITLE
Do you guys have a dockerfile for deploying next.js?

### ISSUE THREAD

**Issue by ojosdegris** [zeit/next.js#121] opened 2016-10-28 01:24 UTC
I have my dokku cluster and would love to deploy it using docker and not buildpacks.

**Comment by ojosdegris** [comment] 2016-10-28 01:37
Overall, I'd say you guys've beat create-react-app by a lot!

**Comment by ojosdegris** [comment] 2016-10-28 03:36
FROM node:6-onbuild
    # Create app directory
    RUN mkdir -p /usr/src/app 
    WORKDIR /usr/src/app
    # Install app dependencies
    COPY package.json /usr/src/app/
    RUN npm install
    # Bundle app source
    COPY . /usr/src/app
    RUN npm run build
    EXPOSE 80

As I said I am trying to run this thing on my dokku, and exposing 80 kinda did the trick but now I can not get letsencrypt to work with this new app. Will keep investigating...

**Comment by impronunciable** [comment] 2016-10-29 11:25
@ojosdegris Thanks for the research. It's really important to be able to deploy this everywhere. In the meanwhile, you can use `now`.

`$ cd your-project`
`$ now`

💥

**Comment by aesopwolf** [comment] 2016-12-01 05:30
I've made *slight* progress on figuring this out, but hit a roadblock.

.dockerignore:
```
node_modules
npm-debug.log
.next
```

Dockerfile:
```Dockerfile
FROM node:argon

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install
RUN npm run build

# Bundle app source
COPY . /usr/src/app

EXPOSE 3000
CMD [ "npm", "start" ]
```

bash:
```bash
$ docker build -t my-nodejs-app .
$ docker run -it -P  --rm --name my-running-app my-nodejs-app
$ open http://localhost:32770/ # port number found using kitematic ui
```

Finally, I get a 404:
![image](https://cloud.githubusercontent.com/assets/6847633/20782805/16e32354-b744-11e6-953c-d342b1a585d4.png)

**Comment by aesopwolf** [comment] 2016-12-01 18:18
Ah, I just switched to `node:6-onbuild` instead of `node:argon` and everything worked fine 🎉

Maybe we can add this to the wiki and close this issue?

**Comment by johannchen** [comment] 2016-12-19 09:16
I used the Dockerfile to build an image.  The image size is 776 MB, is it too big? node:6-onbuild image is already 651 MB. Is there any slimmer node image that works?

**Comment by luisrudge** [comment] 2016-12-19 12:56
@johannchen try node:alpine

**Comment by rauchg** [comment] 2016-12-19 14:46
Should work out of the box with any Node docker image. Next doesn't require anything special on top, other than running `npm run build` and `npm run start`.

**Closed by rauchg** 2016-12-19 14:46 UTC
Labels: Nice to have

**Comment by to-kra** [comment] 2017-07-22 15:35
dont work for me `
> Couldn't find a `pages` directory. Please create one under the project root`

**Comment by sbr464** [comment] 2017-07-29 22:47
I posted this tutorial which has a node-alpine image

https://medium.com/@sbr464/next-js-tutorial-deploy-to-docker-on-google-cloud-container-engine-6b0c19dd8ecb

**Comment by bigbassroller** [comment] 2018-04-25 02:35
Here is my Dockerfile: 
```
FROM node:8.0.0-alpine

#Install bash
RUN apk add --update bash && rm -rf /var/cache/apk/* 

#Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

#Install app dependencies
COPY frontend/package.json /usr/src/app/
RUN npm install --no-optional

#Bundle app source
COPY ./frontend /usr/src/app

EXPOSE 3000
CMD [ "npm", "run", "dev" ]
```
and here is my docker-compose.dev.yml
```
version: '3'

services:
 mongo-db:
  container_name: mongo-db
  image: mongo
  ports:
   - 27017
  volumes:
   - ./env/mongo-db:/data/db
  environment:
   PORT: 27017
 frontend:
  container_name: frontend
  build: 
    context: ./
    dockerfile: DockerfileFrontendDev
  ports:
    - "3000:3000"
  volumes:
    - ./frontend:/usr/src/app/
  environment:
   NODE_ENV: 'development'
   PORT: 3000
 api-server:
  container_name: api-server
  build: 
    context: ./
    dockerfile: DockerfileAPIDev
  ports:
    - "4000:4000"
  volumes:
    - ./api-server:/usr/src/app/
  links:
    - mongo-db
  environment:
   NODE_ENV: 'development'
   MONGO_URL: mongodb://mongo-db:27017/mongo-db
   PORT: 4000
```

Everything works with Next and api on the frontend, but I am not able to reach the api from within the container. I get this error: 
```
request to http://localhost:4000/api/users failed, reason: connect ECONNREFUSED 127.0.0.1:4000
FetchError: request to http://localhost:4000/api/users failed, reason: connect ECONNREFUSED 127.0.0.1:4000
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:399:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

**Comment by beeman** [comment] 2019-03-14 05:39
This is what works for me. The issue with `Couldn't find a pages directory. Please create one under the project root` was caused by the `postinstall` script that tried to run `next build`, but at a moment that the files were not copied in yet.

My Dockerfile:

```
FROM node:11-alpine

WORKDIR /workspace

COPY package.json yarn.lock /workspace/

RUN yarn install

COPY . .

RUN yarn build

CMD ["yarn", "start"]
```

**Comment by Meemaw** [comment] 2019-10-13 08:44
```
FROM node:12-alpine as build

COPY . /src
WORKDIR /src

RUN npm ci
RUN npm run build
RUN npm prune --production

FROM node:12-alpine

WORKDIR /usr/app

COPY --from=build /src/node_modules /usr/app/node_modules
COPY --from=build /src/package.json /usr/app/package.json
COPY --from=build /src/.next /usr/app/.next

ENV NODE_ENV production

CMD ["npm", "start"]
```

**Comment by whs-dot-hk** [comment] 2020-02-04 05:53
@Meemaw Thank you very much

Below is my slightly modified version
```
FROM node:13.7.0-alpine3.11 as build

COPY . .

ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --production

RUN npm build

FROM node:13.7.0-alpine3.11

COPY --from=build package.json package.json
COPY --from=build package-lock.json package-lock.json
COPY --from=build .next .next

ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --production

EXPOSE 3000

CMD npm start
```

**Comment by dickamin** [comment] 2020-05-06 19:51
@whs-dot-hk Thank you. 
 
Added public folder

`
FROM node:12-alpine as build

COPY . .

ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --production

RUN npm run build

FROM node:12-alpine

COPY --from=build package.json package.json
COPY --from=build package-lock.json package-lock.json
COPY --from=build .next .next
COPY --from=build public public

ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --production

EXPOSE 3000

CMD npm start
`

**Comment by desaijay315** [comment] 2020-06-17 18:02
**Here is my running application Dockerfile** Create this inside the root folder - 

FROM node:12

# Create app directory
RUN mkdir /var/movable/ && mkdir /var/movable/app
WORKDIR /var/movable/app

# Installing dependencies
COPY package*.json /var/movable/app/
RUN npm install

# Copying source files
COPY . /var/movable/app


# Building app
RUN npm run build

# Running the app
CMD "npm" "run" "start"

**Comment by knsakib** [comment] 2020-08-03 23:23
none of these is working. container does not have .next folder inside.

**Comment by toruta39** [comment] 2020-10-19 06:04
Thanks to @whs-dot-hk and @dickamin

Adding `next.config.js` (e.g. if you use `basePath` for routing)

```
FROM node:14-alpine as build

COPY . .

ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --production

RUN npm run build

FROM node:14-alpine

COPY --from=build package.json package.json
COPY --from=build package-lock.json package-lock.json
COPY --from=build next.config.js next.config.js
COPY --from=build .next .next
COPY --from=build public public

ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --production

EXPOSE 3000

CMD npm start
```

**Comment by malixsys** [comment] 2021-05-17 20:36
With pruning
```
FROM node:14-alpine as BUILD_IMAGE

WORKDIR /app

COPY package.json package-lock.json ./

# install dependencies
RUN npm install

COPY . .

# build
RUN npm run build

# remove dev dependencies
RUN npm prune --production

FROM node:14-alpine

WORKDIR /app

# copy from build image
COPY --from=BUILD_IMAGE /app/package.json ./package.json
COPY --from=BUILD_IMAGE /app/node_modules ./node_modules
COPY --from=BUILD_IMAGE /app/next.config.js next.config.js
COPY --from=BUILD_IMAGE /app/.next ./.next
COPY --from=BUILD_IMAGE /app/public ./public

EXPOSE 3000
CMD ["npm", "start"]
```

**Comment by balazsorban44** [comment] 2022-01-28 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
