### ISSUE TITLE
window.scrollTo(0, 0) doesn't work

### ISSUE THREAD

**Issue by markolofsen** [zeit/next.js#5313] opened 2018-09-27 15:25 UTC
# Bug report
I added this code to _app.js
```
Router.events.on('routeChangeComplete', () => {
  NProgress.done()
  window.scrollTo(0, 0)
})
```

Everything ok, but scroll doesn't work

**Comment by timneutkens** [comment] 2018-09-27 15:29
`next/link` already implements this behavior, why'd you need to trigger it another time 🤔

**Comment by markolofsen** [comment] 2018-09-27 15:59
Nothing, after each transition my page doesn't scroll to top. I'm using Nextjs Canary 7*

**Comment by timneutkens** [comment] 2018-09-27 16:03
Can you create a minimal reproduction?

**Comment by rabbititus** [comment] 2018-09-28 04:05
@timneutkens Is there any solution for the scroll position; when you refresh the page or click to history back button on your browser?

**Comment by timneutkens** [comment] 2018-09-28 09:41
I'm not sure what you're referring to exactly, could you create a minimal reproduction?

**Comment by echoulen** [comment] 2018-10-03 05:17
My project is working fine
the example in recompose 
```
import Router from "next/router";
import {compose, lifecycle} from "recompose";

export const withScrollToTop = compose(
  lifecycle({
    componentDidMount() {
      const previousCallback = Router.onRouteChangeComplete;
      Router.onRouteChangeComplete = (url: string) => {
        if (typeof previousCallback === "function") {
          previousCallback(url);
        }

        window && typeof window === "object" && window.scrollTo && typeof window.scrollTo === "function" && window.scrollTo(0, 0);
      };
    },
  }),
);

```

**Comment by timneutkens** [comment] 2018-10-17 11:48
Going to close this

**Closed by timneutkens** 2018-10-17 11:48 UTC

**Comment by NikoMontana** [comment] 2019-07-01 15:26
> Can you create a minimal reproduction?

@timneutkens Could you provide a minimal reproduction of a working example? Because `next/Link` is not scrolling to top for me either.

[Reference Code](https://github.com/zeit/next.js/issues/7594)

**Comment by balazsorban44** [comment] 2022-01-31 13:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
