### ISSUE TITLE
bundled successfully, waiting for typecheck results

### ISSUE THREAD

**Issue by chj-damon** [zeit/next.js#8105] opened 2019-07-25 12:18 UTC
# Bug report

## Describe the bug

I ran into this issue because it was exactly what @kachkaev describled:
`[ info ]  bundled successfully, waiting for typecheck results ...`

I have two pages: index.tsx, about/index.tsx:

```tsx
index.tsx:
export default () => (
  <div>
    <Link href="/about"><a>got to about page</a></Link>
  </div>
);

about/index.tsx:
export default () => (
  <div>
    this is about page.
  </div>
);
```
it works fine. But if I add some style in about.tsx:
```tsx
import styles from './index.module.less';
export default () => <div className={styles.content}>123</div>;
```
index.module.less:
```css
.content {
  color: red;
}
```
I cannot link to about page anymore. and I got this info in the terminal:
```
[ wait ]  compiling ...
[ info ]  bundled successfully, waiting for typecheck results ...
[ event ] disposing inactive page(s): /next/dist/pages/_error, /about
```

My next.config.js is:
```js
const withLess = require('@zeit/next-less');
const path = require('path');

module.exports = withLess({
  cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: '[name]___[local]___[hash:base64:5]',
  },
  lessLoaderOptions: {
    javascriptEnabled: true,
  },
  webpack(config) {
    config.module.rules.push({
      test: /\.js$/,
      enforce: 'pre',
      include: [path.resolve('components'), path.resolve('pages')],
    });
    config.devtool = 'cheap-module-inline-source-map';
    config.resolve.alias = {
      ...config.resolve.alias,
      '@pages': path.join(__dirname, '.', 'pages'),
      '@components': path.join(__dirname, '.', 'components'),
    };
    return config;
  },
});

```
## System information

- OS: macOS Mojave 10.14.5
- Browser: Chrome
- Version of Next.js: 9.0.2

**Comment by Timer** [comment] 2019-07-25 13:31
Sorry, but without a full/complete reproduction provided via a GitHub repository there's nothing we can do to help.

**Comment by chj-damon** [comment] 2019-07-26 07:43
@Timer sorry about that. 
I created a repository: https://github.com/chj-damon/nextjs-bug-reproduce

**Comment by ijjk** [comment] 2019-07-28 21:19
Hi @chj-damon, this appears to be related to https://github.com/zeit/next-plugins/issues/282 and https://github.com/zeit/next.js/issues/7886

I'm gonna close this in favor of the previously mentioned issues. If you find it's not related to those issues please reply with additional information.

**Closed by ijjk** 2019-07-28 21:19 UTC

**Comment by balazsorban44** [comment] 2022-01-31 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
