### ISSUE TITLE
Does next support component structure caching?

### ISSUE THREAD

**Issue by yangchongduo** [zeit/next.js#5032] opened 2018-08-26 06:06 UTC
Does next support component structure caching?

react-component-caching

**Comment by timneutkens** [comment] 2018-08-26 13:27
If you mean https://github.com/rookLab/react-component-caching this is not supported currently as we don't allow alternative `renderToString` implementations. 

Duplicate of #1334

**Closed by timneutkens** 2018-08-26 13:27 UTC
