### ISSUE TITLE
Next.js 9 doesn't work with Antd on build

### ISSUE THREAD

**Issue by phakphumi** [zeit/next.js#7957] opened 2019-07-14 13:41 UTC
When I try to run `next build` on the docker container below error appear.

`
> Build error occurred
{ /usr/src/app/node_modules/antd/lib/style/index.less:1
@import './themes/default';
^
`
`
SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/src/app/node_modules/antd/lib/button/style/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) type: 'SyntaxError', '$error': '$error' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

By the way, this error doesn't appear when I run next start.

Any idea.

**Comment by kachkaev** [comment] 2019-07-14 13:52
Please share a reproduction. Here is the official example, with which you may want to check first: https://github.com/zeit/next.js/tree/canary/examples/with-ant-design

**Comment by phakphumi** [comment] 2019-07-14 14:09
For reproduction, I use [this package](https://github.com/sdli/next-antd-aza-less) and have the configuration follow read me.

I will try to apply the official solution to my project and will update to you.

**Comment by phakphumi** [comment] 2019-07-14 16:54
The official example works fine on my project but unfortunately, the code in the example file can't enable cssModule. Enable cssModule cause all Antd styling disappear.

Reproduction:
- Just add `cssModules: true` in withCss option

My code within next.config.js

`module.exports = {
  ...withSass(withCss({
    cssModules: true,
    cssLoaderOptions: {
      importLoaders: 1,
      localIdentName: '[local]___[hash:base64:5]',
    },
    lessLoaderOptions: {
      javascriptEnabled: true,
      modifyVars: themeVariables, // make your antd custom effective
    },
    webpack: (config, { isServer }) => {
      if (isServer) {
        const antStyles = /antd\/.*?\/style\/css.*?/
        const origExternals = [...config.externals]
        config.externals = [
          (context, request, callback) => {
            if (request.match(antStyles)) return callback()
            if (typeof origExternals[0] === 'function') {
              origExternals[0](context, request, callback)
            } else {
              callback()
            }
          },
          ...(typeof origExternals[0] === 'function' ? [] : origExternals),
        ]
  
        config.module.rules.unshift({
          test: antStyles,
          use: 'null-loader',
        })
      }
      return config
    },
  })),
}`

@kachkaev

**Comment by luffyZh** [comment] 2019-07-15 03:00
The same question, Next 9 with antd less occur the same error in the production.

**Comment by macalinao** [comment] 2019-07-15 04:15
we have the same problem

**Comment by Viin-zx** [comment] 2019-07-16 09:33
we have the same problem

**Comment by timneutkens** [comment] 2019-07-17 13:09
I'm going to close this issue as it doesn't follow the issue template and isn't directly related to the example, as said the example seems to work.

**Closed by timneutkens** 2019-07-17 13:09 UTC

**Comment by videni** [comment] 2019-12-09 03:21
@luffyZh , @phakphumi,  how did you solve this problem? the example works, however I did everything as the example , it simply just doesn't work. I also did as @grrowl said, I checked the `.babelrc` and the less configuratoin lots of times. 

.babelrc
```
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    ["relay", { "artifactDirectory": "./src/__generated__" }],
    ["import", { "libraryName": "antd", "style": true }]
  ]
}

```

next.config.js
```
require('dotenv').config();
const lessToJS = require('less-vars-to-js');

const slash = require('slash');
const withLess = require('@zeit/next-less');
const fs = require('fs');
const path = require('path');
const Dotenv = require('dotenv-webpack');

const withImages = require('next-images');

const themeVariables = lessToJS(
  fs.readFileSync(path.resolve(__dirname, './src/themes/default.less'), 'utf8')
);

const config = withImages(withLess({
  lessLoaderOptions: {
    javascriptEnabled: true,
    modifyVars: themeVariables
  },
  webpack: (config, { isServer }) => {
    config.plugins.push(
      new Dotenv({
        path: path.join(__dirname, '.env'),
        systemvars: true,
      }),
    );

    config.resolve.alias = {
      ...config.resolve.alias,
      'react-jsonschema-form': '@vidyvideni/react-jsonschema-form',
      '@': path.resolve(__dirname, 'src'),
    };

    config.module.rules.push({
      test: /\.mjs$/,
      include: /node_modules\/react-relay-network-modern/,
      type: 'javascript/auto',
    });
    config.resolve.extensions.push('.mjs');

    if (isServer) {
      const antStyles = /antd\/.*?\/style.*?/;
      const origExternals = [...config.externals];
      config.externals = [
        (context, request, callback) => {
          if (request.match(antStyles)) return callback();
          if (typeof origExternals[0] === 'function') {
            origExternals[0](context, request, callback);
          } else {
            callback()
          }
        },
        ...(typeof origExternals[0] === 'function' ? [] : origExternals),
      ];

      config.module.rules.unshift({
        test: antStyles,
        use: 'null-loader',
      });
    }

    return config;
  },

  cssLoaderOptions: {
    modules: true,
    getLocalIdent: (
      context,
      _,
      localName,
    ) => {
      if (
        context.resourcePath.includes('node_modules') ||
        context.resourcePath.includes('ant.design.pro.less') ||
        context.resourcePath.includes('global.less')
      ) {
        return localName;
      }

      const match = context.resourcePath.match(/src(.*)/);

      if (match && match[1]) {
        const antdProPath = match[1].replace('.less', '');
        const arr = slash(antdProPath)
          .split('/')
          .map((a) => a.replace(/([A-Z])/g, '-$1'))
          .map((a) => a.toLowerCase());

        return `acme${arr.join('-')}-${localName}`.replace(/--/g, '-');
      }

      return localName;
    },
  }
}));

module.exports = {
  useFileSystemPublicRoutes: false,
  ...config
};

```

**Comment by luffyZh** [comment] 2019-12-09 03:35
@videni emm...my scaffold is [next-antd-scaffold](https://github.com/luffyZh/next-antd-scaffold).it works, can go&&see.

**Comment by videni** [comment] 2019-12-09 06:01
@luffyZh , your scaffold is not helpfull for me, I am just need to know 

1. Why less files of `Antd` matching `/antd\/.*?\/style.*?/`  are excluded  from server webpack. 

2.  Since they are excluded using `null-loader`, why they are still loaded?  that is why I have following error.
```
/Users/john/www/acme-admin-ui/node_modules/antd/lib/style/index.less:1
@import './themes/index';
^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Object.require.extensions.<computed> [as .js] (/Users/john/www/acme-admin-ui/node_modules/ts-node/src/index.ts:529:44)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/john/www/acme-admin-ui/node_modules/antd/lib/layout/style/layout/style/index.jsx:1:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Object.require.extensions.<computed> [as .js] (/Users/john/www/acme-admin-ui/node_modules/ts-node/src/index.ts:529:44)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/john/www/acme-admin-ui/node_modules/@ant-design/pro-layout/lib/BasicLayout.js:10:1)
```

**Comment by j-mcgregor** [comment] 2021-03-24 12:47
Was there a fix for this? The link just takes me down a rabbit-hole of similar issues but no solutions

**Comment by dannysofftie** [comment] 2021-07-19 06:37
This is all you need, just change how `.less` files are imported. Add/change `webpackImporter` to false to load `.less` files with `less-loader`.  Also, remember to install `style-loader`, `css-loader` `less` & `less-loader` as devDependencies

```js
 {
    test: /\.less$/i,
    use: [
      'style-loader',
      'css-loader',
      {
        loader: 'less-loader',
        options: {
          lessOptions: {
            javascriptEnabled: true,
            webpackImporter: false,
          },
        },
      },
    ],
}
```

**Comment by balazsorban44** [comment] 2022-01-28 02:15
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
