### ISSUE TITLE
Files outside of app directory will not be transpiled

### ISSUE THREAD

**Issue by Swatinem** [zeit/next.js#5666] opened 2018-11-13 15:14 UTC
# Bug report

## Describe the bug

I have a monorepo usecase, where I want to share code between the next app and other modules that are located outside of the app folder.

It will end up with this error: 
```
{ Error: (client) ../foo.ts 1:0
Module parse failed: The keyword 'interface' is reserved (1:0)
You may need an appropriate loader to handle this file type.
> interface Foo {
|   prop: string;
| }
 @ ./pages/index.tsx 4:0-28 8:5-8
 @ multi ./pages/index.tsx
```

## To Reproduce

I have set up a simple repo here, based on the next-typescript example:

https://github.com/Swatinem/next-monorepo/tree/master

## Expected behavior

Whatever I import should be transpiled like everything else, period.

## System information
 - OS: linux
 - Version of Next.js: next@7.0.2

## Additional context

Related issue (possibly a duplicate?): https://github.com/zeit/next-plugins/issues/234
Also related maybe: 
* https://github.com/zeit/next.js/issues/706
* https://github.com/zeit/next.js/issues/3018

**Comment by timneutkens** [comment] 2018-11-13 18:12
Sounds like this is a duplicate of https://github.com/zeit/next.js/issues/706

**Comment by jakemmarsh** [comment] 2019-02-08 19:48
Thanks @Swatinem! Made it slightly more resilient by searching for the relevant loader rather than relying on index:

```
config.module.rules.forEach((rule) => {
    const ruleContainsTs = rule.test.toString().includes('ts|tsx');

    if (ruleContainsTs && rule.use && rule.use.loader === 'next-babel-loader') {
      rule.include = undefined;
    }
  });
```

**Comment by felixmosh** [comment] 2019-02-26 14:45
@Swatinem, Thanx for the workaround I've spent few hours till found this thread.

**Comment by revskill10** [comment] 2019-02-26 15:14
For easier debug, you can `console.log` the `config` and find out the exact ts-loader, then modify it.

**Comment by timneutkens** [comment] 2019-03-05 16:40
Going to track this in #706

**Closed by timneutkens** 2019-03-05 16:40 UTC

**Comment by Jonasdoubleyou** [comment] 2019-08-27 22:41
Apparently someone changed the regex in the rules to `/\.(tsx|ts|js|mjs|jsx)$/`, thus the fix suggested by @jakemmarsh only works if you check for `.includes("tsx|ts")` ...

**Comment by jescalan** [comment] 2019-10-31 21:54
I feel like this should be re-opened because it's a different issue. This one is for files outside of the nextjs root, and #706 is for files within the nextjs root, but in the `node_modules` folder.

**Comment by steida** [comment] 2019-10-31 22:32
I seems that transpileModules works for me.

```ts
module.exports = withBundleAnalyzer(
  withTranspileModules({
    // To force Next.js to transpile code from other workspace packages.
    // https://github.com/martpie/next-transpile-modules
    transpileModules: ['evolu'],
    // We need server for local next export for integration tests.
    // We can detects ZEIT Now runtime via AWS_REGION.
    target: process.env.AWS_REGION ? 'serverless' : 'server',
    // Enforce relative paths for integration tests.
    // https://github.com/zeit/next.js/issues/2581
    assetPrefix: './',
  }),
);
```

**Comment by brysonandrew** [comment] 2020-05-15 12:17
This seemed like a cleaner solution. Specifying the path to wherever your external files are.

`
config.module.rules.forEach((rule) => {
                const isTsRule = rule.test && rule.test.toString().includes('tsx|ts');

                if (isTsRule && rule.use && rule.use.loader === 'next-babel-loader') {
                    rule.include = [
                        path.join(__dirname, 'path', 'to', 'external', 'folder'),
                        ...rule.include
                    ];
                }
            });
`

**Comment by brysonandrew** [comment] 2020-05-15 12:32
```
config.module.rules.forEach((rule) => {
    const isTsRule = rule.test && rule.test.toString().includes('tsx|ts');
    if (isTsRule && rule.use && rule.use.loader === 'next-babel-loader') {
        rule.include = [
            path.join(__dirname, 'path', 'to', 'external', 'folder'),
            ...rule.include
        ];
    }
});
```

**Comment by Maycon-Santos** [comment] 2020-05-30 14:31
@jakemmarsh This works for me:
```javascript
const ruleString = rule.test ? rule.test.toString() : ''
const ruleContainsTs = /tsx?/.test(ruleString)

if (ruleContainsTs && rule.use && rule.use.loader === 'next-babel-loader') {
  rule.include = undefined
}
```

**Comment by desmap** [comment] 2020-08-19 11:44
Does Next dev mode rebuilds on change of the external files?

**Comment by ar7casper** [comment] 2020-08-19 12:30
@Maycon-Santos @Swatinem 

Any chance you can share your next.config.js file?
For some reason, none of your solutions work for me.

I use a monorepo as well, got a shared lib of components, and it fails for the exact same reason.

I followed the instructions on - https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config and added your logic. No success.... :/

Thanks

**Comment by jescalan** [comment] 2020-08-19 17:35
We made this library to do this - it's not 100% reliable but it's pretty good.

https://github.com/hashicorp/next-remote-watch

**Comment by gfortaine** [comment] 2021-01-20 09:15
@brysonandrew It looks like that we would also need to look for the loader `'next-babel-loader'` in case of use is an array :

``` js 
  const hasNextBabelLoader = (r) => {
    if (Array.isArray(r.use)) {
      return r.use.find(l => l?.loader === 'next-babel-loader')
    }

    return r.use?.loader === 'next-babel-loader';
  }

  if (/(ts|tsx)/.test(String(rule.test)) && hasNextBabelLoader(rule)) {
    rule.include = [
      ...rule.include,
      path.join(__dirname, '..', 'portal')
    ];

    return rule;
  }

**Comment by spanwair** [comment] 2021-02-21 20:40
I made even more simple. The fact is that `rule.use` can be Object or Array<Object>. Which fail to include shared files to all `tsx|ts` tests.

```module.exports = {
  webpack: (config) => {
    config.module.rules.forEach((rule) => {
      if (
        rule.test && rule.test.toString().includes('tsx|ts')
      ) {
        rule.include = [
          ...rule.include,
          require('path').join(__dirname, '../packages/shared'),
        ];
      }
    });
    return config
  },
}

**Comment by MythicManiac** [comment] 2021-04-04 06:03
`next-transpiled-modules` didn't work for us in it's 5.x or 6.x versions, but 4.1.0 seems to be working. They seem to have swapped to [enhanced-resolve](https://www.npmjs.com/package/enhanced-resolve) between versions 4 and 5, which at least when trying to resolve local packages according to the monorepo setup found at https://github.com/NiGhTTraX/ts-monorepo does not work.

The solution by @spanwair did work however 👍

**Comment by cliffordfajardo** [comment] 2021-04-10 23:07
NextJS introduced an experimental option to allow imports from outside the project directory. I tried it out in our mono repo and was able to get it to work

[#22867](https://github.com/vercel/next.js/pull/22867)

**Comment by taletski** [comment] 2022-01-23 10:48
If if you attempt to transpile `.tsx` files as well, you might get the following error `ModuleNotFoundError: Module not found: Error: Can't resolve 'react/jsx-dev-runtime' in ...`

In this case, Webpack fails to import `react/jsx-dev-runtime` from outside of the working dir.

The solution was to add Webpack aliases for the missing modules:
```JS
config.resolve.alias["react/jsx-runtime"] = require.resolve("react/jsx-runtime")
config.resolve.alias["react/jsx-dev-runtime"] = require.resolve("react/jsx-dev-runtime")
// you may want to add more depending on your use case (take it from the error description)
```
so that now my full config is:
```JS
// next.config.js
module.exports = {
  experimental: {
    externalDir: true,
  },
  webpack: config => {
    config.resolve.alias["react/jsx-runtime"] = require.resolve("react/jsx-runtime")
    config.resolve.alias["react/jsx-dev-runtime"] = require.resolve("react/jsx-dev-runtime")
    return config
  },
}
```
