### ISSUE TITLE
`ENOENT` error in `renderToHTML` should pass `err` to error page

### ISSUE THREAD

**Issue by vjpr** [zeit/next.js#5625] opened 2018-11-07 19:28 UTC
```
    try {
      const out = await renderToHTML(req, res, pathname, query, this.renderOpts)
      return out
    } catch (err) {
      if (err.code === 'ENOENT') {
        res.statusCode = 404
        return this.renderErrorToHTML(null, req, res, pathname, query)
      } else {
```

See also `renderScriptError`
```
if (error.code === 'ENOENT' || error.message === 'INVALID_BUILD_ID') {
```

---

1. The `ENOENT` check should be replaced by a named error. Its not always going to be a 404. Sometimes it might be a bug, and we need the stack trace to work out what is going on - like in https://github.com/zeit/next.js/issues/5620. If a page doesn't exist, the error would be throw far away in `renderToHTML > doRender > requirePage > getPagePath`.

2. There should be a better check for a 404 vs. other ENOENTs.

3. We should always return the error for 404s.

`return this.renderErrorToHTML(null, req, res, pathname, query)`. 

Silencing errors is bad. How to handle a 404 should be taken care of inside `renderErrorToHTML`

4. `err` should be made available outside of server-side `renderToHTML`.

See https://github.com/zeit/next.js/issues/3452.

**Comment by timbielawski** [comment] 2018-12-05 08:29
I have added a errorCodeMapper, the fork is here: https://github.com/timbielawski/next.js/tree/add/custom-error-handler

I want to see what the feeling is and then I will do a PR

> Add a errorCodeMapper for the handleRequest and renderToHTML methods.
The purpose is allow the rendered app to throw errors which can be mapped to http error codes, which then results in the correct error html being rendered in Nextjs

Currently Nextjs will render a 500 for any error thrown in rendered app

In my app I add the error code mapper
`const nextLoader = next({ dev, quiet, errorCodeMapper });`

Then i can map any error that my app throws is to a http code so the correct error is returned from Nextjs

`const { CONTENT_404, THEME_404, SERVER_500 } = require("../constants/errors");

const errorCodeMapper = err => {
    switch (err) {
        case CONTENT_404:
        case THEME_404:
            return 404;
        default:
            return 500;

    }
}

module.exports = errorCodeMapper;`

**Comment by timneutkens** [comment] 2019-11-09 23:34
I'm going to close this as this has been open for a year and there hasn't been a contribution to solve it. It would require a relatively large refactor of how the server implementation works so I don't feel like it's worth exploring rewriting it just for this specific case.

**Closed by timneutkens** 2019-11-09 23:34 UTC
Labels: Type: Enhancement

**Comment by balazsorban44** [comment] 2022-01-30 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
