### ISSUE TITLE
URL does not update in Chrome iOS v64

### ISSUE THREAD

**Issue by andrewb** [zeit/next.js#7516] opened 2019-06-05 21:28 UTC
# Bug report

## Describe the bug

There appears to be a routing bug in Chrome for iOS v59–64 (and possibly other versions) since the 8.1.0 release. The URL does not update after navigating between pages when using a standard `<a>` tag, however the correct template renders. `window.location.href` (and similar) do not update either.

Note, the issue does not occur when using `Link` and client side routing.

I was able to reproduce this error after a user report using BrowserStack and iOS Chrome 64. The user reporting the issue uses iOS Chrome 59. I am not sure how many versions are affected, however iOS Chrome 74 does not show the issue.

## To Reproduce

I have created a basic repo showing the bug. See https://github.com/andrewb/next-ios-chrome-bug.

To test `yarn install` and `yarn run dev` and load the app in *Chrome for iOS v64*.

Test 1:
- In a new tab, navigate to the index page
- Click the link to "Foo" – this is a standard `<a>` tag with a `href` of `/foo`
- Note the "Foo" template renders, however the page URL does not update and the value of `window.location.href` rendered by the template does not show `/foo` – it is still the URL of the index page.
- Click the link to "Bar" and observe the same issue

Test 2:
- In a **new** tab load `/foo` before any other page. Note the URL and value of `window.location.href` in the template.
- Click the "Home" or "Bar" links and note that the URL is still `/foo`

Additionally you can see this behavior on https://zeit.co/. Go to `https://zeit.co/` in iOS Chrome v64. Update the URL bar to `https://zeit.co/now` and load the page. The correct page will load, but the URL will remain as `https://zeit.co/`.

## Expected behavior

The URL should update after following each link. The correct behavior is observed in iOS Safari, MacOS Chrome, etc.

The correct behavior is also observed in iOS Chrome v64 if the repo is downgraded to Next 8.0.4.

## Screenshots

Video of test 1: https://www.dropbox.com/s/ea2utnc1cehgtg1/t-1.mov?dl=0
Video of test 2: https://www.dropbox.com/s/e5ykwce3waymcx7/t-2.mov?dl=0
Video of same code downgraded to Next 8.0.4: https://www.dropbox.com/s/0b5dh8zbvadu1ez/t-3.mov?dl=0

## System information

- OS: iOS
- Browser Chrome v64
- Version of Next.js: 8.1.0

## Additional context

Please let me know if I can provide more information.

**Comment by andrewb** [comment] 2019-06-05 23:15
Looks like this behavior started in https://github.com/zeit/next.js/releases/tag/v8.0.5-canary.28

**Comment by andrewb** [comment] 2019-06-06 14:06
Appears to be due to https://github.com/zeit/next.js/blob/canary/packages/next-server/lib/router/router.ts#L120-L123

**Comment by eribean** [comment] 2019-07-03 04:24
This is affecting me as well, does google have any plans to fix this?

**Comment by ijjk** [comment] 2019-07-04 02:00
Hi, I'm not able to reproduce using Chrome iOS on BrowserStack. If it's fixed in modern versions of Chrome on iOS and the user should be updating their Chrome automatically this doesn't exactly seem like a Next.js bug more so a previous Chrome on iOS bug.

**Comment by andrewb** [comment] 2019-07-09 15:14
Thanks @ijjk. Browserstack has updated their Chrome iOS version so I can no longer reproduce the issue either.

**Comment by eribean** [comment] 2019-07-09 16:33
Just checked and my issues are gone too.

**Closed** 2019-07-10 18:43 UTC

**Comment by balazsorban44** [comment] 2022-01-31 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
