### ISSUE TITLE
Put content of _app inside common while building webpack

### ISSUE THREAD

**Issue by PetrSnobelt** [zeit/next.js#5633] opened 2018-11-08 12:49 UTC
# Feature request
While I'm analyzing my bundle I realize that there are some packages (in my case huge momentjs with full languages) in both `_app` and in some pages. 
IMHO there are no reasons to generate _app bundle. Merging the content of _app with common would have this benefits:
 - remove 1 HTTP request for app bundle
 - packages included in app bundle could be removed from pages    

## Describe the solution you'd like
Update internal webpack config to "merge" `_app` and `commons` chunks

## Describe alternatives you've considered
In my case, I moved moment co common by adding something like this to next.config, but would be nice if it works out of the box.

```
// Add moment to commons
if (config.optimization.splitChunks.cacheGroups) {
  config.optimization.splitChunks.cacheGroups.moment = {
    test: /\/node_modules\/moment/,
    name: "commons",
    chunks: "all",
  }
}
```

**Comment by timneutkens** [comment] 2019-03-09 15:45
Duplicate of #5923

**Closed by timneutkens** 2019-03-09 15:45 UTC
