### ISSUE TITLE
AWS API Gateway stages and nextjs uri base path

### ISSUE THREAD

**Issue by danielcondemarin** [zeit/next.js#6447] opened 2019-02-25 23:28 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
Amazon API Gateways have a stage in their URLs:

E.g. https://vbe6aad5c.execute-api.us-east-1.amazonaws.com/prod/home

This breaks next8 serverless page deployments routing because there doesn't seem to be a way to configure nextjs with a basePath (/prod in this case). 

## Describe the solution you'd like
I would like to be able to configure nextjs with a uri `basePath` which works with next's routing. 

Could be something like:

_next.config.js_
```
module.exports = {
  uriBasePath: '/prod'
}
```
Note `assetPrefix` doesn't work here because it applies only to static files AFAIK.

## Describe alternatives you've considered
Using a custom domain for the AWS API GW would solve the problem as it removes the /{stage} from the URL.

**Comment by timneutkens** [comment] 2019-03-05 16:41
Duplicate of #4998

**Closed by timneutkens** 2019-03-05 16:41 UTC
