### ISSUE TITLE
Router query object not immediately populated from dynamic route params

### ISSUE THREAD

**Issue by majelbstoat** [zeit/next.js#11201] opened 2020-03-19 14:50 UTC
# Bug report

The router query object is not populated immediately from dynamic route params on either the server or the client.

## Describe the bug

The [example for Dynamic routing](https://nextjs.org/docs/routing/dynamic-routes) shows using `useRouter()` to extract a query param to use for rendering. However, on the server, and on client first load, query is an empty object.

This becomes a problem when relying on the param to do anything more than display it - for example using swr to retrieve data based on it.

It's also unexpected, because it appears to be information that is knowable immediately, given either a `req` or a `window.location`.

## To Reproduce

Example repro:

```tsx
// [id].tsx
const TestPage: NextPage = () => {
  const router = useRouter()
  const { query } = router
  const id = query.id
  console.log('Props', process.browser, router)

  return <h1>ID: {id}</h1>
}
```

## Actual behaviour 

Visiting `/42`

There is one entry in the server log:

`Props false undefined`

The component runs twice on the client, with two entries in the client console: 
`Props true undefined`
`Props true 42`

## Expected behavior

I expect query to be populated the first time I call `useRouter()`.

I expect a server log of `Props false 42`.

I expect the function to render once on the client, with one entry in the console: `Props true 42`

## System information

- Version of Next.js: 9.3.1

**Comment by majelbstoat** [comment] 2020-03-19 14:57
Interestingly, if I define a `getServersideProps` – even one that doesn't do anything – query is populated on both the server and the client first load. Is this to do with ASO, perhaps? If so, we might just need clearer documentation or worked examples of how to safely hybridise a page.

**Comment by lifeiscontent** [comment] 2020-03-21 00:37
reproduction: https://codesandbox.io/s/inspiring-feather-uxeph

**Comment by VinSpee** [comment] 2020-03-25 19:04
I bumped into this today as well, and tried `withRouter` as well, but it behaves the same.

**Comment by steida** [comment] 2020-04-06 20:06
My temporal workaround: 

```ts
const withRouterFix = (
  WrappedComponent: FC<{ router: NextRouter }>,
  filter: (query: ParsedUrlQuery) => boolean,
) => () => {
  const router = useRouter();
  if (filter(router.query)) return null;
  return <WrappedComponent router={router} />;
};

const PageID: FC<{ router: NextRouter }> = withRouterFix(
  ({ router }) => {
```

**Comment by Timer** [comment] 2020-04-13 18:17
Duplicate of #11484 

Fix in #9370

**Closed by Timer** 2020-04-13 18:17 UTC

**Comment by majelbstoat** [comment] 2020-04-13 19:55
@Timer, is adding a no-op getServersideProps() the suggested way to disable ASO? This adds a bunch of complexity to pages on dynamic routes when ASO is enabled. (I know getStaticProps is a thing, but many kinds of dynamic page can't be properly populated at build time, and it seems like a common pattern to retrieve data based on the route param.)

**Comment by Timer** [comment] 2020-04-13 20:16
Adding a no-op `getServerSideProps` is not the suggested way of working around this, though, it'd work. You should really defer the data fetching until the router is ready, as will be made easy via #9370 (if you rely on query information).

**Comment by majelbstoat** [comment] 2020-04-13 20:18
I'm using SWR for data fetching. I can't useSWR inside useEffect, and I can't conditionally call useSWR (both due to rules of hooks).

**Comment by Timer** [comment] 2020-04-13 20:20
Can you please share your `useSWR` component?

**Comment by majelbstoat** [comment] 2020-04-13 20:27
A simplified version looks like:

```ts
const ProfilePage = ({query}: Props) => {
  const { username } = query
  const { data: user } = useSwr(`/api/v1/${username}`) 

  if (!user) return null
  return <div>{user.name}</div>
}
```

which gives 404s as it tries to load from `/api/v1/undefined`. (fetcher is set in SWRConfig higher up).

Really, if query isn't going to be ready on first load (which again, it does seem knowable immediately), then this page is not suitable for ASO (as most of my pages are not), but I can't seem to disable it.

**Comment by Timer** [comment] 2020-04-13 21:13
This should work:
```js
const ProfilePage = ({ query }: Props) => {
  const { username } = query;
  const { data: user } = useSwr(() =>
    username ? `/api/v1/users/${username}` : false
  );

  if (!user) return null;
  return <div>{user.name}</div>;
};

```

**Comment by majelbstoat** [comment] 2020-04-13 21:18
Cool, thank you 🙂

**Comment by steida** [comment] 2020-04-25 02:11
A little workaround:

```ts
const useRouterWithQueryReady = (): NextRouter & { queryReady: boolean } => {
  const router = useRouter();
  const queryReady =
    Object.keys(router.query)
      // Server uses amp prop for some reason.
      .filter((k) => k != 'amp').length > 0;
  return { ...router, queryReady };
};
```

**Comment by peterpoe** [comment] 2020-05-06 01:36
If you are using TypeScript, the key function must return `null`:
```ts
const { data: store } = useSWR<Store>(() => (id ? `stores/${id}` : null), fetch)
```

**Comment by balazsorban44** [comment] 2022-01-30 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
