### ISSUE TITLE
Missing styled-jsx dependency in newly created app (yarn 2)

### ISSUE THREAD

**Issue by goszczynskip** [zeit/next.js#11224] opened 2020-03-20 13:34 UTC
# Bug report

## Describe the bug

Created next js app misses `styled-jsx` dependency. This creates error when running `yarn dev` via yarn 2 (berry). Package json should contain `styled-jsx` dependency or `next.js` code shouldn't call it.

## To Reproduce

* Create new app.
* Set yarn to newest version `yarn ser version berry`. 
* Run `yarn dev`

Error message:
```
...
[ error ] ./pages/index.js
Module not found: Your application tried to access styled-jsx, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
...
```
## Expected behavior

It should compile successfully.

**Comment by arcanis** [comment] 2020-03-26 09:50
Duplicate of #10149 - I described the solution there (the reexport + babel), but I don't have bandwidth at the moment to push it myself. Would you be interested to give it a look by any chance?

**Closed** 2020-03-26 10:28 UTC

**Comment by balazsorban44** [comment] 2022-01-30 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
