### ISSUE TITLE
Dynamically importing component in different files cause "loading" flash on mount (only in prod)

### ISSUE THREAD

**Issue by Fumler** [zeit/next.js#5452] opened 2018-10-15 09:05 UTC
# Bug report

## Describe the bug

If we use `next/dynamic` to import components in several files, we experience a flashing "loading..." text when the client mounts. 

If we only import one place, it works fine.
It also works fine in development.

## To Reproduce

Codesandbox example below shows that the `One` component flashes with "loading" text since it is imported twice, while the `Two` component does not flash, because it is only imported once.

[![Edit next-dynamic-import-bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qqy7x4r26w)

## Expected behavior
I expect the dynamic import to behave the same in development and production, as well as it not causing a flash when the client mounts.

## System information
 - OS: macOS mojave
 - Browser: Chrome 69.0.3497.100
 - Version of Next.js: 7.0.2

**Comment by Fumler** [comment] 2018-10-15 12:01
edit: Codesandbox wasnt running with NODE_ENV=production, fixed now.

**Comment by Fumler** [comment] 2018-10-16 15:00
Workaround is to dynamically import only one place, and then export that for use other places.

**Comment by timneutkens** [comment] 2018-10-17 11:29
Duplicate of #5452

**Closed by timneutkens** 2018-10-17 11:29 UTC

**Comment by Fumler** [comment] 2018-10-17 12:42
> Duplicate of #5452

You linked to this issue, which issue were you referring to?

**Comment by timneutkens** [comment] 2018-10-17 12:48
Updated the link, sorry about that 😅
