### ISSUE TITLE
next export: How to disable source maps?

### ISSUE THREAD

**Issue by elyran** [zeit/next.js#6153] opened 2019-01-27 16:34 UTC
How do we disable source maps on the static export?

That is:
`next build && next export`
Now 'out/' has many `.map` files, which I'd like to avoid.

Any solution? Couldn't find on the docs, thanks.

**Comment by timneutkens** [comment] 2019-01-27 18:13
Duplicate of #6009

**Closed by timneutkens** 2019-01-27 18:13 UTC
