### ISSUE TITLE
[BUG] in styled jsx loaders not apply to images

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [zeit/next.js#12158] opened 2020-04-24 00:01 UTC
i have files
`/pages/_App.js`
`/res/images/image.jpg`

```javascript
export default function App() {

  // language=Stylus
  return <style jsx global>{ `
	body {
		background-image: url("../res/images/image.jpg");
	}
  ` }</style>
}
```

Problem
---
`url("../res/images/image.jpg")` will not replace to `/_next/static/images/lol-c8bbed083d312e8f1cccb6069d6f7919.png`. styled jsx not applied webpack loaders, and not create optimized next.js assets

Temporary solution
---

```javascript
export default function App() {

  // language=Stylus
  return <style jsx global>{ `
	body {
		background-image: url(${ require("../res/images/image.jpg") });
	}
  ` }</style>
}
```

**Comment by jamesmosier** [comment] 2020-04-24 02:01
You'll have to either `import` (or `require`) the image as you have in your second example or place the image in the `public` folder [as mentioned in the docs](https://nextjs.org/docs/basic-features/static-file-serving)

**Comment by timneutkens** [comment] 2020-04-24 09:25
Closing as answered. Please follow the issue template in the future. I've asked you this multiple times now in the issue tracker.

**Closed by timneutkens** 2020-04-24 09:25 UTC

**Comment by MaxmaxmaximusGitHub** [comment] 2020-04-24 17:14
@jamesmosier @timneutkens 

if i use webepack base 64 loader, for svg icons, then render component with jsx styles generate 10kb+ style text? every render iteration? if i use 10 png icons by 10kb, i create 100kb style text by every render?

**Comment by MaxmaxmaximusGitHub** [comment] 2020-04-24 17:27
temporary solution:
---

```javascript
import css from 'styled-jsx/css'
import icon from 'res/images/icon.svg'

export default function Box() {
  return <div className='box'>
    <style jsx>{ style }</style>
  </div>
}

// language=Stylus
const style = css`
  .input-panel {
    background-image(${  icon })
  }
`
```

**Comment by balazsorban44** [comment] 2022-01-30 06:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
