### ISSUE TITLE
Error on reloading page in the initial next.js installation

### ISSUE THREAD

**Issue by RobertB4** [zeit/next.js#4456] opened 2018-05-23 12:52 UTC
**Describe the bug**
I get the following error shown in the console when I reload a page in firefox:
`The connection to http://localhost:3000/_next/webpack-hmr was interrupted while the page was loading.`

This seems to happen even with a new next.js installation.

**To Reproduce**
- Create a new folder `mkdir nextjs-test`
- navigate to the folder and install dependencies `npm install --save next react react-dom`
- add the dev script to package.json `"dev": "next"`
- create `./pages/index.js` and copy the following code:
```export default () => <div>Welcome to next.js!</div>```
- `npm run dev` and open localhost:3000 in firefox.
- Reload the browser and open the console. The error should show up in your console.

**Expected behavior**
I expect no error since I only followed the basic setup.

**System information**
 - OS: macOS
 - Browser: firefox 60.0.1 (no error when using chrome)
 - Version of Next.js: 6.0.3

**Comment by timneutkens** [comment] 2018-08-04 12:32
Sounds like you have a babelrc in a directory above the next.js app, next itself doesn’t use babel-preset-react-app, that’s a create-React-app preset

**Comment by anshumanv** [comment] 2018-11-10 16:05
Hey @RobertB4 did you find a workaround?

**Comment by timneutkens** [comment] 2018-11-10 19:03
I'm going to close this as it's probably outdated and fixed already if there was an issue before.

**Closed by timneutkens** 2018-11-10 19:03 UTC

**Comment by StephD** [comment] 2019-10-16 07:52
Hello,

October 2019 here, I still have this error with a lightly different message : 
`The connection to http://localhost:3000/_next/webpack-hmr?page=/ was interrupted while the page was loading.`

Anyway to clean a bit the console in dev mod?

Thanks

**Comment by cryptour** [comment] 2019-10-17 18:01
> Hello,
> 
> October 2019 here, I still have this error with a lightly different message :
> `The connection to http://localhost:3000/_next/webpack-hmr?page=/ was interrupted while the page was loading.`
> 
> Anyway to clean a bit the console in dev mod?
> 
> Thanks

Bump, same problem here. Next 9.1.1

**Comment by Nicolas-Menettrier** [comment] 2019-10-22 16:44
Same, only with firefox.

**Comment by FrancoisVeauvy** [comment] 2019-11-19 01:54
Same problem, only with Firefox too

**Comment by adam-beck** [comment] 2019-11-22 18:09
@timneutkens can this issue be reopened? Or should we create a new one, separate for Firefox issues?

**Comment by wesbos** [comment] 2019-12-18 15:35
Getting this on firefox too. Good news is that soon firefox will be able to negate things from the filter with "-webpack" - but not yet :(

**Comment by wesbos** [comment] 2019-12-18 15:45
I've created a new issue for this: 

https://github.com/zeit/next.js/issues/9776

**Comment by bfunc** [comment] 2021-03-01 20:07
having similar error 
GET http://localhost:3000/_next/webpack-hmr?page=/
(canceled) | eventsource
net::ERR_INCOMPLETE_CHUNKED_ENCODING

**Comment by edikabe** [comment] 2021-03-07 16:08
> 
> 
> having similar error
> GET http://localhost:3000/_next/webpack-hmr?page=/
> (canceled) | eventsource
> 
> hot reload do not works (no updating triangle)
> 
> issue happens from version 10.0.5 and greater, versions from 10.0.0 to 10.0.4 are working ok, I was able to downgrade and work normally
> 
> it is strange but looks like it is only browsers (tested Chrome and Firefox on two diffrent machines) cannot perfom request, commands like _wget_ or _curl_ do receive data

Hey **bfunc** I had similar issue and removing an old registered service-worker solved my problem, please take a look --> https://github.com/vercel/next.js/issues/9776#issuecomment-567411748

**Comment by ShahriarKh** [comment] 2021-05-13 09:24
I resolved this by removing the `assetPrefix` from the config file.
```
//next.config.js

module.exports = withOptimizedImages({
   assetPrefix: ".", //remove this when in development mode
});
```

**Comment by balazsorban44** [comment] 2022-01-28 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
