### ISSUE TITLE
more flexible logging infrastructure

### ISSUE THREAD

**Issue by CNLHC** [zeit/next.js#9383] opened 2019-11-12 07:09 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

may be related to #8422.

At the present time , when using next.js with other backend frameworks (isomorphic applications), users have few controls to the logging facility of next.js.

Users can only  pass `{quiet: true}` when instantiate `next.js`  object. But doing these only hide error messages,  still can not modify some logging behaviours such as  logging level or  logging format.

I hope next.js can provide some mechanics for controlling dev logging behaviour.

## Describe the solution you'd like

using more advanced logging framework such as [winston](https://github.com/winstonjs/winston) maybe a good solution.

## Additional context

I found next.js do have an abstract layer to handle logging([log.ts](https://github.com/zeit/next.js/blob/52dd42a6bb9f0a45af1fb5eac773729b031e8fb1/packages/next/build/output/log.ts)), while some code use these abstract APIs to log( such as [`bundled successfully`](https://github.com/zeit/next.js/blob/18a9c7e371efc4c487f9c3599c3211ce30009d6c/packages/next/build/output/store.ts#L81) ), some do not ( such as [`Compiled successfully`](https://github.com/zeit/next.js/blob/18a9c7e371efc4c487f9c3599c3211ce30009d6c/packages/next/build/index.ts#L322) )

Maybe with controllable logging  is also make  next.js  avilable to provide  more detailed messages for debug using.

**Comment by Janpot** [comment] 2019-11-12 09:32
duplicate of https://github.com/zeit/next.js/issues/4808

**Closed** 2019-11-13 02:43 UTC

**Comment by balazsorban44** [comment] 2022-01-30 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
