### ISSUE TITLE
JSON-API fetching with Devour-client

### ISSUE THREAD

**Issue by auvipy** [zeit/next.js#9746] opened 2019-12-14 08:59 UTC
for easier fetching of JSON-API 1.0 compliant REST API's.

**Comment by timneutkens** [comment] 2019-12-14 10:16
Not sure what to do here. Closing as it doesn't follow the issue template.

**Closed by timneutkens** 2019-12-14 10:16 UTC

**Comment by auvipy** [comment] 2019-12-14 11:13
JSON-API is a standard. and I fund devour he besst client as stanalone. should this be a external package/extension of next?

**Comment by balazsorban44** [comment] 2022-01-30 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
