### ISSUE TITLE
Go back browser button does not refresh page

### ISSUE THREAD

**Issue by jansedlon** [zeit/next.js#9449] opened 2019-11-18 21:45 UTC
# Bug report

## Describe the bug

Going to dynamic route, refresh the page and go back does not refresh the page

## To Reproduce

1. Go to Index page
2. Go to dynamic articles/[slug].js page
3. Refresh the page
4. Click go back browser button

## Expected behavior

Load the Index page

## Screenshots

![Peek 2019-11-18 22-41](https://user-images.githubusercontent.com/13948180/69096458-c3feae80-0a54-11ea-956b-8fa3623768e6.gif)

## System information

- OS: KUbuntu 19.10
- Browser: Google Chrome, newest
- Version of Next.js: 9.1.3

## Additional context

It behaves exactly like here..  #9378 
I tried to use two examples from examples folder, same result. Tried to turn on/off ssr, same result.

There is a sample of my code, might help.

**ArticleView**
```jsx
const Article: NextPage = (props) => {
    const router = useRouter();

    const { loading, data, error } = useQuery<IArticleQueryData>(ARTICLE_QUERY, {
        variables: { id: router.query.slug }
    });

    if (loading) {
        return null;
    }

    const article = data!.Article;

    return (
        <>
            <div className="d-flex justify-content center">
                <div className="container">
                    <div className="article">
                        <div className="article__header d-flex">
                            <div className="col-8 p-0 article__header-thumbnail">
                                <img src={article.thumbnail} alt=""/>
                            </div>
                            <div className="col-4 p-4 article__header-title d-flex flex-column justify-content-end">
                                <h1>{article.title}</h1>
                                <time className="article-date" dateTime={article.createdAt}>
                                    {getArticlePreviewDate(article.createdAt)}
                                </time>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

Article.getInitialProps = async (ctx: NextPageContext): Promise<any> => {
    console.log(ctx)

    return { };
}

export default withApollo(withNav(Article), {
    ssr: false,
});
```

**IndexView**
```jsx
const ArticlePreview: FunctionComponent<IArticlePreviewProps> = (props) => {
    const { article }: { article: IArticlePreviewData } = props;
    const size: number = props.size || 2;
    const sizeInColumns: number = size * 4;
    const articleFormattedDate: string = getArticlePreviewDate(article.createdAt);

    return (
        <div
            className={`article-preview article-preview__container col-12 col-md-${sizeInColumns}`}
        >
            <div
                className="article-preview__thumbnail"
            >
                <Link href="/articles/[slug]" as={`/articles/${article.slug}`}>
                    <a>
                        <img src={article.thumbnail} alt=""/>
                    </a>
                </Link>
            </div>
            <div className="article-preview__content">
                <div className="article-preview__tags">
                    {article.category.name}
                </div>
                <div className="article-preview__title">
                    <Link href="/articles/[slug]" as={`/articles/${article.slug}`}>
                        <a>
                            {article.title}
                        </a>
                    </Link>
                </div>
                <div className="article-preview__meta">
                    <time dateTime={article.createdAt}>
                        {articleFormattedDate}
                    </time>
                    <div className="article-preview__author">
                        {article.author.name} {article.author.surname}
                    </div>
                </div>
            </div>
        </div>
    )
}

export default ArticlePreview;

```

**Comment by ijjk** [comment] 2019-11-18 21:49
Hi, as mentioned in #9378 this has been fixed in `9.1.4-canary.7` of Next.js you can upgrade with `yarn add next@canary`

**Closed by ijjk** 2019-11-18 21:49 UTC

**Comment by jansedlon** [comment] 2019-11-18 21:52
Oh yea, I'm blind, thanks.

**Comment by balazsorban44** [comment] 2022-01-30 22:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
