### ISSUE TITLE
Next Preview has stopped working in version 9.3.5

### ISSUE THREAD

**Issue by JimmyGray** [zeit/next.js#12385] opened 2020-05-01 14:47 UTC
# Bug report

## Describe the bug

Next Preview works in version 9.3.4 with static generation. Upon upgrading to version 9.3.5 and greater preview does not work.

## To Reproduce

1. Go to https://bitbucket.org/jimmmygray/nextpreviewtest/src/master/
2. clone the example
3. run the application
4. navigate too http://localhost:3000/api/preview?slug=22
5. you will be navigated too the posts page
6. Preview mode is true in the console
7. update node modules to version 9.3.5 or greater
8. retry the above steps
9. Preview mode is undefined in the console

**Comment by ijjk** [comment] 2020-05-01 16:19
Hi, it looks like you are trying to test preview mode in production mode on a non-https connection to localhost which will not allow the cookie to be set since the `secure` flag is set for the preview mode cookie in production mode since without this it would allow sending the preview data over an insecure connection.

You are still able to test preview mode in development on a non-https connection and that does appear to be working properly. If you are noticing preview mode not working in development mode please reply with additional details and we can investigate this more.

**Comment by timneutkens** [comment] 2020-05-25 12:38
Closing as no reply was provided.

**Closed by timneutkens** 2020-05-25 12:38 UTC

**Comment by balazsorban44** [comment] 2022-01-30 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
