### ISSUE TITLE
getInitialProps return undefined props

### ISSUE THREAD

**Issue by meazou75** [zeit/next.js#4929] opened 2018-08-09 08:16 UTC
# Bug report

`import fetch from 'isomorphic-unfetch';

const Page = ({ stars }) => <div>Next stars: {stars}</div>;

Page.getInitialProps = async ({ req }) => {
    const res = await fetch('https://api.github.com/repos/zeit/next.js');
    const json = await res.json();
    return { stars: json.stargazers_count };
};

export default Page;
`

## Describe the bug

I want to show the number of stars like in this example : https://nextjs.org/docs/#routing
But the props return by the getInitialProps function are undefined.

## Expected behavior
I expect to show the number of start 

## Screenshots
<img width="468" alt="capture d ecran 2018-08-09 a 15 13 51" src="https://user-images.githubusercontent.com/9728122/43886900-58ac55b0-9be7-11e8-8293-8d2edf19ea7e.png">

## System information
 - OS: macOS
 - Browser chrome
 - Version of Next.js: ^6.1.1

## Additional context

Thx for your help

**Comment by HaNdTriX** [comment] 2018-08-09 10:09
You have a syntax error in your code. 

Since this is not a bug. Please ask such questions on [spectrum chat](https://spectrum.chat/next-js) and close this issue.

**Closed** 2018-08-09 10:26 UTC
