### ISSUE TITLE
Unclear documentation/examples

### ISSUE THREAD

**Issue by austinthetaco** [zeit/next.js#11242] opened 2020-03-20 21:59 UTC
### A Few Things
- I can't seem to find the documentation on the render() method anywhere. It's used in the custom server info but it doesn't actually say what the arguments are or how to use it.
- The docs say to set useFileSystemPublicRoutes to false if you don't want to use /pages, but then how do you point the render method to the right folder/file? How do you actually route to places?

I couldn't find documentation on either. My whole goal is to not use the /pages folder and to be able to write custom routes.

**Comment by timneutkens** [comment] 2020-03-21 17:21
Duplicate of https://github.com/zeit/next.js/discussions/11218

**Closed by timneutkens** 2020-03-21 17:21 UTC

**Comment by balazsorban44** [comment] 2022-01-30 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
