### ISSUE TITLE
Router array parameter without []

### ISSUE THREAD

**Issue by andylaci** [zeit/next.js#3426] opened 2017-12-08 16:19 UTC
Hello, I think standard for url array params is `?arr1[]=1&arr2[]=2`, am I missing something? `Router` parses the object into: `?delivery=1&delivery=24`

**Comment by arunoda** [comment] 2017-12-08 22:28
@andylaci It's because we are seems to be using a older [querystring parser](https://github.com/zeit/next.js/blob/dc07cd1b19f9236f5d906a7b288c01a91d2ce645/server/index.js#L3).

I'd like to use [`qs`](https://www.npmjs.com/package/qs) instead of this.

**Comment by arunoda** [comment] 2017-12-08 22:29
On the other hand, you can parse the url yourself by using a [custom server](https://github.com/zeit/next.js#custom-server-and-routing).

**Comment by timneutkens** [comment] 2017-12-09 00:08
We shouldn't use `qs` cause the library is too big for such a small feature. If we want to provide for a feature like this I guess we should expose the parsing to be overwritten on the router.

**Comment by timneutkens** [comment] 2017-12-09 00:09
Also, Duplicate of #2530

**Closed by timneutkens** 2017-12-09 00:09 UTC

**Comment by andylaci** [comment] 2017-12-09 06:37
Can I at least put string into next router somehow? Without breaking page navigation?
