### ISSUE TITLE
An unexpected error has occurred in production build 9.1.6 version

### ISSUE THREAD

**Issue by Ravindersingh1526** [zeit/next.js#9877] opened 2019-12-30 06:08 UTC
an unexpected error has occurred in production build and following error shown in the console
TypeError: Cannot read property 'attach' of undefined
at nn (commons.5752e1f292d2b25a6a64.js:1)
at commons.5752e1f292d2b25a6a64.js:1
at commons.5752e1f292d2b25a6a64.js:1
at commons.5752e1f292d2b25a6a64.js:1
at commons.5752e1f292d2b25a6a64.js:1
at da (commons.5752e1f292d2b25a6a64.js:1)
at Va (commons.5752e1f292d2b25a6a64.js:1)
at Tu (commons.5752e1f292d2b25a6a64.js:1)
at Tl (commons.5752e1f292d2b25a6a64.js:1)
at jl (commons.5752e1f292d2b25a6a64.js:1)

When we run npm start command project will working fine.

**Comment by alabobriggs** [comment] 2019-12-30 06:41
Reference this issue #9854 and check the fix if it helps out

**Comment by timneutkens** [comment] 2020-01-01 13:28
It's impossible to help based on half a stacktrace and a random error without a full reproduction. Closing as the issue template was ignored.

**Closed by timneutkens** 2020-01-01 13:28 UTC

**Comment by ivanjeremic** [comment] 2020-06-01 14:59
If Nextjs would give better error messages it would be easier to find the error, same here on a clean install of the Chakra-ui template only added a few contexts file nothing more.

**Comment by timneutkens** [comment] 2020-06-01 17:21
> If Nextjs would give better error messages it would be easier to find the error, same here on a clean install of the Chakra-ui template only added a few contexts files nothing more and got this error on every route except index.

Same argument from my previous comment still applies, we can't improve the stacktraces you're running into if you do not provide a complete reproduction in a github repository.

**Comment by ivanjeremic** [comment] 2020-06-02 10:12
> Same argument from my previous comment still applies, we can't improve the stacktraces you're running into if you do not provide a complete reproduction in a github repository.

Sorry, the problem was due to a package I tried to use on the server, stitch-browser-sdk

**Comment by balazsorban44** [comment] 2022-01-30 02:14
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
