### ISSUE TITLE
Compile-time browser environment check from a package in node_modules

### ISSUE THREAD

**Issue by elliottsj** [zeit/next.js#9240] opened 2019-10-29 21:58 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

As described [here](https://github.com/zeit/next.js/blob/acf7d0ad3bdde5fd579e80325894f4b8a262130f/errors/no-router-instance.md#possible-ways-to-fix-it), we can use the expression `typeof window !== 'undefined'` to eliminate code paths at compile time. webpack uses this to determine which dependency paths it needs to traverse, e.g.

```ts
const Sentry: SentryType =
  typeof window !== 'undefined' ? require('@sentry/browser') : require('@sentry/node');
```

The compiled code effectively becomes this in the browser:

```ts
const Sentry = require('@sentry/browser');
```

And the server:

```ts
const Sentry = require('@sentry/node');
```

But this only works on application code, as of https://github.com/zeit/next.js/pull/8355. I have a monorepo structure for my project where I'd like to move the Sentry code above into a separate package, but the `typeof window !== 'undefined'` expression is no longer effective, so errors like this occur:

```
[ error ] /path/to/node_modules/.registry.npmjs.org/@sentry/node/5.7.1/node_modules/@sentry/node/esm/integrations/console.js
Module not found: Can't resolve 'console' in '/path/to/node_modules/.registry.npmjs.org/@sentry/node/5.7.1/node_modules/@sentry/node/esm/integrations'
```

## Describe the solution you'd like

I'd like to have a compile-time expression I can use to check if code is running in the browser/server, and have it applied to code in `node_modules`.

## Describe alternatives you've considered

I am using `process.browser` currently, but my perception from [this comment](https://github.com/zeit/next.js/issues/2177#issuecomment-536178575) is that `typeof window !== 'undefined'` is recommended over `process.browser`.

**Comment by timneutkens** [comment] 2019-10-31 12:49
We tried to do this before but it's too dangerous with packages in the ecosystem breaking hence why it's only applied to user code.

**Comment by elliottsj** [comment] 2019-10-31 17:43
I suppose that, since the [`typeof window` expression is resolved via babel](https://github.com/zeit/next.js/blob/37ee8fc9e7b2b507e82ddbcff6b4ab86cd09ad0d/packages/next/build/webpack/loaders/next-babel-loader.js#L167-L171), adding [support to transpile `node_modules`](https://github.com/zeit/next.js/issues/706) would solve this issue. I would be able to opt-in my Sentry package to be transpiled, and the `typeof window !== 'undefined'` expression would be transpiled too.

**Comment by timneutkens** [comment] 2020-01-03 00:10
Going to close this because of said reason.

**Closed by timneutkens** 2020-01-03 00:10 UTC
Labels: Type: Feature Request

**Comment by balazsorban44** [comment] 2022-01-30 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
