### ISSUE TITLE
Dynamic routes with locale code in <Link /> `as` leads to warn in console.

### ISSUE THREAD

**Issue by DmitryKozyrenko** [zeit/next.js#8462] opened 2019-08-21 11:16 UTC
# Bug report

## Describe the bug

When I try update production project with 100+ pages and 10+ languages to Next.js 9.0.4 and move all my routes from `next-routes` to built-in dynamic routes found some issue on client side routing.

In multi language sites in most cases we need to show locale code in the start of paths but with dynamic routes it cant be done right now, this will lead to an warning in console:https://github.com/zeit/next.js/blob/f41f630d19a1f87265fd77ae884b003d85915847/packages/next-server/lib/router/router.ts#L317

So if we have dynamic route like `/post/[id]` and try to build link component with `href="/post/[id]?locale=de"` and `as="/de/post/${id}"` we have warning in console after click on that link.

As I understand this issue was appears because route created from href does not match regex created from `as`, but I dont quite understand how to fix it for dynamic routes.

Need clear way to build multi language sites without using `next-routes`.

## To Reproduce

1. Create dynamic route `/post/[id]`.
2. Create `<Link />` component with `href="/post/[id]?locale=de"` and `as="/de/post/${id}"`.
3. Click on it and you will see warning in the console.

## System information

- Next.js 9.0.4

**Comment by timneutkens** [comment] 2019-08-21 12:41
I don't really understand the problem here, why not create `pages/[locale]/post/[id].js`?

**Comment by DmitryKozyrenko** [comment] 2019-08-21 12:54
I thought about this as a solution when the problem occurred, but this is good idea when you have a small number of pages, in my case this is not the most elegant solution as I think.

**Comment by Timer** [comment] 2019-08-22 16:00
Closing this as misuse of `<Link>` -- your `as` must match your `href`'s format -- there's no exception to this rule.

Please wait for future RFCs about optional route parameters -- I'll close this as a duplicate of https://github.com/zeit/next.js/issues/8443.

**Closed by Timer** 2019-08-22 16:00 UTC

**Comment by balazsorban44** [comment] 2022-01-31 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
