### ISSUE TITLE
get query object by Router.query error

### ISSUE THREAD

**Issue by lancetian65** [zeit/next.js#10519] opened 2020-02-13 16:28 UTC
# Bug report
get query object by Router.query error
## Describe the bug
when i use dynamic-routing, i come across that bug,

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2]

**Comment by Timer** [comment] 2020-02-13 17:08
duplicate of #10521

**Closed by Timer** 2020-02-13 17:08 UTC

**Comment by balazsorban44** [comment] 2022-01-30 13:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
