### ISSUE TITLE
One rendered "layout"

### ISSUE THREAD

**Issue by apapacy** [zeit/next.js#3596] opened 2018-01-20 11:07 UTC
> Note: React-components outside of <Main /> will not be initialised by the browser. If you need shared components in all your pages (like a menu or a toolbar), do not add application logic here, but take a look at this example. https://github.com/zeit/next.js/tree/master/examples/layout-component

OK. But it very useful.

The layout inside the component is created every time a page is moved to a new page. But the layout should not be created every time you go to a new page.

Also, the layout should have an asynchronous initialization method.

Ideally, it would be possible to create several layouts and set the current layout in the component page.

**Comment by timneutkens** [comment] 2018-01-20 12:37
Duplicate of https://github.com/zeit/next.js/issues/88

**Closed by timneutkens** 2018-01-20 12:37 UTC
