### ISSUE TITLE
Route to new page without invoking `getInitialProps`

### ISSUE THREAD

**Issue by brettinternet** [zeit/next.js#8774] opened 2019-09-17 18:55 UTC
# Feature request

When using a `next export` static build, I would like the `getInitialProps` method to fire only during the build step and not on the client for select page components. ([Related StackOverflow question](https://stackoverflow.com/questions/57897785/how-can-i-use-getinitialprops-only-during-the-nextjs-site-build/57905091))

On a static client, Next.js invokes this method before the page component is rendered in order to provide the necessary props for the component. Thus, large requests can delay the client's first paint as this is a blocking request.

I would like to selectively ignore `getInitialProps` for a page component, and instead use the props provided by `getInitialProps` during `next export`.

I'm unwilling to move my slow API request to `componentDidMount` in order to avoid the blocking request because I want to use the data returned during the build step to populate the static HTML, and this particular request doesn't need to be dynamic or updated after the build.

> Shallow routing works only for same page URL changes.

\- [Shallow Routing](https://nextjs.org/docs/#shallow-routing)

For this feature request, is it possible to implement something similar to shallow routing, but for _new_ pages?

To circumvent `getInitialProps` on static exports, I currently have to use a standard JSX anchor `<a href="/next-page">` to avoid invoking the method. This does cause a full page refresh which is a poor solution.

**Comment by tylermcrobert** [comment] 2019-09-20 01:30
I don't have a solution yet but perhaps these help? #8291  #5903

**Comment by dmks** [comment] 2019-10-02 04:15
I have the same problem, @brettinternet , what's your workaround so far? Could you explain more about it?

Thanks

**Comment by dmks** [comment] 2019-10-02 06:29
My workaround is 
`
XXXPage.getInitialProps = async (req) => {
  if (process.browser) {
    return __NEXT_DATA__.props.pageProps;
  }
  // original logic
`

**Comment by tylermcrobert** [comment] 2019-10-02 06:33
@dmks I’m excited to try this. It’s been working for you well?

**Comment by dmks** [comment] 2019-10-02 06:54
> @dmks I’m excited to try this. It’s been working for you well? Where does `__NEXT_DATA__` come from, the `window` ?

Yes, here is the source code: 
https://github.com/zeit/next.js/blob/canary/packages/next/client/index.js#L30-L31

**Comment by tylermcrobert** [comment] 2019-10-03 01:22
Nice. Thanks dude. Here's a function I now include at the beginning of each `getInitialProps`:

```
export default function serveStaticData() {
  if (typeof window !== 'undefined') {
    const nextScript = document.getElementById('__NEXT_DATA__')
    const nextData = JSON.parse(nextScript.textContent)
    const { pageProps } = nextData.props
    return { ...pageProps }
  }
}
```

**Comment by tylermcrobert** [comment] 2019-10-03 02:30
Unfortunately, turns out this doesn't seem to always grab the `__NEXT_DATA__` for the current page unless i'm missing something

**Comment by brettinternet** [comment] 2019-10-03 03:05
@dmks I'm not able to reproduce this ([CodeSandbox](https://codesandbox.io/s/conditionally-use-getinitialprops-1xx1n)). Could you provide an example?

**Comment by dmks** [comment] 2019-10-15 20:48
@brettinternet , your sandbox is not using the "static export" function of nextjs, right? 

Maybe we are talking about different scenarios, mine is this:
```
const MyPage = ({prop1, prop2}) => {
  ...
}
MyPage.getInitialProps = async (ctx) => {
  console.log("getInitialProps in MyPage");
  const {prop1, prop2, ...} = await fetchHeavyData(...);
  return {prop1, prop2};
};
```
When I enter the url on the navigation bar on my browser, the behavior is different for different environment.

1. In development environment (`next dev`), "getInitialProps in MyPage" only print at the server side, and not at the browser side. And this's good and expected.

2. In the exported static page environment (`next build && next export && cd out && serve -p 8080`),  the message "getInitialProps in MyPage" will print when `next export` and in the browser console. Printing at the browser side is unexpected to me because the page is already rendered. 


And my workaround is to solving the #2 issue, I don't want `fetchHeavyData()` to be called at the browser side.

**Comment by luukdv** [comment] 2019-11-29 09:53
Related: https://github.com/zeit/next.js/issues/9524

**Comment by Timer** [comment] 2019-11-29 16:28
Closing as duplicate of https://github.com/zeit/next.js/issues/9524

**Closed by Timer** 2019-11-29 16:28 UTC

**Comment by balazsorban44** [comment] 2022-01-30 21:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
