### ISSUE TITLE
How include node modules in next server build?

### ISSUE THREAD

**Issue by 3jwddgm** [zeit/next.js#5432] opened 2018-10-11 18:35 UTC
Hi, next is great, thnx.

I have a big project based on lerna monorepo with next, and custom next server as a different packages. For production build we use few stages docker build, lerna build building all packets in monorepo, after this i wanna take custom server package and builded .next folder for the run next on server, but for the disk space economy, i wanna include using in next node_modules to next server bundle. I try customize webpack config for chose config.externals, or next-plugin-transpile-node-modules, but i dont have a luck.

Maybee you have example proj, example config, actual plugin or any advice for this?

Thnx.

Next version 7.0.1

https://spectrum.chat/thread/2a07bd86-895c-41f9-a610-392765a845df

**Comment by timneutkens** [comment] 2018-10-11 19:04
Based on your description you're looking for #4496.

So I'm going to close this issue as a duplicate of that issue.

**Closed by timneutkens** 2018-10-11 19:04 UTC

**Comment by 3jwddgm** [comment] 2018-10-11 19:21
Thnx)
