### ISSUE TITLE
Enhancement: remove regenerator runtime from any code that'll end up on the client

### ISSUE THREAD

**Issue by timruffles** [zeit/next.js#6615] opened 2019-03-12 01:57 UTC
## Feature request

NextJS currently bundles regenerator-runtime in its distribution: 10k (minified) of JS that it doesn't need to. This is bad:
- mobile clients, especially lower powered ones in emerging markets, struggle to parse giant chunks of JS
- Next.js as a SSR framework is often picked by precisely the teams that care about performance
- browsers are [considering limits on JS](https://bugs.webkit.org/show_bug.cgi?id=194028) due to the performance impact of too much JS

Therefore Next.js should remove this dependency. It's well worth the payoff for library code to avoid `async` and use promises directly.

## Describe alternatives you've considered

As it's part of the distribution, it's unreasonably hard to remove as an end-user of Next.js.

## Additional context

- I'm seeing regenerator-runtime end up in client-side built code in `router/index.js` and `lib/utils.js`.
- #1291 mentioned this'd be coming after preset env support.

**Comment by timneutkens** [comment] 2019-03-12 10:16
Still wondering why the issue templates are not being used 🤔

---

Just for context this issue entails the Next.js codebase itself, not the bundling of user code 🕵️

**Comment by timruffles** [comment] 2019-03-12 14:53
> Still wondering why the issue templates are not being used

@tim-phillips my bad, fixed.

**Comment by tim-phillips** [comment] 2019-03-12 17:14
Too many Tim’s

**Comment by timneutkens** [comment] 2019-03-12 22:17
One can never have too many Tims 🚀

**Comment by acjay** [comment] 2019-04-02 21:59
Is it possible to manually configure Next.js to use native `async` support? I'm experimenting, but can't figure out how to do so.

**Comment by timneutkens** [comment] 2020-01-02 20:27
Closing in favor of #7563

**Closed by timneutkens** 2020-01-02 20:27 UTC
Labels: Type: Enhancement

**Comment by balazsorban44** [comment] 2022-01-30 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
