### ISSUE TITLE
Hot Module Replacement doesn't reload styles when switching between routes

### ISSUE THREAD

**Issue by scabbiaza** [zeit/next.js#6178] opened 2019-01-30 09:20 UTC
# Bug report

## Describe the bug

Hot Module Replacement doesn't reload styles when switching between pages

## To Reproduce

I created a demo repo here:
https://github.com/scabbiaza/nextjs-test

Steps to reproduce:
1. Create two pages, each one should include own CSS files:
https://github.com/scabbiaza/nextjs-test/tree/master/pages

In my case: 
* home page has styles to make a text RED
* about page has styles to make a text GREEN

2. Run `npm run dev`

3. Open the home page, see that CSS has styles for the current page only

Text color is red, which is correct:

<img width="805" alt="screen shot 2019-01-30 at 11 08 20" src="https://user-images.githubusercontent.com/2734464/51970454-a0e01f80-247f-11e9-94f8-7111380b3e10.png">

4. Click on the link to load About page, styles are not updated 

Text color is red, which is incorrect! Should be green

<img width="799" alt="screen shot 2019-01-30 at 11 08 31" src="https://user-images.githubusercontent.com/2734464/51970506-c705bf80-247f-11e9-96d0-5db7219f5644.png">

Although, we can see that the script to hot-reload CSS was loaded:
<img width="991" alt="screen shot 2019-01-30 at 11 08 44" src="https://user-images.githubusercontent.com/2734464/51970586-fa484e80-247f-11e9-916e-09c0e8c6ef31.png">

If you refresh a page, or change any code, styles will be updated on the page.

## Expected behavior
Styles should be updated when switchig between pages inside a SPA.

## System information
 - OS: macOS
 - Browser: Chrome
 - Next: 7.0.2
 - zeit/next-css 1.0.1

Not sure if this is an issue in NextJs configuraitons, or in Webpack. Please advise.

**Comment by MarchWorks** [comment] 2019-01-30 11:37
There is already an open issue for this [#282](https://github.com/zeit/next-plugins/issues/282)

**Comment by timneutkens** [comment] 2019-01-30 15:51
Duplicate of https://github.com/zeit/next-plugins/issues/282

**Closed by timneutkens** 2019-01-30 15:51 UTC
