### ISSUE TITLE
_app.js build bundle size too big

### ISSUE THREAD

**Issue by gnoyixiang** [zeit/next.js#9682] opened 2019-12-10 14:44 UTC
# Bug report
The _app.js build bundle size is too big

## Describe the bug
I have looked through many issues for solutions and it seems that the team has repeatedly mentioned that next.js build bundle size is small. What I realised was that the _app.js was already 216 kb (with yellow indication, not green) when I have not added any additional code or library. 

Adding a little more code or importing some libraries in a custom _app.js file will increase the bundle size until the indicator becomes red, meaning it is a unacceptable size?

## To Reproduce

Just do `npx create-next-app` and `yarn build`

## Expected behavior

Currently, _app.js  bundle size is already 216 kb. Expected should be a much smaller value. I don't know what should be the acceptable size, but of course, the smaller the better. Otherwise, it seems like next.js is really too bloated.

## Screenshots

![nextjs-build-ss](https://user-images.githubusercontent.com/30717323/70538775-9e6d4c80-1b9d-11ea-903d-0152813a7efc.png)

## System information

- OS:  Windows
- Version of Next.js:  9.1.5

**Comment by enesTufekci** [comment] 2019-12-12 14:00
@gnoyixiang assuming that you are using custom `app` if so, can you share the code if it is possible. Also you can check whatever goes into the bundles via bundle analyzer.
https://www.npmjs.com/package/@next/bundle-analyzer

**Comment by hushino** [comment] 2019-12-13 14:38
Same issue here, and i'm not using a custom app, to reproduce Just do npx create-next-app and yarn build.
Is the size expected by the team?

**Comment by timneutkens** [comment] 2019-12-13 15:05
Can you try next@canary, it includes improvements in the way that the sizes are displayed.

**Comment by sakulstra** [comment] 2019-12-13 19:12
@timneutkens i just tested without a custom _app.js and the output size is still `211kb` on `"next": "^9.1.6-canary.5",` ... not sure why it's different to the reported one(due to typescript?), but it's still in the orange area.

**Comment by timneutkens** [comment] 2019-12-13 22:06
Do you see the split out between framework etc chunks? Can you post a screenshot?

**Comment by srdjan** [comment] 2019-12-13 23:48
for what it is worth, total size difference comparing to the older version (v9.0.7), is **-30kb** for this small app (repo: https://github.com/srdjan/next-repros). 

But it can be confusing at first sight - since the new output presents both _'shared by all'_ total and each individual shared item in the similar way (vertically aligned)...

before: 
<img width="351" alt="Screen Shot 2019-12-13 at 6 29 17 PM" src="https://user-images.githubusercontent.com/61190/70838607-20948580-1dd7-11ea-8b2f-aa9612aac1ff.png">

latest:
<img width="266" alt="Screen Shot 2019-12-13 at 6 29 25 PM" src="https://user-images.githubusercontent.com/61190/70838616-2a1ded80-1dd7-11ea-94f6-b7ae0fe39db8.png">

**Comment by gnoyixiang** [comment] 2019-12-14 06:38
> @gnoyixiang assuming that you are using custom `app` if so, can you share the code if it is possible. Also you can check whatever goes into the bundles via bundle analyzer.
> https://www.npmjs.com/package/@next/bundle-analyzer

I did not use a custom app.js or any additional code before building.

> Can you try next@canary, it includes improvements in the way that the sizes are displayed.

 There isn't a lot of documentation on how to use this and how it improves the situation. If using next@canary is better, it should be the default recommended one to those who are using your framework. 

Anyway this issue is very easy to replicate and I have not seen anyone from the team who has really explained/addressed this issue.

**Comment by Timer** [comment] 2019-12-14 07:10
Please try `next@9.1.6-canary.9` (`next@canary`). This should show proper output sizes.

Closing as fixed.

![image](https://user-images.githubusercontent.com/616428/70844940-b4397680-1e16-11ea-9232-7d3aacad46b3.png)

**Closed by Timer** 2019-12-14 07:10 UTC

**Comment by srdjan** [comment] 2019-12-14 11:55
just a suggestion... consider removing (or showing in different color) number for the total size of shared:

![unnamed](https://user-images.githubusercontent.com/61190/70848375-8f58f980-1e3e-11ea-8d15-b86f9ab7fd29.png)

**Comment by luanlucho** [comment] 2020-05-27 20:17
Hey guys I'd created a new project following your with redux thunk example and my _app.js file size became larger than 500kb.

<img width="822" alt="Screen Shot 2020-05-27 at 3 16 40 pm" src="https://user-images.githubusercontent.com/30386923/83067974-256b8f80-a02d-11ea-950e-cce1a3bfb0c6.png">

Please shed some light.

**Comment by balazsorban44** [comment] 2022-01-30 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
