### ISSUE TITLE
Allow customization of Babel config from next plugins

### ISSUE THREAD

**Issue by developit** [zeit/next.js#7533] opened 2019-06-07 21:27 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, it is not possible to inject Babel plugins or presets from within a Next.js plugin (or next.config.js). This would be a really useful addition to the plugin system that would help avoid relying on user instructions, packaging all necessary configuration pieces together in a single function.

This would be especially useful for Next plugins that need to modify both Webpack and Babel in a single plugin (Linaria, for example).

## Describe the solution you'd like

A new plugin hook would allow customization of the Babel configuration after it gets derived from babelrc/babel.config.js, but before it is applied via next-babel-loader:

```js
module.exports = function withFoo(nextConfig) {
  return Object.assign({}, nextConfig, {
    babel(babelConfig, options) {
      if (nextConfig.babel) {
        babelConfig = nextConfig.babel(babelConfig, options);
      }
      babelConfig.plugins.push(require.resolve('./babel-plugin'));
      return babelConfig;
    }
  });
};
```

## Describe alternatives you've considered

Scaffolding `.babelrc`/`babel.config.js`: this gets difficult/impossible since the latter is arbitrary JavaScript, and both can contain any number of `env` values.

Injecting into `options.defaultLoaders.babel`: this doesn't work. Maybe making it work could be a reasonable API surface?

Adding additional `babel-loader` passes: this technically works, but increases build times considerably due to multiple AST parse + codegen passes.

Use injecting a wrapper around `next-babel-loader`: this doesn't work because the loader invoke babel with an internal configuration object that can't be mutated from the outside.

**Comment by abusada** [comment] 2019-06-08 08:59
Are we talking about something like [this](https://github.com/abusada/next.js/pull/1/files)?

**Comment by developit** [comment] 2019-07-12 16:47
@abusada yeah, something like that.

**Comment by timneutkens** [comment] 2019-07-12 17:11
Probably good to add the note that this causes issues in interop with other tools like Jest

**Comment by kachkaev** [comment] 2019-07-12 17:19
To satisfy jest, would it be possible to do something like that in `babel.config.js`?

```js
module.exports = require('next').someFunctionThatLooksIntoNextConfigAndReturnsBabelJson();
```

The function can optionally accept the path to the config, e.g. when the app’s root dir is a subdirectory of the repo’s root dir.

**Comment by timneutkens** [comment] 2020-01-02 21:00
This was needed for module/nomodule tests but is no longer needed I think. Closing.

**Closed by timneutkens** 2020-01-02 21:00 UTC
Labels: Type: Feature Request

**Comment by will-stone** [comment] 2020-07-22 08:37
Hi chaps. Any chance this could be reopened? This...

> This would be especially useful for Next plugins that need to modify both Webpack and Babel in a single plugin (Linaria, for example).

...would be incredibly useful when trying to avoid having to ask the consumer to add additional config to their setup. I asked @abusada this on his PR but I'll post the question here too just in case: is there really no way to coax the webpack config to be able to add babel plugins? I've tried all sorts of things like:

```ts
webpack: (config, options) => {
  config.module.rules.push({
    test: /\.+(js|jsx|ts|tsx)$/,
    use: [
      options.defaultLoaders.babel,
      {
        loader: 'babel-loader',
        options: {
          presets: ['next/babel'],
          plugins: [['styled-components', { 'ssr': true }]],
        },
      },
    ],
  });

  return config;
},
```

but obviously to no success. I appreciate all the hard work, and if there's anything I can do to maybe help push @abusada's PR through, testing etc., please let me know.

**Comment by will-stone** [comment] 2020-07-22 09:44
Okay, I think I have it working with:

```ts
webpack: (config) => {
  config.module.rules.push({
    test: /\.+(js|jsx|mjs|ts|tsx)$/,
    use: {
      loader: 'babel-loader',
      options: {
        plugins: [['styled-components', { 'ssr': true }]],
      },
    },
  });

  return config;
},
```

Where I had to install the `babel-loader`. I think this is essentially what @developit described as:

> Adding additional babel-loader passes: this technically works, but increases build times considerably due to multiple AST parse + codegen passes.

Please let me know if I've done anything unintentionally bad, but this appears to be the solution for now.

**Comment by will-stone** [comment] 2020-07-23 13:59
For anyone stumbling upon this, you still have to include the `next/babel` preset, otherwise you lose IE11 support:

```js
webpack: (config: any) => {
  config.module.rules.push({
    test: /\.+(js|jsx|mjs|ts|tsx)$/,
    use: {
      loader: 'babel-loader',
      options: {
        'presets': ['next/babel'],
        plugins: [['styled-components', { 'ssr': true }]],
      },
    },
  });

  return config;
},
```

**Comment by balazsorban44** [comment] 2022-01-29 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
