### ISSUE TITLE
API(8.1.1-canary.28): error logged when importing child_process

### ISSUE THREAD

**Issue by Janpot** [zeit/next.js#7334] opened 2019-05-14 21:43 UTC
# Bug report

## Describe the bug

Errors are shown in the logs when trying to import `child_process` in an api function.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Create an api function
```js
// /pages/api/hello.js
import 'child_process';
export default (req, res) => {
  res.end('hello');
};
```
2. start next dev server
3. visit `http://localhost:3000/api/hello` in the browser
```
[ error ] ./pages/api/hello.js
Module not found: Can't resolve 'child_process' in '<project-root>/pages/api'
```
## Expected behavior

No error

## System information
 - OS: macOS
 - Version of Next.js: 8.1.1-canary.28

## Additional context

Functionally there doesn't seem to be any problem, looks like it's just a logging problem.

**Comment by Janpot** [comment] 2019-05-14 22:14
> Functionally there doesn't seem to be any problem, looks like it's just a logging problem.

Actually, there is a problem, this seems to break rendering the actual pages

**Comment by timneutkens** [comment] 2019-05-16 09:17
Note that you're using experimental features. This in particular is caused by the /api implementation not being complete yet.

**Comment by Janpot** [comment] 2019-05-16 09:19
I'm aware, just test driving new things, that's what canary is for, right?

**Comment by huv1k** [comment] 2019-06-08 18:51
This is fixed in latest canary 🚀

**Closed by huv1k** 2019-06-08 18:51 UTC

**Comment by aaahrens** [comment] 2019-10-11 00:01
I am getting this error again in canary of 9. Any advice?

**Comment by IMax153** [comment] 2019-10-30 23:58
I am also running into the same issue trying to integrate the GraphQL API endpoints example with Prisma2. The query engine, PhotonJS, seems to depend on 'child_process', which results in an error every time I hit the GraphQL endpoint (or any other endpoint that attempts to use PhotonJS).

<pre>
<code>
ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/@generated/photon/runtime'
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/webpack/lib/Compilation.js:888:10
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/neo-async/async.js:2830:7
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/neo-async/async.js:6877:13
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/@generated/photon/runtime'
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/webpack/lib/Compilation.js:888:10
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/neo-async/async.js:2830:7
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/neo-async/async.js:6877:13
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/maxbrown/Documents/projects/apps/iudex-next/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
</code>
</pre>

**Comment by huv1k** [comment] 2019-10-31 11:22
This is most likely how is photon getting the path to the binary. I think it uses `__dirname` to resolve paths to binary. Next.js it's not working with `__dirname` yet https://github.com/zeit/next.js/issues/8251 But I am not 100% sure, didn't check how exactly photo binary resolution works.

**Comment by balazsorban44** [comment] 2022-01-31 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
