### ISSUE TITLE
with-ant-design-less doesn't work on build when using Link

### ISSUE THREAD

**Issue by watch-janick** [zeit/next.js#9937] opened 2020-01-04 04:20 UTC
# Examples bug report

## Example name

with-ant-design-less

## Describe the bug

Links doesn't work on production build when using Ant design in pages.

## To Reproduce

Clone repo: https://github.com/watch-janick/next-with-ant-design-less-link-issue.git

1. Start a production build (npm run build && npm run start)
2. Go to localhost:3000
3. Click on 'login'
4. Nothing happens
5. Go to localhost:3000/login
6. Click on any link
7. It works

## Expected behavior

Every links should work.

## System information

- Version of Next.js: 9.1.6
- Version of Ant Design: 3.25.2

**Comment by timneutkens** [comment] 2020-01-04 11:52
Assuming duplicate of https://github.com/zeit/next-plugins/issues/282

**Closed by timneutkens** 2020-01-04 11:52 UTC

**Comment by balazsorban44** [comment] 2022-01-30 17:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
