### ISSUE TITLE
meta duplicate

### ISSUE THREAD

**Issue by krmao** [zeit/next.js#7166] opened 2019-04-26 10:49 UTC
# Bug report
meta duplicate
## Describe the bug
meta duplicate
if add <meta name="viewport" content="width=device-width"/> in _document.js
just like 
```
// _document is only rendered on the server side and not on the client side
// Event handlers like onClick can"t be added to this file

// ./pages/_document.js
import Document, {Html, Head, Main, NextScript} from "next/document";
import React from "react";

class MyDocument extends Document {
    static async getInitialProps(ctx) {
        const initialProps = await Document.getInitialProps(ctx);
        return {...initialProps};
    }

    render() {
        return (
            <Html>
            <Head>
                <link rel="icon" href="../static/favicon.ico" type="image/x-icon"/>
                <link rel="shortcut icon" href="../static/favicon.ico" type="image/x-icon"/>

                <meta name="viewport" content="width=device-width"/> // bug 在每个页面的 Head 里面加这一行，否则系统会默认加这一行
            </Head>
            <body>
            <Main/>
            <NextScript/>
            </body>
            </Html>
        );
    }
}

export default MyDocument;

```

and also add Head tag in page.js, just like
```
import React from "react";
import Head from "next/head";
import {withRouter} from "next/router";

export default withRouter(class extends React.Component {

    constructor(props) {
        super(props);
    }

    render() {
        console.log(this.props.router.asPath);
        return (
            <div>
                <Head>
                    <title>xxxxxx</title>
                </Head>
            </div>
        );
    }
});

```

the result is 

nextjs will auto add <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1" class="next-head"> to page

![image](https://user-images.githubusercontent.com/7344437/56802944-f98f4080-6853-11e9-8b46-b3faaae88dd9.png)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information
 - OS: [e.g. macOS, Windows]
 - Browser (if applies) [e.g. chrome, safari]
 - Version of Next.js: [e.g. 6.0.2]

**Comment by MarchWorks** [comment] 2019-04-26 11:19
Duplicate of https://github.com/zeit/next.js/issues/6919

**Closed** 2019-04-26 11:34 UTC
