### ISSUE TITLE
AMP site is missing CSS

### ISSUE THREAD

**Issue by pizzafox** [zeit/next.js#9409] opened 2019-11-14 02:18 UTC
# Bug report

## Describe the bug

When using AMP my pages have no styles. I am using [grommet](https://grommet.io) and SCSS files imported with the Zeit SASS loader.

## To Reproduce

I noticed this on my personal website. Here is the repository locked at the commit where I noticed this and sample pages for that commit. Note that the sample pages are 404 pages on purpose since they are very simple.

[GitHub repository](https://github.com/pizzafox/jonah.pw/blob/04e922e00ea17950f1755c7b2a224ad88af1ebf0/src/pages/404.tsx)
[Live version of non-AMP page](https://5dccae974c8c3a0008b66a0c--jonahsnider.netlify.com/404)
[Live version of  AMP page](https://5dccae974c8c3a0008b66a0c--jonahsnider.netlify.com/404.amp)

These pages are from `next export` in case that matters.

## Expected behavior

The AMP page should include the rendered styles from my component framework and imported SCSS files.

## Screenshots

<details>
  <summary>What it should look like (from non-AMP version in)</summary>

  _this is the dark theme version, default theme has inverted colors_

  ![a pretty 404 page](https://user-images.githubusercontent.com/7608555/68820109-257ee180-063f-11ea-8ba8-70513d8828d3.png)
</details>

<details>
  <summary>What the AMP version actually looks like</summary>

  ![a not pretty 404 page](https://user-images.githubusercontent.com/7608555/68820098-19931f80-063f-11ea-981f-53133c5137aa.png)
</details>

## System information

- OS: Windows 10
- Browser: 78.0.3904.97 (Official Build) (64-bit)
- Version of Next.js: `9.1.3`

## Additional context

I observed an empty `amp-custom` style element in the `<head>` of the page:

```html
<style amp-custom=""></style>
```

Possibly related to #7121, because we are both using Styled Components. However, my SCSS styles aren't on the AMP page which makes me think that this is a different issue.

Edit: Possibly related to #7057 as they were using Styled Components and [the SASS loader](https://github.com/zeit/next.js/issues/7057#issuecomment-484687172), although they had a crash occur.

**Comment by ijjk** [comment] 2019-11-18 22:31
Hi, as mentioned above, it is related to #7121. When that is addressed this should be also so closing this in favor of that issue

**Closed by ijjk** 2019-11-18 22:31 UTC

**Comment by balazsorban44** [comment] 2022-01-30 22:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
