### ISSUE TITLE
Built-in CSS support is being disabled due to custom CSS configuration being detected

### ISSUE THREAD

**Issue by saresh-krish** [zeit/next.js#12244] opened 2020-04-27 16:31 UTC
Hello
# Bug report

## Describe the bug

Nextjs CSS & SASS in next.config.js

## To Reproduce

I am working on  NextJs 9.3.4, when i run the app i am facing problem
"Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled"
so in some time external style is not rendering properly and we give to hard reload then the styles work properly .
How to solve this problem??
I need to use external components style for there particular components.
how to use external style CSS and SaSS in next.config.js file.

## Expected behavior

Styles(CSS & SASS) will be work on individual components

## System information

- OS: Ubuntu 18.04.3 LTS
- Browser (if applies): chrome, Mozilla 
- Version of Next.js: 9.3.4
- Version of Node.js: 10.16.3

## Additional context

Some times styles are not loaded and we need to hot reload it is work fine.

**Comment by timneutkens** [comment] 2020-04-27 17:13
Duplicate of #12230. Can you provide all your configuration there?

**Closed by timneutkens** 2020-04-27 17:13 UTC

**Comment by saresh-krish** [comment] 2020-04-28 06:56
hi timneutkens
I have attached all the details in #12230, Can you suggest the solution for that problem.

Thanks 
B.Saresh

**Comment by balazsorban44** [comment] 2022-01-30 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
