### ISSUE TITLE
Example using CSS Blocks

### ISSUE THREAD

**Issue by alexparish** [zeit/next.js#4627] opened 2018-06-17 19:20 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
It would be great to see support for [CSS Blocks](https://css-blocks.com/)

## Describe the solution you'd like
[CSS Blocks](https://css-blocks.com/) is a CSS framework that uses static analysis and dead code elimination to output highly performant stylesheets. Perhaps it could be a good fit for Next.js?

**Comment by arzafran** [comment] 2018-10-27 14:56
Has anyone being able to add cssblocks to a NEXT 7 project? I'm curious about it but not quite sure about how to start.

**Comment by timneutkens** [comment] 2018-10-28 20:41
I guess an example can be made by the community, we won't be adding it as part of the core.

**Comment by Jaace** [comment] 2018-11-10 17:02
Perhaps this is my naivety with this setup, but could one realistically set this up using:
1. The [custom Webpack config](https://nextjs.org/docs/#customizing-webpack-config) with Next.js
2. The [Webpack plugin](https://github.com/linkedin/css-blocks/tree/master/packages/@css-blocks/webpack) for CSS-Blocks.
3. [CSS Blocks JSX Analyzer / Rewriter](https://github.com/linkedin/css-blocks/tree/master/packages/@css-blocks/jsx)

I'm probably overlooking something here and I haven't tried this yet.

**Comment by webbertakken** [comment] 2019-10-03 19:23
I have been looking into this. Currently it looks like this may be harder to implement than it looks.

A few observations:

- The latest release of the package is 2 years old (see [css-blocks](https://www.npmjs.com/package/css-blocks) on npm) however the maintainer still commits on a pretty regular basis.
- This package seems to be barely used, with 5 downloads per week at the time of writing.
- The official docs from css-blocks about [integration using webpack](https://github.com/linkedin/css-blocks/tree/master/packages/@css-blocks/webpack) is based on Webpack 3 and uses deprecated features.

After trying for a good hour, I did not get this to work. Integration may require substantial work and possible updates to the css-blocks repository.

**Comment by Timer** [comment] 2019-10-03 19:28
I believe the right package is https://www.npmjs.com/package/@css-blocks/core, but it still only has 170 downloads.

**Comment by timneutkens** [comment] 2020-01-02 19:54
Going to close this as @timer pointed out the package is not really in use.

**Closed by timneutkens** 2020-01-02 19:54 UTC
Labels: Type: Example, good first issue, help wanted

**Comment by lachieh** [comment] 2020-01-03 02:39
Perhaps one of the core maintainers of @css-blocks would be interested in adding an example.

@chriseppstein What is the timeline for css-blocks? any interest in this? It would certainly promote interest.

**Comment by balazsorban44** [comment] 2022-01-30 17:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
