### ISSUE TITLE
Chose a file separator to replace square brackets []

### ISSUE THREAD

**Issue by gbreux** [zeit/next.js#8013] opened 2019-07-17 12:15 UTC
Hi,

I just encounter an issue after migrated to the new dynamic routing feature and just found the bad news that AWS API gateway doesn't support square brackets in their path.

# Feature request

Add a way to choose a query param separator to replace square brackets

## Is your feature request related to a problem? Please describe.

AWS API gateway doesn't support square brackets in the filename so the dynamic routing is not usable on AWS

## Describe the solution you'd like

Allowing us to chose what separator we would like could fit in the Nextjs config 

`dynamic_separator: '___$QUERY___'`

## Describe alternatives you've considered

I'd love to go on now but unfortunately, this is not an option for this project :/ 
If anyone has a solution to work around this issue, that would be great.

~I've found a little ugly work around in the meantime:~

- ~Replace all known query in the out folder with the encodeURI version: (i.e encodeURI(/[hash]/) will become /%5Bhash%5D/~
- ~Decode the route in the lambda to read the file with the proper name fs.readFileSync(decodeURI(route))~

That was indeed a bad idea, there is too many occurences and sometimes it needs to be as-is in the code.

## Additional context

- https://stackoverflow.com/questions/51941139/aws-api-gateway-returns-400-error-when-square-bracket-is-in-path
- https://forums.aws.amazon.com/thread.jspa?threadID=287209

**Comment by Vadorequest** [comment] 2019-07-18 09:35
Related to a similar issue with a next+aws plugin https://github.com/danielcondemarin/serverless-nextjs-plugin/pull/99

**Comment by c-st** [comment] 2019-09-10 10:27
That convention is not only causing trouble with AWS but also when serving from Spring Boot using Tomcat as application server. Also it seems that square brackets are not valid in URIs according to RFC3986:

https://tools.ietf.org/html/rfc3986?#section-3.2.2
```
A host identified by an Internet Protocol literal address, version 6
[RFC3513] or later, is distinguished by enclosing the IP literal
within square brackets ("[" and "]").  This is the only place where
square bracket characters are allowed in the URI syntax.  In
anticipation of future, as-yet-undefined IP literal address formats,
an implementation may use an optional version flag to indicate such a
format explicitly rather than rely on heuristic determination.
```

For a workaround: it could help to have a proxy (or middleware) rewrite URLs from `**/[fooId]` to `**/%5BfooId%5D`.

**Comment by timneutkens** [comment] 2019-09-10 14:01
Can you try `next@canary` it uses encoded urls.

**Comment by camiblanch** [comment] 2019-11-04 23:48
Looks like encoded urls are now part of the non canary build as of 9.1.2

**Comment by Timer** [comment] 2019-11-05 01:13
Closing as the `latest` has encoded URLs now.

**Closed by Timer** 2019-11-05 01:13 UTC

**Comment by balazsorban44** [comment] 2022-01-31 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
