### ISSUE TITLE
use High-Order-Component to create _document with babel.config.js throws error

### ISSUE THREAD

**Issue by thundermiracle** [zeit/next.js#8173] opened 2019-07-30 12:39 UTC
# Bug report

We need HOC to create _document to reduce repeat coding. But it throws error `TypeError: Class constructor Document cannot be invoked without 'new'` when upgrade to next9.

## Describe the bug

Make a function to create _document dynamically. Use babel.config.js to transpile.

## To Reproduce

An minor repo: 

https://github.com/thundermiracle/next-babel-bug

1. yarn dev

## Screenshots

![image](https://user-images.githubusercontent.com/25689126/62129718-59ddc480-b312-11e9-841a-c89306ad7bc0.png)

## System information

- OS: [Windows]
- Browser (if applies) [chrome]
- Version of Next.js: [9.0.2]

**Comment by timneutkens** [comment] 2019-07-30 12:44
Assuming the problem is https://github.com/thundermiracle/next-babel-bug/blob/master/babel.config.js#L4, but I haven't tried it out. @huv1k / @lfades can check it out

**Comment by huv1k** [comment] 2019-07-30 12:48
This is already fixed in the latest canary.

**Closed by huv1k** 2019-07-30 12:48 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 09:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
