### ISSUE TITLE
[RFC] Plugins, beyond the scope of build configs

### ISSUE THREAD

**Issue by abusada** [zeit/next.js#7507] opened 2019-06-05 13:40 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Currently the [examples](https://github.com/zeit/next.js/tree/canary/examples) directory serves as a great place to learn how to integrate with all these awesome libraries, let's take `styled-components` as an example, to get it working you will need to:

1. `npm i styled-components babel-plugin-styled-components`.
2. Create or Edit `.babelrc`.
3. Create or Edit `_document`.
4. Create or Edit `_app` to add `ThemeProvider`.

and apply this to all the other libraries you would want to integrate with!

Cannot these steps be abstracted into a plugin system? especially that many edit points are common between all integrations.

## Describe the solution you'd like

I think the way Gatsby did it, see example [here](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-styled-components) would be very suitable for nextjs and it's users, so it would be something like this

```
npm install --save nextjs-plugin-styled-components styled-components babel-plugin-styled-components
```

Edit `next.config.js`

```
module.exports = {
  plugins: [
    {
      resolve: `nextjs-plugin-styled-components`,
      options: {
        // Add any options here
      },
    },
  ],
}
```

and 🎉

**Comment by jth0024** [comment] 2019-06-05 17:06
Yes! I asked about this in the Spectrum chat too. I think this would be a great addition. Uber's FusionJS has a similar concept. I've implemented something similar in personal project. Essentially, plugins could return an object with `enhancer` and `middleware`. Enhancer is an HOC used to enhance the App component, and middleware is used to affect the server or the _document markup (via req.ssr). Here's an example:

```javascript
import React from 'react'
import { ServerStyleSheet } from 'styled-components'

export default function styledComponentsPlugin() {
  if (!process.browser) {
    return {
      middleware(req, res, next) {
        const sheet = new ServerStyleSheet()
        const enhancer = App => props => sheet.collectStyles(
          React.createElement(App, props)
        )
        const callback = () => {
          const elements = sheet.getStyleElement()
          elements.forEach(el => req.ssr.addHeadElement(el))
          sheet.seal()
        }

        req.ssr.decorateRender(enhancer, callback)

        next()
      },
    }
  }

  return {}
}

```

My solution is coupled to express, but there's no reason it needs to be.

**Comment by abusada** [comment] 2019-06-06 08:11
@jth0024 Nice!! 

Would love to hear thoughts from the core team on such an addition, i'd gladly work on this.

**Comment by timneutkens** [comment] 2019-10-18 20:34
Closing this in favor of https://github.com/zeit/next.js/issues/9133

**Closed by timneutkens** 2019-10-18 20:34 UTC

**Comment by balazsorban44** [comment] 2022-01-31 01:26
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
