### ISSUE TITLE
Option to disable console clear

### ISSUE THREAD

**Issue by maerzhase** [zeit/next.js#6799] opened 2019-03-27 11:01 UTC
I know there are already issues about it but they are all closed. I checked out the solution in this issue #3159 — which would have been ok for me to use.

But my investigation showed that next-js is actually not using the plugin anymore, hence atm there is not way of disabling the clearing at all.

Shouldn't there be an option in the next-js-config now since you implemented this feature into next-js itself?

**Comment by timneutkens** [comment] 2019-03-27 11:20
Duplicate of #6525

Could you explain why you didn't use the issue template? I'm super curious to track down why people keep ignoring it / don't use it 🙏

**Closed by timneutkens** 2019-03-27 11:20 UTC

**Comment by maerzhase** [comment] 2019-03-27 16:35
sorry, @timneutkens in my case:
I choose "question about next js" and I didn't read it but could see there is a headline and a paragraph. So i thought: "OK don't need a headline, just write my question".

TBH I would just use a template for a complex problem that needs reproduction or any detailed context. What I wouldn't expect is a template that tells me to write a question elsewhere. But of course I get why you do that, because you want to avoid spamming gh with questions. 

In general I think templates are ignored because they are not always a match with your own mental model of describing the problem. Especially if you are not experienced with working on larger codebases and/or teams its not straight forward to figure out the benefit of evenly formatted issues-descriptions and feature-requests.
