### ISSUE TITLE
support for React Router 4+

### ISSUE THREAD

**Issue by laurencefass** [zeit/next.js#9177] opened 2019-10-23 12:45 UTC
this article suggests that React Router was being consider around version 5.
https://react-etc.net/entry/next-js-to-adopt-react-router

is Next supporting the React Router in version 9?

thanks

**Comment by timneutkens** [comment] 2019-10-23 13:00
Not currently. Duplicate of #1632. Please follow the issue template in the future.

**Closed** 2019-10-23 13:13 UTC

**Comment by balazsorban44** [comment] 2022-01-31 01:26
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
