### ISSUE TITLE
"Module parse failed" running next dev in 8.1.1-canary.28

### ISSUE THREAD

**Issue by fionawhim** [zeit/next.js#7344] opened 2019-05-15 15:45 UTC
# Bug report

## Describe the bug

Running `next dev` in my project is causing a `Module parse failed: Unexpected token` error when trying to compile `next/dist/client/next-dev.js`:

```
Module parse failed: Unexpected token (19:6)
You may need an appropriate loader to handle this file type.
|
|
> import('./noop'); // Support EventSource on Internet Explorer 11
|
| if (!window.EventSource) {
```

## To Reproduce

My babel configuration is:

```
{
  presets: [
    [
      'next/babel',
      {
        'preset-env': {
          useBuiltIns: 'usage',
        },
      },
    ],
    '@babel/preset-typescript'
  ],
  plugins: [
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    ['@babel/plugin-proposal-class-properties', { loose: true }],
  ]
}
```

I can reproduce even when my `next.config.js` does not modify the webpack config.

## Expected behavior
Compilation should succeed

## System information
 - Version of Next.js: 8.1.1-canary.28

## Additional context

This is in a Yarn workspace–using monorepo, so the next package gets installed in a `node_modules` that’s a few directories up from where my source is.

**Comment by ijjk** [comment] 2019-05-15 15:57
Hi, I'm not able to reproduce on a non-monorepo so I think it might have to do with that. Could you create a minimal version of your set up that produces the issue? Also, probably not related to this issue but you don't need to add `@babel/preset-typescript` anymore since it's now included in Next.js

**Comment by fionawhim** [comment] 2019-05-15 16:07
@ijjk Sure, lemme try and pare it down.

I still need to have `@babel/preset-typescript` because of the other tooling that I use (Jest, Storybook) that doesn’t go through Next’s build process.

**Comment by ijjk** [comment] 2019-05-15 16:21
Awesome thanks 🙏, by included I mean when you add the `next/babel` it already adds `@babel/preset-typescript`

**Comment by pvdlg** [comment] 2019-05-15 17:57
We have the same issue on version `8.1.0`. Here the babel config we use:
```
{
      "presets": ["next/babel"],
      "plugins": [
        [
          "babel-plugin-react-docgen",
          {"resolver": "findAllComponentDefinitions"}
        ],
        [
          "transform-react-remove-prop-types",
          {"ignoreFilenames": ["src"]}
        ],
        [
          "babel-plugin-styled-components",
          {"displayName": true, "fileName": true, "minify": false, "pure": false, "transpileTemplateLiterals": false}
        ]
      ]
    }

```

**Comment by ijjk** [comment] 2019-05-15 18:17
@pvdlg Are you also using a monorepo setup?

**Comment by fionawhim** [comment] 2019-05-15 18:40
I'm getting closer on this; I think it’s some node_modules / hoisting / different versions thing. When I deleted an app out of my repo that was built on `create-react-app` the problem disappeared. I’m now trying to dig in and pinpoint what dependency change is the culprit.

**Comment by ijjk** [comment] 2019-05-15 18:57
@fionawhim This looks to be the same issue as https://github.com/zeit/next.js/issues/6240

**Comment by fionawhim** [comment] 2019-05-15 19:04
Ah, cool. Thanks for finding that. It looks like the parts of the error that I was searching for weren’t included in that thread.

Do you need more information about the cause of this? Or is just "try to shuffle your dependencies around until #6940 is implemented" all that’s needed?

**Comment by ijjk** [comment] 2019-05-15 19:14
> Or is just "try to shuffle your dependencies around until #6940 is implemented"

This seems to be the case for now, although we have prioritized #6940 
I'm gonna close this issue in favor of the mentioned one, if you have any additional information that you think is helpful feel free to add it to that thread.

**Closed by ijjk** 2019-05-15 19:14 UTC

**Comment by timneutkens** [comment] 2019-05-15 19:15
This is the bug https://github.com/webpack/webpack/issues/8656#issuecomment-456713191

It's an npm bug actually.

I'm going to close this issue in favor of #6240

**Comment by fionawhim** [comment] 2019-05-15 19:37
Yeah, bug in Yarn, too, apparently. Thanks y’all for walking through this with me.
