### ISSUE TITLE
How to minify serverless files?

### ISSUE THREAD

**Issue by VadymBoguslavsky** [zeit/next.js#9333] opened 2019-11-07 09:22 UTC
Hi, i have a question about minification.
As i have read now in next we use Terser plugin to do it, but it seems that i am missing something because i try to catch errors with bugsnag and i need source map and minified files to upload to bugsnag. So the question is how to create source maps for serverless files? For static components its ok, its creating both of it map.js and min.js and uploads completely fine, but for serverless files i cant do it. The thing is when i used Uglify with Terser my error was coming from the path:

`/zeit/8fc9cc9/.next/serverless/pages/webpack:/pages/borked.js`

When i stopped using uglifyJS the error was coming from:

`pages/borked.js`

And the path to get min and map files from next is:

```
publicPath: isServer ? 
                ".next/serverless/"
                : "*/_next/"
```

For Terser plugin the code is

```
if (config.optimization && config.optimization.minimizer) {
            for (const plugin of config.optimization.minimizer) {
              if (plugin['constructor']['name'] === 'TerserPlugin') {
                plugin.options.parallel = true;
                plugin.options.sourceMap = true;
                break;
              }
            }
          }
```

Thanks for your help, I appreciate it.

**Comment by timneutkens** [comment] 2019-11-07 18:53
Duplicate of #9324

**Closed by timneutkens** 2019-11-07 18:53 UTC

**Comment by VadymBoguslavsky** [comment] 2019-11-07 19:48
I opened the issues and choose a question, why did it get closed?

**Comment by timneutkens** [comment] 2019-11-07 23:09
> GitHub Issues are reserved for Bug reports and Feature requests. The best place to get your question answered is to post it on https://spectrum.chat/next-js.

The exact message in the issue template says to post your question on Spectrum.

**Comment by VadymBoguslavsky** [comment] 2019-11-08 09:47
Already did that, zero responses

**Comment by chrisbenincasa** [comment] 2020-04-01 22:46
@VadymBoguslavsky did you ever figure this out? I saw your message on Spectrum as well and there are still no responses.

**Comment by VadymBoguslavsky** [comment] 2020-04-02 12:54
@chrisbenincasa Sorry but no, continuing to using it just like up here :(

**Comment by balazsorban44** [comment] 2022-01-30 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
