### ISSUE TITLE
webpack error: modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

### ISSUE THREAD

**Issue by thian4** [zeit/next.js#7754] opened 2019-07-05 04:10 UTC
I'm not able to use this package https://www.npmjs.com/package/react-preload

I've created a repo https://github.com/thian4/react-preload-nextjs-error using create-react-app and nextjs, in nextjs it failed with error of
```
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

```

**Comment by timneutkens** [comment] 2019-08-10 13:47
Going to close this as it doesn't follow the issue template.

**Closed by timneutkens** 2019-08-10 13:47 UTC

**Comment by balazsorban44** [comment] 2022-01-31 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
