### ISSUE TITLE
Server-side only method to ensure server-only code is never sent to the browser

### ISSUE THREAD

**Issue by Jauny** [zeit/next.js#5354] opened 2018-10-01 19:09 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
Let's say I have a hypothetical `Analytics.js` module which works differently depending on whether we are on the server or in the browser. It dynamically loads a `library-node` or `library-browser` package with an eval for example.

Since it's an analytics module we need it inside most of our components to send events.

I tried to initialise it in getInitialProps like this:

```js
static async getInitialProps({req}) => {
  this.analytics = new Analytics(!!req)
}
```

This allows to correctly load Analytics with server or client side setup, but when loaded on the server side, the code will then be sent to the browser, which will error on unknown code (such as `fs` etc).

## Describe the solution you'd like
It would be nice to have a way to say "here is some code I want ran only on the server because it will break in the browser".
We can already do this with browser code, because we have `componentDidMount` which is only called in the browser, so we know it will never get evaluated on the server. Something similar for server-side would be helpful.

## Describe alternatives you've considered
Right now I'm just loader my module inside component in `componentDidMount` (only in the browser) and abstracted the analytics logic in other non-components modules that are ran in the server, but it's not as flexible and mixes concerns.

## Additional context
n/a

Thanks!

**Comment by HaNdTriX** [comment] 2018-10-01 21:07
Did you try:

```js
if (!process.browser) {
  console.log('this code will only run on the server')
}
```

**Comment by sergiodxa** [comment] 2018-10-02 05:56
`process.browser` as far as I remember is something from webpack and not safe to use. Using `typeof window === 'undefined'` will give you the same result.

**Comment by Jauny** [comment] 2018-10-02 06:03
@HaNdTriX being able to check if I'm in the server or the browser is not really a problem. As you mention we can use process.browser or as sergiodxa mentions check for window.

My issue is that if I do something like `this.analytics = new mylib()`, when the component is rendered server side, the server version of the lib is correctly loaded, _and sent to the browser with it_, so then the browser has issues with it.

What I'm offering here is a way to mark code to be loaded/ran during server side rendering, but then maybe purged before it is sent to the browser.

The more I try to explain this is less it seems plausible tho 🤔

**Comment by hugotox** [comment] 2018-10-06 14:48
can't you move your server logic to the server.js file instead of your component?

**Comment by HaNdTriX** [comment] 2018-10-06 15:50
@sergiodxa As far as I now the behaviour of `process.browser` was changed in next@7. 

So `browser.browser` will now be picked up by the minifier and remove the code.
Please not that this only works at the root scope and with simple if statements.
In addition please note that you`ll need to use the commonjs syntax (see my example above).

https://github.com/zeit/next.js/blob/canary/packages/next/build/webpack.js#L285

Another approach could be to use of dynamic imports (see `ssr` option).

**Comment by rikuayanokozy** [comment] 2018-10-22 22:11
I solved this by add `process.env.IS_SERVER`:
next.config.js: ```js
const webpack = require('webpack');

// unnecessary code, but make your code beautiful
const applyPlugin = (plugins, initialConfig=undefined) => {
  return plugins.reduce(
    (result, plugin) => plugin(result),
    initialConfig);
}

const withProcessEnv = nextConfig => ({
  ...nextConfig,
  webpack(config, {isServer}) => {
    config.plugins.push(
      new webpack.DefinePlugin({
        // ... your process.env injects ...
        'process.env.SERVER': JSON.stringify(isServer),
      }),
    );
    return config;
  },
});

module.exports = applyPlugin([
  withProcessEnv,
  // withLess,
  // withTypescript,
]);
```

in Page.js:```js
class Page extends React.Component {
  render() {
    return `pathname: ${this.props.pathname}`;
  }
}

if (process.env.IS_SERVER) {
  Page.getInitialProps = async ctx => ({
    pathname: ctx.pathname,
  })
}
```

If you're using TypeScript:```ts
interface PageProps {
  pathname: string;
}

class Page extends React.Component<PageProps> {
  render() {
    return `pathname: ${this.props.pathname}`;
  }
}

if (process.env.IS_SERVER) {
  // should be fix after https://github.com/Microsoft/TypeScript/issues/14600 lands
 (Page as any).getInitialProps = async (ctx: Next.NextContext) => ({
    pathname: ctx.pathname,
  });
}
```

**Comment by rikuayanokozy** [comment] 2018-10-23 01:31
I think it still needs a better, official solution to made getInitialProps never been sent to the client for security and bundle size concerns. Maybe we can utilize the compiler's Dead Code Elimination to achieve it (but it never works on class's static method, verified on Terser and GCC)?

**Comment by pengshaosu** [comment] 2018-11-22 03:43
> `process.browser` as far as I remember is something from webpack and not safe to use. Using `typeof window === 'undefined'` will give you the same result.

when `window === 'undefined'``   casuing `ReferenceError: window is not defined`,
`window` can't resolve on server side.

**Comment by pengshaosu** [comment] 2018-11-22 05:03
> @pengshaosu :
> 
> ```
> typeof window === 'undefined'
> ```

thx.
how can disable `getInitialProps ` call only when `next export`,  still working when next build(both csr and ssr). may be i can by `process.env`. any other apporach?

**Comment by constb** [comment] 2018-11-25 11:12
@HaNdTriX really knows what he's talking about. #5159 added code elimination on webpack-level when `process.browser` is referenced. Webpack replaces it with `true` in client build stage, and with `false` when compiling server. Then it's just standard dead code elimination routine… This should probably be documented somewhere, but either way maybe we should close this issue?

**Comment by codyzu** [comment] 2019-01-20 20:35
I found an interesting solution:

1. serve next using an express server as shown [here](https://github.com/zeit/next.js/tree/master/examples/custom-server-express)
2. require whatever server side modules you need inside your `server.js` and add them the `req` via an express middleware

```javascript
const myModule = require('this-only-works-on-the-server');

// ... initialize express + next

server.use((req, res, next) => {
  // now I can access this module inside the getInitialProps function
  req.myModule = myModule;
  return next();
})

server.get('*', (req, res) => {
  return handle(req, res);
})
```

:point_up: this avoids webpack ever trying to include the server side module since the `server.js` file is never imported by webpack.

**Comment by musemind** [comment] 2019-01-28 14:49
Is there a way to use a folder (for example `/server/*`) for server-only code. My `server.js` grows fast.

**Comment by janoist1** [comment] 2019-02-04 12:47
> I found an interesting solution:
> 
> 1. serve next using an express server as shown [here](https://github.com/zeit/next.js/tree/master/examples/custom-server-express)
> 2. require whatever server side modules you need inside your `server.js` and add them to the `req` via an express middleware
> 
> ```js
> const myModule = require('this-only-works-on-the-server');
> 
> // ... initialize express + next
> 
> server.use((req, res, next) => {
>   // now I can access this module inside the getInitialProps function
>   req.myModule = myModule;
>   return next();
> })
> 
> server.get('*', (req, res) => {
>   return handle(req, res);
> })
> ```
> 
> ☝️ this avoids webpack ever trying to include the server side module since the `server.js` file is never imported by webpack.

That's a great idea!!

**Comment by jaydenseric** [comment] 2019-02-04 13:07
The idea in https://github.com/zeit/next.js/issues/5354#issuecomment-455900041 might be ok within a project, but is not particularly viable for published packages as consumers might not have a custom server setup.

For [`next-graphql-react`](https://github.com/jaydenseric/next-graphql-react) I ended up exporting a Next.js plugin that for the client bundle aliases all the server only exports to [empty named exports](https://github.com/jaydenseric/next-graphql-react/blob/v2.0.0/src/universal/ssrAlias.mjs); see [`withGraphQLConfig`](https://github.com/jaydenseric/next-graphql-react/tree/v2.0.0#function-withgraphqlconfig).

I also use the undocumented, but handy, `process.browser` to eliminate client/server code in the relevant bundles: https://github.com/jaydenseric/next-graphql-react/blob/v2.0.0/src/universal/withGraphQLApp.mjs#L85

This used to be inferior to `typeof window !== 'undefined'` checks as Webpack would include a massive `process` polyfill, but I'm pretty sure [that no longer happens in recent Next.js releases](https://github.com/zeit/next.js/pull/5159#discussion_r217931820).

**Comment by janoist1** [comment] 2019-02-04 14:05
> Is there a way to use a folder (for example `/server/*`) for server-only code. My `server.js` grows fast.

Yes. Create a folder `server` move `server.js` to `server/main.js` and update your `package.json` scripts accordingly. For example:

```
    "dev": "node server/main.js",
    "inspect": "node --inspect server/main.js",
    "start": "NODE_ENV=production node server/main.js",
```

**Comment by CodyBrouwers** [comment] 2019-08-12 05:49
For anyone else like me that comes across this thread wondering what they should use, according to this PR https://github.com/zeit/next.js/pull/7651 `process.browser` is now deprecated and the recommended approach is 
```js
typeof window === "undefined"
```

**Comment by Timer** [comment] 2019-08-15 13:33
👆 the above actually results in the code being removed from your client-side bundles.

We have a test to ensure server-only code does not appear in the client bundle: https://github.com/zeit/next.js/pull/8361!

**Closed by Timer** 2019-08-15 13:33 UTC
Labels: Type: Feature Request

**Comment by y0n3r** [comment] 2020-06-25 20:27
@Timer Will the following check work as well?

```js
const hasWindow = () => {
  return typeof window === 'object'
}

if (!hasWindow) {
  // server-side code
}
```

Or does the built-in Next optimization search specifically for when `window` is `undefined`?

**Comment by timneutkens** [comment] 2020-06-26 13:11
It specifically replaces `typeof window` with `'object'` or `'undefined'` based on the environment. This is then shaken away by Terser because it becomes `if(true)` or `if(false)`. So yes you have to use the explicit typeof check instead of creating a function for it.

**Comment by DiscoveryFEE** [comment] 2020-06-26 17:30
> It specifically replaces `typeof window` with `'object'` or `'undefined'` based on the environment. This is then shaken away by Terser because it becomes `if(true)` or `if(false)`. So yes you have to use the explicit typeof check instead of creating a function for it.

I really hate this answer... no offense! It shouldn't evaluate a function at build time like that without an explicit plugin. If this is in fact what's happening, then we should look into removing webpack all together in favor of pure es6 modules.

**Comment by timneutkens** [comment] 2020-06-27 09:33
> I really hate this answer... no offense! 

Not sure what your problem is with the answer... I've explained the behavior that has been there since Next.js 9.1 or so.

> It shouldn't evaluate a function at build time like that without an explicit plugin.

It's not evaluating a function, it's converting a statement that is known to always be a certain value because we take care of the full environment.

> If this is in fact what's happening, then we should look into removing webpack all together in favor of pure es6 modules.

This is a bundle size / performance optimizations that so far has had no issues reported by issuers. It only runs against first-party code so not against node_modules (would have even bigger size wins if we did run it against node_modules however that gave issues with some packages in the ecosystem).

> Is it possible to prevent this or do somewhat of the reverse: use a plugin to swap a placeholder with hasWindow() to be evaluated at runtime?

Why do you want to do that? There is no benefit to it as we know it's always going to be defined client-side.

**Comment by MeghalBisht** [comment] 2020-07-04 12:24
ok

**Comment by DiscoveryFEE** [comment] 2020-07-09 19:38
The "hate" was due to deadline stress. 😉 

I'm still trying to understand this. If I only wanted to evaluate a condition within the _build_ environment, I totally get that the variable `process.env.NODE_ENV` would be replaced with its value during the build. But when NextJS is rendering a page, there is no `window` object on the server. When the same code runs in a browser, there _is_ a `window` object. So why would NextJS bother changing typeof `window !== 'undefined';` when I need it to evaluate at runtime, not build time?

**Comment by DiscoveryFEE** [comment] 2020-07-09 19:44
Sorry, the "hate" was due to deadline pressure. 😉 

> We do tons of optimizations against first-party code that make sure the bundle output is as optimized as possible. E.g. `getStaticProps` and `getServerSideProps` are dropped from client-side bundles as well: https://next-code-elimination.now.sh/

According to `next-code-elimination` above, the hasWindow() function DOES NOT get replaced. It stays in source and gets rendered at runtime like I would expect.

This code block is what I tested:

```
// This app shows what Next.js bundles for the client-side with its new SSG
// support. This editor supports TypeScript syntax.
import Cookies from 'cookies';
import Mysql from 'mysql';
import Link from 'next/link';
import SQL from 'sql-template-strings';
import Layout from '../components/Layout';

const pool = Mysql.createPool(process.env.DATABASE_URL);

const hasWindow = () => {
  return typeof window !== 'undefined';
};

export default function ({ projects }) {
  const env = hasWindow() ? 'browser' : 'server';
  return (
    <Layout>
      <h1 env={env}>Projects</h1>
      <ul>
        {projects.map((project) => (
          <li key={project.id}>
            <Link href="/projects/[id]" as={`/projects/${project.id}`}>
              <a>{project.name}</a>
            </Link>
          </li>
        ))}
      </ul>
    </Layout>
  );
}

export async function getServerSideProps({ req, res }) {
  const userId = new Cookies(req, res).get('user_id');
  const projects = await new Promise((resolve, reject) =>
    pool.query(
      SQL`SELECT id, name FROM projects WHERE user_id = ${userId};`,
      (err, results) => (err ? reject(err) : resolve(results))
    )
  );
  return { props: { projects } };
}
```

This is the result:

```
// This is the code that is bundled for the client-side:

import Link from 'next/link';
import Layout from '../components/Layout';
const hasWindow = () => {
  return typeof window !== 'undefined';
};
export var __N_SSP = true;
export default function ({ projects }) {
  const env = hasWindow() ? 'browser' : 'server';
  return (
    <Layout>
      <h1 env={env}>Projects</h1>
      <ul>
        {projects.map((project) => (
          <li key={project.id}>
            <Link href="/projects/[id]" as={`/projects/${project.id}`}>
              <a>{project.name}</a>
            </Link>
          </li>
        ))}
      </ul>
    </Layout>
  );
}
```

**Comment by DiscoveryFEE** [comment] 2020-07-09 20:03
> @Timer Will the following check work as well?
> 
> ```js
> const hasWindow = () => {
>   return typeof window === 'object'
> }
> 
> if (!hasWindow()) {
>   // server-side code
> }
> ```
> 
> Or does the built-in Next optimization search specifically for when `window` is `undefined`?

@y0n3r `if (!hasWindow()) { ... }` won't get touched according to the next-code-elimination site (https://next-code-elimination.now.sh/)

**Comment by DiscoveryFEE** [comment] 2020-07-09 20:04
@timneutkens thank you for the info and that link!!!

**Comment by timneutkens** [comment] 2020-07-12 12:21
next-code-elimination only shows how the elimination of getServerSideProps/getStaticProps works and doesn't include the other Babel plugin optimizations we run including the one that optimizes `typeof window`. In your example the code would become `return true` in the compiled output for the browser bundles and `return false` in the Node.js bundles

**Comment by balazsorban44** [comment] 2022-01-29 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
