### ISSUE TITLE
Fully static sites

### ISSUE THREAD

**Issue by tylermcrobert** [zeit/next.js#8483] opened 2019-08-22 23:09 UTC
# Feature request

Client-side navigation without `getInitialProps` being called

## Is your feature request related to a problem? Please describe.

<img width="1036" alt="Screen Shot 2019-08-22 at 3 32 11 PM" src="https://user-images.githubusercontent.com/31973492/63555645-9908cb00-c4f6-11e9-8869-d2ea47ab3939.png">

- Headless CMS data is requested on every client-side route, slowing down the site. 

- API keys are visible

## Describe the solution you'd like

I'd like to be able to navigate through a site client-side (for page transitions) without having data requests in `getInitialProps` 

## Describe alternatives you've considered

- Gatsby
- if statements inside `getInitialProps()` that only runs requests on the server. Results in an error, `An unexpected error has occurred.`

**Comment by timneutkens** [comment] 2019-08-23 18:17
Duplicate of #5903

**Closed by timneutkens** 2019-08-23 18:17 UTC

**Comment by balazsorban44** [comment] 2022-01-31 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
