### ISSUE TITLE
Problem with customer server

### ISSUE THREAD

**Issue by Andrei997** [zeit/next.js#1433] opened 2017-03-15 19:31 UTC
Hi guys I am having this weird problem with my custom server where I am getting this message in the terminal
> Client pings, but there's no entry for page: /recordings
> Building page: /recordings
 The page resorts to an error the renders again. 
 
After this however I am getting this error when navigating to a page that has the getInitialProps method.
TypeError: _regenerator2.default.mark is not a function

[server.js.zip](https://github.com/zeit/next.js/files/845786/server.js.zip)

I've uploaded my custom server here. Also, this never happens without the custom server

**Comment by timneutkens** [comment] 2017-03-15 19:44
@Andrei997 can you please provide a repository with more than the server.js. I have a feeling you are using `next/link` `<Link href="/recordings/something">` without `as`

**Comment by arunoda** [comment] 2017-03-15 20:23
You need to allow `_next/*` and `_webpack/*`  paths to serve via `app.handle(req, res)`.

**Comment by Andrei997** [comment] 2017-03-15 20:28
Could you give me an example of that ? I don't really see how am I stopping them since I am passing control to `app.handle(req,res)` via `server.get(*, ...)`

**Comment by arunoda** [comment] 2017-03-15 21:27
@Andrei997 You need to do that on the top of the routing rules.

**Comment by Andrei997** [comment] 2017-03-15 21:34
@arunoda 
Adding this at the top of the routes doesn't solve the issue. They are getting called, but the problem isn't solved.
`server.get(/next/, (req,res)=> {
        console.log("next");
        handle(req,res);
    });

    server.get(/webpack/, (req,res)=> {
        console.log("webpack");
        handle(req,res);
    });`

**Comment by timneutkens** [comment] 2017-03-15 21:45
1. clone repo
2. `npm install`
3. `node server.js`
4. navigate around

I tried the above steps, couldn't reproduce.

**Comment by Andrei997** [comment] 2017-03-15 21:50
did you try the recordings page ? 
<img width="1077" alt="screen shot 2017-03-15 at 22 48 23" src="https://cloud.githubusercontent.com/assets/15995496/23972357/bc393b38-09d1-11e7-9921-8abd13fbfb7a.png">
<img width="835" alt="screen shot 2017-03-15 at 22 49 03" src="https://cloud.githubusercontent.com/assets/15995496/23972356/bc38e304-09d1-11e7-909f-91d0ba6ad4e8.png">
<img width="1059" alt="screen shot 2017-03-15 at 22 48 48" src="https://cloud.githubusercontent.com/assets/15995496/23972358/bc398d36-09d1-11e7-9007-5f239577b3b8.png">

**Comment by timneutkens** [comment] 2017-03-15 22:16
@Andrei997 yeah I did click the recordings page. Also clicked an item on that page. All worked fine. Strange!

**Comment by arunoda** [comment] 2017-03-16 04:53
Hey @Andrei997 the logs on the server console looks fine.
This happens when you re-start the dev server. First it tries to load the page which we haven't built and then it builds it.

The client side error might due to the babel issue.
Try creating a `.babelrc` file in your root of the project and add it:

```
{
   "presets": ["next/babel"]
}
```

**Comment by Andrei997** [comment] 2017-03-16 06:26
@arunoda Hey, no help with the babel config file. I am still getting this weird error on the client side, accompanied by these: 
<img width="1280" alt="screen shot 2017-03-16 at 07 10 00" src="https://cloud.githubusercontent.com/assets/15995496/23984358/730b1df8-0a19-11e7-8f5a-f9450278d2d8.png">

When loading the page from the server everything is okay but navigating from the client side brings up these errors.

**Comment by timneutkens** [comment] 2017-03-16 07:11
What command are you using to start the server?

**Comment by Andrei997** [comment] 2017-03-16 07:14
'node server.js'

**Comment by guidiego** [comment] 2017-03-16 17:25
@arunoda @timneutkens @Andrei997 videojs not exist into server render, it's a CDN library, possible next are crashing when Andrei tries to apply `videojs()` into the code without this on global :)

**Comment by Andrei997** [comment] 2017-03-16 17:34
@guidiego purely genius. I've removed the video js and it works now. 
Do you have any suggestions where i should include it ? Maybe a custom _document page ?

**Comment by timneutkens** [comment] 2017-03-16 17:40
You could use next/head Or custom document. Closing this as it's not related to next.js functionality

**Closed by timneutkens** 2017-03-16 17:40 UTC
Labels: Can't Reproduce, Type: Question

**Comment by guidiego** [comment] 2017-03-16 17:47
@Andrei997 you can try another lib that be required and not injected by CDN, or, you can validate if this exists, and let react do the job when loaded in client side :)

Something like:

```
import React, {Component} from 'react';
import ReactDOM from 'react-dom';

class VideoPlayer extends Component {
    componentDidMount() {
        let category = this.props.category;
        let date = this.props.date;

        console.log(category + " " + date);

        //vars
        let video, wrapper, location;
        location = `https://s3.amazonaws.com/recording.tissuu.com/${category}/${date}.mp4`;

        //creating the element
        wrapper = document.createElement('div');

        //adding innerHTML
        wrapper.innerHTML = `<video class="video-js vjs-default-skin"
        id="video-player"
        controls
        width="400"
        height="360"
        preload="metadata">
            <source src="${location}"/>
        type='video/mp4'
            </video>`;

        //getting the element
        video = wrapper.firstChild;

        //mounting it with react dom
        ReactDOM.findDOMNode(this.videoContainer).appendChild(video);

        //setup
        if (videojs) {
            videojs('video-player', {"playbackRates": [1, 1.3, 1.5, 2]}, function() {
                this.hotkeys({
                    alwaysCaptureHotkeys: true
                });
            })
        }
    }

    componentWillUnmount() {
        if (videojs) {
            let player = videojs('video-player');
            player.dispose(()=> {
                console.log("disposed");
            })
        }
    }

    render() {
        return (
            <div className="player-page">
                <div className="row">
                    <div className="col-md-10 col-md-offset-1">
                        <div id="video-container" ref={(div)=> this.videoContainer = div}></div>
                    </div>
                </div>
            </div>
        )
    }
}


export default VideoPlayer
```

**Comment by Andrei997** [comment] 2017-03-16 17:49
That seems like a great idea. I've also tried adding it to the head of the _document page and it also works. Thanks for finding this issue i was losing my mind :D
