### ISSUE TITLE
Error when trying out the "With Styled Components" example

### ISSUE THREAD

**Issue by pencilcheck** [zeit/next.js#2390] opened 2017-06-28 16:17 UTC
Following `https://github.com/zeit/next.js/tree/v3-beta/examples/with-styled-components`

Then I get this error when launching
`Nesting detected at 1:757. Unfortunately nesting is not supported by styled-jsx.`

```
500
Internal Server Error.
Nesting detected at 1:757. Unfortunately nesting is not supported by styled-jsx.
Error: Nesting detected at 1:757. Unfortunately nesting is not supported by styled-jsx.
    at Function.disableNestingPlugin (/node_modules/styled-jsx/dist/lib/style-transform.js:19:13)
    at proxy (/node_modules/stylis/stylis.js:1133:30)
    at compile (/node_modules/stylis/stylis.js:679:10)
    at compile (/node_modules/stylis/stylis.js:319:17)
    at stylis (/node_modules/stylis/stylis.js:1270:16)
    at stringifyRules (/node_modules/styled-components/lib/utils/stringifyRules.js:27:31)
    at ComponentStyle.generateAndInjectStyles (/node_modules/styled-components/lib/models/ComponentStyle.js:59:24)
    at StyledComponent.generateAndInjectStyles (/node_modules/styled-components/lib/models/StyledComponent.js:121:38)
    at StyledComponent.componentWillMount (/node_modules/styled-components/lib/models/StyledComponent.js:150:39)
```

**Comment by timneutkens** [comment] 2017-06-28 16:58
Duplicate of https://github.com/zeit/next.js/issues/2304

**Closed by timneutkens** 2017-06-28 16:58 UTC
