### ISSUE TITLE
Escaping problem with meta tags

### ISSUE THREAD

**Issue by Balamir** [zeit/next.js#2006] opened 2017-05-18 08:23 UTC
Hi,

I'm facing an issue with meta tags. When I use some special characters like single quote in the head tag, it's escaping. I can not use `dangerouslySetInnerHtml` for meta tags.

in code:
`<meta name="description" content="That's it!" />`

result:
`<meta name="description" content="That&#x27;s it!" />`

How can I handle with this? I couldn't find any solution about this problem.

Thanks.

**Comment by arunoda** [comment] 2017-05-18 22:14
@Balamir could you give us some code for this?

**Comment by Balamir** [comment] 2017-05-18 23:53
@arunoda thanks for the reply.

I just tried this with your [head-elements](https://github.com/zeit/next.js/tree/v3-beta/examples/head-elements) example.

Simply I added above meta:

```
import Head from 'next/head'

export default () => (
  <div>
    <Head>
      <title>This page has a title 🤔</title>
      <meta charSet='utf-8' />
      <meta name="description" content="That's it!" />
      <meta name='viewport' content='initial-scale=1.0, width=device-width' />
    </Head>

    <h1>This page has a title 🤔</h1>
  </div>
)
```
and the result:

![snip20170519_2](https://cloud.githubusercontent.com/assets/116791/26227873/eabfcd8e-3c3d-11e7-83e2-ae830d5f7d1d.png)

Thanks.

**Comment by arunoda** [comment] 2017-05-19 00:27
Thanks. I'll see what's happening here.

**Comment by Balamir** [comment] 2017-05-19 07:26
@arunoda By the way, I couldn't reopen this issue. It's still closed.

Thanks.

**Comment by Rupeshn73** [comment] 2017-07-14 11:06
This Issue still exist .For single quote it is rendering as `&#x27;`

> clothing,men's shoes,men's accessories,women's clothing,women's shoes,jewelry,women's handbags,women's accessories,dogs,furniture,home and decor,kitchen and dining

![meta](https://user-images.githubusercontent.com/16379335/28209936-8bbdfecc-68b2-11e7-8576-50566df3c478.png)

**Comment by damusnet** [comment] 2017-08-04 17:39
The same is true for urls. 

Adding `<meta property="og:image" content="http://example.com?foo=bar&bar=baz" />` results in `<meta property="og:image" content="http://example.com?foo=bar&amp;bar=baz" class="next-head"/>`.

Notice the encoded `&amp;`. Any way around that?

**Comment by poohitan** [comment] 2018-01-05 16:34
I'm facing the same issue. Are there any updates on it?

**Comment by timneutkens** [comment] 2018-01-08 09:28
I'm expecting this is an upstream React SSR issue, since we don't escape values afaik.

**Comment by donaminos** [comment] 2018-03-09 14:31
Running through the same issue. any workaround please ?

**Comment by stefl** [comment] 2018-05-19 15:38
I've made a workaround by post-processing the generated HTML and using a regex for the attributes that are incorrectly encoded with HTML entities:

https://gist.github.com/stefl/1f8c246dd7ca9cb332ae41f68e80088d

Obviously not a long-term fix but it means that my Opengraph metadata is now not affected by this. Hope this is of use to others here!

**Comment by oliviertassinari** [comment] 2018-10-12 12:01
Please track https://github.com/facebook/react/issues/13838.

**Comment by mrasoahaingo** [comment] 2019-01-15 13:33
Still have the same issue...

**Comment by timneutkens** [comment] 2019-01-15 13:42
@mrasoahaingo it's not really relevant to post "same issue", as @oliviertassinari said it's an upstream issue. If the issue is open you can consider it's still there an not solved, so saying "same issue" is not really useful, if you want to "+1" an issue use GitHub's reaction system on the initial post to 👍

Thanks.

**Comment by equinusocio** [comment] 2019-07-26 08:20
@timneutkens After 2 years it's normal to see people saying that the issue still there.

**Comment by timneutkens** [comment] 2019-07-26 11:08
The last comment before the "same issue" clearly said it's a bug in React, the issue on React's side is still open, hence why it's not valuable to say something along the lines of "Same issue...", it doesn't add value, this is why the emoji reactions exist in GitHub.

**Comment by equinusocio** [comment] 2019-07-26 12:04
Who open the issue report a "workaround"

```js
import Entities from 'html-entities/lib/html5-entities'

const entities = new Entities()
const contentRegExp = /content="([^"]+)"/g
const handleContent = (match, content) => {
  return `content="${entities.decode(content)}"`
}

html = html.replace(contentRegExp, handleContent)
```

But i can't figure out how to make it works with next

**Comment by equinusocio** [comment] 2019-07-27 10:03
React Helmet has a `encodeSpecialCharacters` boolean prop to disable the encode server side. Can it be done on next-head too?

**Comment by timneutkens** [comment] 2019-07-27 10:36
Seems like Helmet completely bypasses React, which doesn't seem like a good idea imo.

**Comment by equinusocio** [comment] 2019-07-27 11:05
😕Adding a temp workaround to re-encode the paths after react?

**Comment by timneutkens** [comment] 2020-01-02 19:42
Closing this as it's tracked on React: https://github.com/facebook/react/issues/13838

**Closed by timneutkens** 2020-01-02 19:42 UTC
Labels: Is Upstream, Type: Bug

**Comment by vxcamiloxv** [comment] 2020-08-24 17:19
@DesignMonkey yes, my final solution was `<script ype="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(json) }}`

**Comment by DesignMonkey** [comment] 2020-08-24 17:33
@vxcamiloxv Oh yea sure... Maybe that was the solution I ended up with as well :)

**Comment by YoannBuzenet** [comment] 2021-05-04 09:43
@oliviertassinari Where do you put this code ? I understand it's a react problem, but where do you parse the meta tag on Next.js ? If I do it on my page, I still have the escaped text in my <head>.

Example :
`// Parsing meta tag string to remove html entities
  const escapeRegExp = /(content|href|src|srcSet)="([^"]+)"/g;
  const escapeHandle = (match, attribute, value) => {
    return `${attribute}="${decode(value)}"`;
  };

  const metaTagEscaped = "default-src * 'self' data: 'unsafe-inline' 'unsafe-eval' *; child-src * 'self' data: 'unsafe-inline' 'unsafe-eval' *; script-src 'unsafe-inline' 'self' https://js.stripe.com/v3".replace(
    escapeRegExp,
    escapeHandle
  );

`

`      <Head>
        <title>{translatedPageTitle}</title>
        <meta
          http-equiv="Content-Security-Policy"
          content={metaTagEscaped}
        ></meta>
      </Head>`

This doesn't work and still gives me escaped characters.

@dzinemon so you write a meta tag this ay ? I don't get how to implement it.

**Comment by jasonfarrell** [comment] 2021-08-17 23:25
Found a workaround for `&amp;` in the image url in next.js — the main issue was the imgix params in the URL weren't sticking, due to the escaped ampersands. So I took the properties out of the meta tag, and wrote a backend proxy to deliver the image data directly:

So in your template:

`const shareImage = myfile.jpg // without any query params`

```
<meta property="og:image" content={`/api/share?image=${shareImage}`} />
```
Then in `api/share.js`:
```
import request from 'request'

export default async function share(req, res) {
  const { image } = req.query
  if (image) {
    request
      .get(image + '?fm=jpg&q=80&w=1402&h=738&fit=crop&crop=faces,edges')
      .pipe(res)
  } else {
    res.status(404).json({})
  }
}
```

Probably need to validate the incoming url, otherwise it could be open for malice, but this fixes the issue until this is merged in: https://github.com/facebook/react/issues/13838

**Comment by equinusocio** [comment] 2021-08-18 05:50
> Found a workaround for `&amp;` in the image url in next.js — the main issue was the imgix params in the URL weren't sticking, due to the escaped ampersands. So I took the properties out of the meta tag, and wrote a backend proxy to deliver the image data directly:
> 
> 
> 
> So in your template:
> 
> 
> 
> `const shareImage = myfile.jpg // without any query params`
> 
> 
> 
> ```
> 
> <meta property="og:image" content={`/api/share?image=${shareImage}`} />
> 
> ```
> 
> Then in `api/share.js`:
> 
> ```
> 
> import request from 'request'
> 
> 
> 
> export default async function share(req, res) {
> 
>   const { image } = req.query
> 
>   if (image) {
> 
>     request
> 
>       .get(image + '?fm=jpg&q=80&w=1402&h=738&fit=crop&crop=faces,edges')
> 
>       .pipe(res)
> 
>   } else {
> 
>     res.status(404).json({})
> 
>   }
> 
> }
> 
> ```
> 
> 
> 
> Probably need to validate the incoming url, otherwise it could be open for malice, but this fixes the issue until this is merged in: https://github.com/facebook/react/issues/13838
> 
> 

Thanks. Unfortunately i don't think that issue on Fb will merged. It is 3yrs old.

**Comment by mislavmiocevic** [comment] 2022-01-24 11:19
I used the Next.js `_document` file to replace all the `&amp;` occurrences. I am using some code from @stefl gist.
The main point is to use `_document` to handle this issue, so please ignore the code.

My use case were images with w and h query parameters being incorrectly used by the crawlers since those pages were made with getStaticProps and they all had `&amp;` instead of `&`.

```
// _document.tsx

import { decode } from 'html-entities';
const srcRegex = /src="([^"]+)"/g;
const srcSetRegex = /srcSet="([^"]+)"/g;

const decodeHtmlEntities = (html: string): string =>
	html
		.replace(srcRegex, (match: string, content: string) => {
			return `src="${decode(content)}"`;
		})
		.replace(srcSetRegex, (match: string, content: string) => {
			return `srcSet="${decode(content)}"`;
		});

class MyDocument extends Document {
	static async getInitialProps(ctx) {
		const initialProps = await Document.getInitialProps(ctx);
		const html = decodeHtmlEntities(initialProps.html);

		return { ...initialProps, html };
	}
	
	...
```

```
// encoded.tsx page

const Page = () => {
	const imageUrl = 'https://makelight-prismic-images.imgix.net/7f97d951970bbb15a8b3744e4c69499ffe969d66_img_1010.jpg';
	const defaultImageParameters = 'w=1024&h=768';
	const largeImageParameters = 'w=1920&h=1080';
	const src = `${imageUrl}?${defaultImageParameters}`;

	console.log(src);

	return <img alt="Some image" src={src} srcSet={`${src} 1024w, ${imageUrl}?${largeImageParameters} 1920w`} />;
};

export default Page;

```

See the images attached. First one is showing before the replace, and second one with the fix. Third one is to show also srcSet.
There are also Node and Chrome logs showing how they didn't have issue anyway.

![After fix](https://user-images.githubusercontent.com/67387665/150773225-e6dba8fa-e01d-4da4-9a9e-627feff0c660.png)
![Before fix](https://user-images.githubusercontent.com/67387665/150773238-2f5a638a-168c-43cb-bd5c-240c9a511605.png)
![srcSet](https://user-images.githubusercontent.com/67387665/150773243-b1906b60-0c50-4450-a26f-7da8b8b7414e.png)

@timneutkens is using _document to do this replace okay?
