### ISSUE TITLE
Create dynamic routes that contain a constant character/word in Next.js

### ISSUE THREAD

**Issue by ShahinGh** [zeit/next.js#10411] opened 2020-02-04 07:10 UTC
# Feature request

I want to create routes that start with @ symbol how should I structure the pages folder? first I tried to create a folder with @ as its name however it will create routes that proceed with @ like www.example.com/@/something. I even tried **[@topic]** and **@[topic]** names for folders but it does not work as expected.

I want to have routes like
_www.example.com/@computer,
www.example.com/@music,
www.example.com/@programming_

## Is your feature request related to a problem? Please describe.
If someone wants to create dynamic routes that contain a constant character/word in their structure, this limits their ability to do so. Current approaches have not the capability to create dynamic routes that have a constant part in it.

## Describe the solution you'd like
I'm looking for a way of structuring the "pages" folder that will match URLs that start with "@" symbol. something like this:   
**pages --> @[topic]**  
or
**pages --> [@topic]**

## Describe alternatives you've considered
For now, I'm forced to have my routes like www.example.com/@/topic but this is not what I wanted.
because we before planned to split the topics based on www.example.com/@topic  pattern.

**Comment by Timer** [comment] 2020-02-04 13:25
The solution to this will use the #9081 RFC!

You'll create a re-write that renders `pages/_internal/topic/[topic].js` or similar.

Closing in favor of that RFC.

**Closed by Timer** 2020-02-04 13:25 UTC

**Comment by balazsorban44** [comment] 2022-01-30 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
