### ISSUE TITLE
Support for SSR only on the first page load, with SPA for every navigation after that.

### ISSUE THREAD

**Issue by ajhool** [zeit/next.js#13157] opened 2020-05-20 18:35 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Next does not really feel like a SPA because each page requires a full refresh and reloads the app bar, drawers, etc. Additionally, it is not as fast as an SPA because each new page requires a request to the server.

## Describe the solution you'd like

The only reason that we use SSR is for search engine indexing on first page load. Thus, it would be fantastic if there was a mode to only do SSR on the first page load. Afterwards, everything would just use the standard SPA flow. This would meet the search-engine indexing requirement while fully leveraging SPA benefits for the customer.

## Describe alternatives you've considered

I have not been able to think of any good alternatives.

## Additional context

This would be an ecommerce site with hundreds of thousands of products. There is also authentication and some social-media type content.

**Comment by Timer** [comment] 2020-05-20 19:44
Could you please share a demo? Your request is exactly how Next.js already works.

Pages are server-side rendered (or prerendered), and then your application turns into a full SPA.

It sounds like you might be using the framework wrong.

**Comment by illuminist** [comment] 2020-05-21 10:38
From my experience where I misused Router and Link and it caused the app to request a page from server again.

For example:

```jsx
```

**Comment by Onibenjo** [comment] 2020-05-22 10:05
and to avoid full refresh of the appbar and drawers, you could create a custom app and wrap the layout component over the page component

```javascript
import App from "next/app"
import Head from "next/head"
import Layout from "./somewhere"

export default class MyApp extends App {
  render() {
    const { Component, pageProps } = this.props
    return (
      <>
        <Head>
          <title>Title</title>
          <meta
            name="viewport"
            content="minimum-scale=1, initial-scale=1, width=device-width"
          />
        </Head>
          <Layout>
            <Component {...pageProps} />
         </Layout>
      </>
    )
  }
}
```

**Comment by robgraeber** [comment] 2020-05-22 12:04
Here's a blog post with all the ways to have shared layouts that persist between pages: https://adamwathan.me/2019/10/17/persistent-layout-patterns-in-nextjs/

**Comment by dercoder** [comment] 2020-05-26 18:24
I got the same problem here: https://github.com/zeit/next.js/issues/11065

**Comment by timneutkens** [comment] 2020-05-27 08:55
Closing this issue as no reproduction was provided. It's likely this https://github.com/zeit/next.js/issues/13157#issuecomment-632014350

**Closed by timneutkens** 2020-05-27 08:55 UTC
Labels: Please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-30 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
