### ISSUE TITLE
getInitialProps not working with history (back button)?

### ISSUE THREAD

**Issue by tomsoderlund** [zeit/next.js#3065] opened 2017-10-10 12:11 UTC
I have an app with a single page `index.js`, and I parse the query parameters in `getInitialProps`:

	static async getInitialProps ({query}) {
		console.log('PAGE', query.screenId);
		try {
			const projectData = await ProjectLoader.loadProject(query);
			return projectData;
		}
		catch (err) {
			console.error(err);
		}
	};

I use `<Link href={pathname, query} prefetch>` tags to build my links.

The `screenId` property is key to finding the right page to render.

However, when I use the back button in the browser to a page without `screenId` set, `getInitialProps` doesn’t return `screenId:undefined` as expected, but another value (as you can see in the console log):

[![getInitialProps not working with history][1]][1]

When I refresh the page, I get the right properties and see the correct results.

The “imaginary” `screenId` is actually a valid value, but I have no idea where this value comes from.

Why is this happening?

  [1]: https://i.stack.imgur.com/pWUXE.gif

**Comment by liweinan0423** [comment] 2017-11-15 09:14
This is interesting to me as I am facing a similar issue with "back button". Could you try using the latest version of next.js and share your repo if possible?

**Comment by anselmdk** [comment] 2017-12-22 00:10
We're facing similar issues, any pointers would be appreciated.

**Comment by tomsoderlund** [comment] 2017-12-22 09:32
This may not be the solution to the above problem, but the last few days I had a big “a-ha” moment with the `<Link>` component when you’re using custom routing:

You need both `href` and `as` properties, they both need to be valid, and they will most likely to be different from each other(!).

Example: `<Link href={'/mynextjspage?articleId=' + articleId} as={'/articles/' + articleId}>`

`as` will be the link as you _want_ it to appear, while `href` will be a reference to a Page component in the `/pages`folder with parameters added with query string.

@liweinan0423 @anselmdk Are you using custom routing?

**Comment by anselmdk** [comment] 2017-12-23 20:24
I think our issue is that we use one central dispatcher (`pages/dispatcher.js`). The dispatcher decides which components to load, based on the url (we're loading data from an API behind the scenes).
This works perfectly until we start hitting the browser's "back" button. Then you're redirected to a random page. It seems like the issue is that our links look like this:

```jsx
<Link
  href="/dispatcher"
  as="/page/about"
>
  <a>home</a>
</Link>
```

The `href` is always set to `/dispatcher` on all pages.

I've looked a little into other issues, and it seemed like the solution mentioned [here](https://github.com/zeit/next.js/issues/2668) would solve it. In short the idea is to append a unique query string, which would then make `href` look like something like this: `/dispatcher?pretty=url1`. Unfortunately that triggers another problem - the links just stop working (clicking them does nothing). I've isolated the issue by taking the code from https://github.com/zeit/next.js/tree/master/examples/parameterized-routing and making it run on one file only:

```jsx
import React from 'react'
import Link from 'next/link'

export default class extends React.Component {
  static getInitialProps ({ query }) {
    return { id: query ? query.id : 'error'}
  }

  render () {
    return <div>
      <h1>My {this.props.id} blog post</h1>
      <ul>
        <li><Link href='/test?id=first' as='/test/first'><a>My first blog post</a></Link></li>
        <li><Link href='/test?id=second' as='/test/second'><a>My second blog post</a></Link></li>
        <li><Link href='/test?id=third' as='/test/last'><a>My last blog post</a></Link></li>
      </ul>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua.
      </p>
    </div>
  }
}
```

Clicking any of the three links does nothing. When the query strings are removed from the links (so `href` only contains `/test`) it works fine again - unless the history part. A funny observation is that when after removing them you add them back in, and the component is hot reloaded, both links and history work - until you refresh the page.

I hope anyone's had similar issues and/or can point us into a direction for solving this.

**Comment by smdevdk** [comment] 2017-12-23 21:16
I am having the same issue..

**Comment by AshishKapoor** [comment] 2018-01-15 11:28
Same here.

**Comment by EvanDylan** [comment] 2018-01-31 07:39
Does anyone solved this problems?

**Comment by adamyonk** [comment] 2018-01-31 13:06
@anselmdk are you using a custom server to handle that sort of routing? Might be helpful to see that as well.

**Comment by adamyonk** [comment] 2018-01-31 13:07
@anselmdk / @tomsoderlund are you using a custom server to handle that sort of routing? Might be helpful to see that as well.

**Comment by anselmdk** [comment] 2018-01-31 19:56
So, because nobody answered, neither here nor on Slack, we solved this issue by creating a custom version of `link.js`. 
I think all we did was to change https://github.com/zeit/next.js/blob/canary/lib/link.js#L75
to `Router[changeMethod](href + '?uri=' + as, as, { shallow })`.
Feels a bit hacky, but it works :)

**Comment by mashaal** [comment] 2018-04-02 23:48
@anselmdk can verify this works for the `Link` component, but if using `Router.push/replace` the issue still persists.

I updated the `Router` component with the following. 

```
  push(url, as = url, options = {}) {
    return this.change('pushState', url + '?uri=' + as, as, options)
  }

  replace(url, as = url, options = {}) {
    return this.change('replaceState', url + '?uri=' + as, as, options)
  }
```

and you can use it like this ```Router.push('/', pathname)```

**Comment by wallynm** [comment] 2018-08-13 20:33
I'm getting same error, tried to update to 6.1.1 but won't fix.
Also tried to set `useFileSystemPublicRoutes: false` and didn't changed anything on the app.
I'm redirecting this way in my app but once i hit the back button the component don't fire the getInitialProps:
```
const cartId = 20;
Router.push(`/step2?cartId=${cartId}&hashId=asd`, `/next/${cartId}/asd`)
```

I've also tried with shallow but no success:
```
const cartId = 20;
Router.push(`/step2?cartId=${cartId}&hashId=asd`, `/next/${cartId}/asd`, { shallow: true })
```

**Comment by HaNdTriX** [comment] 2018-08-19 16:42
Hey guys

I tried to reproduce your example but could not verify it.

**Example:**

* [source](https://zeit.co/handtrix/data-fetch/ixbnrmwfyr/source)
* [example](https://data-fetch-ixbnrmwfyr.now.sh/)

Got you issue resolved in the meantime or did I do something wrong?

**Comment by OscarBengtsson** [comment] 2018-08-23 19:31
@HaNdTriX It works well inside App routing but not with external link.
If you navigate to external url(e.g. github) and click back button, you see `getInitialProps` is not called.

**Comment by OscarBengtsson** [comment] 2018-08-24 03:55
Guys, is there any cool solution or alternatives? It's a really block at my project.

```
class Profile extends React.Component {
    // Update the profile avatar and show updated avatar
}
Profile.getInitialProps = () => {
    // Call api to get profile information
}
```

When I update the profile avatar and navigate to external url(e.g. `terms` pdf url) and click back button, it shows the previous avatar as `getInitialProps` is not called.
`Router.replace()` after updating Avatar, didn't help me.

**Comment by HaNdTriX** [comment] 2018-08-27 22:30
Ok I finally could reproduce the issue. 

The issue is only existent in the browsers Safari & Firefox. These browsers use a feature called "bfcache" (back-forward cache). This means the html document is cached in memory. As soon as a user uses a back button coming from an external page, no request is made on the server. Instead the html document is rendered from the cache. Since `getInitialProps` already ran (before it was cached) it won't run again.

The only way I know of, to disable this behaviour is to add a cache buster.
This can be done, by setting the following http header:


```js
...
static getInitialProps ({ res }) {
  if (res) {
    res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate')
  }

  return {}
}
...
```

More info: https://developer.mozilla.org/en-US/docs/Archive/Misc_top_level/Working_with_BFCache

**Comment by DontRelaX** [comment] 2018-08-27 22:59
If you are experiencing issue that `getInitialProps` not invoked when user click back between same pages you can use next code (somewhere during bootstrap on frontend):
`Router.beforePopState(({url, as}) => Router.replace(url, as, {}));`

**Closed** 2018-09-03 13:26 UTC

**Comment by wallynm** [comment] 2018-09-17 16:42
Guys, finally i've better understood my problem. Im using Next 7.0 canary to see if latest updates work.

Im my project im using custom routing and my first URL is `/start/:id/:hash`
When i change route to `next/:id/hash` it works correct
```js
Router.push({
    pathname: '/step2',
    query: { id: cartId, hash: 'asd' }
}, `/next/${id}/${hash}`)
```

Once i got back using chrome back button the route stop working as expected, the initialProps doesn't receive the params vars, They do work in step2 that i've redirect but once popstate gets called it doesnt receive any params option, because it was the first rendered page and next router didn't received any options as first render... 

To solve this im splitting url, it's temporally until i found a way to solve this.

**Comment by DontRelaX** [comment] 2018-09-17 20:17
@wallynm did you try my solution above? Looks very similar to what I faced.

**Comment by timneutkens** [comment] 2018-09-19 20:10
I'm wondering if you're using `next export` or not? If you're not there's definitely something else going on and we should investigate that further, as replacing on initial render is not the correct solution.

**Comment by wallynm** [comment] 2018-09-20 03:27
I don't know for sure what is this config. Quick search and found this:
https://github.com/zeit/next.js/issues/604
I don't using anything like that, but let me explain a little about my current config:

I'm using custom routing integrated with Express:

```js
const app = next({ dev, dir: './src' })
const handle = app.getRequestHandler()
const bodyParser = require('body-parser')
const cookieParser = require('cookie-parser')
const compression = require('compression');

const render = function(req, res, page) {
  const parsedUrl = parse(req.url, true)
  const { pathname, query } = parsedUrl
  return app.render(req, res, page, query)
}

app.prepare().then(() => {
  const server = express()
  if (process.env.NODE_ENV === "production") {
    server.use(compression());
  }

  server.get('/start/:id/:hash', (req, res, next) => render(req, res, '/step1'))
  server.get('/next/:id/:hash', (req, res, next) => render(req, res, '/step2'))
})
```

**Comment by timneutkens** [comment] 2018-09-20 09:40
No worries, was just making sure people won't come here in the future and copy-paste a workaround that probably introduces performance issues 🙏

**Comment by wallynm** [comment] 2018-09-20 17:46
Of course @timneutkens , if you like i can remove these comments as they may not help future users!

**Comment by timneutkens** [comment] 2018-09-20 19:07
Looks like GitHub has a `hide` feature to minimize the comment, just tried it on your comment and looks perfect 🙌

**Comment by johanleroch** [comment] 2019-02-22 19:17
Hi,

I tried this and It worked for me. Let me know if this is fixing yours.

You have to put Router.beforePopState() in _app.js -> componentDidMount()
`
import React from 'react';
import App, { Container } from 'next/app';
import Router from 'next/router';

class MyApp extends App {
  componentDidMount() {
    Router.beforePopState(({url, as}) => {
      location.href = as; // fix the issue getInitialProps not triggered when go back with browser history
    });
  }

  render() {
    const { Component } = this.props;
    return (
      <Container>
        <Component />
      </Container>
    );
  }
}

export default MyApp;
`

**Comment by brothatru** [comment] 2019-03-15 20:30
^ The above worked for me, however, it looks like it renders the page twice.

Better than it not rendering at all I guess.

Note*: This "back button" issue was only happening to me in Safari (next@7.0.2).

Hate to admit it, but I think Safari is the new IE6 🤦‍♂️

Anyways, good find @johanleroch !

**Comment by timneutkens** [comment] 2019-03-15 21:19
Can you try `next@canary`, it includes bunch of fixes for back button behavior in older browsers.

**Comment by ninjawhocodes** [comment] 2019-04-20 21:49
Do we have any solution for this ?

My case :

1. From http://localhost:3000 navigate to http://localhost:3000/p/hello using Link.
2. Refresh the page.
3. Click back button : It goes to http://localhost:3000 but still renders the content of http://localhost:3000/p/hello it is not loading the content of http://localhost:3000.

I am using "next": "^8.1.0".

**Comment by emil-alexandrescu** [comment] 2019-05-08 21:49
@ninjawhocodes , try changing @johanleroch 's code as below

```
...
Router.beforePopState(({ as }) => {
      window.location.href = as;
      window.location.reload();
    });
```

**Comment by bautistaaa** [comment] 2019-07-20 02:57
having this issue with `^8.0.0`

this work around appears to work but it does a full page reload which isn't ideal, any other solutions?
```js
    Router.beforePopState(({ as }) => {
      window.location.href = as;
      window.location.reload();
      return false 
     // returning true or false here doesnt seem to matter, new signature requires a boolean to be returned
    });
```

**Comment by cotyhamilton** [comment] 2019-08-12 01:50
I was having this error in my getInitialProps function at a line that used `ctx.req.url`

Error:
`TypeError: undefined is not an object (evaluating 'ctx.req.url')`

I changed this line to use a url param, `ctx.query.user` (I have a [user]/index.js page) and I no longer receive this error 🤷‍♂️

before:
`let username = ctx.req.url.split('/')[1];`

after:
`let username = ctx.query.user;`

I haven't been using next.js for very long and I have no idea why this is happening. Dumping the ctx object contains everything it should when hitting the back button.

**Comment by loganpowell** [comment] 2019-08-15 08:25
I'm getting this same behavior (internal routing - within pages inside my `next.js` app - work, but once navigating away - or even to a static asset - breaks). I **am** using `export`

**Comment by loganpowell** [comment] 2019-08-15 10:37
If anyone runs into this issue in the future, I found a not-so-pretty solution.

I'm not sure why `next export` doesn't work in `federalist` (or the underlying `s3` config), but does work in github pages. However, if you are using federalist with next export and you're running into `404` pages when either refreshing any page or navigating back from an external page to your next.js static site, I've found the following works:

If you add `.html` to your `as=` prop in any component using `next/link` for example:

Diff
```diff
import { withRouter } from 'next/router'
import Link from 'next/link'

const custom_link = ({ href, router, children, name, as }) => 
-   <Link prefetch href={href} as={as} passHref>
+   <Link prefetch href={href} as={as + ".html"} passHref>
      {children}
    </Link>

export const CustomLink = withRouter(ELink)

```
This works as it forces the server to serve the html file for the page instead of referring to the router which has lost its context... from what I gather. 

Hope this helps someone who's in a bind and needs a quick fix. Not an ideal solution, but eh...

**Comment by xe4me** [comment] 2019-10-05 23:22
Why is this closed ? :(

**Comment by codefist** [comment] 2019-10-09 20:33
just encountered this.  this should not be closed

**Comment by PerlBug** [comment] 2019-10-21 04:03
Same issue here on Safari 13 (Technology Preview)

**Comment by arjunmehta** [comment] 2019-11-04 17:46
Also experiencing this with Safari. Chrome works as expected.

If anything the different behaviors in the two browsers should be treated as an issue in and of itself.

**Comment by utsavm9** [comment] 2019-12-26 13:09
This issue is in Firefox, Chrome when using Next 9.1.6. This needs to be reopened.

**Comment by utsavm9** [comment] 2019-12-27 06:40
This hack worked for me now, but please let me know if anyone has a good solution or cause for this problem.
```js
static async getInitialProps(context) {

    //Hack: If this code is executing in client-side, just reload.
    if (process.browser) {
        history.go();
    }

    ...
    return { ... };
}
```

**Comment by fabb** [comment] 2020-02-14 19:26
Is there a workaround that does NOT cause SSR? We‘d like to keep unnecessary SSR low because of backend resources.

**Comment by jooj123** [comment] 2020-03-02 06:24
This is still an issue for me - for all browsers. 
I am using `Router.push` to navigate to pages, so I think thats probably where the issue lies

**Comment by tsmith123** [comment] 2020-03-03 22:17
Getting issue in Chrome and Next 9.2.1. `getInitialProps` does not refetch data when using the back button

**Comment by kush-agra** [comment] 2020-03-09 08:35
Issue exists in firefox, currently using the 

https://github.com/zeit/next.js/issues/3065#issuecomment-569202884

hack to get around it but would like a better solution, maybe one of the Router.events can be of some use? will investigate too

**Comment by beamercola** [comment] 2020-03-11 06:35
Issue in Safari still

**Comment by f2hard3** [comment] 2020-03-11 08:25
Upgrading to 9.3.0 and changing getIntialProps to getServerSideProps solved the problem.

**Comment by kush-agra** [comment] 2020-03-11 12:58
It really did solve it, thanks :)

**Comment by beamercola** [comment] 2020-03-12 02:10
Awesome, worked for me but `getServerSideProps` didn't do anything, but `getInitialProps` seems to work now with back button

**Comment by visualcookie** [comment] 2020-03-18 11:28
I'm running a legacy project on `9.1.5`, and really can't update right now, as this would break a lot. Tried the quick fix from https://github.com/zeit/next.js/issues/3065#issuecomment-569202884 but still doesn't work. He doesn't refetch the data from `_app.tsx`.

**Comment by timneutkens** [comment] 2020-03-18 11:52
> I'm running a legacy project on 9.1.5, and really can't update right now

There haven't been breaking changes in the latest releases.

**Comment by shrugs** [comment] 2020-08-03 14:59
for searchers finding this issue, here's another possible cause of the back button not working, `getInitialProps` or otherwise:

i was using `window.history.replaceState(null, '', as);` to change the url without triggering next's shallow routing (which causes a react rerender), but this apparently doesn't play well with how next manages the url. replacing that code with shallow rendering (and then refactoring my code to allow those re-renders) solved my issue and got the back button to work again

**Comment by sphilee** [comment] 2020-10-13 07:07
In app.ts, execute the following statement on componentDidMount.
```ts
// app.ts
this.props.router.beforePopState(({ as, options }) => {
      if (options.shallow) {
        this.props.router.replace(as)
        return false
      }
      return true
    })
```

**Comment by mankenconde** [comment] 2020-12-11 17:19
> Upgrading to 9.3.0 and changing getIntialProps to getServerSideProps solved the problem.

This worked for me! Thank you @f2hard3 !

**Comment by jpamarohorta** [comment] 2021-06-25 22:03
Hello, I'm having this exact same issue with Router.push and an componentDidMount kind of useEffect. What is the recommended solution for a client-side rendering flow?

**Comment by balazsorban44** [comment] 2022-01-28 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
