### ISSUE TITLE
Router context breaking change in v8.0.0-canary.6

### ISSUE THREAD

**Issue by jaydenseric** [zeit/next.js#6042] opened 2019-01-12 23:16 UTC
# Bug report

## Describe the bug

The `next/router` migration to `React.createContext` in https://github.com/zeit/next.js/pull/6030 (Next.js v8.0.0-canary.6) is a breaking change for the GraphQL SSR related examples such as [`with-graphql-react`](https://github.com/zeit/next.js/tree/canary/examples/with-graphql-react) and probably [`with-apollo`](https://github.com/zeit/next.js/tree/canary/examples/with-apollo).

## To Reproduce

In the [`with-graphql-react`](https://github.com/zeit/next.js/tree/canary/examples/with-graphql-react) example, update the `next` dependency to `8.0.0-canary.6` and replace the contents of `pages/index.js` with:

```jsx
import { Query } from 'graphql-react'
import { RouterContext } from 'next/router'

export default () => (
  <RouterContext.Consumer>
    {router => {
      console.log(router)
      return null
    }}
  </RouterContext.Consumer>
)
```

With `npm run dev`, in terminal you will see first `undefined` (bad) for the GraphQL preload render and then a router instance when the final SSR happens:

<img width="301" alt="screen shot 2019-01-13 at 9 50 03 am" src="https://user-images.githubusercontent.com/1754873/51079346-66edea00-1719-11e9-800a-52b1f69363a4.png">

I imagine this reproduction would work for the [`with-apollo`](https://github.com/zeit/next.js/tree/canary/examples/with-apollo) examples too:

https://github.com/zeit/next.js/blob/v8.0.0-canary.6/examples/with-apollo/lib/with-apollo-client.js#L27

## Expected behavior

Perhaps the API would be non-breaking from Next.js v7 if `<RouterContext.Consumer>` was used inside of `<App>` instead of immediately outside.

## System information
 - Version of Next.js: v8.0.0-canary.6

## Additional context

Is this breaking change intentional? If so, I can work it in to [`next-graphql-react`](https://github.com/jaydenseric/next-graphql-react) and cut a new release for Next.js v8 compatibility.

The Apollo examples will also need updating.

**Comment by timneutkens** [comment] 2019-01-13 00:46
Right so the issue is the non-standard rendering of the React tree in getInitialProps, I guess the best solution would be to wrap `Component` in the provider, so that when it's rendered the value is provided automatically. This would require no user-side changes.

**Comment by todesstoss** [comment] 2019-04-25 13:31
@timneutkens  Hello, i'm currently using Next.js v8.1.0, and as I understand after implementation of `useRouter`, `Provider` implemented with a same issue described here, legacy context `witRouter` works just fine, but `useRouter` breaks my `getDataFromTree` in `with-apollo` example, as useRouter return `null` in this method, is it smth that will be fixed or it is expected behaviour?  Thanks

**Comment by timneutkens** [comment] 2019-04-25 15:03
See https://github.com/zeit/next.js/issues/7075#issuecomment-484780337

**Comment by todesstoss** [comment] 2019-04-25 15:32
Yes, sure, but i think it's smth you should be aware of

**Comment by adamsoffer** [comment] 2019-06-01 05:09
Hey @jaydenseric 👋 I'm encountering this as well. Did you by any chance figure out a workaround?

**Comment by adamsoffer** [comment] 2019-06-01 14:08
Can confirm Next router is not working when using Apollo as well.

**Comment by jaydenseric** [comment] 2019-06-02 22:57
@adamsoffer perhaps you are trying to use the `useRouter` hook, or using on of the broken Next.js versions?

The original issue was resolved when modern context for router was reverted before v8 landed. Modern context would be fine for us, if implemented in a different way so the `<App>` API doesn't break:

> Perhaps the API would be non-breaking from Next.js v7 if <RouterContext.Consumer> was used inside of <App> instead of immediately outside.

I'm looking forward to being able to use the `useRouter` hook once it's implemented properly.

**Comment by timneutkens** [comment] 2019-06-03 13:44
> I'm looking forward to being able to use the useRouter hook once it's implemented properly.

Note that it is implemented properly and it's Apollo that causes this for you, not Next.js.

**Comment by adamsoffer** [comment] 2019-06-03 14:11
@timneutkens Would you mind explaining what's causing this bug so I can open up an issue in `react-apollo`?

**Comment by timneutkens** [comment] 2019-06-03 19:25
Well `getDataFromTree` does a full server-render (one for every single query component) so it needs the full tree as otherwise it doesn't have certain values in context (this was already the case).

So basically I guess we'll have to provide some kind of way to provide the tree, even though we really wouldn't want to as it can lead to misusage.

**Comment by adamsoffer** [comment] 2019-06-17 15:03
@timneutkens @jaydenseric  I updated my `next-apollo-example` to use `@apollo/react-hooks` and `useRouter` 😀

For now, I get around this issue by wrapping `router` in a conditional: https://github.com/adamsoffer/next-apollo-example/blob/master/components/Header/index.js#L9

Not ideal, so if anyone has any ideas here let me know!

**Closed** 2019-07-30 18:00 UTC
Labels: Type: Bug

**Comment by balazsorban44** [comment] 2022-01-31 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
