### ISSUE TITLE
react-native-web doesn't work with styled-components

### ISSUE THREAD

**Issue by Aleksion** [zeit/next.js#7244] opened 2019-05-04 02:33 UTC
# Bug report
Importing styled-components/native or @emotion/native results in the following error:

```
{ Error: Cannot find module 'react-native'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/aleksanderhr/projects/experiments/with-react-native-web-app/node_modules/styled-components/native/dist/styled-components.native.cjs.js:16:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.styled-components/native (/Users/aleksanderhr/projects/experiments/with-react-native-web-app/.next/server/static/development/pages/index.js:225:18)
    at __webpack_require__ (/Users/aleksanderhr/projects/experiments/with-react-native-web-app/.next/server/static/development/pages/index.js:23:31)
    at Module../pages/index.tsx (/Users/aleksanderhr/projects/experiments/with-react-native-web-app/.next/server/static/development/pages/index.js:113:82)
    at __webpack_require__ (/Users/aleksanderhr/projects/experiments/with-react-native-web-app/.next/server/static/development/pages/index.js:23:31) code: 'MODULE_NOT_FOUND' }
```

## Describe the bug
I've verified that react-native-web and styled-components work together (at least on 0.10.1 of RNW), by running this as a create-react-app. However, when the app is run on NextJS it fails.
My guess is that the alias works fine for the client side of things (since create-react-app uses webpack internally) but that it fails when running on the server. But I might be off here.

## To Reproduce
- clone with-react-native-web example
- add styled-components
- change index.js to the following:

```jsx
import React from "react";
import styled from "styled-components/native";

const Wrapper = styled.View``;
const StandardText = styled.Text`
  font-size: 12;
`;

export default props => (
  <Wrapper>
    <StandardText>YOYOYO</StandardText>
  </Wrapper>
);

```

## Expected behavior
I expected the page to render "YOYOYO"

## System information
 - OS: macOS
 - Browser chrome
 - Version of [7.0.3, 8.0.1] (Tested both)

Versions Tested:
react-native-web: [0.10.1, 0.11.1]
styled-components: [3.0.0, 4.2.0, 5.0.0 (Canary)]

**Comment by lolcookie** [comment] 2019-05-06 12:47
For some reason I have had success resolving these issues with this plugin.
https://github.com/martpie/next-transpile-modules
It may help you with this issue.

**Comment by Aleksion** [comment] 2019-05-06 20:23
@lolcookie I tried that as well, but to no avail :(
Was your test case the same?

**Comment by lolcookie** [comment] 2019-05-07 00:02
@Aleksion same error message but I was using 'react-native-popup-menu'.

I only got the error on nextjs but not create react app base, which also doesn't transform so probably a false positive.

Did you add the module to the transformation script in next.config.js?

I have a project running CRA + RNW base with style components and it just worked so I think it's a related issue.

Have you tried `npm run clean` and then `npm run dev`?

**Comment by BjoernRave** [comment] 2019-06-11 21:54
@lolcookie which modules did you include in the transpileModules array?

**Comment by Aleksion** [comment] 2019-06-11 22:58
@lolcookie  I tried both of those and eventually gave up. Wiring everything up myself with Razzle proved to be a lot easier

**Comment by elmpp** [comment] 2019-06-14 14:46
- you need to use `react-native-web` version 0.10.1 (or earlier)

**Comment by Timer** [comment] 2019-06-14 15:19
Closed as the user seems to not need help anymore, but a question like this is best suited for our [Spectrum](https://spectrum.chat/next-js) if anyone else still needs help.

**Closed by Timer** 2019-06-14 15:19 UTC

**Comment by DavitVosk** [comment] 2020-02-11 16:43
Any progress here?

**Comment by beblaawy** [comment] 2020-05-11 16:16
any progress guys ?

**Comment by YG-qualson** [comment] 2020-07-17 13:41
```
const withTM = require('next-transpile-modules')(['styled-components']);

module.exports = withTM({
  webpack: config => {
    config.resolve.alias = {
      ...config.resolve.alias,
      'react-native$': 'react-native-web'
    }
    return config
  }
});
```

This worked for me

**Comment by balazsorban44** [comment] 2022-01-29 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
