### ISSUE TITLE
API routes for method POST returns 404 Not found error

### ISSUE THREAD

**Issue by aneesa** [zeit/next.js#8473] opened 2019-08-22 10:37 UTC
Hi, I am trying to call a POST API to the internal API Routes that I set up. Calling `GET` method with queries has no problem, but when I changed the method to `POST` and add a body, it returns `404 Not found error`

Example codes:

`.../xxx.ts` (no errors)
```
import fetch from "isomorphic-unfetch";
...
const res = await fetch('http://localhost:3000/api/someAPI?a=1&b=2');
...
```

`.../xxx.ts` (ERRORS out)
```
import fetch from "isomorphic-unfetch";
...
const res = await fetch('http://localhost:3000/api/someAPI', {
   method: 'POST',
   body: JSON.stringify(<some body object here>)
});
...
```

`pages/api/someAPI.ts`
```
import fetch from "isomorphic-unfetch";
import aws4 from "aws4"; // just to show I'm calling Amazon API
...
export default async (req, res) => {
   ...
      const response = await fetch(<some-aws-iam-api>, <signed-aws-request>);
   ...
}
```

Please let me know if you need more details

**Comment by huv1k** [comment] 2019-08-22 11:46
Hey @aneesa, please provide full reproduction. From your snippets, everything looks okay.

**Comment by timneutkens** [comment] 2019-08-22 13:45
We also have tests in the test suite to make sure that this works correctly, we'd be happy to look at a full reproduction! I'm going to close this issue as it doesn't follow the issue template 👍

**Closed by timneutkens** 2019-08-22 13:45 UTC

**Comment by balazsorban44** [comment] 2022-01-31 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
