### ISSUE TITLE
Error: Cannot find module 'core-js/library/fn/object/define-property'

### ISSUE THREAD

**Issue by fachilles** [zeit/next.js#7990] opened 2019-07-16 02:26 UTC
# Error: Cannot find module 'core-js/library/fn/object/define-property'
There is a project I did create. It worked fine in my local env with yarn start/dev. But it would meet a error after I did deploy this app to GCP(google cloud platform) like the screenshort. So,
what should I do that fix the issue?

![image](https://user-images.githubusercontent.com/3346188/61261219-ac1bd300-a7b3-11e9-929f-6feb920dedce.png)

**Comment by Suresh-R-S** [comment] 2019-07-16 02:46
Observing the same issue.
Since I am having a firebase sdk dependency in the project, downgrading the core-js version is also leading to an error.

**Comment by fachilles** [comment] 2019-07-16 08:20
@Suresh-R-S I proved a solution. As follow( hope it should be ok to you):
My project is a web app built on the Next.js(9.0.0), in my local node.js version. I used yarn cli to start/build my project. It will meet the issue. So, In my opinion, maybe it's a enviroment issue if we used the yarn cli.  I changed the yarn to npm, and re-install and re-build the project. Then re-deploy the app to GCP. It's worked.
But, so far, I didn't figure out the reason that not working with yarn build. Maybe GCP doesn't support it?

**Comment by Suresh-R-S** [comment] 2019-07-16 08:25
Only using npm across environments to build the project.
Haven't yet figured out the issue.

**Comment by timneutkens** [comment] 2019-07-17 14:20
I'm going to close this as it doesn't follow the issue template. Please follow the issue template and provide a full reproduction.

**Closed by timneutkens** 2019-07-17 14:20 UTC

**Comment by Luqih** [comment] 2019-07-22 14:12
Same error here, also with yarn and google cloud. @Suresh-R-S @fachilles did you figure out a solution? I've tried installing core-js but didn't work

**Comment by Suresh-R-S** [comment] 2019-07-22 14:31
@Luqih No I haven't got a solution yet

**Comment by raulfdm** [comment] 2019-12-16 09:01
I was having this issue locally (node v12.13.0). Just remove my `node_modules` and reinstall them and it works.

**Comment by tristanMatthias** [comment] 2019-12-19 19:30
I am also experiencing this on AWS Elastic beanstalk. Works fine locally, but when deployed it throws this error

**Comment by Kcin1993** [comment] 2020-03-27 05:26
@tristanMatthias 

Same situation.
Solve this problem by using `yarn update` to update the yarn.lock file. Then I deploy to ELB. It works fine. But I'm not why it happens.

**Comment by balazsorban44** [comment] 2022-01-30 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
