### ISSUE TITLE
ValidationError: Invalid options object. CSS Loader has been initialised using an options object that does not match the API schema

### ISSUE THREAD

**Issue by wellyshen** [zeit/next.js#8909] opened 2019-09-30 05:46 UTC
# Bug report

## Describe the bug

When upgrade to v9.0.7. `css-loader` throw an API schema error. It won't happens in v9.0.6. Seems `minimize` has been removed from the options of `css-loader` (see [here](https://github.com/webpack-contrib/css-loader#options))

## To Reproduce

1. yarn upgrade next.js@^9.0.7
2. yarn dev

## Expected behavior

app compiled success

## Screenshots

<img width="984" alt="螢幕快照 2019-09-30 下午1 40 57" src="https://user-images.githubusercontent.com/21308003/65852364-7cc73c00-e388-11e9-8e96-b8be76838e24.png">

## System information

- OS: macOS
- Browser: chrome
- Version of Next.js: 9.0.7

**Comment by timneutkens** [comment] 2019-09-30 09:11
Duplicate of https://github.com/zeit/next-plugins/issues/541

Will keep it open there as this doesn't relate to Next.js internals.

**Closed by timneutkens** 2019-09-30 09:11 UTC

**Comment by macrozone** [comment] 2019-10-02 09:56
@timneutkens be aware that because next 9.0.7 now forces css-loader 3.2.0, anyone that uses `@zeit/next-css` will run into that issue. So i think it should be top priority. I would also like to see a migration path from css-loader to the new experimental css feature.

**Comment by timneutkens** [comment] 2019-10-03 10:29
Joe opened https://github.com/zeit/next.js/pull/8944

**Comment by CezarMocan** [comment] 2019-10-03 16:50
+1, happening with @next/less for me.

**Comment by Timer** [comment] 2019-10-03 17:15
Please try `next@v9.0.8-canary.3` -- this version should fix these broken plugins.

**Comment by retallicka** [comment] 2019-10-03 20:30
I got this error using 9.0.7 and @zeit/next-sass, 1.0.1 when I upgrade to `next@v9.0.8-canary.3` I get `Module not found: Can't resolve 'css-loader/locals'`

**Comment by Timer** [comment] 2019-10-03 21:06
@retallicka please provide a reproduction.

**Comment by Timer** [comment] 2019-10-03 21:16
@retallicka a fix should be up in https://github.com/zeit/next.js/pull/8957; I found the source of this loader.

**Comment by Timer** [comment] 2019-10-04 00:37
Please give v9.0.8-canary.4 a try.

**Comment by dbedoyat** [comment] 2019-10-04 19:25
Works well with `next@9.0.8-canary.4 ` and `css-loader@2.2.0`

**Comment by nns2009** [comment] 2019-10-06 09:10
I confirm for 'next-sass'
"@zeit/next-sass": "^1.0.1"
produced the same error with next@9.0.7,
but works with next@9.0.8-canary.4

**Comment by balazsorban44** [comment] 2022-01-31 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
