### ISSUE TITLE
Dynamic Routing Fails To Redirect

### ISSUE THREAD

**Issue by cngeru** [zeit/next.js#8823] opened 2019-09-22 15:20 UTC
# Bug report

The dynamic routing solution doesn't work at all

## To Reproduce
I have this code using `material-ui`
I have this button
```
<Link 
        href='/r/[id]'                  
        as={`/r/${selected.id}`}
        passHref>
            <Button component="a" variant="outlined" size="small">View Menu</Button>
</Link>
```
on the other page
```
import { useRouter } from 'next/router';
const Index = () => {
  const router = useRouter()
  console.log(router.query.id)
  return (
     )
}
```
The `next.config.js`
```
const withOffline = require('next-offline');
const withCSS = require('@zeit/next-css')

const nextConfig = {
  target: 'serverless',
  transformManifest: manifest => ['/'].concat(manifest),
  workboxOpts: {
    swDest: 'static/service-worker.js',
    runtimeCaching: [
      {
        urlPattern: /^https?.*/,
        handler: 'NetworkFirst',
        options: {
          cacheName: 'https-calls',
          networkTimeoutSeconds: 15,
          expiration: {
            maxEntries: 150,
            maxAgeSeconds: 30 * 24 * 60 * 60, // 1 month
          },
          cacheableResponse: {
            statuses: [0, 200],
          },          
        },
      },
    ],
    maximumFileSizeToCacheInBytes: 5 * 1024 * 1024
  },
};

module.exports = withOffline(withCSS(nextConfig));
```

and the` now.json`
```
{
  "version": 2,
  "routes": [	
    {	
      "src": "^/service-worker.js$",	
      "dest": "/_next/static/service-worker.js",
      "headers": {
        "cache-control": "public, max-age=43200, immutable",
        "Service-Worker-Allowed": "/"
      }
    }
  ],
  "builds": [
    {
      "src": "next.config.js",
      "use": "@now/next"
    }
  ]
}
```

## Expected behavior
Expect to move to a new route but nothing happens

## System information

- OS: Windows
- Browser : chrome
- Version of Next.js: [e.g. 9.0.6]

**Comment by timneutkens** [comment] 2019-09-23 08:02
Duplicate of #8821

**Closed by timneutkens** 2019-09-23 08:02 UTC

**Comment by balazsorban44** [comment] 2022-01-31 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
