### ISSUE TITLE
/_next/webpack-hmr takes forever to load in ssr-caching example

### ISSUE THREAD

**Issue by lz000** [zeit/next.js#5194] opened 2018-09-18 03:09 UTC
# Examples bug report

## Example name
ssr-caching

## Describe the bug
I ran `npm run dev` to start the dev server, then quickly opened the pages (http://localhost:3000/, http://localhost:3000/blog/first, http://localhost:3000/blog/second, http://localhost:3000/blog/last) in 6-10 tabs, the last several tabs will stuck on loading. I then found that it was due to http://localhost:3000/_next/webpack-hmr loading forever causing entire app not responding 

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Check out the code
2. Go to `sources\ssr-caching`
3. Run `npm install`
4. Run `npm run dev`
5. Open the pages in 6-10 tabs quickly in Chrome
6. You would see server start not responding 

## Expected behavior
Server should still respond as fast as the first several tabs. /_next/webpack-hmr should either respond quickly or timeout

## Screenshots
<img width="506" alt="aaa" src="https://user-images.githubusercontent.com/5400124/45662047-2d400600-bace-11e8-98f5-e40712636a0a.png">
## System information
 - OS: Windows
 - Browser (if applies) Chrome
 - Version of Next.js: latest 6 and 7

## Additional context

I tried set timeout on express server but still stuck. The only way I found to get around this is to turn off hmr or block the /_next/webpack-hmr endpoint on the server. Any other idea or workaround?

**Comment by timneutkens** [comment] 2019-03-09 15:50
@ijjk we've recently updated the example so maybe this is already fixed.

**Comment by ijjk** [comment] 2019-03-09 19:05
@timneutkens I believe the issue is related to this [comment](https://github.com/zeit/next.js/issues/6479#issuecomment-468491157). A warning is shown now and there's not much we can do since it's a browser limitation so I'm closing this issue now.

**Closed by ijjk** 2019-03-09 19:05 UTC
Labels: good first issue, help wanted
