### ISSUE TITLE
returning `undefined` or `Symbol` from getServerSideProps throws error in dev but not in production

### ISSUE THREAD

**Issue by danielhusar** [zeit/next.js#11237] opened 2020-03-20 19:31 UTC
# Bug report

## Describe the bug

When you return `undefined` or `Symbol` from `getServerSideProps`, you got error in dev:
<img width="1548" alt="Screen Shot 2020-03-20 at 12 27 18" src="https://user-images.githubusercontent.com/1857751/77199571-469c8680-6aa6-11ea-8cf7-21f484a3ec97.png">

The status code is however **200**.

This error is not present in production where those props are simply ignored.

## To Reproduce

Create `getServerSideProps` for page like this:
```
export function getServerSideProps() {
  return {
    props: {
      foo: undefined
    }
  };
}
```

## Expected behavior

Probably same as JSON.stringify:
```
JSON.stringify({foo: Symbol('a'), bar: undefined, baz: 1})
"{"baz":1}"
```

Or page status code should not be **200** if you still want to throw error for those in dev.

## System information

OSX

```
"next": "9.3.1",
"react": "16.13.1",
"react-dom": "16.13.1"
```

**Comment by jgpacker** [comment] 2020-03-20 20:32
Related to https://github.com/zeit/next.js/discussions/11209

**Comment by Timer** [comment] 2020-04-15 05:51
Closing in favor of above

**Closed by Timer** 2020-04-15 05:51 UTC

**Comment by balazsorban44** [comment] 2022-01-30 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
