### ISSUE TITLE
Hot Module Reloading Config?

### ISSUE THREAD

**Issue by zocheyado** [zeit/next.js#4525] opened 2018-06-02 20:05 UTC
# Question about Next.js

So I am using next 5.1.X, looking to upgrade to 6 soon. However are there any current or old docs about configuring the HMR? I am trying to find out what is triggering my HMR since it seems to rebuild my bundle at random times and I cannot find any docs on it. Is there an way to check what triggers the bundle rebuild? A debug mode? A default reload timeout? Any ideas would be great!

**Comment by timneutkens** [comment] 2018-06-02 20:41
Should be fixed in Next 6 or next@canary. It was caused by on-demand-entries removing an active page. Also please follow the issue template. The template you chose clearly states questions shouldn't be posted here. 

Template:

```
# Question about Next.js

Questions should be posted on https://spectrum.chat/next-js
```

**Closed by timneutkens** 2018-06-02 20:41 UTC
