### ISSUE TITLE
Add App Address in context for getInitialProps

### ISSUE THREAD

**Issue by viztor** [zeit/next.js#8581] opened 2019-08-31 02:00 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

By default next.js automatically routes /api/file, we need a way to access the api through relative path. It is currently forbidden in next.js probably due to the need to support SSR, though it should be possible to supply the address where api could be accessed from the req header.

## Describe the solution you'd like

add something like appAddress in context parameter of getInitialProps

## Describe alternatives you've considered

.env or other configuration setting to customize, though it creates overhead for a usual use-case.

**Comment by timneutkens** [comment] 2020-01-02 22:10
Duplicate of #8698

Closing in favor of #9524

**Closed by timneutkens** 2020-01-02 22:10 UTC

**Comment by balazsorban44** [comment] 2022-01-30 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
