### ISSUE TITLE
Fully support "NODE_OPTIONS='--inspect' next"

### ISSUE THREAD

**Issue by josias-r** [zeit/next.js#12143] opened 2020-04-23 17:45 UTC
Node has this great feature for debugging inside a webkit inspector (for example to console log complete objects) using the NODE_OPTIONS env variable.

Unfortunately, there seem to be multiple node processes running during development. My start scripts look like this `NODE_OPTIONS='--inspect' next` and it works to the level of console logging everything inside my next.config.json to a webkit console.

What I would prefer though, if I could inspect my functions that are run from `getStaticProps` for example. Unfortunately, this is not possible, because that's a different node process and the same port can't be reused (I also get a warning regarding that inside my console).

It would be nice to have some option to set the NODE_OPTIONS individually, or you could internally possibly pass the console logs along to the other node process?

Nothing of high priority, but it would be neat to have :D

**Comment by josias-r** [comment] 2020-04-23 17:50
I feel really stupid now, but after some more investigation I just found out, there is a "fix". You can set `"NODE_OPTIONS='--inspect=0' next"` (notice the "=0") and it will assign random ports. This is a bit annoying as you need to add the new ports manually after every start again, but its the best workaround I currently know ^^

**Comment by timneutkens** [comment] 2020-05-25 14:05
This was fixed by https://github.com/zeit/next.js/pull/10807

**Closed by timneutkens** 2020-05-25 14:05 UTC

**Comment by balazsorban44** [comment] 2022-01-30 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
