### ISSUE TITLE
Some Links freeze when refreshing the page

### ISSUE THREAD

**Issue by yassinebridi** [zeit/next.js#8168] opened 2019-07-29 20:47 UTC
# Bug report

## Describe the bug
Some Link components stops working in development and production
## To Reproduce
here is a live example https://frontend-e4m1qf1rc.now.sh/ (**note**: there is popup ads, i hope you have an adblock)
1- Click on any news article, if you click on the home Link or the Logo link in the header, everything works as expected.
but when clicking on a news article, and refresh the page, and clicking on the home Link, the Link freezes and it's not routing to the proper route
2- This also occurs when going directly to a news article from a full url(domaine.com/news/some-slug)

## Expected behavior

for the Link components to route to the desired route without freezing

## Screenshots

this is how i use Link for those non-working routes:
```javascript
<Link href="/" prefetch>
  <a className={classes.homeLink} title="home">
    home
  </a>
</Link>
```

## System information
- Browser: chrome 75.0.3770.100 64bit
- Version of Next.js: 9.0.2

**Comment by landsman** [comment] 2019-08-01 09:31
I have very similar problem.

**Comment by Timer** [comment] 2019-08-01 15:22
Hi! I have a feeling this is due to the Next CSS plugin, but we cannot diagnose the problem without the full source code to your website.

The issue in question is the following one: https://github.com/zeit/next-plugins/issues/282

**Comment by yassinebridi** [comment] 2019-08-01 15:47
@Timer i sent you an invitation link for private repo

**Comment by yassinebridi** [comment] 2019-08-01 15:50
@Timer the problem exist before the "0f92c26" commit

**Comment by Timer** [comment] 2019-08-01 15:52
Ah, you are using `next-css` and this is a known bug. Unfortunately, there's no known solution for it right now.

As a work around you _may_ be able to use some (simple) CSS in `_app` to cause all other links to work.

**Comment by yassinebridi** [comment] 2019-08-01 15:56
thanks, i will take a look at that issue.
should i close this?

**Comment by Timer** [comment] 2019-08-01 17:04
Yeah, this issue is a duplicate of the above. We're going to be trying to solve it soon! 🙏

**Closed by Timer** 2019-08-01 17:04 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
