### ISSUE TITLE
Extra bundles for each page non exported

### ISSUE THREAD

**Issue by DevSide** [zeit/next.js#5849] opened 2018-12-10 14:58 UTC
# Bug report

## Describe the bug

When we export pages using `exportPathMap` in the config, pages in the `./pages` folder which don't match any exported pages have a useless generated bundle.

## To Reproduce

`./pages folder`
```
pages
├── test.js
├── not-exported.js
```

`./next.config.js`
```
module.exports = {
  exportPathMap () {
    return { '/test': { page: 'test'} }
  }
}
```
Generated `./out`
```
out
├── _next
│   ├── static
│   │   ├── chunks
│   │   │   └── commons.1b42176ace0557fce426.js
│   │   ├── runtime
│   │   │   ├── main-c9114fb56a7a60b18e89.js
│   │   │   └── webpack-ec1c16685a7b62d3e9ca.js
│   │   └── wu3mlMdrnfHyIL2h3~Z1K
│   │       └── pages
│   │           ├── _app.js
│   │           ├── _error.js
│   │           ├── not-exported.js ( This shouldn't be generated )
│   │           └── test.js
│   └── wu3mlMdrnfHyIL2h3~Z1K
└── test.html
```

## Expected behavior
No extra bundle.

## Workaround
Mutate Webpack entries to exclude pages based on `exportPathMap`

**Comment by timneutkens** [comment] 2018-12-10 15:08
I was just talking with @lucleray about how it'd make sense to have `next build` being aware of the `export` target so that we can do optimizations

**Comment by timneutkens** [comment] 2019-08-10 12:32
Going to close this as we're currently pursuing a different route, eg https://nextjs.org/blog/next-9#automatic-static-optimization

**Closed** 2019-08-10 12:32 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
