### ISSUE TITLE
The default export is not a React Component

### ISSUE THREAD

**Issue by timlind** [zeit/next.js#6164] opened 2019-01-28 11:18 UTC
Create a link /displays and an empty file in pages/displays/index.js

Navigate via the link, notice that an error shows in the console, the browser URL bar updates but the page does not.

## Expected behavior

The browser should show the error instead of it being hidden in the console.

## System information
 - macOS
 - Chrome
 - Next 7.0.2

**Comment by ijjk** [comment] 2019-03-09 18:56
This issue has been resolved in the latest version of Next.js. I'm going to close this issue now, if you are still having trouble feel free to comment.

**Closed by ijjk** 2019-03-09 18:56 UTC
Labels: Type: Needs Investigation

**Comment by giovannigiordano** [comment] 2019-07-12 16:44
@ijjk I am having the same issue with `next` 7.0.2 after upgrading `react-redux` to 7.1.0 and using `React.memo`

**Comment by balazsorban44** [comment] 2022-01-31 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
