### ISSUE TITLE
Supporting partial rehydration on server side rendered pages

### ISSUE THREAD

**Issue by aymanfarhat** [zeit/next.js#10344] opened 2020-01-30 17:16 UTC
## The problem

While SSR in NextJS works well with hybrid pre-rendering targets by page, it would be much more effective if this option was available on a component level rather than just by page. 

Consider the following scenario: A page includes a large number of components. The majority of those components don't have much need to be interactive on the client side after being rendered on the server while a minority of those components (say 10%) will need to re-hydrate to be interactive and have their JS loaded on the client.

In such a case, I'd have no option but to SSR the whole page and all the components involved in order to make sure that 10% of the components are gonna be interactive. At the same time, the 90% will also have to get re-hydrated, and I'd have a really bloated `__NEXT_DATA__` with state and values that are not entirely needed, that will end up being evaluated and processed by the browser.

## Proposed solution

Instead of doing SSR on all components and then sending the entire application to the client to be re-hydrated, I'd have the option of marking specific components to not hydrate on the client which would signal to NextJS that the component will be statically generated and potentially prevent any related data to be sent via `__NEXT_DATA__` back to the client. At the same time, the components that need to be re-hydrated would get re-hydrated normally.

This could potentially bring big savings for the case mentioned above in terms of cutting down on unneeded JS that will have to be evaluated and executed by the browser.

Is this something that has been discussed before or currently on the roadmap ? Is it something that I could potentially build myself on top of NextJS ? Would really appreciate any pointers around how I could potentially solve this problem in case there are no plans for official support on it.

[This post](https://medium.com/@luke_schmuke/how-we-achieved-the-best-web-performance-with-partial-hydration-20fab9c808d5) seems to be proposing a solution to the problem, I'd really love to hear your thoughts on this approach and whether you're looking into officially supporting it.

Thanks!

**Comment by timneutkens** [comment] 2020-01-31 11:44
It’s on the roadmap and something we’re collaborating on with the React and Chrome team, we’ll share more information when possible.

Overall it’s currently not possible to do this besides following what’s described in the article.

Definitely something we plan on tackling eventually!

There’s a bunch of issues around this already so I’ll close this one.

**Closed by timneutkens** 2020-01-31 11:44 UTC

**Comment by caub** [comment] 2020-11-29 08:37
@timneutkens Is it possible to completely disable client-side hydration?

Because we don't need it, it's a static website and also we use a custom cms for loading content, and the constraint of serializable props is annoying for us

**Comment by caub** [comment] 2020-11-29 17:23
Here's a simplified example: https://repl.it/@caub/ComplexTerrificEditor#pages/index.js

**Comment by LucasBassetti** [comment] 2021-02-10 19:17
Hey @timneutkens, what's the current status of this feature? 

I believe this is affecting PageSpeed because it can't look only the static files (unless it has a way to do that).

**Comment by caub** [comment] 2021-02-10 21:26
We ended up doing a very simple custom next.js, each component has a `getServerSideProps` exported function, props are not serialized, we simply output the markup, and client-side will replace the whole content (based on preact also)

It works beautifully

**Comment by LucasBassetti** [comment] 2021-02-10 21:36
@caub Do you have a code sample of that?

**Comment by caub** [comment] 2021-02-15 18:43
@LucasBassetti Ok I've done one, we will share it later this week or next week after review

**Comment by markpinero** [comment] 2021-05-13 23:48
@caub hi, just wondering if you're still able to provide a code sample for this?

**Comment by caub** [comment] 2021-05-15 22:28
Hey guys, sorry for delay, here's a short gist: https://gist.github.com/caub/4ddbe7ed7642fcaca91553360c37ee91, as said it's really simple, I'll probably add a webpack.config.js and components/html.js example later, or even a full working example on codesandbox
Hope it helps

**Comment by bramvbilsen** [comment] 2021-08-02 06:30
Is there any timeframe or priority level compared to other features? We are also really looking forward to this feature!

**Comment by balazsorban44** [comment] 2022-01-28 01:27
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
