### ISSUE TITLE
[idea] Router.hash

### ISSUE THREAD

**Issue by trusktr** [zeit/next.js#5163] opened 2018-09-14 05:11 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Yes, https://github.com/zeit/next.js/issues/5161

## Describe the solution you'd like

For next Router to have a `Router.hash` property, and when this changes to also trigger `onRouteChangeComplete`.

## Describe alternatives you've considered

see https://github.com/zeit/next.js/issues/5161#issuecomment-421233900

**Comment by mherodev** [comment] 2018-10-05 04:13
Looking in the code, there appears to be a `hashChangeComplete` event that could be listened for. I'm not quite sure why it's separate from `routeChangeComplete`, but maybe that would suffice?

**Comment by timneutkens** [comment] 2019-08-10 12:42
I'm going to close this issue as it has been open for almost a year and I don't want to increase the router bundle size at this point for this particular feature.

**Closed by timneutkens** 2019-08-10 12:42 UTC
Labels: Type: Feature Request

**Comment by balazsorban44** [comment] 2022-01-31 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
