### ISSUE TITLE
import NextSeo change to import { NextSeo }

### ISSUE THREAD

**Issue by Butonix** [zeit/next.js#9446] opened 2019-11-18 16:56 UTC
You have the wrong import.
In the new version you need to change
import NextSeo from 'next-seo'
change to
import { NextSeo } from 'next-seo'

**Comment by ijjk** [comment] 2019-11-18 17:10
Hi, it seems this might have been accidentally posted and was meant as a reply. I'm gonna close this since it doesn't seem like a proper issue

**Closed by ijjk** 2019-11-18 17:10 UTC

**Comment by balazsorban44** [comment] 2022-01-30 22:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
