### ISSUE TITLE
TypeError: require is not a function when importing an npm module in a file within the `api` folder

### ISSUE THREAD

**Issue by tenjojeremy** [zeit/next.js#7933] opened 2019-07-12 17:51 UTC
# Bug report

## Describe the bug

When deployed I get a TypeError: require is not a function error when importing npm module in api/allMovies.js. It works locally but not when deployed.

## To Reproduce

1. clone https://github.com/tenjojeremy/test-nextjs-simple
2. run `yarn`
3. run `yarn start`
4. open localhost: 3000
5. You should see movie posters as expected
6. Deploy site 
7. open deployed site url
8. you will see `Internal Server Error`
9. logs will show error log:

![Screen Shot 2019-07-11 at 10 31 52 AM](https://user-images.githubusercontent.com/25231946/61072222-b4e16300-a3c7-11e9-8a7b-9a4694ff680a.png)

## Expected behavior

On prod site, movies should be fetched and appear on screen on initial load 

## Additional context

Related to https://github.com/zeit/next.js/issues/7850

Thank you

**Comment by timneutkens** [comment] 2019-07-12 21:00
Did you install 9.0.1?

**Comment by tenjojeremy** [comment] 2019-07-12 22:13
Hi @timneutkens, I upgraded to 9.0.1 and I still get `Internal Server Error` but now the console shows a different error message:

![Screen Shot 2019-07-12 at 3 11 28 PM](https://user-images.githubusercontent.com/25231946/61161160-7a56f380-a4b7-11e9-9a78-be58d16b59d2.png)

It works locally but not in a deployed site.

**Comment by ritz078** [comment] 2019-07-16 13:00
Getting the same error for a normal page component.

**Comment by Timer** [comment] 2019-07-16 14:19
This is a duplicate of https://github.com/zeit/next.js/pull/7758 now -- you're looking for a file that's no longer available.

**Comment by timneutkens** [comment] 2019-07-17 14:17
Let's close this in favor of #7758 then.

**Closed by timneutkens** 2019-07-17 14:17 UTC

**Comment by balazsorban44** [comment] 2022-01-31 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
