### ISSUE TITLE
Unit Tests are failing

### ISSUE THREAD

**Issue by Aid19801** [zeit/next.js#7402] opened 2019-05-22 11:25 UTC
# Bug report
When trying to run unit tests consistent failure on using css imports

## Describe the bug
Using Jest, Enzyme, all tests run as long as you don't have `import './styles.css'` style imports. Once you break away from styled jsx into the separate styles.css file you get issues. 

The error generated is
```
   SyntaxError: Unexpected token .

      1 | import React from 'react';
      2 | import PropTypes from 'prop-types';
    > 3 | import './styles.css';
        | ^
      4 |
      5 |
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. setup Create Next App instance.
2. Copy settings and files from [example jest config](https://github.com/zeit/next.js/tree/master/examples/with-jest)
3. in your `pages/index.js` put your stylesheet in `import './styles.css'`. 
4. configure next to accept css files on dev app load. [next-css](https://github.com/zeit/next-plugins/tree/master/packages/next-css)
5. run app (will run css fine)
6. run tests (will fail)

![image](https://user-images.githubusercontent.com/15033409/58170871-8cbd6980-7c8c-11e9-920e-8ba49450b994.png)

## Expected behavior
Expect nextJS / next-css to flex across jest/unit-test/node env and allow import of css files to happen and subsequently tests to pass.

## System information
 - OS: MacOS
 - Version of Next.js: 8.0.1

**Comment by ijjk** [comment] 2019-05-22 15:08
Hi, this looks like a repeat of #6241 I'm gonna close this, if you don't think it's the same thing feel free to reply with additional information.

**Closed by ijjk** 2019-05-22 15:08 UTC

**Comment by balazsorban44** [comment] 2022-01-31 14:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
