### ISSUE TITLE
npm install next fails (No valid versions available for duplexer3)

### ISSUE THREAD

**Issue by sambhav-gore** [zeit/next.js#3541] opened 2018-01-06 19:11 UTC
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

npm install next should work without any errors

## Current Behavior

When running npm install next I get the following error

```shell
$ npm install --save next

npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated @semantic-release/last-release-npm@2.0.2: Use @semantic-release/npm instead
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: timed-out@^4.0.1 (node_modules/got/node_modules/timed-out):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: No valid versions available for timed-out

npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for duplexer3

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sgore/.npm/_logs/2018-01-06T19_02_46_815Z-debug.log

```

Additionally, When I check at npmjs.org there is no duplexer3 package listed. 

## Steps to Reproduce (for bugs)

1. Following the steps from getting started - https://learnnextjs.com/basics/getting-started/setup
2. npm install --save next
3.
4.

## Context

I am unable to get started with next

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |         |
| node    |    9.3.0     |
| npm    |    5.5.1    |
| OS      |   MacOS X El Capitan 10.11.6      |
| browser |    Chrome     |
| etc     |         |

**Comment by vanesyan** [comment] 2018-01-06 19:23
It seems the error with npm registry, as I have the same issue, but with another package - "timed-out"

**Comment by sambhav-gore** [comment] 2018-01-06 19:25
yes it seems like a registry issue.

**Comment by skoch** [comment] 2018-01-06 19:26
Same. 
* node -v: `8.6.0`
* npm -v: `5.6.0`

```
$ npm i next                                                                                                                                                                      ⏎
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated @semantic-release/last-release-npm@2.0.2: Use @semantic-release/npm instead
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for duplexer3
```

**Comment by lucleray** [comment] 2018-01-06 19:28
I have a similar issue using yarn :

```
yarn add v1.3.2                                                                                                                  
info No lockfile found.                                                                                                          
[1/4] 🔍  Resolving packages...
warning next > glob-promise > semantic-release > npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
warning next > glob-promise > semantic-release > @semantic-release/last-release-npm@2.0.2: Use @semantic-release/npm instead
error Received malformed response from registry for "timed-out". The registry may be down.
```

(I found duplexer3 on npmjs.com : https://www.npmjs.com/package/duplexer3)

**Comment by sambhav-gore** [comment] 2018-01-06 19:34
I do not get duplexer3 error now. The error is changed to timed-out. 
I hope it gets corrected soon. 
I tried alternate public registries but none of them worked.

**Comment by skoch** [comment] 2018-01-06 19:41
@sambhav-gore You can get started if you want by installing a previous version. eg:
```
npm i next@3.2.2
```

**Comment by sambhav-gore** [comment] 2018-01-06 19:44
Thanks @skoch this worked. 

btw, duplexer3 was updated just minutes ago on npm and I think timed-out is updated recently too. It will work eventually so this issue can be closed.

**Comment by timneutkens** [comment] 2018-01-08 09:37
This was caused by the npm registry issues 2 days ago. closing.

**Closed by timneutkens** 2018-01-08 09:37 UTC
