### ISSUE TITLE
Sub-directory index page route hangs, emits no response

### ISSUE THREAD

**Issue by atis--** [zeit/next.js#6277] opened 2019-02-12 21:21 UTC
# Bug report
Hi!

I'm evaluating Next.js for potential use with some e-commerce sites. While it's easy to set up and looks pretty nice, there's this completely basic yet crazy thing that's happening when I run the "getting started" example with a small alteration -- a subdirectory route with an index.js file in it.

## Describe the bug

Create a subdirectory within `pages` folder, let's call it `subdir`. Put an `index.js` file in it (with a page component). Navigate to `http://host/subdir/` with a **trailing slash** at the end of the URL. There is no response from the server, the connection just hangs (until some timeout)! Other routes like `http://host`, `http://host/`, and `http://host/subdir` work fine. Happens with both Next.js 7 and 8.

Here's a repo that shows the setup, but it's really just that -- `pages/subdir/index.js` file.

https://github.com/atis--/nextjs-subdir-index-bug

## System information
 - OS: Ubuntu 14.04
 - Browser: chrome, firefox, curl, anything
 - Version of Next.js: 7.0.2, 8.0.0

**Comment by icflorescu** [comment] 2019-02-13 14:42
I can also confirm this.

Tested on MacOS and it just hangs with Next.js `>6.1.2`.
Also, in `6.1.2` you'd get a `404` error when trying to access `/subdir/` (with a trailing slash).

I remember noticing this a long time ago but never found it to be a show-stopper... more of a "quirk" than a bug.

**Comment by dlbnco** [comment] 2019-04-01 13:08
I'm getting some of this with Next 8.0.0, especially after getting runtime/404 errors. After erroring, I try to go to another route (e.g. go back) and it just hangs.

It goes back to normal after I replace the routes with a simple `<div />` and then replace again with the actual content.

**Comment by ijjk** [comment] 2019-08-23 16:00
Hi, the hanging when a trailing slash is present with `next/link` seems to be resolved in the latest version of Next.js v9.0.4. We don't currently handle trailing slashes in Next.js by default so if the URL is visited directly it will still 404.

Closing as the hanging issues seems to be resolved. If you are still having trouble with this feel free to reply with additional details.

**Closed by ijjk** 2019-08-23 16:00 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 01:26
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
