### ISSUE TITLE
there are too many cache on my server

### ISSUE THREAD

**Issue by liubin915249126** [zeit/next.js#8067] opened 2019-07-23 03:04 UTC
# Question about Next.js
we used lru-cache within nextjs like this
```js
     function renderAndCache(req, res, pagePath, queryParams) {
    const key = getCacheKey(req)
    if (ssrCache.has(key)) {
        console.log(`CACHE HIT: ${key}`)
        res.send(ssrCache.get(key))
        return
    }
    app.renderToHTML(req, res, pagePath, queryParams)
        .then((html) => {
            console.log(`CACHE MISS: ${key}`)
            ssrCache.set(key, html)
            res.send(html)
        })
        .catch((err) => {
            app.renderError(err, req, res, pagePath, queryParams)
        })
}
```

but we find that there are too many cache file like this
![image](https://user-images.githubusercontent.com/14243729/61679688-a08f5580-ad39-11e9-84cb-5fbdf5a098e9.png)

and those cache file occupy the server memory,
Is there any solution?
thanks a lot

**Comment by Janpot** [comment] 2019-07-23 08:10
Looks like your cache isn't evicting old items. That doesn't seem to be a problem caused by `next.js`. I'm not sure which cache implementation you are using but `lru-cache` is an in-memory cache so it can't create files. If you were using this package, you'd need to set the `max` option. I can only assume your implementation has a similar option.
Another thing to look into is your `getCacheKey` function. It seems to create more different keys than you expect. Maybe it's taking into account a parameter with high cardinality, that you didn't foresee?

**Comment by timneutkens** [comment] 2019-07-23 09:42
Going to close this as it doesn't follow the issue template (questions should be posted on https://spectrum.chat/next-js). @janpot's reply is correct

**Closed by timneutkens** 2019-07-23 09:42 UTC

**Comment by balazsorban44** [comment] 2022-01-31 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
