### ISSUE TITLE
React component works faster than getInitialProps can complete.

### ISSUE THREAD

**Issue by varbachakov** [zeit/next.js#9166] opened 2019-10-22 21:11 UTC
# Bug report
Hi, sometimes function Blogs works faster than getInitialProps can complete. How can I fix it?

## Screenshots
![image](https://user-images.githubusercontent.com/40147645/67332979-77dd4e80-f528-11e9-87ee-b19164cfcb3a.png)

![image](https://user-images.githubusercontent.com/40147645/67333025-8fb4d280-f528-11e9-9639-d4cb81293c79.png)

![image](https://user-images.githubusercontent.com/40147645/67333209-dacee580-f528-11e9-9b41-ec7af0801991.png)

![image](https://user-images.githubusercontent.com/40147645/67333335-0baf1a80-f529-11e9-99ad-aefbd5fb5b71.png)

## System information

- OS: [macOS]
- Browser (if applies) [chrome]
- Version of Next.js: [e.g. 9.1.1]

**Comment by ijjk** [comment] 2019-10-23 00:38
Hi, it looks like you don't always ensure `categories` is an `array`. Also, note it looks like you aren't returning any initial props in your `getInitialProps` when you get an error from the API. 

You can add a default value for `categories` where you destructure the props:
```jsx
function Blogs({ blogs, categories = [], tags, size, router }) {
...
```

I'm gonna close this since it doesn't appear to be an issue with Next.js. If you are still having trouble feel free to reply with additional details or open a thread on our Spectrum per the issue template

**Closed by ijjk** 2019-10-23 00:38 UTC

**Comment by varbachakov** [comment] 2019-10-23 05:27
Well, thank you very much for the comment!!!

**Comment by balazsorban44** [comment] 2022-01-31 01:26
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
