### ISSUE TITLE
Ability to set BaseURL on call to next()

### ISSUE THREAD

**Issue by rgbkrk** [zeit/next.js#2452] opened 2017-07-03 18:55 UTC
I'd like to be able to host a next.js app on it's own base path (e.g. `/some/base/path/` - on a configurable http proxy). This is primarily for use with [JupyterHub](https://github.com/jupyterhub/jupyterhub) to run as a separate service (on e.g. `/services/nextApp`). I've gotten everything to work for the express app (that uses next handlers underneath) as well as the frontend's handling of the paths (the `req.params -> query -> page/component` are awesome with next.js).

The only issue I'm running into is that `_next` is assumed to be at the absolute path of `/_next` when it needs to be able to be served at `/some/base/path/_next`.

```
const app = next({ dev, baseURL: '/asdf' });
```

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

**Comment by timneutkens** [comment] 2017-07-04 08:28
Duplicate of https://github.com/zeit/next.js/issues/257

**Closed by timneutkens** 2017-07-04 08:28 UTC

**Comment by rgbkrk** [comment] 2017-07-05 16:00
Sure enough, thanks.

**Comment by timneutkens** [comment] 2017-07-05 18:40
🙌 there's some solutions in that thread :)
