### ISSUE TITLE
PullRequest: Implementation #10700 

### ISSUE THREAD

**Issue by frank-dspeed** [zeit/next.js#13079] opened 2020-05-19 05:36 UTC
# PR

#10700 - HTTPS via ENV

## Additional Issues
 - Scenario 1 https default cert invalid => simply host a proxy with a valid cert and let him accept the other same for browser simply add the exemption local

- Should ship default cert generation can not be guaranteed but we could offer a script for that anyway

## Documentation
```
# Using Own Key relativ to process.cwd
# if SSL_CRT_FILE && SSL_KEY_FILE HTTPS=ture
HTTPS=true SSL_CRT_FILE=cert.crt SSL_KEY_FILE=cert.key

# Using Self Signed Cert that gets generated if it does not exist
# Using shipped developer Self Signed Cert 
HTTPS=true
```

Generate a cert and key delete the cert request.
```
openssl genrsa -out key.pem
openssl req -new -key key.pem -out csr.pem
openssl x509 -req -days 9999 -in csr.pem -signkey key.pem -out cert.pem
rm csr.pem
```

**Comment by timneutkens** [comment] 2020-05-25 12:14
Not sure what this issue is but I'll close it as duplicate of #10700

**Closed by timneutkens** 2020-05-25 12:14 UTC

**Comment by frank-dspeed** [comment] 2020-05-29 07:56
@timneutkens good idea it is not worth getting implemented the users should handle that

**Comment by timneutkens** [comment] 2020-05-29 09:00
I'm just not sure what this is, it's not a pull request and it's not really an issue 🤔

**Comment by frank-dspeed** [comment] 2020-05-30 05:07
@timneutkens It is a so-called tracking issue as this is a complex feature as it can be implemented in tons of ways with down and upsides when you would click on the https://github.com/direktspeed/next.js/issues/2 that is referenced you would see a fork with a even more complete issue.

I was still busy choosing the right place to implement it. And creating additional issues for votings after it is implemented.

The Implementation itself could be easily done for example with dynamic import but i was not sure about the nodejs versions that need to be supported and other details.

but overall the new way is to simply list every useful function that next.js has and then transform that into a lib so that everyone can use and configure what he wants and then abandon next.js .

I would not want a dependency that is managed like that and I have the resources.

**Comment by frank-dspeed** [comment] 2020-05-30 05:11
next/server/start-server.ts
```js
async function listen(app,createServer) {
  const protocol = process.env[HTTPS] ? 'https' : 'http';
  const config = protocol === 'https' ? {
    key: fs.readFileSync('key.pem'),
    cert: fs.readFileSync('cert.pem')
  } : {};
  const srv = await import(protocol).then(({ createServer }) => createServer(config, app.getRequestHandler())) 
  await new Promise((resolve, reject) => {
    // This code catches EADDRINUSE error if the port is already in use
    srv.on('error', reject)
    srv.on('listening', () => resolve())
    srv.listen(port, hostname)
  })
}
```

**Comment by frank-dspeed** [comment] 2020-05-30 05:13
Sorry but when I do a PR I want to do it right as I am a senior-level engineer. I understand the side effects of such implementations before I even do them so I try to figure out all edge cases

**Comment by balazsorban44** [comment] 2022-01-30 02:14
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
