### ISSUE TITLE
next with sentry, error in function getInitialProps not reported

### ISSUE THREAD

**Issue by huanglijiao** [zeit/next.js#8292] opened 2019-08-09 02:18 UTC
# Question about Next.js
we used @sentry/browser in _app.js,  and @sentry/node in server.js. 

error in react life cycle function and server.js can be reported, but error in function getInitialProps not reported.

**Comment by timneutkens** [comment] 2019-08-09 12:27
Closing this as per the issue template.

**Closed by timneutkens** 2019-08-09 12:27 UTC

**Comment by balazsorban44** [comment] 2022-01-31 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
