### ISSUE TITLE
How to persist layout between page changes? thank you very much

### ISSUE THREAD

**Issue by Orecic** [zeit/next.js#4166] opened 2018-04-18 09:02 UTC
- [ ] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |         |
| node    |         |
| OS      |         |
| browser |         |
| etc     |         |

**Comment by timneutkens** [comment] 2018-04-18 09:05
Duplicate of #4145

**Closed by timneutkens** 2018-04-18 09:05 UTC

**Comment by Orecic** [comment] 2018-04-18 10:31
@timneutkens hello, I still don't understand how to persist layout between page changes, Can you give me an example? thank you very much

**Comment by timneutkens** [comment] 2018-04-18 10:36
https://github.com/zeit/next.js/issues/88

**Comment by timneutkens** [comment] 2018-04-18 13:31
If you want to not re-render that's not possible yet.
But:

https://github.com/zeit/next.js/tree/canary/examples/layout-component

**Comment by Orecic** [comment] 2018-04-19 01:26
https://github.com/zeit/next.js/tree/canary/examples/layout-component , this example does not work, it cause re-render. Will support golbal layout  in the next version? thanks.

**Comment by Orecic** [comment] 2018-04-19 01:26
@timneutkens  hi , https://github.com/zeit/next.js/tree/canary/examples/layout-component , this example does not work, it cause re-render. Will support golbal layout in the next version? thanks.

**Comment by timneutkens** [comment] 2018-04-19 07:43
I believe I linked you to 2 issues explaining exactly that. It’ll be possible with _app.js in next 6. Currently out on canary.

**Comment by pozylon** [comment] 2018-04-20 07:02
@Orecic This example will show you what you're looking for, it will hopefully get into canary soon: https://github.com/zeit/next.js/pull/4177 cc @timneutkens

**Comment by Orecic** [comment] 2018-04-20 09:16
@timneutkens @pozylon thank you very much.  I have  another question，I have a golbal nav，when page A link to page B,  page B rendered, but when link back to page A, page A re-rendered ,so page A's getInitialProps execute twice， I want page A's getInitialProps execute only once, what should I do
？ thank you.

**Comment by Orecic** [comment] 2018-04-20 09:30
@pozylon  when switching routes ,getInitialProps execute only once, Can it be achieved?
