### ISSUE TITLE
Readme should mention `public` is an experimental feature

### ISSUE THREAD

**Issue by dbachrach** [zeit/next.js#7800] opened 2019-07-08 21:17 UTC
# Bug report

## Describe the bug

The README contains this line:

> To serve static files from the root directory you can add a folder called public and reference those files from the root, e.g: /robots.txt.

However #7771 made this feature experimental. It should either be removed from the readme or the experimental flag to enable it should be mentioned.

## To Reproduce

Read README (https://github.com/zeit/next.js)

## Expected behavior

Should not include experimental features or should mention that the feature is experimental.

## Screenshots

N/A

## System information

N/A

## Additional context

N/A

**Comment by c0b41** [comment] 2019-07-08 21:38
same as middleware #7647

**Comment by pkrawc** [comment] 2019-07-08 21:58
@Timer Will this be marked as experimental or made a production feature? I don't want to move to this from having a static build with zeit until I don't have to worry about this not changing, but this is a perfect fit for service workers since they need to be served from the root path.

**Comment by Timer** [comment] 2019-07-09 00:04
@pkrawc It's marked experimental until we deprecate `static/`, but it's stable for all intents and purposes. You can opt-into it and use it if you'd like.

**Closed** 2019-07-09 00:12 UTC
Labels: Documentation

**Comment by jkjustjoshing** [comment] 2019-09-19 15:06
Is there a place all the current `experimental` features are listed/documented?

**Comment by Timer** [comment] 2019-09-19 15:32
No @jkjustjoshing, you can find them in the code, though!

The two I'd suggest to try in your apps are `experimental: { publicDirectory: true, granularChunks: true }`!

**Comment by balazsorban44** [comment] 2022-01-31 04:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
