### ISSUE TITLE
Can't use dynamic expressions in imports

### ISSUE THREAD

**Issue by Roger** [zeit/next.js#2533] opened 2017-07-11 14:57 UTC
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Imports like, import(`./widgets/${name}/index.js`) work

## Current Behavior

```
Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (http://localhost:3242/_next/1499784830986/manifest.js:698:30)
    at fn (http://localhost:3242/_next/1499784830986/manifest.js:117:20)
    at SameLoopPromise.ssr [as cb] (http://localhost:3242/_next/1499784830986/page/metaspace:296:38)
    at SameLoopPromise.runIfNeeded (http://localhost:3242/_next/1499784830986/commons.js:53634:12)
    at SameLoopPromise.then (http://localhost:3242/_next/1499784830986/commons.js:53564:12)
    at DynamicComponent.loadComponent (http://localhost:3242/_next/1499784830986/commons.js:53416:17)
    at DynamicComponent.load (http://localhost:3242/_next/1499784830986/commons.js:53406:16)
    at DynamicComponent.componentDidMount (http://localhost:3242/_next/1499784830986/commons.js:53484:16)
    at http://localhost:3242/_next/1499784830986/commons.js:32667:25
    at measureLifeCyclePerf (http://localhost:3242/_next/1499784830986/commons.js:32478:12)
```

## Steps to Reproduce (for bugs)

Use dynamic imports like this:
```
const loadModule = name => dynamic(import('./modules/' + name + '/index.js'))
...
const Component = loadModule('name');
() => <Component />
```

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | next@3.0.1-beta.13         |
| node    | v8.1.2        |
| OS      | linux        |
| browser | chrome        |

**Comment by timneutkens** [comment] 2017-07-11 17:46
Duplicate of #2514

**Closed** 2017-07-11 17:46 UTC
