### ISSUE TITLE
[docs] Missing example for Public file serving

### ISSUE THREAD

**Issue by a-kon** [zeit/next.js#8552] opened 2019-08-29 09:41 UTC
# Examples bug report
404 in Docs example

## Example name
Public file serving

## Describe the bug
The link leads from Documentation to non-existing example.

## To Reproduce
1. Go to https://nextjs.org/docs#static-file-serving-eg-images
2. Click on the `Examples` spoiler
3. Click on the `Public file serving` link 
4. See 404 octocat

**Comment by timneutkens** [comment] 2019-08-29 10:49
It's already fixed in the readme. @lfades can you sync the readme?

**Closed** 2019-09-02 20:50 UTC

**Comment by balazsorban44** [comment] 2022-01-31 06:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
