### ISSUE TITLE
Unstyled unMounted components

### ISSUE THREAD

**Issue by vongohren** [zeit/next.js#9812] opened 2019-12-22 20:48 UTC
# Bug report

## Describe the bug

For some reason unmounted components are not styled when coming from next.js with this setup https://github.com/vongohren/fouc-example
They are styled in the storybook example, so it works.
Some more people experiencing the same problems: 
https://spectrum.chat/styled-components/general/next-js-ssr-client-side-style-tags-empty~d723f9ad-65d7-423c-aeed-e456ae6d87b5

https://spectrum.chat/next-js/general/third-party-component-library-using-css-modules~f5dfdd04-7e29-4ed3-8693-7e5220933ea3

## To Reproduce

Here is a simple repo reproducing this error: https://github.com/vongohren/fouc-example

## Expected behavior

I expect that the unmounted components are styled.

## Screenshots

See gifs in https://github.com/vongohren/fouc-example

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of Next.js: "next": "^8.0.3",

## Additional context

See bottom of this README to see efforts I have tried: https://github.com/vongohren/fouc-example

**Comment by enesTufekci** [comment] 2019-12-23 13:43
@vongohren Bad news I tested it locally and it is working as expected. I saw a little problem normally you shouldnt need `next-transpile-module`, then i realized, in ui packages you target esm output for commonjs https://github.com/vongohren/fouc-example/blob/master/packages/tsdx-emotion-comps-lib/package.json#L4
it should be `dist/index.js` in your case. 

If you want to output specific format with tsdx you can do `tsdx build --format esm`

I would suggest you to
- nuke node_modules
- Get rid of `main` in package.json files in ui packages or fix it
- Get rid of `next.config.js`
- build ui packages with `--format esm` flag
- run `lerna clean -y && lerna bootstrap` // this might not be necessary
- and try again

**Comment by vongohren** [comment] 2019-12-23 13:55
@enesTufekci thanks for feedback! Yeah you are not the first one saying it acctually working! I will try out your steps. Emotion.js did work out of the box though, so running with that for now

**Comment by timneutkens** [comment] 2020-01-03 01:43
Closing based on @enesTufekci checking.

**Closed** 2020-01-03 01:43 UTC
Labels: Can't Reproduce

**Comment by balazsorban44** [comment] 2022-01-30 17:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
