### ISSUE TITLE
ModuleParseError when referencing external repo

### ISSUE THREAD

**Issue by lancejpollard** [zeit/next.js#3088] opened 2017-10-14 01:57 UTC
Getting this when I try to reference a separate project (`repo/b/components/layout.js`):

```
ModuleParseError: Module parse failed: /path/to/repo/a/node_modules/react-hot-loader/webpack.js!/path/to/repo/b/components/layout.js Unexpected token (65:17)
You may need an appropriate loader to handle this file type.
|     return <div></div>
...
```

The paths are like:

```
/repo/a
/repo/a/pages/page1.js
/repo/b
/repo/b/components/layout.js
```

And in page1.js it is doing this:

```
import Layout from '../../b/components/layout'
```

The next server is running from within repo a:

```
cd repo/a
npm run dev # which is this:
babel-node --presets=es2015,stage-0 --plugins=transform-react-jsx,styled-jsx/babel server.js
```

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and related are https://github.com/zeit/next.js/issues/1706 and https://github.com/zeit/next.js/issues/3018.

## Expected Behavior

Expected behavior is that I can load this JSX module from a separate repo outside of the main project.

## Current Behavior

Current behavior is that I can't abstract out code into a separate repo if it has JSX in it.

## Context

I can't refactor code into a shared lib.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 4beta2  |
| node    | 8.4 |

**Comment by lancejpollard** [comment] 2017-10-14 02:05
I also get this error if I `npm link` repo b into repo a:

```
cd repo/b
npm link
cd ../..
cd repo/a
npm link repo-b
```

Then import this instead:

```
import Layout from 'repo-b/components/layout'
```

Same error:

```
ModuleParseError: Module parse failed: /path/to/repo/a/node_modules/react-hot-loader/webpack.js!/path/to/repo/b/components/layout.js Unexpected token (65:17)
You may need an appropriate loader to handle this file type.
|     return <div></div>
...
```

However there is one small difference. It renders one time without the error, then on refresh is when it shows the error. Not sure. Either way its not working.

**Comment by timneutkens** [comment] 2018-05-25 22:21
Duplicate of #706

**Closed by timneutkens** 2018-05-25 22:21 UTC
