### ISSUE TITLE
Can't Deploy with v9 & Now 2.0

### ISSUE THREAD

**Issue by Pushplaybang** [zeit/next.js#8052] opened 2019-07-22 12:30 UTC
# Bug report

Since upgrading to v9 I've run into several issues that stop the deployment, the app runs fine with `now dev` . This includes

- can't load grpc 
- self register bug
  - both avoided when setting grpc to external in custom webpack config as mentioned 
- can't use latest firebase - produces `pages/about.js:29:31) code: 'MODULE_NOT_FOUND' }` when that page clearly exists, (downgrading to 5.11.1 "solves" this)

Seems to relate to #7894 #7758 #6655 

Working around the above I now get the following as mentioned here https://github.com/zeit/next.js/issues/7894#issuecomment-513766944

```
running "yarn run now-build"
Jul 22 2019 14:05:48:345 | ...next.config.js | yarn run v1.16.0
Jul 22 2019 14:05:48:403 | ...next.config.js | $ next build
Jul 22 2019 14:05:49:159 | ...next.config.js | Creating an optimized production build ...
Jul 22 2019 14:05:49:824 | ...next.config.js | > Using external babel configuration
Jul 22 2019 14:05:49:824 | ...next.config.js | > Location: "/tmp/bc0fa1c/babel.config.js"
Jul 22 2019 14:07:52:235 | ...next.config.js | Failed to compile.
Jul 22 2019 14:07:52:235 | ...next.config.js | ./node_modules/amp-toolbox-optimizer/lib/transformers/AddBlurryImagePlaceholders.js
Jul 22 2019 14:07:52:235 | ...next.config.js | Module not found: Can't resolve 'jimp' in '/tmp/bc0fa1c/node_modules/amp-toolbox-optimizer/lib/transformers'
Jul 22 2019 14:07:52:235 | ...next.config.js |  
```

## To Reproduce

Attempt to deploy nextjs v9 with firebase

## Expected behavior

Can deploy next js v9 to Now 2.0

**Comment by Timer** [comment] 2019-07-22 13:14
Hey @Pushplaybang!

Thanks for opening this issue, but I'm going to close it as a duplicate of some of the linked issues.

In this case, you're being primarily affected by https://github.com/zeit/next.js/pull/7758 -- please subscribe to that issue for updates.

Thanks!

**Closed by Timer** 2019-07-22 13:14 UTC

**Comment by Pushplaybang** [comment] 2019-07-22 14:14
@Timer thanks, I appreciate the link, I thought it may be useful to bring these together, as I seemed to be darting around the issues attempting to find the right one, and thought it may be useful.

**Comment by balazsorban44** [comment] 2022-01-31 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
