### ISSUE TITLE
with-tailwindcss example breaks when typescript is added

### ISSUE THREAD

**Issue by gihrig** [zeit/next.js#9415] opened 2019-11-15 00:59 UTC
# Examples bug report

## Describe the bug

with-tailwindcss works as expected when installed as instructed in its README. When typescript is installed as instructed in the [Next docs](https://nextjs.org/docs/#typescript), tailwind is rendered inoperative and no styles appear in the browser.

## To Reproduce

$ npx create-next-app --example with-tailwindcss next-ts-tailwind
$ cd next-ts-tailwind && yarn dev

open http://localhost:3000 >>> App works as expected

Install typescript

$ touch tsconfig.json
$ yarn add --dev typescript @types/react @types/node
$ yarn dev

open http://localhost:3000 >>> App works as expected

Enable typescript

$ mv ./pages/index.js ./pages/index.tsx
$ mv ./pages/_app.js ./pages/_app.tsx
$ mv ./components/nav.js ./components/nav.tsx
$ yarn dev

open http://localhost:3000 >>> App loads without styles

Inspecting page in browser's dev tools shows tailwind classes added to html elements but there is no evidence of tailwind css in the document head.

This condition applies to any single file with a .tsx extension. I need not rename all three .js files to see the failure.

## Expected behavior

The app should function identically whether files have .js or .tsx extensions.

## System information

- OS: macOS Mojave 10.14.6
- Browser: Brave Version 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)
- Version of Next.js: 9.1.3

## Additional context

A worked example is available [here](https://github.com/gihrig/next-ts-tailwind).

Following this [example](https://medium.com/quick-code/tailwind-react-typescript-a0317155e5ee) from the web, I am able to get Create-React-App + tailwind + typescript to work together, so I see this combination can work.

**Comment by jamesmosier** [comment] 2019-11-15 17:06
Moving this [`/* purgecss end ignore */`](https://github.com/zeit/next.js/blob/d90c85311140b8a55d611dd5cc4fd15e30f7e708/examples/with-tailwindcss/styles/index.css#L5) to line 8 (below the last tailwind import) seems to fix this. I'm still investigating why that happens though...

**Comment by gihrig** [comment] 2019-11-15 21:08
@jamesmosier thank you for looking into this, and pointing me in the right direction!

There appears to be a typescript/purgecss interaction which is the source of the missing styles.

And the answer to that is the `postcss.config.js` purgecss `content:` segment only targets '.js' files:

Changing

``` content: ['./pages/**/*.js', './components/**/*.js'],```

to

```content: ['./pages/**/*.tsx', './components/**/*.tsx'],```

Handles the problem in this case, with index.css left in its original state.

In the `with-tailwindcss` example the `content: ...` segment should be changed to something like:

```
      content: [
        './pages/**/*.js', './components/**/*.js',
        './pages/**/*.ts', './components/**/*.ts',
        './pages/**/*.tsx', './components/**/*.tsx'
      ],
```

Let me know if you would like a PR opened with this change.

Thanks again for your help!

**Comment by jamesmosier** [comment] 2019-11-16 00:11
You're welcome @gihrig, good find with the fix. Feel free to open a PR with the fix, otherwise I can take care of it. Just let me know.

Also instead of listing all the different extensions out, you could do:

```js
content: [
  "./pages/**/*.{js,jsx,ts,tsx}",
  "./components/**/*.{js,jsx,ts,tsx}"
],
```

**Comment by gihrig** [comment] 2019-11-16 04:47
Hi @jamesmosier. I have opened PR #9432 with the fix.

Regarding the updated search path, thanks for that. I spent too much time trying various regex and glob patterns, before resigning myself to a 'workable kludge'. ;-)

**Closed** 2019-11-20 19:13 UTC
Labels: Type: Example, good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-30 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
