### ISSUE TITLE
[ERROR][NEED HELP] Use getServerSideProps with Wrapper

### ISSUE THREAD

**Issue by happy-unicorn** [zeit/next.js#11319] opened 2020-03-24 07:59 UTC
The example [with-cookie-example](https://github.com/zeit/next.js/blob/canary/examples/with-cookie-auth/utils/auth.js) uses getInitialProps, how to use getServerSideProps in that case? 

```
// /components/withAuth.js
export const withAuthSync = WrappedComponent => {
  const Wrapper = props => {
    return <WrappedComponent {...props} />
  }

  Wrapper.getInitialProps = async ctx => {
    const token = auth(ctx)

    const componentProps =
      WrappedComponent.getInitialProps &&
      (await WrappedComponent.getInitialProps(ctx))

    return { ...componentProps, token }
  }

  return Wrapper
}
```
My page with this wrapper
```
// /pages/home.js
import React from 'react';
import {withAuthSync} from '../containers/hocs/withAuth';

const Home = (props) => {
    return (
        <div>
            Home Page
        </div>
    );
};

export async function getServerSideProps(ctx) {
    const data = await doSomething();
    return {
        props: {...data}
    };
};

export default withAuthSync(Home);
```
I have this error 

> You can not use getInitialProps with getServerSideProps. Please remove getInitialProps. /home

**Comment by chanlito** [comment] 2020-03-24 08:04
What's with that title? 🤔

**Comment by timneutkens** [comment] 2020-03-24 08:56
Please stop double posting and ignoring the issue template.

Duplicate of https://github.com/zeit/next.js/discussions/11317

**Closed by timneutkens** 2020-03-24 08:56 UTC

**Comment by balazsorban44** [comment] 2022-01-30 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
