### ISSUE TITLE
No styles appear before page loads.

### ISSUE THREAD

**Issue by EnderDev** [zeit/next.js#8786] opened 2019-09-18 15:50 UTC
# Bug report

## Describe the bug
No styles before page loads.

## To Reproduce
1. `git clone https://github.com/dot-browser/website`
2. `npm i`
3. `npm run dev`
4. `when page loads, you will see that styles don't appear for a few ms, then appear.`

## Expected behavior
Should load styles before DOM is finished.

## Screenshots
n/a

## System information

- OS: Windows
- Browser: Chrome
- Version of Next.js: 9.0.5

## Additional context
N/A

**Comment by ijjk** [comment] 2019-09-18 16:28
Hi, it looks like you need to add a `_document` to gather the styles during SSR. See the example `_document` in `with-styled-components` [here](https://github.com/zeit/next.js/blob/a9c82613922666b5b049dfcf2b3b26c16d61a70a/examples/with-styled-components/pages/_document.js#L21)

Closing since this doesn't appear to be a bug, if you are still having trouble feel free to reply with additional info

**Closed by ijjk** 2019-09-18 16:28 UTC

**Comment by EnderDev** [comment] 2019-09-18 17:59
Hi. I've created _document.js and pasted the code in. However it doesn't seem to do anything. Am I doing anything wrong?

**Comment by ijjk** [comment] 2019-09-18 21:08
I just checked out your repo and it looks like it's working. Before you added the `_document` the styles weren't added during SSR now they are. Are you referring to the fadeIn styles you added in [`pages/styles.ts`](https://github.com/dot-browser/website/blob/2b5af9ea810df8757ba0f54f05325c29a5bc1a7a/pages/styles.ts#L25)?  

Also note the `styles.ts` file shouldn't be in the `pages` directory unless you are wanting users to visit it at `/styles` otherwise it should be outside of the `pages` directory

**Comment by balazsorban44** [comment] 2022-01-31 04:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
