### ISSUE TITLE
withRouter query is undefined

### ISSUE THREAD

**Issue by serranoarevalo** [zeit/next.js#5374] opened 2018-10-03 14:17 UTC
# Bug report

## Describe the bug

I'm connecting a component to the router using withRouter, on the server side the router.query object is populated by the params on the URL like /post?id=1234 but on the front end, the query object is undefined for a moment and then populated again.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Clone: https://github.com/serranoarevalo/next-graph-pwa
2. Run ```yarn dev```
3. Click on any of the categories
4. See the console for a log of the router.query as undefined and then populated. 

## Expected behavior
The router.query should be populated with what's on the URL
 
## System information
 - OS: macOs
 - Browser: Chrome
 - Version of Next.js: 7.0.1

## Additional context

If I refresh it works perfectly (SSR) but if I go to that page from another page the problem happens.

<img width="616" alt="screen shot 2018-10-03 at 11 18 26 pm" src="https://user-images.githubusercontent.com/3612017/46416528-ac863880-c762-11e8-9e9e-2b3cfdea57a4.png">

As you can see, it's undefined first and then it gets populated.

**Comment by johannesfritsch** [comment] 2019-02-16 07:30
I have the exact same problem. To me it looks as if the router is not updated from the last page. router.asPage is still '/' when it should be /node/a?id=123123. On SSR everything works.

**Comment by ijjk** [comment] 2019-03-05 20:03
@serranoarevalo I'm not able to reproduce this with the latest version Next.js `8.0.3`  

<img width="388" alt="screenshot" src="https://user-images.githubusercontent.com/22380829/53833945-60c4fe80-3f4f-11e9-8162-cdeea5dff30b.png">

**Comment by ijjk** [comment] 2019-03-08 21:32
After further investigation, this appears to be related to `apollo` and it calling `getDataFromTree`. I am not able to reproduce this behavior on a Next.js app not utilizing `apollo` so I am going to close this since there's not much I can do to fix this from our end. 

It also seems to work fine using the query parameter from `getInitialProps` so I'd recommend that.

**Closed by ijjk** 2019-03-08 21:32 UTC
Labels: Type: Needs Investigation

**Comment by serranoarevalo** [comment] 2019-03-09 01:45
Thank you for investigating, I'm gonna report this issue to the Apollo team.

@ijjk What do you mean by 'using the query parameter from getInitialProps so I'd recommend that' 

Does that work with Apollo?

**Comment by ijjk** [comment] 2019-03-09 02:06
@serranoarevalo Like how you are doing [here](https://github.com/serranoarevalo/next-graph-pwa/blob/c4b5d886b1cd96a1469fde634ae91c96565a3a82/pages/category/categoryContainer.js#L8) you can just pass down the `id` value to the components that need it for apollo and remove the `withRouter` HOC. When testing that value was always correct.

Here is a link to the [`getDataFromTree`](https://github.com/apollographql/react-apollo/blob/6142a87d7ca2338c0938150a99f77f1f45f23451/src/getDataFromTree.ts) function that seems to be rendering the tree with the query value not being set.

**Comment by ijjk** [comment] 2019-03-09 16:33
@serranoarevalo We actually might be able to fix this on our end I kept looking into how the `with-apollo` stuff is working and it appears this might be fixed when #6042 is addressed. I'm gonna keep this issue closed in favor of that one.

**Comment by serranoarevalo** [comment] 2019-03-10 01:21
Cool! Thanks @ijjk

**Comment by designbyadrian** [comment] 2019-05-24 11:48
I'm having this same issue with pretty basic NextJS setup. The query is filled in in getInitialProps, but not in subsequent checks to this.props.router.query.

**Comment by Bundas** [comment] 2020-01-23 23:40
@designbyadrian did you find a solution?

**Comment by sboh1214** [comment] 2020-03-17 20:11
@designbyadrian @Bundas Did you find a solution? I'm also having the same issue. (Inside apollo provider, I can't get this.props.router.query

**Comment by Dipeshlohani** [comment] 2020-06-09 11:54
Its Jun 09,2020 still no solution found.

**Comment by Dipeshlohani** [comment] 2020-06-09 11:55
Still waiting for the solution.

**Comment by 2b-dev** [comment] 2020-07-06 19:17
I try to use 
let partUrl = window.location.href;
let lastPath = partUrl.split("/").pop();
to get ID

**Comment by ctrlaltdylan** [comment] 2020-07-16 22:46
Anything feasible for functional components? @2b-dev's solution will work, but it seems like the router should be handling this, not manual string splitting and searching.

**Comment by ctrlaltdylan** [comment] 2020-07-16 22:52
Leaving my solution until the bug is addressed:

```
  const router = useRouter()
  const userId = router.query.userId;

    useEffect(() => {
        if(!checkId) {
          return;
        }
        // now userId is available.
        // make API call here
    }, [userId]);
```

**Comment by ahakem** [comment] 2020-07-22 13:45
I fixed that by disable SSR for the component

**Comment by balazsorban44** [comment] 2022-01-29 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
