### ISSUE TITLE
Office UI Fabric React example is not working good- css load on client side

### ISSUE THREAD

**Issue by doronnahum** [zeit/next.js#7653] opened 2019-06-24 20:54 UTC
Office UI Fabric React-  css load on client side

**Comment by Timer** [comment] 2019-07-18 13:22
Closing as it doesn't follow the issue template.

**Closed by Timer** 2019-07-18 13:22 UTC

**Comment by balazsorban44** [comment] 2022-01-31 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
