### ISSUE TITLE
JSX error just create new app

### ISSUE THREAD

**Issue by kungfu321** [zeit/next.js#8027] opened 2019-07-18 12:51 UTC
# Bug report

## Describe the bug

I'm creating a new project with `create-next-app`, but I have the error when change .js to tsx ??
How do I fix this error?

```
JSX element type 'Link' is not a constructor function for JSX elements.
Type 'Link' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.ts(2605)
JSX element class does not support attributes because it does not have a 'props' property.ts(2607)
```

## Screenshots

![image](https://user-images.githubusercontent.com/10558363/61458722-6159b100-a995-11e9-9799-8dbf6a539cab.png)

## System information

- OS: [macOS]
- Browser (if applies) [chrome]
- Version of Next.js: [9.0.2]

**Comment by Timer** [comment] 2019-07-18 12:54
Can you please / did you run `yarn start` and follow the TypeScript setup instructions?

**Comment by Timer** [comment] 2019-07-18 12:59
Closing this as I can see in the provided screenshot that TypeScript setup isn't complete yet.

You can run `yarn dev` or `yarn build` and it should set everything up for you!
Let us know if you're still having trouble getting things to work.

**Closed by Timer** 2019-07-18 12:59 UTC

**Comment by balazsorban44** [comment] 2022-01-31 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
