### ISSUE TITLE
I regularly get ENOENT error when running npm run dev

### ISSUE THREAD

**Issue by rajaraodv** [zeit/next.js#633] opened 2017-01-03 03:31 UTC
I'm trying out bunch of examples and when I stop one example and then go to another and try to run `npm run dev`, I get the following error. 
I think somehow when I ctrl+c the server it's not shutting down some child process or something?

```

{ Error: spawn /Users/rraodv/app/node_modules/.bin/next-dev ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn  /Users/rraodv/app/using-router/node_modules/.bin/next-dev',
  path: '/Users/rraodv/app/using-router/node_modules/.bin/next-dev',
  spawnargs: [] }
```

**Comment by nkzawa** [comment] 2017-01-07 01:44
I tested with the current master, but couldn't reproduce. Does it still happen ? Let us know your environment (OS, node and npm versions) ?

**Comment by rajaraodv** [comment] 2017-01-07 06:17
I just saw it but i was using an ^1.2.3 version. I'll update this if I see this again in ^2.0.0-beta.16

**Comment by timneutkens** [comment] 2017-01-17 21:21
@rajaraodv Closing this for now. If it still persist please feel free to re-open the issue ❤️

**Closed by timneutkens** 2017-01-17 21:21 UTC
Labels: Can't Reproduce

**Comment by CharlesW95** [comment] 2017-04-11 02:42
I'm getting the exact same error; no matter what I do it still gives me the ENOENT error. Does anyone know why this is happening?
