### ISSUE TITLE
Stuck with a Problem of access permission denied

### ISSUE THREAD

**Issue by ashu8912** [zeit/next.js#8908] opened 2019-09-30 01:09 UTC
# Bug report

## Describe the bug

UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, unlink '/Users/ashughildiyal/Desktop/WebDevelopment/VipWebApp/VIP-Intern-Alok/Backend/.next/server/pages-manifest.json'
when i run npm start i get the above error..
i have to run my server with sudo npm start which i dont want to do.

## To Reproduce

running the project with npm start leads to this problem

## System information

- OS: [macOS]
- Browser (if applies) [e.g. chrome, mozilla]
- Version of  Nextjs : "^8.1.0"

**Comment by timneutkens** [comment] 2019-09-30 09:03
Potentially you run `next build` under a different user than `next start`? 🤔 Or the permissions on the files are modified between build and start. Either way we can't really investigate this as it happens on your machine.

**Comment by timneutkens** [comment] 2019-09-30 09:49
I'll close this as this is better suited for Spectrum:

```
# Question about Next.js

GitHub Issues are reserved for Bug reports and Feature requests. The best place to get your question answered is to post it on https://spectrum.chat/next-js.
```

**Closed by timneutkens** 2019-09-30 09:49 UTC

**Comment by ashu8912** [comment] 2019-10-01 01:32
No this is not my machine specific problem even my other team members has to do sudo.
And yes i asked this on spectrum but couldn't get any answer there.

**Comment by stilistik** [comment] 2020-10-21 12:01
This happened to me when i mounted my next app project in a docker container and then later tried to run it outside the docker again. 

`sudo chown -R $USER <project-dir>` solved this for me

**Comment by balazsorban44** [comment] 2022-01-29 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
