### ISSUE TITLE
HMR

### ISSUE THREAD

**Issue by ZhouYuTao2017** [zeit/next.js#9457] opened 2019-11-19 10:26 UTC
# Bug report

## Describe the bug

No other loaders are enabled when my file is updated

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. start
2. update file jsx or tsx
3. See error

## Expected behavior

load other loaders normally

## Screenshots
The first boot is normal
![image](https://user-images.githubusercontent.com/30223113/69138170-23ae9580-0af9-11ea-9227-ad20ebcbef5e.png)

But I am modifying the file jsx or tsx
![image](https://user-images.githubusercontent.com/30223113/69138297-61132300-0af9-11ea-8e7d-533f2847cdd3.png)

my file tsx
![image](https://user-images.githubusercontent.com/30223113/69138477-bb13e880-0af9-11ea-925a-4423790c426e.png)

my .babelrc
![image](https://user-images.githubusercontent.com/30223113/69138439-a46d9180-0af9-11ea-9608-59a7fec375ba.png)

next.config.js
![image](https://user-images.githubusercontent.com/30223113/69138549-d8e14d80-0af9-11ea-9f67-6be8c9ff9fac.png)

## System information

- OS: macOS
- Browser:chrome
- Version of Next.js: 9.0

## Additional context

The first boot is normal

**Comment by ijjk** [comment] 2019-11-19 17:47
Hi, it looks like the above `next.config.js` is incorrect. You should be exporting an object with the config not an array of configs e.g. `module.exports = { target: 'serverless' }`. 

It also looks like you're trying to import an image asset in a TypeScript file. TypeScript doesn't handle this by default. 

You can add handling for this by adding a `global.d.ts` to your project root with the below contents and then restarting your Next.js app
```TypeScript
declare module "*.jpg"
```

I'm going to close this since the above should correct the problem. If you are still encountering problems with this feel free to reply with additional details

**Closed by ijjk** 2019-11-19 17:47 UTC

**Comment by balazsorban44** [comment] 2022-01-30 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
