### ISSUE TITLE
Router.push() doesn't do anything (using `@zeit/next-sass` and CSS Modules)

### ISSUE THREAD

**Issue by claus** [zeit/next.js#8019] opened 2019-07-17 21:52 UTC
# Bug report

## Describe the bug

When using `@zeit/next-sass` and CSS Modules, a `Router.push` (or click on `<Link>`) has no effect when linking from a page that doesn't have a CSS import to another page that has.

## To Reproduce

1. Clone https://github.com/claus/next-test-css-modules
2. `npm run dev`
3. Click on the "Test" link.
4. Nothing happens.

## Expected behavior

App should navigate from the index page to `/test`.

## System information

- OS: macOS
- Version of Next.js: 9.0.2

## Additional context

What appears to happen is that the `test.js` script loads, but the loaded component
is never registered. In PageLoader `loadPage()`, the page register event is never fired,
and as a result the Promise never fulfills/rejects.

To "fix" the app:
- Either uncomment `import styles from './index.scss'` in `index.js`
- Or comment out `import styles from './test.scss'` in `test.js`

**Comment by timneutkens** [comment] 2019-07-18 09:45
Duplicate of https://github.com/zeit/next-plugins/issues/282

**Closed by timneutkens** 2019-07-18 09:45 UTC

**Comment by balazsorban44** [comment] 2022-01-31 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
