### ISSUE TITLE
Support for .mjs files

### ISSUE THREAD

**Issue by isaachinman** [zeit/next.js#5685] opened 2018-11-16 01:49 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
NextJs does not recognise files like `pages/index.mjs`.

## Describe the solution you'd like
I'd like to be able to use `.mjs` files in place of `.js` files across my entire project.

## Describe alternatives you've considered
N/A.

## Additional context
It'd be great to see this land sometime soon. As Node 11 moves forward, I'd like to see a future where we don't need to use Babel for module support, and can rely directly on Node.

I am more than happy to work on a PR for this, if someone can point me in the right direction. I'm not 100% sure of the implications here, but hopefully it's rather simple. We'll likely need to do detection of Node versioning.

**Comment by timneutkens** [comment] 2018-11-16 09:51
We're already planning on changing the build pipeline a bit to allow multiple targets for browsers etc. So I guess this can just be a continuation of that.

Until then you can add https://github.com/zeit/next.js#configuring-extensions-looked-for-when-resolving-pages-in-pages

**Comment by isaachinman** [comment] 2018-11-16 17:11
Yeah, I saw the extension support. I assume that doesn't change anything in regards to the build pipeline as you said, though?

It should be noted that `mjs` files are fundamentally different from "custom" extensions like `jsx` in that they are a part of the Node core (still behind a flag in v11, though).

We can just leave this issue open for awhile if it makes sense further down the roadmap.

**Comment by samkelleher** [comment] 2018-11-19 18:12
I've run into the same issue. Where NextJS essentially works as an opioninated starter kit with a preconfigured and abstracted API, it's essentially just webpack underneath in terms of the build pipeline.

In the project I'm working on NextJS provided an excellent jumping board, but now wanting to support:

- ESM (aka _mjs_ files)
- Importing assets (fonts, images etc)
- Custom babel transpilation (support language options specific for our project).

These requirements came out of a number of issues with NextJS.

Ultimately, I duplicated the existing NextJS webpack config and customised it to meet some of the requirements I was facing.

I think it comes down to how opinionated should NextJS become in terms of what is supported, but at least the behaviour can be configued,

**Comment by isaachinman** [comment] 2018-11-19 18:18
@samkelleher Your comment seems to be off-topic and references several different issues (all of which can already be solved, and have been discussed at length elsewhere):

1. ESM: configure custom extensions until this issue is resolved
2. Importing assets: put your stuff in the `static` dir, or start some Googling
3. Just put your own `.babelrc` in your root, and extend the next config

**Comment by samkelleher** [comment] 2018-11-19 18:30
@isaachinman  Hey, I was just pointing out that mjs can be supported without the need for nextjs to implement support for it, by customising the config, which I did to also address the other issues I mentioned, as when you dig into them, the workarounds suggested in the other discussions don't really solve the issue.

Changing the extension from `js` to `mjs` doesn't actually change support for ESM modules because the output will still be CommonJS.

For example, a custom `.babelrc` impacts any place babel is used in project not just the specific configuration applied by nextjs. Additionally an effectively copy-and-paste static folder where we have broken the link between an asset file and the component that actually uses it.

So if you want mjs support, you can add to your project without needing nextjs support for it.

**Comment by isaachinman** [comment] 2018-11-19 18:40
@samkelleher Yes, all of that is true! However, this issue is more about first-class support for `mjs` files.

**Comment by raymondsze** [comment] 2018-11-28 18:32
@samkelleher I see this https://web.dev/fast/serve-modern-code-to-modern-browsers today. And I would like to ask if it is possible with Next.js. What do you customize the config so that you can get ESM modules works?

**Comment by raymondsze** [comment] 2018-11-29 03:56
@isaachinman Yes, what I would like to ask is what should we change in nextjs default webpack config to get the output format as ESM modules. I tried to do something similar to what https://web.dev/fast/serve-modern-code-to-modern-browsers do, but no luck.

**Comment by isaachinman** [comment] 2018-11-29 12:54
Not sure about that. You'll probably want to post on StackOverflow or elsewhere.

**Comment by isaachinman** [comment] 2019-01-10 09:38
@ivan-kleshnin You'll need a reproducible example, and once you have it you should open a different issue, or perhaps post on StackOverflow.

**Comment by ivan-kleshnin** [comment] 2019-01-10 09:53
As I said, it's not a question but a caution note for people finding this issue. I've spent 3 days trying to migrate to Node11 with NextJS and a realistically big project. Now, I'm switching back to CommonJS because the amount of problems I experienced was too big to handle them.

**Comment by richardgill** [comment] 2019-01-12 17:02
I don't have many `.mjs` files in my project but something like this helped me:

```
  webpack(config, options) {
    config.resolve.extensions.push('.mjs')
    config.module.rules.forEach(rule => {
      if (rule.test.source.includes('js|jsx')) {
        rule.test = new RegExp(rule.test.source.replace('js|jsx', 'js|jsx|mjs'))
      }
    })
```

But not sure if it will help you @ivan-kleshnin

**Comment by Timer** [comment] 2019-12-23 15:29
The `.mjs` extension has been supported for a while -- closing this!

**Closed by Timer** 2019-12-23 15:29 UTC
Labels: Type: Feature Request

**Comment by jim-king-2000** [comment] 2020-10-28 03:18
I use next@v10.0.0, it still can't recognize `pages/index.mjs`. And it reports 'module is not defined' when I import a mjs file in `pages/index.js`. So, how `.mjs` source file is supported?

**Comment by samsends** [comment] 2021-02-09 08:36
also having issues with mjs files

**Comment by electerious** [comment] 2021-02-20 12:59
> The .mjs extension has been supported for a while -- closing this!

Sure? I've just replaced all my files with `.mjs` and adjusted the imports to include the `.mjs` extension. That's how it works in Node.js 14. Next.js however just shows a 404 page. And renaming a part of the modules to `.mjs` shows `module is not defined`.

**Comment by meglio** [comment] 2021-11-30 23:00
So how do I import .mjs files? It show "ReferenceError: module is not defined" when trying to import an mjs file.

**Comment by balazsorban44** [comment] 2022-01-27 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
