### ISSUE TITLE
getStaticProps incompatible with hybrid AMP dynamic routes

### ISSUE THREAD

**Issue by MickCoelho** [zeit/next.js#11446] opened 2020-03-28 21:30 UTC
# Bug report

## Describe the bug
`getStaticProps` is being ignored when added onto a page (that has a dynamic route and is AMP `hybrid`).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
 1 - Create an hybrid AMP page with dynamic route (for example `pages/test/[id].js`)
 2 - add `getStaticProps` and return data (`{bar: 'foo'}`)
 2 - Run `npm run dev`
 3 - go to `http://localhost:3000/test/1/` 
 4 - the `bar` object is accessible within the props
 5 - go to `http://localhost:3000/test/1?amp=1`  
 6 - the page doesn't render and the console logs the following: 
```
Error: Cannot find module for page: /test/[id].amp
```

## Expected behavior
`getStaticProps` should run on an hybrid AMP page that has a dynamic route (it is the case already for non-dynamic routes).

## Code Sample
```
import { useAmp } from 'next/amp'
export const config = { amp: 'hybrid' };
export async function getStaticProps() {
  return {
    props: {
      bar: 'foo',
    },
  }
}

export default function Index() {
  const {
    bar,
  } = this.props;
  const isAmp = useAmp()
  return (
    <div>
      <p>Bar? {bar}</p>
    </div>
  );
}
```

## System information
- Version of Next.js: `9.3.3`

## Additional context

Somewhat really similar to https://github.com/zeit/next.js/issues/11332 and https://github.com/zeit/next.js/pull/11205/files

**Comment by eheaton** [comment] 2020-04-01 21:11
I'm working on a similar site and having the same issue. Any traction or update on this guy?

**Comment by taylorhayduk** [comment] 2020-04-16 02:17
I had similar issue.  Was about to create new issue till I found this one.

## To Reproduce

Create a `/post/[id].jsx` file and paste in the following:

```
export const config = { amp: 'hybrid' };

function Post(props) {
  return (
    <div>
      <h1>My AMP Post Page!</h1>
      <h2>PostID: {props.id}</h2>
    </div>
  );
}

export async function getStaticPaths() {
  return {
    paths: [{ params: { id: '4' } }],
    fallback: true,
  };
}

export async function getStaticProps({ params }) {
  return { props: { id: params.id } };
}

export default Post;

```

Navigate to `http://localhost:3000/post/4?amp=1`.  You'll get an error similar to the following:
`Error: Cannot find module for page: /post/[id].amp`

**Comment by Gliba** [comment] 2020-05-09 20:27
+1

**Comment by Timer** [comment] 2020-05-19 12:47
Fixed on canary

**Closed by Timer** 2020-05-19 12:47 UTC

**Comment by balazsorban44** [comment] 2022-01-30 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
