### ISSUE TITLE
'ECONNREFUSED' running dev on next@6.0.0

### ISSUE THREAD

**Issue by DanHarman** [zeit/next.js#4252] opened 2018-05-02 15:42 UTC
I'm behind a corporate firewall and have to have a .npmrc setup with a proxy and https-proxy.

There appears to be something in next@6.0.0 that tries to connect to npm on launch and seems to ignore my .npmrc proxy settings as I'm seeing what look like proxy problems when I start my next app in dev mode.

## Expected Behavior

running `yarn dev` or `npm run dev` should bring up the server.

## Current Behavior

```
λ yarn dev
yarn run v1.3.2
$ next
{ Error: connect ECONNREFUSED 151.101.0.162:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '151.101.0.162',
  port: 443 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

n.b. this does not occur when using `yarn build` & `yarn start`.

## Steps to Reproduce (for bugs)
This appears to affect all projects, but I used this one:

https://github.com/zeit/next.js/tree/canary/examples/hello-world

You need to be relying on a custom .npmrc with a proxy - everything is fine if you don't have a proxy.

## Context
This has only broken since upgrading to next@6.0.0 - maybe related to `update-check`?

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |     6.0.0    |
| node    |    8.9.1     |
| OS      |     Windows 7 x64    |

**Comment by timneutkens** [comment] 2018-05-02 16:19
Duplicate of #4237

**Closed by timneutkens** 2018-05-02 16:19 UTC
