### ISSUE TITLE
Dependency loading issue in canary with Experimental API Support

### ISSUE THREAD

**Issue by Rameshv** [zeit/next.js#7328] opened 2019-05-14 12:02 UTC
I am trying out the canary build with the experimental API support https://github.com/zeit/next.js/pull/7296.

I am using Mongoose as my ORM and when I try load a schema from the `/pages/api/product.js` like

```
const Category = require('../../models/category')
export default async (req,res) => {
  const data = Category.find{...}
 res.json(data)
}
```

I am getting this error 

```

{ OverwriteModelError: Cannot overwrite `Category` model once compiled.
    at new OverwriteModelError (/Users/rameshvel/work/dailybasket/node_modules/mongoose/lib/error/overwriteModel.js:20:11)
    at Mongoose.model (/Users/rameshvel/work/dailybasket/node_modules/mongoose/lib/index.js:423:13)
    at Object../models/category.js (/Users/rameshvel/work/dailybasket/.next/server/static/development/pages/api/category.js:142:27)
    at __webpack_require__ (/Users/rameshvel/work/dailybasket/.next/server/static/development/pages/api/category.js:23:31)
    at Module../pages/api/category.js (/Users/rameshvel/work/dailybasket/.next/server/static/development/pages/api/category.js:498:16)
    at __webpack_require__ (/Users/rameshvel/work/dailybasket/.next/server/static/development/pages/api/category.js:23:31)
    at Object.3 (/Users/rameshvel/work/dailybasket/.next/server/static/development/pages/api/category.js:605:18)
    at __webpack_require__ (/Users/rameshvel/work/dailybasket/.next/server/static/development/pages/api/category.js:23:31)
    at /Users/rameshvel/work/dailybasket/.next/server/static/development/pages/api/category.js:91:18
    at Object.<anonymous> (/Users/rameshvel/work/dailybasket/.next/server/static/development/pages/api/category.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at DevServer.handleApiRequest (/Users/rameshvel/work/dailybasket/node_modules/next-server/dist/server/next-server.js:180:59)
  message: 'Cannot overwrite `Category` model once compiled.',
  name: 'OverwriteModelError' }
[ event ] disposing inactive page(s): /api/category
[ ready ] compiled successfully
```

If I comment out the mongoose model loading and just return any random json it works fine. 

## System information
 - OS:  macOS
 - Version of Next.js: [Latest Canary]

Seems something is forcing to recreate the mongoose model. any ideas?

**Comment by HorizonShadow** [comment] 2019-05-20 11:45
Instead of exporting the mongoose.model('Category', schema), try requiring the file and using `mongoose.Model('Category')` to use the model. It kind of seems like next is running the import twice and trying to re-create the Category model.

**Comment by Timer** [comment] 2019-06-14 15:06
Closing as it seems the user above provided the solution. Either way, we'll need a complete reproduction to dig into this further. We can reopen if you're still having issues and can provide a full repository that reproduces this.

**Closed by Timer** 2019-06-14 15:06 UTC

**Comment by sakulstra** [comment] 2019-08-08 14:37
@Rameshv did you find a proper solution to this? I found this: https://www.hoangvvo.com/blog/migrate-from-express-js-to-next-js-api-routes/ and while `export default mongoose.models.User || mongoose.model('User', UserSchema);` seems to work it actually reduces dx a lot as changes to the schema won't be picked up by `next dev` as the old model will be used.

**Comment by johnbarhorst** [comment] 2020-08-16 01:00
I ran into this same issue today, with next v- 9.5.2.  New to next, it took me a bit to stumble on this solution.

**Comment by PrimarchAlpharius** [comment] 2020-08-29 08:17
I am surprised more people didn't run into this issue. Anyway, the export above does work, but it would be nice to have a less hacky way of dealing with this.

**Comment by theonlydaleking** [comment] 2021-09-01 03:18
For anyone else, this can also happen if you misspell something on either side of the `||`

I've seen this solution floating around 

```ts
const MODEL_NAME = "Users" 

export default mongoose.models[MODEL_NAME] || mongoose.model(MODEL_NAME, UserSchema)
```

It's not pretty but it'll work

**Comment by balazsorban44** [comment] 2022-01-27 21:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
