### ISSUE TITLE
Fall back to random open port if specified/default one is in use

### ISSUE THREAD

**Issue by leo** [zeit/next.js#1066] opened 2017-02-10 10:45 UTC
We should use [detect-port](https://www.npmjs.com/package/detect-port), which would basically make it much easier to develop because the app will stop throwing an error if the port is in use and just go with a random one instead.

**Comment by nkzawa** [comment] 2017-02-10 11:41
Duplicate of https://github.com/zeit/next.js/pull/68

We have already discusses this and decided to print a message instead.

https://github.com/zeit/next.js/pull/932

**Closed by nkzawa** 2017-02-10 11:41 UTC
Labels: Good for Beginners, Priority: Medium, Type: Enhancement
