### ISSUE TITLE
`next build` no output on disk

### ISSUE THREAD

**Issue by christopher-wong** [zeit/next.js#7887] opened 2019-07-10 23:12 UTC
# Bug report

## Describe the bug

Running `next build` executes and returns no error, but the static files compiled for production to not appear on disk.

## To Reproduce

Run `yarn build` which runs my `next build`

## Expected behavior

Static files on disk.

## Screenshots

<img width="532" alt="Screen Shot 2019-07-10 at 7 17 12 PM" src="https://user-images.githubusercontent.com/10580086/61011172-62f8f880-a347-11e9-9e50-a402ec3d0e2d.png">

## System information

- OS: macOS
- Version of Next.js: 9.0.0

**Comment by ijjk** [comment] 2019-07-10 23:39
Hi, the output defaults to `.next` which is usually not displayed with `ls -l` you should be able to view it with `ls -a` and the contents with `ls .next`. 

I'm gonna close this since it doesn't seem like the output is actually failing. If you're still having trouble with this feel free to reply with additional details.

**Closed by ijjk** 2019-07-10 23:39 UTC

**Comment by christopher-wong** [comment] 2019-07-11 04:10
Hi @ijjk thanks for the quick reply. Didn't realize the output defaulted to .next, thanks!

**Comment by balazsorban44** [comment] 2022-01-31 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
