### ISSUE TITLE
huge memory use on build?

### ISSUE THREAD

**Issue by MarkLyck** [zeit/next.js#3530] opened 2018-01-03 12:53 UTC
The build process of my next.js application seems to use an unusual amount of memory causing the following error when attempting to deploy with now:

```
> Deploying ~/web/PWA under xxxx@gmail.com
> Using Node.js 8.9.3 (default)
> Ready! https://formulastocks-kixfvvuhaf.now.sh (copied to clipboard) [13s]
> Synced 15 files (27.62KB) [0ms] 
> Initializing…
> Building
> ▲ npm install
> ✓ Using "package-lock.json"
> ⧗ Installing 57 main dependencies…
> ✓ Installed 1295 modules [10s]
> ▲ npm run build
> > FormulaStocks@1.0.0 build /home/nowuser/src
> > next build
> > Using external babel configuration
> > Location: "/home/nowuser/src/.babelrc"
> > Using "webpack" config function defined in next.config.js.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 137
> npm ERR! FormulaStocks@1.0.0 build: `next build`
> npm ERR! Exit status 137
> npm ERR! 
> npm ERR! Failed at the FormulaStocks@1.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nowuser/.npm/_logs/2018-01-03T10_55_16_097Z-debug.log
> Error! The build step of your project failed. To retry, run `now --force`.
```

This was identified in #3407 to be due to the app using way too much memory in the build process and the OSS version of now only allowing 500MB of memory.

Before it was using 1.3GB of memory (when testing the build process locally, as I can't actually see how much it is on now).

I then tried to move ALL of the non-page files out of the pages folder and into the components folder as I was recommended by @timneutkens and I got the build process down to around 700MB.

However, that's still unusually high for just 12 routes?

Why does it use so much memory, and any ideas how to reduce this to an acceptable amount? I will need to add more routes in as well, and if it's already at 700MB even the paid version won't work for me.

Link to failing build: https://formulastocks-kixfvvuhaf.now.sh

**Comment by timneutkens** [comment] 2018-01-03 13:00
@MarkLyck I saw you had something to do with css loading in your next.config.js, it might be caused by that. Since it'll probably build the full styles for every page 🤔

**Comment by timneutkens** [comment] 2018-01-03 13:05
Just checked with a live app that has more than 180 pages (big pages with a lot of logic), peak was a little over 500MB memory usage. So it must be something in your configuration 🤔

**Comment by MarkLyck** [comment] 2018-01-03 13:08
@timneutkens thanks for the quick reply! Just tried without the css still failing, but let me mess around with the config some more and see if I can find the issue.

**Comment by MarkLyck** [comment] 2018-01-03 13:12
@timneutkens hmm I tried to rename the next.config.js file so it's not being used at all, and it's still failing? https://formulastocks-esnkaeavxs.now.sh doesn't seem to be related to the webpack config :(

**Comment by MarkLyck** [comment] 2018-01-05 10:21
I also tried removing my _document file, to see if that was causing something that required a lot of memory on all pages. But that didn't work either...

Any ideas at all what might be causing this!?

**Comment by timneutkens** [comment] 2018-03-16 12:25
Most of the memory use is coming from webpack compiling pages. There's not that much we can do to optimize it unfortunately. Going to close this as this is on our list of things to tackle 👍

**Closed by timneutkens** 2018-03-16 12:25 UTC
