### ISSUE TITLE
PHASE EXPORT not set wher run `export` task

### ISSUE THREAD

**Issue by MartinKristof** [zeit/next.js#8202] opened 2019-08-01 13:56 UTC
# Bug report

## Describe the bug
After update Next.js the detection of phase stops work. It maybe does not work after previous upgrade (Next 7).
I dumped phase during runtime and the result is `phase-production-build` according to https://github.com/zeit/next.js/blob/canary/packages/next-server/lib/constants.ts instead of previous `phase-export`.
I am using it to send source map to Rollbar via forked plugin.

## Expected behavior

Detect phase as `phase-export` when the `npm run export` running.

## Code

```
module.exports = withPlugins(
    [
        nextEnv,
        sourceMaps,
        sass,
        fonts,
        [
            rollbar,
            {
                publicPath: process.env.PUBLIC_PATH,
                accessToken: process.env.ROLLBAR_SERVER_ACCESS_TOKEN,
            },
            [PHASE_EXPORT],
        ],
    ],
    nextConfig,
);

```

## System information

- OS: macOS
- Next.js: "9.0.1"
- next-compose-plugins: "2.2.0"

**Comment by lfades** [comment] 2019-08-06 18:31
@MartinKristof  I'm unable to reproduce this, can you provide a reprodution of the issue? also remember that you need to compare the current phase in progress (`module.exports = (phase) => {`) with the constant (`PHASE_EXPORT`)

**Comment by Timer** [comment] 2019-08-14 01:47
Closing as unable to reproduce.

**Closed by Timer** 2019-08-14 01:47 UTC
Labels: Can't Reproduce, Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 07:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
