### ISSUE TITLE
Routing doesn't working in safari 10 

### ISSUE THREAD

**Issue by hientrandsn** [zeit/next.js#9827] opened 2019-12-25 04:21 UTC
Routing doesn't working in safari 10, I have some code like: 
 onClick={() => route.push(tab.href, tab.href, { shallow: true })}
<Link href="/">back home</Link>
Both of them are not working, I don't know why, please help me

**Comment by timneutkens** [comment] 2020-01-03 01:45
Duplicate of #9851

**Closed by timneutkens** 2020-01-03 01:45 UTC

**Comment by balazsorban44** [comment] 2022-01-30 17:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
