### ISSUE TITLE
Upgrading nextjs v9.3.0 to v.9.3.1 causes Error: Cannot find module 'babel-types'

### ISSUE THREAD

**Issue by vasco3** [zeit/next.js#11153] opened 2020-03-17 19:40 UTC
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. On an existing nextjs v9.3.0 application
2. Bump nextjs to v9.3.1 `npm install next@latest`
3. run dev `next dev`

## Expected behavior

expected a smooth upgrade 

## Screenshots

```
[ error ] ./node_modules/next/dist/client/next-dev.js
[1] Error: Cannot find module 'babel-types'
```

## System information

- OS:  macOS  
- Version of Next.js: 9.3.1
 - @babel/core": "^7.8.7"
- using `.babelrc` with `next/babel` preset

**Comment by vasco3** [comment] 2020-03-17 19:47
I downgraded back to v9.3.0 in the meantime

**Comment by ijjk** [comment] 2020-03-17 20:59
Hi, I'm not able to reproduce this on a minimal Next.js project so it is most likely specific to your environment/project. Wiping `node_modules` and re-creating your lockfile (`yarn.lock` or `package-lock`) may help resolve this for your project

**Comment by vasco3** [comment] 2020-03-17 22:15
I'm seeing some node-gyp errors.. I'll verify and come up with a complete repro

**Comment by vasco3** [comment] 2020-03-17 22:42
I think I found the issue. I am using reasonML based on the nextjs examples. 
I figured out that the babel preset of `babel-plugin-bucklescript` is no longer needed (that's the one requiring `babel-types`. By removing that preset from `.babelrc` it fixed the build.

**Comment by vasco3** [comment] 2020-03-17 22:43
I assume that babel-plugin-bucklescript was using babel-types as a peerDependency from nextjs.. Probably the new nextJS removed that dependency and that's why this babel plugin is crashing

**Comment by vasco3** [comment] 2020-03-17 22:44
I also noticed that babel-plugin-bucklescript is now deprecated and its repo is archived. Should I open a ticket to update the nextjs reason examples?

**Comment by timneutkens** [comment] 2020-03-18 09:14
> I also noticed that babel-plugin-bucklescript is now deprecated and its repo is archived. Should I open a ticket to update the nextjs reason examples?

Yep sure, could be that there's already an open one.

Going to close this issue as it's not related to Next.js, and we can't change anything here. Basically your app worked accidentally previously as that babel plugin was hoisting babel-types.

**Closed by timneutkens** 2020-03-18 09:14 UTC
Labels: Please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-30 10:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
