### ISSUE TITLE
Upgrading from 9.2.1 --> 9.3.5 "Error: Cannot find module 'next/dist/next-server/lib/fid.js'"

### ISSUE THREAD

**Issue by hatchli** [zeit/next.js#11918] opened 2020-04-15 16:41 UTC
Trying to upgrade from 9.2.1 to latest stable release (9.3.5).
Node Version: 10.16

Compiles successfully in terminal, but when opening localhost:port, I'm getting  the following:
```
[ ready ] compiled successfully - ready on http://localhost:7778
{ Error: Cannot find module 'next/dist/next-server/lib/fid.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.../next-server/lib/fid (C:\Users\Wade\Documents\GitHub\myodesign\dist\functions\next\server\static\development\pages\_document.js:136:18)
    at __webpack_require__ (C:\Users\Wade\Documents\GitHub\myodesign\dist\functions\next\server\static\development\pages\_document.js:23:31)     
    at Object../node_modules/next/dist/pages/_document.js (C:\Users\Wade\Documents\GitHub\myodesign\dist\functions\next\server\static\development\pages\_document.js:192:35)
    at __webpack_require__ (C:\Users\Wade\Documents\GitHub\myodesign\dist\functions\next\server\static\development\pages\_document.js:23:31)     
    at Object../node_modules/next/document.js (C:\Users\Wade\Documents\GitHub\myodesign\dist\functions\next\server\static\development\pages\_document.js:878:18)
    at __webpack_require__ (C:\Users\Wade\Documents\GitHub\myodesign\dist\functions\next\server\static\development\pages\_document.js:23:31)     
    at Module../pages/_document.js (C:\Users\Wade\Documents\GitHub\myodesign\dist\functions\next\server\static\development\pages\_document.js:895:71)
    at __webpack_require__ (C:\Users\Wade\Documents\GitHub\myodesign\dist\functions\next\server\static\development\pages\_document.js:23:31)     
    at Object.1 (C:\Users\Wade\Documents\GitHub\myodesign\dist\functions\next\server\static\development\pages\_document.js:996:18)
    at __webpack_require__ (C:\Users\Wade\Documents\GitHub\myodesign\dist\functions\next\server\static\development\pages\_document.js:23:31)     
    at module.exports.../../node_modules/common/src/assets/image/favicon-32.png.module.exports (C:\Users\Wade\Documents\GitHub\myodesign\dist\functions\next\server\static\development\pages\_document.js:91:18)
    at Object.<anonymous> (C:\Users\Wade\Documents\GitHub\myodesign\dist\functions\next\server\static\development\pages\_document.js:94:10) code: 'MODULE_NOT_FOUND' }
```

`next.config`
```
const withPlugins = require("next-compose-plugins");
const withTM = require("next-transpile-modules");
const withOptimizedImages = require("next-optimized-images");
const withFonts = require("next-fonts");
const withCSS = require("@zeit/next-css");
module.exports = {
  webpack: (config, { isServer }) => {
    // Fixes npm packages that depend on `fs` module
    if (!isServer) {
      config.node = {
        fs: "empty"
      };
    }

    return config;
  }
};

module.exports = withPlugins(
  [
    [
      withTM,
      {
        transpileModules: ["reusecore", "common"]
      }
    ],
    [
      withOptimizedImages,
      {
        mozjpeg: {
          quality: 90
        },
        webp: {
          preset: "default",
          quality: 90
        }
      }
    ],
    withFonts,
    withCSS
  ],
  {
    distDir: "../../dist/functions/next"
  }
);
```

`_document.js`
```
import Document, { Html, Head, Main, NextScript } from "next/document";
import { ServerStyleSheet } from "styled-components";
import FavIcon from "common/src/assets/image/favicon-32.png";

export default class CustomDocument extends Document {
  static async getInitialProps(ctx) {
    const sheet = new ServerStyleSheet();
    const originalRenderPage = ctx.renderPage;

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: App => props => sheet.collectStyles(<App {...props} />)
        });

      const initialProps = await Document.getInitialProps(ctx);
      return {
        ...initialProps,
        styles: (
          <>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </>
        )
      };
    } finally {
      sheet.seal();
    }
  }
  render() {
    return (
      <html lang="en">
        <Head>
          <link rel="shortcut icon" type="image/x-icon" href={FavIcon} />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}
```

**Comment by tavidian** [comment] 2020-04-16 14:22
same is happening to me

**Comment by mabc224** [comment] 2020-04-16 15:42
same is happening to me

**Comment by jshuadvd** [comment] 2020-04-21 17:05
same happening here...

**Comment by lambda2** [comment] 2020-04-25 17:32
same here

**Comment by hatchli** [comment] 2020-04-25 17:34
I just want to let everyone know that I managed to solve the issue by going to the canary build (10). Give it a try. It's not a real solution or explanation, but it seems like the Vercel team is just ignoring this.

**Comment by jshuadvd** [comment] 2020-04-25 18:49
@hatchli thank you! I'll try this

**Comment by timneutkens** [comment] 2020-04-25 18:59
> but it seems like the Vercel team is just ignoring this.

Not ignoring it. The issue was not closed. Note that there are 421 open issue as of currently.

You did not follow the issue template btw. It asks for a clear and concise reproduction, what was provided are 2 files.

**Comment by lambda2** [comment] 2020-04-25 19:33
A rollback to 9.3.4 worked for me

**Comment by hatchli** [comment] 2020-04-25 20:24
> > but it seems like the Vercel team is just ignoring this.
> 
> Not ignoring it. The issue was not closed and currently has 2  from other people. Note that there are 421 open issue as of currently.
> 
> You did not follow the issue template btw. It asks for a clear and concise reproduction, what was provided are 2 files.

Fair enough! I don't have the ability to open my repo, not the resources to make a new one atm. Glad to hear this was on the radar though :)

**Comment by Pixelatex** [comment] 2020-05-13 12:24
My site suddenly got this issue, been on v9.3.6 for 10 days with no issue. Suddenly it happened :/

**Comment by lambda2** [comment] 2020-05-13 15:04
Seems to works well on v9.4.0 too

**Comment by tettoffensive** [comment] 2020-05-14 22:14
I'm getting this error on v9.4.0

**Comment by lambda2** [comment] 2020-05-14 23:13
I upgraded my NextJS app to 9.4.0 and "so far" it didn't happened again in local and production.

ℹ️ Here is my project code: https://github.com/lambda2/luua/tree/master/frontend (if looking at the `package.json` can help to better understand this issue).

**Comment by devergroupio** [comment] 2020-05-15 17:58
me too :(. worked well before but now it's happen

**Comment by Timer** [comment] 2020-05-15 18:19
Closing as no reproduction was provided. Please upgrade to 9.4 and let us know if it still happens.

**Closed by Timer** 2020-05-15 18:19 UTC

**Comment by vhpoet** [comment] 2020-05-19 01:39
Happened to me too. Downgrading to `9.3.6` fixed it.

**Comment by timneutkens** [comment] 2020-05-19 08:56
Can you upgrade to 9.4.1?

**Comment by tmhenry** [comment] 2020-06-03 11:02
For those who have the same problem, I solve it by removing and reinstalling next using yarn. I've used the 9.3.5 version. 

The downgrade failed once for me, which I later found due to yarn.lock issue. 

Hope this helps.

**Comment by esamattis** [comment] 2020-09-15 11:36
I saw this when upgrading from 9.3.6 to 9.5.3 but it was solved by removing the `.next` directory which was generated by the old version.

**Comment by MiguelMachado-dev** [comment] 2020-10-27 17:20
Here I solved by doing
`ctrl + shift + p`
`> TypeScript: Restart TS server`

**Comment by luannoe** [comment] 2020-11-04 12:02
> Here I solved by doing
> `ctrl + shift + p`
> `> TypeScript: Restart TS server`

This worked for me! 👍

**Comment by luannoe** [comment] 2020-11-04 12:27
Delete `node_modules` folder and run `npm i` again, worked for me! :)

**Comment by balazsorban44** [comment] 2022-01-29 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
