### ISSUE TITLE
How to enable brotli compression using express-static-gzip

### ISSUE THREAD

**Issue by snly2386** [zeit/next.js#7501] opened 2019-06-04 23:32 UTC
I'm trying to enable Brotli compression using express-static-gzip in my Next.Js 8.0.3 app.  I've generated the brotli files using the webpack-brotli-plugin.  

In my server.js, I'm not sure what values to use as the filepath in production.  I'm setting both values to /static.  Using my current configruation (below), I have not been able to serve brotli or gzipped files (verified by the Content-Encoding header).  Any guidance would be appreciated.

```
server.use('/static', expressStaticGzip('/static', {
      enableBrotli: true,
      orderPreference: ['br', 'gz'],
      setHeaders: function (res, path) {
        res.setHeader("Cache-Control", "public, max-age=4444444444")
      }
    }
  ))
```

**Comment by Riccardo-Andreatta** [comment] 2019-06-05 09:35
You do not need to specify the `orderPreference` as it should be already like that by default

**Comment by timneutkens** [comment] 2019-06-05 11:09
Closing this as it doesn't follow the issue template.

**Closed by timneutkens** 2019-06-05 11:09 UTC

**Comment by balazsorban44** [comment] 2022-01-31 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
