### ISSUE TITLE
[example/auth0] Failed to authenticate in "next start"

### ISSUE THREAD

**Issue by lightsound** [zeit/next.js#9003] opened 2019-10-09 05:05 UTC
# Examples bug report

## Example name

auth0

## Describe the bug

Authentication cannot be completed in "next start".
Of course, I tried after the "next build".

It worked in "next" (= yarn dev ).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'http://localhost:3000/'
2. Click on 'Login'
3. Please enter your auth ID/PW.
4. See error `state mismatch, expected *****, got: *****`.

## Expected behavior

Completion of authentication and go back to application page.

## Screenshots

After "reproduce 3", you'll see this error message.
![image](https://user-images.githubusercontent.com/8220973/66452936-6a8e8180-ea9d-11e9-929f-331eb3da7313.png)

## System information

- OS: macOS
- Browser chrome
- Version of Next.js: 9.0.8 (9.1.1 has same error)

**Comment by ijjk** [comment] 2019-10-09 13:25
Hi, I believe this is because the `nextjs-auth0` package sets the `secure` field for cookies when running in production mode which means you would need to access the site using `https`. You can achieve this by proxying the requests through a server that handles `https` or deploying with a service like [ZEIT Now](https://zeit.co) that handles `https` for you

Relevant line in `nextjs-auth0` package [here](https://github.com/auth0/nextjs-auth0/blob/f2c5b6792aadfdfee210e0f9eaf738e8a75f1092/src/utils/cookies.ts#L57)

**Comment by lightsound** [comment] 2019-10-10 03:12
@ijjk 
Thanks, I fully understood and confirmed it actually works on ZEIT Now.

But, I found it cumbersome to edit `now.json` every time to see if it works on staging environment. `REDIRECT_URI` and `POST_LOGOUT_REDIRECT_URI` params are different from production and staging. Is there a way to check more easily?

And, It may be another issue, when I develop using `now dev` instead of `next` script, what should I do? I checked following docs tried it in various ways. But I couldn't work well. Could you tell me how to do that.
- https://zeit.co/docs/v2/serverless-functions/env-and-secrets/?query=env#during-local-development
- https://zeit.co/docs/v2/environment-variables-and-secrets/?query=.env.build#local-development

**Comment by ijjk** [comment] 2019-10-10 17:16
Closing as this has been updated now

**Closed by ijjk** 2019-10-10 17:16 UTC

**Comment by lightsound** [comment] 2019-10-11 04:36
@sandrinodimattia 
I upgraded the version and confirmed it works on localhost.
Thanks a lot.

**Comment by balazsorban44** [comment] 2022-01-31 02:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
