### ISSUE TITLE
Provide an option to configure the API route path

### ISSUE THREAD

**Issue by oliviertassinari** [zeit/next.js#8123] opened 2019-07-26 09:07 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Next.js v9.0.0 hard codes the route name of the API path: `/api/`.

https://github.com/zeit/next.js/blob/71f9288a54c32420a18a07035ea7a73c9c3c50e5/packages/next/lib/constants.ts#L19

In Material-UI, we host pages under the `/api/` folder. For instance: https://v3.material-ui.com/api/app-bar/. It forces us to rename this folder. This has an SEO impact. 

## Describe the solution you'd like

We would be interested in having an option to configure this path. For instance, I could imagine something like:

**next.config.js**
```js
module.exports = {
  apiRoutePath: 'json-api',
};
```

## Additional context

- The related thread on our side: https://github.com/mui-org/material-ui/pull/16752
- I had an initial discussion about the problem with @timneutkens on Twitter. 
- It seems relatively simple to implement as we have access to the config here:
https://github.com/zeit/next.js/blob/71f9288a54c32420a18a07035ea7a73c9c3c50e5/packages/next/build/entries.ts#L51

**Comment by timneutkens** [comment] 2019-07-26 11:02
It's actually not super simple to change it, and I'd rather not if not really required. We have talked about a page-level opt-out thought, but haven't really had community interest until now.

**Comment by eps1lon** [comment] 2019-07-26 14:08
> We have talked about a page-level opt-out

That would work for our use case. Will take a look at making this work. Any things I should pay extra attention to?

**Comment by timneutkens** [comment] 2019-07-26 14:15
It's slightly complicated as this also ties into the serverless target and hosting (@now/next). I'll have @huv1k take a look 👍

**Comment by timneutkens** [comment] 2020-01-02 21:27
Closing this in favor of https://github.com/zeit/next.js/issues/9081

**Closed by timneutkens** 2020-01-02 21:27 UTC

**Comment by balazsorban44** [comment] 2022-01-30 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
