### ISSUE TITLE
Getting `Couldn't find a `pages` directory. Please create one under the project root` with Next.js 9.0.7

### ISSUE THREAD

**Issue by ccambournac** [zeit/next.js#8914] opened 2019-09-30 13:24 UTC
# Bug report

## Describe the bug
With Next.js 9.0.7, after Next.js and deployment of directories and files below listed, the application is unable to start because of the following error : `Couldn't find a `pages` directory. Please create one under the project root`. It works well again after rolling back to Next.js 9.0.6.

Deployed files and folders:
- `.next`
- `data`
- `node_modules`
- `static`
- `next.config.js``
- `package.json`
- `pm2.config.js`

## To Reproduce
Build a minimal application with Next.js 9.0.7 and deploy it without /pages source folder.

## Expected behavior
Built application should run without source files.

## System information

- OS: Debian 8.5
- Version of Node.js: 10.16.3
- Version of Next.js: 9.0.6/9.0.7

**Comment by timneutkens** [comment] 2019-09-30 13:25
Duplicate of https://github.com/zeit/next.js/issues/8893

**Closed by timneutkens** 2019-09-30 13:25 UTC
