### ISSUE TITLE
 browser back didn't work

### ISSUE THREAD

**Issue by poyiding** [zeit/next.js#9859] opened 2019-12-28 05:58 UTC
# Bug report
I find a bug about browser back didn't work, and when i import the css ,it work.
I provided a [demo](https://github.com/poyiding/next-js-bug-rep) to reproduce the problem。
## Describe the bug
1. click "link about" link to /about/123 page
2. refresh the page, then click browser back, you will find it stop in current page.
3. if you import '../styles/global.css ' in about page and reload page, browser back it work ok.

**Comment by timneutkens** [comment] 2019-12-28 12:16
Closing this as no reproduction is provided.

**Closed by timneutkens** 2019-12-28 12:16 UTC
Labels: Can't Reproduce

**Comment by poyiding** [comment] 2019-12-29 17:09
I have referred to this issue and the problem has been solved. I hope the next.js team can fix the bug as soon as possible.

**Comment by balazsorban44** [comment] 2022-01-30 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
