### ISSUE TITLE
Compiling too slow on next 9.4

### ISSUE THREAD

**Issue by ranjithkumar8352** [zeit/next.js#12797] opened 2020-05-12 15:44 UTC
# Bug report

## Describe the bug

Hello, I just upgraded next from 9.3 to 9.4 today. It seems that compiling a single page takes too long. More than 3 minutes. Sometimes it never compiles too.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Install next 9.4
2. run `next dev` and start the server
3. Go to any page in `localhost:3000`
4. It takes a very long time to compile and even it compiles, the page never loads on browser sometimes.

## Expected behavior

It should compile the page faster (usually 5 to 10 seconds) and load the page.

## Screenshots

![image](https://user-images.githubusercontent.com/10174991/81715132-790aa480-9495-11ea-89a3-209c47b6ee32.png)

## System information

- OS: Windows
- Version of Next.js: 9.4
- Version of Node.js: 12.16.3

**Comment by Timer** [comment] 2020-05-12 15:59
Could you please give us a full reproduction? We'll need it to reproduce and track this down. 🙏

**Comment by ranjithkumar8352** [comment] 2020-05-12 16:04
@Timer Its a private codebase.
Here's the `package.json`
```
{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "build:staging": "cross-env NEXT_PUBLIC_ENV=staging next build",
    "start": "next start -p 8081",
    "start:staging": "cross-env NEXT_PUBLIC_ENV=staging next start -p 8081"
  },
  "dependencies": {
    "@stripe/stripe-js": "^1.5.0",
    "@zeit/next-sass": "^1.0.1",
    "aws-amplify": "^3.0.8",
    "bulma": "^0.8.2",
    "graphql-tag": "^2.10.3",
    "mobx": "4.x",
    "mobx-react": "^6.2.2",
    "next": "^9.4.0",
    "node-fetch": "^2.6.0",
    "node-sass": "^4.13.1",
    "nookies": "^2.2.2",
    "nprogress": "^0.2.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native-web": "^0.12.2"
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/plugin-proposal-decorators": "^7.8.3",
    "@react-native-community/eslint-config": "^1.0.0",
    "babel-plugin-react-native-web": "^0.12.2",
    "cross-env": "^7.0.2",
    "eslint": "^6.8.0"
  }
}
```
It takes too long to compile even for a page with a single div.  Can you tell me what other details should I share?

**Comment by Timer** [comment] 2020-05-12 16:06
Sorry, but we'll need a full demo to provide any more insights. You can try to reduce your app to a single page without private data.

**Comment by SelvinM** [comment] 2020-05-12 17:40
I'm having the same problem

**Comment by s-kris** [comment] 2020-05-13 05:25
I'm having the same problem

**Comment by Timer** [comment] 2020-05-13 05:27
Hi everyone!

Replying with "+1"s do not help us prioritize this issue any quicker. If you'd like us to fix this problem, please provide a reproducible demo.

Thanks!

**Comment by s-kris** [comment] 2020-05-13 06:09
Hey @Timer,
Here it is: https://github.com/s-kris/loading-test

Steps to reproduce:
1. Clone above repo && run `yarn dev` && go to `localhost:3000`.
2. Click on `click here to go to test page`. 
3. Hit refresh button on browser.
4. Click back button on browser.
5. Repeat steps 2, 3 & 4. Hit refresh. You can see that page loads forever. Closing the tab and loading `localhost:3000` doesn't fix either.

Video: https://www.youtube.com/watch?v=orS_6SbEafc

**Comment by Timer** [comment] 2020-05-13 06:10
Thank you! We'll look at this soon.

**Comment by mahmoudm-mvsi** [comment] 2020-05-14 06:02
Thanks @Timer I'm having the same issue here with a very small project too...

**Comment by timneutkens** [comment] 2020-05-14 18:52
> Thanks @Timer I'm having the same issue here with a very small project too...

@mahmoudm-mvsi, As said by @Timer:

> Replying with "+1"s do not help us prioritize this issue any quicker. If you'd like us to fix this problem, please provide a reproducible demo.

Your comment does not add to this issue and is the equivalent to saying `+1`. Please use GitHub's emoji reactions if you want to "+1" an issue.

**Closed** 2020-05-15 12:30 UTC
Labels: Type: Needs Investigation

**Comment by Timer** [comment] 2020-05-15 12:54
Could everyone please try `next@9.4.1-canary.5` and see if that resolves their speed issue?

**Comment by ranjithkumar8352** [comment] 2020-05-15 15:37
@Timer It is resolved in `next@9.4.1-canary.5` Thanks for the quick fix!

**Comment by Timer** [comment] 2020-05-15 15:40
For those curious, this was caused by Windows Defender. Windows Defender was blocking the HMR because our emitted JavaScript files contained the word `eval`!

**Comment by ranjithkumar8352** [comment] 2020-05-15 15:51
That's interesting!

**Comment by s-kris** [comment] 2020-05-15 16:18
@Timer It's fixed now, thanks! But I'm on MacOS 10.15.4!

**Comment by Timer** [comment] 2020-05-15 16:27
@s-kris the repo you posted was something else that's still a bug: #5598.

**Comment by s-kris** [comment] 2020-05-15 16:33
Just checked #5598, interesting. On the first try it seemed to be fixed but I'll keep a track on this (not using nextjs currently for any active projects).

**Comment by Timer** [comment] 2020-05-15 16:46
We're planning on fixing it as part of webpack 5, which is coming 🔜!

**Comment by mahmoudm-mvsi** [comment] 2020-05-16 09:20
> For those curious, this was caused by Windows Defender. Windows Defender was delaying the HMR (to do a scan) because our emitted JavaScript files contained the word `eval`! That's why macOS was unaffected.

I'm really curious to know how did you find out about that! lol

**Comment by timneutkens** [comment] 2020-05-16 09:37
> > For those curious, this was caused by Windows Defender. Windows Defender was delaying the HMR (to do a scan) because our emitted JavaScript files contained the word `eval`! That's why macOS was unaffected.
> 
> I'm really curious to know how did you find out about that! lol

Profiling together with @sokra

**Comment by mosesoak** [comment] 2020-07-17 16:46
Wow, this issue saved me a headache, thank you @Timer!!! It looks like HMR was disabled by Windows Defender: when on, Next was doing a full rebuild / page refresh, ~20 seconds vs ~1 second. Huge diff. 

Here's where you turn it off: click the Manage Settings link in **Settings > Security > Virus & Threat Protection**. Note that it says it will turn itself back on after some amount of time. Anyone know how to configure it? I dug around in Control Panel and couldn't find anything.

![image](https://user-images.githubusercontent.com/24345/87810026-322c8880-c811-11ea-9b50-b63f2f80b77e.png)

**Comment by mosesoak** [comment] 2020-07-17 16:49
Wondering if this issue might be key to fixing this? Obviously we don't want to have to disable security on our machine just to use Next! https://github.com/vercel/next.js/issues/14266

**Comment by Timer** [comment] 2020-07-17 16:49
That is the correct issue to follow, @mosesoak!

**Comment by mosesoak** [comment] 2020-07-17 17:01
Cool thanks. Just found out from a very smart friend that you can fix the issue more cleanly by leaving Defender turned on but setting your project folder as an Exception:

![image](https://user-images.githubusercontent.com/24345/87812028-6e151d00-c814-11ea-9111-4e06e90faa4a.png)

**Comment by tom1mat** [comment] 2020-08-01 15:27
Hi guys! Firstyle thank you for your awesome support always!! @Timer @timneutkens 
I am having the same problem stated in the issue description in macOS Mojava 10.14.6.
I tried with **next@9.4.1-canary.5** and the last **next@9.5.1**

Package Json:
```
{
  "name": "web-porpora",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "start-dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@babel/polyfill": "^7.10.1",
    "@material-ui/core": "^4.10.2",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.56",
    "@sendgrid/mail": "^7.2.1",
    "@zeit/next-sass": "^1.0.1",
    "bcrypt": "^5.0.0",
    "classnames": "^2.2.6",
    "cookie": "^0.4.1",
    "debounce": "^1.2.0",
    "dotenv": "^8.2.0",
    "formidable": "^1.2.2",
    "formik": "^2.1.4",
    "js-cookie": "^2.2.1",
    "jsonwebtoken": "^8.5.1",
    "mysql": "^2.18.1",
    "next": "^9.5.1",
    "node-sass": "^4.14.1",
    "react": "16.13.1",
    "react-click-outside": "github:tj/react-click-outside",
    "react-dom": "16.13.1",
    "react-dropzone": "^11.0.2",
    "react-table": "^7.2.1",
    "s": "^1.0.0",
    "yup": "^0.29.1"
  },
  "devDependencies": {
    "@types/node": "^14.0.6",
    "@types/react": "^16.9.35",
    "@types/react-dom": "^16.9.8"
  }
}
```

next.config
```
const withSass = require('@zeit/next-sass')
module.exports = withSass({
  webpack: (config, { isServer }) => {
    // Fixes npm packages that depend on `fs` module
    if (!isServer) {
      config.node = {
        fs: 'empty'
      }
    }

    return config
  }
})
```

.babelrc
```
{
  "presets": [
    [
      "next/babel",
      {
        "preset-env": {},
        "transform-runtime": {},
        "styled-jsx": {},
        "class-properties": {}
      }
    ]
  ],
  "plugins": []
}
```

**Comment by PrimeObjects** [comment] 2020-08-13 18:13
Got the same slow, and the webpack took around 30 s 
![image](https://user-images.githubusercontent.com/3459952/90171193-fb855780-dd55-11ea-9c76-fb19c531dad9.png)

**Comment by timneutkens** [comment] 2020-08-14 13:49
webpack-hmr is only an eventsource connection that stays open hence why the time keeps running, it's unrelated to webpack compilation times.

**Comment by asdofindia** [comment] 2020-09-02 15:27
I just want to add a comment here although it is definitely not the problem that others faced.

I was having slow compilation time on Ubuntu. The problem was that I had graalvm installed and the "node" binary that was getting executed was the one provided by graalvm. Removing that from the $PATH solved the issue.

This might help someone.

**Comment by usama-asfar** [comment] 2021-03-10 01:29
> For those curious, this was caused by Windows Defender. Windows Defender was delaying the HMR (to do a scan) because our emitted JavaScript files contained the word `eval`! That's why macOS was unaffected.

but I'm using Ubuntu.

**Comment by vgb0332** [comment] 2021-03-16 03:35
Everyone I've been having the exact same issue for a long time and tried every possible solution I could find on the internet.
And I finally found an answer to my case. i hope it helps some people with similar problems.

My project uses quill, ckeditor, less, ant design for third libraries and had to configure next.config.js for them.
I figured their configurations require massive amount of regex check which have caused the slow build issue(even heap out of memory issue).

I haven't been able to find an alternative to fasten things up with these configuration.
But my recommendation is for 'dev' environment slash these configuration setting unless really important or necessary.

**Comment by dailytravel** [comment] 2021-08-07 08:18
NextJS compile slow after I try test with pwa. You need clear data from application as the bellow to fix it! 
![image](https://user-images.githubusercontent.com/43479213/128593779-2c9ebd38-8d8b-4847-bc31-e9242c3fef33.png)

**Comment by erfanasbari** [comment] 2021-08-12 10:51
My project took around 30sec for a page to compile and it took around 10 seconds for hot reloading, also the ram usage was very high (4 Gb on mac). I tried a lot of methods but it wasn't working. I analyzed the bundle using `@next/bundle-analyzer` and I saw `react-icons` was the largest package that was being parsed. So I went to [`react-icons` NPM page](https://www.npmjs.com/package/react-icons) and saw this:

> If your project grows in size, this option is available. This method has the trade-off that it takes a long time to install the package.
```
yarn add @react-icons/all-files
# or
npm install @react-icons/all-files --save
```
Example usage:
```
import { FaBeer } from "@react-icons/all-files/fa/FaBeer";
class Question extends React.Component {
  render() {
    return <h3> Lets go for a <FaBeer />? </h3>
  }
}
```

So I did that and the ram usage decreased by 3 Gb and the compile time decreased as well and now everything is ok.
Note: you can apply the same method for other libraries like `@material-ui/icons`

My project was ok on react and I don't know why next has some problems with importing a single value from a large module.

**Comment by CrispenGari** [comment] 2021-09-07 23:10
I've tried all these mentioned methods none of them worked on my situation. Developing in nextjs is becoming a pain. Can you guys improve this on windows we are suffering and its stressful spending half of a day staring on the browser waiting for the code to compile only to find out that you have an error. Im coming beck to nextjs when this bug is fixed, for now let me use gasty and react.

**Comment by timneutkens** [comment] 2021-10-08 08:14
FYI I'm tracking a new thread here: https://github.com/vercel/next.js/issues/29559#issuecomment-938431883
