### ISSUE TITLE
a11y: Link does not support activating with [enter] on non <a> components

### ISSUE THREAD

**Issue by lucacasonato** [zeit/next.js#12179] opened 2020-04-24 19:24 UTC
# Bug report

## Describe the bug

Currently it is not possible to activate a `<Link>` that wraps a by default non interactive component (like a `div` or a `tr`) by pressing the enter key. This is something that should be included by default imo. https://developer.mozilla.org/en-US/docs/Web/Accessibility/Keyboard-navigable_JavaScript_widgets says that any clickable object should be activatable using the keyboard. The reason it already works for `<a>` is because this element handles the keyboard events under the hood.

## To Reproduce

```jsx
<Link href="/abc">
   <tr role="button" tabIndex={0}>
      ...   
   </tr>
</Link>
```

1. Select the `<tr>` using tab
2. Press [enter]
3. Navigation does not occur

## Expected behavior

`next/link` should not just listen to `onClick` events but also `onKeyDown` with the key == "enter".

**Comment by leerob** [comment] 2020-05-13 02:45
I'm trying to understand your use case. Can you not have the child be an `a` tag? It seems like you're trying to navigate to another page, which seems like a valid use for `a`.

**Comment by lionel-rowe** [comment] 2020-05-15 11:26
@leerob https://html.spec.whatwg.org/multipage/tables.html#the-tr-element

> **Contexts in which this element can be used:**
> As a child of a `thead` element.
> As a child of a `tbody` element.
> As a child of a `tfoot` element.
> As a child of a table element, after any `caption`, `colgroup`, and `thead` elements, but only if there are no `tbody` elements that are children of the `table` element.

Inserting an intermediate `a` tag between a `tr` and its parent therefore wouldn't be valid HTML.

With that said... it does seem like a child of `Link` should have `role="link"` rather than `role="button"` 🤔

A related issue - <kbd>Ctrl</kbd> + click and <kbd>Ctrl</kbd> + <kbd>Enter</kbd> also don't open the link in a new tab.

**Comment by timneutkens** [comment] 2020-05-25 14:03
We're planning to force an `<a>` tag always as per https://github.com/zeit/next.js/issues/8207, so I'll close this issue in favor of that.

**Closed by timneutkens** 2020-05-25 14:03 UTC

**Comment by balazsorban44** [comment] 2022-01-30 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
