### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by Luktm** [zeit/next.js#6079] opened 2019-01-17 15:58 UTC
## Window is not defined every time npm install reactjs modules
window is not defined after install react-chat-widget or any others reactjs modules

## Error of  Window is not defined when import react modules
when i import the module as picture below:

1) import module 
![import-widget](https://user-images.githubusercontent.com/24861458/51331277-58eeef00-1ab4-11e9-9fda-1fc74b4e4381.PNG)

2) use module into render function
![insert-render](https://user-images.githubusercontent.com/24861458/51331288-5ee4d000-1ab4-11e9-92d1-17a07e276f94.PNG)

3) next.config.js with zeit/next-css npm package
![capture](https://user-images.githubusercontent.com/24861458/51331356-850a7000-1ab4-11e9-984c-90b401e97052.PNG)

4) package.json
![package-json](https://user-images.githubusercontent.com/24861458/51330339-4a9fd380-1ab2-11e9-892c-b981bc89ff49.PNG)

## Step to get error
Steps to produce the error after install react modules:
1. Open cmd as administration
2. run "yarn run dev"
3. localhost:3000 started
4. open chrome browser, refresh
5. Unhandled Rejection (ReferenceError): window is not defined

## Expected behavior
I expect react-chat-widget it can do like this as picture below after installed module:
![react-chat-widget-snap](https://user-images.githubusercontent.com/24861458/51330541-b6823c00-1ab2-11e9-87a7-403ba2c641ac.PNG)

## Screenshots of Error shows in browser after run it
![capture](https://user-images.githubusercontent.com/24861458/51330597-cbf76600-1ab2-11e9-8e70-1143c1a7cf61.PNG)

## System information
 - OS: Windows
 - chrome
 - Version of Next.js: [e.g. 7.0.2]

**Comment by timneutkens** [comment] 2019-01-17 16:14
Duplicate of #6080

**Closed by timneutkens** 2019-01-17 16:14 UTC
