### ISSUE TITLE
with-ant-design bundle file is too big

### ISSUE THREAD

**Issue by Shangyunliang** [zeit/next.js#4101] opened 2018-04-03 06:59 UTC
![image](https://user-images.githubusercontent.com/18652330/38233858-9aa243e2-374e-11e8-9b46-a3a91d99ac61.png)

### Can we optimize it?

**Comment by timneutkens** [comment] 2018-04-03 07:08
Try analyzing using https://github.com/zeit/next-plugins/tree/master/packages/next-bundle-analyzer

**Comment by supra28** [comment] 2018-04-04 09:16
I think it imports the whole css rather than importing just the css for the components that are used

**Comment by xavcz** [comment] 2018-04-05 08:37
CSS Bundle
---
![server bundle result screenshot](https://cl.ly/2R3E31003v47/Capture%20d%E2%80%99e%CC%81cran%202018-04-05%20a%CC%80%2010.28.27.png)

> ⬆️ Server bundle, with almost no CSS loaded (~500 bytes? 🤔), [click to read the tooltip](https://cl.ly/0A1i3A010H3y/Capture%20d%E2%80%99e%CC%81cran%202018-04-05%20a%CC%80%2010.27.33.png)

> I think it imports the whole css rather than importing just the css for the components that are used

I believed the same, and it actually imports *only* what it needs in terms of CSS! 😄 

I would guess the `style.css` file is "that big" because `@zeit/next-css` plugin SSR feature is a work in progress, see https://github.com/zeit/next-plugins/issues/1

JS Bundle
---
![client bundle screenshot](https://cl.ly/0A1i3A010H3y/Capture%20d%E2%80%99e%CC%81cran%202018-04-05%20a%CC%80%2010.27.33.png)

> ⬆️ Client bundle, loading only the components specified in the example, [click to read the tooltip](https://cl.ly/0A1i3A010H3y/Capture%20d%E2%80%99e%CC%81cran%202018-04-05%20a%CC%80%2010.27.33.png)

The `index.js` bundle is "that big" cause [the example imports some heavy components (code)](https://github.com/zeit/next.js/blob/dac2f39a257a690124abf372c25d2c2b0e769d23/examples/with-ant-design/pages/index.js#L2), like the `Form` or the `DatePicker`. 

These components are super-fully-featured and rely on other packages, like components from https://github.com/react-component/ or depend on `moment` (one-third of the bundle!)

Try just importing the `Button` and you'll see a neat difference! 📉 

Conclusion
---
1. `next-bundle-analyzer` is dope! 🚀
2. When `next-css` is fixed, we shouldn't have to load CSS on the client 👌 
3. `antd` is a great library, but can cost you in terms of size / dependencies! 👍

**Comment by aimeefe** [comment] 2018-04-26 10:43
[
      "import",
      {
        "libraryName": "antd"
      }
    ]

**Comment by lifuzhao100** [comment] 2018-05-01 16:00
@aimeefe can u teach me how config babel-plugin-import with antd.now i got a error 
@font-face {
^

SyntaxError: Invalid or unexpected token

**Comment by ashinga48** [comment] 2018-05-12 08:45
@Shangyunliang 
Please have a look. @supra28 suggestion, i kept in an example.

**## 1. ANT Design imports optimisation ( to reduce build size )**
Replace

`import { DatePicker, Avatar, Badge } from 'antd';`
with

```
import DatePicker from 'antd/lib/date-picker';
import Avatar from 'antd/lib/avatar';
import Badge from 'antd/lib/badge';
```
with that build changed from **1.4MB to 560KB**

**## 2. ANT Design CSS import**
Instead statical import of full css like this

`import stylesheet from 'antd/dist/antd.min.css';`
Use

```
import stylesheet from 'antd/lib/style/index.css'
import Badge_CSS from 'antd/lib/badge/style/index.css'
```

[Example File](https://github.com/ashinga48/Fifi-NextJS-ANT-Design-Redux-Styled-JSX-with-SCSS/blob/master/pages/index.js)

https://github.com/ashinga48/Fifi-NextJS-ANT-Design-Redux-Styled-JSX-with-SCSS/blob/master/pages/index.js

Hope it helps

**Comment by supra28** [comment] 2018-05-12 10:37
@ashinga48 [babel-plugin-import](https://github.com/ant-design/babel-plugin-import) from ant-design does those things automatically.
[Docs](https://ant.design/docs/react/getting-started#Import-on-Demand)

**Comment by delikat** [comment] 2018-06-10 23:02
@lifuzhao100 and anyone else who runs into SyntaxErrors using babel-plugin-import with next, you have to exclude `antd` from webpack externals as described here: https://github.com/zeit/next-plugins/issues/70#issuecomment-368090305

**Comment by YUFENGWANG** [comment] 2018-07-21 01:39
@ashinga48 didn't work at all

**Comment by Enalmada** [comment] 2018-09-20 05:49
Note there is some information in [this](https://github.com/zeit/next.js/issues/484#issuecomment-419603009) thread about getting modular ant design.

**Comment by kushalmahajan** [comment] 2019-01-01 07:08
Webpack in CRA builds add to +219kb to initial chunk. Whereas importing manual way adds  +12 i.e. becomes +231kb

**Comment by qaiser110** [comment] 2019-01-23 08:50
I've created `src/client/icons.js` at the root. In this file I have all the antd icons that I need like so:

```js
export { default as SwapOutline } from '@ant-design/icons/lib/outline/SwapOutline';
export { default as UploadOutline } from '@ant-design/icons/lib/outline/UploadOutline';
```

And I've set the absolute imports in ``:

```js
const path = require('path')

module.exports = {
  webpack: function(config, options) {
    config.resolve.alias['@ant-design/icons/lib/dist$'] = path.join(__dirname, 'src/client/icons.js')
    return config
  },
}
```js

Works for me, and I don't see the icons/dist in bundle analyzer. The bundle size is now reduced by 500k

**Comment by mssaisandeep** [comment] 2019-02-07 23:32
Hello,

From antd 3.5 version. when I try to install npm. I am observing "@antdesign" package in nodemodules. When I try to build (npm build which uses webpack) for production and analyze the build, I am getting 2MB for that @antdesign package. Is there anyone facing the same issue?

Note: I have used Babel-Import-Plugin and added the following thing as a configuration in webpack:

```
plugins: [
            ['import', { libraryName: "antd", libraryDirectory: "lib", style: "css" }],
          ],

```

I tried different syntaxes using Babel-Import-Plugin (BTW, latest version) but couldn't able to reduce the production build. 

Please help me in figuring it out.

**Comment by mssaisandeep** [comment] 2019-02-07 23:34
> Hello,
> 
> From antd 3.5 version. when I try to install npm. I am observing "@antdesign" package in nodemodules. When I try to build (npm build which uses webpack) for production and analyze the build, I am getting 2MB for that @antdesign package. Is there anyone facing the same issue?
> 
> Note: I have used Babel-Import-Plugin and added the following thing as a configuration in webpack:
> 
> ```
> plugins: [
>             ['import', { libraryName: "antd", libraryDirectory: "lib", style: "css" }],
>           ],
> ```
> I tried different syntaxes using Babel-Import-Plugin (BTW, latest version) but couldn't able to reduce the production build.
> 
> Please help me in figuring it out.

I am not even using any @antddesign icons. I am just using few antd components which are also showing as separate in bundle analyzer. **Please find the screenshot**

![image](https://user-images.githubusercontent.com/47436031/52449903-c6a79d00-2aed-11e9-82bc-e2d64c7ac8e7.png)

**Comment by mssaisandeep** [comment] 2019-02-08 19:28
> > Hello,
> > From antd 3.5 version. when I try to install npm. I am observing "@antdesign" package in nodemodules. When I try to build (npm build which uses webpack) for production and analyze the build, I am getting 2MB for that @antdesign package. Is there anyone facing the same issue?
> > Note: I have used Babel-Import-Plugin and added the following thing as a configuration in webpack:
> > ```
> > plugins: [
> >             ['import', { libraryName: "antd", libraryDirectory: "lib", style: "css" }],
> >           ],
> > ```
> > I tried different syntaxes using Babel-Import-Plugin (BTW, latest version) but couldn't able to reduce the production build.
> > Please help me in figuring it out.
> 
> I am not even using any @antddesign icons. I am just using few antd components which are also showing as separate in bundle analyzer. **Please find the screenshot**
> 
> ![image](https://user-images.githubusercontent.com/47436031/52449903-c6a79d00-2aed-11e9-82bc-e2d64c7ac8e7.png)

(Or) 
Is there any way that I can exclude @ant-design package from production build? I am using web pack to bundle. Please please help me.

**Comment by poorel** [comment] 2019-03-07 10:04
> > > 您好，
> > > 来自antd 3.5版本。当我尝试安装npm时。我正在观察nodemodules中的 “ @antdesign ”包。当我尝试构建（使用webpack的npm build）进行生产并分析构建时，我获得了2MB的@antdesign包。有没有人面临同样的问题？
> > > 注意：我使用了Babel-Import-Plugin并在webpack中添加了以下内容作为配置：
> > > ```
> > > plugins: [
> > >             ['import', { libraryName: "antd", libraryDirectory: "lib", style: "css" }],
> > >           ],
> > > ```
> > > 我使用Babel-Import-Plugin（BTW，最新版本）尝试了不同的语法，但无法减少生产构建。
> > > 请帮我搞清楚。
> > 
> > 
> > 我甚至没有使用任何@antddesign图标。我只是使用很少的antd组件，它们也在bundle分析器中显示为独立的。**请找截图**
> > ![图片](https://user-images.githubusercontent.com/47436031/52449903-c6a79d00-2aed-11e9-82bc-e2d64c7ac8e7.png)
> 
> （或）
> 有什么方法可以从生产版本中排除@ ant-design包吗？我正在使用网络包捆绑。请帮帮我。



> > > Hello,
> > > From antd 3.5 version. when I try to install npm. I am observing "@antdesign" package in nodemodules. When I try to build (npm build which uses webpack) for production and analyze the build, I am getting 2MB for that @antdesign package. Is there anyone facing the same issue?
> > > Note: I have used Babel-Import-Plugin and added the following thing as a configuration in webpack:
> > > ```
> > > plugins: [
> > >             ['import', { libraryName: "antd", libraryDirectory: "lib", style: "css" }],
> > >           ],
> > > ```
> > > I tried different syntaxes using Babel-Import-Plugin (BTW, latest version) but couldn't able to reduce the production build.
> > > Please help me in figuring it out.
> > 
> > 
> > I am not even using any @antddesign icons. I am just using few antd components which are also showing as separate in bundle analyzer. **Please find the screenshot**
> > ![image](https://user-images.githubusercontent.com/47436031/52449903-c6a79d00-2aed-11e9-82bc-e2d64c7ac8e7.png)
> 
> (Or)
> Is there any way that I can exclude @ant-design package from production build? I am using web pack to bundle. Please please help me.

me too.I have the same problem. ask for help.

**Comment by stephankaag** [comment] 2019-03-07 10:33
I noticed the same. Don't know what's wrong. Is anyone having a clue?

**Comment by stephankaag** [comment] 2019-03-07 12:56
See: https://github.com/ant-design/ant-design/issues/12011
Workaround until fixed: https://github.com/ant-design/ant-design/issues/12011#issuecomment-423173228

**Comment by blooddrunk** [comment] 2019-08-18 04:35
I'm using the config from `with-ant-design-less` example, but the client bundle size is too big even for a page with only a single `Button` in it, could this be an `ant-design` problem?

**Comment by mmiszy** [comment] 2019-10-18 10:00
I managed to reduce the bundle size by adding 2 lines to my next.config.js:

```
config.resolve.alias['@ant-design/icons/lib/dist$'] = path.join(__dirname, 'icons.js')
config.plugins.push(new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),)
```

**Comment by janlukasschroeder** [comment] 2019-11-05 03:53
I reduced my bundle size by 500KB by editing `config-override.js` like so:

**config-override.js**
```js
const { override, fixBabelImports } = require('customize-cra');
const path = require('path');

module.exports = override(
  fixBabelImports('import', {
    libraryName: 'antd',
    libraryDirectory: 'es',
    style: 'css'
  }),
  // used to minimise bundle size by 500KB
  function(config, env) {
    const alias = config.resolve.alias || {};
    alias['@ant-design/icons/lib/dist$'] = path.resolve(__dirname, './src/icons.js');
    config.resolve.alias = alias;
    return config;
  }
);
```

**./src/icons.js**

```js
/**
 * List all antd icons you want to use in your source code
 */
export {
  default as SearchOutline
} from '@ant-design/icons/lib/outline/SearchOutline';

export {
  default as CloseOutline
} from '@ant-design/icons/lib/outline/CloseOutline';

export {
  default as QuestionCircleOutline
} from '@ant-design/icons/lib/outline/QuestionCircleOutline';

export {
  default as PlayCircleOutline
} from '@ant-design/icons/lib/outline/PlayCircleOutline';

export {
  default as PauseCircleOutline
} from '@ant-design/icons/lib/outline/PauseCircleOutline';

export {
  default as LoadingOutline
} from '@ant-design/icons/lib/outline/LoadingOutline';
```

**Comment by timneutkens** [comment] 2019-11-05 05:45
@janlukasschroeder that looks like a config for cra which is different from Next.js.

**Comment by luisgserrano** [comment] 2019-12-10 16:12
@mmiszy How do you know which icons you need to import if you're using, e.g the pagination component from `antd`?

**Comment by mahimshridhar** [comment] 2020-01-03 14:31
> > > Hello,
> > > From antd 3.5 version. when I try to install npm. I am observing "@antdesign" package in nodemodules. When I try to build (npm build which uses webpack) for production and analyze the build, I am getting 2MB for that @antdesign package. Is there anyone facing the same issue?
> > > Note: I have used Babel-Import-Plugin and added the following thing as a configuration in webpack:
> > > ```
> > > plugins: [
> > >             ['import', { libraryName: "antd", libraryDirectory: "lib", style: "css" }],
> > >           ],
> > > ```
> > > 
> > > 
> > > I tried different syntaxes using Babel-Import-Plugin (BTW, latest version) but couldn't able to reduce the production build.
> > > Please help me in figuring it out.
> > 
> > 
> > I am not even using any @antddesign icons. I am just using few antd components which are also showing as separate in bundle analyzer. **Please find the screenshot**
> > ![image](https://user-images.githubusercontent.com/47436031/52449903-c6a79d00-2aed-11e9-82bc-e2d64c7ac8e7.png)
> 
> (Or)
> Is there any way that I can exclude @ant-design package from production build? I am using web pack to bundle. Please please help me.

I am facing the exact same problem, is there any way to solve this ?

**Comment by simjoeweb** [comment] 2020-01-05 22:51
If you want to remove unused momentjs locales:

```javascript
const MomentLocalesPlugin = require('moment-locales-webpack-plugin');

module.exports = {
  webpack: function(config, options) {
    config.plugins.push(new MomentLocalesPlugin())
    return config
  },
}
```

Check out: https://www.npmjs.com/package/moment-locales-webpack-plugin

**Comment by Timer** [comment] 2020-01-21 13:56
Duplicate of #9830

**Closed by Timer** 2020-01-21 13:56 UTC
Labels: Type: Example, good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-30 15:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
