### ISSUE TITLE
(node:45211) UnhandledPromiseRejectionWarning: Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead

### ISSUE THREAD

**Issue by konojunya** [zeit/next.js#5595] opened 2018-11-05 00:51 UTC
# Bug report

(node:45211) UnhandledPromiseRejectionWarning: Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead

## Describe the bug

Followed by the next document, I installed next and react, react-dom. Then I got the above error, so I searched, installed extract-text-webpack-plugin @ next and executed `yarn dev`.
However, I still get an error.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. yarn add next react react-dom
2. yarn add -D extract-text-webpack-plugin@next
3.  yarn dev

## Screenshots

![2018-11-05 9 49 25](https://user-images.githubusercontent.com/12035578/47972492-2867fd80-e0e0-11e8-9b82-97ad6ddcd94d.png)

## System information
 - OS: macOS（10.14）
 - Browser (if applies) chrome
 - Version of Next.js: 7.0.2

**Comment by konojunya** [comment] 2018-11-05 01:12
It may be healed, perhaps.
Because I was building a project I made before.
I'm sorry :(

**Comment by timneutkens** [comment] 2018-11-05 01:17
`extract-text-webpack-plugin` does not support webpack 4, there is nothing we can do about this in Next.js, so I'm going to close this issue.

**Closed by timneutkens** 2018-11-05 01:17 UTC

**Comment by lvxiaojie** [comment] 2019-10-31 05:03
I'm upgrading  **`_@zeit/next-less@0.3.0`** to **`_@zeit/next-less@1.0.1`** and this works for me.

**Comment by ThatGuySam** [comment] 2020-08-07 17:38
@lvxiaojie that was it for me too. 

I just ran `npm install @zeit/next-css@latest`

**Comment by balazsorban44** [comment] 2022-01-29 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
