### ISSUE TITLE
npm run build doesn't delete old files in .next folder

### ISSUE THREAD

**Issue by andrenaught** [zeit/next.js#8116] opened 2019-07-25 22:46 UTC
# Bug report

## Describe the bug

Whenever I do ```npm run build``` it doesn't remove the old files from previous builds inside the .next folder. This eventually causes the ```.next/server/static/``` folder to have a lot of folders of the old builds. Is this intended?
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. ```npm run build```
2. Open ```.next/server/static```
3. ```npm run build``` multiple times
4. New folders are generated (with the respective BUILD_ID), but the old folders for the previous builds aren't deleted.
5. ```npm run dev```
6. ```.next``` is rebuilt from the ground up, which deletes old builds
7. But if you never ```npm run dev```, the old build folders stay there. Which is usually the case for projects in production servers

## Expected behavior

Old build folders should be deleted right? (on development environments it's okay since ```npm run dev``` resets it, but on production environments these folders will start to pile up)

I just checked one of my servers and saw a bunch of these unnecessary folders. In this server i would ```git pull```, ```npm run build && pm2 restart [pm2 name]```. So it eventually accumulated a bunch of these

## Screenshots

All the previous builds are still in the folder, ```XB7kfZi8MyFj3pO7k5iSZ``` is the current build as seen in the ```BUILD_ID``` file

![Screen Shot 2019-07-25 at 3 22 58 PM](https://user-images.githubusercontent.com/12690211/61912865-1d643000-aef0-11e9-8282-392dee08d042.png)

## System information

- OS: macOS
- Version of Next.js: 9.0.0 (also tested on 8.0.3)

**Comment by timneutkens** [comment] 2019-07-26 11:27
Duplicate of #6009

**Closed by timneutkens** 2019-07-26 11:27 UTC

**Comment by balazsorban44** [comment] 2022-01-31 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
