### ISSUE TITLE
False positive report of "API resolved without sending a response"

### ISSUE THREAD

**Issue by gaku-sei** [zeit/next.js#10439] opened 2020-02-06 04:23 UTC
# Bug report

## Describe the bug

_Api endpoint_

Next will log the "API resolved without sending a response" warning even though the API endpoint always send a response back.

## To Reproduce

Here the code that triggers the warning:

```ts
export default async function(req: NextApiRequest, res: NextApiResponse) {
  switch (req.method) {
    case "POST":
    case "OPTION": {
      try {
        const request = http.request( // Node core http module
          url,
          {
            headers: await makeHeaders(req, res),
            method: req.method,
          },
          response => {
            response.pipe(res);
          },
        );

        request.write(JSON.stringify(req.body));

        return request.end();
      } catch (error) {
        Log.error(error); // Can be a simple console.error too
      }

      return res.status(500).end();
    }
  }

  return res.status(405).end();
}
```

It seems that this endpoint will always send a response back.

## Expected behavior

No warning

## System information

- OS: MacOS
- Version of Next.js: 9.2.1

**Comment by timneutkens** [comment] 2020-02-06 08:58
This has been fixed in canary, can you try `next@canary`?

**Comment by iddify** [comment] 2020-02-06 12:41
same issue here, i tried `next@canary` Next still logs "API resolved without sending a response"

**Comment by timneutkens** [comment] 2020-02-06 12:47
@iddify please provide code instead of saying "same issue", it's unlikely that you're doing exactly the same as the person that posts an issue.

**Comment by iddify** [comment] 2020-02-06 12:59
I'm simply trying to Integrate sendgrid to handle a form via this endpoint '/api/bulk-order'

- **bulk-order.js**

```
const sgMail = require('@sendgrid/mail');

sgMail.setApiKey(process.env.SENDGRID_APIKEY);

export default function handler(req, res) {
  ///const { name, email, phone, date, order_desc } = req.body;
  const msg = {
    to: 'myemail@gmail.com',
    from: 'test@example.com',
    subject: 'Sending with Twilio SendGrid is Fun',
    text: 'and easy to do anywhere, even with Node.js',
    html: '<strong>and easy to do anywhere, even with Node.js</strong>'
  };
  sgMail.send(msg);
}
```


- **Form.js**

```
const sendEmail = (url, emailData) => {
  fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(emailData)
  });
};
const handleSubmitForm = () => {
    sendEmail('/api/bulk-order', emailBody);
};
```

when i submit nothing really happens other the the console logs "API resolved without sending a response for /api/bulk-order, this may result in a stalled requests."

**Comment by iddify** [comment] 2020-02-06 13:37
**UPDATE**:  i wasn't resolving the request, returning a 200 status code after the request finished removed the warning for me, **MY BAD!**

**Comment by gaku-sei** [comment] 2020-02-07 03:00
@timneutkens Thank you for the quick reply. Unfortunately `9.2.2-canary.12` doesn't solve the issue 😞 

I don't know exactly how Next analyzes whether or not a route actually returns something, but it could because of the callback in `http.request` or the `try/catch` ?

I also wonder if this couldn't be because of the `http.request` function that could "silently" fail and just not do anything 🤔 

I will investigate a bit more 👍

**Comment by ijjk** [comment] 2020-02-07 03:12
@gaku-sei it is most likely caused by the `callback` as we can't detect you are still doing work in the API unless you return a promise an wait to resolve it until after the callback is fired e.g.

```js
export default async function(req: NextApiRequest, res: NextApiResponse) {
  return new Promise(resolve => {
    switch (req.method) {
      case "POST":
      case "OPTION": {
        try {
          const request = http.request( // Node core http module
            url,
            {
              headers: await makeHeaders(req, res),
              method: req.method,
            },
            response => {
              response.pipe(res);
              resolve()
            },
          );

          request.write(JSON.stringify(req.body));
          request.end();
        } catch (error) {
          Log.error(error); // Can be a simple console.error too
          res.status(500).end();
          return resolve()
        }
      }
    }
    res.status(405).end();
    return resolve()
  })
}
```

**Comment by gaku-sei** [comment] 2020-02-07 05:25
@ijjk Thank you very much, that worked perfectly for me!

Issue solved 😄

**Closed** 2020-02-07 05:25 UTC

**Comment by danielhusar** [comment] 2020-02-11 06:30
I see the same warning with `apollo-server-express`.

**Comment by mattcarlotta** [comment] 2020-03-28 21:35
I had a "fun" time figuring this out when dealing with multiple callbacks, and while I'm not a fan of the solution, for anyone else who may stumble upon this warning...

When dealing with multiple callbacks functions, **the warning is only suppressed if the parent function returns a Promise** and passes its `resolve` function down the callback tree. However, you can always ignore the warning in development provided that any callbacks always return a response.

That said, this seems like a rather hacky approach and should be handled more efficiently by the ZEIT team. 

---

A brief summary of the example below...

1). Parent function
```javascript
next => (req, res) => { 
  return new Promise(resolve => { 
    return next(req, res, resolve); 
  }); 
}
```
2). Child callback
```javascript
next => (req, res, resolve) => {
  return next(req, res, resolve);
}
```
3). Handler callback
```javascript
(req, res, resolve) => {
  res.status(200).send("Hello");
  return resolve();
}
```

---

For example... if your API route flows through 2 middleware functions, `withMiddleware` and `requireAuth`, before it hits the `handler`:
```javascript
export default withMiddleware(requireAuth(handler));
```
Then, the parent function will need to `return New Promise` and pass down its `resolve` to the `next(req, res, resolve)` child callback:

**middlewares.js** (parent function):
```javascript
import morgan from "morgan";
import session from "cookie-session";
import passport from "passport";

const { NODE_ENV } = process.env;
const inProd = NODE_ENV === "production";

/**
 * Applies middleware to request/response objects
 *
 * @function
 * @param {function} next - callback function
 * @param {object} req - request object
 * @param {object} res - response object
 * @returns {function}
 */
export default next => (req, res) => {
  return new Promise(async resolve => {
    try {
      const middlewares = [
        session({
          path: "/",
          keys: ["cookieKey"],
          name: "app",
          sameSite: inProd,
          maxAge: 2592000000, 
          httpOnly: true,
          secure: inProd,
        }),
        morgan("tiny"),
        passport.initialize(),
      ];

      const promises = middlewares.reduce((acc, middleware) => {
        const promise = new Promise((resolve, reject) => {
          middleware(req, res, result =>
            result instanceof Error ? reject(result) : resolve(result),
          );
        });
        return [...acc, promise];
      }, []);

      await Promise.all(promises);

      return next(req, res, resolve);
    } catch (error) {
      res.status(400).send(err)
      return resolve();
    }
  });
}
```

From the next callback, you'll have to pass down `resolve` to the `handler` callback):

**requireAuth.js** (child callback)
```javascript
import get from "lodash.get";
import User from "../path/to/mongoose/models/User";

const badCredentials = "There was a problem with your login credentials. Please make sure your username and password are correct.";

/**
 * Middleware function to check if a user is logged into a session.
 *
 * @function
 * @param {function} next - callback function
 * @param {object} req - request object
 * @param {object} res - response object
 * @param {function} resolve - Promise resolve function
 * @returns {function}
 */
export default next => async (req, res, resolve) => {
  try {
    const _id = get(req, ["session", "user", "id"];
    if (!_id) throw String(badCredentials);

    const existingUser = await User.findOne({ _id  });
    if (!existingUser || existingUser.status === "suspended")
      throw String(badCredentials);

    req.user = {
      id: existingUser._id,
      email: existingUser.email,
      firstName: existingUser.firstName,
      lastName: existingUser.lastName,
      role: existingUser.role,
    };

    return next(req, res, resolve);
  } catch (error) {
    res.status(403).send(error);
    return resolve();
  }
};
```

Then from within the `handler` callback, it should `return resolve();` the parent's `Promise`:

**api/examplePage.js**
```javascript
import withMiddleware from "../path/to/middlewares"
import requireAuth from "../path/to/requireAuth";

/**
 * Allows a user to log in to the application on refresh.
 *
 * @function handler
 * @param {object} req - request object
 * @param {object} res - response object
 * @param {function} resolve - Promise resolve function
 * @returns {function} resolve
 */
const handler  = (req, res, resolve) => {
  res.status(200).send(req.user);
  return resolve();
}

export default withMiddleware(requireAuth(handler));
```

**Comment by eric-burel** [comment] 2020-04-16 15:06
@danielhusar Any idea what could be the valid solution for apollo-server-express? Hitting the same issue "API resolved without sending a response for /, this may result in stalled requests.". 
`/` is not even called in my app, my endpoint is `/api/graphql`.

**Comment by danielhusar** [comment] 2020-04-16 16:06
I havent been able to figure it out yet. Im considering to switch to express server to handle all requests. (Instead of just api)

**Comment by timneutkens** [comment] 2020-04-17 07:40
We're going to add a config option to opt-out of the warning for certain api routes if you're sure they resolve

**Comment by davidwieler** [comment] 2020-05-12 23:35
Not sure if this helps anyone, but using async/await in tandem with handler worked for me:

```
handler.get(async (req, res) => {
	let user = await findUserByEmail({
		email: req.user.email
	});

	await res.status(200).json({
		user
	});
});
```

**Comment by MuddyBootsCode** [comment] 2020-05-22 21:39
I'm still running into this: 
```
export default async function token(req, res) {
  try {
    const { user } = await auth0.getSession(req);

    if (user) {
      return new Promise((resolve, reject) => {
        fetch(`https://${process.env.domain}/oauth/token`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            grant_type: 'client_credentials',
            client_id: process.env.authClientID,
            client_secret: process.env.authClientSecret,
            audience: `https://${process.env.domain}/api/v2/`,
          }),
        })
        .then((res) => res.json())
        .then(({ access_token, scope, expires_in, token_type }) => {
          token = { access_token, scope, expires_in, token_type };
          console.log(token)
          resolve(token);
        })
        .catch(err => {
          reject(err);
        })
      })
    }
    else {
      throw new Error('No User');
    }
  } catch (error) {
    console.error(error)
    res.status(error.status || 500).end(error.message)
  }
}
```

**Comment by timneutkens** [comment] 2020-05-23 09:24
```js
export default async function token(req, res) {
  try {
    const { user } = await auth0.getSession(req);

    if(!user) {
      throw new Error('No User');
    }

    const result = await fetch(`https://${process.env.domain}/oauth/token`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        grant_type: 'client_credentials',
        client_id: process.env.authClientID,
        client_secret: process.env.authClientSecret,
        audience: `https://${process.env.domain}/api/v2/`,
      }),
    })
    const { access_token, scope, expires_in, token_type } = await result.json()


    return { access_token, scope, expires_in, token_type }
  } catch (error) {
    console.error(error)
    return res.status(error.status || 500).end(error.message)
  }
}
```

This should solve your case, but you can now disable the warning also: https://nextjs.org/docs/api-routes/api-middlewares

```js
// export this from the api route
export const config = {
  api: {
    externalResolver: true,
  },
}
```

**Comment by tettoffensive** [comment] 2020-05-29 18:57
I'm not sure I understand. I'm getting it with this code which I got from the example for firebase server authentication:

**pages/api/login.ts**:
```ts
import commonMiddleware from '../../middleware/commonMiddeware';
import { verifyIdToken } from '../../firebase/auth/admin';

const handler = async (req, res) => {
  if (!req.body) {
    return res.status(400);
  }

  const { token } = req.body;

  try {
    const decodedToken = await verifyIdToken(token);
    req.session.decodedToken = decodedToken;
    req.session.token = token;
    return res.status(200).json({ status: true, decodedToken });
  } catch (error) {
    return res.status(500).json({ error });
  }
};

export default commonMiddleware(handler);
```

**Comment by timneutkens** [comment] 2020-05-30 16:43
Looks like you're not finishing the request when a body is not set:
```
  if (!req.body) {
    return res.status(400);
  }
```

Should be:
```
  if (!req.body) {
    return res.status(400).send({});
  }
```

**Comment by Manubi** [comment] 2020-08-02 17:44
> Looks like you're not finishing the request when a body is not set:
> 
> ```
>   if (!req.body) {
>     return res.status(400);
>   }
> ```
> 
> Should be:
> 
> ```
>   if (!req.body) {
>     return res.status(400).send({});
>   }
> ```

Have the same problem and the above fix isn't working for me. :/

**Comment by BetaPlays3** [comment] 2020-08-05 21:24
I have the same problem. The message just a warning or can it really give you problems?

**Comment by miguel9554** [comment] 2020-08-09 18:43
I'm having the same problem. Why is this issue closed? Is this a problem from Next server or am I doing something wrong?

**Comment by b1narylife** [comment] 2020-08-30 19:14
I am getting this same warning too however I am getting the data I expect to revieve in the console :/

**Comment by parabuzzle** [comment] 2020-10-21 04:39
Updated to `next@canary` and I'm still seeing this error. 

here's my handler: 

```
const trades = mongoMiddleware(async (req, res, connection, models) => {
  const {
    method
  } = req

  apiHandler(res, method, {
    GET: (response) => {
      models.Trade.find({}, (error, trade) => {
        if (error) {
          connection.close();
          response.status(500).json({ error });
        } else {
          response.status(200).json(trade);
          connection.close();
        }
      })
    }
  });
})
```

When I hit my route I get a json array returned with all the trades.. but I get this in the console:

`API resolved without sending a response for /api/trades, this may result in stalled requests.`

**Comment by rene-demonsters** [comment] 2020-11-17 18:13
People still running into this issue might want to look closely at: https://github.com/vercel/next.js/issues/10439#issuecomment-633013628 and https://github.com/vercel/next.js/pull/11380

If you're using an externalResolver (such as Express), nextjs can't detect that the API response has been send. At the bottom of https://github.com/vercel/next.js/issues/10439#issuecomment-633013628 @timneutkens explains how you can disable the warning if that is indeed the case.

**Comment by eric-burel** [comment] 2020-11-20 15:48
I don't think it explains why I would get the warning for `API resolved without sending a response for /, this may result in stalled requests.` even if I don't query it

**Comment by rista404** [comment] 2020-11-22 15:01
I had the same issue with the following code:

```ts
export default async (req: NextApiRequest, res: NextApiResponse) => {
	if (req.method === 'POST') {
		handlePost(req, res)
		return
	}

	if (req.method === 'GET') {
	       handleGet(req, res)
	       return
	}

	res.status(405).send('Method not allowed')
}
```

What solved it for me was `await`ing both handlers, like so: `await handlePost(req, res)`.

**Comment by pheianox** [comment] 2021-04-19 21:09
The problem was that (req, res) => ... neeeds to return some default  response. 

E.g. `return res.status(200).json({ msg: "Works"});`

**Comment by imamabdulazis** [comment] 2021-05-28 07:12
> @gaku-sei it is most likely caused by the `callback` as we can't detect you are still doing work in the API unless you return a promise and wait to resolve it until after the callback is fired e.g.
> 
> ```js
> export default async function(req: NextApiRequest, res: NextApiResponse) {
>   return new Promise(resolve => {
>     switch (req.method) {
>       case "POST":
>       case "OPTION": {
>         try {
>           const request = http.request( // Node core http module
>             url,
>             {
>               headers: await makeHeaders(req, res),
>               method: req.method,
>             },
>             response => {
>               response.pipe(res);
>               resolve()
>             },
>           );
> 
>           request.write(JSON.stringify(req.body));
>           request.end();
>         } catch (error) {
>           Log.error(error); // Can be a simple console.error too
>           res.status(500).end();
>           return resolve()
>         }
>       }
>     }
>     res.status(405).end();
>     return resolve()
>   })
> }
> ```

Awesome, work perfectly sir😃.

**Comment by balazsorban44** [comment] 2022-01-28 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
