### ISSUE TITLE
AMP Pages doesn't work with Material UI

### ISSUE THREAD

**Issue by amit090shukla** [zeit/next.js#7487] opened 2019-06-03 11:07 UTC
# Feature request
The AMP pages support introduced with Next.js 8.1 doesn't work if you have server injected styles from Material UI or styled component.
![92974d4e-fbcf-4f95-bd8c-54cd65308745-Screenshot%20from%202019-05-27%2015-27-48](https://user-images.githubusercontent.com/11248457/58797346-6cdb5d80-861d-11e9-9c4c-178248441e22.png)

I am assuming that the amp page requires only one style tag to be present. Currently I am using both Material UI and Styled-components and injecting them both.

![Screenshot from 2019-06-03 16-37-01](https://user-images.githubusercontent.com/11248457/58797542-e4a98800-861d-11e9-9bd7-0ecf2053a54c.png)
 
Is there any way to make it work? I couldn't find any example in the repo.

**Comment by ijjk** [comment] 2019-06-04 04:19
Hi, this should be updated in the latest canary of Next.js `next@canary`. I'm going to close this. If you are still having trouble after trying the latest canary feel free to reply with further info.

**Closed by ijjk** 2019-06-04 04:19 UTC

**Comment by jessicar135** [comment] 2019-06-12 14:05
Still facing issue. Please share sample / github reference

**Comment by Danhiler** [comment] 2020-01-04 13:54
@ijjk I'm having the same issue, Does anyone know how to fix this?

**Comment by balazsorban44** [comment] 2022-01-30 17:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
