### ISSUE TITLE
styling third parties

### ISSUE THREAD

**Issue by ducanh2110** [zeit/next.js#9915] opened 2020-01-03 03:50 UTC
# Bug report
Styling third parties using styled-jsx
## Describe the bug
Hi, I am using nextjs + nextcss + 3rd party UI library. I try to styling third parties scoped. I've followed the instruction https://github.com/zeit/styled-jsx#styling-third-parties--child-components-from-the-parent. But I can't style anything from 3rd parties library. Anyone have the solution for me. Thanks so much

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2]

**Comment by Timer** [comment] 2020-01-03 05:33
Closing as issue template was not followed. [Questions belong on our Spectrum](https://spectrum.chat/next-js).

**Closed by Timer** 2020-01-03 05:33 UTC

**Comment by balazsorban44** [comment] 2022-01-30 17:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
