### ISSUE TITLE
Link's Next.js doesn't work when use css

### ISSUE THREAD

**Issue by akylkb** [zeit/next.js#9392] opened 2019-11-13 00:57 UTC
# Example
```javascript
<Link href="/posts/[id]" as="/posts/article123">
    <a>Go to post</a>
</Link>
```
Source: https://github.com/akylkb/bug-nextjs-css0
Live: https://bug-nextjs-css0.akylkb.now.sh/

## Describe the bug
Everything works in developer mode
Doesn't work in production

## dependencies

@zeit/next-css: 1.0.1
next: 9.1.3
react: 16.11.0
react-dom: 16.11.0

**Comment by ijjk** [comment] 2019-11-13 02:39
Hi, this is a duplicate of https://github.com/zeit/next-plugins/issues/282. We are looking into this fixing this and opened a RFC [here](https://github.com/zeit/next.js/issues/8626). If you are using global CSS only you can test out the experimental support by adding `module.exports = { experimental: { css: true } }` to your `next.config.js`

**Closed by ijjk** 2019-11-13 02:39 UTC

**Comment by balazsorban44** [comment] 2022-01-30 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
