### ISSUE TITLE
next/head has a memory leak issue

### ISSUE THREAD

**Issue by KrishnaVamsiKV** [zeit/next.js#6955] opened 2019-04-08 12:39 UTC
We observed a huge spike in memory when we deployed our next app a few days back. We figured out that problem is being caused by using next/head on the server. When we stopped rendering next/head on the server by adding a conditional check, the problem was solved. 

But this should have already been handled. Later I checked the code of head.tsx and suspected that maybe rewind is not being called when it has to be. And when I tried to call that manually in _app.tsx every time, that also stopped the memory leak. Any explanation why I had to manually call this every time ? Shouldn't that already be handled ?

Here is the code that caused the memory leak

```javascript
import App, { Container } from 'next/app';
import React from 'react';
import { getMetaTagsFromUrl } from '../util';
import Head from 'next/head';

export default class MyApp extends App {
  static async getInitialProps({ Component, ctx }) {
    let pageProps = {};

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx);
    }

    const metaTags = pageProps.metaTags || getMetaTagsFromUrl(ctx.asPath);

    return { pageProps, metaTags };
  }

  constructor(props) {
    super(props);
  }

  render() {
    const { Component, pageProps, metaTags } = this.props;
    return (
      <Container>
        <Head>
          <title>{metaTags.title}</title>
        </Head>
        <Component {...pageProps} />
      </Container>
    )
  }
}
```

NextJs Version: 7.0.2

**Comment by whistlerbrk** [comment] 2019-04-08 13:21
see https://github.com/zeit/next.js/issues/6914

**Comment by atis--** [comment] 2019-04-09 10:09
Also see this: #5525 

And this: https://github.com/staylor/react-helmet-async

**Comment by Timer** [comment] 2019-06-14 15:34
Closing as dupe of https://github.com/zeit/next.js/issues/6914

**Closed by Timer** 2019-06-14 15:34 UTC
