### ISSUE TITLE
Memory leak in app created from specific boilerplate

### ISSUE THREAD

**Issue by dongrh214** [zeit/next.js#10394] opened 2020-02-03 07:40 UTC
# Bug report
We have some problem on our server. After some time of execution we have an out of memory error on our server.
So I tried to reproduce on my computer. I create a clean project just use  [nextjs-kit](https://github.com/wsdo/nextjs-kit) . and build it.run it using pm2,  after one hour  to see if the memory increase.
Here is the memory evolution :

![07d60abe-5cc5-4a01-b312-6b2a8b7c868c](https://user-images.githubusercontent.com/18432911/73632495-d3c28200-4696-11ea-927e-061e035c208e.png)

### pm2 monit show like this:
![pm2----a825bca0-13fe-4665-9618-45a5a1b1cc4e](https://user-images.githubusercontent.com/18432911/73632511-df15ad80-4696-11ea-927f-88495394b3a3.png)
![pm2----cad82bf9-ec8c-49b7-8843-73fc6dd7f215](https://user-images.githubusercontent.com/18432911/73632520-e341cb00-4696-11ea-9835-1acc36a43797.png)

## Describe the bug
you can see the heap size awaly increasing when i use loadtest request

## To Reproduce

1.  git clone https://github.com/wsdo/nextjs-kit
2.  cd nextjs-kit 
3.  npm i
4.  add pm2.config.js file
   ```
     const pkg = require("./package.json");

     module.exports = {
        apps: [
          {
             name: pkg.name,
             script: "server.js",
             instances: 1,
             exec_mode: "cluster",
             watch: false,
             node_args: "--inspect --expose-gc",
             max_memory_restart: "1500M",
             env: {
                   NODE_ENV: "development",
                   BUILD_ENV: "test",
                   RUNTIME_ENV: "test",
            },
            env_test: {
                   NODE_ENV: "production",
                   BUILD_ENV: "test",
                   RUNTIME_ENV: "test",
           },
        },
         ],
      };
   ```
5.   npm run build
6.   pm2 start pm2.config.js 
7.   loadtest -c 30 --rps 20 http://localhost:3600/demo
8.  you can use pm2 monit or chrome://inspect  See error
9.  I also use express test, it is ok!

## stem information

- OS: macOS
- Version of pm2: 4.2.1
- Version of Next.js: 9.1.1 or lastest
- Version of loadtest:  4.1.0

## Additional context
use pm2 log see node inspect port 
![ad03283b-19e2-4928-a34c-e942a22162e3](https://user-images.githubusercontent.com/18432911/73633800-8b0cc800-469a-11ea-9fcd-b6eb4d8cdfa9.png)
![8b6e20b7-6b9a-469d-bc9b-ccca6019f14e](https://user-images.githubusercontent.com/18432911/73634114-636a2f80-469b-11ea-90e3-621bcc5715b9.png)

**Comment by dongrh214** [comment] 2020-02-07 07:54
https://github.com/iaincollins/nextjs-starter has same problem

**Comment by Timer** [comment] 2020-04-15 05:33
Fixed in Next.js 9.3.5. Thanks!

**Closed by Timer** 2020-04-15 05:33 UTC

**Comment by dongrh214** [comment] 2020-04-27 06:25
> Fixed in Next.js 9.3.5. Thanks!
 
the version 9.3.5 performace nice!
but i fork next.js from 8.4.1 and add-on functions 'development，can you tell me where the memory leaks? or the exact fixed tag?

**Comment by balazsorban44** [comment] 2022-01-30 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
