### ISSUE TITLE
Clean URLs with Dynamic Routing is not working 

### ISSUE THREAD

**Issue by samarth-keskar-au1** [zeit/next.js#8377] opened 2019-08-15 04:29 UTC
The example from the Clean URLs with Dynamic Routing learning module on Next.js portal is not working as it should.
![Screenshot from 2019-08-15 09-50-31](https://user-images.githubusercontent.com/47717252/63072784-44d47880-bf43-11e9-841d-4b4e342c7bf6.png)

![Screenshot from 2019-08-15 10-00-54](https://user-images.githubusercontent.com/47717252/63072865-a0066b00-bf43-11e9-968a-fcf2abb53fd0.png)

**Comment by samir-araujo** [comment] 2019-08-15 12:06
Seems like you're a missing the `p` folder inside `pages`.
Try to create this file: `pages/p/[id].js` with this content:
```
import { useRouter } from 'next/router';
import Layout from '../../components/MyLayout';

export default function Post() {
  const router = useRouter();

  return (
    <Layout>
      <h1>{router.query.id}</h1>
      <p>This is the blog post content.</p>
    </Layout>
  );
}
```

It probably should work after this.

Please refer to https://nextjs.org/learn/basics/clean-urls-with-dynamic-routing/dynamic-routing for more information

**Comment by Timer** [comment] 2019-08-15 13:14
Closing as tutorial was not followed, per above comment.

**Closed by Timer** 2019-08-15 13:14 UTC

**Comment by samarth-keskar-au1** [comment] 2019-08-15 16:22
Thanks

**Comment by balazsorban44** [comment] 2022-01-31 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
