### ISSUE TITLE
Organization of release notes

### ISSUE THREAD

**Issue by miloofcroton** [zeit/next.js#9600] opened 2019-12-02 22:03 UTC
# Feature request

It'd be nice if we could scan release notes quickly to see if it's something that could affect a library upgrade on our end. Several of items on any given release note are related solely to documentation or examples. Could those be separated in the future? One section for library upgrades, one section for docs/examples is all I ask.

That's all. Love your work, guys.

**Comment by timneutkens** [comment] 2019-12-03 09:00
Release notes are automated through github.com/zeit/release so it'd involve a *lot* of manual work. In general I try to separate examples when doing minor / major releases though, but that is entirely manual.

**Comment by miloofcroton** [comment] 2019-12-03 09:18
That makes sense. I totally understand if the juice is not worth the squeeze, but I thought I'd make the desire known.

**Comment by kachkaev** [comment] 2019-12-03 11:04
@timneutkens would it be possible to look at labels in linked PRs and use them for grouping?

**Comment by timneutkens** [comment] 2019-12-03 11:51
Would take significant engineering effort to implement that in release, so I can’t justify my team working on it over other things we’re building.

**Comment by timneutkens** [comment] 2020-01-03 01:24
Closing this based on my earlier messages.

**Closed by timneutkens** 2020-01-03 01:24 UTC

**Comment by jkjustjoshing** [comment] 2020-05-04 17:25
Just would like to throw in a vote for this - it's very hard right now to figure out the difference between 9.3.6, 9.3.5, 9.3.4, etc, and what including each version means for my environment.

**Comment by balazsorban44** [comment] 2022-01-30 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
