### ISSUE TITLE
typescript can't resolve @types/next

### ISSUE THREAD

**Issue by droganov** [zeit/next.js#8551] opened 2019-08-29 09:31 UTC
Hi, I had working setup, which got corrupt with recent next update.

Now I'm using
"@types/next": "^8.0.6",
"next": "^9.0.5",

And
`import { AppProps, AppComponentType, DefaultAppIProps, NextAppContext } from 'next/app';``

Results in
`Module '"../node_modules/next/app"' has no exported member 'AppComponentType,'.`

My ts config is
```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "inlineSourceMap": false,
    "inlineSources": false,
    "jsx": "preserve",
    "lib": ["dom", "es2017"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noLib": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "preserveConstEnums": true,
    "removeComments": true,
    "skipLibCheck": true,
    "sourceMap": false,
    "strict": true,
    "target": "esnext"
  },
  "exclude": ["node_modules", ".next", "**/*.spec.ts"]
}

```

How do I fix types resolution in order @types/next to be used again?

**Comment by timneutkens** [comment] 2019-08-29 10:50
Closing as per the issue template:

# Question about Next.js

GitHub Issues are reserved for Bug reports and Feature requests. The best place to get your question answered is to post it on https://spectrum.chat/next-js.

---

You can find the upgrading guide here: https://github.com/zeit/next.js/blob/canary/UPGRADING.md#zeitnext-typescript-is-no-longer-necessary

**Closed by timneutkens** 2019-08-29 10:50 UTC

**Comment by balazsorban44** [comment] 2022-01-31 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
