### ISSUE TITLE
Dependencies specified in _app are duplicated in other pages.

### ISSUE THREAD

**Issue by akotlar** [zeit/next.js#5923] opened 2018-12-19 18:39 UTC
# Bug report

## Describe the bug

Dependencies not properly shared across pages and _app.js

## To Reproduce

Create a number of pages. Add a module to _app.js.
Increase the number of times a module is included from once to N times, track progress

Takes at least 2 pages for a dep included in _app.js to be factored out.

## Expected behavior
Once a module has been included in _app, it should never be packed again.

## Screenshots

In a 4 page + _app + _document app

// _app only  (_app.js includes Auth)
<img width="555" alt="screen shot 2018-12-19 at 1 29 25 pm" src="https://user-images.githubusercontent.com/5543229/50240340-86039100-0392-11e9-880f-3852dc46ccda.png">

// 1 page (_app.js + submit.js  include Auth)
<img width="571" alt="screen shot 2018-12-19 at 1 30 22 pm" src="https://user-images.githubusercontent.com/5543229/50240341-86039100-0392-11e9-8333-0961ac723210.png">

// 2 pages (_app.js + submit.js + scorecard.js include Auth)
<img width="565" alt="screen shot 2018-12-19 at 1 31 00 pm" src="https://user-images.githubusercontent.com/5543229/50240334-7edc8300-0392-11e9-8045-6b643f9fc66f.png">

## System information
 - OS: Mac OS X
 - Version of Next.js: canary, 7.0.2

## Additional context
Related to: #3818 (though in this case import isn't being exported as in HOC)
Related to: #118 and #253

Potential solutions: expose or document modifying the threshold for placing a dependency in the common bundle. 

However, it seems there should be a more intelligent procedure, in which unnecessary data is not bundled for any descendants of _app.js.

**Comment by akotlar** [comment] 2018-12-19 20:35
Fixed by

```js
if (!options.isServer) {
  config.optimization.splitChunks.cacheGroups.commons.minChunks = 2;
}
```

This is a simple fix, effectively just needs documentation of default of 3. This may be somewhat confusing, as Webpack's default is 1, and "shared" implies 2.

**Comment by jamessimone** [comment] 2018-12-29 16:46
@akotlar that snippet seems out of date when investigating the cacheGroups object returned by  [the most recent version of webpack](https://webpack.js.org/plugins/split-chunks-plugin/) bundled with Next:

After console.logging(config.optimizations.splitChunks.cacheGroups) on startup (with zeit/next-css generating the "styles" prop):  

```javascript
{ cacheGroups:
   { default: false,
     vendors: false,
     styles:
      { name: 'styles',
        test: /\.+(css)$/,
        chunks: 'all',
        enforce: true }
 } 
}
```

Looking at the [documentation for the SplitChunksPlugin](https://webpack.js.org/plugins/split-chunks-plugin/#split-chunks-example-1) it seems you can set up the commons object as you are suggesting; I am wondering if that or either of these lines would do the trick on newer versions:

```javascript
if (!isServer) {  
    const chunkingDefaults = { minChunks: 2, reuseExistingChunk: true };
    config.optimization.splitChunks.cacheGroups.default = chunkingDefaults;
    config.optimization.splitChunks.minChunks = 2;  
}
```

**Comment by chirag04** [comment] 2019-03-22 05:52
I can confirm this is happening with our app bundles too.

**Comment by timneutkens** [comment] 2019-03-22 11:28
@dav-is is working on fixing this.

**Comment by sheerun** [comment] 2019-04-17 13:31
Cheering for fixing this as well.. Our app is 2x more heavy than necessary because of this bug

**Comment by sheerun** [comment] 2019-04-17 15:19
Currently I have best results when using following:

```
    if (!isServer) {
      config.optimization.splitChunks.cacheGroups = {
        default: false,
        vendor: {
          name: 'vendor',
          test: /[\\/]node_modules[\\/]/,
          enforce: true,
          priority: 20
        },
        common: {
          name: 'common',
          minChunks: 2,
          priority: 10
        }
      }
    }
```

This forces all dependencies from node_modules to vendor chunk (nice, because yarn.lock ensures this chunk won't change very often), then it forces all non-vendor application code to commons chunk (nice because pages are loading faster when browsing on client side).

The only issue I have currently is that _app.js is separate chunk while I'd like it to be a part of commons chunk...  Also runtime chunk that I'd like also to be a part of commons chunk. Any help appreciated..

**Comment by isBatak** [comment] 2019-10-28 16:42
Any updates regarding this issue?

**Comment by timneutkens** [comment] 2019-10-28 20:34
This should be fixed in https://github.com/zeit/next.js/pull/7696

```
module.exports = {
  experimental: {
    granularChunks: true
  }
}
```

**Comment by timneutkens** [comment] 2019-11-09 21:35
Closing this as it should be solved by #7696

**Closed by timneutkens** 2019-11-09 21:35 UTC
Labels: Feature: Compilation, Type: Bug, priority: high

**Comment by switz** [comment] 2020-09-03 08:20
I'm still seeing an overlapping `@apollo/client` in `_app.js`, even with `granularChunks` enabled:

<img width="1124" alt="double apollo" src="https://user-images.githubusercontent.com/990166/92087837-0605a080-ed9a-11ea-9d9f-7b43379405e6.png">

And if I manually split the chunks, it still overlaps a decent amount of code (should be ~30kb gzipped total, but is more like 50kb gzipped combined):

```
        const regexWithApollo = /(?<!node_modules.*)[\\/]node_modules[\\/](react|react-dom|scheduler|prop-types|use-subscription|@apollo\/client)[\\/]/;

        config.optimization.splitChunks.cacheGroups.framework.test = regexWithApollo;
```

<img width="815" alt="image" src="https://user-images.githubusercontent.com/990166/92089587-5c73de80-ed9c-11ea-80fa-f3f25b9f2c65.png">

Any ideas?

**Comment by jaydenseric** [comment] 2020-09-03 09:51
@switz it might not be what is causing your specific issue, but note that `@apollo/client` publishes code duplicated in separate ESM (faux ESM, not Node.js compatible) and CJS files:

https://unpkg.com/browse/@apollo/client@3.1.4/

Depending how multiple modules require or import from the various files, you could end up encountering the [dual package hazard](https://nodejs.org/api/esm.html#esm_dual_package_hazard).

**Comment by balazsorban44** [comment] 2022-01-29 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
