### ISSUE TITLE
Add example demonstrating serverless

### ISSUE THREAD

**Issue by kamleshchandnani** [zeit/next.js#6684] opened 2019-03-17 11:58 UTC
# Example request

## Example name
example with serverless

## Describe the bug
Add an example demonstrating nextjs with serverless

#### Why?
The main goal is to get all the following pieces work together
1. Use `serverless`
2. Use `serverless-offline` to get it work for emulating locally  - (`development`)
3. Use `express` to handle all the routes and middlewares
3. Use `aws-serverless-express`
4. Deploy it on AWS lambda - (`production`)

**Comment by timneutkens** [comment] 2019-03-17 12:18
I guess https://github.com/danielcondemarin/serverless-nextjs-plugin covers what you're trying to do 🤔

**Comment by kamleshchandnani** [comment] 2019-03-17 12:19
Give me 5 minutes. I'm sending a PR 😄

**Comment by kamleshchandnani** [comment] 2019-03-17 12:30
@timneutkens It's here 😉 #6685

**Comment by falconmick** [comment] 2019-04-03 16:24
I thought that it would be a good exercise to roll my own solution, so I have done so. My solution is a basic wrapper around the .next build folder that uses [require.context](https://webpack.js.org/guides/dependency-management/#requirecontext) that webpack makes possible to scan the .next build directory and discover all of the pages + setup express routes for them.

Now that I understand how it all works using webpack and express as ways to shortcut the solution I will be re-writing it using pure node + serverless-http. If it all works out without any major hitches I will re-upload the code as an example codebase so that people have the option of a lightweight rapper around nextjs's serverless option without having to become dependent on yet another plugin that might loose steam. That being said, holly crap there is allot of activity there currently (good sign!)

**Comment by timneutkens** [comment] 2020-01-02 20:36
Closing this as we recommend using `next dev`. Deployment is easiest when using ZEIT Now. https://nextjs.org/docs/deployment

**Closed by timneutkens** 2020-01-02 20:36 UTC
Labels: Type: Example, good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-30 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
