### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'call' of undefined when clicking Link

### ISSUE THREAD

**Issue by MoritzR** [zeit/next.js#5636] opened 2018-11-08 14:43 UTC
# Bug report

## Describe the bug

When running next.js in dev mode and clicking on a link, the error `Unhandled Rejection (TypeError): Cannot read property 'call' of undefined` until the linked page has been refreshed at least once. It seems to be related to using sass, css and typescript exports.

## To Reproduce

Follow the readme in this repository: https://github.com/leanovate/nextjs-hmr-bug

## Expected behavior
When clicking the link, the linked page appears and no error is thrown.

## Screenshots
![hmr-bug](https://user-images.githubusercontent.com/4339283/48205373-6bd69c00-e36c-11e8-9544-dfe4a5b41f94.gif)

![hmr-bug](https://user-images.githubusercontent.com/4339283/48205496-a2141b80-e36c-11e8-9adf-81b6a3adeb20.png)

## System information
 - OS: macOs
 - Browser: Chrome version 70.0.3538.77
 - Version of Next.js: 7.0.2

**Comment by timneutkens** [comment] 2018-11-08 15:03
Duplicate of https://github.com/zeit/next-plugins/issues/282

**Closed by timneutkens** 2018-11-08 15:03 UTC

**Comment by MoritzR** [comment] 2018-11-14 12:52
@timneutkens I am not sure that [zeit/next-plugins#282](https://github.com/zeit/next-plugins/issues/282) is related to the same problem.
I tried the suggested solution but it didn't have an effect: https://github.com/leanovate/nextjs-hmr-bug/tree/no-fix-update-to-canary-plugins-plus-app-fix

It seems to be related to sass/css though. Should I re-create this ticket in [zeit/next-plugins](https://github.com/zeit/next-plugins)?

**Comment by Jero786** [comment] 2018-11-20 10:12
@MoritzR How are you?? could you find some workaround to fix that? Seems like in FF works, but in no in Chrome, do you see it?

**Comment by MoritzR** [comment] 2018-11-20 15:47
> @MoritzR How are you?? could you find some workaround to fix that? Seems like in FF works, but in no in Chrome, do you see it?

@Jero786 You can have a look at a workaround here: https://github.com/leanovate/nextjs-hmr-bug/pull/3
I need some more time to understand everything related to the problem but maybe you can get some more insights from the workaround.

**Comment by Jero786** [comment] 2018-11-26 08:15
> @MoritzR Solve the ESLint warning and the problem is solved.
> 
> E.g: Modify `.eslintrc` file
> 
> ```js
> {
>   ....
>   "rules": {
>     ...
>     "no-console": 1
>   }
> }
> ```

@MoritzR Seems like it's working after I put that rule!!! thanks a lot! after almost a month I could work again with Chrome!! thank you very very much!!!!

**Comment by icflorescu** [comment] 2018-12-30 18:42
None of the fixes I've tried so far worked for me, so I've come up with this one: https://github.com/zeit/next-plugins/issues/282#issuecomment-450578740

**Comment by calvinvoo2** [comment] 2019-02-24 09:08
I am not sure if this works for other cases, but it works for mine
Change from
`import Link from "next/link";`
to
`import { default as NextLink } from "next/link";`
