### ISSUE TITLE
__dirname in getStaticProps is not reflective of where file actually is

### ISSUE THREAD

**Issue by SivanMehta** [zeit/next.js#10943] opened 2020-03-10 18:42 UTC
# Bug report

When attempting to reference the local file system, I often use `__dirname` to ensure that I can use relative path names. However while using `getStaticProps`, `__dirname` is not resolving correctly.

## Describe the bug

I expected `__dirname` to be the absolute path of the file in which `getStaticProps` is being executed, but instead it is incorrectly resolving as `/`.

## To Reproduce

I am using this component in the `pages` directory under the name `faq.js`:

```js
import React from 'react';

export default function FAQ ({ faq }) {
  return (
    <pre >
      { faq }
    </pre>
  )
}

export async function getStaticProps() {
  const read = require('util').promisify(require('fs').readFile);
  const path = require('path');

  console.log(__dirname);

  const faq = await read(path.join(__dirname, 'faq.md'), 'utf8');
  return { faq };
};
```

## Expected behavior

I expect `__dirname` to be the relative path name of `faq.js`, but it instead is output as `/` in the console during `next build`. This is causing the file `faq.md` to not be read properly because it is not on the correct path.

## System information

- OS: MacOS
- Version of Next.js: `9.3.0`

**Comment by Timer** [comment] 2020-03-10 20:12
This is a known issue per #8251. 

In the meantime, something like this should work:
```js
  const pagesDirectory = path.resolve(process.cwd(), 'pages');
```

**Comment by timneutkens** [comment] 2020-03-11 11:29
Closing as duplicate of https://github.com/zeit/next.js/issues/8251

**Closed by timneutkens** 2020-03-11 11:29 UTC

**Comment by SivanMehta** [comment] 2020-03-11 16:13
Thanks for your help!

**Comment by balazsorban44** [comment] 2022-01-30 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
