### ISSUE TITLE
with-react-intl example: use react-intl-translations-manager instead of custom script

### ISSUE THREAD

**Issue by nwshane** [zeit/next.js#1990] opened 2017-05-17 08:37 UTC
First off, thanks for the with-react-intl example! It was very helpful for me in setting up localization in my app.

Currently, the example uses a custom script to generate a JSON of the default messages at `lang/en.json`. The README explains that you can send this file to your translator for translation. 

The react-intl-translations-manager library already does something very similar: it generates JSON files of the default messages for the languages that you specify. It's a bit nicer, though, because it's easily configurable, outputs useful command line messages, and most importantly will insert missing messages into the lang/locale.json files.

Maybe it would be better to replace the default-lang script with react-intl-translations-manager? If so, I'll submit a pull request with this change.

**Comment by nwshane** [comment] 2017-05-17 08:40
@ericf What do you think about this idea?

**Comment by timneutkens** [comment] 2017-07-02 10:32
@ericf @coluccini could you have a look 👌

**Comment by coluccini** [comment] 2017-07-02 12:01
I have never used react-intl-translations-manager 😞 , but if no one else can do it I could give it a try

**Comment by thundermiracle** [comment] 2017-07-18 01:01
I switched from sample's script to react-intl-translations-manager and then to my custom script because I want to detect not only  duplicated ids, but also duplicated messages as well. 
If react-intl-translations-manager could check duplicated messages, it will be more interesting.

**Comment by nwshane** [comment] 2017-07-18 17:44
@thundermiracle Maybe open an issue proposing that feature in the react-intl-translations-manager repo?

**Comment by timneutkens** [comment] 2019-11-09 23:19
Considering this issue has been open for 2 years and there hasn't been a reply I'm going to close it.

**Closed by timneutkens** 2019-11-09 23:19 UTC
Labels: Type: Enhancement, Type: Example, good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-30 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
