### ISSUE TITLE
_next/webpack-hmr request 404

### ISSUE THREAD

**Issue by hh54188** [zeit/next.js#5110] opened 2018-09-06 01:58 UTC
This issue's demo repo is [https://github.com/hh54188/happy-server/tree/issue-demo](https://github.com/hh54188/happy-server/tree/issue-demo)

I try to integrate Next.js with Hapi.js as a plugin. Here is my next.js plugin project folder main structure:

```
--plugins
   |--app
        |--pages
            |--app
                |--a.js
        |--handlers
        |--public
             |--dist
        |--index.js
        |--next.config.js
```

And here is `index.js` main content, most for route register

```javascript
const nextRenderService = next({
  dir: path.join(__dirname)
});

module.exports = {
  name: "AppService",
  version: "0.0.1",
  register: async function(server, options) {
    await nextRenderService.prepare();

    server.route({
      method: "GET",
      path: `/app/${assetPrefix}/_next/webpack-hmr`,
      handler: nextHandlerWrapper(nextRenderService)
    });

    server.route({
      method: "GET",
      path: "/app/{param*}",
      handler: defaultHandler(nextRenderService)
    });

    server.route({
      method: "GET",
      path: `/app/${assetPrefix}/_next/on-demand-entries-ping`,
      handler: nextHandlerWrapper(nextRenderService)
    });

    server.route({
      method: "GET",
      path: `/app/${assetPrefix}/_next/-/page/{param*}`,
      handler: {
        directory: {
          path: path.join(__dirname, pagesPath),
          listing: true
        }
      }
    });

    server.route({
      method: "GET",
      path: `/app/${assetPrefix}/_next/{param*}`,
      handler: {
        directory: {
          path: path.join(__dirname, distPath),
          listing: true
        }
      }
    });
  }
};
```
However, when I run the server, and visit [http://127.0.0.1:4000/app/a](http://127.0.0.1:4000/app/a), the page could render success, and most script file could load successful. But the `_next/webpack-hmr`  and the `_next/on-demand-entries-ping` requests status is `404`. And I notice the `404` status is from Next.js, not Hapi.js 

So what's wrong with my code ? How can I solve this problem ?

**Comment by timneutkens** [comment] 2018-09-06 07:48
Going to close this as you're not following the issue template.

**Closed by timneutkens** 2018-09-06 07:48 UTC

**Comment by NathanielHill** [comment] 2019-02-11 20:22
@timneutkens I noticed there have been a lot of changes to HMR recently with Next 8. I'm running into a similar issue with HMR not respecting `assetPrefix`. Can you tell me if this behavior has changed to recently?

**Comment by hameltomor** [comment] 2019-05-16 11:31
@NathanielHill Hey!

The same problem. I have two projects like monorepo. The each project runs in docker. I use `(custom express server + typescript + next-routes-pages)`. I use `assetPrefix` for both of project. In docker I use `nginx` to manage routes. I have the same problem with HMR, I see bad requests in terminal for `webpack-hmr` and `on-demand-ping?`.

Maybe now you know how to solve this shit?

**Comment by NathanielHill** [comment] 2019-05-29 00:29
@hameltomor Never resolved this, as I moved to a single Next.js app for other reasons.

**Comment by balazsorban44** [comment] 2022-01-31 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
