### ISSUE TITLE
[Learn] Tutorial not working in style section

### ISSUE THREAD

**Issue by A13k2** [zeit/next.js#7520] opened 2019-06-06 12:08 UTC
# Bug report

## Describe the bug

In the section [Styling Components](https://nextjs.org/learn/basics/styling-components) there seems to be sth wrong.  In the preivous section I replaced the index.js and post.js for fetching data via api for the tv shows. When it comes to the styling components section, the tutorial switches back to the old My Blog thing, but the post.js file is never changed.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [FEtching data tutorial](https://nextjs.org/learn/basics/fetching-data-for-pages)
2. Do as expected until next section
3. You will get an error at [this](https://nextjs.org/learn/basics/styling-components/styles-and-nested-components) step

## Expected Behavior
...

## System information

- OS: macOs
- Firefox
- Version of Next.js: 8.1.0

**Comment by KumarAbhirup** [comment] 2019-06-09 14:50
Hey, it works on my end. Can you please let us know what error you get at [this](https://nextjs.org/learn/basics/styling-components/styles-and-nested-components) step?

**Comment by jamzi** [comment] 2019-06-12 14:43
As @A13k2 said, **post.js** file under pages for step 7 (7-styling-components) still has code from previous step about fetching data. When you click on a link on index page (for example Hello Next.js), it will try to fetch the show with id hello-nextjs).

Not completely sure, but I think post.js should have code from previous step (5-clean-urls-ssr)

**Comment by lfades** [comment] 2019-07-29 22:19
This issue should be fixed already thanks to [next-learn-demo#14](https://github.com/zeit/next-learn-demo/pull/14)

**Closed by lfades** 2019-07-29 22:19 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
