### ISSUE TITLE
next/link : <Link> does not work in production

### ISSUE THREAD

**Issue by ayradc** [zeit/next.js#9980] opened 2020-01-07 17:10 UTC
# <Link> does not work in production

I'm having an issue with next link, on my development environment the component work really well, i have included the code for the component bellow, my main issue is when i deploy to production (im using zeit now) the link does not work and anything happens when the button is clicked, **no consol errors**

## Component 
` import Link from 'next/link';
import { ShopingCartNavIcon } from '../../lib/icons';
const CheckoutButton = () => {
  return (
    <Link href='/cart'>
      <button class='nav--cart--btn' title='Shopping Cart'>
        <span>Shopping Cart</span>
        <ShopingCartNavIcon />
      </button>
    </Link>
  );
};
export default CheckoutButton;`

## Expected behavior

To redirect the user to the Cart page.

## System information

- OS: Windows 10
- Browser chrome
- Version of Next.js: 9.1.4

**Comment by ijjk** [comment] 2020-01-07 17:29
Hi, this sounds like a duplicate of https://github.com/zeit/next-plugins/issues/282. We are looking into fixing this and opened a RFC [here](https://github.com/zeit/next.js/issues/8626). If you are using global CSS only you can test out the experimental support by adding `module.exports = { experimental: { css: true } }` to your `next.config.js`

I'm gonna close this since it appears to be a duplicate

**Closed by ijjk** 2020-01-07 17:29 UTC

**Comment by amiguet3** [comment] 2021-09-12 16:04
Use passHref prop in Link

**Comment by balazsorban44** [comment] 2022-01-27 20:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
