### ISSUE TITLE
using Preact with v9 not working

### ISSUE THREAD

**Issue by NikoMontana** [zeit/next.js#8083] opened 2019-07-24 09:13 UTC
# Examples bug report

## Example Name

[using-preact](https://github.com/zeit/next.js/tree/canary/examples/using-preact)

## Describe the bug

`npm run dev` produces following error

```The version of React you are using is lower than the minimum required version needed for Next.js. Please upgrade "react" and "react-dom": "npm install --save react react-dom" https://err.sh/zeit/next.js/invalid-react-version```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `npx create-next-app --example using-preact using-preact-app`
2. `npm run dev`
3.  Error as described
 
## Expected behavior

Replace react with preact.

## Screenshots

No screenshots available - only error message

## System information

- OS: macOSX 10.14
- Browser: Chrome
- Version of Next.js: 9.0.1

## Additional context

No additional context

**Comment by timneutkens** [comment] 2019-07-24 10:54
This is the third issue that does not follow the issue template. https://github.com/zeit/next.js/issues?utf8=%E2%9C%93&q=is:both+is:issue+author:NikoMontana

**Comment by NikoMontana** [comment] 2019-07-24 13:15
@timneutkens I apologize, I have mainly used the `question template` therefor I did not fill out any template. I will use the bug template in future.

**Comment by NikoMontana** [comment] 2019-07-24 18:22
I have updated the Issue

**Comment by Timer** [comment] 2019-12-23 15:47
Closing as updated to Preact X

**Closed by Timer** 2019-12-23 15:47 UTC

**Comment by balazsorban44** [comment] 2022-01-30 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
