### ISSUE TITLE
Query param missing when using router.push but appears when page is rendered on server.

### ISSUE THREAD

**Issue by hgezim** [zeit/next.js#9574] opened 2019-11-29 22:22 UTC
# Bug report

## Describe the bug

I'm doing a `router.push` using url, as,  and passing query object in options parameter.

When the page is rendered from the server side, the query string is processed fine. However, when using `router.push`, query seems to be ignored.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository: https://github.com/hgezim/nextjs-scrolll-custom-route-bug

1. Clone https://github.com/hgezim/nextjs-scrolll-custom-route-bug/
2. Checkout `query_param` branch
2. Run `npm run dev`
3. Navigate to `http://localhost:4000/recipes/diet-halal?cuisine=greek`
4. Notice in the dev console that the query is set to `query L7: Object { cuisine: "greek", filter: "diet-halal" }`.
5. Click the button labeled 95 on the page.
6. Notice that `cuisine` isn't picked up here and it only shows `filter` parameter as part of query in dev console: `query L7: Object { filter: "diet-halal" }`

## Expected behavior

I expect the log statement to look the same when I press button `95`, namely: `query L7: Object { cuisine: "greek", filter: "diet-halal" }`

## System information

- OS: macOS
- Browser (if applies) Firefox 70.0.1
- Version of Next.js: 9.1.4

**Comment by jamesmosier** [comment] 2019-12-01 03:29
This relates to #9473 I believe which is to add additional documentation around this usage.

For your example though, you'll want to provide the query string to the `href` value as well:

```js
router.push("/recipes/[filter]?cuisine=greek", "/recipes/foo?cuisine=greek", {
  query: { cuisine: "greek" }
});
```

**Comment by hgezim** [comment] 2019-12-01 04:50
Any plans to rework the URL/dynamic route APIs? They're really not user-friendly.

What's the point of specifying the query object in the options if I have to specify it everywhere else?

**Comment by timneutkens** [comment] 2019-12-01 09:38
The third parameter actually doesn't exist. It's just:

```
router.push("/recipes/[filter]?cuisine=greek", "/recipes/foo?cuisine=greek")
```

However I think in this case it could just be:

```
router.push("/recipes/[filter]", "/recipes/foo?cuisine=greek"
```

cc @timer @ijjk

**Comment by cybervaldez** [comment] 2020-01-16 20:16
I agree it does get really awkward, using the example above with the following code

```
const router = useRouter();
    // this works (pressing back and forward in history to test)
    useEffect(() => {
        console.log(router.query.cuisine); // greek
    }, [router.query.cuisine])

   // this doesn't
    useEffect(() => {
        router.events.on('routeChangeComplete', (url)=>{
           console.log(url, router.query.cuisine); // undefined
        })
    })
```

**Comment by Timer** [comment] 2020-02-03 19:29
Closing as duplicate of https://github.com/zeit/next.js/issues/9473

**Closed by Timer** 2020-02-03 19:29 UTC

**Comment by somratAtSekaiLab** [comment] 2020-07-24 19:06
> **This will work for single or multiple query params as well dynamic routing:** 

`const query = {
      param1: 'foo', param2: 'bar'
    }`

`const url = { pathname: '/search/[id]', query };`

`const urlAs = { pathname: '/search/1234', query }`

`router.push(url, urlAs);`

> Output: 

**`/search/1234?param1=foo&param2=bar`**

**Comment by oktaykose** [comment] 2020-12-02 09:01
const basePath = Router.asPath.split('?')[0] || Router.asPath
     
        const query =  Router.query
        query.lang = lang || locale

        Object.keys(query).map(function(k) {
          if(Router.pathname.includes(`[${k}]`)){
              delete query[k]
          }
        })

        const url = { pathname: Router.pathname, query }
        const urlAs = { pathname: basePath, query }
        
        Router.push(url, urlAs)

**Comment by balazsorban44** [comment] 2022-01-29 02:12
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
