### ISSUE TITLE
Persistent sidebar [Question]

### ISSUE THREAD

**Issue by rashidul0405** [zeit/next.js#3891] opened 2018-02-26 06:22 UTC
We need a sidebar which is a category tree of an e-commerce site, fetched from DB(pls check this example - [ffshop : left menu](https://www.ffshop.no/abonnement-c-84.html) - building the next version of it).

This should only load once - at very first time (server rendered) like [react router example](https://reacttraining.com/react-router/web/example/sidebar)

How can I fetch this initially - using HOC? I use [layout component](https://github.com/zeit/next.js/tree/canary/examples/layout-component) and also checked [HOC](https://github.com/zeit/next.js/tree/canary/examples/with-higher-order-component)

I think this may be related to #3461, #3552.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

next.js match in every aspect of our need but looks like it falls a bit short in this use case. Building another site which also requires rendering dynamic menu from DB. I would like to contribute.

**Comment by timneutkens** [comment] 2018-02-26 09:00
Duplicate of https://github.com/zeit/next.js/issues/88

**Closed by timneutkens** 2018-02-26 09:00 UTC

**Comment by rashidul0405** [comment] 2018-02-28 05:23
@timneutkens is there any other way we can achieve this for now, maybe using _document.js while we wait for #88?

**Comment by rashidul0405** [comment] 2018-03-05 09:39
Thank you @postor. For this project, I skipped Redux in favor of unstated (just for global user data etc.). I did this using HOC. just like with-intl example, on server I fetch the data from API and on client read the data from __NEXT_PROPS__. So fetch once and reused on every page.
