### ISSUE TITLE
App with http2-server returns 404 if public/files have been queried

### ISSUE THREAD

**Issue by bunnywrote** [zeit/next.js#9789] opened 2019-12-19 19:00 UTC
# Bug report

## Describe the bug

nextjs-app with **http2-server** returns '404' when the files in the "public" folder will be queried.

In server.js  all requests are processed as follows:
```
server.on('request', (req, res) => {
    return app.render(req, res, req.url, req.query)
})
```

## To Reproduce

1. Clone [example-repo](https://github.com/bunnywrote/nextjs-with-http2)
2. Follow Readme.md to set up and lauch
3. After the application launched navigate in a browser to https://localhost:3000/robots.txt

## Expected behavior

The application should return requested files from "public" directory (in this case robots.txt) instead of returning an 404-error.

## System information

- OS: Windows 10
- Browser Chrome, Firefox
- Version of Next.js: 9.1.4

## Additional context

Similar question on spectrum.chat

https://spectrum.chat/next-js/general/clarification-on-public-directory~67b410b6-81ff-442b-8238-3a6f72891384?m=MTU3NDE4NjIzMjc4Mw==

**Comment by ijjk** [comment] 2019-12-19 19:42
Hi, you should use `getRequestHandler`, `render` is meant for rendering specific pages.

```
const app = next({ dev })
const handleRequest = app.getRequestHandler()

app.prepare().then(() => {
  server.on('error', err => console.error(err))

  server.on('request', (req, res) => {
    return handleRequest(req, res)
  })

  server.listen(port)

  console.log(`Listening on HTTPS port ${port}`)
})
```

I'm going to close this since it doesn't appear to be an issue with Next.js and is documented under [Custom server and routing](https://github.com/zeit/next.js#custom-server-and-routing)

**Closed by ijjk** 2019-12-19 19:42 UTC

**Comment by balazsorban44** [comment] 2022-01-30 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
