### ISSUE TITLE
Webpack picks wrong entry file when do server side rendering.

### ISSUE THREAD

**Issue by videni** [zeit/next.js#9892] opened 2019-12-31 07:13 UTC
when do server sider rendering, webpack try to import files from` antd/es` directory, it supposed to be `antd/lib`.

I  explicitly specified the dir to import antd files for `babel-import-plugin` as following.

```
{
    "presets": [
        "next/babel"
    ],
    "plugins": [
        [
            "import",
            {
                "libraryName": "antd",
                "style": true,
                "libraryDirectory": "lib"
            }
        ]
    ]
}

```
the `rc-pagination` package has following fields defined, why webpack pick the "module" field  rather the `main` field ?

rc-pagination/pakage.json
```
 "main": "lib/index",
  "module": "es/index",
```

_next/development/server/static/development/pages/auto/brand.js
```
/* harmony import */ var _locale_default__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../locale/default */ "./node_modules/antd/es/locale/default.js");
```

```
SyntaxError: Unexpected token export
(anonymous function)
/Users/vidy/www/acme-admin-ui1/node_modules/rc-pagination/es/locale/en_US.js:1
Module._compile
internal/modules/cjs/loader.js:718:23
Module._extensions..js
internal/modules/cjs/loader.js:785:10
require.extensions.<computed> [as .js]
/Users/vidy/www/acme-admin-ui1/node_modules/ts-node/src/index.ts:529:44
Module.load
internal/modules/cjs/loader.js:641:32
Function.Module._load
internal/modules/cjs/loader.js:556:12
Module.require
internal/modules/cjs/loader.js:681:19
require
internal/modules/cjs/helpers.js:16:16
rc-pagination/es/locale/en_US
webpack:/external "rc-pagination/es/locale/en_US":1
> 1 | module.exports = require("rc-pagination/es/locale/en_US");
View compiled
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
View compiled
Module../node_modules/antd/es/locale/default.js
./node_modules/antd/es/locale/default.js:1
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
View compiled
Module../node_modules/antd/es/modal/locale.js
/_next/development/server/static/development/pages/auto/brand.js:20177:73
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
View compiled
Module../node_modules/antd/es/locale-provider/index.js
/_next/development/server/static/development/pages/auto/brand.js:19894:72
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
View compiled
Module../node_modules/antd/es/config-provider/index.js
/_next/development/server/static/development/pages/auto/brand.js:11327:74
```

**Comment by timneutkens** [comment] 2019-12-31 10:35
Closing as the issue template was ignored. Follow the issue template when creating issues.

**Closed by timneutkens** 2019-12-31 10:35 UTC

**Comment by balazsorban44** [comment] 2022-01-30 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
