### ISSUE TITLE
Support assetPrefix for Link component ?

### ISSUE THREAD

**Issue by revskill10** [zeit/next.js#5899] opened 2018-12-16 22:01 UTC
# Feature request

Support `assetPrefix` with `next/link` component.

## Describe the solution you'd like

Provide `assetPrefix` props for `next/link` component.

## Additional context
This feature is needed in case we have multiple NextJS apps on the same domain with different `assetPrefix` .

**Comment by timneutkens** [comment] 2018-12-31 13:54
Duplicate of #4998

**Closed by timneutkens** 2018-12-31 13:54 UTC

**Comment by revskill10** [comment] 2019-01-27 11:21
#4998 doesn't solve my issue.
In my case, each `assetPrefix` is a full CDN domain , like `https://cdn-1.cdn.com/project1` . It has no knowledge about the domain of NextJS application is being served.

**Comment by timneutkens** [comment] 2019-01-30 16:00
@revskill10 I'm sure you mean the same problem / feature though. If not please write up a more detailed issue about what you're trying to solve, because it sounds like you want the exact same solution, being able to link to a specific subpath.
