### ISSUE TITLE
Problem with firebase-hosting example

### ISSUE THREAD

**Issue by julianbenegas** [zeit/next.js#8897] opened 2019-09-28 17:50 UTC
I started from [this](https://github.com/zeit/next.js/tree/canary/examples/with-firebase-hosting) example. Changed nothing more than what is explained in there to get up and running.

npm run dev works perfectly.
npm run serve (firebase local) throws me the following:

Error: > Couldn't find a `pages` directory. Please create one under the project root
    at Object.findPagesDir (/Users/julianbenegas/Documents/Work/mayeutica-platform-2.nosync/dist/functions/node_modules/next/dist/lib/find-pages-dir.js:3:170)
    at new Server (/Users/julianbenegas/Documents/Work/mayeutica-platform-2.nosync/dist/functions/node_modules/next/dist/next-server/server/next-server.js:40:42)
    at createServer (/Users/julianbenegas/Documents/Work/mayeutica-platform-2.nosync/dist/functions/node_modules/next/dist/server/next.js:2:133)
    at Object.<anonymous> (/Users/julianbenegas/Documents/Work/mayeutica-platform-2.nosync/dist/functions/index.js:10:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
⚠  Your function was killed because it raised an unhandled error.

Cheers!
@jthegedus

**Comment by matchatype** [comment] 2019-09-28 19:35
Duplicate #8893

**Comment by timneutkens** [comment] 2019-09-29 10:18
Will close this in favor of #8893

**Closed by timneutkens** 2019-09-29 10:18 UTC

**Comment by balazsorban44** [comment] 2022-01-31 03:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
