### ISSUE TITLE
Invalid token @import when using a package that depends a lib with less files

### ISSUE THREAD

**Issue by pradyuman** [zeit/next.js#9663] opened 2019-12-08 16:05 UTC
# Bug report

## Describe the bug

My import dependency tree looks like this:
```
- main app
  - components library
    - antd
```

The components library is built with `next/babel`. When running a production build, I get the following error:
<img width="584" alt="Screen Shot 2019-12-08 at 8 00 22 AM" src="https://user-images.githubusercontent.com/9904569/70392087-d2275700-1990-11ea-89d8-55c3da46a1f7.png">

I used this as a reference to build my next config: https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less 

Everything works fine until I include the components repo (I can use antd in the main app without a problem). Any idea how to work around this issue?

I imagine directly including the components library in the next config would work, but I'm not sure how exactly to do this with the next/babel preset.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less 
2. Include any library that has a dependency on antd
3. Run next build

## Expected behavior

The build works.

**Comment by timneutkens** [comment] 2019-12-08 17:13
Duplicate of #9661 

Same reply, closing in favor of #8626

**Closed by timneutkens** 2019-12-08 17:13 UTC

**Comment by balazsorban44** [comment] 2022-01-30 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
