### ISSUE TITLE
Error with dynamic import if import the same component on different pages

### ISSUE THREAD

**Issue by DimaBur** [zeit/next.js#9622] opened 2019-12-04 12:06 UTC
# Bug report

## Describe the bug

Importing component with `dynamic` on one page and with es6 `import` on other page breaks build and causes error: `TypeError: __webpack_require__.e is not a function`

## To Reproduce

1. Import the same component on one page using 
```const Component = dynamic(() => import("Components/Component"));```
and on other page using
```import Component from 'Components/Component'```

2. Try to build `yarn build`
3. Build fails with error `TypeError: __webpack_require__.e is not a function`

## System information

- Version of Next.js: 9.1.1
- Version of Yarn: 1.12.1

**Comment by timneutkens** [comment] 2019-12-04 15:30
Please provide a full reproduction in a github repo.

**Comment by DimaBur** [comment] 2019-12-05 09:50
Sorry, I can't, it's private. I described it as detailed as I can.

**Comment by kachkaev** [comment] 2019-12-05 12:06
@DimaBur it will help if you create a new Next.js project with a minimum number components, which would still produce an error you experience. This will give Next.js maintainers a testing ground to inspect and fix the problem for your team 😉

**Comment by jamesmosier** [comment] 2019-12-07 21:59
I was not able to recreate this in [codesandbox](https://codesandbox.io/s/nextjs-issue-9622-p0672). Was there another step that I missed? I was able to run `yarn dev` and `yarn build` successfully

**Comment by timneutkens** [comment] 2019-12-08 11:28
I'm going to close this issue as it's unfortunately not reproducible. Which means that there's nothing actionable we can do right now.

**Closed by timneutkens** 2019-12-08 11:28 UTC
Labels: Can't Reproduce

**Comment by balazsorban44** [comment] 2022-01-30 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
