### ISSUE TITLE
Exception during hydration phase is not handled correctly

### ISSUE THREAD

**Issue by Mikhail-Fiadosenka** [zeit/next.js#5113] opened 2018-09-06 14:38 UTC
# Bug report

## Describe the bug

If an unhandled exception occurs in `render()` method during hydration phase, the error handling logic of nextjs doesn't unmount/clear the markup received from a server. It's for production build, not dev mode.

More details:
Say you have page with a React component that throws an unhandled exception on client-side only. It's rendered correctly on server-side. After browser has loaded HTML&JS, hydration phase begins. The component throws an exception in `render()`; nextjs catches it and renders default error page, but the markup originated from server is not cleared. As a result user is faced with inconsistent page state: SSR'ed page without JS attached and default error page below it.

## To Reproduce

Full source code to reproduce the bug: https://github.com/Mikhail-Fiadosenka/nextjs-rehydration-exception

## Expected behavior
Default error page. Markup from server should be removed.

## Screenshots
Actual result is on the screenshot below.
<img height="400" alt="actual result" src="https://user-images.githubusercontent.com/1673511/45164139-7fde1000-b1fa-11e8-8d88-9c380f304b68.png">

## System information
 - next@6.1.1
 - next@7.0.0-canary.13 is subject to this bug too
 - react@16.4.2

## Additional context
I've debugged nextjs sources and found out that `ReactDOM.hydrate` is invoked twice 
 in `client/index.js@renderReactElement()`. My conclusion is that hydration process is aborted by exception, the flag `isInitialRender` is not set to `false` and the markup/React tree is not unmounted before error page is rendered.

**Comment by timneutkens** [comment] 2018-09-07 10:47
I wonder if fixing this is as simple as doing:

```
try {
  ReactDOM.hydrate(reactEl, domEl)
} finally {
  isInitialRender = false
}
```

`finally` makes sure it's always executed regardless of an error being thrown

I'd have to debug this more to be certain though.

**Comment by Mikhail-Fiadosenka** [comment] 2018-09-07 11:00
Hm, I've just tried this - it still hydrates twice, because it doesn't exit from first `hydrate` call, but goes deeper.
Log statements:
```
renderReactElement
Error: fake client-side error
renderReactElement
renderReactElement finally block
renderReactElement finally block
```

```js
console.log('renderReactElement');
try {
    _reactDom.default.hydrate(reactEl, domEl);
} catch (e) {
    console.log('exception during hydration', e);
} finally {
    console.log('renderReactElement finally block');
    isInitialRender = false;
}
```

**Comment by timneutkens** [comment] 2019-08-10 12:45
I'm going to close this issue as it's been open for almost a year and no other community members ran into the same issue, it seems like an edge case at this point.

**Closed by timneutkens** 2019-08-10 12:45 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
