### ISSUE TITLE
Overriding Node's ProcessEnv typing causes TypeScript errors in third-party libs

### ISSUE THREAD

**Issue by kachkaev** [zeit/next.js#8379] opened 2019-08-15 12:44 UTC
# Bug report

## Describe the bug

https://github.com/zeit/next.js/blob/cffa2e3f2165b58b77fb354d3f74a4ac8222b68f/packages/next/types/global.d.ts#L1-L12

↑
This file overrides the [original implementation](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/10b6a9d288a936fe95836e4919ac103338aaf5b2/types/node/globals.d.ts#L736-L738) of the `ProcessEnv` typing, which causes negative side effects in third-party libraries that rely on it. In my case this was `execa`.

## To Reproduce

1.  Create a Next.js app, ensure `tsconfig.json` and `next-env.d.ts` have been autogenerated.

1.  Install `execa` and `ts-node`. 
    ```
    yarn add execa ts-node
    ```

1.  In `test.ts` write something like:

    ```ts
    import execa from "execa";
    
    execa("printenv", [], {
        env: {
          HELLO: "world",
          NODE_ENV: "development",
        },
        extendEnv: false,
        stdout: "inherit",
      });
    ```
1.  Observe no typing issues and ensure that the command works by running:
    ```
    yarn ts-node --transpile-only  --compiler-options="{\"module\": \"commonjs\"}" test.ts
    ```

    Output:
    ```
    HELLO=world
    NODE_ENV=development
    ✨  Done in 0.42s.
    ```

1.   Comment out `NODE_ENV: "development",` in `test.ts`, which is a totally valid action.

1.  Observe the following TypeScript error in the editor:

    ```
    Argument of type '{ env: { HELLO: string; }; extendEnv: false; stdout: "inherit"; }' is not assignable to parameter of type 'Options<null>'.
      Types of property 'env' are incompatible.
        Property 'NODE_ENV' is missing in type '{ HELLO: string; }' but required in type 'ProcessEnv'.ts(2345)
    global.d.ts(10, 14): 'NODE_ENV' is declared here.
    ```

## Expected behavior

I would not expect Next.js to pollute Node's `ProcessEnv` interface, thus not causing typing false-positives in third-party libraries like `execa`. I'm using `execa` in a project that includes a few data-processing commands in addition to the Next.js app itself.

## System information

- Version of Next.js: 9.0.3

## Additional context

`git blame` points to https://github.com/zeit/next.js/pull/7648

**Comment by Timer** [comment] 2019-08-15 13:18
This seems like a edge case to me, as this is the first time this issue has cropped up.

It seems odd to me that `execa` depends directly on `NodeJS.ProcessEnv` rather than a self-made object or a Partial variant.

Could we see if `execa` would be interested in making the type `Partial<NodeJS.ProcessEnv>`?

**Comment by kachkaev** [comment] 2019-08-15 13:24
> Could we see if execa would be interested in making the type `Partial<NodeJS.ProcessEnv>`?

I'm not sure they would want to do so because outside Next.js it's just.

```ts
interface ProcessEnv {
  [key: string]: string | undefined;
}
```

There is nothing to take `Partial` from really.

Instead, could Next.js make `NODE_ENV` optional? Alternatively, you can create and use your own `ProcessEnvWithNodeEnv` interface, in which this attribute is included. This is even better, because it does not constrain the value of `NODE_ENV` in `execa` and alike. Overriding global typings is somewhat similar to polluting prototypes in old JS – you never know when and how you'll be bitten 🙈

**Comment by jeremy-coleman** [comment] 2019-08-25 01:24
"It seems odd to me that an npm package uses a proper type, when we restrict it to 3 strings". keep on keeping on

**Comment by Timer** [comment] 2019-08-25 01:54
I'm closing this because there's been no 👍s, and the DX improvement across the board is way more valuable than allowing the types to work with `execa`.

If you must fix this "error", you can extend the `execa` types in your project to account for it.

**Closed by Timer** 2019-08-25 01:54 UTC

**Comment by balazsorban44** [comment] 2022-01-31 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
