### ISSUE TITLE
Can't finish export when count of threads lower than count of pages

### ISSUE THREAD

**Issue by EpicUsaMan** [zeit/next.js#8599] opened 2019-09-02 11:27 UTC
# Bug report

## Describe the bug

When count of threads lower than capacity of sema tokens (exportPaths.length) export can't be finished (12/13 like example)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. create export path map with 13 elements
2. start next export --threads 12
3. Observe result (12 pages are exported, 1 page can't be exported and wait for another worker)

## Expected behavior

All pages should be exported with any count of threads

## System information

- OS: Linux
- Version of Next.js: 9.0.3

**Comment by ijjk** [comment] 2019-09-02 14:40
Hi, I'm not able to reproduce this. Could you provide a link to a repo with a minimal reproduction and exact steps to reproduce? The above steps don't seem to cause it.

**Comment by ijjk** [comment] 2019-09-04 00:11
Closing since it doesn't seem to be able to be reproduced. Feel free to reply with additional details if you are able to find more specific details to reproduce

**Closed by ijjk** 2019-09-04 00:11 UTC
Labels: Can't Reproduce

**Comment by balazsorban44** [comment] 2022-01-31 05:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
