### ISSUE TITLE
React Context Provider in _app.js doesn't work in _document.js

### ISSUE THREAD

**Issue by yunluyl** [zeit/next.js#7551] opened 2019-06-10 17:58 UTC
# Bug report

I put a React Context Provider in my custom _app.js, and used the context in my pages. This resulted in undefined context in SSR.

## Describe the bug
_app.js
```js
import React, { Fragment } from 'react';
import { Modal } from '@redq/reuse-modal';
import '@redq/reuse-modal/es/index.css';
import { MyProvider } from '../../common/src/contexts/MyContext';

export default ({ Component, pageProps }) => {
  return (
    <Fragment>
      <Modal />
      <MyProvider>
        <Component {...pageProps} />
      </MyProvider>
    </Fragment>
  );
};
```
_document.js
```js
import Document, { Head, Main, NextScript } from 'next/document';
import { ServerStyleSheet } from 'styled-components';
import FavIcon from 'common/src/assets/image/favicon.png';

export default class CustomDocument extends Document {
  static async getInitialProps(ctx) {
    const sheet = new ServerStyleSheet();
    const originalRenderPage = ctx.renderPage;

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: App => props => sheet.collectStyles(<App {...props} />),
        });

      const initialProps = await Document.getInitialProps(ctx);
      return {
        ...initialProps,
        styles: (
          <>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </>
        ),
      };
    } finally {
      sheet.seal();
    }
  }
  render() {
    return (
      <html lang="en">
        <Head>
          <link rel="shortcut icon" type="image/x-icon" href={FavIcon} />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}
```
Error message: TypeError: Cannot read property 'value' of undefined

```js
ctx.renderPage
./pages/_document.js:11
   8 |    const originalRenderPage = ctx.renderPage;
   9 | 
  10 |    try {
> 11 |      ctx.renderPage = () =>
     | ^  12 |        originalRenderPage({
  13 |          enhanceApp: App => props => sheet.collectStyles(<App {...props} />),
  14 |        });
```

**Comment by frol** [comment] 2019-06-10 19:14
I have just bumped into the same issue. I am going investigate it further.

**Comment by frol** [comment] 2019-06-10 20:04
In my case, the issue was that I exported/imported a shortcut `MyContext.Consumer` and rendered it as `<MyConsumer></MyConsumer>`. For some reason, once I exported/imported the whole `MyContext` and rendered it as `<MyContext.Consumer></MyContext.Consumer>`, I get things going correctly.

**Comment by yunluyl** [comment] 2019-06-10 20:24
I used the React useContext hook instead of the Consumer. The dev server also reported the same error in my case.

**Comment by frol** [comment] 2019-06-10 20:35
I my case, the following code gets triggered and `reactContext = (reactContext: any)._context;` hide the problem in the dev build:

https://github.com/facebook/react/blob/d38cfd452f014167d223c73091d4a148a9f893a5/packages/react-dom/src/server/ReactPartialRenderer.js#L1122-L1148

**Comment by frol** [comment] 2019-06-11 20:29
It turned out that my issue was reported in #7167 and fixed in #7200 (which is only available in the 8.1.1 [canary] build)

**Comment by IAmNatch** [comment] 2019-06-29 00:20
@frol I've been searching all day for a solution to this problem and finally your post saved me.

I was running styled-components and it ran perfectly on dev, but would never show my themes in "prod" mode. I updated to `v8.1.1-canary.62`, with styled components at 4.3.2. 

Made my day thanks.

**Comment by ijjk** [comment] 2019-06-29 23:05
Closing as this looks like a duplicate of #7167 which has been resolved in the latest canaries of Next.js. If this is still a problem, feel free to reply with additional details.

**Closed by ijjk** 2019-06-29 23:05 UTC

**Comment by balazsorban44** [comment] 2022-01-31 13:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
