### ISSUE TITLE
`granularChunks` creates assets with invalid names

### ISSUE THREAD

**Issue by ematipico** [zeit/next.js#8836] opened 2019-09-24 12:41 UTC
# Bug report

## Describe the bug

When using `experimental.granularChunks`, some of the assets that are generates have names that don't play well with AWS S3. Some of the characters generate issue: https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Generate asset with invalid characters
2. Upload to S3 bucket
3. Try to serve it

## Expected behavior

I would expect a hash that is generated like the rest of the chunks that Next.js already creates.

## System information

- OS: macOS/Linux
- Version of Next.js 9.0.4

**Comment by Timer** [comment] 2019-09-26 14:10
This was fixed in Next.js 9.0.6. Please upgrade!

**Closed by Timer** 2019-09-26 14:10 UTC

**Comment by ematipico** [comment] 2019-09-26 14:37
Thank you @Timer !
I wish I could upgrade but this issue https://github.com/zeit/next.js/issues/8201 is a major blocker

**Comment by Timer** [comment] 2019-09-26 14:50
@ematipico #8201 is a bug in your application and cannot be fixed by Next.js.

**Comment by ematipico** [comment] 2019-09-26 20:45
Apologies @Timer but my app hasn't changed since Next.js 8.* and the only changes applied are the ones that Next.js required due to the upgrade.

My application follows the correct patterns dictated by the documentation and the error popped up after 9.0.3.

**Comment by balazsorban44** [comment] 2022-01-31 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
