### ISSUE TITLE
Current page persists when using Safari go back gesture

### ISSUE THREAD

**Issue by Lomkex1** [zeit/next.js#11720] opened 2020-04-07 03:52 UTC
![F88310B9-B5B0-427A-B2CD-9BB849A8443E](https://user-images.githubusercontent.com/18073779/78628174-7b7d4b80-78a4-11ea-816f-81e89037a67c.gif)

This happens when going back with back gesture, current page persists(maybe it is being rerendered)

**Comment by timneutkens** [comment] 2020-04-07 09:47
Closing as the issue template was not followed.

**Closed by timneutkens** 2020-04-07 09:47 UTC

**Comment by balazsorban44** [comment] 2022-01-30 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
