### ISSUE TITLE
Transpiling components outside /pages?

### ISSUE THREAD

**Issue by malexdev** [zeit/next.js#883] opened 2017-01-25 18:58 UTC
Hello! I'm just now getting started with next (using version 1.2.3), and I have the following folder structure:

- package.json
- pages
  - index.js
- lib
  - components
    - Test.js

I have a symlink: `node_modules/lib -> ../lib`.
I import my `Test` component with `import Test from 'lib/components/Test'`.

This works fine, but it seems to not be transpiled: if I `import` anything from my `Test` component, I get the following error: `SyntaxError: Unexpected token import`.

Any guidance here? I'd be fine having my `/components` under `/pages` but I don't want them to be able to be served up standalone.

Thanks!

**Comment by timneutkens** [comment] 2017-01-25 19:18
Duplicate of https://github.com/zeit/next.js/issues/706

**Comment by timneutkens** [comment] 2017-01-25 19:22
Short term answer is use relative paths for now. So `import Test from 'lib/components/Test'` would become `import Test from '../lib/components/Test'`

**Closed by timneutkens** 2017-01-25 19:22 UTC
Labels: Type: Question

**Comment by malexdev** [comment] 2017-01-25 20:10
Ah, sorry for the duplicate, and makes sense about not transpiling node_modules. Thanks!

**Comment by timneutkens** [comment] 2017-01-25 20:12
🙌
