### ISSUE TITLE
Unexpected identifier while using Import

### ISSUE THREAD

**Issue by petermarks12** [zeit/next.js#9751] opened 2019-12-14 17:59 UTC
I am using import statement in one of the javascript file which is on root level (utils/xyz.js)  I am also using nodemom because of custom server routing.   As far I know the error is due to babel because if i change import and export to common js style, it works fine, but not with es6 module style.  Do i need to install some plugin to make it work?

Scripts in Package.json
`"scripts": {
    "dev": "nodemon server/index.js",
    "build": "next build",
    "start": "NODE_ENV=production node server/index.js"
  },`

Screenshot:
https://i.imgur.com/RqgV6ZS.png

**Comment by jamesmosier** [comment] 2019-12-14 18:46
If the file lives outside of the Next `dir` defined in your [custom server](https://nextjs.org/docs#custom-server-and-routing), it will not be transpiled by Babel. Any custom server code can only use valid Node.js syntax, therefore `import` will not work.

For example:

```js
const app = next({
  dev: true,
  dir: path.resolve(__dirname, './app')
});

```

and a folder structure of:

```
app
  - pages
      - index.js
server
  - index.js
utils
  - xyz.js
```

anything outside of `app` will not be transpiled with Babel.

These issues describe similar issues.

* https://github.com/zeit/next.js/issues/9474
* https://github.com/zeit/next.js/issues/4315

**Comment by Timer** [comment] 2019-12-14 19:03
Closing as likely reasoning was given.

**Closed by Timer** 2019-12-14 19:03 UTC

**Comment by balazsorban44** [comment] 2022-01-30 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
