### ISSUE TITLE
After cloning and running the with-firebase-hosting I got 404 page

### ISSUE THREAD

**Issue by larrotta69** [zeit/next.js#3640] opened 2018-01-31 01:17 UTC
In `with-firebase-hosting` I got 404 page once I run `npm run serve` and go to `localhost:5000/`

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

See the next server running, home page 
## Current Behavior

404 page
## Steps to Reproduce (for bugs)

1. Clone the repo
2. Install dependencies then add my firebase project name
3. npm run serve

**Comment by sarovin** [comment] 2018-01-31 11:31
Is it a duplicate of #3634?

**Comment by larrotta69** [comment] 2018-02-02 15:30
I didn't do a change for the code, just put my firebase project name and is not working

**Comment by NickDelfino** [comment] 2018-02-20 00:05
I am also seeing this same issue on MacOS with this example. No modifications besides changing the project name. 

When I deploy, I get the logs from the failure and they show a module missing in the next folder. 
`{ Error: Cannot find module '/Users/nickdelfino/Documents/reactjs/test/app/node_modules/next/dist/pages/_document.js'     at Function.Module._resolveFilename (module.js:469:15)     at Function.Module._load (module.js:417:25)     at Module.require (module.js:497:17)     at require (internal/module.js:20:19)     at Object.10 (/user_code/next/dist/bundles/pages/_document.js:78:18)     at __webpack_require__ (/user_code/next/dist/bundles/pages/_document.js:23:31)     at Object.9 (/user_code/next/dist/bundles/pages/_document.js:85:18)     at __webpack_require__ (/user_code/next/dist/bundles/pages/_document.js:23:31)     at /user_code/next/dist/bundles/pages/_document.js:70:18     at Object.<anonymous> (/user_code/next/dist/bundles/pages/_document.js:73:10) code: 'MODULE_NOT_FOUND' }`

**Comment by jthegedus** [comment] 2018-02-20 13:42
hey all, this may be the same as this issue https://github.com/zeit/next.js/issues/3167 

@larrotta69 please give the whole thread a read.

**Comment by jthegedus** [comment] 2018-02-20 23:15
@NickDelfino On the deployed code too.. hmm. I'm not sure if the example pins the Next version to v4, but it has not been updated to v5 yet so that may be the issue. I am working on an update to v5 atm. I will go through some testing this evening and get back to you.

**Comment by NickDelfino** [comment] 2018-02-23 14:39
@jthegedus did you have any luck reproducing this issue? Or anyone else who may have tried? No worries or rush. Thanks!

**Comment by abelta** [comment] 2018-02-25 10:29
Can confirm that this is happening both in local and in production. It's giving me a 500, not a 404, though.

**Comment by jthegedus** [comment] 2018-02-25 14:10
Please test https://github.com/zeit/next.js/pull/3886 to see if it fixes your problems.

This error:

```
{ Error: Cannot find module '/home/james/Projects/Personal/firebase-functions-next-example/node_modules/next/dist/pages/_error.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.8 (/user_code/next/dist/bundles/pages/_error.js:86:18)
    at __webpack_require__ (/user_code/next/dist/bundles/pages/_error.js:23:31)
    at Object.7 (/user_code/next/dist/bundles/pages/_error.js:78:18)
    at __webpack_require__ (/user_code/next/dist/bundles/pages/_error.js:23:31)
    at /user_code/next/dist/bundles/pages/_error.js:70:18
    at Object.<anonymous> (/user_code/next/dist/bundles/pages/_error.js:73:10) code: 'MODULE_NOT_FOUND' }
```

was fixed by adding a `_error.js` page to the `pages/` dir taken from: https://github.com/zeit/next.js/#custom-error-handling


After adding that I then got:

```
{ Error: Cannot find module '/home/james/Projects/Personal/firebase-functions-next-example/node_modules/next/dist/pages/_document.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.10 (/user_code/next/dist/bundles/pages/_document.js:78:18)
    at __webpack_require__ (/user_code/next/dist/bundles/pages/_document.js:23:31)
    at Object.9 (/user_code/next/dist/bundles/pages/_document.js:85:18)
    at __webpack_require__ (/user_code/next/dist/bundles/pages/_document.js:23:31)
    at /user_code/next/dist/bundles/pages/_document.js:70:18
    at Object.<anonymous> (/user_code/next/dist/bundles/pages/_document.js:73:10) code: 'MODULE_NOT_FOUND' }
```

which was fixed by adding a `_document.js` page to the `pages/` dir taken from: https://github.com/zeit/next.js/#custom-document (minus the `styled-jsx` stuff).

This issue either started because of the [upgrade to next.js 5](https://github.com/zeit/next.js/commit/9a82ca4029151754097c7b4c77e125516c97171e) or because of some flux within the Firebase Functions product. Due to this issue opening the same number of days ago as the next.js dep upgrade I would put it down to that.

Thanks to https://github.com/JulienHe for previously solving this issue and sharing with me. Checkout his latest blog post about [next-routes with Firebase Hosting](https://codeburst.io/next-routes-with-firebase-hosting-on-cloud-functions-e7c78308a24d).

**Closed** 2018-02-28 10:54 UTC
Labels: good first issue, help wanted

**Comment by NickDelfino** [comment] 2018-03-02 00:14
This worked for me! Thanks for looking into this!
