### ISSUE TITLE
[RFC] Exported `getInitialProps`

### ISSUE THREAD

**Issue by sergiodxa** [zeit/next.js#8535] opened 2019-08-27 16:00 UTC
## Goal

Make using `getInitialProps` easier for function components.

## Background

When static method `getInitialProps` was added the main way to create React components where classes, an example of how a Page level component looks with this is:

```js
export default class MyPage extends React.Component {
  static async getInitialProps(ctx) {
    // do something here
  }

  componentDidMount() {
    // run some effect
  }

  render() {
    // render something here
  }
}
```

With Hooks page levels components with complex logic could be created a simpler function components.

```js
export default function MyPage(props) {
  React.useEffect(() => {
    // run some effect
  });

  // render something here
}
```

But if we want to use `getInitialProps` we still need to ues static method, that means doing something like this:

```js
MyPage.getInitialProps = async ctx => {
  // do something here
}
```

While it works I have found it a little repetitive and not the best experience I would expect from Next.js and as it was it class based components.

## Proposal

I propose add support to do a named export for `getInitialProps`, the function component file will then look like this:

```js
export default function MyPage(props) {
  React.useEffect(() => {
    // run some effect
  });

  // render something here
}

export async function getInitialProps(ctx) {
  // do something here
}
```

We could still support the static method which for classes based components.

This will also match how the config is exported for API endpoints.

As a side effect of this I could re-export `getInitialProps` from another module with a single line.

```js
export default function MyPage(props) {
  React.useEffect(() => {
    // run some effect
  });

  // render something here
}

export { getInitialProps } from "../another/module
```

This could let me extract it to another file and share it easier.

**Comment by timneutkens** [comment] 2019-08-28 08:59
This is something @Timer has been wanting to do for a while, however I'm still not convinced it's the way to go. It depends on how data fetching ends up in the near future.

**Comment by Jessidhia** [comment] 2019-09-04 03:12
For what it's worth, this does get a reduction in bundle size as the `getInitialProps` `Identifier` no longer has to be preserved in the bundle, but it's really negligible.

**Comment by HaNdTriX** [comment] 2019-09-04 15:50
@sergiodxa many HOCs out there use and extend the `getInitialProps` method.

https://github.com/zeit/next.js/blob/73f6e04b6bfe02c95eeffd7d113eedcb82da9300/examples/with-apollo/lib/apollo.js#L44-L45

How would such a pattern look like using your proposal?

**Comment by sergiodxa** [comment] 2019-09-04 17:53
1. HOCs wouldn’t need to do something special for getInitialProps anymore since the method will be exported separately of the component, if you want to extend the gIP method you could create a High Order Function and compose it with the exported one. This will let devs only compose  what they need.

2. This doesn’t change, you could use an arrow function, assign it to a constant, apply getInitialProps and export it. If people want to do it they will, also is not a Next issue but more something React docs should warn about.

3. Yeah, but with exported gIP you can just export directly from the import, in a single line. Not a big deal however.

**Comment by fabb** [comment] 2019-11-01 12:44
The proposal does not play well with TypeScript, as the expected return type of `getInitialProps` cannot be automatically inferred, whereas currently it can when using the `MyPage.getInitialProps =` idiom.

**Comment by amitdahan** [comment] 2019-11-10 14:50
@fabb 
Isn't `MyPage.getInitialProps` only typed when the user manually annotates his component with the `NextPage` type?

If so, it means the user already had to explicitly annotate something for the `MyPage.getInitialProps` type to work as expected, so what's another type annotation?
In fact, if we'd type the `getInitialProps` export _separately_, we won't need `NextPage` anymore (unless I'm forgetting something), so we're left with only 1 type, which is more concise (and less dependant on react's types?).

**Comment by fabb** [comment] 2019-11-10 16:03
You need to type it, otherwise you cannot typesafely access the props in `render`.

**Comment by amitdahan** [comment] 2019-11-10 21:22
Whoops, that's what I missed.
So it'll mean manually typing 2 things instead of 1 for the same result. I see why this is less than ideal.

**Comment by Timer** [comment] 2020-04-15 05:31
Closing as the new exported `getServerSideProps` and `getStaticProps` use this behavior. Thanks for initial thoughts!

**Closed by Timer** 2020-04-15 05:31 UTC
Labels: RFC

**Comment by balazsorban44** [comment] 2022-01-30 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
