### ISSUE TITLE
Duplicate commons script

### ISSUE THREAD

**Issue by narek1993x** [zeit/next.js#8819] opened 2019-09-22 09:09 UTC
# Bug report

## Describe the bug

When i create default layout component for my nextjs pages and import it with next/dynamic i see duplicate commons link(in head) and script(in body).

## To Reproduce

I created the repository for reproduction.
https://github.com/narek1993x/duplicate_commonjs_script

1. Go to localhost:3000.
2. Open inspect element on the page.
3. You can see commons script is duplicated.

## Expected behavior

See only one commons script.

## Screenshot

https://ibb.co/X4d3KvK

## System information

- OS: Linux
- Browser Chrome
- Version of Next.js: 9.0.0

**Comment by ijjk** [comment] 2019-09-22 17:22
Hi, this appears to be a duplicate of #8678 and is resolved in the latest version of Next.js `v9.0.6`

**Closed by ijjk** 2019-09-22 17:22 UTC

**Comment by balazsorban44** [comment] 2022-01-31 04:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
