### ISSUE TITLE
getInitialProps is not called for external url

### ISSUE THREAD

**Issue by OscarBengtsson** [zeit/next.js#5024] opened 2018-08-24 04:06 UTC
```getInitialProps``` is called well while routing inside the project.
However it doesn't work when navigating external url and click back button of browser.
Here is the simple flow of my project.

```
class Profile extends React.Component {
    // Update the profile avatar and show updated avatar
    // Call api to update avatar at backend database
}
Profile.getInitialProps = () => {
    // Call api to get profile information
}
```

1. I see the profile avatar from api response.
2. I update the avatar and see updated avatar.
3. I navigate to external url - e.g Terms pdf url.
4. When I click back button, I see the old avatar as `getInitialProps()` is not called.
5. I refresh the page and I see the updated avatar.

Is this normal behavior of `next-routes` or bug?
As my project has many other cases of this, I really need the solution or alternatives.
Thanks,

**Comment by SniperGER** [comment] 2018-08-24 06:59
Having the same issue here, but with local URLs instead. Every time I navigate two or more pages forward (like for example `index -> login -> dashboard`) and navigate back, `index` errors out because `this.props.property.map` is undefined (I'm mapping an array here that gets its data from `getInitialProps`).

I throw in a `console.log()` or a `console.trace()` and nothing shows up in the log, so I assume that `getInitialProps` never gets called when the browser navigates back.

This error happens in the latest 6.1.1, in 5.1.0 and even in one of the early 5.0.0 alphas on both macOS/Safari and Windows/Firefox. Even a proposed solution found in #3065 didn't help at all.

Here, have some example code:

```javascript
import React, { Component as ReactComponent } from "react";
import Link from "next/link";
import { PackageApi, AuthApi } from "../shared/api/services";

export default class Index extends ReactComponent {
    static async getInitialProps({ asPath, req, res, query }) {
        if (typeof req === "undefined") {
            return __NEXT_DATA__.props;
        }

        this["PackageApi"] = new PackageApi();
        this["AuthApi"] = new AuthApi();

        const packageData = await this["PackageApi"].getPackages();
        const popularPackages = await this["PackageApi"].getPopularPackages(5);

        return {
            packages: packageData,
            popularPackages: popularPackages
        };
    }
    render() {
        return (
            <div>
                <Head/>
                <div className="header">
                    <Link href="/login" as="/login" prefetch={true}>
                        <div className={`account-button ${this.props.loggedIn ? "logged-in" : ""}`}>
                            {this.props.loggedIn &&
                            <div className="letters">{this.getInitials(this.props.userInfo.username)}</div>
                            }
                        </div>
                    </Link>
                </div>
            </div>
            [...]
        )
    }
}
```

**Comment by SniperGER** [comment] 2018-08-24 12:03
I really can't see why this is supposed to be intended behavior. Is there any way to make this method get called server-side every time? Because in my case, `getInitialProps` contains logic in some places that can only be used on the server.

**Comment by timneutkens** [comment] 2018-08-24 12:57
I guess not using `next/link` would work, just plain `<a>` tags.

If you have logic that can only run on the client side the best thing you can do is create a separate API endpoint for that logic so that you can call it on both the server/client side.

**Comment by HaNdTriX** [comment] 2018-08-24 15:09
@SniperGER 

```js
        if (typeof req === "undefined") {
            return __NEXT_DATA__.props;
        }
```

You are using the following code above. In other words when `getInitialProps` is called on the server you are aborting. Try removing the code above.

**Comment by OscarBengtsson** [comment] 2018-08-25 04:32
@HaNdTriX I don't think your sample project works for this case.
```
Navigate back from external url (external): getInitialProps is called on the server (server render).
```
I've checked your logs and server side `getInitialProps` isn't called when I click back from external url, which is also not working for my project.

**Comment by HaNdTriX** [comment] 2018-08-25 09:25
@OscarBengtsson Please provide a full working example in a separate repository. Otherwise I can't help you. Right now I can only guess whats wrong with your code.

**Comment by OscarBengtsson** [comment] 2018-08-27 14:39
@HaNdTriX This is the sample project you provided before.
[source](https://zeit.co/handtrix/data-fetch/ixbnrmwfyr/source)
[example](https://data-fetch-ixbnrmwfyr.now.sh/index?pageId=3)
[server side log](https://zeit.co/handtrix/data-fetch/ixbnrmwfyr/logs)

* You need to refresh the log page every time you do action.
1. When you reach out to example page, you see the server log 3.
2. Navigate to external url, and click back button.
3. There are no logs at server side and client side.

**Comment by ijjk** [comment] 2019-03-17 16:57
The original issue might be related to #5648 but it sounds like as @HaNdTriX pointed out that you might be adding code in your `getInitialProps` to cause it to not be called. 

I'm going to close this issue in favor of the other, if you think this isn't actually related to other issue feel free to comment.

**Closed by ijjk** 2019-03-17 16:57 UTC
Labels: Type: Needs Investigation

**Comment by ssolanki** [comment] 2019-12-23 11:29
@OscarBengtsson Did you find any work around this?

**Comment by balazsorban44** [comment] 2022-01-30 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
