### ISSUE TITLE
Module not found: Error: Can't resolve '../components' in '/mnt/c/users/lucifer/Desktop/New/github-betaprofile/pages'

### ISSUE THREAD

**Issue by TeAmP0is0N** [zeit/next.js#8947] opened 2019-10-03 08:46 UTC
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2]

## Additional context

```bash
ModuleNotFoundError: Module not found: Error: Can't resolve '../components' in '/mnt/c/users/lucifer/Desktop/New/github-betaprofile/pages'
    at factory.create (/mnt/c/users/lucifer/Desktop/New/github-betaprofile/node_modules/webpack/lib/Compilation.js:888:10)
    at factory (/mnt/c/users/lucifer/Desktop/New/github-betaprofile/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
    at resolver (/mnt/c/users/lucifer/Desktop/New/github-betaprofile/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/mnt/c/users/lucifer/Desktop/New/github-betaprofile/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /mnt/c/users/lucifer/Desktop/New/github-betaprofile/node_modules/neo-async/async.js:2830:7
    at /mnt/c/users/lucifer/Desktop/New/github-betaprofile/node_modules/neo-async/async.js:6877:13
    at normalResolver.resolve (/mnt/c/users/lucifer/Desktop/New/github-betaprofile/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/mnt/c/users/lucifer/Desktop/New/github-betaprofile/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/mnt/c/users/lucifer/Desktop/New/github-betaprofile/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/mnt/c/users/lucifer/Desktop/New/github-betaprofile/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/mnt/c/users/lucifer/Desktop/New/github-betaprofile/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/mnt/c/users/lucifer/Desktop/New/github-betaprofile/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/mnt/c/users/lucifer/Desktop/New/github-betaprofile/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/mnt/c/users/lucifer/Desktop/New/github-betaprofile/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/mnt/c/users/lucifer/Desktop/New/github-betaprofile/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/mnt/c/users/lucifer/Desktop/New/github-betaprofile/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
```

I used to create a next.config.js file with the following content to get the client bundle to build:
```bash
module.exports = {
  webpack: (config, { isServer }) => {
    // Fixes npm packages that depend on `fs` module
    if (!isServer) {
      config.node = {
        fs: 'empty'
      }
    }

    return config
  }
}
```

**Comment by Janpot** [comment] 2019-10-03 09:04
Does that mean https://github.com/zeit/next.js/issues/8945 is resolved? If so, maybe you can close that ticket?

According to the issue template:
> If you have a question related to Next.js or the examples. Reach out to the community on https://spectrum.chat/next-js

**Comment by timneutkens** [comment] 2019-10-03 09:59
Going to close this issue as it doesn't provide a reproduction.

**Closed by timneutkens** 2019-10-03 09:59 UTC

**Comment by balazsorban44** [comment] 2022-01-31 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
