### ISSUE TITLE
webpack alias ignored on landing for files inside node_modules

### ISSUE THREAD

**Issue by eps1lon** [zeit/next.js#7588] opened 2019-06-16 16:17 UTC
# Bug report

## Describe the bug

webpack's `config.resolve.alias` works different for initial landing and navigation. It seems to be ignored when landing on a page but used as expected when navigating to a page (via next/link).

Edit: Difference is only observable for files inside `node_modules/`

## To Reproduce

See https://github.com/eps1lon/next-webpack-alias#steps-to-reproduce

## Expected behavior

aliases are used for initial landing as well. The idea for the implementation was taken from https://github.com/zeit/next.js/tree/canary/examples/with-absolute-imports

## Screenshots

N/A

## System information

- OS: Ubuntu 18.04.2 LTS
- Browser: Version 75.0.3770.80 (Official Build) (64-bit)
- Version of Next.js: 8.1.0 and 9.0.2

## Additional context

The use case in the constructed repository is simpler than our actual use case but I believe that config.resolve.alias working differently in some cases is the root cause.

We have docs and published packages living in a monorepo. Some of the npm packages used in our docs depend on our packages and want only a single version of our published packages in the docs bundle.

### why is resolve.alias ignored?
`.next/server/static/BUILD_ID/pages/*` uses standard `require` instead of inlining those modules. The node_modules/ are included via node's `require` at which point webpack's resolve.alias will no longer be of effect. This may be an issue with chunking? Should probably just disable it for static/BUILD_ID/pages

### fix iteration
- removing `externals` from the webpack config fixes the issue. Need to find out why all node_modules should be externals.

**Comment by eps1lon** [comment] 2019-07-20 09:53
Still happening with 9.0.2.

Would appreciate it if someone could respond if this is a bug or changing the expected behavior would be accepted as a feature.

**Comment by Timer** [comment] 2019-07-20 22:06
This is a feature request, not a bug -- it's not expected to be able to alias modules _within_ `node_modules` unless you're using the `serverless` target.

We can investigate this more in the future, but it appears like this behavior might remain the same unless we start compiling `node_modules`.

**Comment by eps1lon** [comment] 2019-07-21 08:26
Yeah I've pinned this down to node_modules being included in the `externals` of webpack. This means no alias or loaders are working for `node_modules` for the server build. 

It's just a bit unfortunate that I missed this in the docs (if it is mentioned).

A naive solution only marks react and react-dom as externals
```js
if (options.isServer) {
	config.externals = ['react', 'react-dom'];
}
```

Our `next build` time went from 141s to 217s. Memory consumption increased considerably to the point where netlify and azure ran out of memory. Will look into a merging strategy for `external` where we only exclude those modules from externals where we need the alias.

**Comment by RDeluxe** [comment] 2019-08-28 15:08
We had the same issue with Next, SSR, react hooks and lerna.

As lerna is using symlinks we had the famous error 

> more than one copy of React

We usually we simply use aliases, but in this case they were not working.

Thanks to @eps1lon for his solution, we did not know that during server compilation all node_modules were set as externals though.

**Comment by Timer** [comment] 2019-08-30 17:38
Closing this as a duplicate of https://github.com/zeit/next.js/issues/706.

By design, webpack doesn't parse (and thus can't alias) modules that are marked external (`node_modules`).

Thanks!

**Closed by Timer** 2019-08-30 17:38 UTC
Labels: Type: Feature Request, Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 01:26
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
