### ISSUE TITLE
[expo][next-babel-loader] plugin resolution failing 

### ISSUE THREAD

**Issue by EvanBacon** [zeit/next.js#8567] opened 2019-08-29 22:45 UTC
# Bug report

## Describe the bug

Starting an Expo web project with next.js support fails in `next-babel-loader` when looking for the plugins in `babel-preset-expo`:

```sh
./pages/index.js
Error: [BABEL] /Users/evanbacon/Documents/GitHub/expo/next-example/pages/index.js: Cannot find module '@babel/plugin-proposal-decorators' from '/Users/evanbacon/Documents/GitHub/expo/next-example'
    at Array.map (<anonymous>)
```

## To Reproduce

Following: [using next with expo](https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/guides/using-nextjs.md)

1. `expo init` (select the blank JS template)
2. `yarn add next`
3. Update the `app.json`:
```json
{
  "expo": {
    "web": {
      "use": "nextjs"
    }
  }
}
```
4. Move the contents of `App.js` to a new file `pages/index.js`
5. Run `expo start --web-only --web --dev`
6. Errors out

### Workaround

Option 1: `yarn add @babel/plugin-proposal-decorators` to your project (effectively including it in the root `node_modules`)

Option 2: Change `babel-preset-expo`:
```diff
- ['@babel/plugin-proposal-decorators', { legacy: true }],
+ [require.resolve('@babel/plugin-proposal-decorators'), { legacy: true }],
```

## Expected behavior

`@babel/plugin-proposal-decorators` is a dependency of `babel-preset-expo`. `next-babel-loader` should follow node's module resolution to find the library.

## System information

- OS: [macOS]
- Next.js v9.0.2
- `expo-cli` v3.0.9
- `expo@34.0.1`
- `next@^9.0.5`
- `babel-preset-expo@6.0.0`

**Comment by Timer** [comment] 2019-09-03 14:43
Hi @EvanBacon! 

This appears to be due to a bug in `babel-preset-expo` -- Babel presets are expected to `require` or `require.resolve` their plugins/etc.

`next-babel-loader` doesn't handle any of the resolving, so there's nothing we can fix from our side.
The error you provided is even coming from Babel:
```
Error: [BABEL] ...
```

See https://github.com/babel/babel-loader/issues/166#issuecomment-417894775, along with the [Next.js preset](https://github.com/zeit/next.js/blob/canary/packages/next/build/babel/preset.ts). This was also one of the first bugs fixed in [the CRA toolbox](https://github.com/facebook/create-react-app/pull/36).

**Closed by Timer** 2019-09-03 14:43 UTC
Labels: Type: Needs Investigation

**Comment by AndrewRayCode** [comment] 2020-01-20 21:57
I just bumped next from 7 to 9, and I'm getting this error now:

> Entry module not found: Error: Can't resolve 'next-babel-loader' in '/myfolder/src'

I'm not using "babel-preset-expo" so not yet sure if this is related

**Comment by AndrewRayCode** [comment] 2020-01-20 22:44
Ah I see, https://github.com/zeit/next.js/blob/e04e5a5c15bdf52dfbaef4842ffc4b6cfc9ea059/packages/next/build/index.ts#L375 checks for config.alias, but not `resolveLoader.alias`, which I was not merging in from nextjs to my own

**Comment by balazsorban44** [comment] 2022-01-30 15:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
