### ISSUE TITLE
cannot access Router in _app.js

### ISSUE THREAD

**Issue by lifeiscontent** [zeit/next.js#10585] opened 2020-02-19 04:00 UTC
# Bug report

## Describe the bug

I can't seem to use router in _app.js when I import it from

```js
import { useRouter } from "next/router";
export default function App({ Component, pageProps }) {
  const router = useRouter();
  console.log(router.asPath);
  return (
      <Component {...pageProps} />
  );
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create `_app.js`
2. Paste my example
3. Boot up server and goto a page that has a route segment
4. See the asPath change

```
/editor/[slug]
/editor/foobar
```

on the server, I'd expect the asPath to be the same here, the use case here is so I can selectively highlight the active pages.

## Expected behavior

Consistent asPath output

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2]

**Comment by timneutkens** [comment] 2020-02-19 10:04
Duplicate of #8259

**Closed by timneutkens** 2020-02-19 10:04 UTC

**Comment by balazsorban44** [comment] 2022-01-30 13:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
