### ISSUE TITLE
Sass and CSS with AMP

### ISSUE THREAD

**Issue by achrinza** [zeit/next.js#8387] opened 2019-08-16 05:15 UTC
I've checked the [NextJS docs](https://nextjs.org/docs) but have not found examples on how CSS or Sass is used with AMP. I haven't been able to use either CSS or Sass without the export failing. Is there a standard way to go about this?

**Comment by timneutkens** [comment] 2019-08-16 11:15
Going to close this as it doesn't follow the issue template. Questions should be posted on spectrum.chat/next-js.

**Closed by timneutkens** 2019-08-16 11:15 UTC

**Comment by balazsorban44** [comment] 2022-01-31 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
