### ISSUE TITLE
Add example: with-antd-mobile with less

### ISSUE THREAD

**Issue by phillip055** [zeit/next.js#8403] opened 2019-08-17 15:45 UTC
## Describe the solution you'd like
with-antd-mobile is working but the example allows no custom css/less.

Either add custom css in with-antd-mobile or have with-antd-mobile-less like the one we have on with-antd-less

**Comment by phillip055** [comment] 2019-08-17 15:47
Either add custom css in with-antd-mobile or have with-antd-mobile-less like the one we have on with-antd-less

**Comment by Timer** [comment] 2020-01-21 13:57
Duplicate of #9830

**Closed by Timer** 2020-01-21 13:57 UTC

**Comment by balazsorban44** [comment] 2022-01-30 15:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
