### ISSUE TITLE
Typescript Issue, with-apollo example, usage of App as a typed parameter in HOC.

### ISSUE THREAD

**Issue by james-ff** [zeit/next.js#6707] opened 2019-03-18 18:27 UTC
# with-apollo Example bug report

## Describe the bug
I am using the with-apollo example in my project, which I have recently converted to Typescript. I have been able to successfuly make the switch to Typescript, apart from one file in the example `with-apollo-client.js` which is now `.tsx` for me. 

Example File:
https://github.com/zeit/next.js/blob/canary/examples/with-apollo/lib/with-apollo-client.js

I have set a type for the App / AppComponent in the Higher Order Component here to AppComponentType from 'next/app', just adding apolloClient as a prop, which seems to be correct.

The issue is in the difference in the usage of the AppComponent in `render` and in `getInitialProps` functions. In `getInitialProps` it receives all of it's props and is happy. But in `render` there is a Type Error saying that it isn't being given `Component` or `router`. I'm not quite sure what is right here: should the render version have these props? should these props be optional? Is this a typescript thing that can be corrected?

## Screenshots

AppComponent definition at the start of the HOC, (AppComponentType imported from 'next/app'):

![Screen Shot 2019-03-18 at 18 03 28](https://user-images.githubusercontent.com/1874352/54553997-5113d400-49ab-11e9-8a7e-15c22472f5dc.png)

Definition of ApolloProps, for clarity:

![Screen Shot 2019-03-18 at 18 03 43](https://user-images.githubusercontent.com/1874352/54553417-13627b80-49aa-11e9-9ebb-6f0e1a52c5e8.png)

Usage in `getInitialProps` function:

![Screen Shot 2019-03-18 at 18 16 25](https://user-images.githubusercontent.com/1874352/54553490-342ad100-49aa-11e9-875d-f5933d3c91fd.png)

Usage in `render` function, missing Component and router as props:

![Screen Shot 2019-03-18 at 18 03 14](https://user-images.githubusercontent.com/1874352/54553519-4573dd80-49aa-11e9-89d7-07dbc4b8ea96.png)

The Type error on AppComponent in the render function (missing Component / router props):

![Screen Shot 2019-03-18 at 18 03 07](https://user-images.githubusercontent.com/1874352/54553191-92a37f80-49a9-11e9-910c-cc63e53b74df.png)

## System information
 - OS: macOS
 - Version of Next.js: 8.0.3

**Comment by msreekm** [comment] 2019-03-20 12:38
if you add this to your app.tsx ,it should fix the erorr-

interface IProps {
  apolloClient: any;
}
MyApp extends App<IProps> {
}

**Comment by james-ff** [comment] 2019-03-20 13:15
Thank you for your suggestion, this helps, but the props in question `{ Component, router }` are the issue here primarily. (Screenshots 3-5 where <AppComponent ... /> is used)

**Comment by skliffmueller** [comment] 2019-05-01 14:25
I would get similar errors, from pageProps not being assigned on my App component, getInitialProps not being assigned properly, or Component, router not being assigned.

This was my fix:

with-apollo-client.tsx
```import React from 'react'
import initApollo from './init-apollo'
import Head from 'next/head'
import { getDataFromTree } from 'react-apollo'
import { AppComponentType, AppProps, DefaultAppIProps, NextAppContext } from 'next/app';
import { ApolloClient, NormalizedCacheObject } from 'apollo-boost'

export interface IApolloProps {
  apolloState?: NormalizedCacheObject;
  apolloClient: ApolloClient<NormalizedCacheObject>;
}

export default (MyApp: AppComponentType<IApolloProps & DefaultAppIProps>) => {
  return class Apollo extends React.Component<IApolloProps & DefaultAppIProps & AppProps> {
    public apolloClient: ApolloClient<NormalizedCacheObject>;
    static displayName = 'withApollo(App)';
    static async getInitialProps (ctx: NextAppContext) {
      const { Component, router } = ctx;

      let appProps = {}
      if (MyApp.getInitialProps) {
        appProps = await MyApp.getInitialProps(ctx)
      }
      // Run all GraphQL queries in the component tree
      // and extract the resulting data
      const apollo = initApollo();
      try {
        // Run all GraphQL queries
        await getDataFromTree(
      <MyApp
            {...appProps}
            pageProps={{}}
            Component={Component}
            router={router}
            apolloClient={apollo}
        />
      )
      } catch (error) {
        // Prevent Apollo Client GraphQL errors from crashing SSR.
        // Handle them in components via the data.error prop:
        // https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-query-data-error
        console.error('Error while running `getDataFromTree`', error)
      }

      // getDataFromTree does not call componentWillUnmount
      // head side effect therefore need to be cleared manually
      Head.rewind();


      // Extract query data from the Apollo store
      const apolloState = apollo.cache.extract();

      return {
        ...appProps,
        apolloState,
      }
    }

    constructor (props: IApolloProps & DefaultAppIProps & AppProps) {
      super(props);
      this.apolloClient = initApollo(props.apolloState);
    }

    render () {
      return <MyApp
        {...this.props}
        apolloClient={this.apolloClient}
      />
    }
  }
}
```

_app.tsx
```
import {AppProps, Container, DefaultAppIProps} from 'next/app';
import * as React from "react";
import withApolloClient, {IApolloProps} from '../lib/with-apollo-client'
import { ApolloProvider } from "react-apollo";

class MyApp extends React.Component<IApolloProps & DefaultAppIProps & AppProps> {
  render() {
    const { Component, pageProps, apolloClient } = this.props;
    return (
      <Container>
        <ApolloProvider client={apolloClient}>
          <Component {...pageProps} />
        </ApolloProvider>
      </Container>
    );
  }
}

export default withApolloClient(MyApp);
```

**Comment by huv1k** [comment] 2019-05-07 09:04
Closing @skliffmueller explanation should work if it's still a problem please comment again.

**Closed by huv1k** 2019-05-07 09:04 UTC

**Comment by muco-rolle** [comment] 2019-09-21 12:32
kl

**Comment by rheaditi** [comment] 2019-09-25 09:06
@skliffmueller @huv1k

Any suggestions for adding typings for the new `withApollo` examples for Page Components?
Trying to use typings similar to `withRouter` HOC, but getting some errors:

![image](https://user-images.githubusercontent.com/6426069/65586373-b1f71700-dfa1-11e9-8699-4cd01edb35c6.png)

**Comment by d-dmytro** [comment] 2019-11-06 18:56
@rheaditi Suggestions about typings: https://gist.github.com/d-dmytro/5269b6cba5efea557ce35ad38778ec2e

**Comment by balazsorban44** [comment] 2022-01-31 00:12
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
