### ISSUE TITLE
Store gets created twice on server

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#978] opened 2017-02-03 16:46 UTC
Code involving redux apparently can't avoid creating its store twice server-side (as mentioned in https://github.com/zeit/next.js/issues/273 and visible in the various examples including my app: https://github.com/relatenow/relate/blob/master/hocs/withData.js), which might result in loss of performance.

That's because getInitialProps can only return a JSON and no proper JavaScript object, so that it can be passed over the wire to the browser. 

Would it be possible for getInitialProps to allow returning objects, only when executed server-side for the initial server render?

**Comment by arunoda** [comment] 2017-02-04 00:26
@sedubois I was working on something similar. So, you should create the store on the `getInitialProps`. But just the initial data (is has).

Creating the store needs to do on the component's(ideally inside the HOC) constructor.

**Comment by sedubois** [comment] 2017-02-04 06:30
@arunoda but in the context of Apollo SSR creating the store is needed to pre-fetch all data with getDataFromTree. I don't see how we could avoid doing that in getInitialProps?

**Comment by arunoda** [comment] 2017-02-04 13:16
@sedubois then we need to create a helper, which caches the apollo client instant for a given a set of initial params. So, both getInitialData and component HOC get the same client.

**Comment by sedubois** [comment] 2017-02-04 13:19
@arunoda That might work but is quite complicated. Why not pass the object from one to the other, when we are server-side?

**Comment by arunoda** [comment] 2017-02-04 13:21
Okay I got it and that's hacky. So, what kind of core solution are you looking for?
Something like this? `getInitialContext()`?

**Comment by sedubois** [comment] 2017-02-04 13:40
@arunoda the problem right now seems that the response from `getInitialProps` is simply passed to `htmlEscape (https://github.com/zeit/next.js/blob/0b3db9173174c7b6ee5e1180441c34d43723982d/server/document.js#L88), so if there's an object in there it yields errors like `TypeError: Converting circular structure to JSON`.

When executing server-side, I guess htmlEscape shouldn't be used, there's no need to serialize then deserialize anything. It might even lead to a performance improvement, if it can be avoided.

**Comment by arunoda** [comment] 2017-02-04 15:23
Basically `getInitialProps()` should be pass serializable object. We have to serialize props and send it to the client. So, we have to use `htmlEscape` or something similar.

**Comment by sedubois** [comment] 2017-02-09 12:38
Yes, but we only need to serialize things when sending from server to client. There's no need to serialize when calling both getInitialProps and constructor on server side.

**Comment by steida** [comment] 2017-05-13 12:53
I believe a good solution is to avoid lazy stateful modules as much as possible and replace them with one [composition root](http://blog.ploeh.dk/2011/07/28/CompositionRoot/).

https://github.com/este/este/blob/next/lib/app.js#L24

**Comment by Sly777** [comment] 2017-09-14 21:12
Is there any updates (or tips/opinions) on this problem? Also on [RAN!](https://github.com/Sly777/ran) Boilerplate we are getting the same problem. I tried to figure it out on Apollo side but It didn't work. Example: [#130](https://github.com/Sly777/ran/issues/130)

**Comment by Timer** [comment] 2019-12-23 15:35
Closing as our apollo examples have been updated extensively since this issue was opened.

**Closed by Timer** 2019-12-23 15:35 UTC
Labels: Type: Needs Investigation, good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-30 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
