### ISSUE TITLE
with-apollo-and-redux-app  Could not find "store"

### ISSUE THREAD

**Issue by YUFENGWANG** [zeit/next.js#8148] opened 2019-07-28 10:20 UTC
# Bug report

with-apollo-and-redux-app Could not find "store"

## Describe the bug

Run the example `with-apollo-and-redux-app`,  when first get index page, data not loaded in ssr.
add `console.log(error)` in `withApollo.js`, here shows the error message: 

```javascript
Error { Invariant Violation: Could not find "store" in the context of "Connect(Index)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(Index) in connect options.
```

## To Reproduce

1, just follow the instructions in the  [repo](https://github.com/zeit/next.js/tree/canary/examples/with-apollo-and-redux)
2, add `console.log('Error', error)` in ` withApollo.js`,
3, yarn dev 
4, go to `localhost:3000` and you'll find error message as described above

## Expected behavior

Data get loaded in ssr correctly

## Screenshots

![image](https://user-images.githubusercontent.com/12859005/62005328-2e1cdc00-b164-11e9-83cb-369e26bbe254.png)

## System information

- OS: Ubuntu
- Browser : Chrome latest
- Version of Next.js: latest

## Additional context

N/A

**Comment by Timer** [comment] 2019-08-15 13:43
Closing as duplicate of https://github.com/zeit/next.js/issues/8375 which appears to have more traction.

**Closed by Timer** 2019-08-15 13:43 UTC

**Comment by balazsorban44** [comment] 2022-01-31 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
