### ISSUE TITLE
get tests running on Windows with Appveyor

### ISSUE THREAD

**Issue by bcoe** [zeit/next.js#261] opened 2016-11-15 18:46 UTC
I did some work in #259 in prep for this, e.g., pulling in `cross-env` and removing a few `&&` operators. There's probably a bit more work to be done, but it would be lovely to have this framework support Windows users.

**Comment by rauchg** [comment] 2016-11-16 00:37
+100

**Comment by rauchg** [comment] 2016-11-16 01:44
Just realized this is a duplicate of #94

**Closed by rauchg** 2016-11-16 01:44 UTC
