### ISSUE TITLE
404 error when using useFileSystemPublicRoutes = false

### ISSUE THREAD

**Issue by GennadyPonomarev** [zeit/next.js#2682] opened 2017-07-30 05:37 UTC
When `useFileSystemPublicRoutes` is set to false and there is no custom route for path, but page-based route exists, nextjs will render that page on client instead of 404.

Steps to reproduce:
1. Take `custom-server ` example
2. Replace `const app = next({ dev })` in `server.js` with 
`const app = next({
  dev,
  conf: {
    useFileSystemPublicRoutes: false
  }
})`
3. There's now no route for /
4. Start the server, hit localhost:3000
5. Server serves 404 (it flashes for a moment), then client takes over and re-renders `/pages/index.js` component. Browser console contains `Warning: React attempted to reuse markup`

So with this option behavior on server and client is not consistent, and it doesn't look like it should work this way.

**Comment by iest** [comment] 2017-09-11 16:13
I've also run into this issue.

This `useFileSystemPublicRoutes: false` seems to be useless — it [stops the server from setting up matching routes](https://github.com/zeit/next.js/blob/master/server/index.js#L236) for the file names, but the next client still attempts to use a `PageLoader` to [pull in the chunk](https://github.com/zeit/next.js/blob/master/client/index.js#L67) for the file-named `pathname` at runtime.

So when a request comes in for a named page e.g. `pages/foo.js`:

1. Server correctly 404s
1. `_error` component is correctly rendered
1. Next client attempts to fetch the chunk for `/foo` (this shouldn't happen)
1. Client-side re-renders, causing chaos

What should _probably_ happen is that when `_error` is rendered, it should have the same behaviour as if `pages/foo.js` doesn't exist.
This is tough though, as you will probably still want to load the `foo.js` chunk on another—valid—page.

One solution is that a flag is passed down to the error page, so it doesn't attempt to load a named chunk (`foo.js` in our case), but just the error chunk.
This will solve the flash-404, but this won't work for client-side routing (where the client wouldn't start from an error page).

But this would be fine as long as you don't make a bad link.

I'll give it a go and open a PR.

**Comment by egoist** [comment] 2017-12-07 09:06
Any updates on this? I'm using a custom server to redirect `/:username` to `./pages/user.js`,  but like what @GennadyPonomarev has described, it didn't work as expected.

**Comment by egoist** [comment] 2017-12-11 10:25
Hmm seems I did it wrong, this could fix my issue:

```js
server.get('/:username', (req, res) => {
    return app.render(req, res, '/user', { 
      username: req.params.username 
    })
  })
```

My app:

```js
<Link href="/user?username=egoist" as="/egoist">
  <a>egoist</a>
</Link>
```

**Comment by millette** [comment] 2017-12-27 04:17
I just ran into this as well, playing with one of the examples (ssr caching) to make it use koa.

In the example, /blog should be invalid, and /blog/first should work.

```js
useFileSystemPublicRoutes = false
```
is ignored by the client-side code.

I worked around the problem by renaming pages/blog.js to pages/blog2.js and fixing my code a bit, just to hide /blog a little better. So now at least /blog is a proper Next 404, but /blog2 is still available and it's a mix of my blog2.js content and formatted as a Next error page.

**Comment by millette** [comment] 2017-12-27 05:12
I've got a small example at <https://ssr-caching-koa-amateehwho.now.sh/> (and [source](https://github.com/millette/ssr-caching-koa)).

```useFileSystemPublicRoutes``` is set ```false``` in [next.config.js](https://github.com/millette/ssr-caching-koa/blob/master/next.config.js).

First, the actual problem can be seen at <https://ssr-caching-koa-amateehwho.now.sh/blog2>. Note that there is a ```/pages/blog2.js``` file.

A correct 404 is <https://ssr-caching-koa-amateehwho.now.sh/blog>. We have no ```/pages/blog.js``` file.

Actual posts are at <https://ssr-caching-koa-amateehwho.now.sh/blog/first> for example but I'm making use of a custom server to handle routing and map ```/blog/:id``` to the ```/pages/blog2.js``` file (passing the ```id``` parameter).

**Comment by rafaelalmeidatk** [comment] 2018-01-09 18:30
I solved this problem changing the end of the default export of `/client/index.js` to:

    if (props && props.statusCode === 404) {
      return emitter
    }

    router.subscribe(({ Component, props, hash, err }) => {
      render({ Component, props, err, hash, emitter })
    })

    const hash = location.hash.substring(1)
    render({ Component, props, hash, err, emitter })

    return emitter

So if the client receives 404 from the server, it stops trying to render the page again. I am not sure if this is the best approach as I am not familiar with the lib. To me, an even better solution would be to prevent the client from re-rendering error pages.

**Comment by fuzzthink** [comment] 2018-01-17 11:13
This seems to be a problem that needs to be addressed. Why no updates in over 6 months?

@rafaelalmeidatk  I don't get your code. The props variable doesn't seem to exist outside of subscribe function.

@iest  Any update on your fix?

thanks.

**Comment by rafaelalmeidatk** [comment] 2018-01-22 21:03
@fuzzthink These changes are here: https://github.com/zeit/next.js/blob/canary/client/index.js#L85

**Comment by thomhos** [comment] 2018-02-12 13:42
I'm currently still experiencing this in 5.0.0. 

@timneutkens I see you've added the label: good first issue. Do you have any pointers on where to look for this?

I'll try to submit a PR to fix this.

**Comment by timneutkens** [comment] 2018-02-12 14:31
@thomhos it's actually not easy to fix, removed the label 👍, I'd have to investigate it further to come up with a solution.

**Comment by thomhos** [comment] 2018-02-12 14:42
Ah, I just submitted a PR which seems to fix the problem for me locally. I guess we should close that as well?

**Comment by lizhiyao** [comment] 2018-02-27 14:36
I encountered the same problem in 5.0.0

**Comment by ex3ndr** [comment] 2018-03-05 12:27
Any updates? This is a very annoying issue.

**Comment by gcpantazis** [comment] 2018-03-06 01:13
My two cents on this (since I asked for `useFileSystemPublicRoutes` in the first place):

1) If you're using `useFileSystemPublicRoutes: false` and a custom router, (perhaps/IMO) it's up to you to guard against client-side navigation to 404'd pages. We do that by maintaining a `routes` file, and only ever generating links from those routes (we use `route-parser`). We also wrap `Link` so that anything passed to our wrapped `Link` goes through the routes file to find a match, and behaves as we expect if it doesn't find one (throw an error, in our case).

```
const Route = require('route-parser');

const routes = {
  exampleRoute: {
    route: new Route('/user/facing/route(/)'),
    template: 'file-system-route',
  },
};

module.exports = routes;
```

```
import React from 'react';
import { find } from 'lodash';
import Link from 'next/link';

import routes from '../../routes';

export default ({ href, children, passHref }) => {
  const matchingRoute = find(routes, definition => definition.route.match(href));

  if (matchingRoute) {
    return (
      <Link as={href} href={`/${matchingRoute.template}`} passHref={passHref}>
        {children}
      </Link>
    );
  }

  // Attempted to Link to a non-existant route, throw.
  throw new Error('Link: Bad route.');
};
```

I don't think this is super-unreasonable since you're using Next in a customized way; our company has had very few problems with that approach.

2) I think a bigger issue is around `popstate`; `Router` uses it directly to kick off navigation in the history, so you could a) go to a 404'd page on the server that corresponds to a filesystem route, b) click on a link on the 404 page to client-side navigate to a real page, and c) click "back" on the browser UI to see that page even though it should be 404ing.

One way to skirt this is to disable client-side navigation on your error pages, however is sensible in your situation, since if you're guarding against bad routes error pages should be the only way to enter a bad route into history.

Alternatively, we could add configuration to allow end-users to inject some functionality at the start of Router's `onPopState()` handler, which would allow you to test for an invalid destination before allowing Router to process the request.

The latter would be nice since it'd allow for a guarantee that the Router can't behave in ways that your custom routing doesn't like, but the former is something you could today do w/o a patch to the core library.

**Comment by gcpantazis** [comment] 2018-03-06 01:17
The issue of the development build refreshing a 404 / rendering the filesystem route is probably separate issue to think through... I've manually disabled a lot of the development mode stuff since it was handier for us to be able to have the same error pages on dev and prod. 🤔

**Comment by tmarshall** [comment] 2018-03-06 01:45
@gcpantazis The problem is that you can have something like

```
.
└── pages
    └── dashboard
    │   └── index.js
    └── landing
        └── index.js
```

And then have some custom routing like:

```js
router.get('/', (req, res) => {
  if (!req.isAuthenticated()) {
      return next.render(req, res, '/dashboard', req.query);
  }
  next.render(req, res, '/landing', req.query);
});
```

So that logged-out users see a landing view, and logged-in users see a dashboard.

This works fine when hitting `/` as expected.

But if any user goes to `/dashboard` or `/landing` they will see these views (though it will likely throw some errors along the way). The expected behavior is that by setting `useFileSystemPublicRoutes: false` the routes _must_ be defined manually, but they are still accessible via the browser.

**Comment by gcpantazis** [comment] 2018-03-06 05:08
For what it's worth, it looks like the case mentioned by most of the reporters here (i.e., server renders a 404s then flashes to an unexpected client-rendered page) was fixed incidentally as of `5.0.1-canary.5` (and specifically by #3749).

There's a few other cases that we could consider:

### Explicit navigation:

1) Create a `Link` that corresponds to a file-system route, even though you disabled it via `useFileSystemPublicRoutes`.
2) Click on that `Link`.
3) See the page, even though `useFileSystemPublicRoutes: false` implies you shouldn't.

### `popstate`:

1) Go to a URL that corresponds to a file-system route, even though you disabled it via `useFileSystemPublicRoutes`. Get a 404 from SSR.
2) Click on a link that takes you something else via client-side navigation.
3) Hit "back" on the browser.
4) You'll see the file-system route render instead of a 404.

Of the two, I'd say the first is maybe not a huge concern, since as you've opted to replace Next's default routing you should be responsible for client-side navigation to bad URLs. The second I think is a bigger issue (and perhaps can be a separate issue, since as far as I can tell most of the reporters' problems will be resolved in `5.0.1`).

**Comment by timneutkens** [comment] 2018-03-06 09:51
@thomhos made a PR for it: https://github.com/zeit/next.js/pull/3777

**Comment by gcpantazis** [comment] 2018-03-06 17:54
Rebased and tried that patch, @timneutkens. Unfortunately I think #3777 only fixes the issue described here because it breaks client-side altogether (removes the route to the bundles, i.e. `['/_next/:buildId/page/:path*.js']` if `useFileSystemPublicRoutes: false`).

I think I have an alternate solution; I'll put it together when I get to the office.

**Comment by thomhos** [comment] 2018-03-06 18:12
Hi guys, I realize now as well that #3777 was a very naive approach to the problem, I was hoping to kickstart it a bit and come to a solution together :)

Let me know if you need any help, I haven't looked into this for a while.

**Comment by gcpantazis** [comment] 2018-03-13 20:28
@timneutkens ping on ☝️ before it gets stale! 🙇

**Comment by timneutkens** [comment] 2018-03-14 13:08
The case mentioned in the issue topic is actually solved in next@canary. Thanks new 404 logic.

**Comment by timneutkens** [comment] 2018-03-14 13:19
Creating a new issue for @gcpantazis's comments on other cases.

**Closed by timneutkens** 2018-03-14 13:19 UTC
Labels: Type: Bug

**Comment by timneutkens** [comment] 2018-03-14 13:22
#4008
