### ISSUE TITLE
useEffect does not propagate state change to parent components in Next.js

### ISSUE THREAD

**Issue by kktam** [zeit/next.js#8680] opened 2019-09-09 18:37 UTC
# Bug report
useEffect does not propagate state change to parent components in Next.js

## Describe the bug
When SSR is disabled using useEffect, and a state change is applied to the state variable using useState. The Next.js framework report the following error.

```
index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Auth0Provider (at _app.js:37)
    in Provider (at _app.js:36)
    in Container (at _app.js:35)
```

An example of this bug is using the login pattern from auth0 as described in [https://auth0.com/docs/quickstart/spa/react/](https://auth0.com/docs/quickstart/spa/react/)

## To Reproduce

The following code from auth0 is used in the project to test the use of setState() inside useEffect() to push non-SSR object changes (auth0 library) to a SSR object (my NavBar and other React components).

[auth0 react-auth0-wrapper.js wrapper](https://gist.github.com/kktam/f4a5066ae33bf608cc013b5645f11fd9)

[NavBar.js that is used to display user information from auth0 library, which uses useEffect and setState to get user information](https://gist.github.com/kktam/754b986a8cd54d9204127e6c18502ba9)

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Open debugger on the browser
2. Follow steps in [https://auth0.com/docs/quickstart/spa/react/](https://auth0.com/docs/quickstart/spa/react/)
3. Click on auth0 popup and perform a successful login
4. Wait for redirect after login completed.
5. See error on debugger console

## Expected behavior

Expects the user object 

## Screenshots

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `NavBar`.
▶ 22 stack frames were collapsed.
_callee$
./react-auth0-spa.js:39
  36 | 
  37 |   console.log(user);
  38 | 
> 39 |   setUser(user);     
     | ^  40 | }      
  41 | 
  42 | setLoading(false);
View compiled
```

## System information

- OS: Windows 10 Pro
- Browser : Chrome
- Version of Next.js: 9.0.3

**Comment by sandrinodimattia** [comment] 2019-10-10 11:09
@kktam have you considered using this wrapper?

https://github.com/sandrinodimattia/use-auth0-hooks/tree/master/examples/nextjs-spa/

**Comment by kktam** [comment] 2019-10-15 15:02
@sandrinodimattia  I am currently testing use-auth0-hooks in my project. Basically it works in next.js 9.0.3 but I am having some issues with auth0 environment variables, as I am currently using both @zeit/next-css and @zeit/next-sass already in next.config.js. I have not yet found a way to add your environnment and other zeit plugins all together in 1 config file.

**Comment by kktam** [comment] 2019-10-15 15:04
My current next.config.js looks like this

```
const withCSS = require("@zeit/next-css");
const cssConfig = withCSS({ 
  cssModules: true,
  webpack: config => {  
    config.module.rules.push({
      test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
      use: {
        loader: "url-loader",
        options: {
          limit: 100000,
          name: "[name].[ext]"
        }
      }
    });  

    return config;
  },

  env: {
    AUTH0_DOMAIN: 'xyz.auth0.com',
    AUTH0_CLIENT_ID: 'abc',
    REDIRECT_URI: 'https://xyz.now.sh/',
    POST_LOGOUT_REDIRECT_URI: 'https://xyz.now.sh/'
  }
});

const withSass = require('@zeit/next-sass')
const sassConfig = withSass();

module.exports = Object.assign(
  cssConfig, { target: "serverless" },
  sassConfig, { target: "serverless" }  
);

```

**Comment by Timer** [comment] 2019-10-18 05:26
I'm closing this as support requests belong on our Spectrum.

However, I'm happy to report we've added an official Auth0 example here: https://github.com/zeit/next.js/tree/canary/examples/auth0

**Closed by Timer** 2019-10-18 05:26 UTC

**Comment by balazsorban44** [comment] 2022-01-31 02:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
