### ISSUE TITLE
Doc bug of Measuring performance

### ISSUE THREAD

**Issue by YanceyOfficial** [zeit/next.js#12817] opened 2020-05-13 03:16 UTC
# Bug report

## Describe the bug

The example of [Measuring performance](https://nextjs.org/docs/advanced-features/measuring-performance) as follow:

```ts
export function reportWebVitals({ id, name, label, value }) {
 ga('send', 'event', {
   eventCategory: `Next.js ${ label } metric`,
   eventAction: name,
   eventValue: Math.round(name === 'CLS' ? value * 1000 : value), // values must be integers
   eventLabel: id, // id unique to current page load
   nonInteraction: true, // avoids affecting bounce rate.
   },
}
```

correct example should be:

```ts
export function reportWebVitals({ id, name, label, value }) {
 ga('send', 'event', {
   eventCategory: `Next.js ${ label } metric`,
   eventAction: name,
   eventValue: Math.round(name === 'CLS' ? value * 1000 : value), // values must be integers
   eventLabel: id, // id unique to current page load
   nonInteraction: true, // avoids affecting bounce rate.
   })
}
```

**Comment by Timer** [comment] 2020-05-13 05:59
This has been fixed on canary. We'll update the docs site soon. Thanks!

**Closed by Timer** 2020-05-13 05:59 UTC

**Comment by balazsorban44** [comment] 2022-01-30 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
