### ISSUE TITLE
Using functional component as child of <Link/> doesn't work (button)

### ISSUE THREAD

**Issue by Vadorequest** [zeit/next.js#10305] opened 2020-01-28 14:40 UTC
# Bug report

## Describe the bug

When using `Link` (next/Link) with a functional component (button), it stops working.

Basically, the link is **ignored**. The button's click is properly triggered, but there is **no redirection** happening. 

## To Reproduce

I had the following (working) source code:

```tsx
<div>
            <Link // TODO sentry warning if < 2k chars https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers
              href={`/solutions?${QUERY_SIMULATION_KEY}=${encodeQueryParameter(serializeStudentSolutionContext(studentSolutionContext))}`}
            >
              <Button
                className="btn-border"
                onClick={(): void => {
                  setIsLoadingSolutionsPage(true);
                }}
              >
                {t('chatbotPage.solutionsFound.button', 'Voir les solutions')}
                {
                  isLoadingSolutionsPage ? (
                    <>
                      {' '}<AnimatedBubble />
                    </>
                  ) : null
                }
              </Button>
            </Link>
          </div>
```

Which I changed into the following (non-working) code:

```tsx

  const solutionsPageLink = `/solutions?${QUERY_SIMULATION_KEY}=${encodeQueryParameter(serializeStudentSolutionContext(studentSolutionContext))}`; // TODO sentry warning if < 2k chars https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

  const SolutionsPageButton = (): JSX.Element => {
    return (
      <Button
        className="btn-border"
        onClick={(): void => {
          // Stores the selected persona in the browser localStorage
          patchUserData({ persona: studentSolutionContext.persona });

          // Starts button's animation
          setIsLoadingSolutionsPage(true);
        }}
      >
        {t('chatbotPage.solutionsFound.button', 'Voir les solutions')}
        {
          isLoadingSolutionsPage ? (
            <>
              {' '}<AnimatedBubble />
            </>
          ) : null
        }
      </Button>
    );
  };

// ...

<div>
            {
              // XXX When displayed within an iframe, then open the link in a new page
              //  The point is to avoid displaying too much on the institutional website,
              //  but rather redirect the user to our platform so that they may benefit from all our services
              isInIframe ? (
                <a
                  href={solutionsPageLink}
                  target={'_blank'} // Open in a new tab while keeping the current tab open
                >
                  <SolutionsPageButton />
                </a>
              ) : (
                <Link
                  href={solutionsPageLink}
                >
                  <SolutionsPageButton />
                </Link>
              )
            }
          </div>
```

## Expected behavior

The `Link` component should redirect in both cases. 

## System information

- OS: [e.g. macOS, Windows] Mac
- Browser (if applies) [e.g. chrome, safari] Chrome
- Version of Next.js: [e.g. 6.0.2] 9.1

## Additional context

Related to https://github.com/zeit/next.js/issues/7915, couldn't find a solution even though I read https://nextjs.org/docs/api-reference/next/link, but there is not example when using a `<Button>`.

My easiest workaround would be not using a functional component, and thus duplicate my button's code.

Alternatively, if the `Link` component could behave link a `<a>` (through prop configuration), I wouldn't have to perform such ternary condition, and could just provide such prop dynamically (no duplicated code, no functional component)

**Comment by rafaelalmeidatk** [comment] 2020-01-28 15:02
You are not forwarding the ref in your function component: https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-function-component

**Comment by Vadorequest** [comment] 2020-01-28 15:33
I tried that and it didn't work either.

**Comment by Vadorequest** [comment] 2020-01-28 15:38
Here is my attempt with `ref`:

```tsx
const SolutionsPageButton = React.forwardRef(({}, ref) => {
    return (
      <Button
        ref={ref}
        className="btn-border"
        onClick={(): void => {
          // Stores the selected persona in the browser localStorage
          patchUserData({ persona: studentSolutionContext.persona });

          // Starts button's animation
          setIsLoadingSolutionsPage(true);
        }}
      >
        {t('chatbotPage.solutionsFound.button', 'Voir les solutions')}
        {
          isLoadingSolutionsPage ? (
            <>
              {' '}<AnimatedBubble />
            </>
          ) : null
        }
      </Button>
    );
  });

//...

<Link
                  href={solutionsPageLink}
                  passHref
                >
                  <SolutionsPageButton />
                </Link>
```

Same behaviour, link doesn't perform a redirection.

**Comment by Vadorequest** [comment] 2020-01-28 15:44
Well, doing this actually works, but it's unintuitive and ugly.

```tsx
               <Link
                  href={solutionsPageLink}
                >
                  {/* eslint-disable-next-line jsx-a11y/anchor-is-valid */}
                  <a>
                    <SolutionsPageButton />
                  </a>
                </Link>
```

Seems to work fine though.

**Comment by rafaelalmeidatk** [comment] 2020-01-28 15:48
You need to pass the other props to the button too, and call the `onClick` from `Link` in your handler:

```js
const SolutionsPageButton = React.forwardRef(({ onClick, props }, ref) => {
  return (
    <Button
      ref={ref}
      className="btn-border"
      onClick={(e): void => {
        // Stores the selected persona in the browser localStorage
        patchUserData({ persona: studentSolutionContext.persona });

        // Starts button's animation
        setIsLoadingSolutionsPage(true);

        onClick(e);
      }}
      {...props}
    >
      {t("chatbotPage.solutionsFound.button", "Voir les solutions")}
      {isLoadingSolutionsPage ? (
        <>
          {" "}
          <AnimatedBubble />
        </>
      ) : null}
    </Button>
  );
});
```

**Comment by Vadorequest** [comment] 2020-01-28 15:58
Thanks, it works as well.

TypeScript complains about `TS2339: Property 'onClick' does not exist on type '{ children?: ReactNode; }'` on SolutionsPageButton's parameters though. I didn't find what was the expected type on this, so I had to use `// @ts-ignore`.

**Comment by lfades** [comment] 2020-01-28 19:22
I'm closing this because this is not an issue with Next.js, thank you @rafaelalmeidatk

**Closed by lfades** 2020-01-28 19:22 UTC

**Comment by balazsorban44** [comment] 2022-01-30 14:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
