### ISSUE TITLE
Hook into app.render() and app.renderToHTML() without custom server

### ISSUE THREAD

**Issue by pmualaba** [zeit/next.js#8602] opened 2019-09-02 18:33 UTC
I would like to implement an LRU Cache like the following:
But it only works using a custom server. Is there a way to achieve the same in Next.js 9 without setting up a custom server?

```
const LRU = require('lru-cache')
const app = next({dev})
const ssrCache = {
    5: new LRU({
        max: 100 * 1024 * 1024 /* size (100 MB) using `return n.length` as length() function */,
        length: function(n, key) {
            return n.length
        },
        maxAge: 1000 * 60 * 5 /* 5 minutes */
    }),
    15: new LRU({
        max: 100 * 1024 * 1024 /* size (100 MB) using `return n.length` as length() function */,
        length: function(n, key) {
            return n.length
        },
        maxAge: 1000 * 60 * 15 /* 15 minutes */
    })
}

app.renderToCache = function renderToCache(req, res, actualPage, queryParams, cacheTime = 5) {
    if (cacheTime !== 5 || cacheTime !== 15) {
        cacheTime = 5
    }
    const key = req.url

    /** if page is in SSR cache, serve from cache */
    if (ssrCache[cacheTime].has(key)) {
        console.log('CACHE HIT')
        res.setHeader('x-cache', 'HIT')
        res.send(ssrCache[cacheTime].get(key))
    } else {
        /** else cache page */
        app.renderToHTML(req, res, actualPage, queryParams)
            .then(html => {
                console.log(`CACHE MISS - CACHE PAGE FOR ${cacheTime} MINUTES`)
                ssrCache[cacheTime].set(key, html)
                res.setHeader('x-cache', 'MISS')
                app.render(req, res, actualPage, queryParams)
            })
            .catch(error => {
                console.log('SSR CACHE ERROR', error)
            })
    }
}

```

**Comment by timneutkens** [comment] 2019-09-02 18:42
Closing as per the issue template:

https://github.com/zeit/next.js/issues/new/choose

https://github.com/zeit/next.js/issues/new?template=8.Question_about_next.md

**Closed by timneutkens** 2019-09-02 18:42 UTC

**Comment by balazsorban44** [comment] 2022-01-31 06:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
