### ISSUE TITLE
api route with graphql error

### ISSUE THREAD

**Issue by YUFENGWANG** [zeit/next.js#8043] opened 2019-07-21 06:34 UTC
# Bug report
api route with `apollo-server-micro` and `apollo-datasource-rest` error

## Describe the bug
I'm using  api routes with `apollo-server-micro` and `apollo-datasource-rest`, but this will cause 
```javascript
{ [TypeError: Class constructor RESTDataSource cannot be invoked without 'new']
  message:
   'Class constructor RESTDataSource cannot be invoked without \'new\'',
  locations: undefined,
  path: undefined,
  extensions:
   { code: 'INTERNAL_SERVER_ERROR',
     exception: { stacktrace: [Array] } } }
```

## To Reproduce

1.  [source code in codesandbox](https://codesandbox.io/s/github/YUFENGWANG/api-route-graphql-demo)
2. [source code in github](https://github.com/YUFENGWANG/api-route-graphql-demo) 
3. `git clone && yarn && yarn dev`
4. you will see errors in console as described above

## Expected behavior

api routes works with  `apollo-server-micro` and `apollo-datasource-rest` correctly
 
## Screenshots

![image](https://user-images.githubusercontent.com/12859005/61587827-e1655e00-abc3-11e9-9243-b75bb4911a5f.png)

## System information

- OS: Ubuntu 18.04
- Browser: chrome latest
- Version of Next.js: latest

## Additional context

no

**Comment by huv1k** [comment] 2019-07-26 17:31
Hey @YUFENGWANG this should be fixed in latest canary with this PR https://github.com/zeit/next.js/pull/7961

**Closed by huv1k** 2019-07-26 17:31 UTC

**Comment by YUFENGWANG** [comment] 2019-07-27 08:02
@huv1k great job

**Comment by balazsorban44** [comment] 2022-01-31 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
