### ISSUE TITLE
Hot-reload doesn't work on macOS 10.13.6

### ISSUE THREAD

**Issue by briefguo** [zeit/next.js#4814] opened 2018-07-21 04:38 UTC
## Describe the bug
Other project which use webpack, it works well（maybe I test not enough）
At first I want to new a project base on Next, but it's Hot-reload doesn't work, even I buy a new Mac😂

## To Reproduce
I follow the Guide
new a project
new a "./pages/index.js"
run `npx next dev`
change the file, Hot-reload doesn't work

## Expected behavior

When I have changed the file, page can show these lastest changes

## Screenshots
![image](https://user-images.githubusercontent.com/9976575/43031998-a3ed5626-8cdf-11e8-846d-0a79f00d0da3.png)
![image](https://user-images.githubusercontent.com/9976575/43032006-b20d9dce-8cdf-11e8-91d0-71cf53dac0ee.png)
![image](https://user-images.githubusercontent.com/9976575/43032030-2a61f9be-8ce0-11e8-8357-9fbfd77621c6.png)
![image](https://user-images.githubusercontent.com/9976575/43032020-11af9c14-8ce0-11e8-81b0-94f271ac4eed.png)
![image](https://user-images.githubusercontent.com/9976575/43032016-07a2a590-8ce0-11e8-98ac-895d117e1226.png)

## System information
 - OS: macOS 10.13.6
 - Browser (if applies) Chrome 67.0.3396.99
 - Version of Next.js: 6.1.1

**Comment by timneutkens** [comment] 2018-07-21 10:42
The problem is the `.www`, we ignore all dotfiles, there's a PR to fix this and another issue explaining this issue already. So I'm going to close this one. 

Here's the PR: https://github.com/zeit/next.js/pull/4589

Duplicate of #3156

**Closed by timneutkens** 2018-07-21 10:42 UTC
