### ISSUE TITLE
Type errors not reported during development when using Next.js and Typescript

### ISSUE THREAD

**Issue by ramraphael** [zeit/next.js#11325] opened 2020-03-24 13:50 UTC
# Bug report

## Describe the bug
When using Typescript with Next, type errors (variable re-assignments to a different type, accessing illegal properties on an object) are not reported during development.

## To Reproduce
1. Please clone [this repo](https://github.com/ramraphael/next-ts-typechecking-issue):
2. Notice that there are two type errors in `index.tsx` (commented out) and `pageTwo.tsx`.
3. Install dependencies and run `yarn dev`.
4. Uncomment the lines with type errors in `index.tsx` and re-run `yarn dev`.

## Expected behavior
1. For type errors to be reported in the terminal during development.
2. Please note that these errors do break the build process.

## System information
- OS: macOS
- Browser: Chrome
- Version of Next.js: 9.3.0

Thank you for all the hard work that goes into making Next.js! =D It's been indispensable for me and my team.

**Comment by dutchenkoOleg** [comment] 2020-05-14 06:49
After updating to 9.3.4 version, also i having same behavior!
strict mode is enabled in tsconfig.json but type errors not reported during development. And on build it break down!

**Comment by dutchenkoOleg** [comment] 2020-05-14 23:34
Found my problem described in #12735

**Comment by Timer** [comment] 2020-05-15 04:50
Closing as this is expected in 9.4 per #12735. Please read there for more info.

**Closed by Timer** 2020-05-15 04:50 UTC

**Comment by balazsorban44** [comment] 2022-01-30 05:04
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
