### ISSUE TITLE
Build problem. Link component

### ISSUE THREAD

**Issue by dmytropanontko** [zeit/next.js#9025] opened 2019-10-10 14:53 UTC
# Bug report

## Describe the bug

We have a navigate component in our company [site](https://keenethics.com/services-mobile-development). Which use `Link` and not in all places `Link` works.
## To Reproduce

1. In this page, you could click on:

![image](https://user-images.githubusercontent.com/37536815/66572922-83209980-eb7a-11e9-8fdf-5615acdcc046.png)

2. You can't visit this page. Here is a [code](https://github.com/keenethics/keenethics/blob/dev/components/content/navigation.js#L95-L116)

I think a problem with a build because I go to `node_modules/next/dist/client/link.js` and make auto formatter for the file. After that, all works fine.

Before `auto formatter` 

![image](https://user-images.githubusercontent.com/37536815/66580008-5ffbe700-eb86-11e9-896e-b99cafb32e39.png)

![image](https://user-images.githubusercontent.com/37536815/66580051-743fe400-eb86-11e9-9925-9cc9421bbb94.png)

## System information

- OS: Linux 18.04
- chrome
- Version of Next.js: `9.0.6`

**Comment by drj17** [comment] 2019-10-10 15:44
Same issue.  I can see it's adding the script tag with the correct page, but it never navigates.

**Comment by lfades** [comment] 2019-10-10 16:32
Closed as a duplicated of https://github.com/zeit/next-plugins/issues/282

This is a known next-css issue, I went to your repo and created a temporal fix by importing an empty scss file inside `pages/_app.js`:

```jsx
import React from 'react';
import App from 'next/app';
// Get around webpack deferred modules for CSS
import '../styles/empty.scss';

class MyApp extends App {
  render() {
    const { Component, pageProps } = this.props;
    return <Component {...pageProps} />;
  }
}

export default MyApp;
```

the above change made page navigations work again in the production build

**Closed by lfades** 2019-10-10 16:32 UTC

**Comment by dmytropanontko** [comment] 2019-10-11 11:02
@lfades 
Only one improvement, we need add `url` props:

```js
import React from 'react';
import App, { createUrl } from 'next/app';
// Get around webpack deferred modules for CSS
import '../styles/empty.scss';

class MyApp extends App {
  render() {
    const { Component, pageProps, router } = this.props;
    const url = createUrl(router);

    return <Component {...pageProps} url={url} />;
  }
}

export default MyApp;

```

**Comment by timneutkens** [comment] 2019-10-11 12:13
@dmytropanontko you should use `useRouter` or `withRouter` for this. `createUrl` is a private and deprecated method that will be removed in the future.

**Comment by balazsorban44** [comment] 2022-01-31 02:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
