### ISSUE TITLE
Deploying on apache / Can't login into spectrum

### ISSUE THREAD

**Issue by creativiii** [zeit/next.js#8140] opened 2019-07-27 16:37 UTC
Hi,

Very sorry about posting this here but I am completely unable to access Spectrum.chat. Every time I try to sign in I get an error page. Creating a new account doesn't seem to help.

I'm trying to deploy my app to an Ubuntu server running Apache. This is the first time I try to do this so I am a bit confused about the process. I was successfully able to clone my development app from github, install it and then build it. 

Running it starts it on my server with no problems, except I can only access it from `domain.com:8080`, which of course isn't very optimal. I tried changing the port to `:80` so that it would be displayed when accessing my domain, but that port is already being used by Apache so that can't be done.

At this point I'm not sure if this is a problem with Nextjs, Apache or my DNS. I have never done this before so I'm not even entirely sure what to Google to fix it.

How do I display my app without showing my port at the end of my domain?

**Comment by ijjk** [comment] 2019-10-10 21:41
Hi, it sounds like you would benefit from a service like [ZEIT Now](https://zeit.co) which takes care of this stuff for you. The configuration process for setting up Apache will be very specific to your environment and goes beyond the scope of a Next.js issue. 

If you are set on using Apache you might want to try exporting your app or setting up [Apache to reverse proxy](https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension) to your Next.js application running in `next start` mode

I'm going to close this since it's not really an issue with Next.js.

**Closed by ijjk** 2019-10-10 21:41 UTC

**Comment by balazsorban44** [comment] 2022-01-31 02:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
