### ISSUE TITLE
TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by ooade** [zeit/next.js#910] opened 2017-01-28 12:22 UTC
This occurs only when including preact.

Steps to reproduce:
- Run the [preact example](https://github.com/zeit/next.js/tree/master/examples/using-preact) app
- Add nextjs's Head helper element to a page
- Give the page a title; then that happens.

The problem arose from the header-manager's method([updateTitle](https://github.com/zeit/next.js/blob/master/client/head-manager.js#L45)). Preact's VNode exposes just attributes to props with no children, the VNode itself exposes children.

**Comment by timneutkens** [comment] 2017-01-28 18:26
I'll have a look 👍

**Comment by timneutkens** [comment] 2017-01-28 18:46
Ok I get what you mean. We read `component.props.children` which is set in `React`, but not in `preact`. in `preact` it's `component.children` Looks like something that would have to be added to preact-compat. I'll check that now 👍

**Comment by timneutkens** [comment] 2017-01-28 18:52
Looks like it's handled here already 🤔 https://github.com/developit/preact-compat/blob/master/src/index.js#L109

@developit could you have a look? ❤️

**Comment by developit** [comment] 2017-01-28 19:16
@timneutkens I just checked and I'm not sure I can reproduce the above issue - here's the JSFiddle I set up:  https://jsfiddle.net/developit/n144pt7m/

I might be going about the repro wrong though!

FWIW I'm not sure [L45 of `<HeadManager>`](https://github.com/zeit/next.js/blob/master/client/head-manager.js#L45) accounts for the case where a single element is passed.  In React (and thus in preact-compat), that will result in `props.children` being a reference to the Virtual DOM Element, rather than an Array.

That is to say, this line:

```js
typeof children==='string' ? children : children.join('')
```

...if rendered like this:

```js
<HeadManager><AnyThing /><HeadManager>
```

... will throw an exception, because `children` is an Object (VNode), not a String or Array.
```

**Comment by timneutkens** [comment] 2017-01-28 19:32
That is a fair point, we will have to update that. The most minimal example where I can reproduce this is this: https://github.com/timneutkens/next-issue-910. In this case, `children` is undefined. That's why it logs an error.

**Comment by developit** [comment] 2017-01-28 19:52
Ah perfect @timneutkens that gives me a great repro.  It looks like the [bit that adds `props.children`](https://github.com/developit/preact-compat/blob/master/src/index.js#L109) is only being applied to Component vnodes, not element VNodes.  We can remedy that quickly :)

**Comment by timneutkens** [comment] 2017-01-28 20:05
Much appreciated ❤️

**Comment by developit** [comment] 2017-01-28 21:36
Should be fixed in `preact-compat@3.12.0`

**Comment by timneutkens** [comment] 2017-01-28 21:46
Thank you very much @developit 👍 💯

**Closed by timneutkens** 2017-01-28 21:46 UTC
Labels: Is Upstream, Status: In Progress

**Comment by ooade** [comment] 2017-01-28 22:33
Thanks @developit

**Comment by developit** [comment] 2017-01-28 23:12
Just confirmed using your repro (thanks again btw!) that it is in fact working now:
<img width="280" alt="screen shot 2017-01-28 at 6 12 20 pm" src="https://cloud.githubusercontent.com/assets/105127/22400512/53c6293c-e585-11e6-988f-f91a0de24e49.png">

**Comment by timneutkens** [comment] 2017-01-29 10:33
@developit confirmed it too ❤️

**Comment by developit** [comment] 2017-01-29 17:05
Great, thanks a million for surfacing this Tim!

**Comment by atuttle** [comment] 2017-09-26 03:13
I am seeing this with:

- React 15.6.1
- React DOM 15.6.1
- Next.js 3.2.2

I want to have a page title containing a bullet character (`&bull;`). If I do:

    <Head><title>foo &bull; bar</title></Head>

... then the title appears as "foo &amp;bull; bar" because the `&bull;` gets escaped to `&amp;bull;`.

When I switch to: 

    <title dangerouslySetInnerHTML={{ __html: "foo &bull; bar" }} />

... the title is set correctly, but this error starts appearing in the browser console.

**Comment by atuttle** [comment] 2017-11-09 15:04
ping @timneutkens @rauchg

**Comment by SomiFrame** [comment] 2018-01-31 03:41
I have the same issue when I pass a custom component as children to another component, how could I fix it. 

**here is the child**

`<Layout right_content={right_content} Router={this.props.Router}>
                    <Carousel lists={this.state.carouselItems}/>
                    <label className="page-title">
                        {'blablabla...'}
                    </label>
                    <News />
                    <ListItem listItems={this.state.listItems} />
                </Layout>
`
**here is the Layout**
`class Layout extends Component {
  constructor(props) {
    super(props)
  }
  render() {
    return (
      <div>
        <Head>
          <title>{this.props.title}</title>
          <meta charSet='utf-8' />
          <meta name='viewport' content='initial-scale=1.0, width=device-width' />
          <style dangerouslySetInnerHTML={{ __html: LayoutCss }} global="true" />
        </Head>
        <Header />
        <div className="container">
          <div className="container-left">
            <Navigate lists={lists} Router={this.props.Router}/>
          </div>
          <div className="container-middle">
            {this.props.children}
          </div>
          <div className="container-right">
            <SearchBox />
            {this.props.right_content}
          </div>
        </div>
        <footer>
        </footer>
      </div>
    )
  }
} `

**Comment by donaminos** [comment] 2018-03-09 14:21
@atuttle  I am running on the same issue with updating title tag. Did you find a fix or workaround please ? tanks in adavnce

**Comment by Irrelon** [comment] 2018-05-02 17:27
I'm seeing this issue whenever I navigate on the client-side. If I do a refresh it doesn't occur and the title of the page is correct.
