### ISSUE TITLE
Catch all route `foo/[...slug].tsx` also match path `foo`

### ISSUE THREAD

**Issue by rolandjohann** [zeit/next.js#12012] opened 2020-04-18 21:42 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Currently catch all routes can be defined by a file like `foo/[...slug].tsx` and matches a path like `http://next.js/foo/bar`. We use nextjs in combination with react-router to support nested views. So our use case requires the path `http://next.js/foo` to be matched by `foo/[...slug].tsx`.

## Describe the solution you'd like
be able to setup the page via `foo/[...slug].tsx` and resolve uris like `http://next.js/foo`

## Describe alternatives you've considered
As workaround we setup `foo.tsx` to resolve `http://next.js/foo` and created a symbolic link of `foo.tsx` to `foo/[...slug].tsx`.

## Additional context
We decided to integrate react-router because our nested views are very dynamic and an implementation with nextjs only is too complex (maintaining this, too).

**Comment by Janpot** [comment] 2020-04-19 08:29
Duplicate of https://github.com/zeit/next.js/issues/10488.

**Closed** 2020-04-19 13:07 UTC

**Comment by balazsorban44** [comment] 2022-01-30 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
