### ISSUE TITLE
More inclusive documentation for next.js

### ISSUE THREAD

**Issue by vcapretz** [zeit/next.js#9537] opened 2019-11-26 16:55 UTC
Hey folks 👋 

I've seen a couple of cases of words like "simple", "easily" and "just" (and some other variations) in your docs. @carolstran explained in her blog post [How to remove condescending language from documentation](https://dev.to/meeshkan/how-to-remove-condescending-language-from-documentation-4a5p) why that can make some people feel frustrated and isolated while reading documentation with these words. 

If you agree and allow me to proceed I can open a PR adapting the docs by removing these words or rephrasing the sentences where they are used.

For more reference on this topics you can also check [Jim Fisher's Don't Say Simply talk from Write the Docs Prague 2018](https://www.youtube.com/watch?v=gsT2BBWBVmM)

Thank you in advance and please let me know your thoughts about this 😄

**Comment by timneutkens** [comment] 2019-11-26 18:31
We're updating the docs right now so it might be good to do a pass through it after that is released 🚀

**Comment by vcapretz** [comment] 2019-11-26 19:05
Perfect! I’ll keep an eye on the updates then, let me know if I can help somehow 😃

**Comment by Timer** [comment] 2019-11-26 22:27
You can follow this PR: #9301!

**Comment by timneutkens** [comment] 2020-01-03 01:12
@vcapretz fyi the PR was landed and available on nextjs.org/docs.

**Comment by vcapretz** [comment] 2020-01-04 19:57
thanks @timneutkens, I'll look into that and send a PR :D

**Comment by Timer** [comment] 2020-04-15 05:09
BTW, this has landed now!

**Comment by vcapretz** [comment] 2020-04-17 13:50
On it! sorry for the long long wait 😅and thank you very much for keeping me updated! 

I ran `npx alex` in the repo and now going through its suggestions 😄

**Closed** 2020-04-17 14:26 UTC
Labels: Documentation

**Comment by balazsorban44** [comment] 2022-01-30 07:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
