### ISSUE TITLE
core-js and regenerator-runtime is missing for next-server

### ISSUE THREAD

**Issue by sheerun** [zeit/next.js#7011] opened 2019-04-11 17:21 UTC
# Bug report

This seems to happen only on current prereleases when deploying to now.sh (I use `@now/node` builder). It happens when next is compiled in normal server mode (i.e. not serverless, but maybe it also happens in serverless mode).

## Describe the bug

```
2019-04-11T17:07:57.771Z  { Error: Cannot find module 'core-js/library/fn/json/stringify'
                              at Function.Module._resolveFilename (module.js:547:15)
                              at Function.Module._load (module.js:474:25)
```

So it seems that core-js is missing from dependencies of compiled project. Maybe it would be good idea to add core-js as dependency of e.g. next-server (I have next in devDependencies and next-server in dependencies, because next itself has too heavy dependencies for deployment).

**Comment by sheerun** [comment] 2019-04-11 17:25
It seems it also happens for current stable release (8.0.4)

**Comment by sheerun** [comment] 2019-04-11 17:47
Maybe I should also mention I'm using custom server code. Here's the file

```es6
const express = require('express')
const next = require('next-server')
if (!process.env.NODE_ENV) {
  process.env.NODE_ENV = 'production'
}
if (process.env.NODE_ENV === 'development') {
  next = require('next')
}

const server = express()

const dev = process.env.NODE_ENV !== 'production'
const nextServer = next({ dev })
const handler = nextServer.getRequestHandler()

server.use((req, res) => {
  handler(req, res)
})

module.exports = server
```

**Comment by MarchWorks** [comment] 2019-04-12 18:45
Do `const next = require('next')`

**Comment by czebe** [comment] 2019-04-12 19:07
I think the reason for using `next-server` is to minimise production deployment size. Requiring `next` results in a much larger container image size.

**Comment by Timer** [comment] 2019-04-13 01:13
@sheerun please provide a full reproduction (git repository). Thanks!

**Comment by ElvenMonky** [comment] 2019-04-13 20:23
@Timer [https://github.com/ElvenMonky/next.js/tree/canary/examples/custom-server-express](https://github.com/ElvenMonky/next.js/tree/canary/examples/custom-server-express)

**Comment by ElvenMonky** [comment] 2019-04-13 23:00
so the fix is to add `"core-js": "2.6.5"` and `"regenerator-runtime": "^0.13.2"` to dependencies. The bigger problem then is dependency on `next/router`. Which is a part of `next` itself rather then `next-server`

**Comment by sheerun** [comment] 2019-04-14 08:59
Like @ElvenMonky mentioned the reproduction is just standard custom-server with next replaced by next-server. He is also right that core-js and regenerator-runtime are just first stumbling blocks. More prominent is missing `next/router` because it is not bundled when using "server" target.

**Comment by sheerun** [comment] 2019-04-14 09:00
I think `next-transpile-modules` should be built-in experience of next instead of plugin

**Comment by azizhk** [comment] 2019-04-18 19:36
I fixed the dependency problem by adding `@babel/runtime-corejs2` to my dependencies to have consistency with `next/babel`
https://github.com/zeit/next.js/blob/90e455791ee63e2697c9de90a0e648e5d1e42d44/packages/next/build/babel/preset.ts#L84-L85

Also:
> The bigger problem then is dependency on next/router. Which is a part of next itself rather then next-server.

I did not have this problem. I swapped `next` with `next-server` and it worked. Did not set `serverless: true` btw.

**Comment by dvakatsiienko** [comment] 2019-04-24 08:56
@azizhk your fix with adding `@babel/runtime-corejs2` to dependencies worked for me aswell. but it looks a bit hacky. would be nice to have a proper fix in `next.js` source code for this issue.

**Comment by azizhk** [comment] 2019-05-09 06:20
> I have next in devDependencies and next-server in dependencies, because next itself has too heavy dependencies for deployment

Just a heads up to those reading this issue, this might not work if you have [Runtime Configuration](https://github.com/zeit/next.js/#runtime-configuration) because that requires `next/config` and for that `next` would have to be in `dependency` list in package.json.

**Comment by timneutkens** [comment] 2019-08-10 13:02
I'm going to close this as it's directly using `next-server` which is not a public api.

**Closed by timneutkens** 2019-08-10 13:02 UTC

**Comment by balazsorban44** [comment] 2022-01-31 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
