### ISSUE TITLE
Add a configuration flag to disable integrated type checker

### ISSUE THREAD

**Issue by Timer** [zeit/next.js#8331] opened 2019-08-11 22:57 UTC
Some users don't want to leverage Next.js' integrated type checking and prefer to do it manually.

While this reduces visibility during development, some users may prefer it.

This flag would only disable the forked type checking process (dev and build). `tsconfig.json` generation would still be mandatory.

---

Please provide a proposal before implementing this.

**Comment by timneutkens** [comment] 2019-08-11 23:10
Just for reference I decided we need to allow this because there are cases where a company does `tsc` / `eslint` in a separate thread (eg with circleci workflows).

**Comment by fabb** [comment] 2019-08-12 05:31
I‘d be for nit just allowing to toggle it on/off, but also pass custom settings, as it would be nice if eslint/tslint could be activated for the fork-ts-checker-plugin.
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/master/README.md#eslint

**Comment by Janpot** [comment] 2019-08-12 06:13
After thinking a bit more about my comment [here](https://github.com/zeit/next.js/issues/7848#issuecomment-509967269), I've come to terms that this is a typescript issue and not a next.js issue. In case anyone is interested, there's a related ticket here: https://github.com/microsoft/TypeScript/issues/13408. In short: typescript should be able to emit warnings instead of errors for linting errors.

**Comment by drewlustro** [comment] 2019-08-15 03:40
I would also love to be able to turn this off in the name of compilation speed. Upon build, we run our code through `tsc` anyway, so it's not practical to have Next run type checking during each file edit.

**Comment by Timer** [comment] 2019-08-15 13:24
@drewlustro Please note Next.js' TypeScript integration does not slow down compilation in any way. You'll see no speed benefits by turning it off.

**Comment by drewlustro** [comment] 2019-08-15 17:25
> @drewlustro Please note Next.js' TypeScript integration does not slow down compilation in any way. You'll see no speed benefits by turning it off.

I understand that, but it's presence still consumes CPU cycles on another thread, yes? My fans whirl a lot on Next 7. Next 9 is already a huge improvement, but I'm only trying to mitigate workstation load.

**Comment by Timer** [comment] 2019-08-15 18:19
@drewlustro the type checking is fully incremental, so it's hardly noticeable after initial app boot.

**Comment by chrisblossom** [comment] 2019-08-15 18:24
I'm very grateful the next.js team has decided to allow this to be disabled pending PR. I think the majority of these comments are off-topic and should be marked as such (including this one).

**Comment by chrisblossom** [comment] 2019-08-15 18:31
This is a wild idea and probably belongs in its own issue. What if next.js had a browser addon that would display type / lint errors in a non-intrusive way (outside of the actual webpage, like [redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension) does) plus any other relevant  information specific to next.js (such as if it is a static page), and toggle certain settings (such as this one).

I think this could further level-up next.js above their competition.

**Comment by Timer** [comment] 2019-08-15 18:50
@chrisblossom please dump your thoughts in https://github.com/zeit/next.js/issues/8065

**Comment by chrisblossom** [comment] 2019-08-15 19:04
@Timer is that what you had in mind? Please delete this comment if so

**Comment by jeremy-coleman** [comment] 2019-08-25 03:47
here
https://github.com/jeremy-coleman/next-tsc-proposal/blob/master/start.js

that runs a prebuild step because im not letting next see my tsc files(this also fixes re-exporting types because babel doesn't see them). if you want an enterprise solution that supports typescript, you need to use typescript. Anyway, just try it out

**Comment by kachkaev** [comment] 2019-10-17 14:22
@Timer will you accept a PR that adds this to Next config?

```js
{
  typescript: {
    transpileOnly: true // same name as in ts-node --transpile-only
  }
}
```

**Comment by timneutkens** [comment] 2019-10-18 15:14
@kachkaev sounds good to me!

**Comment by kachkaev** [comment] 2019-10-19 11:01
👀 https://github.com/zeit/next.js/pull/9138

**Closed** 2019-10-28 18:02 UTC
Labels: help wanted

**Comment by balazsorban44** [comment] 2022-01-30 17:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
