### ISSUE TITLE
how can I use next in pm2?

### ISSUE THREAD

**Issue by ckken** [zeit/next.js#109] opened 2016-10-27 10:37 UTC

**Comment by Florian-R** [comment] 2016-10-27 10:47
Duplicate of #83

**Comment by nkzawa** [comment] 2016-10-27 11:23
I think it's not duplicate if it's about https://github.com/Unitech/pm2 ?

**Comment by Florian-R** [comment] 2016-10-27 11:49
Good catch @nkzawa, must have read too quickly. Sorry @ckken!

**Comment by nodegin** [comment] 2016-10-28 00:50
Maybe Unitech/pm2#1317

**Comment by nodegin** [comment] 2016-10-28 00:56
```sh
# for development
pm2 start npm --name "next" -- run dev

# for production
npm run build
pm2 start npm --name "next" -- start
```

**Comment by nkzawa** [comment] 2016-10-29 16:19
@nodegin thanks!

**Closed by nkzawa** 2016-10-29 16:19 UTC
Labels: question

**Comment by Lizhooh** [comment] 2017-09-22 01:40
The above method is wrong on my computer (win7). I don't know why.

Now my solution is...

```js
"scripts": {
    "pm2-next": "next build && pm2 start ./node_modules/next/dist/bin/next-start",
    "pm2-next-cluster": "next build && pm2 start ./node_modules/next/dist/bin/next-start -i max",
}
```


use:  npm run pm2-next
