### ISSUE TITLE
Automatically configure webpack to handle `tsconfig.json`'s `baseUrl` and `paths`

### ISSUE THREAD

**Issue by liamdanielduffy** [zeit/next.js#7779] opened 2019-07-08 12:45 UTC
# Bug report

## Describe the bug

Reproduction here: https://github.com/liamdanielduffy/next-9-baseurl-reproduction

I've setup a simple Next.js project using v 9.0.0, with a tsconfig.json generated by Next

I've added the 'baseUrl' compiler option to 'tsconfig.json' in the root of my repository. The baseUrl is `./` since I want paths in my Next app to resolve relative to the root of my repository. 

I've created a test import in `pages/index.tsx` which imports a string constant.

When I run this locally with `now dev`, I get the following error:

`ModuleNotFoundError: Module not found: Error: Can't resolve 'constants/test'`

I've also deployed this to Now under this project: `/liamdanielduffy/app-workflow/6ijvjnt5c`

I get the same error during build:

```
./pages/index.tsx
Module not found: Can't resolve 'constants/test' in '/tmp/28475d91/pages'
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone the provided repository
2. Run `now dev` in the root to see the local build error
3. Run `now` to deploy and see the build error in the Now environment

## Expected behavior

Next should be able to resolve modules imported within `.ts` or `.tsx` files relative to the `"baseUrl"` set in `"compilerOptions"` of tsconfig.json

**Comment by Timer** [comment] 2019-07-08 15:32
Hey @liamdanielduffy! Next.js currently doesn't translate `baseUrl` nor `paths` to webpack configuration.

For now, please customize your webpack configuration using `next.config.js`. We'll get this implemented soon!

**Comment by liamdanielduffy** [comment] 2019-07-09 08:13
Awesome :) thanks @Timer!

**Comment by JerryGreen** [comment] 2019-07-22 17:33
Holy moly this will be incredible to seeing this! I mean, I love you guys, the NextJS team. For removing all these unnecessary configs, etc. - that's cool

**Comment by timneutkens** [comment] 2019-11-09 22:30
Feel free to implement this!

**Comment by danteissaias** [comment] 2019-12-28 03:42
+1

**Closed** 2020-03-23 14:45 UTC
Labels: Type: Feature Request

**Comment by Timer** [comment] 2020-03-23 15:26
This is now supported in the latest Next.js canary version: `next@^9.3.2-canary.2`.

**Comment by balazsorban44** [comment] 2022-01-30 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
