### ISSUE TITLE
SyntaxError: Unexpected identifier on ES6 import

### ISSUE THREAD

**Issue by httpiago** [zeit/next.js#4798] opened 2018-07-18 15:09 UTC
I'm trying to use [Framework7-react](https://github.com/framework7io/Framework7) with NextJS and I've cloned this [repository here](https://github.com/framework7io/framework7-template-react) that works normally using the react-scripts but I made some simple modifications to be compatible with Next and this error appeared that I can not fix:

![image](https://user-images.githubusercontent.com/3616259/42890284-d0abd87c-8a82-11e8-9da6-57e04217f1d3.png)

The problem is not with framework7, the file is written in the ES6 standard. I do not know if I have to configure something in Next, in the webpack or babel (I think it's in it) and would like some help.

Thank you in advance for trying to help!

**Comment by wolfsky7** [comment] 2018-08-27 07:50
the window  not existed on server.so just  change window to win in framework7.js 
![image](https://user-images.githubusercontent.com/1808416/44647544-e69c4600-aa10-11e8-8b74-30590f98ac62.png)

**Comment by svencowart** [comment] 2018-09-12 01:15
My goal is to implement material design components within next.js and I am experiencing this same issue.

Here is my exact error:

```
/home/svencowart/dev/arete/site/node_modules/@material/top-app-bar/index.js:24
import MDCTopAppBarAdapter from './adapter';
       ^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.@material/top-app-bar (webpack:/external "@material/top-app-bar":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 85f9a7f6ec944291a11f:21:0)
    at Object../components/header.jsx (/home/svencowart/dev/arete/site/.next/server/bundles/pages/index.js:81:80)
    at __webpack_require__ (webpack:/webpack/bootstrap 85f9a7f6ec944291a11f:21:0)
    at Object../pages/index.jsx (/home/svencowart/dev/arete/site/.next/server/bundles/pages/index.js:189:77)
    at __webpack_require__ (webpack:/webpack/bootstrap 85f9a7f6ec944291a11f:21:0)
```

**Comment by httpiago** [comment] 2018-09-12 01:51
I still do not understand this error right, I used another library of components and it worked perfectly. What I understood is that NextJS does not transpile the codes inside the folder node_modules, I tried to use a plugin to circumvent this but without success. I still have not given up

**Comment by saintego** [comment] 2018-10-17 01:17
I'm getting same error when trying to run https://github.com/zeit/next.js/tree/master/examples/with-react-native-web with react-native-material-textfield or any other react-native component

**Comment by timneutkens** [comment] 2018-10-17 11:34
Going to close this as it doesn't follow the issue template and there's no minimal reproduction that uses Next.js.

**Closed by timneutkens** 2018-10-17 11:34 UTC

**Comment by Shomeis-Eskandari** [comment] 2018-11-21 11:35
download f7-and-nextjs.zip
https://www.bountysource.com/issues/63736590-ssr

**Comment by httpiago** [comment] 2018-11-21 17:22
@Shomeis-Eskandari I did this zip and it has some problems when some file is edited. I have already reported in the Framework7 repository.

**Comment by StupidSexyJake** [comment] 2019-03-04 06:38
Did you ever get this working? I'm having the same issue

**Comment by Vinlock** [comment] 2019-03-16 05:42
Having the same issue here. I'll bookmark and reply if I find a solution. Not sure how this happened.

**Comment by bfreeds** [comment] 2019-07-13 22:32
I'm getting the same issue when using https://github.com/kmwhelan93/react-geocoder-autocomplete.  
![Screen Shot 2019-07-13 at 5 31 34 PM](https://user-images.githubusercontent.com/5316367/61177166-1ce4a480-a594-11e9-8860-150ba6c86c7d.png)

**Comment by flearsmedia** [comment] 2019-07-31 20:27
Was anyone able to solve this?

**Comment by talaikis** [comment] 2019-08-03 08:08
I had this issue with `react-spinners`. The solution, working with 8.1.1 and 9.0.3:

```
const withTM = require('next-transpile-modules')
module.exports = withTM({
  transpileModules: ['react-spinners']
})
```

**Comment by balazsorban44** [comment] 2022-01-31 09:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
