### ISSUE TITLE
Can't resolve next/dynamic when deploy in now.sh?

### ISSUE THREAD

**Issue by ibraelillo** [zeit/next.js#9148] opened 2019-10-21 09:49 UTC
# Question about Next.js

Hi all, 

I'm trying to deploy next with Now, and although everything runs ok on development using now dev, when I deploy I get the error "**Can't resolve next/dynamic**". 

I was facing an issue related to @babel/runtime-corejs2 not being resolved. I've added to my dependencies and now I got this error from the title. 

I've seen a comment from @timneutkens in https://github.com/zeit/next.js/issues/6906#issuecomment-480259576  about the fact that next.config is not loaded when target is "serverless". 

So, my question is: Is it possible then that the aliases defined by next for next/router, next/dynamic and so on, stops working because of this? Here's the screenshot from the error, I've done a console log from the config.resolve.alias to check that aliases are right there. 

<img width="1037" alt="Captura de pantalla 2019-10-21 a las 12 01 15" src="https://user-images.githubusercontent.com/3011753/67196160-8decf100-f3fa-11e9-9dfe-564bb8abaffa.png">

**Comment by Timer** [comment] 2019-10-21 14:36
Hi, we'll need to see your full project to find the error in your configuration. I'll close this issue until it's provided, thanks!

**Closed by Timer** 2019-10-21 14:36 UTC

**Comment by balazsorban44** [comment] 2022-01-31 01:26
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
