### ISSUE TITLE
import {Link} from "next"; makes app stuck in [ wait ]  compiling ...

### ISSUE THREAD

**Issue by JorgeSivil** [zeit/next.js#11866] opened 2020-04-13 23:35 UTC
# Bug report

When using

`import {Link} from "next";`

At the top of the file, the App stops working.

## Describe the bug

I don't know if this is really a bug, I was using my IDE and made it automatically make the import by pressing ALT+Enter.
I hope this report can help you see why the compiler got stuck, and change it to have a better error output.

## To Reproduce

Use `import {Link} from "next";` in a page, linking to another page.

## Expected behavior

Should compile and not be stuck in Compiling...

## System information

```
"dependencies": {
    "@zeit/next-sass": "^1.0.1",
    "next": "^9.3.4",
    "node-fetch": "^2.6.0",
    "node-sass": "^4.13.1",
    "react": "^16.13.0",
    "react-dom": "^16.13.0",
    "webpack": "^4.42.1"
  }
```

## Additional context

By doing `import Link from "next/link";` the problem got sorted.

**Comment by ijjk** [comment] 2020-04-14 00:21
Hi, the build getting stuck from `import {...} from 'next'` should be resolved by https://github.com/zeit/next.js/pull/11733. Are you still seeing your build get stuck with the latest canary of Next.js `v9.3.5-canary.9`?

**Comment by Timer** [comment] 2020-04-15 05:45
Closing as we test this behavior now.

**Closed by Timer** 2020-04-15 05:45 UTC

**Comment by balazsorban44** [comment] 2022-01-30 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
