### ISSUE TITLE
Loadd css chunks on page changing

### ISSUE THREAD

**Issue by kodermax** [zeit/next.js#7415] opened 2019-05-23 18:35 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
I would like to when you go to another page in addition to the script loaded css chunk that refers to this page

## Describe the solution you'd like
I think when loading a page, in addition to loading a script, add logic for loading a css file

https://github.com/zeit/next.js/blob/78783477e0630ddcc1aae508d63941e2f858868c/packages/next/client/page-loader.js#L75

**Comment by hugotox** [comment] 2019-05-23 23:45
just curious why would you want to do that? By default next uses styled-jsx which is bundled within the js chunks so it's already code splitted

**Comment by kodermax** [comment] 2019-05-24 11:20
> just curious why would you want to do that? By default next uses styled-jsx which is bundled within the js chunks so it's already code splitted

I think this is a bad approach for performance.
Increase parsing time and file size.

**Comment by timneutkens** [comment] 2019-05-25 09:37
Going to close this as there is a similar issue on next-plugins.

**Closed by timneutkens** 2019-05-25 09:37 UTC

**Comment by balazsorban44** [comment] 2022-01-31 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
