### ISSUE TITLE
React too eagerly sanitizes HTML entities

### ISSUE THREAD

**Issue by ivan-kleshnin** [zeit/next.js#6718] opened 2019-03-19 14:03 UTC
**Now-2** and **Next-8** require us to drop `server.js`-based approach to serve SSR in production, and replace it with lambdas and route configs. I fully understand the reasoning behind this and I don't question it. Hovewer, the `server.js` file was useful not only to apply routing but to inject middlewares! Middlewares were necessary, for example, to fix a bunch of annoying problems with React. 

1) React title encodes HTML entities

https://github.com/facebook/react/issues/13838
https://github.com/facebook/react/issues/3879

See fix-1 below.

2) Linebreaks in meta tags and stuff like that

See fix-2 below.

```js
import Express from "express"
import Interceptor from "express-interceptor"
import {AllHtmlEntities} from "html-entities"

let ent = new AllHtmlEntities()
let metaContentFixer = Interceptor((req, res) => ({
  isInterceptable() {
    return /text\/html/.test(res.get("Content-Type"))
  },
  intercept(body, send) {
    send(normalizeHTML(body.toString()))
  }
}))

app
  .prepare()
  .then(() => {
    let server = Express()
    server.use(metaContentFixer)
    ...
  })

function normalizeHTML(html) {
  return html
    // Fix SEO title
    .replace(/<title[^>]*>([^<]*)<\/title>/, (match, content) => {
      return match.replace(content, ent.decode(content))
    }) // fix-1
    // Remove linebreaks in meta contents
    .replace(/content="([^"]+)"/g, (match, content) => {
      return `content="${ent.decode(content).replace(/(\r\n|\n|\r)+/g, " ")}"`
    }) // fix-2
}
```

You can say "meh, it's just React bugs". The problem is that such bugs can be very long-lasting and quite detremental to SEO (ruining og attributes for example).

And the list of such issues can be expanded. Not necessary NextJS-related but I remember fixing HTML after ReactRouter + Helmet and so on. The bottom line is that similar issues and answers like "You can only fix it in HTML" are regular at StackOverflow. 

`server.js` allowed us to inject whatever middlewares we wanted. Unless I miss something, **Now-2 + Next-8 do not leave any option to apply custom middlewares**. It's quite a limitation, you know.

**Comment by ivan-kleshnin** [comment] 2019-03-19 17:35
@Timer I think the new title is slightly misleading. I used React bug just as a demonstration of a bigger problem. I don't think it's really possible to scale SSR app without middlewares.

**Comment by ivan-kleshnin** [comment] 2019-03-20 05:10
Another consideration. 

With `next.config.js:routes` we still need `server.js` for a local dev. Which requires either to duplicate code or to add a transformation step from JSON to Express routes. With middlewares, the situation complicates. 

The next logical thep, for you guys, may be writing your own Serverless framework like AWS ended up. As you already on the path of abandoning Docker and the benefit of "No need to rewrite" is no longer a selling point.

**Comment by Timer** [comment] 2019-05-24 00:24
Closing this because this is semantically valid HTML -- can you please provide a case where this doesn't work?

https://codesandbox.io/s/6xn18

For example, the following code opens the link as you'd expect without `&amp;` in the slug:
```html
<a target="_blank" href="http://example.com/?test=1&amp;test2=test">Testing</a>
```

**Closed by Timer** 2019-05-24 00:24 UTC
Labels: Is Upstream, Type: Bug

**Comment by ivan-kleshnin** [comment] 2019-05-24 05:07
> Closing this because this is semantically valid HTML -- can you please provide a case where this doesn't work?

Well, compare:

```
<title>X & Y</title>
```

and

```
<title>X &amp; Y</title>
```

What do you think the browser will display in the tab?

**Comment by ivan-kleshnin** [comment] 2019-05-24 05:14
Consider SEO titles where you want

```
<title>X & Y</title>
```

instead of

```
<title>X &amp;</title>
```

because:

1. the latter can be treated differently by search engines
2. SEO titles have effective length limitation

**Comment by ivan-kleshnin** [comment] 2019-05-24 08:58
FYI, this issue started when we saw 

```
Foo &amp; Bar
```

like results in the Goole SERP (search engine result page)! There are many opinions as for is HTML entities are allowed. Google itself uses a £9.24 not &pound;9.24 nor &#163;9.24:

https://support.google.com/webmasters/answer/79812?hl=en

**Comment by Timer** [comment] 2019-05-27 19:40
This should probably be filed as a bug with Google -- if this still reproduces we can likely help ping people.

**Comment by balazsorban44** [comment] 2022-01-31 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
