### ISSUE TITLE
build fail by using  typeface-roboto in material ui next

### ISSUE THREAD

**Issue by aqeeldilmir** [zeit/next.js#4326] opened 2018-05-10 12:26 UTC
Module parse failed: Unexpected character '@' (2:0)
You may need an appropriate loader to handle this file type.
| /* roboto-100normal - latin */
| @font-face {
|   font-family: 'Roboto';
|   font-style: normal;
 @ ./pages/index.tsx 3:0-25
 @ multi ./pages/index.tsx
    at /home/muhammad/be-projects/bluerain-app-dukaan-admin/node_modules/next/dist/server/build/index.js:162:31
    at runWithDependencies (/home/muhammad/be-projects/bluerain-app-dukaan-admin/node_modules/webpack/lib/MultiCompiler.js:154:4)
    at /home/muhammad/be-projects/bluerain-app-dukaan-admin/node_modules/async/dist/async.js:1126:9
    at /home/muhammad/be-projects/bluerain-app-dukaan-admin/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/muhammad/be-projects/bluerain-app-dukaan-admin/node_modules/async/dist/async.js:1050:13)
    at /home/muhammad/be-projects/bluerain-app-dukaan-admin/node_modules/async/dist/async.js:958:16
    at /home/muhammad/be-projects/bluerain-app-dukaan-admin/node_modules/async/dist/async.js:1123:13
    at runCompilers (/home/muhammad/be-projects/bluerain-app-dukaan-admin/node_modules/webpack/lib/MultiCompiler.js:96:47)
    at fn (/home/muhammad/be-projects/bluerain-app-dukaan-admin/node_modules/webpack/lib/MultiCompiler.js:101:6)
    at compiler.run (/home/muhammad/be-projects/bluerain-app-dukaan-admin/node_modules/webpack/lib/MultiCompiler.js:150:5)
    at emitRecords.err (/home/muhammad/be-projects/bluerain-app-dukaan-admin/node_modules/webpack/lib/Compiler.js:265:13)
    at Compiler.emitRecords (/home/muhammad/be-projects/bluerain-app-dukaan-admin/node_modules/webpack/lib/Compiler.js:371:38)
    at emitAssets.err (/home/muhammad/be-projects/bluerain-app-dukaan-admin/node_modules/webpack/lib/Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (/home/muhammad/be-projects/bluerain-app-dukaan-admin/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/home/muhammad/be-projects/bluerain-app-dukaan-admin/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/home/muhammad/be-projects/bluerain-app-dukaan-admin/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
  errors:
   [ '(client) ./node_modules/typeface-roboto/index.css\nModule parse failed: Unexpected character \'@\' (2:0)\nYou may need an appropriate loader to handle this file type.\n| /* roboto-100normal - latin */\n| @font-face {\n|   font-family: \'Roboto\';\n|   font-style: normal;\n @ ./pages/index.tsx 3:0-25\n @ multi ./pages/index.tsx',
     '(server) ./node_modules/typeface-roboto/index.css\nModule parse failed: Unexpected character \'@\' (2:0)\nYou may need an appropriate loader to handle this file type.\n| /* roboto-100normal - latin */\n| @font-face {\n|   font-family: \'Roboto\';\n|   font-style: normal;\n @ ./pages/index.tsx 3:0-25\n @ multi ./pages/index.tsx' ],
  warnings: [] }

**Comment by timneutkens** [comment] 2018-05-10 12:34
Again, please follow the issue template...

Duplicate of #4325

**Closed by timneutkens** 2018-05-10 12:34 UTC
