### ISSUE TITLE
Cannot find module for _error.js

### ISSUE THREAD

**Issue by tomjohnneill** [zeit/next.js#5656] opened 2018-11-10 23:43 UTC
# Bug report

Deploying Next to a Firebase function, gets the following error:
```
{ Error: Cannot find module '/srv/next/server/static\vk8cHgwKqiKyVYwLtSV~e\pages\_error.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at _callee$ (/srv/node_modules/next/dist/server/require.js:85:46)
    at tryCatch (/srv/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/srv/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/srv/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/srv/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/srv/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9) code: 'MODULE_NOT_FOUND' }
```

## Describe the bug

I think this is because there's a mix of slashes and backslashes in the file name so Node can't find it. 

The file definitely exists in the correct folder.

## System information
 - OS: Windows
 - Version of Next.js: 7.0.2

## Additional context

Would it make sense to replace all backslashes with slashes in the getPagePath function?

**Comment by timneutkens** [comment] 2018-11-10 23:56
Duplicate of #4920

**Closed by timneutkens** 2018-11-10 23:56 UTC
