### ISSUE TITLE
Ignored folders as page on /pages folder

### ISSUE THREAD

**Issue by Alecell** [zeit/next.js#10377] opened 2020-02-01 20:28 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
It isn't related to a problem. But if what I'm asking already exists its a good idea to let it more clear on the docs.

## Describe the solution you'd like
It will be awesome if we can add a config on `next.config` that allow us to add a ignored name folder to `/pages` that will not crawl that folder as an app page. 
The purpose of it is a way to create a components folder wich has the components that belong to a unique page and (probably) wont be reused again. That kind of practice let clear that this components belong only to that page and will be easier to add things like useMemo, React.memo and useCallback without pollute the root `/components` folder with never reused components.

Something like:

Folder:
```
/pages
....  /customers
........  /components
........  index.js
```

Config:
```
module.exports = {
    notPage: ['components']
};
```

## Describe alternatives you've considered
It is possible to create a `/pages` components inside `root` `/components` folder and there add that kind of component.

**Comment by timneutkens** [comment] 2020-02-01 21:21
This has been discussed many times before in the issue tracker. Most recently the issue below.

Duplicate of https://github.com/zeit/next.js/issues/8454

**Closed by timneutkens** 2020-02-01 21:21 UTC

**Comment by pcmaffey** [comment] 2020-03-20 16:29
You can get around this easily by just using the `/pages` folder as an index of files that point to a separate `/pages-lib` folder, structured however you want. eg. each file is just a single line `export { default } from 'page-lib/Index'`

**Comment by alihesari** [comment] 2020-04-18 16:33
To solve this issue, I added `getInitialProps` in my component and pass a prop to the component. When the component call from in the page `getInitialProps` will not run and that the props will be `undefined` so I return the current component and otherwise I render 404.
Something like:
```

**Comment by alihesari** [comment] 2020-04-18 16:42
To solve this issue, I added getInitialProps in my component and pass a prop to the component. When the component imported in a page `getInitialProps` function will not run and that the prop will be undefined so I return the current component and otherwise I return 404 error.

Something like:
```
/pages
....  /home.js
........  /components
.........  myComp.js
```

**home.js**
```
import MyComp from "./components/myComp";

const home = ({ course }) => {
    return (
        <>
             <h1>Home page</h1>
             <MyComp />
        </>
    );
}

export default home;
```

**mycomp.js**
```
import Error from 'next/error'

const mycomp = ({ isValid }) => {
   const renderComp = () => {
       if (isValid !== undefined) {
            return <Error statusCode={404} />
        } else {
            return <h2>This is My component</h2>;
        }
   }

    return renderComp();
}

mycomp.getInitialProps = (ctx) => {
    return { isValid: false };
};

export default mycomp;
```

**Comment by sidinei-silva** [comment] 2020-09-05 03:24
> Você pode contornar isso facilmente apenas usando a `/pages`pasta como um índice de arquivos que aponta para uma `/pages-lib`pasta separada , estruturada como você quiser. por exemplo. cada arquivo é apenas uma única linha`export { default } from 'page-lib/Index'`


Despite solving, this will prevent using Data fetching methods on server side:
getStaticProps, getStaticPaths, getServerSideProps

**Comment by melnyczuk** [comment] 2021-06-07 10:50
> > Você pode contornar isso facilmente apenas usando a `/pages`pasta como um índice de arquivos que aponta para uma `/pages-lib`pasta separada , estruturada como você quiser. por exemplo. cada arquivo é apenas uma única linha`export { default } from 'page-lib/Index'`
> 
> Despite solving, this will prevent using Data fetching methods on server side:
> getStaticProps, getStaticPaths, getServerSideProps

This is easily solved by adding the required function to the same line: 
`export { default, getStaticProps } from 'page-lib/Index'`

**Comment by Cauen** [comment] 2021-08-18 15:43
For people that's searching for a way to ignore files inside `/pages` folder
https://github.com/vercel/next.js/issues/3728#issuecomment-523789071
https://nextjs.org/docs/api-reference/next.config.js/custom-page-extensions

**Comment by mycolaos** [comment] 2022-01-05 13:18
I can use files, but as I understand correctly, the directories are still crawled for pages.

I have this error:
`error: Using `export * from '...'` in a page is disallowed. Please use `export { default } from '...'` instead.`

Isn't it possible to discard as path a whole directory at once with some prefix?

**Comment by balazsorban44** [comment] 2022-02-04 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
