### ISSUE TITLE
Next doesn't output sw-precache file in development mode

### ISSUE THREAD

**Issue by wesleycoder** [zeit/next.js#4718] opened 2018-07-03 01:33 UTC
# Bug report

## Describe the bug
Next supress the file output from [`sw-precache-webpack-plugin`](https://github.com/goldhand/sw-precache-webpack-plugin) in development mode (in build/production mode it outputs correctly)

## To Reproduce
I've made a simplified repository to clone here: [https://github.com/wescoder/sw-test](https://github.com/wescoder/sw-test)
After cloning, run it with `npm start` (will start in development mode)

## Expected behavior
Next should output the service worker file in `.next/static/sw.js` as descripted [here](https://github.com/wescoder/sw-test/blob/08f11192c561876b4be0cd79b58858b07b3f5d28/next.config.js#L18)

## System information
 - OS: `Linux 4.15.0-21deepin-generic #21 SMP Mon May 21 05:20:09 UTC 2018 x86_64 GNU/Linux`
 - Browser: `Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)`
 - Version of Next.js: `^6.1.1`

## Additional context
I've made another repository without `next` to validate that sw-precache-plugin is working properly without next: [https://github.com/wescoder/sw-test-only](https://github.com/wescoder/sw-test-only)

**Comment by aequasi** [comment] 2018-07-04 01:13
Any way around this?

**Comment by wescoder** [comment] 2018-07-04 01:33
Unfortunately I couldn't figure out any way to run this in development mode yet, any workaround would be much appreciated.

**Comment by aequasi** [comment] 2018-07-04 02:39
My guess is its because of this: https://github.com/goldhand/sw-precache-webpack-plugin#webpack-dev-server-support

**Comment by wescoder** [comment] 2018-07-04 17:23
My doubt is that despite of this it works when using just sw-precache as i found tested here: [https://github.com/wescoder/sw-test-only](https://github.com/wescoder/sw-test-only)

**Comment by wescoder** [comment] 2018-07-04 17:48
And I think Next.js does something different with the dev-server because it doesn't hold an in-memory fs, it outputs the build to `.next` directory (AFAIK).

**Comment by wescoder** [comment] 2018-07-04 21:50
I have tried [`sw-precache-webpack-dev-server-plugin`](https://www.npmjs.com/search?q=sw-precache-webpack-dev-server-plugin) as suggested in [this comment](https://github.com/goldhand/sw-precache-webpack-plugin/issues/17#issuecomment-277271950) and [`sw-precache-webpack-plugin-loader`](https://www.npmjs.com/package/sw-precache-webpack-plugin-loader) but until now I had no success in making it work.

**Comment by wescoder** [comment] 2018-07-05 20:35
I think I got a workaround that works.
I'm using [`sw-precache-webpack-plugin-loader`](https://www.npmjs.com/package/sw-precache-webpack-plugin-loader) instead of `sw-precache-webpack-plugin` and using a config like this:
```js
    const SW_PATH = resolve('./.next/static')
    mkdirp(SW_PATH) // ensure the folder exists before next creates it otherwise sw-precache will break the build

    config.plugins.push(new SWPrecacheWebpackPlugin({
      cacheId: 'rockheine',
      filepath: `${SW_PATH}/sw.js`,
      minify: true,
      // do not set mergeStaticsConfig: true this will mess with stripPrefixMulti
      navigateFallback: ENV.PUBLIC_URL,
      handleFetch: !dev, // set this so in dev env fetch will not be directed to sw according to: https://github.com/GoogleChromeLabs/sw-precache#handlefetch-boolean
      staticFileGlobs: [
        '.next/bundles/**/*.{js,json}',
        '.next/static/**/*.{js,css,jpg,jpeg,png,svg,gif}'
      ],
      staticFileGlobsIgnorePatterns: [/_.*\.js$/, /\.map/],
      stripPrefixMulti: {
        '.next/bundles/pages/': `/_next/${buildId}/page/`,
        '.next/static/': '/_next/static/'
      },
      runtimeCaching: [
        { handler: 'fastest', urlPattern: /[.](jpe?g|png|svg|gif)/ },
        { handler: 'networkFirst', urlPattern: /^https.*(js|css)/ }
      ],
      templateFilePath: resolve('./components/service-worker.js.ejs'),
      verbose: !dev
    }))
```

**Comment by wescoder** [comment] 2018-07-05 21:59
I've commited this workaround to the sample repo [here](https://github.com/wescoder/sw-test/tree/dc06e0448afe187176eafeacea3ce4440528d9ea)

**Comment by Huaoe** [comment] 2018-10-15 14:14
Hi @wescoder , 
Your repo is down and I'd be curious to have a look.

**Comment by wescoder** [comment] 2018-10-15 14:19
Hi @Huaoe, I'm able to access it normally via https://github.com/wescoder/sw-test and by the commit link https://github.com/wescoder/sw-test/tree/dc06e0448afe187176eafeacea3ce4440528d9ea.

Maybe is a temporary issue with github on your location?

Be aware that since then `next` had major changes and my repo wasn't updated for the latest release.
I'll see if I have time this week to update it and if so I'll comment here.

**Comment by Huaoe** [comment] 2018-10-17 12:58
hi @wescoder, thank you for your diligency ! you're right next.js has changed. FYI I'm using next-offline now . Your code's worth a look, thx

**Comment by timneutkens** [comment] 2019-08-09 15:36
Going to close this as the issue has been open for over a year.

**Closed by timneutkens** 2019-08-09 15:36 UTC
Labels: good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-31 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
