### ISSUE TITLE
Next.js & Now – `continue: true` is required for dynamic routing

### ISSUE THREAD

**Issue by borekb** [zeit/next.js#8440] opened 2019-08-20 10:36 UTC
As discussed in https://github.com/zeit/next.js/pull/8426#issuecomment-522807908, `continue: true` must be added to `now.json` for Next.js dynamic routing to work correctly on Now. [Full example](https://github.com/zeit/next.js/blob/61cf7128cdf330af4ae46f3521f58371245be7b4/packages/next/README.md#how-to-merge-them):

```json
{
  "builds": [
    { "src": "docs/next.config.js", "use": "@now/next" },
    { "src": "home/next.config.js", "use": "@now/next" }
  ],
  "routes": [
    { "src": "/docs(.*)", "dest": "docs$1", "continue": true },
    { "src": "(?!/?docs)(.*)", "dest": "home$1", "continue": true }
  ]
}
```

Without `continue: true`, Now-deployed app returns HTTP 404 for dynamic routes like `/blog/post/1` (assuming a dynamic page `/pages/blog/post/[id].js`).

> **Note**: while `continue: true` works for Now (cloud), it breaks on `now dev`, see https://github.com/zeit/now/issues/2685.

## Can this be avoided?

First, I personally find it very unintuitive that `continue: true` must be added for dynamic routing to work. I still don't quite understand why it's so, probably something about how the `@now/next` builder internally works, and it's a bit unfortunate that this technical detail leaks into the "UI".

Another downside is that with `continue: true`, I have to worry about the following routes. In the example above, the second route uses negative lookahead exactly because of that, and when first looking at it, I was wondering why the second line has `continue: true` as well when there's seemingly nothing to continue to.

Maybe @Timer has any insights?

## Places that should be updated

If `continue: true` cannot be avoided, these are the places where I think it should be updated / mentioned:

- [x] [with-zones example](https://github.com/zeit/next.js/blob/f0b6d0a1e2f56a3523c67e554b996d549d65b262/examples/with-zones/now.json) https://github.com/zeit/next.js/pull/8459
- [ ] [README / routing](https://github.com/zeit/next.js/blob/61cf7128cdf330af4ae46f3521f58371245be7b4/packages/next/README.md#how-to-merge-them): I think it should be noted why `continue: true` is required (even for the last route).
- [ ] [`docs/v2/advanced/routes.mdx#continue`](https://github.com/zeit/docs/blob/2373ace86fd047ca6b0d04f1b6e35494b315014c/pages/docs/v2/advanced/routes.mdx#continue)
- [ ] (Maybe) [`docs/v2/advanced/configuration.mdx#routes`](https://github.com/zeit/docs/blob/2373ace86fd047ca6b0d04f1b6e35494b315014c/pages/docs/v2/advanced/configuration.mdx#routes)

Wow, nothing to update in `now-examples` 😄:

![Screenshot 2019-08-20 at 12 23 05](https://user-images.githubusercontent.com/101152/63339866-1fca7600-c346-11e9-9f2d-6bd1d1f3c8b7.png)

**Comment by borekb** [comment] 2019-08-20 11:10
I spoke too soon – `continue: true` doesn't work for me. This is my config:

```
{
  "builds": [
    { "src": "graphql-server/src/server.ts", "use": "@now/node" },
    { "src": "apps/one/next.config.js", "use": "@now/next@canary" },
    { "src": "apps/two/next.config.js", "use": "@now/next@canary" }
  ],
  "routes": [
    { "src": "/graphql", "dest": "/graphql-server/src/server.ts" },
    { "src": "/app-one/(.*)", "dest": "/apps/one/$1", "continue": true },
    { "src": "/app-two/(.*)", "dest": "/apps/two/$1", "continue": true }
  ]
}
```

Static routes, e.g., `https://deploymentid.now.sh/app-one/static-route`, work but dynamic routes return HTTP 500.

**Comment by borekb** [comment] 2019-08-21 08:51
I tried `continue: true` again in #8459 with the `with-zones` example and it indeed didn't work. I'll report back if that PR gets any comments about it.

**Comment by borekb** [comment] 2019-08-27 20:21
Updated `with-zones` example, see https://github.com/zeit/next.js/pull/8459, now works.

**Comment by Timer** [comment] 2019-12-23 15:49
Closing as the idea of multiple apps in one project is being deprecated on Now. See https://github.com/zeit/next.js/pull/9604.

**Closed by Timer** 2019-12-23 15:49 UTC

**Comment by borekb** [comment] 2019-12-30 21:03
@Timer Is this explained somewhere please? #9604 is just a README update, pointing to an internal JIRA issue. Will it no longer be possible to deploy two Next.js apps side by side on Now?

**Comment by Timer** [comment] 2019-12-30 22:07
@borekb The ability to deploy two separate projects as **one project** is being deprecated. The new behavior will allow you to setup multiple projects on ZEIT Now that deploy from a single Git repo -- effectively enabling this same behavior.

See that [the `builds` key is deprecated](https://zeit.co/docs/configuration#project/builds). We're also [deprecating `routes` in favor of `rewrites`](https://zeit.co/docs/configuration#project/routes).

There's no official migration guide yet as we're not ready. Once we add the ability to specify a "project root" (e.g. `packages/web-app-1`) we'll have official docs for the new solution!

**Comment by borekb** [comment] 2019-12-30 23:06
We have **one project** that consists of **two Next.js app** (but could also be a Next.js app & Gatsby app, for example) – they should be deployed together, to a single URL.

The docs show this example for `functions`:

```json
{
  "functions": {
    "api/test.php": {
      "runtime": "now-php"
    }
  }
}
```

How would that look for us? Like this?

```json
{
  "functions": {
    "app1/next.config.js": {
      "runtime": "nextjs"
    },
    "app2/next.config.js": {
      "runtime": "nextjs"
    }
  }
}
```

It looks weird but I'm not sure how to replace `builds` with this.

**Comment by Timer** [comment] 2019-12-30 23:23
> There's no official migration guide yet as we're not ready. Once we add the ability to specify a "project root" (e.g. packages/web-app-1) we'll have official docs for the new solution!

Keep in mind this is a WIP and the use case is not yet supported. Please remain using `builds` for now.

**Comment by balazsorban44** [comment] 2022-01-30 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
