### ISSUE TITLE
How to ignore a folder when running "next build"

### ISSUE THREAD

**Issue by andy-asi** [zeit/next.js#11144] opened 2020-03-17 16:05 UTC
When we run "next build" in our production server, it takes +20mins for the process to finish.
The problem for this delay is that we have a folder in the public/ directory called "uploads" and it has about 30,000 folders and files. This is our project hierarchy:

... other folders
public/
... other folders
uploads/ #### << here
... (huge number of files)
pages/
is there a way to prevent the build command from going through each folder and file inside the uploads folder because they are only used for serving static pictures and assets.

maybe adding an argument inside "next.config.js" to exclude specific folders?

thank you for your time!

## System information

- OS: ubuntu-18-04
- Version of Next.js: 9.3.1

**Comment by timneutkens** [comment] 2020-03-17 16:20
Duplicate of https://github.com/zeit/next.js/discussions/11113

**Closed by timneutkens** 2020-03-17 16:20 UTC

**Comment by danawoodman** [comment] 2020-12-22 04:23
Sorry to nitpick but is it really a duplicate if it is a discussion and not a ticket?

**Comment by timneutkens** [comment] 2020-12-22 13:17
Yes, especially if the issue template is ignored and the discussion content is copied into issues to fast-track getting an answer to the question.

**Comment by danawoodman** [comment] 2020-12-22 16:05
Gotcha. I guess maybe the ticket should instead be "Support ignoring directories with 'next build'" and follow the template to be considered? Or perhaps there are other tickets that relate to this topic?

**Comment by ctjlewis** [comment] 2021-07-26 18:17
I believe the best approach would to enable Next to respect `rootDir` like it respects `excludes`:

https://github.com/vercel/next.js/discussions/11113#discussioncomment-1052618_

**Comment by balazsorban44** [comment] 2022-01-28 01:27
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
