### ISSUE TITLE
a separate documentation subsite *specifically* targeting SSG usecase

### ISSUE THREAD

**Issue by sandys** [zeit/next.js#9633] opened 2019-12-05 07:00 UTC
Looking at many SSG specific features being built into Nextjs (especially https://github.com/zeit/next.js/issues/9524) , here's what I think is the biggest issue in using Nextjs for SSG.

The problem is that Nextjs entire documentation and manuals are written from the perspective of a server-side rendering framework. They are not geared around the usecase of someone wanting to either quickly get started..or someone who is working with a Nextjs SSG and wanted help on some SSG contextual aspect. 

For example, the entire section of "Prefetching Pages", "Custom server and routing", and many more is not relevant for a SSG usecase. In fact on the left side - there is no section for "static site generation". The documentation page of Nextjs lets people think that this is not a usecase that Nextjs supports. 

I dont believe there is any real way the two usecases can be merged in docs without massive cognitive overload for the user. 

The documentation subsites should be entirely different for SSG and SSR usecases. Its ok if section are duplicated (which can be included in both sites from "common docs").

**Comment by timneutkens** [comment] 2020-01-03 01:29
Fixed by #9301

**Closed by timneutkens** 2020-01-03 01:29 UTC
Labels: Documentation

**Comment by balazsorban44** [comment] 2022-01-30 17:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
