### ISSUE TITLE
Inconsistent loading order of CSS in dev mode

### ISSUE THREAD

**Issue by Joozty** [zeit/next.js#11946] opened 2020-04-16 12:58 UTC
# Bug report

## Describe the bug

It's based on https://github.com/zeit/next.js/issues/10148#issuecomment-614478653. When `_app.jsx` contains component which imports postcss module the order of css chunks is inconsistent. Most likely css from module is inserted before global css.

## To Reproduce

I created a repo for you https://github.com/Joozty/nextjs-css. It's a fork from https://github.com/zeit/next.js/issues/10148. So the steps to reproduce are almost identical.

## Expected behavior

CSS in dev mode should be imported/inserted the same way as on production, i.e. global css first and then modules.

Thanks a lot :)

**Comment by fabinppk** [comment] 2020-04-16 14:03
I still have problems with css order too.
I think the comment below is the same problem :thinking: 

https://github.com/zeit/next.js/pull/11901#issuecomment-614644961

**Comment by iksent** [comment] 2020-04-17 15:08
Maybe I have a similar bug:

1. I am using Dart SASS: `"node-sass": "npm:sass@1.26.2"` with `@use` imports.
2. Also I am using CSS Modules.
3. And I tried both Next.js built-in CSS and `@zein/next-css` with custom config,
4. Everything works just perfect in development.
5. But I have a problems with styles in production: some elements displaying not correctly because of different CSS-files importing order or because CSS duplicates (there is no duplicates in dev).

Production:
![prod](https://user-images.githubusercontent.com/32956521/79583805-f9ccbf80-80e6-11ea-9bd4-d29ce3b10c0a.png)

Development:
![dev](https://user-images.githubusercontent.com/32956521/79583818-ff2a0a00-80e6-11ea-93d9-6ee7b8b2c0a0.png)

Just no ideas, how to fix it...

**Comment by fabinppk** [comment] 2020-04-17 15:43
I am installed this version [v9.3.6-canary.0](https://github.com/zeit/next.js/releases/tag/v9.3.6-canary.0) because has a patch to fix css, but didnt resolve to me.

I dont really what it that, but i continuous having duplicates between css chunks and when not,  problems with classes order/priority.

**Comment by iksent** [comment] 2020-04-17 15:46
@fabinppk, hello.
I think v9.3.6-canary.0 fixes other problems "Correct Global and Local CSS Loading Order in Dev". No words about avoiding duplicates. And I have no problems is dev, only in production :(

**Comment by fabinppk** [comment] 2020-04-17 15:57
I understand, but the v9.3.6-canary.0 brokers my css in dev mode too, not only in production.

**Comment by ashfaqnisar** [comment] 2020-04-19 08:00
> 
> 
> Maybe I have a similar bug:
> 
>     1. I am using Dart SASS: `"node-sass": "npm:sass@1.26.2"` with `@use` imports.
> 
>     2. Also I am using CSS Modules.
> 
>     3. And I tried both Next.js built-in CSS and `@zein/next-css` with custom config,
> 
>     4. Everything works just perfect in development.
> 
>     5. But I have a problems with styles in production: some elements displaying not correctly because of different CSS-files importing order or because CSS duplicates (there is no duplicates in dev).
> 
> 
> Production (button is visible - its mistake):
> ![prod](https://user-images.githubusercontent.com/32956521/79583805-f9ccbf80-80e6-11ea-9bd4-d29ce3b10c0a.png)
> 
> Development (button is hidden - its correct):
> ![dev](https://user-images.githubusercontent.com/32956521/79583818-ff2a0a00-80e6-11ea-93d9-6ee7b8b2c0a0.png)
> 
> Just no ideas, how to fix it...
> 
> And also there is such a strange thing: styles duplicates appears after HOVERing over the button...
> Production:
> ![simple](https://user-images.githubusercontent.com/32956521/79584453-d9e9cb80-80e7-11ea-89a2-d149937d9c08.png)
> Production (after hover)
> ![hover](https://user-images.githubusercontent.com/32956521/79584465-e0784300-80e7-11ea-84ae-c7c85eb291ae.png)

I also have the same issue @iksent, were you able to solve this thing ?

**Comment by iksent** [comment] 2020-04-19 08:02
@ashfaqnisar, no, I’m not. And this is a really big problem...

**Comment by ashfaqnisar** [comment] 2020-04-19 08:05
Yup, all the important css components in the production are broken due to this thing. Can we assign a label to this issue @iksent

**Comment by Timer** [comment] 2020-04-22 14:51
This should be fixed in `^9.3.6-canary.9`!

**Closed by Timer** 2020-04-22 14:51 UTC
Labels: Type: Bug, help wanted, priority: high

**Comment by fabinppk** [comment] 2020-04-22 16:51
> This should be fixed in `^9.3.6-canary.9`!

I'm installed the exact version `9.3.6-canary.9` and unfortunately in production mode there are still duplicate css.

I'm using sass, but I don't think that could be the problem.

**Comment by iksent** [comment] 2020-04-23 04:07
Yes, my problem has not been resolved either.
Should we open a new issue, @Timer?
Or maybe move to there: https://github.com/zeit/next.js/issues/12099

**Comment by bravokiloecho** [comment] 2020-04-29 11:10
I just upgraded to the stable `9.3.6` and I'm still getting global CSS overrriding CSS from modules (see image below). `elements.css` is imported in the `_app.js`

![image](https://user-images.githubusercontent.com/5556900/80589545-4af78000-8a12-11ea-84fe-95661c72304c.png)

**Comment by iksent** [comment] 2020-04-29 11:12
@bravokiloecho, probably, that's because this issue was resolve in `9.3.6-canary.9`
(https://github.com/zeit/next.js/issues/11946#issuecomment-617827900)

**Comment by bravokiloecho** [comment] 2020-04-29 11:25
@iksent but `9.3.6` was released 7 days after `9.3.6-canary.9` so I assumed it would include everything from that release.

**Comment by iksent** [comment] 2020-04-29 11:33
@bravokiloecho, yes. sorry, my mistake.

**Comment by balazsorban44** [comment] 2022-01-30 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
