### ISSUE TITLE
create-next-app always uses yarn if it is installed

### ISSUE THREAD

**Issue by tsriram** [zeit/next.js#11628] opened 2020-04-03 09:15 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I have both `npm` and `yarn` installed in my laptop. When I create a new app using `npm init next-app` (or `npx create-next-app`), Next always uses `yarn` as the package manager. This is because it [just checks](https://github.com/zeit/next.js/blob/canary/packages/create-next-app/helpers/should-use-yarn.ts) if `yarns` is installed and decides to use it.

## Describe the solution you'd like

Ideally, I'd like this command to check if the command is run using `npm` or `yarn` and use the same as package manager for the new app. I'd suggest to use [is-npm](https://github.com/sindresorhus/is-npm) package (or just copy those few lines 😛, if we don't want to add a dependency) and check if code is run using `npm` or `yarn`. If for any reason this module isn't able to determine the used package manager, we can use the current logic as a fallback mechanism.

I'm happy to submit a PR is this makes sense.

**Comment by timneutkens** [comment] 2020-04-03 09:49
Duplicate of https://github.com/zeit/next.js/issues/10647

Feel free to add checking for it similar to https://github.com/sindresorhus/is-npm/blob/master/index.js. I'd like to avoid adding additional deps

**Closed** 2020-04-03 09:51 UTC

**Comment by tsriram** [comment] 2020-04-05 11:35
Hi @timneutkens! I've made the changes locally but couldn't figure out how to test it. Would be great if you could share a quick note on how to run/test this locally. I'll add it to the README.md or CONTRIBUTING.md for future contributors.

**Comment by timneutkens** [comment] 2020-04-05 11:48
Tbh I'm not sure how to test this behavior correctly without fully running `npm` or `yarn`. Let's open a PR first and figure out how to test it later 👍

**Comment by balazsorban44** [comment] 2022-01-30 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
