### ISSUE TITLE
 file system-based dynamic routes - slug and param and string  combination

### ISSUE THREAD

**Issue by farhadniaz** [zeit/next.js#8243] opened 2019-08-05 12:22 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

A clear and concise description of what you want and what your use case is.

Currently with nextjs9 we can make routes like  
```
root/city/[id].js  
root/city/[id]/details.js
```
this cool. 

## Describe the solution you'd like

But we can't make routes like:
```
root/city-[id]/details.js
```

**Comment by Timer** [comment] 2019-08-05 12:42
Related: https://github.com/zeit/next.js/issues/7607

**Comment by farhadniaz** [comment] 2019-08-05 13:41
@Timer  [#7607](https://github.com/zeit/next.js/issues/7607) seems related but there is more :
Next.js9 use [path-to-regexp) ](https://www.npmjs.com/package/path-to-regexp)  for routing and i just wondering why in nextjs we cant build folder slugs like :

```
/ads/[art-:id]/details/[location]
/ads/[auto-:id]/details/[location]
/ads/[home-:id]//details/[location]

```

this will cause a error :

 **throw new Error('You cannot use different slug names 
for the same dynamic path.');**



but we can use same patterns in express.js with path-to-regexp ,

**Comment by Timer** [comment] 2019-12-23 15:46
Duplicate of #9081

**Closed by Timer** 2019-12-23 15:46 UTC

**Comment by balazsorban44** [comment] 2022-01-30 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
