### ISSUE TITLE
 deploy on amazon S3 + CF is not working, /post not access the /post.html file

### ISSUE THREAD

**Issue by flakesrc** [zeit/next.js#10432] opened 2020-02-05 18:04 UTC
I'm using nextjs to export the static html website. When I go to the homepage (http://geekhouse-client.s3-website-sa-east-1.amazonaws.com/), the content loads normally, and it also works when I click on other links on the site.

But when I try to access other urls directly
(http://geekhouse-client.s3-website-sa-east-1.amazonaws.com/second-post), I get a 404 error
Any ideas what to do? I have already configured the bucket to host a static website, and configured the 404.html file for errors.

S3 Bucket config and files: https://imgur.com/a/4TsHBuJ
Print of Browser > Network when i try access the link os posts: https://imgur.com/a/SDdHoxx

**Comment by timneutkens** [comment] 2020-02-05 21:12
Both urls don't seem to work for me. Potentially you can try https://zeit.co.

As per the issue template I'm going to close this issue as questions should be posted on https://spectrum.chat/next-js.

**Closed by timneutkens** 2020-02-05 21:12 UTC

**Comment by flakesrc** [comment] 2021-02-18 16:41
For those who have the problem, when I had this, I couldn't solve it. So I just went to Zeit (now Vercel) and everything worked as it should. I recommend doing the same.

**Comment by balazsorban44** [comment] 2022-01-28 17:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
