### ISSUE TITLE
[FEATURE REQUEST] Add react-refresh support?

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [zeit/next.js#12455] opened 2020-05-03 20:40 UTC
Add https://www.npmjs.com/package/react-refresh in dev mode

The guide https://github.com/facebook/react/issues/16604#issuecomment-528663101

**Comment by jamesmosier** [comment] 2020-05-03 23:06
This is currently being developed https://github.com/zeit/next.js/pull/12008

**Comment by Timer** [comment] 2020-05-03 23:36
Closing as this is already supported, re above comment.

**Closed by Timer** 2020-05-03 23:36 UTC

**Comment by MaxmaxmaximusGitHub** [comment] 2020-05-04 01:19
@Timer you should specify experimental functions in the documentation =) otherwise many people will ask the same thing =) sorry to distract

**Comment by Timer** [comment] 2020-05-04 02:00
Experimental features are not meant to be used by normal users, so we do not plan on documenting them. They're available to people who dive in the code and find them, or follow PRs closely!

**Comment by balazsorban44** [comment] 2022-01-30 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
