### ISSUE TITLE
a disturbing delay between DOMContentLoaded event to Load event

### ISSUE THREAD

**Issue by Ajar-Ajar** [zeit/next.js#1426] opened 2017-03-15 10:28 UTC
Hi all,
I've prepared two example projects using next.js 
The first example is using styled-components as a solution, and the second one is using the default solution for css which is styled-jsx.
Both examples include exactly the same code with a minimum level of complexity.
As you will soon see for yourself - in the styled-components example there is a disturbing delay between DOMContentLoaded event and Load event inwhich the user actually sees the un-styled html markup, while in the second example using styled-jsx this is not the case.

Both demos are hosted online using Zeit now:
1 -  https://01-styled-components-sqprkdqeft.now.sh
2 -  https://02-styled-jsx-nhrynpsdox.now.sh

Source available on github:
1 - https://github.com/Ajar-Ajar/next-demo--styled-components
2 - https://github.com/Ajar-Ajar/next-demo--styled-jsx

I would very much appreciate any insights regarding why does the delay occure in one and not the other,
and of course any way to amend this behavior using styled-components.

Thank you
Ajar
:)

**Comment by arunoda** [comment] 2017-03-15 11:38
@Ajar-Ajar here the issue is styled-component doesn't work in the SSR version by default.
For that you need to use our custom document feature.

See: https://github.com/zeit/next.js/blob/master/examples/with-styled-components/pages/_document.js

**Comment by Ajar-Ajar** [comment] 2017-03-15 13:27
@arunoda - you're our hero!
🌵

**Comment by arunoda** [comment] 2017-03-15 16:04
Nice. Closing this.

**Closed by arunoda** 2017-03-15 16:04 UTC
Labels: Type: Question
