### ISSUE TITLE
Material UI React - Broken on production

### ISSUE THREAD

**Issue by Rawnly** [zeit/next.js#5906] opened 2018-12-17 11:34 UTC
# Bug report
Hi guys, when I use `dev: false` inside my app, **material-ui** classes wont load.
## Describe the bug

That's the code:
```js
const port = process.env.PORT || 3000;
const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev: false });
const handle = app.getRequestHandler();

app.prepare().then(() => {
	const server = express();
    
	// Routes and stuff...
})
```

The expected result should be:
![cleanshot 2018-12-17 at 12 31 51](https://user-images.githubusercontent.com/16429579/50084583-c4b11400-01f7-11e9-9be4-6a236d3882fd.png)

but is:
![cleanshot 2018-12-17 at 12 25 52](https://user-images.githubusercontent.com/16429579/50084533-9c291a00-01f7-11e9-96f0-5396ef45ed56.png)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Install  **@material-ui**
```json
		"@material-ui/core": "latest",
		"@material-ui/icons": "^3.0.1",
		"@material-ui/styles": "^3.0.0-alpha.2",
```

2. Run the server with production build

## System information
 - OS: macOS Mojave `v10.14.2`
 - Version of Next.js: `7.0.2`

**Comment by timneutkens** [comment] 2018-12-17 11:37
Duplicate of #5892, this is not a Next.js issue.

cc @oliviertassinari did material-ui have a breaking change or something 🤔

**Closed by timneutkens** 2018-12-17 11:37 UTC

**Comment by Rawnly** [comment] 2018-12-17 11:42
Ok sorry I've just missed it. Thank you!
