### ISSUE TITLE
Prevent remounting of layout component on every page?

### ISSUE THREAD

**Issue by scf4** [zeit/next.js#2091] opened 2017-05-28 11:49 UTC
I have a top level navbar component which starts a web socket to listen for user notifications. Unfortunately the navbar is unmounted and remounted on every page load, forcing the websocket to disconnect/reconnect.

Is there no way around this with next.js?

**Comment by timneutkens** [comment] 2017-05-28 12:21
Currently there is no way around this. Closing this as duplicate of https://github.com/zeit/next.js/issues/88 which is the same question brought differently 👍

**Closed by timneutkens** 2017-05-28 12:21 UTC

**Comment by sedubois** [comment] 2017-05-28 13:04
will https://github.com/zeit/next.js/pull/2010 solve this or is it about something else?

**Comment by timneutkens** [comment] 2017-05-28 13:30
#2010 is about server side rendering, renderpage is used in _document.js so it won't help with this

**Comment by bestwestern** [comment] 2017-05-29 09:12
@scf4 a hacky solution until Next solves it: Make the web socket global
