### ISSUE TITLE
Did not expect server HTML to contain a <span> in <div> using redux-saga

### ISSUE THREAD

**Issue by francisrod01** [zeit/next.js#5367] opened 2018-10-02 19:23 UTC
# Examples bug report

## Example name
with-redux-saga:
https://github.com/zeit/next.js/tree/canary/examples/with-redux-saga

## Describe the bug
I receive the content from serve and show on the screen but the console shows a red warning with the exactly text rendered by redux.

## To Reproduce
I have a real demo on CodeSandbox:
https://codesandbox.io/s/y16j84949

## Expected behavior
I expect a correct rendering in server and client.

## Screenshots
![image](https://user-images.githubusercontent.com/4691768/46371126-e15c9780-c65d-11e8-8529-b1c7c3fc049e.png)

## System information
 - OS: Linux debian 3.16.0-6-amd64 #1 SMP Debian 3.16.57-2 (2018-07-14) x86_64 GNU/Linux
 - Browser : chrome Version 69.0.3497.100 (Official Build) (64-bit)
 - Version of Next.js: 1.0.3

**Comment by MisterKort** [comment] 2018-10-24 15:11
I have a similar issue: ` Did not expect server HTML to contain a <span> in <span>.` I'm not using redux-saga. The following warning show only in Safari.

**Comment by drex44** [comment] 2018-10-27 09:11
Hi, @francisrod01 this warning is given by react. It is because your app is somehow initially rendering a different tree on the client vs the server. you can read about it here on [stackoverflow](https://stackoverflow.com/a/45371427/5027712).

The warning is due to the call to the store.dispatch in getInitialProps. Somehow it results in two different nodes on server and client. due to this react identifies it as different node and could not compare it properly for updation.

One solution I found is to set the initial store value for translation instead of an empty object. I forked and have set the initial value in this [codesandbox](https://codesandbox.io/s/0yqqw9oywl). It resolves this warning.

This issue is somewhat different but will help you understand better,
https://github.com/facebook/react/issues/10879.

**Comment by mfix22** [comment] 2019-02-22 00:18
@timneutkens this can be closed as the error is no longer shown in the the `with-redux-saga` example

**Closed** 2019-02-22 01:31 UTC
Labels: good first issue, help wanted

**Comment by sayjeyhi** [comment] 2019-12-25 13:29
In my case it was because of using `PersistGate` and `react-loadable`. if you using this libraries, you could use preloadAll instead of preloadReady

**Comment by balazsorban44** [comment] 2022-01-30 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
