### ISSUE TITLE
Links to some pages are hanging on navigation with `next-css` plugin

### ISSUE THREAD

**Issue by tannerlinsley** [zeit/next.js#7886] opened 2019-07-10 23:04 UTC
# Bug report

When attempting to navigate to some pages with a simple `<Link href='...'/>`, the page hangs and things break.

- Go to https://nozzleio-8f0sjfbt1.now.sh/
- Navigate around using the top nav bar
- Go to the footer and click on the three links that contain "API Docs"
- Observe the console and network tab

## Expected behavior

The navigation should succeed.

## System information

- OS: macOS
- Browser: Chrome
- Version of Next.js: 9@latest

## More Information
The repo for this website can be found at https://github.com/nozzle/nozzle.io on the master branch.

**Comment by ijjk** [comment] 2019-07-10 23:44
Hi, this is most likely related to a bug in `next-css` where if you import CSS in a page instead of `_app` the loading of the page hangs. Moving the CSS import for `import 'swagger-ui-react/swagger-ui.css'` from `pages/docs/api.js` to `pages/_app.js` should resolve the hanging.

Note: the mentioned `next-css` bug is being investigated/discussed

**Comment by timneutkens** [comment] 2019-07-11 14:21
Specific issue @ijjk is referencing is https://github.com/zeit/next-plugins/issues/282

**Comment by zackkrida** [comment] 2019-08-01 20:59
Wow, this is an absolutely brutal issue. 

FYI if anyone has an issue where route changes via `<Link />` components and the imperative `Router` load the correct code chunk without error but the route simply doesn't change, this might be a likely cause.

**Comment by timneutkens** [comment] 2019-08-03 12:04
It'd help if you provide a reproduction @zackkrida.

**Comment by zackkrida** [comment] 2019-08-04 00:03
Hi Tim! Here's an extremely small reproduction. The `<Link />` on the homepage points to a page with an included css file `import '../test.css'. The link doesn't work. 

If you visit the linked page _first_: https://next-css-bug.zackkrida.now.sh/has-css _then_ use the `<Link />` on the page to havigate to home and back, both links work.

Here's the source if you need it, thank you! Next and zeit are both fantastic.

https://github.com/zackkrida/next-css-bug

**Comment by zackkrida** [comment] 2019-08-04 00:06
And @timneutkens it's definitely this issue: zeit/next-plugins#282
I was only commenting to share the specific behavior because it took me a long time to find this issue. Thanks!

**Comment by Timer** [comment] 2020-04-15 04:44
Closing as this is fixed when switching to Next.js' new build-in CSS support.

**Closed by Timer** 2020-04-15 04:44 UTC
Labels: Type: Bug

**Comment by avin-kavish** [comment] 2020-04-18 19:21
@Timer I don't know about that, routes are still hanging even with built-in support.

**Comment by Timer** [comment] 2020-04-19 03:10
@avin-kavish we have extensive integration tests ensuring they do not. If you're able to reproduce, please provide a demo and we can fix it ASAP.

It's likely that something else is misconfigured, or you're still using `@zeit/next-css`.

**Comment by avin-kavish** [comment] 2020-04-19 05:06
@Timer maybe it's something else, can you give me any common scenarios to lookout for? I'm not sure how to debug this without any sort of feedback. Nothing on the console, no network calls, but server cli says building the page and stops there. Does next support `DEBUG=...` or something similar?

**Comment by Timer** [comment] 2020-04-19 05:12
Unfortunately, there's no advice we can give without you providing a full demo.

**Comment by balazsorban44** [comment] 2022-01-29 04:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
