### ISSUE TITLE
`Link` or `Router.push` is broken under some conditions

### ISSUE THREAD

**Issue by skmdev** [zeit/next.js#9728] opened 2019-12-13 05:10 UTC
# Bug report

## Describe the bug

I am not sure about this bug is due to antd or nextjs.

it cannot use `Link` or `Router.push` to a page that contains antd component from a page not contains any antd component

if there are three pages:
page A: contain antd component
page B and C: not contain antd component

page B -> page C : Success
page A -> page B : Success
page A -> page C : Success
page B -> page A : Failure
page C -> page A : Failure

## To Reproduce
- Clone the example project
```
npx create-next-app --example with-ant-design-less with-ant-design-app
```
- Create a page without any antd component
```
// pages/test.js

import Link from 'next/link';
import { useRouter } from 'next/router';

const TestPage = props => {
  const Router = useRouter();
  const goToIndexPage = e => {
    e.preventDefault();
    Router.push('/');
  };
  return (
    <div>
      <a href="/" onClick={goToIndexPage}>
        Router push Test
      </a>
      <br />
      <Link href="/">
        <a>Link Test</a>
      </Link>
    </div>
  );
};

export default TestPage;
```

- Start project and enter to `localhost:3000/test` and try

## Expected behavior

Link and Router.push should work

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: 9 / 8

## Additional context

it can reproduce in `next@8` and `antd@3.9` too
I built the project also, but it is the same behaviour

**Comment by timneutkens** [comment] 2019-12-13 11:16
Probably a duplicate of https://github.com/zeit/next-plugins/issues/282

**Closed by timneutkens** 2019-12-13 11:16 UTC

**Comment by watch-janick** [comment] 2020-01-04 04:10
> Probably a duplicate of [zeit/next-plugins#282](https://github.com/zeit/next-plugins/issues/282)

That's great to know it's a duplicate of an issue from the 24th of September 2018, but where's the fix?

**Comment by balazsorban44** [comment] 2022-01-30 17:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
