### ISSUE TITLE
Partial Hydration

### ISSUE THREAD

**Issue by oguzzkilic** [zeit/next.js#9475] opened 2019-11-20 18:58 UTC
# Question about Next.js

Hello,

I am trying to obtain information regarding how "**partial hydration**" can be done on next.js. I haven't found any clear information in official documentation. Is there any solution produced on this subject or will there be any?

**Comment by timneutkens** [comment] 2019-11-21 01:52
Please follow the issue template in the future.

--- 

Eventually with React Concurrent mode Next.js will be able to do this by default, however currently it's non-trivial, I know of one post that talks about it: https://medium.com/@luke_schmuke/how-we-achieved-the-best-web-performance-with-partial-hydration-20fab9c808d5

It's definitely something that will be addressed in the future.

**Closed by timneutkens** 2019-11-21 01:52 UTC

**Comment by thuringia** [comment] 2019-12-16 10:24
@timneutkens Sorry to piggyback on this. If you want, I can move this to a new issue based on the template.
As far as I understood Dan Abramov's examples and discussions on this topic, this should be possible right now, given the changes of #9207.
I can, right now, activate concurrent mode, and Next will create a hydrating root, however when using `<Suspense>` as in Dan's example (https://codesandbox.io/s/floral-worker-xwbwv) I get a `ReactDOMServer`-related error.

Could you clarify "how much" of concurrent mode is currently supported in Next? The PR, and the release notes, are not very clear about that.

**Comment by timneutkens** [comment] 2019-12-16 11:21
@devknoll is working on progressive/partial hydration in next.

**Comment by devknoll** [comment] 2019-12-17 17:24
@thuringia Make sure you're using an experimental version of `react` and `react-dom`, and you shouldn't see any `ReactDOMServer` errors. If you still do, please post it and I could try to help out.

Generally, there shouldn't be anything in Next.js preventing you from using Concurrent mode. It's just not optimized, and you may get subpar results. This is what I'm working to address now.

**Comment by timneutkens** [comment] 2019-12-17 18:04
> Generally, there shouldn't be anything in Next.js preventing you from using Concurrent mode. It's just not optimized, and you may get subpar results. This is what I'm working to address now.

Do note that none of the frameworks out there are currently optimized for concurrent mode.

**Comment by LukasBombach** [comment] 2020-02-03 23:09
> @devknoll is working on progressive/partial hydration in next.

That is so awesome. Is there any way I can see this (maybe even contribute if that's wanted)?

**Comment by dennisroethig** [comment] 2020-09-10 13:16
> @devknoll is working on progressive/partial hydration in next.

@timneutkens @devknoll Is this still WIP? I was looking for something like that and ended up here and was wondering what the current state of this is 😅

**Comment by tk-o** [comment] 2020-10-24 02:52
Hey @devknoll 👋 Would you be able to share an update on this issue, please?

**Comment by devknoll** [comment] 2020-10-27 17:59
There are still some optimizations that we can do in Next.js to further improve performance, but generally speaking, you should already be able to use `react@experimental` and `react-dom@experimental` along with the experimental `reactMode: "concurrent"` option in Next.js and get partial + incremental hydration across `<Suspense>` components.

**Comment by zxzl** [comment] 2020-12-27 16:03
For those who are having trouble understanding how react concurrent mode and partial hydration related (like me 🐶) this tweet by Dan Abramov https://twitter.com/dan_abramov/status/1200111677833973760 will be helpful

**Comment by balazsorban44** [comment] 2022-01-29 00:11
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
