### ISSUE TITLE
with-graphql-hooks: Error while running `getInitialState` TypeError: Cannot read property 'pathname' of null

### ISSUE THREAD

**Issue by djskinner** [zeit/next.js#9617] opened 2019-12-04 08:19 UTC
# Examples bug report

## Example name

with-graphql-hooks

## Describe the bug

Server-side rendering error in console: _"Error while running `getInitialState` TypeError: Cannot read property 'pathname' of null"_

Caused by `router` being `null` in one of the components:

```
import { useRouter } from 'next/router'

const Header = () => {
  const router = useRouter()
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run the example, load any page
4. See error in console

## Expected behavior

No error in console, router is defined and pathname is available.

## System information

- OS: Windows 10
- Version of Next.js: 9.1.4

**Comment by djskinner** [comment] 2019-12-04 08:20
I've been away from next for a while and have spent a fair amount of time looking at this but to no avail. If someone can point me in the right direction I'll submit a PR to fix.

**Comment by supaspoida** [comment] 2019-12-07 06:01
@djskinner submitted a PR to fix this error here: https://github.com/zeit/next.js/pull/9658

**Comment by timneutkens** [comment] 2019-12-07 14:38
https://github.com/zeit/next.js/blob/fe994a539f41aa1544090f9782641f86391b0114/examples/with-graphql-hooks/lib/with-graphql-client.js#L26

The problem is that this uses `<App` instead of `<AppTree` coming from `ctx`, you can take `with-apollo` as a reference: https://github.com/zeit/next.js/blob/f9e4f1869172835b49d25e91af5142f533ca1163/examples/with-apollo/lib/apollo.js#L43

**Comment by supaspoida** [comment] 2019-12-07 20:54
@timneutkens I took another crack at this via pulling `AppTree` from the `ctx`, is that in line with what you'd expect? I'll admit I'm definitely just going with trial and error here to try and learn more about next so I appreciate the pointer!

**Comment by timneutkens** [comment] 2019-12-08 11:30
@supaspoida looks fine! Only thing that I think can be removed is these 2 lines: https://github.com/supaspoida/next.js/commit/bf9d7a44dbbbe47e4b6e432c178428c9447d6d11#diff-bf1bb2f8c3c7908ff5039fd3151a6870L28-L29

**Comment by lcswillems** [comment] 2019-12-08 15:07
@timneutkens I don't know if you saw [the issue I opened one month ago](https://github.com/zeit/next.js/issues/9336), but `AppTree` is not working correctly (and hence is not usable). I gave a very small reproduction in the issue I filled.

**Comment by supaspoida** [comment] 2019-12-09 17:10
@timneutkens I've updated my PR based on your suggestions. The issue that @lcswillems pointed out is beyond my ability to debug right now so if it's a blocker for this PR I might need to bow out unless you've got further guidance. Thanks for your time!

**Comment by lfades** [comment] 2019-12-12 09:12
#9658 was merged, can the issue be closed now?

**Closed** 2019-12-12 09:46 UTC
Labels: good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-30 20:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
