### ISSUE TITLE
Cannot find module 'webpack' in CI environment

### ISSUE THREAD

**Issue by tortilaman** [zeit/next.js#12288] opened 2020-04-28 19:06 UTC
# Bug report

## Describe the bug

In CI environments, when initially trying to start the server after build, it errors out with the following error:
```
ERR Error: Cannot find module 'webpack'
ERR Require stack:
ERR - /home/vcap/deps/0/node_modules/mini-css-extract-plugin/dist/index.js
ERR - /home/vcap/deps/0/node_modules/mini-css-extract-plugin/dist/cjs.js
ERR - /home/vcap/deps/0/node_modules/@zeit/next-css/css-loader-config.js
ERR - /home/vcap/deps/0/node_modules/@zeit/next-sass/index.js
ERR - /home/vcap/app/next.config.js
ERR - /home/vcap/deps/0/node_modules/next/dist/next-server/server/config.js
ERR - /home/vcap/deps/0/node_modules/next/dist/next-server/server/next-server.js
ERR - /home/vcap/deps/0/node_modules/next/dist/server/next.js
ERR - /home/vcap/app/routes/next.js
ERR - /home/vcap/app/helpers/startServer.js
ERR - /home/vcap/app/server.js
ERR     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
ERR     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
ERR     at Module.require (internal/modules/cjs/loader.js:683:19)
ERR     at require (internal/modules/cjs/helpers.js:16:16)
ERR     at Object.<anonymous> (/home/vcap/deps/0/node_modules/mini-css-extract-plugin/dist/index.js:7:16)
ERR     at Module._compile (internal/modules/cjs/loader.js:776:30)
ERR     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
ERR     at Module.load (internal/modules/cjs/loader.js:643:32)
ERR     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
ERR     at Module.require (internal/modules/cjs/loader.js:683:19) {
ERR   code: 'MODULE_NOT_FOUND',
ERR   requireStack: [
ERR     '/home/vcap/deps/0/node_modules/mini-css-extract-plugin/dist/index.js',
ERR     '/home/vcap/deps/0/node_modules/mini-css-extract-plugin/dist/cjs.js',
ERR     '/home/vcap/deps/0/node_modules/@zeit/next-css/css-loader-config.js',
ERR     '/home/vcap/deps/0/node_modules/@zeit/next-sass/index.js',
ERR     '/home/vcap/app/next.config.js',
ERR     '/home/vcap/deps/0/node_modules/next/dist/next-server/server/config.js',
ERR     '/home/vcap/deps/0/node_modules/next/dist/next-server/server/next-server.js',
ERR     '/home/vcap/deps/0/node_modules/next/dist/server/next.js',
ERR     '/home/vcap/app/routes/next.js',
ERR     '/home/vcap/app/helpers/startServer.js',
ERR     '/home/vcap/app/server.js'
ERR   ]
ERR }
```

It seems there is an issue with the `mini-css-extract-plugin` as part of @zeit/next-sass.
We've been successfully using this plugin for over a year, with different versions of next.js from 6.0 up to 9.2, and a seemingly unrelated commit is now introducing this error that prevents the site from starting.

This was reported previously in the `mini-css-extract-plugin` repo: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/198

## To Reproduce

I know this isn't helpful, but I'm unable to provide a repository at this time.

## Expected behavior

The app should start.

## System information

- OS: Linux
- Version of Next.js: 9.2.2, "@zeit/next-sass": "^1.0.1",
- Version of Node.js: 12.6.0

**Comment by timneutkens** [comment] 2020-04-29 08:59
This issue is not actionable so I'm not sure what to do here.

**Comment by tortilaman** [comment] 2020-04-30 18:55
I seem to have found a workaround, so while not an issue for me, maybe an issue for others?

**Comment by timneutkens** [comment] 2020-05-01 08:44
Will close this issue then as no reproduction is provided so we can't investigate.

**Closed by timneutkens** 2020-05-01 08:44 UTC
Labels: Please add a complete reproduction

**Comment by robianmcd** [comment] 2020-07-23 13:27
I'm running into this issue too. @tortilaman what was your workaround?

**Comment by Danelund** [comment] 2020-07-31 23:23
I have this as well

**Comment by Danelund** [comment] 2020-07-31 23:35
running

> I'm running into this issue too. @tortilaman what was your workaround?

`npm i --save @zeit/next-sass` fixes this for me

**Comment by tortilaman** [comment] 2020-08-11 22:50
Thanks @Danelund. I no longer had access to the repo I was working on when I encountered this bug, so wasn't really able to figure out the solution I came to.

**Comment by ashispavan** [comment] 2021-01-21 20:24
I am facing this issue after upgrading to NextJS 10. It only happens in CI env.
@robianmcd Were you able to figure out a workaround for this?

**Comment by geun** [comment] 2021-01-30 04:15
> I am facing this issue after upgrading to NextJS 10. It only happens in CI env.
> @robianmcd Were you able to figure out a workaround for this?

Same here

**Comment by MrNghia123** [comment] 2021-01-30 06:53
Next 10  run successfully for several builds for me 3 days ago, now it started to show the same error.
Downgraded to 9.5.5 and build successfully.

**Comment by soly2014** [comment] 2021-01-30 10:15
same issue here

**Comment by iampeterbanjo** [comment] 2021-01-30 11:51
Rolling back to next@10.0.3 fixes webpack dependency.

**Comment by blaxk** [comment] 2021-02-01 01:23
I checked the difference from next@10.0.3 version in package-lock.json.
I found the webpack dependency was gone.

If you add webpack to package.json, you can use it without rollback.

```json
"dependencies": {
    "webpack": "^4.46.0"
}
```

**Comment by saifbechan** [comment] 2021-02-01 19:38
@blaxk I can confirm this works indeed. My version of webpack is higher.

`"webpack": "^5.19.0"`

**Comment by qipoy** [comment] 2021-02-02 09:52
it happens in `next 10.0.6` .  we need reproduce

**Comment by timneutkens** [comment] 2021-02-03 15:21
https://github.com/vercel/next.js/issues/21679#issuecomment-771941447

**Comment by balazsorban44** [comment] 2022-01-28 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
