### ISSUE TITLE
Link not working in production

### ISSUE THREAD

**Issue by flizana** [zeit/next.js#9785] opened 2019-12-19 15:34 UTC
I have various Link in my application but when deployed in production they stop working. The code is as follows:

    <Link href="/register">
      <a>Register</a>
    </Link>

When navigating in development they work fine. When I deploy to production the link takes forever to load the next page. If I write the URL in the address bar it loads fine. When I click on the Link it just hangs, and never loads the page. 

Production environment is:

Ubuntu 18.04
Node.js custom server (Express) behind Nginx.

**Comment by ijjk** [comment] 2019-12-19 16:26
Hi, please follow the issue template. 

This sounds like a duplicate of https://github.com/zeit/next-plugins/issues/282. We are looking into fixing this and opened a RFC [here](https://github.com/zeit/next.js/issues/8626). If you are using global CSS only you can test out the experimental support by adding `module.exports = { experimental: { css: true } }` to your `next.config.js`

I'm going to close this as this is most likely the issue and it doesn't follow the issue template

**Closed by ijjk** 2019-12-19 16:26 UTC

**Comment by YoLoADR** [comment] 2021-02-20 06:03
> I have various Link in my application but when deployed in production they stop working. The code is as follows:
> 
> ```
> <Link href="/register">
>   <a>Register</a>
> </Link>
> ```
> 
> When navigating in development they work fine. When I deploy to production the link takes forever to load the next page. If I write the URL in the address bar it loads fine. When I click on the Link it just hangs, and never loads the page.
> 
> Production environment is:
> 
> Ubuntu 18.04
> Node.js custom server (Express) behind Nginx.

Do you find the solution ? because I have the same issue

**Comment by amiguet3** [comment] 2021-09-12 16:03
Use passHref

**Comment by RacketyWater7** [comment] 2021-12-17 04:20
> Use passHref

I did. But still it doesn't work sometimes in production. I click the Link and its as if nothing happens; as if the Link did not hear the command. Then I have to refresh the page multiple times and then it works. So sometime it works and sometimes doesn't.

**Comment by balazsorban44** [comment] 2022-01-27 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
