### ISSUE TITLE
How to Next.js and Antd integration ？

### ISSUE THREAD

**Issue by VanquisherMe** [zeit/next.js#5180] opened 2018-09-16 09:56 UTC
I'm trying to configure
> https://github.com/VanquisherMe/with-nextjs-antd-app/blob/master/next.config.js#L28

I need to load it on demand ，‘less’ mode
> https://github.com/VanquisherMe/with-nextjs-antd-app/blob/master/.babelrc#L9

I tried many times but I didn't get it right
![fa86fbf0-8c5d-4fe5-8f7a-25f7b65a9ca3](https://user-images.githubusercontent.com/4927398/45595135-a01b8500-b9d9-11e8-9471-4feaa9bc031f.png)

I have ever seen
> https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less

But this is not for the project
**I need an example**

**Comment by afc163** [comment] 2018-09-16 16:56
https://github.com/zeit/next.js/issues/484

**Comment by VanquisherMe** [comment] 2018-09-16 17:26
@afc163 
https://github.com/VanquisherMe/with-nextjs-antd-app/blob/master/next.config.js#L18
nextjs + antd ，open cssModules ，The class of antd is converted
![ce773f5f-f43c-4115-bef9-2747600a7246](https://user-images.githubusercontent.com/4927398/45599112-a67d2180-ba18-11e8-9009-dad32460b56f.png)
 
Problems in this

**Comment by VanquisherMe** [comment] 2018-09-17 03:00
@afc163
I'm looking forward to the

> 1 can use less and customize topics

> 2 load less as required

> 3 enable CSS module, antd class is not converted

I tried it many times, no results, and I needed an example
You can try this example and open CSS module
https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less
this is not for the project

**Comment by sdli** [comment] 2018-12-09 13:19
@VanquisherMe 可以参考以下这个：https://www.yuque.com/steven-kkr5g/aza/ig3x9w

**Comment by jaggerwang** [comment] 2019-02-14 09:36
@sdli It changes config too much!

I already successfully customized theme as the following simple way:

*next.config.js*
```javascript
const withCSS = require('@zeit/next-css')
const withSass = require('@zeit/next-sass')
const withLess = require('@zeit/next-less')

const isProd = process.env.NODE_ENV === 'production'

// fix: prevents error when .less files are required by node
if (typeof require !== 'undefined') {
  require.extensions['.less'] = file => { }
}

module.exports = withLess(withSass(withCSS({
  lessLoaderOptions: {
    javascriptEnabled: true
  }
})))
```

*css/antd.less*
```less
@import "~antd/dist/antd.less";

@primary-color: #C02428;

```

*pages/_app.js*
```javascript
import React from 'react'
import App from 'next/app'
import { Provider } from 'react-redux'

import withReduxStore from '../lib/with-redux-store'

import '../css/antd.less'

class WgApp extends App {
  render() {
    const { Component, pageProps, store } = this.props

    return (
      <Provider store={store}>
        <Component {...pageProps} />
      </Provider>
    )
  }
}

export default withReduxStore(WgApp)

```

But I found the code size of page is very big (6.1 MB).
![image](https://user-images.githubusercontent.com/1255011/52777272-59ac7e00-307e-11e9-879b-439cb1bf9a5e.png)

So it's very needed to load antd component on demand. I tried to transplant the [official way](https://ant.design/docs/react/use-with-create-react-app) in nextjs, but not succeed.

**Comment by sdli** [comment] 2019-02-20 08:07
@jaggerwang See update for less-loader tools, and I have made a npm package to reduce the redundancy。https://www.yuque.com/steven-kkr5g/aza/ig3x9w

**Comment by koolamusic** [comment] 2019-02-26 17:27
Anybody know how to fix this error ?
![screenshot from 2019-02-26 18-26-20](https://user-images.githubusercontent.com/8960757/53433148-2b229180-39f4-11e9-98a3-1d641a5c50d7.png)

I have followed the guides to integrate less

**Comment by stephankaag** [comment] 2019-02-28 15:53
@koolamusic  See https://github.com/zeit/next.js/issues/6181

**Comment by koolamusic** [comment] 2019-03-01 13:06
@stephankaag I have fixed my issues, come of my bottleneck came from fact that I was implementing a custom server together with next-routes, this affected the manner in which the less modules were loaded

**Comment by transitive-bullshit** [comment] 2019-03-08 21:58
@koolamusic is your solution open source? I'm running into this as well.

**Comment by koolamusic** [comment] 2019-03-08 22:31
Lemme send a repo

**Comment by transitive-bullshit** [comment] 2019-03-09 00:12
Thanks @koolamusic! Really stuck on what seems like it should be a pretty simple issue. But then again, they always seem simple... 😄

**Comment by koolamusic** [comment] 2019-03-11 10:20
@timneutkens I could add an example with nextjs using a custom express server and next routes, right ?

**Comment by MerabikoG** [comment] 2019-06-10 11:01
@jaggerwang thx

**Comment by lyzhovnik** [comment] 2019-06-11 06:23
Hi, my config for css-modules, typescript and antd design, tried to make the best..
`const withTypescript = require("@zeit/next-typescript");
const withCss = require("@zeit/next-css");
const withSass = require('@zeit/next-sass')
const withLess = require('@zeit/next-less')
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

module.exports =
  withTypescript(
    withCss(
      withSass({
        cssModules: true,
        ...withLess({
          dir: "src",
          distDir: "../build",
          cssLoaderOptions: {
            importLoaders: 1,
            localIdentName: "[folder]_[local]___[hash:base64:5]",
          },
          lessLoaderOptions: {
            javascriptEnabled: true
          },
          webpack(config, options) {
            if (options.isServer) {
              config.plugins.push(new ForkTsCheckerWebpackPlugin({
                tsconfig: '../tsconfig.json',
              }))

              const antStyles = /antd\/.*?\/style.*?/
              const origExternals = [...config.externals]
              config.externals = [
                (context, request, callback) => {
                  if (request.match(antStyles)) return callback()
                  if (typeof origExternals[0] === 'function') {
                    origExternals[0](context, request, callback)
                  } else {
                    callback()
                  }
                },
                ...(typeof origExternals[0] === 'function' ? [] : origExternals),
              ]

              config.module.rules.unshift({
                test: antStyles,
                use: 'null-loader',
              })
            }

            return config;
          }
        })
      })
    )
  );
`

**Comment by Godsenal** [comment] 2020-01-13 15:24
@lyzhovnik 
Hi! this config works like a charm!
If you don't mind, Could you explain what this config does..?
```
              const antStyles = /antd\/.*?\/style.*?/
              const origExternals = [...config.externals]
              config.externals = [
                (context, request, callback) => {
                  if (request.match(antStyles)) return callback()
                  if (typeof origExternals[0] === 'function') {
                    origExternals[0](context, request, callback)
                  } else {
                    callback()
                  }
                },
                ...(typeof origExternals[0] === 'function' ? [] : origExternals),
              ]
```

**Comment by Timer** [comment] 2020-01-21 13:56
Duplicate of #9830

**Closed by Timer** 2020-01-21 13:56 UTC
Labels: Type: Example, good first issue, help wanted

**Comment by goalbased** [comment] 2020-03-07 22:14
> Hi, my config for css-modules, typescript and antd design, tried to make the best..
> 
> ```js
> const withTypescript = require("@zeit/next-typescript");
> const withCss = require("@zeit/next-css");
> const withSass = require('@zeit/next-sass')
> const withLess = require('@zeit/next-less')
> const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
> 
> module.exports =
>   withTypescript(
>     withCss(
>       withSass({
>         cssModules: true,
>         ...withLess({
>           dir: "src",
>           distDir: "../build",
>           cssLoaderOptions: {
>             importLoaders: 1,
>             localIdentName: "[folder]_[local]___[hash:base64:5]",
>           },
>           lessLoaderOptions: {
>             javascriptEnabled: true
>           },
>           webpack(config, options) {
>             if (options.isServer) {
>               config.plugins.push(new ForkTsCheckerWebpackPlugin({
>                 tsconfig: '../tsconfig.json',
>               }))
> 
>               const antStyles = /antd\/.*?\/style.*?/
>               const origExternals = [...config.externals]
>               config.externals = [
>                 (context, request, callback) => {
>                   if (request.match(antStyles)) return callback()
>                   if (typeof origExternals[0] === 'function') {
>                     origExternals[0](context, request, callback)
>                   } else {
>                     callback()
>                   }
>                 },
>                 ...(typeof origExternals[0] === 'function' ? [] : origExternals),
>               ]
> 
>               config.module.rules.unshift({
>                 test: antStyles,
>                 use: 'null-loader',
>               })
>             }
> 
>             return config;
>           }
>         })
>       })
>     )
>   );
> ```

want to know what does this part means
```
config.module.rules.unshift({
                test: antStyles,
                use: 'null-loader',
              })
```

**Comment by koolamusic** [comment] 2020-06-10 11:21
PS: You may get an error when building with `mini-css-extract-plugin` about conflicting errors between styles. 

I am able to bypass this error by lazy loading antd components within my application, An example in NextJS would be to load in this manner

```js
const Menu = dynamic(() => import('antd/lib/menu'))
const MenuItem = dynamic(() => import('antd/lib/menu/MenuItem'))
```

Here I can use the Menu and Menu Item from antd in place or the `import {Menu} from 'antd'` syntax where `MenuItem` is `Menu.Item`

So far no issues with Conflicting order between styles"
**This applies if you are using less and the babel-import-plugin**

**Comment by balazsorban44** [comment] 2022-01-30 01:27
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
