### ISSUE TITLE
[dynamic] shouldn't loadingComponent just return null be default? 

### ISSUE THREAD

**Issue by rileybracken** [zeit/next.js#4058] opened 2018-03-26 15:48 UTC
Currently if you are using `next/dynamic` it will return `Loading...` everywhere. I think that it should just return `null` by default that way you aren't forcing everyone to override `Loading...` (I assume everyone would). Instead if they want to create their own component they can. This would be super easy to do and I would be happy to add a PR for it.

Here is the line of code in question:
https://github.com/zeit/next.js/blob/canary/lib/dynamic.js#L32

**Comment by timneutkens** [comment] 2019-06-28 10:02
Fixed in #7543

**Closed** 2019-06-28 10:02 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 13:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
