### ISSUE TITLE
Warn on using getInitialProps in child components 

### ISSUE THREAD

**Issue by masives** [zeit/next.js#6401] opened 2019-02-22 10:02 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
In [documentation](https://nextjs.org/docs#fetching-data-and-component-lifecycle) we see that the `getInitialProps` method shouldn't be used outside of `/pages` directory. This was a little surprise for me as I didn't notice this note in the first read of docs. 

## Describe the solution you'd like
If `getInitialProps` is used in child component of `/pages` component it should throw error like `you're using getInitialProps in child component, which can introduce issues please see documentation for more information `

## Describe alternatives you've considered
adding seperate getInitalProps section to docs to highlight the gotchas

**Comment by timneutkens** [comment] 2019-02-22 11:15
It's actually hard to do this because it's valid for the user to implement a higher order component that implements getInitialProps. I do think it would be a huge help for new users to have a warning for this, so maybe we need to have a way to opt-out of the warning 🤔

**Comment by masives** [comment] 2019-02-24 19:09
Thanks for pointing it out! The issue I have is I feel it's not obvious enough that this shouldn't be used in child components. Is there currently a way to test if getInitialProps is being called in child component? If not maybe adding more info to documentation on this method would be enough

**Comment by timneutkens** [comment] 2019-08-09 15:42
Going to close this in favor of a RFC @timer is drafting.

**Closed** 2019-08-09 15:42 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
