### ISSUE TITLE
Unable navigate, when using `@zeit/next-sass`

### ISSUE THREAD

**Issue by talentedandrew** [zeit/next.js#6874] opened 2019-04-03 10:18 UTC
# Bug report
Unable to navigate to another route when using `@zeit/next-sass` in version `8.0.4`.

## To Reproduce

On clicking the link from index page, it doesn't route to about page(when using `@zeit/next-sass`). But after removing (`@zeit/next-sass`), it works as expected.

This unusual behaviour happens on client side. When going directly to the about page, it works but still navigation does not work on client side.

`/pages/index.js`
```
import Link from "next/link";
const Index = () => (
  <div>
    <Link href="/about">
      <a>About Page</a>
    </Link>
    <p>Hello Next.js</p>
  </div>
);

export default Index;
```

`/pages/about.js`
```
import "../styles/about.scss";
function About() {
  return (
    <div>
      <p className="about">This is the about page</p>
    </div>
  );
}
export default About;
```

`styles/about.scss`
```
$font-size: 50px;

.about {
    font-size: $font-size;
}
```

`next.config.js`
```
const withSass = require("@zeit/next-sass");

module.exports = withSass();
```

## Expected behavior
It should be able to route to about page from index page on client side.

## System information
 - OS: macOS
 - Version of Next.js: 8.0.4
 - Node version : v10.13.0

**Comment by timneutkens** [comment] 2019-04-03 10:31
Duplicate of https://github.com/zeit/next-plugins/issues/282

**Closed by timneutkens** 2019-04-03 10:31 UTC

**Comment by talentedandrew** [comment] 2019-04-03 11:00
@timneutkens is there any fix for this?

**Comment by movingStars** [comment] 2019-04-24 08:31
This issue is not fixed.I still have this problem.
