### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by rodrigooler** [zeit/next.js#5550] opened 2018-10-29 18:35 UTC
There is a strange error occurring, I have created a HOC to check if the user is logged in or not and then proceed as follows.

```js
return <Component user = {user} {... props} />
```

The error is probably about `{... props}`, has anyone ever dealt with this problem?

One thing that happens is that this error only appears when I'm running `yarn build && yarn start`

![captura de tela 2018-10-29 as 15 34 58](https://user-images.githubusercontent.com/5496931/47672243-3eca0280-db90-11e8-985c-ab115b3a1cad.png)

**Comment by timneutkens** [comment] 2018-10-29 19:10
Potentially it's related to the spaces you're adding. Try this:

```
<Component user={user} {... props} />
```

Going to close this as it's not following the issue template.

**Closed by timneutkens** 2018-10-29 19:10 UTC

**Comment by rodrigooler** [comment] 2018-10-29 19:31
@timneutkens unfortunately it's not the space problem this started to become common in version 7.0.2

**Comment by rodrigooler** [comment] 2018-10-29 19:33
```js
import idx from 'idx'
import * as React from 'react'

import Loading from '~/atoms/Loading'
import Maintenance from '~/organisms/Maintenance'
import Dashboard from '~/pages/dashboard'
import Login from '~/pages/login'
import { initUser, IUser, user, userInitialState } from '~/states/userState'

interface IState {
  isLoading: boolean
  user: IUser
}

export default function withAuth(
  Page: React.ReactNode,
  isHome: boolean = false,
) {
  return class extends React.Component<{}, IState> {
    public state = {
      isLoading: true,
      user: userInitialState,
    }

    public componentDidMount() {
      // @TODO: Improve Reworm
      user.subscribe(user => this.setState({ user }))
      initUser()

      this.setState({ isLoading: false })
    }

    public render() {
      const {props} = this
      const { isLoading, user } = this.state

      const token = idx(user, _ => _.token)

      if (isLoading) {
        return <Loading render={isLoading} />
      }

      if (false) {
        return <Maintenance />
      }

      if (token && !isHome && Boolean(Page)) {
        return <Page user={user} {...props} />
      }

      if (token) {
        return <Dashboard user={user} {...props} />
      }

      if (!token) {
        return <Login {...props}/>
      }
    }
  }
}

```

**Comment by joshpitzalis** [comment] 2018-12-02 10:45
Not sure why this was closed. I'm having the same problem when using typescript.

**Comment by joshpitzalis** [comment] 2018-12-02 10:49
`import Layout from '../components/Layout';
// import Link from 'next/link';
import Steps from 'antd/lib/steps';
import { useState } from 'react';

const OnboardingSteps: React.SFC<{
  step: number;
}> = props => (
  <Steps current={props.step}>
    <Steps.Step
      title="Invite Your Partner"
      description="This is a description."
    />
    <Steps.Step
      title="Discard Shitty Missions"
      description="This is a description."
    />
    <Steps.Step title="Play" description="This is a description." />
  </Steps>
);

const Index = () => {
  const [step, changeStep] = useState(0);
  return (
    <Layout>
      <p className="f1 b tc">Welcome To Marital Bliss</p>
      <OnboardingSteps step={step} />
      <button onClick={() => changeStep(step + 1)}>Next</button>
    </Layout>
  );
};

export default Index;`

**Comment by joshpitzalis** [comment] 2018-12-02 10:50
if I remove the `const [step, changeStep] = useState(0);` line everything works fine. It doesn't like me retuning an object as the functional state component.

**Comment by joshpitzalis** [comment] 2018-12-02 10:56
unrelated, sorry.
I was using hooks with the default react 16.
`npm i react@next react-dom@next` fixed this.

**Comment by djyde** [comment] 2018-12-20 05:07
Same error: `TypeError: Object(...) is not a function`

I think it is because of the React Hooks.

```jsx
import { useState } from 'react'

function App() {
  const [ name, setName ] = useState('') // If I remove this line, it works well.

  return (
    <div />
  )
}

export default App

```

**Comment by phocks** [comment] 2019-10-10 21:23
I was getting this error using Next.js and for me it was caused by trying to destructure a function that didn't exist in an npm module. eg `import { loadRecaptcha } from "recaptcha-v3";` instead of `import { load } from "recaptcha-v3";` and then trying to run it in an async function.

**Comment by rodrigooler** [comment] 2019-10-11 00:51
@phocks I was able to resolve this error because of some disruption that was occurring in the HOC, so as I am no longer using this HOC the problem was resolved. 100% that was faulty in my code.

**Comment by Trapintrovert** [comment] 2021-02-20 20:36
@rodrigooler can you share how you resolve this please

**Comment by rodrigooler** [comment] 2021-02-24 20:07
Look @Trapintrovert  I don't remember how I solved this problem anymore. But post the code and the error that is appearing so that we can help you.

**Comment by Trapintrovert** [comment] 2021-02-25 07:40
Thank you for your response @rodrigooler  here is my code.
I'm using Next, and Redux


This is my HOC

`import React from 'react'
import { useRouter } from 'next/router'
import { connect } from 'react-redux'

const withPrivateRoute = Component => {
  const Auth = ({ auth: {isAuthenticated}}) => {
    // Login data added to props via redux-store (or use react context for example)
    const router = useRouter()

    // If user is not logged in, return login component
    if (!isAuthenticated) {
      return (
        router.push('/auth/Login')
      );
    }

    // If user is logged in, return original component
    return (
      <Component {...props} />
    );
  };

  return Auth;
};

const mapStateToProps = state => ({
  auth: state.auth
});


export default connect(mapStateToProps)(withPrivateRoute)
`


Here is the usage


`
import React, { useState} from 'react'
import { connect } from 'react-redux';
import { useRouter } from 'next/router'
import { Form, Container, Row, Col, FormGroup, Button } from 'reactstrap'
import FormInput from '../../components/FormInput/FormInput'
import Layout from '../../components/Layout'
import { registerUser } from '../../redux/actions/authActions'
import withPrivateRoute from '../../PrivateRoute/withPrivateRoute'

const initialState = {
    name: '',
    email: '',
    password: '',
    password2: ''
}

const Register = ({registerUser}) => {
    const router = useRouter()

    const [formData, setFormData] = useState(initialState)

    const { name, email, password, password2 } = formData;

    const handleChange = (e)=>{
        const { name, value } = e.target;
        setFormData({ ...formData, [name ] : value})
    }

    const handleSubmit = async (e) => {
        e.preventDefault()
        console.log(formData)
        registerUser(formData, router)
    }

    return (
        <Layout title="UniCrypto | Register">
            <section className="register">
                <Container>
                    <h4 className="register__heading">Register</h4>
                    <Row>
                        <Col sm="12" md={{ size: 6, offset: 3 }}>
                            <Form onSubmit={handleSubmit}>
                                <FormGroup>
                                    <FormInput
                                        type="text"
                                        name="name"
                                        value={name}
                                        id="name-input"
                                        placeholder="Your full name"
                                        handleChange={handleChange}
                                    />
                                </FormGroup>
                                <FormGroup>
                                    <FormInput
                                        type="email"
                                        name="email"
                                        id="email-input"
                                        value={email}
                                        placeholder="Your email"
                                        handleChange={handleChange}
                                    />
                                </FormGroup>
                                <FormGroup>
                                    <FormInput
                                        type="password"
                                        name="password"
                                        id="password-input"
                                        placeholder="******"
                                        value={password}
                                        handleChange={handleChange}
                                    />
                                </FormGroup>
                                <FormGroup>
                                    <FormInput
                                        type="password"
                                        name="password2"
                                        id="password-input2"
                                        placeholder="******"
                                        value={password2}
                                        handleChange={handleChange}
                                    />
                                </FormGroup>
                                <Button className="button-shadow" type="submit" size="md" block>Submit</Button>
                                
                            </Form>
                        </Col>
                    </Row>
                </Container>
            </section>
        </Layout>
    )
}

export default connect(null, {registerUser})(withPrivateRoute(Register))

`

Here is the error

`
TypeError: Object(...) is not a function
    at Module../pages/auth/Register.js (C:\React\unicrypto-front\.next\server\pages\auth\Register.js:4255:82)
    at __webpack_require__ (C:\React\unicrypto-front\.next\server\pages\auth\Register.js:23:31)
    at C:\React\unicrypto-front\.next\server\pages\auth\Register.js:91:18
    at Object.<anonymous> (C:\React\unicrypto-front\.next\server\pages\auth\Register.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
`

**Comment by afzalzbr** [comment] 2021-02-27 05:36
@Trapintrovert I'm having the same issue last week and now as well.
Can you tell me if you got it solved?

**Comment by Trapintrovert** [comment] 2021-03-03 21:38
@afzalzbr i didn't use HOC anymore, i had to use next-auth context. This article helped me out `[here](https://blog.logrocket.com/how-to-use-nextauth-js-for-client-side-authentication-in-next-js/)`
