### ISSUE TITLE
Dynamic import() fails in next 5.xx

### ISSUE THREAD

**Issue by lkostrowski** [zeit/next.js#3775] opened 2018-02-12 10:45 UTC
I have been using this piece of code to asynchronously load one of heavy component on my client side. It was working like a charm:

`
const DynamicChart = dynamic(
    import('../components/LineChart/LineChart'),
    {
        loading: () => <SectionPlaceholder><Loader /></SectionPlaceholder>,
        ssr: false,
    },
);
`

Since update to v5.0.0 I get webpack error, but only when I open the parent page from frontend route. When I directly load from server, it get's loaded. When I get it once (from first load) and go back to this page on frontend, it works too.

This is the error I get:
![image](https://user-images.githubusercontent.com/9268745/36093000-8e62f87e-0fe9-11e8-9023-cc8f1f391b59.png)

I tried `import(...).then(...).catch(...)` but none of chains were triggered.

The problem is that I can't reproduce it always.

I'm also using next-routes if that matters

I assume that problem occurs because of `undefined` part in webpack. Any ideas how to debug the cause?

My package dependencies:

```
 "dependencies": {
    "babel-plugin-styled-components": "^1.5.0",
    "dotenv": "^5.0.0",
    "dotenv-webpack": "^1.5.4",
    "enzyme": "^3.3.0",
    "eslint-plugin-jest": "^21.7.0",
    "express": "^4.16.2",
    "glamor": "^2.20.40",
    "glamorous": "^4.11.4",
    "htmlescape": "^1.1.1",
    "isomorphic-fetch": "^2.2.1",
    "lodash": "^4.17.5",
    "next": "^5.0.0",
    "next-redux-wrapper": "^1.3.5",
    "next-routes": "^1.3.0",
    "polished": "^1.9.2",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-extras": "^0.5.0",
    "react-icons": "^2.2.7",
    "react-markdown": "^3.2.0",
    "react-modal": "^3.1.12",
    "react-no-ssr": "^1.1.0",
    "react-redux": "^5.0.6",
    "react-sizeme": "^2.3.6",
    "recharts": "^1.0.0-beta.10",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0",
    "reselect": "^3.0.1",
    "socket.io": "^2.0.4",
    "socket.io-client": "^2.0.4",
    "yargs": "^11.0.0"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^3.3.12",
    "@storybook/addon-info": "^3.3.12",
    "@storybook/addon-links": "^3.3.12",
    "@storybook/addons": "^3.3.12",
    "@storybook/react": "^3.3.12",
    "@types/enzyme": "^3.1.8",
    "@types/jest": "^22.1.1",
    "@types/next": "^2.4.7",
    "@types/node": "^9.4.1",
    "@types/react": "^16.0.36",
    "@types/recharts": "^1.0.13",
    "@types/reselect": "^2.2.0",
    "@types/socket.io": "^1.4.31",
    "@types/storybook__react": "^3.0.6",
    "babel-core": "^6.26.0",
    "babel-eslint": "^7.2.3",
    "babel-plugin-recharts": "^1.1.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babili-webpack-plugin": "^0.1.2",
    "console-probe": "^2.0.4",
    "create-component-app": "^1.6.2",
    "eslint": "^4.17.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-babel": "^4.1.2",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.6.1",
    "eslint-plugin-styled-components-config": "0.0.2",
    "jest": "^22.1.4",
    "prop-types": "^15.6.0",
    "redux-devtools-extension": "^2.13.2",
    "webpack-bundle-analyzer": "^2.10.0"
  }
```

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Component gets loaded every time

## Current Behavior
Sometimes component is not loaded and webpack tries to load something with `undefined` in name

**Comment by aputinski** [comment] 2018-02-12 21:25
I've created a test case that I can consistently reproduce https://github.com/aputinski/next-dynamic-import-test-case

**Comment by rauchg** [comment] 2018-02-12 23:56
Thanks for the nice reproducible test case @aputinski. We'll take a look!

**Comment by arunoda** [comment] 2018-02-13 03:35
@aputinski @lkostrowski 
Thanks for the detailed error report and for the sample repo.
Yes. I can reproduce the error.

We got this due to the the importing module is located inside the `pages` directory.
As a quick fix, try to move those modules outside of `pages` directory and import.

Like this:

```
import React from 'react';

export default class extends React.Component {
  static async getInitialProps() {
    const post = await import('../lib/post.json')
    return {
      post
    }
  }
  render () {
    return <h1>{this.props.post.title}</h1>
  }
}

```

**Comment by lkostrowski** [comment] 2018-02-13 10:22
Hi guys, thanks for input.

Unfortunately there must be different reason than @aputinski posted.
Let me paste my simplified page:

```
const DynamicChart = dynamic(
    import('../components/LineChart/LineChart')
        .then((c) => {
            console.log('Component loaded');
            return c;
        }).catch(err => console.log(err)),
    {
        loading: () => <SectionPlaceholder><Loader /></SectionPlaceholder>,
        ssr: false,
    },
);

class Dashboard extends React.Component {
    static async getInitialProps() {
        return {};
    }

    render() {
        return (
            <UserArea>
                <Grid>
                    <DashboardSection>
                        <DynamicChart />
                    </DashboardSection>
                    <DashboardSection>
                        <DynamicChart />
                    </DashboardSection>
                </Grid>
            </UserArea>
        );
    }
}
```

So 
1: I create dynamic in module scope 
2: I load component from different directory

As I said before I have problem to reproduce it all the times

I will do some checks today:
1: I will try to wrap this page with another component (I would have done it anyway but I'm working on prototype)
2: I will check f.e if moving dynamic() factory to getInitialProps() helps

**Comment by lkostrowski** [comment] 2018-02-13 11:46
Ok I have new input.
Changing structure to more nested seems to make no difference.

However I detected how to accurately reproduce problem. It happens only after first server start (dev or prod), so it's enough to force server to build page again and chunks are built successfully. Even if I refresh page on another view and go to page with dynamic components, they are build well. 

Isn't it connected to server caching? I don't know what's happening under the hood, but looks like page is server before chunks created?

Can I provide any more information?

**Comment by aputinski** [comment] 2018-02-13 13:54
@arunoda Moving the file still produces the same error, but as @lkostrowski said, it only happens upon first starting the server. Refreshing the page or starting on that page results in no errors.

**Comment by aputinski** [comment] 2018-02-13 13:58
I've also tried giving the imported file a hard-coded chunk name using `/* webpackChunkName */`

**Comment by aputinski** [comment] 2018-02-20 18:17
@arunoda If you can give me a few pointers on where to start, I can take a stab at debugging the issue.

**Comment by gerhardsletten** [comment] 2018-02-23 14:57
I am only experience this in dev-mode, and here its happening on each new route in the app:

* Start with `npm run dev`, and visit localhost:3000 (ok)
* Navigate to /route-b (fails with error above)
* Hard refresh /route-b (ok)
* Navigate to /route-c (fails with error above)
* Hard refresh /route-c (ok)

Each route in my app has a dynamic require for the component used. Get the same error in the examples `with-dynamic-import` by initially visit [localhost:3000/about](http://localhost:3000/about) and the Home-link. But as said, only in dev-mode.

**Comment by lkostrowski** [comment] 2018-02-23 15:22
@gerhardsletten good that you mentioned that - just check and **I also see this error on dev server**
uff

**Comment by PaulRBerg** [comment] 2018-04-06 22:02
Playing around with `6.0.0-canary.3` and I can confirm it's still the same.

**Comment by lolcoolkat** [comment] 2018-04-10 17:27
I'd also like to point out.. this bug only occurs during development.. the production build works fine with loading chunks.

**Comment by zhengqingxin** [comment] 2018-04-11 06:27
Anyone has a temporary solution ?

**Comment by zhengqingxin** [comment] 2018-04-11 09:11
Can I disable dynamic import in development mode and enable it in production? 
I try it as below, but it seems disabled dynamic import in both development and production. 
```js
const isDev = process.env.NODE_ENV !== 'production'
const PCMenu = isDev ? require('./pc/Menu').default : dynamic(import('./pc/Menu'))
```

**Comment by zhengqingxin** [comment] 2018-04-11 09:59
I use With No SSR in development mode as a temporary solution
```js
const isDev = process.env.NODE_ENV !== 'production'
const PCSearch = dynamic(import('page/pc/index/Search'),{ ssr: !isDev })
```

**Comment by dcalhoun** [comment] 2018-04-30 02:05
@arunoda I created another [test case](https://github.com/dcalhoun/nextjs-dynamic-import) where I'm experiencing this same error. You're proposed changes (i.e. moving the file out of the `pages` directory) did not help. Is there any other guidance for resolving this? Thanks!

**Comment by brad-decker** [comment] 2018-05-03 19:41
@arunoda having this issue on Next 6, exact same behavior with the exception of ssr: false does not help. If i hit the route with a dynamic import directly all is fine. If i hit it as a routing even within the app it throws errors for every dynamic import:

![screen shot 2018-05-03 at 2 40 33 pm](https://user-images.githubusercontent.com/4448075/39599009-032279a2-4ee0-11e8-9f7c-a199f82b97ec.png)

**Comment by brad-decker** [comment] 2018-05-04 01:03
this issue is being reported in several places with different descriptions. #4175 #4059 etc.

If i run next build before next i don't hit the same issue as before. Its like the dev server is trying to hit files in the main build folder instead of the ephemeral files created in dev.

**Comment by vjpr** [comment] 2018-05-07 00:56
Also be aware that errors are silenced in dynamic components with {ssr: false}. See https://github.com/zeit/next.js/pull/3009.

**Comment by stramel** [comment] 2018-05-16 15:19
I am also running into this error getting `Error: Loading chunk 6 failed.` This was my import statement with `dynamic`.

```
const Map = dynamic(import('../../components/Map'), {
  ssr: false,
})
```

I swapped it out for a raw `import` statement and still had the issue, I don't believe this is related to the `dynamic` that Next.js offers but more of something with the webpack config.

```
class A extends React.Component {
  constructor(props) {
    super(props)
    this.state = { module: null }
  }
  componentDidMount() {
    import('../../components/Map').then(module => this.setState({ module: module.default }))
  }
  render() {
    const { router } = this.props
    const { module: Map } = this.state

    return (
      <div>
        {Map && <Map />}
      </div>
    )
  }
}
```

**Comment by stramel** [comment] 2018-05-17 05:38
I'm curious if there is a way instead of trying to parse the import ourselves, if we could just pass off as much processing as possible to the import to webpack's Parser? That would probably allow dynamic imports with Computed module specifiers.

**Comment by eli0shin** [comment] 2018-05-24 03:55
After a couple hours of banging my head against the wall, I found that by using the multi-component example for `import()` from the docs and exporting the wrapper, the error goes away.

Not the prettiest solution, but the api functions as expected and there are no more errors

**Comment by jesstelford** [comment] 2018-06-04 06:28
@eli0shin do you have a concrete code example of before vs after for that fix?

**Comment by eli0shin** [comment] 2018-06-04 06:55
I realized that I still get errors occasionally in development, before it wasn't even working in production.
It is worth noting that `loaded-component` is not capable of being loaded on the server and had to be loaded in asynchronously inside on a component that skips the server render.

```
import React, { Component } from 'react';
import dynamic from 'next/dynamic';

const Loader = dynamic({
  modules: () => {
    const LoadedComponent = import('loaded-component');
    return { LoadedComponent };
  },
  render: (props, { LoadedComponent }) => (
    <Wrapper
      LoadedComponent={LoadedComponent}
      {...props}
    />
  ),
  ssr: false,
});

const Wrappper Wysiwyg  = ({LoadedComponent}) =>{
    const { LoadedComponent } = this.props;
    return (
      <LoadedComponent />
    );
  };

export default Loader;

```

**Comment by jesstelford** [comment] 2018-06-04 12:34
That's a shame, thanks for sharing the partial workaround though! 👍

**Comment by arnaud-brun** [comment] 2018-06-05 09:32
Hi ! I encounter the related issue when working with `react-pdf` which cannot be rendered outside the client. So my first thought was to use dynamic.

I think I solved the problem with `getInitialProps` function.
Here is a snippet :

```
class PdfViewer extends React.PureComponent {
  constructor(props) {
    super(props);
  }

  render() {
    if (this.props.isServer)
      return (<Loader />)

    return (
      <div>
        <div className="document">
          <Document
            file={data}
            rotate={rotate}
            onLoadSuccess={this.onDocumentLoad}
            >
            <Page pageNumber={pageNumber} scale={scale}/>
          </Document>
        </div>
     )
  }
}

PdfViewer.getInitialProps = async function(context) {
  const isServer = typeof window === 'undefined'
  return { isServer }
}
```

I hope this will help !
Still looking for a proper solution with dynamic feature

**Comment by mherodev** [comment] 2018-06-06 07:35
I am also experiencing this issue. It's important to note that it didn't occur in Next 3, and possibly Next 4. Some regression was introduced since then.

**Comment by akshayjai1** [comment] 2018-06-17 05:32
May be this chunk missing error is resulting due being not present either server side or cache, since if it were nextjs or webpack related error, i see no rational that following three urls( these are just chosen for illustration) always result in blank page.

http://localhost:3000/profile/3966689/ij
http://localhost:3000/profile/619474/OA_2003
http://localhost:3000/profile/2335466/Twit

I have no info regarding redis cache or server side, so cannot comment on that part.

**Comment by zvictor** [comment] 2018-06-20 15:20
This bug seems to have been underrated. I would like to emphasise that such bug **makes the dynamic imports feature totally useless** and therefore I would suggest reestimating it's importance for this project.

If it is not possible to foresee a fix for it in the short term, which is totally fine and understandable, we should then hide it in the docs to avoid more frustration and more issues being reported from new users trying it out.

@timneutkens would you be the right person to take a look at that?

**Comment by imagine10255** [comment] 2018-06-22 09:43
I have also encountered this problem, I am trying to find this issue

**Comment by vjpr** [comment] 2018-06-28 15:14
`build/static/commons/manifest.js` is recompiled many times while the app runs.

It is configured by the CommonsChunkPlugin here: server/build/webpack.js:302.

The issue appears to be a race condition whereby a stale `manifest.js` is retrieved from the server.

There is a line in the `manifest.js` file that contains all the available chunks:

```
/******/ 		script.src = __webpack_require__.p + "" + ({"0":"main.js","1":"bundles/pages/_document.js","2":"bundles/pages/_app.js","3":"bundles/pages/_error.js","5":"bundles/pages/analytics.js","6":"bundles/pages/overview.js","7":"chunks/_quantitec_intranav_map_0b0839261db7b60c6ddf2824cfd4e835","8":"bundles/pages/map.js"}[chunkId]||chunkId) + "-" + {"0":"a03f371cba25b2a7a353","1":"78550462ac237623af14","2":"ce770dc184e8107d9392","3":"a8b57bdb879379391237","5":"783eb7ab48d1525905aa","6":"3a46e0123295a0cdeb4a","7":"5deeabe4c6c6987dbbb5","8":"a0bedc5798c3e304bf3c"}[chunkId] + ".js";
```

The reason `undefined` shows up is because the chunk's hash is not included in the `manifest.js` file.

You should find that reloading the page used `cmd+r` makes the dynamic component show up.

If you look at `build/static/commons/manifest.js` before and then just after you try to load the dynamic component, you will see that your chunk appears there, but a stale version is used by the client.

---

@timneutkens @ptomasroos Would be great if you could shed light on how this is suppose to work.

**Comment by timneutkens** [comment] 2018-06-28 15:39
This issue will be fixed with webpack 4.

**Comment by vjpr** [comment] 2018-06-28 15:42
@timneutkens When do you think this will be released in next? Weeks or months?

Just wondering whether its worth me trying to find a fix for it.

**Comment by mjanssen** [comment] 2018-06-28 16:10
Dynamically importing modules in `componentDidMount` using `System.import('module');` seems to work while developing. However, when running a production build, the file seems not to be loaded correctly. When using the `dynamic` import from `next/dynamic` it doesn't seems to be functional during developing.

**Comment by vjpr** [comment] 2018-06-28 17:37
There is a workaround here: https://github.com/zeit/next.js/issues/4642#issuecomment-399151228

**Comment by mjanssen** [comment] 2018-06-28 18:36
The workaround is not functional (or I'm implementing it wrongly).

We've got:

```
> lib/common.js

const dynamics = () => [import('flickity')];
```

```
> Module using flickity
import '../../lib/common'

class A extends React.Component {
  async componentDidMount() {
    const Flickity = await System.import('flickity');
  }
  ...
}
```

But the reference to the Flickity module still breaks.

Note. The reason we're importing Flickity dynamically is because right now they instantly rely on `window`, which is obviously not available during SSR.

**Comment by timneutkens** [comment] 2018-06-28 18:50
The reason I'm saying it'll be solved when webpack 4 lands, is that I'm currently reworking the whole next/dynamic implementation so that it does nothing "special" and will just use default webpack `import()` which it doesn't currently. This will allow for setting the chunk name comment etc. And also solve this issue.

**Comment by vjpr** [comment] 2018-06-29 12:53
@mjanssen I just tried it out and it works.

Try using: 

```
import dynamic from 'next/dynamic'

const Flickity = dynamic(import('flickity'), {ssr: false}))
```

The idea with the workaround is to make sure that `import('flickity')` is in all your pages so that when loading any SSR page, the `manifest.js` will contain references to all dynamic chunks it will need in the future.

**Comment by stramel** [comment] 2018-06-29 18:30
I moved the `import './lib'` to my `_app.js` and it seems to be working

**Comment by mjanssen** [comment] 2018-06-29 19:11
All right, so your fix works @vjpr, thanks. However, I've used the 'forbidden fruit' from React, to pass a `ref={}` to a component and call functions in the mounted component. The functions within the component are not passed over when dynamic importing the component.

So:

```
> Slider.js

class Slider extends React.Component {
  next = () => {
    // Slide to next slide
  };

  prev = () => {
    // Slide to next slide
  };

  render() {
    ...
  }
}

> ClassUsingSlider.js

import dynamic from 'next/dynamic';

const Slider = dynamic(import('./Slider'), {ssr: false});

class ClassUsingSlider extends React.Component {
  onClick = () => {
    this.slider.next();
  };

  render() {
    return <Slider ref={c => (this.slider = c)} />;
  }
}
```

Other solutions are welcome though ;)

**Comment by vjpr** [comment] 2018-07-24 14:59
Found the cause https://github.com/webpack/webpack/issues/4842#issuecomment-407437764.

**Comment by timneutkens** [comment] 2018-07-25 11:39
Going to re-open, I tried solving this yesterday with @vjpr but ran into more issues with `__webpack_require__.e` needing some other bits of code that weren't there.

**Closed** 2018-07-26 10:38 UTC
Labels: Type: Bug

**Comment by coderwassananmol** [comment] 2019-04-19 12:09
I just installed the latest 8.1.0 version and it is still giving me error on dynamic import.
`import('./noop'); // Support EventSource on Internet Explorer 11`

**Comment by PetrSnobelt** [comment] 2019-05-15 17:18
It is weird, because `import('./noop'); // Support EventSource on Internet Explorer 11` happen to me also after upgrade to latest 8.1.0 and I do not use dynamic import.

**Comment by timneutkens** [comment] 2019-05-16 09:30
Not sure how you ended up on an issue that is almost 1 year old and closed, has 28 participants that are being pinged etc.

You're looking for https://github.com/zeit/next.js/issues/6240

I'm going to lock this issue as it was resolved.
