### ISSUE TITLE
Adding Typescript loader in next.config.js

### ISSUE THREAD

**Issue by jagreehal** [zeit/next.js#607] opened 2017-01-01 22:59 UTC
With #222 merged any ideas how to add a loader for TypeScript in next.config.js?

I've tried adding a TypeScript specific loader like this 

```
const path = require('path');
const nextPagesDir = path.join(__dirname, 'pages');

const typescriptLoader = {
  test: /\.ts(x?)$/,
  loader: ['ts-loader'],
  exclude: /node_modules/,
  include: [
    nextPagesDir
  ]
};

module.exports = {
  webpack: (config) => {
    config.module.rules.push(typescriptLoader);
    return config;
  }
}
```

but assume additional changes need to be made as well as additional entries for hot loading etc.

Another question is should the TypeScript loader be used in with babel e.g.

`loaders: ['babel-loader', 'ts-loader']`

If so I'd need to apply the same babel options as in webpack.js.

**Comment by rauchg** [comment] 2017-01-01 23:26
This would be a _terrific_ example to add! `./examples/with-typescript`

**Comment by giacomorebonato** [comment] 2017-01-15 22:24
I think that now the problem is that Next is looking only for files with .js extension in the pages folder, but with TypeScript we have .tsx

**Comment by timneutkens** [comment] 2017-01-17 21:43
Duplicate of #96. Closing in favor of that one.
Regarding the extensions (.ts/.tsx). There is a comment about adding custom extensions here: https://github.com/zeit/next.js/issues/544 (at the bottom)

**Closed by timneutkens** 2017-01-17 21:43 UTC

**Comment by nelak** [comment] 2017-06-15 15:52
I was able to get this working in https://github.com/zeit/next.js/pull/2250 if anyone wants to take a look a it
