### ISSUE TITLE
getInitialProps is being called client side with Automatic Static Optimization disabled

### ISSUE THREAD

**Issue by dijs** [zeit/next.js#10546] opened 2020-02-16 11:21 UTC
# Bug report

## Describe the bug

When a user navigates back/forward in history, `getInitialProps` is being called on the client-side which throws an error.

Unless I am misunderstanding something, this should never be called when Automatic Static Optimization is disabled, since all pages should be server side rendered.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Disable Automatic Static Optimization
2. Load page with `getInitialProps` 
3. Navigate away and back

## Expected behavior

Should not call `getInitialProps` client side

## System information

- Version of Next.js: 9.2.1

**Comment by lfades** [comment] 2020-02-17 19:31
`getInitialProps` is called in the browser for client-side navigations with `Link` and `next/router`; and in the server for the first render, so such behavior is expected.

You may want to check for `getServerProps`, currently experimental: https://github.com/zeit/next.js/issues/9524 - but it will be released very soon.

**Closed by lfades** 2020-02-17 19:31 UTC

**Comment by balazsorban44** [comment] 2022-01-30 13:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
