### ISSUE TITLE
with-firebase-authentication error on npm run dev

### ISSUE THREAD

**Issue by talkaboutdesign** [zeit/next.js#7003] opened 2019-04-10 19:17 UTC
# Bug report

when running sample project I get the following error. 

```
./node_modules/next/dist/client/next-dev.js 36:6
Module parse failed: Unexpected token (36:6)
You may need an appropriate loader to handle this file type.
| 
| 
> import('./noop'); // Support EventSource on Internet Explorer 11
| 
| if (!window.EventSource) {
> Ready on http://localhost:3000

```

Server obviously can't open anything. And subsequent log spits this out: 

```
TypeError: Cannot read property 'issuer' of null
    at findEntryModule (/Users/max/Documents/Developer/React/nextExpressFirebase/with-firebase-authentication-app/node_modules/next/dist/server/hot-reloader.js:60:16)
    at erroredPages (/Users/max/Documents/Developer/React/nextExpressFirebase/with-firebase-authentication-app/node_modules/next/dist/server/hot-reloader.js:68:29)
    at HotReloader.getCompilationErrors (/Users/max/Documents/Developer/React/nextExpressFirebase/with-firebase-authentication-app/node_modules/next/dist/server/hot-reloader.js:310:33)
    at <anonymous>


```

**Comment by DianeX** [comment] 2019-04-12 14:15
Me too, I have the same error when I am learning the [Lazy loading modules ](https://nextjs.org/learn/excel/static-html-export/deploying-the-app) . Now waiting for help !

**Comment by SvanBoxel** [comment] 2019-04-13 18:17
Same here! For the time being, I fixed it by commenting out line 36 in `./node_modules/next/dist/client/next-dev.js`

**Comment by fcaplette** [comment] 2019-04-13 18:19
I have the same error, only I am not using firebase:

`Failed to compile.

./node_modules/next/dist/client/next-dev.js 48:6
Module parse failed: Unexpected token (48:6)
You may need an appropriate loader to handle this file type.
| // The runtimeChunk can't hot reload itself currently to correct it when adding pages using on-demand-entries
| 
> import("./noop"); // Support EventSource on Internet Explorer 11
| 
| if (!window.EventSource) {
> Ready on http://localhost:3000
`

**Comment by DianeX** [comment] 2019-04-13 19:49
the real problem here is that when you open the noop.js file, there is nothing. Its content is `` "use strict"``
and that's all, nothing more. Or it is already declared in the line 1 of this next-dev.js.

**Comment by timneutkens** [comment] 2019-04-14 09:56
Duplicate of https://github.com/zeit/next.js/issues/6240

> the real problem here is that when you open the noop.js file, there is nothing. Its content is "use strict"

Actually the issue is a bug in `npm`, it's described in #6240 🙏

**Closed** 2019-04-14 09:58 UTC
