### ISSUE TITLE
A cleaner way to add plugins

### ISSUE THREAD

**Issue by mlescaudron** [zeit/next.js#9743] opened 2019-12-14 03:32 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

When you load a lot of plugins, the next.config.js start to be kind of messy.

Example:
```
const withSass = require("@zeit/next-sass");
const withFonts = require("next-fonts");
const withCss = require("@zeit/next-css");
const withPurgeCss = require("next-purgecss");
const TerserPlugin = require("terser-webpack-plugin");
const withOffline = require("next-offline");
const optimizedImages = require("next-optimized-images");
const { whitelistClassPurgeCss } = require("components-translations");

const OptimizeCSSAssetsPlugin = require("optimize-css-assets-webpack-plugin");
module.exports = {
  enableSvg: true,
  ...withOffline(
    optimizedImages(
      withCss(
        withPurgeCss(
          withFonts(
            withSass({
              enableSvg: true,
              webpack(config, options) {
                // Text && CSS Optimization
                config.optimization.minimize = true;
                config.optimization.minimizer.push(new TerserPlugin());

                config.optimization.minimizer.push(
                  new OptimizeCSSAssetsPlugin({
                    cssProcessorPluginOptions: {
                      preset: [
                        "default",
                        { discardComments: { removeAll: true } }
                      ]
                    }
                  })
                );

                return config;
              }
            })
          )
        )
      )
    )
  )
};

```

I discovered that there was a plugin called `next-compose-plugins` to improve the readability, but still, I didn't like it.

## Describe the solution you'd like

Finally created a  simple function who load the plugins in order: 

```
const loadNextPlugins = (n, l = 0) =>
  n.length - 1 === l ? n[l](nextConfig) : n[l](loadNextPlugins(n, l + 1));
```

Uniminifed version:
```
const loadNextPlugins = (plugins, index = 0) => {
  if (plugins.length - 1 === index) {
    return plugins[index](nextConfig);
  } else {
    return plugins[index](loadNextPlugins(plugins, index + 1));
  }
};
```

So a next.config.js file will look like this instead
```
const withSass = require("@zeit/next-sass");
const withFonts = require("next-fonts");
const withCss = require("@zeit/next-css");
const withPurgeCss = require("next-purgecss");
const TerserPlugin = require("terser-webpack-plugin");
const withOffline = require("next-offline");
const optimizedImages = require("next-optimized-images");
const { whitelistClassPurgeCss } = require("components-translations");
const OptimizeCSSAssetsPlugin = require("optimize-css-assets-webpack-plugin");

const nextConfig = {
  enableSvg: true,
  webpack(config, options) {
    config.optimization.minimize = true;
    config.optimization.minimizer.push(new TerserPlugin());

    config.optimization.minimizer.push(
      new OptimizeCSSAssetsPlugin({
        cssProcessorPluginOptions: {
          preset: ["default", { discardComments: { removeAll: true } }]
        }
      })
    );

    return config;
  }
};

const loadNextPlugins = (n, l = 0) =>
  n.length - 1 === l ? n[l](nextConfig) : n[l](loadNextPlugins(n, l + 1));

const plugins = [
  withOffline,
  optimizedImages,
  withCss,
  withPurgeCss,
  withFonts,
  withSass
];

module.exports = loadNextPlugins(plugins);
```

Just wanted to share that fast solution with you :)
Maybe a cleaner solution to add in the doc...

**Comment by ijjk** [comment] 2019-12-14 03:37
Hi, have you seen our RFC for plugins https://github.com/zeit/next.js/issues/9133

I'm gonna close this in favor of that, please leave any feedback on that thread

**Closed by ijjk** 2019-12-14 03:37 UTC

**Comment by rafaelalmeidatk** [comment] 2019-12-14 03:43
FWIW, while the RFC isn't out yet, you can simplify your code with https://github.com/cyrilwanner/next-compose-plugins

**Comment by balazsorban44** [comment] 2022-01-30 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
