### ISSUE TITLE
Blog Starter Example Suspense issue

### ISSUE THREAD

**Issue by jaredpalmer** [zeit/next.js#8892] opened 2019-09-28 12:56 UTC
# Examples bug report

## Example name

blog-starter

## Describe the bug

Client-side route changes are broken. When you click around on the client after the initial load, content is appended to a container instead of replacing it. Seems like there might be an issue with a Suspense component? 

![Kapture 2019-09-28 at 8 46 47](https://user-images.githubusercontent.com/4060187/65816670-c9661800-e1cc-11e9-87c2-38beb54bdc6c.gif)

<img width="842" alt="Screenshot 2019-09-28 08 50 18" src="https://user-images.githubusercontent.com/4060187/65816681-06320f00-e1cd-11e9-9ac5-f6e211db7e62.png">

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `npx create-next-app --examples blog-starter my-blog`
2. `now dev`
3. Click around

## Expected behavior

Links/content match routes

## System information

- OS: macOS
- Browser: Chrome
- Version of Next.js: 9.0.6

**Comment by timneutkens** [comment] 2019-09-28 13:01
Duplicate of https://github.com/zeit/next.js/issues/8886

9.0.7 was published to npm in the last 5 minutes 👍

**Closed by timneutkens** 2019-09-28 13:01 UTC

**Comment by jaredpalmer** [comment] 2019-09-28 13:11
Yep. it works now. Sorry about that.

**Comment by balazsorban44** [comment] 2022-01-31 03:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
