### ISSUE TITLE
Back button does not trigger getInitialProps after shallow routing followed by client transition

### ISSUE THREAD

**Issue by TonyHYK** [zeit/next.js#3999] opened 2018-03-13 02:44 UTC
Hi, I'm noticing that the back button doesn't trigger getInitialProps.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Steps to Reproduce
1. Go to https://wecured.com/condition/depression
2. Click on 'Symptoms' tab, which will trigger a shallow client transition.
3. Click on 'hay fever' on the left rail, which will trigger a client transition.
4. Press back.
Expected: page should end up on the depression page with symptoms tab.
Actual: page ended up on hay fever on the symptoms tab.

I did some debugging and found that this is because getInitialProps wasn't called.

**Comment by timneutkens** [comment] 2018-03-13 09:46
Duplicate of #3065

Searching for `Back button does not trigger getInitialProps`

**Closed by timneutkens** 2018-03-13 09:46 UTC
