### ISSUE TITLE
[BUG] How i can disable every HMR and Webpack log?

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [zeit/next.js#12021] opened 2020-04-19 13:29 UTC
bug
===

silent options from webpack documentation not working

How i can disable EVERY HMR log?

![image](https://user-images.githubusercontent.com/60403187/79688933-51d80300-825a-11ea-87f9-264c08f77bd2.png)

and in console i get `[ info ] [ info ] [ info ] [ info ] [ event ] [ info ] [ info ] [ info ] [ info ] [ info ] [ info ] [ info ] [ info ] [ info ] [ info ] [ info ] [ info ] [ info ] [ event ] [ event ] [ event ] [ event ] [ event ] [ event ] [ event ] [ event ] [ event ]  [ info ] [ info ] [ info ]  [ info ] [ info ] [ info ]  [ info ] [ info ] [ info ]  [ info ] [ info ] [ info ]` 

just spam that prevents reading important messages from the console

![image](https://user-images.githubusercontent.com/60403187/79689100-4cc78380-825b-11ea-8cd9-b41b4a285758.png)

this my server console and it ALL in **SPAM** =) and red `"get props"` text is MY console.log which carries the payload. and I have to pull these bits of information out of a huge mountain of spam. 👎  =(

![image](https://user-images.githubusercontent.com/60403187/79689189-d70fe780-825b-11ea-8214-b5fcd668cabc.png)

i use this:

![image](https://user-images.githubusercontent.com/60403187/79688948-7502b280-825a-11ea-85aa-8ef7689a49d2.png)

and i use this:

![image](https://user-images.githubusercontent.com/60403187/79689084-40dbc180-825b-11ea-8b4a-19f3d51576f1.png)

but i get in console `[HMR] [HMR] [HMR] [HMR] [HMR] [HMR] [HMR] [HMR]` output:

![image](https://user-images.githubusercontent.com/60403187/79688979-aa0f0500-825a-11ea-8433-29caceea468f.png)

how can I disable hmr log and indeed and the whole webpack logging once and for all? please help, I’ve been suffering a fight with this spam for a year now.

how to disable the ALL log on the client and on the server 
===

so that if I DO NOT WRITE ANYTHING to the console, then there IS NOTHING in the console at all. in general, not a single letter, even "server started on port bla bla bla" (I KNOW on which port I run the dev server, I don’t have autism, this tab does not even close, why should I read this reminder every time as if I'm mentally retarded? ahahah)  tell me how can I do this? =) I’m a fan of the console, I do debugging through the console, not through breakpoints, not through inspectors, but through the console. and all this spam prevents me from using MY console ((((  I’ve been suffering with this for 5 years, I can't stand it anymore.

![image](https://user-images.githubusercontent.com/60403187/79689435-839e9900-825d-11ea-9235-1d1db6d4ea8b.png)

p.s. my emotionality is of course a joke, but the problem is really relevant for many of these frameworks. "frameworkLog" and "debugLog" are logically different things, and we should not write them to the same journal console.log

**Comment by MaxmaxmaximusGitHub** [comment] 2020-04-19 13:41
how to disable the ALL log on the client and on the server so that if I DO NOT WRITE ANYTHING to the console, then there IS NOTHING in the console at all. in general, not a single letter, even "server started" so that it is not written! tell me how can I do this? =) I’ve been suffering with this for 5 years, I can't stand it anymore.

![image](https://user-images.githubusercontent.com/60403187/79689304-8f3d9000-825c-11ea-9ac0-a5b080ee153b.png)

**Comment by MaxmaxmaximusGitHub** [comment] 2020-04-19 13:45
temporary solution:

```javascript
let log = global.console.log;
global.console.log = function noop () { }
```

and just use `log` instead of `console.log`

but even so, some messages manage to get into the console before we use this hack.

**Comment by timneutkens** [comment] 2020-04-20 09:06
Closing as the issue template wasn't followed as asked for before.

**Closed by timneutkens** 2020-04-20 09:06 UTC

**Comment by MaxmaxmaximusGitHub** [comment] 2020-04-20 16:10
@timneutkens two fire extinguishers to this guy, at my expense

**Comment by MaxmaxmaximusGitHub** [comment] 2020-04-20 16:12
@timneutkens two fire extinguishers to this guy

**Comment by MaxmaxmaximusGitHub** [comment] 2020-04-20 16:19
@timneutkens I will obey your requirements, you are the boss https://github.com/zeit/next.js/issues/12052

**Comment by balazsorban44** [comment] 2022-01-30 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
