### ISSUE TITLE
Access environment variables in custom server

### ISSUE THREAD

**Issue by NewBieBR** [zeit/next.js#12269] opened 2020-04-28 07:07 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Environment variables are `undefined` in a custom server. For example in `server.js`
```js
...
const app = next({dev});
console.log(process.env.MY_ENV_VARIABLE);
...
```

In `next.config.js`:
```js
module.exports = {
  env: {
     MY_ENV_VARIABLE: 'hello',
  },
};
```

Output:
```bash
undefined
```

## Describe the solution you'd like

I would like to be able to use environment variable in a custom server.

## Describe alternatives you've considered
No

## Additional context
No

**Comment by timneutkens** [comment] 2020-04-28 08:51
I'll post the same reply as here, as it applies in the same way: https://github.com/zeit/next.js/issues/12254#issuecomment-620460451

If you want to create API endpoints it's recommended to use API routes: nextjs.org/docs/api-routes/introduction. API routes are automatically compiled through Next.js' compilation pipeline and allow you to use import/export syntax and a bunch of other syntax that hasn't landed in Node.js yet, similar to pages.

If you use a custom server you're basically handing off a request to Next.js and Next.js is unaware of the server existing, it also boots up after the server boots up, meaning we can't compile the server, hence why you can only use Node.js features and Node.js currently does not compile import syntax.

**Comment by NewBieBR** [comment] 2020-04-28 12:09
I want to use a custom server. 

This scenario is straight from the nextjs offical firebase authentication example. And is deployed on vercel. In server.js we need to use credentials from firebase.

Is there any alternative solution without pushing the private credentials to deploy?

**Comment by rachelgould** [comment] 2020-04-30 21:17
I'm dealing with this same issue right now

**Comment by jmaister** [comment] 2020-05-23 10:09
I did some workaround using 'dotenv' package. Same as Next.js does internally.

First install dotenv:

    yarn add dotenv

Then add the config reading into my custon server.js

    const dev = process.env.NODE_ENV !== 'production';

    const dotenv = require('dotenv');
    dotenv.config();
    if (dev) {
        dotenv.config({path: '.env.development'});
    }

    const PORT = process.env.FC_PORT;
    const startJobs = process.env.START_JOBS === 'true';


    const app = next({ dev });
    ...

**Comment by timneutkens** [comment] 2020-05-23 10:20
dotenv is already automatically supported when you run `next()`, closing this as the new environment support sort of covers it: https://nextjs.org/blog/next-9-4#new-environment-variables-support

**Closed by timneutkens** 2020-05-23 10:20 UTC

**Comment by coler-j** [comment] 2020-11-07 02:14
@timneutkens env variables do not seem to pass through custom server into client side code regardless of using `NEXT_PUBLIC` prefix. Is there tests that demonstrate this?

**Comment by kushalmahajan** [comment] 2020-12-18 10:52
Running custom server on next 10 and using `.env` or `.env.development` does not work. it is undefined.

Refer - https://github.com/vercel/next.js/issues/20271 for my setup details.

**Comment by feross** [comment] 2021-03-04 22:47
In case it's helpful to future Google searchers, you can hook into the existing Next.js `.env.local`, `.env`, etc. processing by including the following at the top of your custom server:

```js
// Load environment variables from .env, .env.local, etc. This explicit call
// into `@next/env` allows using environment variables before next() is called.
// More info: https://nextjs.org/docs/basic-features/environment-variables
import { loadEnvConfig } from '@next/env'
loadEnvConfig('./', process.env.NODE_ENV !== 'production')
```

**Comment by endrureza** [comment] 2021-07-03 06:57
> In case it's helpful to future Google searchers, you can hook into the existing Next.js `.env.local`, `.env`, etc. processing by including the following at the top of your custom server:
> 
> ```js
> // Load environment variables from .env, .env.local, etc. This explicit call
> // into `@next/env` allows using environment variables before next() is called.
> // More info: https://nextjs.org/docs/basic-features/environment-variables
> import { loadEnvConfig } from '@next/env'
> loadEnvConfig('./', process.env.NODE_ENV !== 'production')
> ```

this is the only one that works for me

**Comment by masontien** [comment] 2021-09-13 07:29
> [.env.local](https://nextjs.org/docs/basic-features/environment-variables)
```shell
MY_ENV_VARIABLE=hello
```


>   [server.js](https://nextjs.org/docs/advanced-features/custom-server)

```js
const app = next({ isDev })

app.prepare().then(() => {
  // To be exactly, you can access environment variables after next().prepare()
  console.log(process.evn.MY_ENV_VARIABLE)  // print  hello
})
```

**Comment by arnaugomez** [comment] 2021-10-04 09:48
> > [.env.local](https://nextjs.org/docs/basic-features/environment-variables)
> 
> ```shell
> MY_ENV_VARIABLE=hello
> ```
> 
> > [server.js](https://nextjs.org/docs/advanced-features/custom-server)
> 
> ```js
> const app = next({ isDev })
> 
> app.prepare().then(() => {
>   // To be exactly, you can access environment variables after next().prepare()
>   console.log(process.env.MY_ENV_VARIABLE)  // print  hello
> })
> ```

This worked for our project. Looks like environment variables only show up once the next.js app is prepared and the `prepare` method has been called.

**Comment by nemanjam** [comment] 2022-01-03 16:02
> 

Where is the reference docs for `import { loadEnvConfig } from '@next/env'`? I want to see more information about arguments.

**Comment by endrureza** [comment] 2022-01-03 16:21
> > 
> 
> Where is the reference docs for `import { loadEnvConfig } from '@next/env'`? I want to see more information about arguments.

its in here [Environment Variables](https://nextjs.org/docs/basic-features/environment-variables)

**Comment by nemanjam** [comment] 2022-01-03 17:08
> > > 
> > 
> > 
> > Where is the reference docs for `import { loadEnvConfig } from '@next/env'`? I want to see more information about arguments.
> 
> its in here [Environment Variables](https://nextjs.org/docs/basic-features/environment-variables)

I know that, I meant more detailed reference about arguments.

![image](https://user-images.githubusercontent.com/9990165/147958892-d4710c52-f6e6-4c6c-96df-c0464d045dcb.png)

**Comment by balazsorban44** [comment] 2022-02-02 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
