### ISSUE TITLE
Site get refresh/server restart while site running with https

### ISSUE THREAD

**Issue by stupidArnob** [zeit/next.js#8009] opened 2019-07-17 05:53 UTC
I host a site name mobipath.online . We had an api server at the same VPS but when we setup the server with SSL certificate. The nextjs hosted site(mobipath.online) get refresh after some time. We inspect the log. And its look like the nextjs server gets restarted.

**Comment by c0b41** [comment] 2019-07-17 10:06
because you are using development mode. [checkout](https://nextjs.org/docs#production-deployment)

**Comment by timneutkens** [comment] 2019-07-17 13:04
Going to close this as it does not follow the issue template.

**Closed by timneutkens** 2019-07-17 13:04 UTC

**Comment by balazsorban44** [comment] 2022-01-31 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
