### ISSUE TITLE
Typescript logging appears disabled in 9.4.0

### ISSUE THREAD

**Issue by nicholaschiang** [zeit/next.js#13027] opened 2020-05-18 02:08 UTC
# Bug report

## Describe the bug

I recently updated Next.js to `9.4.0` and I'm no longer seeing the Typescript compiler errors when I run my development server.

I was poking around [the release blog post](https://nextjs.org/blog/next-9-4#improved-log-output) and it seems as if the "improved logging" might have done away with a feature that I really need and enjoy (i.e. being able to see compiler errors before running `next build` is a must-have).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone the [typescript example repository](https://github.com/zeit/next.js/tree/canary/examples/with-typescript) by running:
```
$ npm init next-app --example with-typescript with-typescript-app
```
2. Install dependencies and start a development server by running:
```
$ npm i && npm run dev
```
3. Notice that there are no more "Checking Typescript compilation..." logs

## Expected behavior

Users should be able to configure the Typescript logging but it should definitely be enabled by default (it's a super useful feature so one doesn't have to do a bunch of type fixes at the last minute before building).

## System information

- OS: Ubuntu 18.04.2
- Version of Next.js: 9.4.0
- Version of Node.js: 12.16.1

**Comment by zxfred** [comment] 2020-05-20 11:10
See this https://github.com/zeit/next.js/issues/12735#issuecomment-626869676

**Comment by Timer** [comment] 2020-05-20 14:19
Closing as duplicate of above

**Closed by Timer** 2020-05-20 14:19 UTC

**Comment by balazsorban44** [comment] 2022-01-30 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
