### ISSUE TITLE
Unable to find sass-loader in next.config.js

### ISSUE THREAD

**Issue by tankpower1** [zeit/next.js#11048] opened 2020-03-13 12:21 UTC
# Bug report

## Describe the bug

Hi,
for my project i needed to pass a variable from webpack to scss which i managed to do in v9.2.2 but since updating to 9.3.0 it doesn't seem to work and i can't seem to locate the sass-loader.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'next.config.js'
2. Add this code:

<pre>
webpack(config) {

        let isDev = ENVIRONMENT !== 'production';

        config.module.rules.forEach(rule => {

            if (rule.test && rule.test.toString().includes('.scss')) {

                rule.use.forEach(el => {

                    if (el.loader && el.loader === 'sass-loader') {

                        el.options.data = `$isDev: ${isDev};`;
                    }
                })

            }
        });

        return config;
    }
</pre>
## Expected behavior

It should work.
## System information

- OS: macOS
- Version of Next.js: 9.3.0

**Comment by timneutkens** [comment] 2020-03-14 09:32
See https://github.com/zeit/next.js/pull/11063

**Comment by tankpower1** [comment] 2020-03-16 07:47
So in v9.3.1-canary.4 sassOptions is supported and i can now pass custom variables to its options?

**Comment by timneutkens** [comment] 2020-03-16 08:23
No, it hasn't been merged, hence why the PR is `open`.

**Closed** 2020-03-16 09:55 UTC

**Comment by balazsorban44** [comment] 2022-01-30 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
