### ISSUE TITLE
Have next export work with relative paths

### ISSUE THREAD

**Issue by DaveStein** [zeit/next.js#6059] opened 2019-01-15 04:07 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
I was excited to see a static site generator in Next. I want to write a prototype of a site, which would end up using Next. I'd love the prototype to be static so I can zip it up and send to someone who isn't tech savvy unzip and run the html. The issue is that someone needs to make the html run on "server" ie `serve`

## Describe the solution you'd like
Allow an option for `next export` which lets things run without a server. As far as I can tell the main issue is the way things are routed, followed by the way clicking `<Link>` is counted.

## Describe alternatives you've considered
I tried detecting an environment variable to do an update like this:

`correctedHref = `file:///C:${prefix}${href}/index.html`

That made the `href=` point at an actual file, however clicking the link did nothing in the app, despite opening the link via source view showing what I wanted.

**Comment by timneutkens** [comment] 2019-01-15 11:17
I recently closed a similar issue to this one as it would involve a lot of work for very minimal gains.

**Comment by timneutkens** [comment] 2019-03-09 15:06
Seems to be a duplicate of #2581

**Closed by timneutkens** 2019-03-09 15:06 UTC
