### ISSUE TITLE
Next and Preact not work with serverless build

### ISSUE THREAD

**Issue by marcelalburg** [zeit/next.js#9848] opened 2019-12-27 10:56 UTC
# Bug report
If i use the latest next.js and latest preact together and described like in the documentation it doesn't work. Even i fixed the preact aliasing, i cannot build and run this setup in the serverless build target.

## Describe the bug

If i follow the installation readme of the preact plugin it results in the following error:

```
npm build
./node_modules/next/dist/client/index.js
Module not found: Can't resolve 'react' in 'node_modules/next/dist/client'
```

i was able to fix this error with a custom aliasing of preact but when i build and start next, the server generate an error like this:

```
npm run build
npm run start
Error: [object Object] is not a valid HTML tag name in <[object Object] value="[object Object]">
    at u (build/serverless/pages/index.js:7555:3347)
```

## To Reproduce

I created a git repo and was able to alias preact by myself. 

```
git clone https://github.com/marcelalburg/nextjs-preact.git
cd nextjs-preact
npm install
npm run build
npm run start
curl http://localhost:3000
```

## Expected behavior

I would like to run nextjs with preact on aws lambda / serverless without internal server errors - described above

## System information

- OS: macos
- Version of Next.js: 9.1.6
- NodeJs: v12.13.1

**Comment by romellogoodman** [comment] 2020-01-28 13:07
Related to #8188

**Comment by Timer** [comment] 2020-02-03 19:19
Duplicate of #8188

**Closed by Timer** 2020-02-03 19:19 UTC

**Comment by balazsorban44** [comment] 2022-01-30 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
