### ISSUE TITLE
Testing with Links

### ISSUE THREAD

**Issue by kristojorg** [zeit/next.js#12371] opened 2020-05-01 03:11 UTC
# Bug report

## Describe the bug

When testing with Jest and rendering a `<Link>` component, clicking the link fails with `No router instance found.` error because we are running outside of the browser.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

[Here is a codesandbox](https://codesandbox.io/s/recursing-lehmann-blvlq?file=/__tests__/testint-library.js) based on the `with-jest` example.

If you comment out `fireEvent.click` on the link, the tests will pass. The problem is, we should be able to click links in testing and make sure that something happened. For example, I want to test that my `<NavButton>` component, which is backed by a `Link`, actually routes the user properly.  

## Expected behavior

The test should pass, ideally navigating jsdom appropriately. 

When testing, we often need/want to closely replicate the browser environment. If we must mock the linking and routing behavior, it would be useful if Next provided a way to implement or mock the Router and Link contexts. For reference, when using react-router, after clicking the link, I can access the `history.location.pathname` and see that it has changed appropriately. 

I suppose it is possible to mock out all of `next/link`, but my personal philosophy is to avoid mocks unless absolutely necessary since production bugs often occur at integration points.

I also feel that this testing links should be made part of the `with-jest` example. 

## Screenshots

![image](https://user-images.githubusercontent.com/4398775/80778485-cd249900-8b25-11ea-94b2-2200ae116feb.png)

## Attempted solutions

I have searched the issues and attempted a few mentioned solutions, including:
1. mocking `useRouter` with a mock router object
2. providing mock `RouterContext` by importing the internal `RouterContext.Provider` component and wrapping my test in that. 

Neither of these work because it appears next is internally using a singleton router instance, which is unavailable in jsdom.

## My suggestion

I would suggest adding a `<NextTestContext>` component which provides the test context and environment necessary (such as the browser-only functionality) for testing. Allows passing in mock values for things like router. Not sure if this is possible or what you'd want, but if you point me in the right direction, I'm happy to submit a PR.

Alternatively, if this should be solved another way, I am happy to make a docs PR too. Just let me know. It seems there are many conflicting recs in the issues, it might be useful to have testing docs.

**Comment by Janpot** [comment] 2020-05-01 07:00
fyi: https://github.com/zeit/next.js/issues/5205

**Comment by timneutkens** [comment] 2020-05-01 08:48
Yeah this is a duplicate of #5205. If you want to test navigations it's generally better to do end to end testing using a real browser otherwise you just test if a "link works sort of" as you don't know if the click actually works and navigates correctly as the underlying page you link to could crash still.

**Closed by timneutkens** 2020-05-01 08:48 UTC

**Comment by kristojorg** [comment] 2020-05-04 03:13
Ok so your suggestion is to mock `next/link` in testing?

**Comment by balazsorban44** [comment] 2022-01-30 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
