### ISSUE TITLE
Has anyone gotten Material-UI 4 working?

### ISSUE THREAD

**Issue by mikepc** [zeit/next.js#7527] opened 2019-06-07 04:34 UTC
# Question about Next.js

So as an old school frontend guy, I've seen the javascript community go insane slowly over the last 4-5 years, but with the latest material-ui changes, I'm at my wits end. The current app I started a few months ago, it's a side project. It took me 3 nights to get next.js+redux+redux-saga+material-ui to work together well in their latest versions.

The app needs a stupid date picker, but the one that ships with material-ui is coyote ugly.  The material-ui team identified that and they introduced an @material-ui/pickers library, that only works with material-ui 4.x

It obviously didn't work with nextjs out of the box, but rather than going down the road of manhandling the app into getting material-ui working again in its latest version of crazy, I just wanted to know if anyone has had success with this thus far?

To be quite honest, my first reaction was to dump material-ui and switch to react-toolbox, but it depends on a sass implementation, which I got working with nextjs (thanks for that by the way!) But then the map component I'm using broke with the sass implementation. Tears. For real.

Thanks for the therapy session!

**Comment by timneutkens** [comment] 2019-06-07 06:20
The material-ui website is built on Next.js and @oliviertassinari tests all components with SSR I think 🤔

**Comment by oliviertassinari** [comment] 2019-06-07 09:21
> they introduced an @material-ui/pickers library, that only works with material-ui 4.x

@mikepc There is a working version of `@material-ui/pickers` with Material-UI v3:
`material-ui-pickers`. Not everybody knows it. You can find part of the documentation in https://github.com/mui-org/material-ui-pickers/tree/v2.2.4.

> It obviously didn't work with nextjs out of the box, but rather than going down the road of manhandling the app into getting material-ui working again in its latest version of crazy

I would encourage the following upgrade approach:
1. Remove all the custom code you have added to make Material-UI v3 works with Next.js.
1. Verify that everything works, at the exception of the [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content).
1. Upgrade to v4. 
1. Verify that everything works, at the exception of the FOUC.
1. Inline the critical CSS in the initial request, with, in your _document.js file: https://github.com/mui-org/material-ui/blob/2bfe66337db790cd89117072f16643ac9e62bec0/examples/nextjs/pages/_document.js#L57-L73.
1. Clean up the server-side styles: https://github.com/mui-org/material-ui/blob/2bfe66337db790cd89117072f16643ac9e62bec0/examples/nextjs/pages/_app.js#L10-L14
1. 🌈

Now, I understand your pain point, we often hear it. We used to have the same problem with Gatsby. It was solved for people with a single line change thanks to [gatsby-plugin-material-ui](https://github.com/hupe1980/gatsby-plugin-material-ui).
```diff
module.exports = {
  plugins: [
+   'gatsby-plugin-material-ui',
  ],
};
```

I'm eager to reproduce the same approach (moving the complexity away from people code into a shared package), but I don't know the best way to proceed.

@timneutkens is correct, https://material-ui.com is powered by Next.js.

**Comment by oliviertassinari** [comment] 2019-06-07 09:23
> But then the map component I'm using broke with the sass implementation. Tears. For real.

I'm curious in hearing more here! In Material-UI v5, we would like to have the option for people to use https://github.com/callstack/linaria. I would suspect CSS modules support is required for making it happen (I'm not sure, I haven't dive)

**Comment by mikepc** [comment] 2019-06-07 21:08
I got it working, createClassNames was removed from styles, I just pulled it out of where I was referencing it, and it did work. Thank you <3

**Comment by huv1k** [comment] 2019-06-11 13:33
@mikepc so did you fix your problem? Can we close it?

**Closed** 2019-06-11 16:55 UTC

**Comment by lorensr** [comment] 2019-08-17 05:00
If anyone else is upgrading from MUI v1, I used this example to update my integration 😄

https://github.com/mui-org/material-ui/blob/master/examples/nextjs/pages/

- `get-page-context.js` mostly gone, theme to `lib/theme.js`
- `MuiThemeProvider -> ThemeProvider`
- no more `JssProvider`
- new `MyDocument.getInitialProps`

**Comment by balazsorban44** [comment] 2022-01-31 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
