### ISSUE TITLE
8.0.0 - dynamic import causing 'You may need an appropriate loader...' error

### ISSUE THREAD

**Issue by dunika** [zeit/next.js#6240] opened 2019-02-11 10:11 UTC
# Bug report
Just upgraded to 8.0.0 and I'm really excited! I've run into an issue though that is preventing my project from compiling

## Describe the bug
So when I run `dev` I am getting the following issue

```
You may need an appropriate loader to handle this file type.
| 
| 
> import('./noop');
| var _window = window,
|     assetPrefix = _window.__NEXT_DATA__.assetPrefix;
```

It seems to be coming from `webpack  4.29.0` ([see here](https://github.com/webpack/webpack/issues/8656#issuecomment-456713191)). 

It looks like the issue was fixed with [this](https://github.com/zeit/next.js/pull/6137) which declared `acorn": "^6.0.5` as a dependency but the change doesn't seem to be present on [master](https://github.com/zeit/next.js/blob/master/packages/next/package.json)

Maybe I upgraded too soon?

**Comment by dimensi** [comment] 2019-02-11 10:18
I got same problem. Can't start develop mode. I updated npm to the latest version and also tried to install the acorn package, but did not help

**Comment by AndrewIngram** [comment] 2019-02-11 10:59
I have a different error related to imports which might have the same root cause:

```
/Users/andrewingram/Repositories/tego/website-next/node_modules/@babel/runtime-corejs2/helpers/esm/typeof.js:1
(function (exports, require, module, __filename, __dirname) { import _Symbol$iterator from "../../core-js/symbol/iterator";
                                                                      ^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
```

Everything is fine if I downgrade to next@7.0.3

**Comment by timneutkens** [comment] 2019-02-11 11:23
@AndrewIngram can you provide a reproduction? curious to look into that one. It sounds related to @babel/runtime

**Comment by incleaf** [comment] 2019-02-11 14:17
I'm facing the same error. Installing `acorn` doesn't work for me either. FYI, I use `ts-node` for running my express server.

**Comment by TomiTakussaari** [comment] 2019-02-11 14:50
For me this was fixed by upgrading @babel/core:

````
-        "@babel/core": "^7.1.0",
+        "@babel/core": "7.2.2",
```
For some reason we have that as direct dependency currently.

**Comment by cnasc** [comment] 2019-02-11 15:16
Experiencing same issue and error message. `@babel/core` is set to `"7.2.2"` so that may not be the issue.

**Comment by YESENE** [comment] 2019-02-11 15:21
For some reason we have that as direct,

**Comment by iaincollins** [comment] 2019-02-11 15:27
We are also seeing this issue and followed the threads for a workaround.

- Production (with `next build`) builds and runs fine.
- Running in development mode produces the same error as OP.
- We invoke Next.js programmatically (we use it with Express currently).
- Updating @babel/core to 7.2.2 did not resolve this for us.

Following the the issues linked in the thread and installing `webpack@4.28.4` and `@babel/core@7.2.2` as devDependancies **did** resolve this.

(This also resolved the error about the Acorn package, which we do not have as a direct dependancy.)

**Comment by YESENE** [comment] 2019-02-11 15:30
develop mode. I updated npm to the latest version and also tried to install the acorn package, but did not help.

**Comment by kpoelhekke** [comment] 2019-02-11 17:49
I had the same issue, also after updating `webpack` and `@babel/core`. Removing my `package-lock.json` and `node_modules` and doing a fresh install solved the issue.

**Comment by jescalan** [comment] 2019-02-11 18:18
Same issue here, unfortunately. Here's a replication: https://github.com/jescalan/nextjs-test/tree/je.canary

**Comment by jescalan** [comment] 2019-02-11 18:33
Just fixed with with a removal of `package-lock.json` and regenerate. The last commit on that branch shows which updates were made to `package-lock.json` -- hopefully this helps to pin down the cause!

**Comment by pdlug** [comment] 2019-02-11 18:44
Removing `node_modules` and `package-lock.json` then reinstalling resolved this for me as well.

**Comment by bitmap** [comment] 2019-02-11 19:11
Deleting `node_modules` and `package-lock.json` didn't resolve this for me, but installing `webpack@4.28.4` as a dev dependency did, as @iaincollins suggested.

**Comment by paulschneider** [comment] 2019-02-12 03:46
Also experiencing this problem but outside of this package; Downgrading to a lower version of node (v9.11 [a colleagues working version], installing webpack@4.28.4 and reinstalling node_modules fixed this for me.

**Comment by icflorescu** [comment] 2019-02-12 16:39
> I have a different error related to imports which might have the same root cause:
> 
> ```
> /Users/andrewingram/Repositories/tego/website-next/node_modules/@babel/runtime-corejs2/helpers/esm/typeof.js:1
> (function (exports, require, module, __filename, __dirname) { import _Symbol$iterator from "../../core-js/symbol/iterator";
>                                                                       ^^^^^^^^^^^^^^^^
> 
> SyntaxError: Unexpected identifier
> ```
> Everything is fine if I downgrade to next@7.0.3

Facing the same issue as @AndrewIngram on a complex project. The issue only appears for `next@8.0.0` in dev mode, not when compiling for production.

**Comment by shaunchurch** [comment] 2019-02-12 18:38
I ran in to the same issue. Removing both `node_modules` and `package-lock.json` and reinstalling _did_ fix it for me. It's important to remove both the directory and lock file before reinstalling, just in case that's the issue some are running in to.

**Comment by schabluk** [comment] 2019-02-12 19:08
I have the same behaviour in TypeScript files:
`error  in ./stores/index.ts

Module parse failed: Export 'IStore' is not defined (77:9)
You may need an appropriate loader to handle this file type.
|   return Store;
| };
> export { IStore, IStoreSnapshotIn, IStoreSnapshotOut };

 @ ./pages/_app.tsx 16:0-37 38:24-32 83:18-26
`

**Comment by timneutkens** [comment] 2019-02-12 19:17
@icflorescu it's impossible to solve the issue without a clear reproduction. Please provide one so that we can investigate further 🙏

**Comment by timneutkens** [comment] 2019-02-12 19:17
@icflorescu could you create a new issue for it (including reproduction) because it's not the same as this one 🙏

**Comment by icflorescu** [comment] 2019-02-13 13:57
@timneutkens I finally discovered last night that my issue was caused by #6273.
As I mentioned in that thread, the error goes away if I modify my `next/babel` preset to `['next/babel', { 'transform-runtime': { useESModules: false } }]`.

**Comment by BiscuiTech** [comment] 2019-02-13 17:07
In my case, a simple complete re-install of the node_modules directory fixed this issue. It might related to the internal dependencies of the modules and the left over modules.

**Comment by goshdarnheck** [comment] 2019-02-13 17:14
I have the same issue (I also get the same error when using dynamic imports, I wrote about it on Spectrum https://spectrum.chat/users/matthew-rapati?thread=c677c233-8b02-447f-aff0-97b3399a493f).

I tried removing node_modules, package-lock.json and clearing my npm cache, but it did not resolve the issue. If I have a chance I will try to create a small reproduction of the issue.

**Comment by obedparla** [comment] 2019-02-14 12:32
Installing `acorn` fixed this issue for me. It is merged already on canary but not yet on master. https://github.com/zeit/next.js/pull/6137

**Comment by timneutkens** [comment] 2019-02-14 12:58
Installing acorn in Next.js doesn't solve the issue.

**Comment by ograycode** [comment] 2019-02-14 15:24
Where I work this problem, this has impacted us when trying to upgrade to next 8.

**Comment by Robbatron** [comment] 2019-02-14 17:40
Using Yarn to install dependencies did the trick for me. Super weird.

**Comment by vasco3** [comment] 2019-02-15 05:41
Ok here is the winning combo (made sure is 100% reproducible):
My project already had next v7
* `npm i next@latest` -> installs next v8.0.1 but warns about acorn
* `npm run dev` -> runs next and fails with the error described in this git issue
* `npm i acorn`
* `npm run dev` -> runs next and fails with the error described in this git issue
* `npm i next@latest` -> no warnings
* `npm run dev` it works!!! 🎉

**Comment by andrewgremlich** [comment] 2019-02-15 16:05
So was it some kind of dependency resolution?  @vasco3  that solved my problem.

**Comment by KB1RMA** [comment] 2019-02-19 18:34
This happens for me directly between `v8.0.0-canary.11` and `v8.0.0-canary.12` https://github.com/zeit/next.js/compare/v8.0.0-canary.11...v8.0.0-canary.12

Installing `webpack@4.28.4` and `@babel/core@7.2.2` as devDependencies as @iaincollins suggested fixes this for me as well.

**Comment by cellog** [comment] 2019-02-22 16:40
still present with next 8.0.2. acorn needs to upgraded in package.json, it fixes the issue

**Comment by cellog** [comment] 2019-02-22 16:44
confirmed: 8.0.3 fixes this issue

**Comment by Soundvessel** [comment] 2019-02-22 20:30
Issue running dev was still present with next 8.0.3 until I tried @vasco3 's recommendation and installed next AFTER acorn. Strange...

**Comment by Magellol** [comment] 2019-02-22 21:11
Same as @Soundvessel 

Installing `acorn` prior `next@8` fixed the issue.


```bash
npm ci
npm i -S acorn@latest
npm i -S next@latest
```

**Comment by Soundvessel** [comment] 2019-02-22 21:19
@Magellol did you try running dev mode after just the `npm ci`. If you see my second post I was able to run dev mode with 8.0.3 _without_ acorn after using the npm command line to properly uninstall next because I believe a cached version outside of `node_modules` was causing the issue. `npm ci` being a clean install might solve the issue without having to install/uninstall individual packages.

**Comment by Magellol** [comment] 2019-02-23 22:16
@Soundvessel Doesn't seem to be working if I don't install acorn explicitely. 
I've tried all sorts of combo with `npm ci` at different stages.

https://github.com/zeit/next.js/issues/6240#issuecomment-466549203 is the only way I could have made it working.

**Comment by pankaj1433** [comment] 2019-02-25 07:44
@vasco3  Your Solution worked for me. Thanks. :+1:

**Comment by Soundvessel** [comment] 2019-02-25 14:59
To clarify I did not need Acorn to resolve the issue. Try to uninstall Next using the command line instead of just deleting `node_modules`.

```
npm uninstall --save next
npm install --save next@latest
```

I believe that using the command line to uninstall Next removes the cause of trouble from an NPM cache outside of `node_modules`.

**Comment by Yzrsah** [comment] 2019-02-27 08:54
Try removing your `.next` directory instead of worrying about npm cache.

I resolved the issue:
- bundleAnalyzer was broken from dynamic import
*after fixing the issue*
- server bundle files got left in `.next/` causing import('./noop'); error despite reinstall
- remove node_modules *and* .next

**Comment by Yzrsah** [comment] 2019-02-27 08:55
Try removing your `.next` directory instead of worrying about npm cache.

I resolved the issue:
- bundleAnalyzer was broken from dynamic import
*after fixing it,*
- server bundle files got left in `.next/` causing import('./noop'); error despite reinstall
- remove `node_modules` *and* `.next`

**Comment by Yzrsah** [comment] 2019-02-27 09:27
Try removing your `.next` directory instead of worrying about npm cache.

I resolved the issue:
- bundleAnalyzer was broken from dynamic import
*after fixing,*
- server bundle files got left in `.next/` causing import('./noop'); error despite reinstall
- remove `node_modules` *and* `.next`

Running `next build` can cause `next` dev to fail, but it works if you didn't run `next build` first:
- If you have a dynamic import error, and you clean the project, then run `next` dev, you will not see the error
- If you have a dynamic import error, and you clean the project, then run `next build`, then run `next` dev, you will see the error

**Comment by Soundvessel** [comment] 2019-03-01 17:04
The error popped up again after updating some other modules.

I did delete `/.next`, /`node_modules`, `package-lock.json`, and `/npm-cache/` in my user folder then reran `npm i` and the error persisted.

Gave up and added `acorn` to my dependencies to prevent the error.

**Comment by ivan-kleshnin** [comment] 2019-03-19 13:34
Getting the "iterator" version of this error. None of the above helped:

```
/Users/username/Sandboxes/mynext/node_modules/@babel/runtime-corejs2/helpers/esm/typeof.js:1
(function (exports, require, module, __filename, __dirname) { import _Symbol$iterator from "../../core-js/symbol/iterator";
```

Requisites: basic `server.js` from the tutorial which always worked.

.babelrc:
```
{
  "presets": [
    "@babel/preset-env",
    "next/babel",
  ],
}
```

```
babel-node server.js
```

package.json

```
{
  "name": "nownext",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "7.2.2",
    "@babel/node": "^7.2.2",
    "@babel/preset-env": "^7.3.4",
    "acorn": "^6.1.1",
    "express": "^4.16.4",
    "next": "^8.0.3",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "webpack": "4.28.4"
  },
  "scripts": {
    "dev": "babel-node server.js",
  }
}
```

produces the above error.

**Comment by timneutkens** [comment] 2019-03-19 21:22
@ivan-kleshnin that's another issue: #6273 which is fixed on canary.

**Comment by dknell** [comment] 2019-03-31 19:45
I tried just removing package-lock.json and node_modules directory, but that didn't work for me. The solution for me was switching to yarn:
```
rm package-lock.json
rm -rf node_modules
yarn dev
```
The error is gone!

**Comment by thomasledoux1** [comment] 2019-04-10 15:13
I had the same error when running trying to run the project in https://github.com/zeit/next-learn-demo/tree/master/E2-lazy-loading-modules. After doing an npm dev install of webpack@4.28.4 it started working again.

**Comment by timneutkens** [comment] 2019-04-21 17:55
Will be fixed by https://github.com/zeit/next.js/issues/6940

**Comment by alexbaumgertner** [comment] 2019-05-17 10:50
@vasco3 Big thanks! It works for me:
```
npm install acorn
npm run dev // -> runs next and fails with the error described in this git issue
npm install next@latest // -> no warnings
npm run dev // it works!!! 🎉
```

**Comment by scub111** [comment] 2019-05-22 08:00
I used Yarn to install dependencies too and it works)

**Comment by Matt-Vegas** [comment] 2019-05-29 20:30
> Ok here is the winning combo (made sure is 100% reproducible):
> My project already had next v7
> 
> * `npm install next@latest` -> installs next v8.0.1 but warns about acorn
> * `npm run dev` -> runs next and fails with the error described in this git issue
> * `npm install acorn`
> * `npm run dev` -> runs next and fails with the error described in this git issue
> * `npm install next@latest` -> no warnings
> * `npm run dev` it works!!! 🎉
> 
> Conclusion:
> The key is to install acorn before next

thanks! proves once again that order matters! saved me.

**Comment by EmilEriksen** [comment] 2019-05-30 11:15
To anybody who might be having issues getting the solutions mentioned in this thread to work: I had to install acorn@^6.0.0 (like the warning calls for). It did not work with the latest version (6.1.1 at this time).

**Comment by naomiHauret** [comment] 2019-06-14 13:44
> Ok here is the winning combo (made sure is 100% reproducible):
> My project already had next v7
> 
> * `npm install next@latest` -> installs next v8.0.1 but warns about acorn
> * `npm run dev` -> runs next and fails with the error described in this git issue
> * `npm install acorn`
> * `npm run dev` -> runs next and fails with the error described in this git issue
> * `npm install next@latest` -> no warnings
> * `npm run dev` it works!!! tada
> 
> Conclusion:
> The key is to install acorn before next

This fixed the issue for me too, thanks ! :clap:

**Comment by dixitpeeyush** [comment] 2019-07-02 11:59
> 
> 
> Ok here is the winning combo (made sure is 100% reproducible):
> My project already had next v7
> 
>     * `npm install next@latest` -> installs next v8.0.1 but warns about acorn
> 
>     * `npm run dev` -> runs next and fails with the error described in this git issue
> 
>     * `npm install acorn`
> 
>     * `npm run dev` -> runs next and fails with the error described in this git issue
> 
>     * `npm install next@latest` -> no warnings
> 
>     * `npm run dev` it works!!! 🎉
> 
> 
> Conclusion:
> The key is to install acorn before next

Thanks a ton, this fixed the problem. 👏👏

**Comment by TidyIQ** [comment] 2019-07-05 04:05
Will this be fixed in the canary branch any time soon?

**Comment by Timer** [comment] 2019-07-05 04:34
@TidyIQ we will be trying to fix it soon! It's important to note that this is a **npm bug**.

**Comment by c0b41** [comment] 2019-07-08 18:54
@Timer webpack already fixed this problem see https://github.com/webpack/webpack/pull/9370

**Closed** 2019-07-08 19:36 UTC
Labels: Is Upstream, priority: very high

**Comment by aequasi** [comment] 2019-07-13 08:40
This doesn't seem to fix the issue for me. Dealing with an older code base that can't quite upgrade to the new features yet, and i still need a transpiled server. 

I've done the above steps, and they don't solve the issue. I'm not even using dynamic imports :/

```
Compiling client app. 
Compiling server app. 
[ error ] ./node_modules/next/dist/client/next-dev.js 23:6
Module parse failed: Unexpected token (23:6)
You may need an appropriate loader to handle this file type.
| 
| 
> import('./dev/noop'); // Support EventSource on Internet Explorer 11
| 
| if (!window.EventSource) {
[ wait ]  compiling ...
[ error ] ./node_modules/next/dist/client/next-dev.js 23:6
Module parse failed: Unexpected token (23:6)
You may need an appropriate loader to handle this file type.
| 
| 
> import('./dev/noop'); // Support EventSource on Internet Explorer 11
| 
| if (!window.EventSource) {
2019-07-13T08:07:59.942Z app:server:log Connected to redis
2019-07-13T08:07:59.947Z app:server:log > Ready on http://localhost:3000
```

**Comment by zargold** [comment] 2019-07-15 22:22
I may have solved this above problem by rm-ing node-modules and re-installing, but maybe not re-installing everything there might be a specific package which is causing this

**Comment by Timer** [comment] 2019-07-15 22:47
The final resolution steps should be to `rm package-lock.json` and `rm -rf node_modules`, then reinstall.

**Comment by Sm00g15** [comment] 2019-08-23 06:38
@Timer I'm running next@9.0.4 and still having the issue. I've tried:
1) removing next, adding acorn with `yarn add acorn` and then running `yarn next@latest` to no avail
2) removing all node_modules and yarn.lock and reinstalling. Anybody else still seeing this issue? I've only begun to experience it with react-datepicker

**Comment by timneutkens** [comment] 2019-08-23 18:31
@Sm00g15 it's quite hard to help you when a reproduction is not provided. Maybe you installed webpack manually?

**Comment by simmatrix** [comment] 2019-11-11 23:58
I fixed this on my end by doing the following steps, not sure whether it works for you but you may try:

1. `npm install babel-plugin-transform-dynamic-import --save-dev`
2. Edit your `.babelrc.js` file and register `transform-dynamic-import` as your plugin
```
module.exports = {
  presets: ['...'],
  plugins: ['transform-dynamic-import'],
};
```
3. Remove the `.next` folder to let it be regenerated again when you run your app again

**Comment by nicktaras** [comment] 2020-01-07 02:26
> I had the same issue, also after updating `webpack` and `@babel/core`. Removing my `package-lock.json` and `node_modules` and doing a fresh install solved the issue.

Thanks, this solution solved the issue for me. I had been working on another Node.js project (not Next.js) where I'd upgraded my version of Node to the latest - this seems to be the cause of the issue. Where the solution to remove the lock.json and node_modules, then re-install the packages worked perfectly. Thanks.

**Comment by balazsorban44** [comment] 2022-01-30 17:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
