### ISSUE TITLE
Issue routing with next/router

### ISSUE THREAD

**Issue by jbraithwaite** [zeit/next.js#9451] opened 2019-11-19 01:23 UTC
# Bug report

## Describe the bug

The next router does not properly handle navigation after a browser refresh

## To Reproduce

1. Go to a [Next site](https://m.twitch.tv/)
2. Click on any link
3. Hit the back button in the browser
4. Refresh the page
5. Hit the forward button in the browser

## Expected behavior

You would expect the browser to go to the page you went to in step `2`, instead you are on step `1`.

## Screenshots

<img width="612" alt="Screen Shot 2019-11-18 at 5 15 26 PM" src="https://user-images.githubusercontent.com/1044105/69107681-1032fa00-0a27-11ea-9e01-16fc10bc60c4.png">

## System information

- OS: macOS
- Browser (if applies) Chrome (`Version 78.0.3904.97`)
- Version of Next.js: 9.1.3

## Additional context

In our application, I added an event listen for `beforePopState`, and this does not trigger when reproducing the issue. It's like Next is completely unaware that the `popstate` has changed.

**Comment by ijjk** [comment] 2019-11-19 01:33
Hi, this has been fixed in the latest version of Next.js `v9.1.4`. This was previously reported in #9449 and #9378

**Closed by ijjk** 2019-11-19 01:33 UTC

**Comment by timneutkens** [comment] 2019-11-19 02:53
@jbraithwaite do you work on the twitch mobile webapp?

**Comment by balazsorban44** [comment] 2022-01-30 22:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
