### ISSUE TITLE
Building on Linux Ubuntu fails, but works on macOS

### ISSUE THREAD

**Issue by tfsjohan** [zeit/next.js#9444] opened 2019-11-18 13:57 UTC
# Bug report
When I run npm run build I get this error message while building on Linux. The same code works fine on macOS. 

```
console.warn(`The module '${dependency}' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install --save ${dependency}'`);}});const defaultCommand='dev';const commands={build:async()=>await Promise.resolve().then(()=>_interopRequireWildcard(require('../cli/next-build'))).then(i=>i.nextBuild),start:async()=>await Promise.resolve().then(()=>_interopRequireWildcard(require('../cli/next-start'))).then(i=>i.nextStart),export:async()=>await Promise.resolve().then(()=>_interopRequireWildcard(require('../cli/next-export'))).then(i=>i.nextExport),dev:async()=>await Promise.resolve().then(()=>_interopRequireWildcard(require('../cli/next-dev'))).then(i=>i.nextDev),telemetry:async()=>await Promise.resolve().then(()=>_interopRequireWildcard(require('../cli/next-telemetry'))).then(i=>i.nextTelemetry)};const args=(0,_index.default)({// Types
                                                  

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
```

## Describe the bug

See above

## To Reproduce

I cloned my project from Bitbucket, ran npm install without errors, tried to run npm run build.

## Expected behavior

I expected build to work as it does on macOs

## System information

- Linux Ubuntu 
- Node 6.17.1
- Next 9.1.2

## Additional context

I'm using TypeScript.

**Comment by ijjk** [comment] 2019-11-18 17:17
Hi, node `v6.17.1` is not supported by Next.js. The minimum supported node version is currently `v8.10.1`. 

Closing as this is most likely the cause. If you are still encountering trouble with this on a supported node version please reply with additional details so we can investigate

**Closed by ijjk** 2019-11-18 17:17 UTC

**Comment by balazsorban44** [comment] 2022-01-30 22:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
