### ISSUE TITLE
AMP-page irregularly deliver a page without css at all.

### ISSUE THREAD

**Issue by iliran11** [zeit/next.js#8196] opened 2019-08-01 09:37 UTC
I don't have a reproducible scenario.
However, I have an `AMP` page and sometimes, irregularly, next.js server delivers a page with an empty ```<style amp-custom></style amp-custom>```

I need help on how can debug such a case, or if someone ever heard about such a scenario and possible causes.

**Comment by iliran11** [comment] 2019-08-04 10:11
I solved this issue. I have implemented `apollo-client` toghter with AMP page. seemingly it caused the problem. I removed `apollo-client` and replaced it with this library: 
https://github.com/prisma/graphql-request

If anyone need more details, Just ask.

**Comment by timneutkens** [comment] 2019-08-04 13:35
I'm going to close this as it's resolved and not following the issue template, but curious if you're using styled-jsx or a different library?

**Closed by timneutkens** 2019-08-04 13:35 UTC

**Comment by balazsorban44** [comment] 2022-01-31 09:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
