### ISSUE TITLE
useRouter hook documentation needed

### ISSUE THREAD

**Issue by hlebbobulka** [zeit/next.js#7075] opened 2019-04-18 12:27 UTC
[This](https://github.com/zeit/next.js/pull/6869) needs documentation. Also needs an explanation of removing `withRouter` HOC with this alternative.

**Comment by timneutkens** [comment] 2019-04-19 06:27
It's experimental. Hence no documentation yet.

**Comment by popuguytheparrot** [comment] 2019-04-19 07:42
@timneutkens so... can u show somewhere example how to use ?

**Comment by HaNdTriX** [comment] 2019-05-01 15:06
@popuguytheparrot [Here](https://gist.github.com/HaNdTriX/b66e30851c2bc3fbc4ee48b4473e2321) is an example. But be warned things might break!

**Comment by chibicode** [comment] 2019-07-08 17:30
The documentation is added here: https://github.com/zeit/next.js/pull/7602 so I think this can be closed.

**Comment by avetisk** [comment] 2019-07-08 18:08
@chibicode would be great to fix this https://github.com/zeit/next.js/issues/6042 or at least leave a comment about it in the documentation.

**Comment by Timer** [comment] 2019-07-08 18:10
@avetisk fixing that issue is in-progress: https://github.com/zeit/next.js/pull/7732

---

Closing this since the hook is now documented.

**Closed** 2019-07-08 18:09 UTC

**Comment by balazsorban44** [comment] 2022-01-31 13:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
