### ISSUE TITLE
assetPrefix + page/[id] slug - Shallow route not possible

### ISSUE THREAD

**Issue by dan-cooke** [zeit/next.js#9399] opened 2019-11-13 12:57 UTC
# Bug report
A while back I raised the following https://github.com/zeit/next.js/issues/9195 - however the reproduction repo that I created did not accurately reproduce the issue we have been seeing.

It turns out its because we are using an `assetPrefix` with all our links next/router behaves very strangely.
## Describe the bug

I have the following directory structure:
![image](https://user-images.githubusercontent.com/22816887/68764740-2dc12780-0613-11ea-9f58-5b067914434b.png)

Using a custom express server, with an `assetPrefix` defined in `next.config.js` and in my `server.js` as follows:

```javascript
const ASSET_PREFIX = process.env.ASSET_PREFIX;

const router = express.Router();

// serve static files

router.get('/_next/*', handler);
router.get('*', handler);
server.use(ASSET_PREFIX, router);

```
With an `ASSET_PREFIX='/test/prefix'` I would assume the following behaviour on the following routes.

### Using page/[id] syntax as the href
**index**  - as: `/test/prefix/`, href: `/` **TO**
**page/[id]/index** - as: `/test/prefix/page/1` href: `/page/[id]`

**Expected Behaviour**
This should load my page slug as a shallow route, re-using the apollo client.

**Actual Result**
Incompatible href/as error
https://github.com/zeit/next.js/blob/master/errors/incompatible-href-as.md

### Removing the [id] and subsituting actual value
**index**  - as: `/test/prefix/`, href: `/` **TO**
**page/[id]/index** - as: `/test/prefix/page/1` href: `/page/1`

**Expected Results**
This should shallow route an re-use the apollo client

**Actual Result**
Route works, but the apollo client is created again, ie. not a shallow route.

## To Reproduce
This bug is _extremely_ difficult to describe - so I would encourage you to check out the reproduction repo.

1. Clone the [repo](https://github.com/dan-cooke/next-with-apollo-bugs)
2. Run `yarn && yarn start`
3. Open `localhost:3000/test/prefix/`
4. Open your dev console and observe the logs on each route
5. Click the `Start Here` link - note how the cache is re-used
6. Click the first link, note how a shallow route does not occur
7. Click the second link, note how a shallow route does not occur
8. Click the final lihnk, check the error in the console.

Have a look in `components/Header.js` for the routes

It seems to me as if its impossible to produce a shallow route when using `assetPrefix` with dynamic file based routing.

## System information

OS: macOS (Mojave 10.14.6)
Browser: Chrome
Version of Next.js: >= 9.x.x

**Comment by jamesmosier** [comment] 2019-11-13 23:39
I think this relates to the discussion about [`basePath`](https://github.com/zeit/next.js/issues/4998) which would allow for the clientside rendering when using a url with a custom prefix. I think [`assetPrefix`](https://nextjs.org/docs#dynamic-assetprefix) is more related to where bundles/files are served from and less about routing/url structure for pages. I could be misreading your issue though.

**Comment by dan-cooke** [comment] 2019-11-14 10:55
> I think this relates to the discussion about [`basePath`](https://github.com/zeit/next.js/issues/4998) which would allow for the clientside rendering when using a url with a custom prefix. I think [`assetPrefix`](https://nextjs.org/docs#dynamic-assetprefix) is more related to where bundles/files are served from and less about routing/url structure for pages. I could be misreading your issue though.

Very interesting, I had not picked up on this issue when searching. This sounds exactly like what we should be using.

**Comment by timneutkens** [comment] 2020-01-03 00:23
Closing this in favor of #4998

**Closed by timneutkens** 2020-01-03 00:23 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-30 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
