### ISSUE TITLE
How to load custom configuration on NextJS custom server

### ISSUE THREAD

**Issue by orafaelfragoso** [zeit/next.js#7570] opened 2019-06-13 14:45 UTC
I'm trying to load my configuration to my custom server setup and this is not shown in the examples of mentioned in the documentation.

I have this file, where I load all the plugins with compose:
```js
const withPlugins = require('next-compose-plugins')
const withEnv = require('next-env')
const withSass = require('@zeit/next-sass')
const withImages = require('next-images')
const withOptimizedImages = require('next-optimized-images')
const withSourceMaps = require('@zeit/next-source-maps')

const config = require('./config')

module.exports = withPlugins([
  withEnv(config.env),
  withImages(),
  [withSass, config.sass],
  [withOptimizedImages, config.optimizedImages],
  withSourceMaps(),
], config.next)
```

And this is my server configuration:
```js
const express = require('express')
const next = require('next')
const helmet = require('helmet')
const routes = require('./config').routes
const conf = require('./next.config')

const port = process.env.PORT || 3000
const dev = process.env.NODE_ENV === 'development'
const app = next({ dev, dir: './src', conf: conf() })
const handler = routes.getRequestHandler(app)

app.prepare().then(() => {
  express()
    .use(helmet())
    .use(handler)
    .listen(port, (err) => {
      if (err) {
        throw err
      }

      console.log(`> Ready on http://localhost:${port}`) // eslint-disable-line no-console
    })
})
```

The server configuration only loads the NextJS configuration object using the `conf` option, but does not load the compose with plugins if I pass it.

Is there a way of using the plugins with my custom server all together?

**Comment by timneutkens** [comment] 2019-08-10 13:28
Going to close this as it doesn't follow the issue template. Questions should be asked on https://spectrum.chat/next-js.

**Closed by timneutkens** 2019-08-10 13:28 UTC

**Comment by vongohren** [comment] 2019-12-12 19:32
@timneutkens how can you blindly close this, there is no clear pointer to do this. @orafaelfragoso did you solve this?

**Comment by orafaelfragoso** [comment] 2019-12-12 22:25
@vongohren Yeap. Some compatibility issue was happening with `next-compose-plugins`. I solved it by removing the lib and wrapping everything manually.

Thanks.

**Comment by gajus** [comment] 2020-12-06 22:04
@timneutkens It is not clear what is the answer to this question.... and it is not covered in the documentation.

**Comment by gajus** [comment] 2020-12-06 22:08
Related issue for anyone trying to track this down.

https://github.com/cyrilwanner/next-compose-plugins/issues/18

**Comment by balazsorban44** [comment] 2022-01-29 01:24
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
