### ISSUE TITLE
Next.js 9.0.6 and later gets stuck in "Automatically rendering pages..." forever

### ISSUE THREAD

**Issue by thomasjm** [zeit/next.js#8910] opened 2019-09-30 06:19 UTC
# Bug report

## Describe the bug

The bug is that Next.js gets stuck on "Automatically rendering pages..." when trying to do `npm run build`. It seems to be connected to having a large folder with lots of files in the `/static` folder (I've been using a git submodule containing MathJax).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `git clone https://github.com/thomasjm/nextjs-freezing-repro`
2. `cd nextjs-freezing-repro`
3. `npm install && npm run build`
4. Observe build getting stuck at "Automatically rendering pages..."

5. Edit `package.json` to set `"next": "9.0.5"`.
6. `npm install && npm run build`
7. The build should complete successfully, showing the problem was introduced in `9.0.6`.

## Expected behavior

The build finishes successfully.

## System information

- OS: Ubuntu 18.10 and also 19.04
- Version of Next.js: 9.0.6

## Additional context

I noticed by using `strace` on the stuck process that it seems to be doing `epoll_wait` on a file descriptor forever.

**Comment by ijjk** [comment] 2019-10-02 14:34
Hi @thomasjm I optimized the auto prerendering phase of `next build` a bit to not copy unnecessary files. It's available in `v9.0.8-canary.1` of Next.js. Could you try that version on your app and update here whether you are still encountering the stalling?

**Comment by ijjk** [comment] 2019-10-09 13:00
I was able to reproduce this with `Linux 5.0.0-31-generic Ubuntu 19.04` and `node v10.16.3` and it appears to be resolved in the latest version of Next.js `v9.1.1`

Closing as per above, if you are still encountering this feel free to reply with additional details

**Closed by ijjk** 2019-10-09 13:00 UTC
Labels: Type: Needs Investigation

**Comment by balazsorban44** [comment] 2022-01-31 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
