### ISSUE TITLE
URL query parameters start off empty when using useRouter

### ISSUE THREAD

**Issue by quietgopher** [zeit/next.js#12219] opened 2020-04-26 19:25 UTC
# Bug report

## Describe the bug

If I pass in URL parameters and use useRouter, the URL query params start off as an empty dict and then on a second render pass they get filled in.  This seems broken.  My app uses the URL parameters as filters (which means the first request requests all entities).  I can create a workaround (by having a different url parameter mean "unfiltered" but it seems pretty hacky).

In my other app, if I use getInitialProps, getServerSideProps, getStaticProps, usually I can get both the server-side and browser side to not have an empty dict (which is strange). 

## To Reproduce

1. git clone https://github.com/quietgopher/nextjs-query-bug.git
2. cd nextjs-blog
3. npm run dev
4. Open Chrome console.
4. Hit http://localhost:8090/?test=true

## Expected behavior

I'd expect that both the server and browser consoles to not contain "query={}".

## Screenshots

<img width="153" alt="Screen Shot 2020-04-26 at 12 22 18 PM" src="https://user-images.githubusercontent.com/49970746/80317450-a9292680-87b8-11ea-81f3-b497344a9c3c.png">
<img width="407" alt="Screen Shot 2020-04-26 at 12 22 13 PM" src="https://user-images.githubusercontent.com/49970746/80317451-aa5a5380-87b8-11ea-808f-80a612a3f6f1.png">

## System information

- OS: macOS
- Browser: Chrome
- Version of Next.js: 9.3.5,
- Version of Node.js: v13.11.0

**Comment by c0b41** [comment] 2020-04-27 00:21
Look at this https://github.com/zeit/next.js/discussions/11484#discussioncomment-2362

**Comment by timneutkens** [comment] 2020-04-27 09:45
Duplicate of #8259

**Closed by timneutkens** 2020-04-27 09:45 UTC

**Comment by balazsorban44** [comment] 2022-01-30 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
