### ISSUE TITLE
Allow getStaticPaths to return extra properties per path

### ISSUE THREAD

**Issue by ernestofreyreg** [zeit/next.js#11915] opened 2020-04-15 13:12 UTC
# Feature request
Allow `getStaticPaths` function to return extra properties per path. 

## Is your feature request related to a problem? Please describe.
Some headless CMS solutions use an ID as only method for retrieving individual content. If you want to use a SLUG for the path there is no way to pass said ID to the `getStaticProps` function, only the SLUG gets passed. Any extra properties are not. 

Ex: `/partner/[slug].tsx`
```typescript
export async function getStaticPaths() {
  const res = await client.getEntries<IPortalFields>({ content_type: 'portal' })
  const paths = res.items.map(item => ({
    params: { slug: item.fields.slug, id: item.sys.id }
  }))
  return { paths, fallback: false }
}
export async function getStaticProps({ params }) {
  const res = await client.getEntry<IPortalFields>(params.id)
  return {
    props: {
      partner: {
        slug: res.fields.slug,
        company: res.fields.companyName,
        logo: res.fields.logo.fields.file.url
      }
    }
  }
}
```

This will not work because the ID is not passed to the `getStaticProps` function only the SLUG is passed.

## Describe the solution you'd like

Allow `getStaticPath` to return extra properties. Could also be as part of a different property per path, like `props` this would also allow typing on it. 

```typescript
interface PageProps {
  id: string
}

export async function getStaticPaths<PageProps>() {
  const res = await client.getEntries<IPortalFields>({ content_type: 'portal' })
  const paths = res.items.map(item => ({
    params: { uid: item.fields.uid },
    props: { id: item.sys.id }
  }))
  return { paths, fallback: false }
}
export async function getStaticProps<PageProps>({ params, props }) {
  const res = await client.getEntry<IPortalFields>(props.id)
  return {
    props: {
      partner: {
        uid: res.fields.uid,
        company: res.fields.companyName,
        logo: res.fields.logo.fields.file.url
      }
    }
  }
}
```

## Describe alternatives you've considered

The only solution I found so far is to write a JSON map of this extra properties to a file on the `getStaticPaths` function and retrieve it on the `getStaticProps` function

## Additional context

Nothing else

**Comment by ijjk** [comment] 2020-04-16 18:53
Duplicate of:
https://github.com/zeit/next.js/issues/10933#issuecomment-598297975
https://github.com/zeit/next.js/discussions/11370 
https://github.com/zeit/next.js/discussions/11272 
https://github.com/zeit/next.js/discussions/11738

Closing in favor of the existing ones

**Closed by ijjk** 2020-04-16 18:53 UTC

**Comment by SergeyRe** [comment] 2020-04-26 19:37
Replace
`const res = await client.getEntry<IPortalFields>(props.id)`
to
```
const postData = await client.getEntries({
    content_type:'post',
    'fields.slug[match]':params.id
  }
    )
   var res = postData.items[0]
```

**Comment by SergeyRe** [comment] 2020-04-27 13:03
The approach described above actually is not perfect as used text-searching may be unpredicteable
The idea i try to realize now -to create entries in contentful with id ===fields.slug
it is possible via contentful management api
```
space.createEntryWithId('<content_type_id>', '<entry_id>', {
  fields: {
    title: {
      'en-US': 'Entry title'
    }
  }
```

**Comment by SergeyRe** [comment] 2020-04-30 11:31
Finally
[contentful-nextjs example just arrived ](https://github.com/lfades/next.js/tree/examples/cms-contentful/examples/cms-contentful)
i see it use [in] operator instead [match] 
in my case it helps

**Comment by balazsorban44** [comment] 2022-01-30 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
