### ISSUE TITLE
api routes not working with now dev and Windows

### ISSUE THREAD

**Issue by lfades** [zeit/next.js#8017] opened 2019-07-17 16:52 UTC
# Bug report

## Describe the bug

Trying to use the new api routes with `now dev` results in a 404

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Download one of the api routes examples
2. install dependencies and run `now dev`
3. See 404 for api routes

## Expected behavior

api routes should be available in the app

## System information

- OS: Windows
- Version of Next.js: ^9.0.0

## Additional context

This is only for Windows, and only for `now dev`

**Comment by Erik-Sovereign** [comment] 2019-07-17 17:43
I experience the same bug with
Windows 10
Next.js: 9.0.1

This has maybe something to do with https://github.com/zeit/now-cli/issues/2385 (Subdirectory pages don't work on `now dev` with @now/next)

**Comment by sjyasuosj** [comment] 2019-07-18 03:35
Same. I thought it was a problem with my code but I've reproduced it using the examples.

**Comment by huv1k** [comment] 2019-07-24 08:48
This issue was fixed with https://github.com/zeit/now-builders/pull/788.

**Closed** 2019-07-24 08:47 UTC
Labels: Type: Bug, priority: high

**Comment by balazsorban44** [comment] 2022-01-31 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
