### ISSUE TITLE
next-css Issue in next New Version

### ISSUE THREAD

**Issue by ebs-PriyankaKanwar** [zeit/next.js#12436] opened 2020-05-03 11:41 UTC
# Bug report

Hello team
I have Facing This issue
$ next build
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

Creating an optimized production build

Failed to compile.

./node_modules/@fortawesome/fontawesome-free/css/all.min.css
ModuleParseError: Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Build error occurred
Error: > Build failed because of webpack errors
at build (/var/ezdev/employzone-us/node_modules/next/dist/build/index.js:13:900)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Can you please help me.
## System information

- OS: [ Windows]
- Browser (if applies) [ chrome, safari]
- Version of Next.js: [ 9.3.6]
- Version of Node.js: [v13.7.0]

**Comment by jamesmosier** [comment] 2020-05-03 23:08
Is this the same issue as https://github.com/zeit/next.js/issues/12388?

**Comment by Timer** [comment] 2020-05-03 23:47
Closing as duplicate.

**Closed by Timer** 2020-05-03 23:47 UTC

**Comment by balazsorban44** [comment] 2022-01-30 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
