### ISSUE TITLE
react-redux's connect HOC breaks HMR

### ISSUE THREAD

**Issue by egorovli** [zeit/next.js#4256] opened 2018-05-02 20:35 UTC
Hi. I've switched to 6.0.0 recently and upgraded `next-redux-wrapper` to the version `2.0.0-beta.2`. It assumes using `withRedux` HOC for the `_app.jsx` component and `react-redux`'es `connect` for pages. Currently this setup breaks hot module replacement, i.e. the console says `[HMR] App is up to date`, but the page does not update.

I know that there are issues with HMR and legacy decorators, so I've used all possible versions:

### ./pages/index.jsx
```jsx
import React, { Component } from 'react'
import { connect } from 'react-redux'

@connect()
export default class Landing extends Component {
  render = () => {
    return (
      <h1>Landing</h1>
    )
  }
}
```

### ./pages/index.jsx
```jsx
import React, { Component } from 'react'
import { connect } from 'react-redux'

class Landing extends Component {
  render = () => {
    return (
      <h1>Landing</h1>
    )
  }
}

const ConnectedLanding = connect()(Landing)
export default ConnectedLanding
```

### ./components/pages/index.jsx
```jsx
import React, { Component } from 'react'

export default class Landing extends Component {
  render = () => {
    return (
      <h1>Landing</h1>
    )
  }
}
```

### ./pages/index.jsx
```jsx
import { connect } from 'react-redux'
import Page from '../components/pages/index'

const ConnectedPage = connect()(Page)
export default ConnectedPage
```

But none of these solutions work. Also, I've tried using both regular `redux` and `fast-redux`, no change. Rest of the config looks like this:

### ./decorators/redux-app.jsx
```jsx
import { createStore, applyMiddleware, compose } from 'redux'
import thunk from 'redux-thunk'
import withRedux from 'next-redux-wrapper'
import { rootReducer } from 'fast-redux'

let composeEnhancers

if (process.env.NODE_ENV !== 'production') {
  composeEnhancers = (typeof window !== 'undefined' && window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__) || compose
}

if (process.env.NODE_ENV === 'production') {
  composeEnhancers = compose
}

const makeStore = initialState => createStore(
  rootReducer,
  initialState,
  composeEnhancers(applyMiddleware(thunk))
)

const reduxApp = Component => withRedux(makeStore)(Component)

export default reduxApp
```

### ./pages/_app.jsx
```jsx
import React from 'react'
import App, { Container } from 'next/app'
import reduxApp from '../decorators/redux-app'

class CustomApp extends App {
  static getInitialProps = async ({ Component, router, ctx }) => {
    const pageProps = typeof Component.getInitialProps === 'function'
      ? await Component.getInitialProps(ctx)
      : {}

    return {
      pageProps
    }
  }

  render = () => {
    const { Component, pageProps } = this.props

    return (
      <Container>
        <Component {...pageProps} />
      </Container>
    )
  }
}

const ReduxedApp = reduxApp(CustomApp)
export default ReduxedApp
```

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

Hot updates are properly applied on change.

## Current Behavior

No hot updates are applied, despite the fact that the console says something like:

```
[HMR] connected
[HMR] bundle rebuilding
[HMR] bundle rebuilt in 453ms
[HMR] Checking for updates on the server...
[HMR] Updated modules:
[HMR]  - ./components/pages/index.jsx
[HMR]  - ./pages/index.jsx
[HMR] App is up to date.
[HMR] bundle rebuilding
[HMR] bundle rebuilt in 570ms
```

## Steps to Reproduce (for bugs)

1. Upgrade to `next 6.0.0` and `next-redux-wrapper 2.0.0-beta.2`
2. Try to use HMR in `connect`'ed pages

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 6.0.0 |
| node    | 9.11.1 |
| next-redux-wrapper | 2.0.0-beta.2 |
| redux | 4.0.0 |
| react-redux | 5.0.7 |

**Comment by desaias** [comment] 2018-05-12 20:12
I noticed this same behavior on `6.0.0` which seemed to be corrected with `6.0.1-canary.0` HMR fix but then wasn't working again with `next 6.0.1-canary.2` and the `next 6.0.1` releases.  I'm guessing it has something to do with the HMR update in #4317

**Comment by timneutkens** [comment] 2018-05-12 22:07
Try the with-redux example: https://github.com/zeit/next.js/tree/canary/examples/with-redux

If it still doesn't work please provide a repository so I can check it out. I'm pretty sure `connect` is not the cause of this though.

**Comment by desaias** [comment] 2018-05-13 23:50
@timneutkens I don't think the issue is with `connect` either but more so the changes that were made with `react-hot-reloader`.  Developing locally I see the issue where it says bundle rebuilt and nothing changes until a hard refresh, worked fine locally with `next 6.0.1-canary.0` and `6.0.1-canary.1`.   There are no issues when running `next build && next start`.

I'm trying to put together a repo that reproduces the issue.

**Comment by egorovli** [comment] 2018-05-15 06:53
I've created a simple repo here: https://github.com/egorovli/react-redux-connect-no-hmr.

It follows guidelines for using `redux` with [`next-redux-wrapper`](https://github.com/kirill-konshin/next-redux-wrapper) and [`fast-redux`](https://github.com/dogada/fast-redux).

**Comment by timneutkens** [comment] 2018-12-31 00:01
This was fixed by dropping react-hot-loader from Next.js

**Closed by timneutkens** 2018-12-31 00:01 UTC
