### ISSUE TITLE
Feature Request: buildAsPath method from `next/router`

### ISSUE THREAD

**Issue by lifeiscontent** [zeit/next.js#9330] opened 2019-11-06 23:31 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

one issue I've run across is a simple routing solution for dynamic path segments.

## Describe the solution you'd like

I'd like to have a function like this that next.js provides to me

``` js
function buildAsPath(pathname, params = {}) {
  let nextPath = pathname;
  const query = JSON.parse(JSON.stringify(params));
  for (const key in query) {
    nextPath = nextPath.replace(
      new RegExp(`\\[(${key})\\]`, 'g'),
      (_match, p1) => {
        const value = query[p1];
        delete query[p1];
        return value;
      }
    );
  }

  return { pathname: nextPath, query };
}
```

so when I have a URL like `/posts/[id]/comments/[commentId]` I can just do

``` js
router.push(router.pathname, buildAsPath(router.pathname, {
  id: router.query.id,
  commentId: comment.id
}))
```

## Describe alternatives you've considered

What I started with:

``` js
function buildPathname(pathname, { unit, city, state, role }) {
  switch (pathname) {
    case '/jobs/roles/[role]/units/[unit]':
      if (typeof unit === 'string' && unit.length !== 0) {
        return '/jobs/roles/[role]/units/[unit]';
      } else if (typeof city === 'string' && typeof state === 'string') {
        return '/jobs/roles/[role]/locations/[state]/[city]';
      } else if (typeof state === 'string') {
        return '/jobs/roles/[role]/locations/[state]';
      } else if (typeof role === 'string') {
        return '/jobs/roles/[role]';
      }
    case '/jobs/roles/[role]/locations/[state]': // eslint-disable-line no-fallthrough
    case '/jobs/roles/[role]/locations/[state]/[city]':
      if (typeof city === 'string' && typeof state === 'string') {
        return '/jobs/roles/[role]/locations/[state]/[city]';
      } else if (typeof state === 'string') {
        return '/jobs/roles/[role]/locations/[state]';
      } else if (typeof unit === 'string' && unit.length !== 0) {
        return '/jobs/roles/[role]/units/[unit]';
      } else if (typeof role === 'string') {
        return '/jobs/roles/[role]';
      }
    // eslint-disable-line no-fallthrough
    default:
      throw new TypeError('invalid arguments for buildPathname()');
  }
}
function buildAsPathname(nextPathname, { unit, city, state, role }) {
  switch (nextPathname) {
    case '/jobs/roles/[role]/units/[unit]': {
      const query = {};
      if (typeof city === 'string') {
        query.city = city;
      }
      if (typeof state === 'string') {
        query.state = state;
      }

      return {
        pathname: `/jobs/roles/${role}/units/${unit}`,
        query,
      };
    }
    case '/jobs/roles/[role]/locations/[state]': {
      const query = {};

      if (typeof unit === 'string' && unit.length !== 0) {
        query.unit = unit;
      }
      return {
        pathname: `'/jobs/roles/${role}/locations/${state}'`,
        query,
      };
    }
    case '/jobs/roles/[role]/locations/[state]/[city]': {
      const query = {};
      if (typeof unit === 'string' && unit.length !== 0) {
        query.unit = unit;
      }
      return {
        pathname: `'/jobs/roles/${role}/locations/${state}/${city}'`,
        query,
      };
    }
    case '/jobs/roles/[role]': {
      const query = {};
      if (typeof unit === 'string' && unit.length !== 0) {
        query.unit = unit;
      }

      return {
        pathname: `/jobs/roles/${role}`,
        query,
      };
    }
    default:
      throw new TypeError('invalid arguments for buildAsPathname()');
  }
}

function navigate(props, { role, unit, state, city }) {
  if (typeof role === 'string') {
    role = role.toLowerCase();
  }

  if (typeof city === 'string') {
    city = titleCaseToKebabCase(city);
  }

  if (typeof state === 'string') {
    state = state.toLowerCase();
  }

  if (typeof unit === 'string') {
    unit = unit.toLowerCase();
  }

  if (
    role !== props.router.query.role ||
    unit !== props.router.query.unit ||
    state !== props.router.query.state ||
    city !== props.router.query.city
  ) {
    const pathname = buildPathname(props.router.pathname, {
      role,
      unit,
      state,
      city,
    });

    const asPath = buildAsPathname(pathname, {
      role,
      unit,
      state,
      city,
    });

    props.router.push(pathname, asPath);
  }
}
```

**Comment by Timer** [comment] 2019-11-09 20:14
Duplicate of #8207

**Closed by Timer** 2019-11-09 20:14 UTC

**Comment by balazsorban44** [comment] 2022-01-30 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
