### ISSUE TITLE
Server side rendering not happening

### ISSUE THREAD

**Issue by BoxmodelTim** [zeit/next.js#5576] opened 2018-11-02 11:48 UTC
# Bug report

## Describe the bug
I am seeing a weird issue where by each page is rendered entirely in the client. My page source is `<div id="__next"><div data-reactroot=""></div></div>`
It was working but has since stopped working.

## To Reproduce

My package.json dependencies are:
```
"dependencies": {
        "@zeit/next-sass": "^1.0.1",
        "axios": "^0.18.0",
        "dotenv": "^6.1.0",
        "fs": "0.0.1-security",
        "isomorphic-unfetch": "^3.0.0",
        "moment": "^2.22.2",
        "next": "^7.0.2",
        "next-cookies": "^1.0.3",
        "node-sass": "^4.9.4",
        "nprogress": "^0.2.0",
        "pell": "^1.0.4",
        "react": "^16.5.2",
        "react-datetime": "^2.16.2",
        "react-dom": "^16.5.2",
        "react-modal": "^3.6.1",
        "react-redux": "^5.0.7",
        "redux": "^4.0.0"
    }
```

## Expected behavior
I expect the page source to be populated with my server rendered page

## System information
 - OS: macOS
 - Browser (if applies): all

Is there any possible scenario where this might happen, or could a package being used cause this?

Thanks,

**Comment by timneutkens** [comment] 2018-11-02 11:53
Can you provide a reproduction? You're only posting the package.json which doesn't really help reproduce as you're not posting any page to be rendered.

**Comment by BoxmodelTim** [comment] 2018-11-02 11:57
Yeah it is a tricky one to post.

This is my index.js

```
import React, { Component } from 'react'
import fetch from 'isomorphic-unfetch'
import { PRODUCTS_ACTIVE } from '../config/endpoints'
import StorePage from '../components/layout/storePage'
import RequestError from '../components/errors/requestError'
import messages from '../constants/messages'
import Hero from '../components/hero'
import ProductListing from '../components/listings/products';

const hero = {
    backgroundImage: "url('/static/homepage-hero-background.png')",
    title: "View our products",
    summary: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat."
 };

class products extends Component {
    static async getInitialProps(ctx) {
        const res = await fetch(PRODUCTS_ACTIVE)
        
        if (!res.ok)
            return {error: messages.requestError}

        const data = await res.json()
        return {
            products: data
        }
    }
    render() {
        const { products, error } = this.props;
        return (
            <StorePage>
                <Hero background={hero.backgroundImage} title={hero.title} summary={hero.summary} />
                <div id="products" className="alt__background c__sectionPadding">
                    <div className="l__contain">
                        <h2 className="aligncenter">Products</h2>
                        {products && <ProductListing products={products} />}
                    </div>
                </div>
                {error && <RequestError message={error} />}
            </StorePage>
        )
    }
}

export default products;

```

document.js

```
import Document, { Head, Main, NextScript } from 'next/document'

export default class MyDocument extends Document {
    static async getInitialProps(ctx) {
        const initialProps = await Document.getInitialProps(ctx)
        return { ...initialProps }
    }

    render() {
        return (
            <html lang="en">
                <Head />
                <body>
                    <Main />
                    <NextScript />
                </body>
            </html>
        )
    }
}
```


_app.js

```
import React from 'react'
import App, { Container } from 'next/app'
import { Provider } from 'react-redux'
import store from '../state/store'
import Page from '../components/layout/page'
import "../styles.scss"

export default class MyApp extends App {
    static async getInitialProps({ Component, router, ctx }) {
        let pageProps = {}

        if (Component.getInitialProps) {
            pageProps = await Component.getInitialProps(ctx)
        }

        return { pageProps }
    }
    render () {
        const { Component, pageProps } = this.props

        return (
            <Container>
                <Provider store={store}>
                    <Page>
                        <Component {...pageProps} />
                    </Page>
                </Provider>
            </Container>
        )
    }
}
```

**Comment by timneutkens** [comment] 2018-11-04 02:07
So SSR is working fine in the simplest example:

https://create-next-example-app-ggdsbdanru.now.sh/

Since the only thing your _document.js does is set `lang="en"` try removing the _document.js and check again.

I'm going to close this issue as it's most likely not a bug in Next.js, we have extensive integration tests for both SSR and client rendering in development as well as production.

**Closed by timneutkens** 2018-11-04 02:07 UTC

**Comment by balazsorban44** [comment] 2022-01-31 15:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
