### ISSUE TITLE
modal with url like reddit or twitter. changing url without navigation.

### ISSUE THREAD

**Issue by joonhocho** [zeit/next.js#8023] opened 2019-07-18 02:39 UTC
# Feature request

On Reddit or twitter, if you click on a post, it will change url to post view url, but it shows post on modal instead of navigating and losing current ui contexts (scroll positions and such).
I don't think this modern behavior is currently supported by Next.js

## Describe the solution you'd like

1. Click on a list item to view list item content details.
2. Show item details on modal and change url
3. closing modal pops url
4. all previous ui contexts are preserved (scroll positions, etc.)

5. when user lands on the item detail url (initial load), it should show item detail page (not modal)

All modern websites implement this behavior for better viewing experience

**Comment by joonhocho** [comment] 2019-07-18 02:41
There is an attempt for this behavior: https://github.com/zeit/next.js/pull/7864
Problem is using window.history breaks Next router.
Using Next router triggers a navigation.

**Comment by lkbr** [comment] 2019-07-18 06:35
I've asked a similar question here: https://spectrum.chat/next-js/general/what-is-the-best-way-to-create-the-instagram-photo-modal-routing-experience-on-dynamic-pages-with-next-9~5695efed-d505-446b-8474-1ce2117e19d0

In theory it's as simple as "basically you don’t link to another page at all when you open the modal, you just display the modal on the current page and manually push a new history entry using Next’s router API." - https://mobile.twitter.com/adamwathan/status/1147593450734444547

But not sure how to do this in a Next.js ordained way.

**Comment by bringking** [comment] 2019-07-19 17:21
To add some of our experience to this from Weedmaps. We ran into issues with Mobile Chrome and Mobile Safari and their attempts to cache resources when navigating back in the browser. So when pushing a route and opening a modal, X set of JS resources are loaded and executed. Then if you navigate away, then click "back" it attempts a full round trip to the Server, loads Y JS bundle for the full detail page, but also re-loads the old JS from the cache, and then the in-correct `X` bundle attempts to hydrate the page, and things break. 

We tried a few tricks to prevent the browser from loading the cached resources, to no avail.

Our solution was to use a custom routing solution to ensure both routes loaded the same JS resources, but then bifurcated the rendering path based on URL

**Comment by exogen** [comment] 2019-07-20 05:20
I think there's a simpler solution than what's been describe above so far. I posted a quick half-baked demo of it here: https://github.com/exogen/next-modal-pages

This solution should definitely be improved upon, but the basic idea is sound:

- In Next.js, routing to another page occurs by unmounting the previous page component and mounting the next one.
- A custom `<App>` lets you decide exactly what to do with these page components. For example, you could wrap them in some layout or provider components in `_app.js`.
- You also don't *necessarily* need to unmount the previous pages just because you're being given a new one in the latest App's render method. You could save a history of the previous page component/props and continue to render those if you want.
- So, this page modal behavior can be accomplished by remembering a "stack" of previous the previous page component/props passed to App, and rendering them as a stack of modals.

My demo does this in a somewhat janky way, but you get the idea. You don't need to mess with browser history or the DOM directly – Next.js and React already give you the pieces you need. From Next.js' perspective, you are still on the new page and rendering that page's component, it's just that the app has chosen to dynamically render other stuff around the current page as well – like the pages from past renders.

**Comment by lkbr** [comment] 2019-07-22 08:43
In my case, I don't want or need to change anything but the browser's url.

**Comment by singlepageprogrammer** [comment] 2019-08-26 08:44
https://github.com/singlepageprogrammer/react-modal-route-example

**Comment by simjoeweb** [comment] 2019-12-29 19:10
I would love to see a clean solution for this

**Comment by oyeanuj** [comment] 2020-02-11 00:42
@timneutkens Is there an official recommended/blessed way to do this, maybe like @exogen's example?

**Comment by rahul3103** [comment] 2020-02-25 06:26
Any official recommended examples?

**Comment by rahul3103** [comment] 2020-02-28 10:22
https://codesandbox.io/s/ecstatic-buck-2t2tr

**Comment by adriangzz** [comment] 2020-03-14 16:25
Can confirm, changing  `if (!routeMatch) {` to `if (false) {` in node_modules/next/dist/next-server/lib/router/router.js makes the use of model to dynamic pages possible. It works beautiful now.

**Comment by FabianL1** [comment] 2020-03-20 12:31
Is there already a good solution? I tried hashchange - but it does not work

**Comment by mohammad-amin-hesam** [comment] 2020-03-26 13:35
https://github.com/mohammad-amin-hesam/react-modal-route-example

**Comment by viztor** [comment] 2020-04-02 05:16
Thi should be closed?

**Comment by timneutkens** [comment] 2020-04-02 07:25
Landed #11473

**Closed by timneutkens** 2020-04-02 07:25 UTC
Labels: Type: Example, good first issue, help wanted

**Comment by makotot** [comment] 2020-04-03 10:50
Is there any way to show modal (not item detail page) when user lands on the item detail url (initial load)  in opposition to the last step of described in https://github.com/zeit/next.js/issues/8023#issue-469543180 ? 
AFAIK, reddit behaves like this now.

**Comment by marjorg** [comment] 2020-04-20 21:03
@timneutkens Hey! I'm trying to do this with nested dynamic routes without any luck.

Structure:
```
/pages
    /posts
        [postId].tsx
        /search
            [term].tsx
```

What I'm trying to do is open a search result in a modal while changing the url from i.e. `localhost/posts/search/hello` to `localhost/posts/{ID_FROM_SEARCH}`, but it just navigates to the page instead. If I change the search page to not be a dynamic route (`[term].tsx` to just `term.tsx`) it opens the modal as expected.

Is there any way to make this work?

**Comment by balazsorban44** [comment] 2022-01-30 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
