### ISSUE TITLE
Request for error.js layout doc example or to pass a custom text

### ISSUE THREAD

**Issue by realtebo** [zeit/next.js#5790] opened 2018-12-02 17:11 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
I'd like to reuse default error page, but adding a custom message

## Describe the solution you'd like
I'd like to Pass a status text to default error component

OR 

see in the doc how to really _clone_ the actual error page

## Describe alternatives you've considered
I'd like to show a 401 or 403 error, but with an exaplanation, not only a Forbidden string, but something like "403 | You're a loyal user but authorized yet to see this level of documentation"

```
if (adminRequired && (!user)) {
   return <Error statusCode="403" statusText="Documentation is reserver to team member" />
}

if (adminRequired && user && !user.isAdmin)) {
   return <Error statusCode="403" statusText="You're a loyal coworker but you're not authorized yet to see this level of documentation" />
}
```
I can utilize [https://nextjs.org/docs#custom-error-handling](the official examples), but there is not layout 

## Additional context

Simply, I'd like to clone the same layout to be able to replace or add a text to the default english-only error string

![image](https://user-images.githubusercontent.com/1268699/49342575-7f201300-f65d-11e8-8c90-93ae3f73670e.png)

**Comment by timbielawski** [comment] 2018-12-05 13:51
Hi,

check this issue

https://github.com/zeit/next.js/issues/5625

I have a errorCodeMapper you can parse into Next, if you return 401 it will display the above message

**Comment by erick2014** [comment] 2019-05-11 17:57
@realtebo As far as I understand you can't pas an error message? to the <Error/> component?

**Comment by realtebo** [comment] 2019-05-12 08:46
Yes exactly

**Comment by timbielawski** [comment] 2019-05-13 06:40
In the end I just used a HOC, I  have a gist https://gist.github.com/timbielawski/6cb793ea8cf8aa22ba32ef88687c42c1

**Comment by timneutkens** [comment] 2019-08-10 13:07
Fixed in https://github.com/zeit/next.js/pull/7381

**Closed by timneutkens** 2019-08-10 13:07 UTC
Labels: Type: Feature Request, good first issue, help wanted

**Comment by balazsorban44** [comment] 2022-01-31 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
