### ISSUE TITLE
.plugins[2][1] must be an object, false, or undefined     at assertPluginItem

### ISSUE THREAD

**Issue by forMine** [zeit/next.js#4583] opened 2018-06-11 07:50 UTC
I deleted the node_modules directory and reinstalled it, then I met this problem
 how can I make it works correctly, please help me

**Comment by HPieters** [comment] 2018-06-11 08:18
@forMine I suspect your package.json did not have exact versions and that by reinstalling the node modules you have installed a version of a package that is incompatible with your source code. However this is a duplicate of https://github.com/zeit/next.js/issues/4227 and https://github.com/zeit/next.js/issues/4254.

**Comment by timneutkens** [comment] 2018-06-11 10:18
Yeah, it's a duplicate of mentioned issues. But this message is coming from having an incompatible `.babelrc`. #4227 gives multiple solutions to this issue.

**Closed by timneutkens** 2018-06-11 10:18 UTC
