### ISSUE TITLE
Next.js does not use production optimized modules

### ISSUE THREAD

**Issue by lifeiscontent** [zeit/next.js#9625] opened 2019-12-04 17:20 UTC
# Bug report

## Describe the bug

Everything can be found here: https://github.com/remarkjs/remark/issues/454

## To Reproduce

follow the steps in the issue, or look at the codesandbox

## Expected behavior

I'd expect IE11 not have a syntax error and expecting the same behavior of what other examples in the issue do.

## Screenshots

N/A

## System information

- OS: N/A
- Browser (if applies) N/A
- Version of Next.js: 9.1.4

## Additional context

N/A

**Comment by jamesmosier** [comment] 2019-12-05 02:07
Next does not polyfill *everything*. If a third party module is not IE11 compatible, [you have to manually polyfill it.](https://github.com/zeit/next.js/#browser-support) What do you mean by it is not using "production optimized modules"?

**Comment by lifeiscontent** [comment] 2019-12-05 02:13
@jamesmosier please read the related issues.

https://github.com/sindresorhus/is-plain-obj/issues/7
https://github.com/remarkjs/remark/issues/454

**Comment by timneutkens** [comment] 2019-12-08 12:07
Duplicate of #706

**Closed by timneutkens** 2019-12-08 12:07 UTC

**Comment by balazsorban44** [comment] 2022-01-30 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
