### ISSUE TITLE
Request: Example for implement redux-toolkit with next.js

### ISSUE THREAD

**Issue by dananw** [zeit/next.js#11097] opened 2020-03-16 07:51 UTC
# Example request
implement [redux-toolkit](https://redux-toolkit.js.org/) with next.js

## Describe the solution you'd like
A detailed example how to properly implement [redux-toolkit](https://redux-toolkit.js.org/) with next.js

edited: 
simple implement  next js with redux toolkit
https://github.com/dananw/next-with-redux-toolkit

**Comment by apollonian** [comment] 2020-04-05 18:02
We have a https://github.com/zeit/next.js/tree/canary/examples/with-redux-toolkit example now.
Please close the issue unless there's more to it @dananw or let me know if I could help.

**Closed** 2020-04-06 08:55 UTC
Labels: good first issue, help wanted

**Comment by vladislav-puzyrev** [comment] 2020-11-27 10:05
This example does not create a store on the server side, can you please add this to it?  It would also be cool if it was in typescript. I'm trying to translate the with-redux example to redux-toolkit and can't output the type for state https://github.com/vercel/next.js/tree/canary/examples/with-redux

**Comment by onopko81** [comment] 2020-12-28 10:32
@apollonian how convert this example (https://github.com/zeit/next.js/tree/canary/examples/with-redux-toolkit ) for serverside?

**Comment by cbdeveloper** [comment] 2021-04-13 11:20
Any news on this? I'm just starting with Next.js and Redux (using toolkit) and I'm having a hard time sorting this out.

**Comment by bogodars** [comment] 2021-06-22 09:37
> @apollonian how convert this example (https://github.com/zeit/next.js/tree/canary/examples/with-redux-toolkit ) for serverside?

+ 1 to this request.

**Comment by balazsorban44** [comment] 2022-01-27 15:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
