### ISSUE TITLE
Unexpected Token Error but when adding script to _app _document

### ISSUE THREAD

**Issue by skdigital** [zeit/next.js#8891] opened 2019-09-28 12:52 UTC
# Bug report

## Describe the bug

- Unexpected Token Error

## To Reproduce

1. add the followings script to either the next/head component in _app.js or _document.js. 

```javascript
 <script type="text/javascript">
var $zoho=$zoho || {};$zoho.salesiq = $zoho.salesiq || 
{widgetcode:"f589f59481ce309ac19d5af4c8559db208871444ed36899ac8a2b22830d6940c", values:{},ready:function(){}};
var d=document;s=d.createElement("script");s.type="text/javascript";s.id="zsiqscript";s.defer=true;
s.src="https://salesiq.zoho.eu/widget";t=d.getElementsByTagName("script")[0];t.parentNode.insertBefore(s,t);d.write("<div id='zsiqwidget'></div>");
</script>
```

## Expected behavior

1. I add the script as per the instructions on Zoho.
2. Everything just works as intended as the head/next component is supposed to accept script files.
2. No Unexpected Token Errors in the in the console.
4. The chat box appears at the bottom of my page.

## Additional context

I posted this questionon spectrum.chat but no-one replied and I am running out of time and options so I am posting here hoping for a response or solution. 

I am using Zoho crm and related services, the script is for a chat app. They have given the following instructions to me.

_To start using SalesIQ, you need to add this code in all the pages of your website.
Copy and paste this code right before the closing </body> tag of your website's HTML source code.
Note: If you wish to add a live chat widget on your website make sure to check the Add Live Chat option below the code._

**Comment by ijjk** [comment] 2019-09-28 14:06
Hi, it looks like you need to use `dangerouslySetInnerHTML` here since [React escapes the characters by default](https://reactjs.org/docs/introducing-jsx.html#jsx-prevents-injection-attacks)

New snippet:
```jsx
<script dangerouslySetInnerHTML={{ 
  __html: `var $zoho=$zoho || {};$zoho.salesiq = $zoho.salesiq || 
{widgetcode:"f589f59481ce309ac19d5af4c8559db208871444ed36899ac8a2b22830d6940c", values:{},ready:function(){}};
var d=document;s=d.createElement("script");s.type="text/javascript";s.id="zsiqscript";s.defer=true;
s.src="https://salesiq.zoho.eu/widget";t=d.getElementsByTagName("script")[0];t.parentNode.insertBefore(s,t);d.write("<div id='zsiqwidget'></div>");` 
}} />
```

Closing since the above should resolve this. Feel free to reply with additional details if you're still having trouble.

**Closed by ijjk** 2019-09-28 14:06 UTC

**Comment by skdigital** [comment] 2019-09-28 14:16
where do I place this snippet?

**Comment by skdigital** [comment] 2019-09-28 16:49
Its working! thank you... however where is best to place such a script, in the _app.js or _document.js?

**Comment by jmayergit** [comment] 2021-02-19 02:30
@skdigital you can place wherever you'd like as for what's best that depends on what pages the script is used. Multiple <heads> on different routes are fine. Thanks for your original question - it solved my issue 👍

**Comment by balazsorban44** [comment] 2022-01-28 17:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
