### ISSUE TITLE
Router.beforePopState not firing

### ISSUE THREAD

**Issue by jsve** [zeit/next.js#4809] opened 2018-07-20 11:04 UTC
# Bug report
I'm unable to get beforePopState trigger.

## Describe the bug
As above. Never seems to trigger.

## To Reproduce

As described in #4289, after it was closed, this seems to be broken again. I'm at 6.1.1-canary-2. I'm using the example from the readme.md in my _app.js (in componentDidMount()). Successfully using Router.events though.

UPDATE:
Put this in _app.js (from readme.md):
```
Router.beforePopState(({ url, as, options }) => {
      console.log('state popped')
      if (as !== "/" || as !== "/other") {
        // SSR-render the specified location. (Should 404)
        window.location.href = as;
        return false;
      }

      return true;
    });
```

click Links or run Router.push() on other pages / in component. Routing executes as expected, but 'state popped' never triggers.

## Expected behavior
Expecting 'state poppes' to be logged to console.

## Screenshots
-

## System information
 - OS: macOS
 - Browser:Chrome &  Safari
 - Version of Next.js: 6.1.1

## Additional context
-

**Comment by jsve** [comment] 2018-07-20 11:53
updated original post. hope this clarifies.

**Comment by uuau99999** [comment] 2018-07-28 01:13
I've encountered this issue too. I also registered listener in onRouteChangeStart but it fired as expected. I just need to intercept the url change and is there an alternative way to do this? My next.js version is 6.0.3.

**Comment by JFranciscoRader** [comment] 2018-08-01 20:13
Same behaviour found also on _app.js

**Comment by mbavio** [comment] 2018-08-02 04:17
+1. I'm having the same issue.

**Comment by HaNdTriX** [comment] 2018-08-08 11:28
@jsve Please add a full, but minimal reproduction example.

**Comment by timneutkens** [comment] 2018-08-08 16:05
Going to close this.

**Closed by timneutkens** 2018-08-08 16:05 UTC

**Comment by jsve** [comment] 2018-08-08 16:09
So it's working in the new canary?

**Comment by HaNdTriX** [comment] 2018-08-08 16:18
@jsve we can't tell, since we still haven't an example to reproduce this.

**Comment by mbavio** [comment] 2018-08-08 16:28
Why was this issue closed?

**Comment by HaNdTriX** [comment] 2018-08-08 18:07
I could not reproduce your issue. The `Router.beforePopState` is working fine from my point of view.
I believe you misused the `Router.beforePopState` function. But I can't tell and help you because saying:

> Put this in _app.js (from readme.md):

is just not enough information. Please don't just copy and paste stuff. 

- Where exactly did you put the function?
- Did you got an error message?
- Did you read the [popstate documentation](https://developer.mozilla.org/en-US/docs/Web/Events/popstate)?
- Learn Markdown

For others looking at this thread please note the following:

> Note that just calling history.pushState() or history.replaceState() **won't trigger** a popstate event. The popstate event will be triggered by doing a browser action such as a click on the back or forward button (or calling history.back() or history.forward() in JavaScript).

[Source](https://developer.mozilla.org/en-US/docs/Web/Events/popstate)

**Comment by simon998yang** [comment] 2018-08-22 07:37
why was this issue closed? I 'm having same issue.

**Comment by timneutkens** [comment] 2018-08-22 07:44
To fully explain, @HaNdTriX's comment says it all. The reproduction says "click links" or use "Router.push", but popstate is only triggered when using the `back` button of your browser. When using the back button everything works fine.

**Comment by jsve** [comment] 2018-08-22 08:05
@HaNdTriX and @timneutkens are correct.

I believe the documentation could be _much_ clearer on what is going on, and the Zeit-representatives could be a bit more reasonable in their (now deleted) responses. However, this is not a bug.

**Comment by wq93** [comment] 2019-04-16 10:06
why was this issue closed? I 'm having same issue.

**Comment by HaNdTriX** [comment] 2019-04-16 15:16
@wq93 please read https://github.com/zeit/next.js/issues/4809#issuecomment-411499411

**Comment by wq93** [comment] 2019-04-17 08:47
Then I want to enter a route, do some judgment, return the ture release, return false interception, what should I do?

**Comment by asyncb** [comment] 2019-05-16 20:24
What about anchor tags, event handlers, SEO, and W3C standards?

**Comment by asyncb** [comment] 2019-05-16 21:05
https://github.com/zeit/next.js/#router-events
- routeChangeStart(url) - Fires when a route starts to change
- routeChangeComplete(url) - Fires when a route changed completely
- routeChangeError(err, url) - Fires when there's an error when changing routes
- beforeHistoryChange(url) - Fires just before changing the browser's history
- hashChangeStart(url) - Fires when the hash will change but not the page
- hashChangeComplete(url) - Fires when the hash has changed but not the page

**Comment by asyncb** [comment] 2019-05-16 21:20
```
componentDidMount() {
  console.log(Router);
  Router.events.on('routeChangeStart', (a, b, c) => {
    console.log('routeChangeStart', a,b,c)
    throw new Error('this works');
    // return false;
  });
}
```

**Comment by sant3001** [comment] 2019-06-11 01:46
+1 on this bug

**Comment by hellobq** [comment] 2019-07-16 06:40
```
// _app.js
componentDidMount() {
    Router.events.on('routeChangeComplete', () => {
      console.log('complete');
    })

    Router.beforePopState(({url, as, opts}) => {
      console.log('_app.js beforePopState');
      console.log(url, as, opts);
      return true;
    });

    Router.events.on('routeChangeStart', url => {
      console.log('start');
    });
}
```

**question**: `beforePopState` cannot listen to route jumps implemented by Link

**Comment by cyberspacedk** [comment] 2019-08-07 07:41
> https://github.com/zeit/next.js/#router-events
> 
> * routeChangeStart(url) - Fires when a route starts to change
> * routeChangeComplete(url) - Fires when a route changed completely
> * routeChangeError(err, url) - Fires when there's an error when changing routes
> * beforeHistoryChange(url) - Fires just before changing the browser's history
> * hashChangeStart(url) - Fires when the hash will change but not the page
> * hashChangeComplete(url) - Fires when the hash has changed but not the page
> 
> ```
> componentDidMount() {
>   Router.events.on('routeChangeStart', url => {
>     this.props.showConfirmDialog('Are you sure?');
>     throw new Error('this works');
>   });
> }
> ```

hmm, in that case, how can i unsubscribe ?
```js
 handleInterceptEventOn = (url) => {
    this.setState({ requestedUrl: url, showModal: true });
    throw new Error('this works');
  };

componentWillUnmount(){
 Router.events.off('routeChangeStart', this.handleInterceptEventOn);
}
```
when componentWillUnmount launch, the function thow an Error

**Comment by jasonhoo95** [comment] 2020-05-05 02:13
```
componentDidMount() {
    Router.events.on('routeChangeStart', (url) => {
      alert('route changes');
    });
    Router.beforePopState(({ url, as, opts }) => {
      alert('before pop state');
      return true;
    });
  }

```
Hi can I ask why my router.beforepopstate is not firing at all..?

**Comment by kartikag01** [comment] 2021-05-30 15:28
I change from `router.beforePopState` to `Router.beforePopState` from `import Router from "next/router"` and it worked for me.
don't know the difference in router api, when to use `const router = useRouter();` or when to directly use `Router.beforePopState`.
but as per docs (https://nextjs.org/docs/api-reference/next/router#usage-3) they says, to use hook `useRouter`

**Comment by balazsorban44** [comment] 2022-01-28 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
