### ISSUE TITLE
with-react-i18next example

### ISSUE THREAD

**Issue by lifeiscontent** [zeit/next.js#4043] opened 2018-03-22 14:21 UTC
@jamuhl Hi,

I tried using your with-react-i18next example with typescript. It's giving me errors. Do you think you could help me debug?

here's my gist: https://gist.github.com/lifeiscontent/f23b5ea2221f11f8f0cfc11a0764e01f

and I'm getting the error: `Cannot read property 'resourceStore' of undefined`

I think it may be due to how you were using a i18nInstance and the i18next module.

**Comment by jamuhl** [comment] 2018-03-22 14:32
caused by this line: https://gist.github.com/lifeiscontent/f23b5ea2221f11f8f0cfc11a0764e01f#file-i18n-ts-L38

looks like you render before init was called.

**Comment by lifeiscontent** [comment] 2018-03-22 15:35
@jamuhl I think it might be something deeper. I'm thinking the way react-i18next is exported isn't done properly for both the client and the server to consume the files in a proper manner.

**Comment by lifeiscontent** [comment] 2018-03-22 15:35
the fact that in your example you have to use i18next.default in the export is what leads me to believe it.

**Comment by jamuhl** [comment] 2018-03-22 16:59
server is node.js and will use the commonjs build...while client depending on what gusto of build tool it uses uses a umd or es6 build...

**Comment by kachkaev** [comment] 2018-04-12 06:41
I think the problem is that you are passing `i18n`, not `i18n.I18n` here: https://gist.github.com/lifeiscontent/f23b5ea2221f11f8f0cfc11a0764e01f#file-withi18next-L5-L8
The argument needs to be a class.

I also spent quite a lot of time chasing this issue and refactored the example in this PR: https://github.com/zeit/next.js/pull/3959

More specifically, see this line: https://github.com/zeit/next.js/pull/3959/files#diff-d60fa1ce8485089e8383d76b6033d1ecR5

**Comment by markolofsen** [comment] 2018-06-29 12:16
Something like that?
```
import { translate } from 'react-i18next';
import { I18n } from '../i18n'
translate.setI18n(I18n);
...
export default withRoot(translate(['home', 'common'], { wait: true })(withStyles(styles)(Index)));
```

**Comment by vjpr** [comment] 2018-08-01 14:03
@kachkaev I am using the Next.js example, and I cannot figure out how the translations are loaded during an SSR.

Where does `req.i18n` get set?

At what point does `req.i18n.services.resourceStore.data` get filled?

**Comment by kachkaev** [comment] 2018-08-01 14:11
`i18n` and `i18nInstance` may not be the same depending on how you resolve modules, which is worth noting if you want your code to work both in SSR and on the client. Not sure about other questions though – I'm not an expert in next.js and i18next :(

**Comment by vjpr** [comment] 2018-08-01 14:28
My issue was that I am using `koa`, and `koa-i18next-middleware`, which attaches `i18n` to `ctx.request`, instead of `ctx.req` from the example.

Currently, `withI18Next` is coupled to Express. This should be changed.

```
    const i18nInitialProps = ctx.request
      ? getInitialProps(ctx.request, namespaces)
      : await loadNamespaces({
          components: [{props: {namespaces}}],
          i18n,
        })
```

**Comment by jamuhl** [comment] 2018-08-01 14:53
cloneInstance is run to assert you get a fixed language for that request (avoiding async mixup of languages).

req.i18n gets set in the middleware.handler (at least for express)

resourceStore.data gets set via (fs) backend on init

**Comment by jamuhl** [comment] 2018-08-01 14:55
i18n and i18nInstance is something i never experienced myself -> might be more a typescript issue

**Comment by jamuhl** [comment] 2018-10-17 09:04
@timneutkens i guess this can be closed - solved in https://github.com/i18next/react-i18next/tree/master/example/nextjs (which get merged back to here soon)

**Comment by timneutkens** [comment] 2018-10-17 11:09
You're on 🔥 @jamuhl ❤️

**Closed** 2018-10-17 11:08 UTC
