### ISSUE TITLE
False positive report of "API resolved without sending a response" in latest canary again

### ISSUE THREAD

**Issue by ReTWi** [zeit/next.js#10518] opened 2020-02-13 15:30 UTC
# Bug report

## Describe the bug

Api endpoint

Next will log the "API resolved without sending a response" warning even though the API endpoint always send a response back.

## To Reproduce
```
export default async function(req: NextApiRequest, res: NextApiResponse) {
  const fn = async () => {
    // if this part will be deleted, error is gone
    await fetch('https://example.com', {
      credentials: 'include'
    })

    res.json({1:1})
    return false
  }

  if (!(await fn())) return
}
```
## Expected behavior

No warning

## System information

OS: Windows 10
Version of Next.js: v9.2.2-canary.18

## Additional context

#10439

**Comment by ijjk** [comment] 2020-02-26 16:11
Hi, I'm not able to reproduce this on the latest canary of Next.js `9.2.3-canary.12`

![Kapture 2020-02-26 at 10 09 18](https://user-images.githubusercontent.com/22380829/75363738-2818e600-5880-11ea-8961-223758f64115.gif)

I'm going to close this since it appears to be working correctly. If you are still seeing this, please reply with additional info so it can be investigated

**Closed by ijjk** 2020-02-26 16:11 UTC

**Comment by balazsorban44** [comment] 2022-01-30 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
