### ISSUE TITLE
Add a configuration option to specify what directory separator is used when building

### ISSUE THREAD

**Issue by ZakFahey** [zeit/next.js#5843] opened 2018-12-09 02:17 UTC
# Feature request

I'm writing a Next app on Windows and deploying it on Elastic Beanstalk. The deployment process involves running `next build` locally and then deploying the necessary files along with the `.next` folder to Elastic Beanstalk. However, this isn't possible since the files in the `.next` build folder use os-specific directory separators, making any build from a Windows machine incompatible with one on a Linux machine.

~What I'd like to see done is have a configuration option that would allow you to specify the directory separator used in build files to either the system default, `/`, or `\`.~ or preferrably, replace the directory separators at runtime to support the build in any operating system.

While running `next build` is still an option, I've personally had issues with permissions doing while building locally works, that is, after manually changing all the directory separators in the config files in the `.next` folder.

EDIT: after posting this last night, I thought it over and realized that just making the changes at runtime when parsing the build folder would be more user intuitive.

**Comment by timneutkens** [comment] 2018-12-09 23:07
Duplicate of #4920

**Closed by timneutkens** 2018-12-09 23:07 UTC
