### ISSUE TITLE
Sourcemap support?

### ISSUE THREAD

**Issue by bliitzkrieg** [zeit/next.js#2925] opened 2017-09-08 15:32 UTC
Does nextJS provide sourcemaps for dev? I added a debugger statement to my code and when It breaks in console, it just shows null as my code.

![issue](http://i.imgur.com/LhvEbNj.png)

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

The sourcemap should be used and my actual code should show

## Current Behavior

See above

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Context

Makes debugging really challenging

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     3.2.1    |
| node    |   8.4.0      |
| OS      |     Win 10 Pro    |
| browser |     Chrome Version 61    |
| etc     |         |

**Comment by timneutkens** [comment] 2017-09-08 18:05
Duplicate of https://github.com/zeit/next.js/issues/2915 I'll ask Arunoda to do a release ❤️

**Closed by timneutkens** 2017-09-08 18:05 UTC
