### ISSUE TITLE
What is the best way to use external CSS resources?

### ISSUE THREAD

**Issue by voronianski** [zeit/next.js#117] opened 2016-10-27 18:00 UTC
I'm trying out next.js but for my specific needs I want to use external CSS file, e.g. from CDN. It's utility belt which provides a lot of useful classes in the app. I've tried adding it in `Head` component like:

```js
import React from 'react';
import Head from 'next/head';

export default () => (
  <div>
    <Head>
      <link href="//unpkg.com/contrabass.css@1.0.4/dist/contrabass.min.css" rel="stylesheet" />
    </Head>
  </div>
);
```

but everytime when switching between pages with `Link` element I see styles blinking - I assume due to loading this css file after the page rendered.

I've also tried to load CSS once when returned from server like:

```js
function addExternalCSS (href, id, media = 'all') {
  if (document.getElementById(id)) {
    return;
  }

  const head  = document.getElementsByTagName('head')[0];
  const link  = document.createElement('link');

  link.id   = id;
  link.rel  = 'stylesheet';
  link.type = 'text/css';
  link.href = href;
  link.media = media;

  head.appendChild(link);
}

(function () {
  if (typeof document === 'undefined') {
    return;
  }

  addExternalCSS('//unpkg.com/contrabass.css@1.0.4/dist/contrabass.min.css', 'contrabass');
})();
``` 

But this approach has downside on big initial styles blink due to waiting while file is downloaded and parsed by browser.

Do you have some pieces of advice how to work with external CSS files and do not have these weird style blinks?

**Comment by dlindenkreuz** [comment] 2016-10-27 18:23
Duplicate of #95

**Closed** 2016-10-28 04:12 UTC
Labels: duplicate
